### PR TITLE
[docs] Virtual version must use cci. as prefix

### PR DESCRIPTION
**Pull request by uilianries**
Update FAQs: Now cci. prefix is described as mandatory for non-official versions.

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
we suggest to use `cci.<date>` in several cases:
- libraries which aren't doing official releases (or tags, snapshots, etc.) at all
- libraries that didn't do releases for a long time, but people need to use newer source code (with new features, bug fixes, etc.). NOTE : such libraries might be still in active development, just release didn't happen yet and not planned/expected in the nearest time (e.g. if library is about to release in few days, it might be better to wait rather introducing unofficial CCI-specific snapshot)
- libraries which were abandoned, with no active development, but still used/requested

how to choose what to use?
- if library is doing any sort of releases, then use that releases. the library might use version numbers, roman numbers, source control revisions, letters, code names, dates, etc. to indicate releases - just use whatever library uses (without cci. prefix), any versioning scheme is accepted
- if the library isn't doing releases, but has tags in its version control system (e.g. on GitHub, GitLab, BitBucket, GoogleCode, SourceForge, etc. or just in their own git/hg/svn/csv/bazaar/etc server), use that tags
- if the library isn't doing releases and tags, but provides snapshots (tarballs) on HTTP/FTP/whatever server, such as nightly/daily/whatever snapshots, use them
- if the library isn't doing anything of the above, grab **some** source and label it with date and cci. prefix, try to record the revision number (if possible). also, try to identify a stable source, e.g. if there are multiple branches in source control, try to identify the stable one (it might be `master`, `trunk`, `main`, `default`, `stable`, etc.). try to reach to developers when in doubt. if they provide some sort of instruction on how to get stable sources, follow it. even within stable branch, it might be hard to pick the right revision within that branch. if library is/was doing CI, try to get revision which passed CI. otherwise, if library provides a test suite, try to choose revision which passes test suite. otherwise, try to manually check some typical scenario to ensure at least basic level of stability.
- some libraries (especially ancient, public domain) aren't hosted in source control, they don't appear to have any history, just provided as-is somewhere. in that case, try to check if there is a date or version in header file. try to find out the date code was published. if nothing was found, just get today's date with cci. prefix.

**Comment by jgsogo** [comment]
Probably some comments from @SSE4 could be added to the docs, wdyt? It can be in this PR or another one in the near future.

**Comment by jgsogo** [comment]
I've merged this one, a new issue with the comment by @SSE4  is added in #2471

**Comment by Croydon** [comment]
I agree with the unification of `<date>` and `cci.<date>` 

It would have been confusing for most people what the difference is and it is a good point that projects can start to do releases in the future, which then would cause another irregularly. 

Thanks @jgsogo for the ping 😄  (despite that I have only seen that now since the amount of my GitHub notifications are overwhelming).

**Pull request merged**
