### PR TITLE
sqlite3: add more configurations

### PR DESCRIPTION
**Pull request by timblechmann**
this patch enables 3 sqlite options, that i used in my projects in the
past.

compare https://www.sqlite.org/compile.html for details

Specify library name and version:  **sqlite3/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by timblechmann** [comment]
btw, how do i try a build locally when the recipe supports multiple versions like the sqlite3 recipe does?

**Comment by uilianries** [comment]
> btw, how do i try a build locally when the recipe supports multiple versions like the sqlite3 recipe does?

@timblechmann You can use a Conan docker image to avoid extra storage in your environment. Use a simple for range loop + conan create command the validate. Anyway, the CCI bot will validate all profiles and the current status is okay

**Comment by timblechmann** [comment]
@uilianries my question might be a little more stupid: how can i specify the version?

```
20:41 $ conan create . "sqlite3/3.23.3"
ERROR: conanfile didn't specify version
```

**Comment by ericLemanissier** [comment]
you can try `conan create . "sqlite3/3.23.3@"`

**Comment by timblechmann** [comment]
hmm:

```
20:46 $ conan create . "sqlite3/3.23.3@"
[HOOK - conan-center.py] pre_export(): [DEPRECATED GLOBAL CPPSTD (KB-H001)] OK
[HOOK - conan-center.py] pre_export(): [REFERENCE LOWERCASE (KB-H002)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE METADATA (KB-H003)] OK
[HOOK - conan-center.py] pre_export(): [HEADER_ONLY, NO COPY SOURCE (KB-H005)] OK
[HOOK - conan-center.py] pre_export(): [FPIC OPTION (KB-H006)] OK
[HOOK - conan-center.py] pre_export(): [VERSION RANGES (KB-H008)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] Total recipe size: 13.0029296875 KB
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] OK
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: ['CMakeLists.txt']
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE FOLDER (KB-H024)] OK
[HOOK - conan-center.py] pre_export(): [META LINES (KB-H025)] OK
[HOOK - conan-center.py] pre_export(): [CONAN CENTER INDEX URL (KB-H027)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE MINIMUM VERSION (KB-H028)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - RUN ENVIRONMENT (KB-H029)] OK
[HOOK - conan-center.py] pre_export(): [SYSTEM REQUIREMENTS (KB-H032)] OK
[HOOK - conan-center.py] pre_export(): [CONANDATA.YML FORMAT (KB-H030)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO IMPORTS() (KB-H034)] OK
[HOOK - conan-center.py] pre_export(): [NO AUTHOR (KB-H037)] OK
[HOOK - conan-center.py] pre_export(): [NO TARGET NAME (KB-H040)] OK
[HOOK - conan-center.py] pre_export(): [NO FINAL ENDLINE (KB-H041)] OK
[HOOK - conan-center.py] pre_export(): [NO REQUIRES.ADD() (KB-H044)] OK
[HOOK - conan-center.py] pre_export(): [DELETE OPTIONS (KB-H045)] OK
[HOOK - conan-center.py] pre_export(): [NO ASCII CHARACTERS (KB-H047)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERBOSE MAKEFILE (KB-H046)] OK
Exporting package recipe
sqlite3/3.23.3 exports: File 'conandata.yml' found. Exporting it...
sqlite3/3.23.3 exports: Copied 1 '.yml' file: conandata.yml
sqlite3/3.23.3 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] Saving conandata.yml: {}
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] New conandata.yml contents: {}

[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
sqlite3/3.23.3: A new conanfile.py version was exported
sqlite3/3.23.3: Folder: /home/tim/.conan/data/sqlite3/3.23.3/_/_/export
sqlite3/3.23.3: Exported revision: dd18b513ca972e3031a698fd162933f6
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

sqlite3/3.23.3: Forced build from source
sqlite3/3.23.3 (test package): Installing package
Requirements
    sqlite3/3.23.3 from local cache - Cache
Packages
    sqlite3/3.23.3:0ea13fbeff7afbe2f19b5c349acf59a585a00e93 - Build

Installing (downloading, building) binaries...
[HOOK - conan-center.py] pre_source(): [IMMUTABLE SOURCES (KB-H010)] OK
sqlite3/3.23.3: Configuring sources in /home/tim/.conan/data/sqlite3/3.23.3/_/_/source
ERROR: sqlite3/3.23.3: Error in source() method, line 67
        tools.get(**self.conan_data["sources"][self.version])
        KeyError: 'sources'
```

**Comment by ericLemanissier** [comment]
well, as 3.23.3 does not exist, I bet you wanted to use 3.32.3 instead

**Comment by timblechmann** [comment]
ah, stupid me :grimacing: thanks for walking me through!

**Pull request merged**
