### PR TITLE
xorg/system: Add xcb-dri2, xcb-dri3, xcb-glx, and xcb-present

### PR DESCRIPTION
**Pull request by jwillikers**
Specify library name and version:  **xorg/system**

Motivation: https://github.com/conan-io/conan-center-index/pull/20502#issuecomment-1757742671

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
What's motivating this addition ?
opensuse does not seem to have this `libxcb-glx0-devel` package https://github.com/bincrafters/system-packages-checks/actions/runs/6478450515/job/17590277231#step:5:197

**Comment by jwillikers** [comment]
> What's motivating this addition ? opensuse does not seem to have this `libxcb-glx0-devel` package https://github.com/bincrafters/system-packages-checks/actions/runs/6478450515/job/17590277231#step:5:197

Sorry, my bad. It must be in the default `libxcb-devel` package, which is true for most distributions, just not Debian.

Um, well, I'm working on a Conan package for Mesa and these libraries are required to build the X11 support.

**Comment by jwillikers** [comment]
It would be nice if there was a way to incorporate packages only on newer versions of Ubuntu which support them.

**Review by ericLemanissier — APPROVED** [review]
LGTM, All distros passed on https://bincrafters.github.io/system-packages-checks/ except:
- centos but it's caused by an already existing problem `Error: Unable to find a match: xcb-util-cursor-devel` https://github.com/bincrafters/system-packages-checks/actions/runs/8096808696/job/22126465695#step:5:137
- FreeBSD, but it's caused by an already existing problem `uuid.pc was not found in the pkg-config search path.` https://github.com/bincrafters/system-packages-checks/actions/runs/8096808696/job/22126436939#step:3:49132

**Pull request merged**
