### PR TITLE
[boost][minor improvement]: Convert boost default options to dict

### PR DESCRIPTION
**Pull request by david-sinuela-pix4d**
Specify library name and version:  **boost/***

Minor improvement, use a dict to declare default options.

### CODE REVIEW

**Comment by david-sinuela-pix4d** [comment]
@jgsogo I already did in https://github.com/conan-io/conan-center-index/issues/4#issuecomment-564992442, do I need to do anything else?

**Comment by danimtb** [comment]
@david-sinuela-pix4d you are now part of the EAP! Sorry for the delay. I have relaunched the CI

**Comment by david-sinuela-pix4d** [comment]
Hi, is there anything preventing this being merged?

**Comment by Morwenn** [comment]
This PR was superseded by #569 apparently, I think it can be closed.

**Comment by Croydon** [comment]
Oh, sorry 🙈 

I upvoted this PR and totally forgot its existent so I indeed solved this in #569

**Comment by jgsogo** [comment]
It's been also our fault merging that one before this 😞  we try to be respectful with a FIFO queue, but sometimes is really hard to be aware of all the PRs and reviews.

Anyway, thanks a lot @david-sinuela-pix4d for submitting this PR, and your contributions to the EAP of conan-center-index. I've seen you have a couple of PRs waiting, let's focus on them 😉

**Comment by david-sinuela-pix4d** [comment]
@jgsogo no worries, happy that the change got merged anyway.

**Pull request closed without merging**
