### PR TITLE
bshoshany-thread-pool: add version 4.0.0

### PR DESCRIPTION
**Pull request by bshoshany**
Specify library name and version:  **bshoshany-thread-pool/4.0.0**

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Thanks! :)

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]
Thanks a lot for ensuring the lib stays up-to-date :)

**Review by ericLemanissier — APPROVED** [review]

**Comment by bshoshany** [comment]
Update: There was an issue with v4.0.0, so since the changes have not been committed yet, I'm just skipping it and going straight to v4.0.1 which fixes that issue (if that's okay).

**Comment by bshoshany** [comment]
Hey, I just wanted to ask when this PR is scheduled to be merged?

**Review by toge — APPROVED** [review]

**Comment by bshoshany** [comment]
Hey @toge @ericLemanissier @RubenRBS @jcar87, it's been more than 3 weeks and this PR has still not been merged, which means Conan users cannot update to the latest version of my package. All the checks have passed, so I don't see why it should not be merged right now. Maybe force pushing the update to v4.0.1 created some kind of issue with the PR? Should I close this and create a new PR instead? Thanks!

**Review by ericLemanissier — APPROVED** [review]
FYI, PRs which only adds new versions to conandata.yml and config.yml are automatically merged without approvals(if no other file is modified)

**Comment by bshoshany** [comment]
Thanks for the information! I had to change the test program because the API was changed in v4.x.x and is now incompatible with v3.x.x, so I guess that's why it is taking longer than usual? Also, right now it says there is still 1 pending review.

**Comment by bshoshany** [comment]
Hey @toge @ericLemanissier @RubenRBS @jcar87, I really hate to keep bothering you about this, but it's now been a full month since I submitted this PR, and it has not been merged yet.

This means Conan users are still unable to update to the latest version of my package.

The PR is very simple and consists of simply adding the new version to `conandata.yml` and `config.yml` and simplifying the test program `test_package.cpp` so it can work both with v3.x.x and v4.x.x.

It also passed all 43 checks successfully. Therefore, I wonder if it would be possible to finish the review process and merge this PR soon?

Thanks again, and sorry for the trouble!

**Comment by toge** [comment]
@bshoshany 
Unfortunately, I am a community reviewer and my review does not meet the merge requirements.

> At least 2 approving reviews are required, and at least one of them has to be from the official reviewers. So, it might be 1 official + 1 community, or 2 official, but it couldn't be just 2 community reviews.
https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md#getting-your-pull-request-reviewed

With over 600 PRs at this point, all we can do is patiently wait for the Official Reviewers to review them.

**Comment by RubenRBS** [comment]
Hi @bshoshany sorry about the lack of review from our side for so long, as @toge mentioned, the amount of PRs we have to deal with means that some of them get unintentionally left behind. I'm approving this now, thanks a lot for your patience :)

**Review by RubenRBS — APPROVED** [review]

**Comment by bshoshany** [comment]
@toge and @RubenRBS, thank you so much for the explanation, and for approving my PR. 600 PRs is definitely a lot to deal with! I really appreciate the work you put into this extremely useful tool.

**Pull request merged**
