### PR TITLE
pipes: move checks to `validate()` instead of `configure()` and add msvc min version

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
I've won the race to post the build results against the bot, here are the v2 errors https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/20369/1-linux-gcc/pipes/1.0.0//summary.json

**Comment by SpaceIm** [comment]
I would restore hardcoded CMAKE_CXX_STANDARD 14 in test package just to pass pipeline. But it seems that this header-only lib doesn't work with C++17...

**Comment by RubenRBS** [comment]
Oh that's a pitty that it can't compile in C++17 - I'm ok having a check for max_cppstd in the validate too even if it then only creates binaries for msvc

**Review by jwillikers — APPROVED** [review]

**Review by valgur — APPROVED** [review]

**Review by jcar87 — DISMISSED** [review]

**Review by RubenRBS — APPROVED** [review]

**Review by uilianries — DISMISSED** [review]
LGTM.

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
