### PR TITLE
add openssl/1.1.1k

### LINKED ISSUE #5053: [request] <openssl>/<1.1.1k>
### Package Details
  * Package Name/Version: openssl/1.1.1j
  * Changelog: https://www.openssl.org/news/openssl-1.1.1-notes.html

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

### PR DESCRIPTION
**Pull request by Croydon**
Specify library name and version:  **openssl/1.1.1k**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

___________________

https://www.openssl.org/news/changelog.html#openssl-111

Closes #5053

### CODE REVIEW

**Comment by prince-chrismc** [comment]
New fpic rules 

```
[HOOK - conan-center.py] pre_build(): ERROR: [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not managed correctly. Please remove it for shared option: del self.options.fpic (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H007) 
openssl/1.1.1k: ERROR: Package 'b614d3b31d5e8feba6472fe56ecfe9a6fec1dbe7' build failed
```

**Comment by Croydon** [comment]
Let's merge #5026 first

**Comment by SSE4** [comment]
> Let's merge #5026 first

we can't, it is failed

**Comment by Croydon** [comment]
Yes, but it shouldn't be hard to fix. We can wait a bit 😄

**Comment by SSE4** [comment]
> Yes, but it shouldn't be hard to fix. We can wait a bit 😄

#5026 is green now. please approve.

**Comment by SSE4** [comment]
@Croydon #5026 has been merged. could you rebase?

**Comment by prince-chrismc** [comment]
Please also link #5053

**Review by prince-chrismc — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
