### PR TITLE
qt: use upstream package folder architecture

### PR DESCRIPTION
**Pull request by ericLemanissier**
blocked by https://github.com/conan-io/hooks/pull/540
fixes https://github.com/conan-io/conan-center-index/issues/23660

Specify library name and version:  **qt/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9028845436/attempts/1)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9028845436/attempts/2)

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@kambala-decapitator can you please try with this recipe and tell us if it solves your problem on android ? thanks !

**Comment by kambala-decapitator** [comment]
@ericLemanissier will check tomorrow

**Comment by kambala-decapitator** [comment]
weird, removing `-o 'qt/*:essential_modules=False'` got me through. But with that option on it builds not just qtbase (e.g. qtdeclarative) which is not something I want. Do I need to skip qtdeclarative explicitly?

And qtdeclarative build fails with an error that doesn't make much sense:
```
/Users/kambala/.conan/data/qt/5.15.13/_/_/source/qt5/qtdeclarative/src/quick/items/qquicktextcontrol.cpp:328:18: error: no member named 'setMarkdown' in 'QTextDocument'
            doc->setMarkdown(text);
            ~~~  ^
```

https://bugreports.qt.io/browse/QTBUG-121530 although that's for Qt 6

**Comment by kambala-decapitator** [comment]
passing `-o 'qt/*:qtdeclarative=False'` and/or `-o 'qt/*:config=-feature-textmarkdownreader'` gets me back to the OpenGL ES error, I'm puzzled

**Comment by ericLemanissier** [comment]
Ok, so the main problem comes from the test_package, which requires qt in the build context : https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/5.x.x/test_package/conanfile.py#L24. The markdown and ES2 problems are real, but are not related to android.
Instead of calling `conan create . qt/5.15.13@ ...` can you please call `conan export . qt/5.15.13@`, then actually build a conan recipe which requires qt, using your android profile ?

**Comment by kambala-decapitator** [comment]
thanks a lot, that worked perfectly! Used the following conanfile:
```
[requires]
qt/5.15.13@

[options]
qt/*:opengl=es2
qt/*:essential_modules=False
qt/*:with_mysql=False
qt/*:with_md4c=False
qt/*:with_odbc=False
qt/*:with_openal=False
qt/*:with_pq=False
qt/*:qttools=True
qt/*:android_sdk=/Users/kambala/dev/android/sdk

[generators]
CMakeDeps
CMakeToolchain
```

all seems good:
```
> ll /Users/kambala/.conan/data/qt/5.15.13/_/_/source/qt5/qttools/include/QtHelp/QtHelp /Users/kambala/.conan/data/qt/5.15.13/_/_/package/40b8d9e84d53fe306a170fca2a2f7448840fe0ae
-rw-rw-r--  1 kambala  staff   495B Jan 22 14:55 /Users/kambala/.conan/data/qt/5.15.13/_/_/source/qt5/qttools/include/QtHelp/QtHelp

/Users/kambala/.conan/data/qt/5.15.13/_/_/package/40b8d9e84d53fe306a170fca2a2f7448840fe0ae:
total 520
drwxr-xr-x  20 kambala  staff   640B May 14 13:52 bin/
-rw-r--r--   1 kambala  staff   7.7K May 14 13:53 conaninfo.txt
-rw-r--r--   1 kambala  staff   251K May 14 13:53 conanmanifest.txt
drwxr-xr-x   4 kambala  staff   128B May 14 13:52 doc/
drwxr-xr-x  29 kambala  staff   928B May 14 13:52 include/
drwxr-xr-x   8 kambala  staff   256B May 14 13:52 jar/
drwxr-xr-x  61 kambala  staff   1.9K May 14 13:53 lib/
drwxr-xr-x  12 kambala  staff   384B May 14 13:53 licenses/
drwxr-xr-x  79 kambala  staff   2.5K May 14 13:52 mkspecs/
drwxr-xr-x   7 kambala  staff   224B May 14 13:52 plugins/
drwxr-xr-x   4 kambala  staff   128B May 14 13:52 src/
```

**Comment by kambala-decapitator** [comment]
yes, now androiddeployqt is able to copy plugins, thanks for the fix!

**Comment by ericLemanissier** [comment]
@danimtb @czoido this is ready for review

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan-center-index/pull/24165

**Pull request closed without merging**
