### PR TITLE
libxml2: fix CMake vars in CMakeDeps & bump icu

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
@uilianries @prince-chrismc why is not automatically merged?

**Comment by danimtb** [comment]
@SpaceIm thanks for the ping. I can see it is waiting for the github actions check runs to be green. But there is no check runs actually run. I will open/close the PR to see if that makes the trick for github actions

**Comment by prince-chrismc** [comment]
I liked the CMake in the test module package name, dang it I missed that in the refactor

**Comment by SpaceIm** [comment]
It leads to long path issue on Windows agent.

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/pull/14427#issuecomment-1327865292 👍

**Pull request merged**
