### PR TITLE
Bump libgeotiff/1.7.1

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@jgsogo why CI doesn't detect a bump? Seems to be a regression. This PR doesn't change RREV of other versions.

**Comment by jgsogo** [comment]
> @jgsogo why CI doesn't detect a bump? Seems to be a regression. This PR doesn't change RREV of other versions.

Once we have started to merge automatically (without reviews) the pull-requests that are only bumping versions, we modified the logic to be a little bit more restrictive to avoid false positives. Here it is being added/modified one additional file, so it is not just adding a new version. The patch could introduce unwanted logic, so we prefer if someone reviews it manually.

**Review by jgsogo — APPROVED** [review]

**Comment by SpaceIm** [comment]
Regarding auto merge I understand and agree, but it doesn't mean that CI has to build versions for which RREV didn't change.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
