### PR TITLE
Bump/clove unit/2.4.2

### PR DESCRIPTION
**Pull request by fdefelici**
Specify library name and version:  **clove-unit/2.4.2**

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by valgur — APPROVED** [review]

**Comment by fdefelici** [comment]
Closing this pr in favor of #23875 related tò latest version of clove-unit

**Comment by RubenRBS** [comment]
Hi @fdefelici sorry about this - this PR fell thru the cracks among the rest of the PR volume, which should have not happened, I'm very sorry about that

**Comment by fdefelici** [comment]
Hi @RubenRBS, no problem.

Eventually for the future, which is the right way to report a scenario like this to your team?

**Comment by RubenRBS** [comment]
Thanks for understanding :)

Feel free to ping me if this happens again (Even though this last few months we have improved the internal processes we use so it's unlikely a version bump would be gone unseen again!)

**Pull request closed without merging**
