### PR TITLE
[bug] fontconfig: Update test_package to CMakeToolchain + CMakeDeps - not possible?

### PR DESCRIPTION
**Pull request by paulharris**
This pull request is here so I can reference it in a bugreport.

### CODE REVIEW

**Comment by paulharris** [comment]
Note: the failure happens when the profile includes:
```
[conf]
tools.cmake.cmaketoolchain:find_package_prefer_config = False
```

**Comment by uilianries** [comment]
@paulharris Thank you for reporting. Could you please open an issue to @conan-io/conan . The client manages all generators. Here we can see that is not only about the recipe, but the generator support. Regards!

**Comment by paulharris** [comment]
I did, you can see the bug referenced above.
It is also connected with conan-io/conan#11201
Would it work better if I referenced my branch from those issues, instead of using a PR ?

**Comment by uilianries** [comment]
@paulharris It's fine. At least, more people will reach to your comments easier. Just need to reference the conan issue on the PR too, otherwise, need to receive notifications from conan-io, or follow the PR to any reference listed by Github.
Thanks for sharing those information.

**Comment by paulharris** [comment]
Moved issue to conan-io/conan-center-index#10687

**Pull request closed without merging**
