### PR TITLE
fix: duckdb 0.10.1 jemalloc no longer built for non ARM Linux

### PR DESCRIPTION
**Pull request by Taepper**
Specify library name and version:  **duckdb/0.10.1**

The recipe did not build on ARM Linux.

Here is an analog change in the setup.py provided by duckdb:
https://github.com/duckdb/duckdb/commit/4a89d97db8a5a23a15f3025c8d2d2885337c2637

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — COMMENTED** [review]
Hi! Thanks a lot for taking the time to fix this

I also think this warrants some changes to the `validate()` method of the recipe to notify Conan that this combination is not possible? wdty? Pinging @uilianries too for his opiniong too :)

**Comment by uilianries** [comment]
@RubenRBS I see no direct dependency to [jemalloc/5.3.0](https://conan.io/center/recipes/jemalloc?version=5.3.0) package in this recipe 🤔 It would need more investigation to understand, but in the current condition, changing only cpp_info, looks correct to me.

**Review by RubenRBS — APPROVED** [review]
After checking with @uilianries this looks good, we got confused for a second there, sorry about the noise :)

Approving now

**Comment by corneliusroemer** [comment]
Unless I'm really misunderstanding something here, the title of the issue is wrong - it should drop the "non". It's not build for ARM anymore, not the opposite as implied by the title

> fix: duckdb 0.10.1 jemalloc no longer built for ~non~ ARM Linux

**Pull request merged**
