### PR TITLE
add cgal/5.0.3

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **cgal/5.0.3**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@uilianries @danimtb @SSE4 @jgsogo Would it be possible to also build non header_only `cgal` binaries in CI (and conan-center) like `boost` recipe?

**Comment by uilianries** [comment]
@SpaceIm CCI should generated automatically for any package: https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md

**Comment by SpaceIm** [comment]
Maybe if default value of `header_only` is True, it doesn't generate binaries for `header_only=False`? I don't know.

**Comment by jgsogo** [comment]
Yes, that's it. Option `header_only`, if present, is only added with the value `True`, it is not exploded like `shared` or `fPIC`. Here, CCI is iterating all the profiles (with the default option values) and then adding one more with `header_only=True`.

Is it important for this specific PR? If not, we can push this PR forward while we decide (I don't know if there is a reason) and implement the feature in CCI.

**Comment by SpaceIm** [comment]
Sure, let's move forward on this PR without waiting modifications in CI.

**Comment by uilianries** [comment]
@jgsogo Thanks for the explanation! I think we can add your note in docs/

**Pull request merged**
