### PR TITLE
gflags: Code Visibility flag added

### PR DESCRIPTION
**Pull request by roalter**
Make it possible to make code (in static builds over all) hidden.
See boost as an example.

Specify library name and version:  **gflags/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
I believe it shouldn't be accepted. There are tools.build:cflags & tools.build:cxxflags, tools.build:sharedlinkflags, tools.build:exelinkflags & tools.build:defines for custom flags. CCI recipes don't have to handle dozens of options for custom compiler flags users may want, and this is exactly why there are these conf I mention.

**Comment by roalter** [comment]
@SpaceIm Sounds interesting. Wasn't aware of this flag.
But on the other hand how to make it package specific?

If I would like to have it only on one certain package?

Maybe interesting for @jngrb . Suggestions on that?

**Comment by roalter** [comment]
> I've never tested to set conf for a specific recipe in conan v2, but something like this in your profile should work (it can also be set while calling conan create/install/build):
> 
> ```
> [conf]
> gflags/*:tools.build:cflags="-fvisibility=hidden"
> gflags/*:tools.build:cxxflags="-fvisibility=hidden"
> ```
> 
> And in your global.conf you may want this line so that these conf can contribute to package id of recipes:
> 
> ```
> tools.info.package_id:confs=["tools.build:cflags", "tools.build:cxxflags", "tools.build:defines", "tools.build:exelinkflags", "tools.build:sharedlinkflags"]
> ```

@prince-chrismc do you think this would be the solution? Is there any chance to have such a behavior on conan 1.x?

**Comment by prince-chrismc** [comment]
I never saw this in 1.x but I am asking.

The suggestion is super interesting 🤔 might be my next tip of the week 🤔

**Review by uilianries — CHANGES_REQUESTED** [review]
Compiler flags should configured by [global.conf](https://docs.conan.io/2/reference/config_files/global_conf.html). Passing it by options will affect the package ID.

**Pull request closed without merging**
