### PR TITLE
adding polylineencoder package

### PR DESCRIPTION
**Pull request by wolfee001**
Specify library name and version:  **lib/1.0**

- [ X ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ X ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ X ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ X ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by wolfee001** [comment]
> Consider [wolfee001#1](https://github.com/wolfee001/conan-center-index/pull/1)

looks cool i gonna use (most of) them! thanks!

**Comment by wolfee001** [comment]
@uilianries Could you give me some hint, why the Linux builds seem to be OK, but marked as failing? Plus I'm not quite familiar with the MSVC, could you give me a hint how to fix the exceeding file path length?
Thanks!

**Comment by uilianries** [comment]
In terms of quality, this recipe looks okay. Let's wait for a new CI result, it failed internally.

**Comment by wolfee001** [comment]
> In terms of quality, this recipe looks okay. Let's wait for a new CI result, it failed internally.

yes, i started the build yesterday evening, and stil not finished :(

**Review by jgsogo — APPROVED** [review]

**Comment by wolfee001** [comment]
@uilianries Could you approve and merge the request?

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@wolfee001 Thanks for your contribution. The review process requires 3 approvals. Almost there.

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
