### PR TITLE
quill: add version 6.0.0

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **quill/6.0.0**

#### Motivation
There are lots of improvements since 4.5.0.
Use official zip files.

#### Details
https://github.com/odygrd/quill/compare/v4.5.0...v6.0.0

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — COMMENTED** [review]
Seems like the new version also [links against rt](https://github.com/odygrd/quill/compare/v4.5.0...v5.0.0#diff-7fc57714ef13c3325ce2a1130202edced92fcccc0c6db34a72f7b57f60d552a3R18) in Linux if I'm not mistaken, can we update the recipe to match? Thanks! :)

**Comment by toge** [comment]
@AbrilRBS 
Thanks you for your comment!
It seems to require linking rt since 4.4.0.
https://github.com/odygrd/quill/blob/v4.4.0/BUILD.bazel

Fixed.

**Review by AbrilRBS — DISMISSED** [review]
Thanks for the quick follow-up!

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by odygrd** [comment]
@toge please can you also add v6.0.0 in this PR ? thanks for maintaining the package

**Comment by toge** [comment]
@odygrd 
Thank you for your notice!
I updated this PR for 6.0.0.

This library always helps me very well. 
Thanks a lot for your contribution!

**Comment by odygrd** [comment]
@jwillikers @AbrilRBS

Could you please merge this PR within the next few days? Our project depends on the Conan Central Repository, and we would like to update to the latest version. Your prompt assistance would be greatly appreciated. Thank you!

**Review by jwillikers — APPROVED** [review]

**Review by AbrilRBS — APPROVED** [review]
Thanks @toge!

**Comment by AbrilRBS** [comment]
@odygrd Have you taken a look into https://docs.conan.io/2/devops/using_conancenter.html? It goes into detail on our recommendations to use Conan Center Index recipes at scale, which lifts you from the need to rely on our throughput - Let me know if that helps, else feel free to open a new issue in the main Conan repository, we're always happy to help!

I've now approved this PR to get merged momentarely too, thanks for your patience

**Review by perseoGI — APPROVED** [review]

**Pull request merged**
