### PR TITLE
arrow: support conan v2

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **arrow/***

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
Oh...
I have to create more patches for supporting conan v2, because cmake in arrow uses non standard package names in `find_package`.

**Comment by uilianries** [comment]
@toge Yes, I remember arrow was tricky last time we visited that recipe.

**Comment by toge** [comment]
@uilianries 
I agree.
I'm trying to re-struct patch files for all versions.

**Comment by uilianries** [comment]
@toge This PR passed, but it's still marked as draft. Please, update to "Read to Review" if it's okay.

**Comment by toge** [comment]
@uilianries 
Sorry. It is still under work in progress.

I have to rewrite patches for version 7.x and 8.x.
These versions has compilation error with some options.

**Comment by uilianries** [comment]
About those patch changes, did you get them from the upstream, or did you submitted to the upstream?

**Comment by toge** [comment]
@uilianries 
Lots of patches are created to solve making conan recipe.
(ex. rename package name (LZ4 -> Lz4))
And rest of pathces are brought by the upstream.

**Comment by uilianries** [comment]
@toge Thank you for explaining and updating conandata.yml, so we have an insight about those patches!

**Review by prince-chrismc — APPROVED** [review]
This is huge we can follow up in the next  pr

**Pull request merged**
