### PR TITLE
util-linux-libuuid/all: bump deps

### PR DESCRIPTION
**Pull request by ericLemanissier**
Generated and committed by [Conan Center Bump Deps](https://github.com/ericLemanissier/conan-center-index-bump-deps) Find more updatable recipes in the [GitHub Pages](https://ericlemanissier.github.io/conan-center-index-bump-deps/)

Specify library name and version:  **util-linux-libuuid/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Why does C3I try to build apple-clang 11.0, which is from an outdated epoch ?

**Comment by ericLemanissier** [comment]
Why does C3I try to build apple-clang 11.0, which is from an outdated epoch ?
@jcar87 @uilianries @RubenRBS

**Comment by RubenRBS** [comment]
We are investigating :)

**Comment by ericLemanissier** [comment]
blocked by:
- https://github.com/conan-io/conan-center-index/issues/18162

**Pull request closed without merging**
