### PR TITLE
yaml-cpp: fix msvc shared + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
- relocatable shared libs on macOS: see https://github.com/conan-io/hooks/issues/376
- cache CMake configuration with `functools.lru_cache`
- rely on `is_msvc()` & `is_msvc_static_runtime()` instead of custom methods
- add `YAML_CPP_DLL` interface definition if msvc & shared to properly define `__declspec(dllimport)` at consume time, since yaml-cpp has several global symbols.

closes https://github.com/conan-io/conan-center-index/issues/10629

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by MartinDelille — APPROVED** [review]

**Review by toge — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by SergeyKrivohatskiy** [comment]
This PR has broken compilation on MacOS
`ImportError: cannot import name 'is_msvc' from 'conan.tools.microsoft'`

Full error:
```
yaml-cpp/0.6.3: Retrieving from remote 'conancenter'...
00:00:22  yaml-cpp/0.6.3: Retrieving from server 'conancenter'
00:00:22  yaml-cpp/0.6.3: Trying with 'conancenter'...
00:00:22  Downloading conanmanifest.txt
00:00:22  Downloading conanfile.py
00:00:22  Downloading conan_export.tgz
00:00:22  yaml-cpp/0.6.3: Downloaded recipe revision 0
00:00:22  ERROR: yaml-cpp/0.6.3: Cannot load recipe.
00:00:22  Error loading conanfile at '***/CONAN_CACHE_arm64/.conan/data/yaml-cpp/0.6.3/_/_/export/conanfile.py': Unable to load conanfile in ***/CONAN_CACHE_arm64/.conan/data/yaml-cpp/0.6.3/_/_/export/conanfile.py
00:00:22    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py", line 171, in load_source
00:00:22      module = _load(spec)
00:00:22    File "<frozen importlib._bootstrap>", line 711, in _load
00:00:22    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
00:00:22    File "<frozen importlib._bootstrap_external>", line 850, in exec_module
00:00:22    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
00:00:22    File "***/CONAN_CACHE_arm64/.conan/data/yaml-cpp/0.6.3/_/_/export/conanfile.py", line 1, in <module>
00:00:22      from conan.tools.microsoft import is_msvc, is_msvc_static_runtime
00:00:22  ImportError: cannot import name 'is_msvc' from 'conan.tools.microsoft' (***/lib/python3.9/site-packages/conan/tools/microsoft/__init__.py)
```

**Comment by uilianries** [comment]
@SergeyKrivohatskiy `is_msvc` is available since conan 1.45.0, it's listed on the [changelog](https://docs.conan.io/en/latest/changelog.html#feb-2022).

**Comment by SergeyKrivohatskiy** [comment]
@uilianries Yep. Checked that already. Will leave the message anyway in case someone will face the same issue.

Thanks

**Comment by SpaceIm** [comment]
The problem is that imports are evaluated before conan check of `required_conan_version`, so error is not very meaningful in this case.

**Comment by uilianries** [comment]
@SpaceIm Excellent observation! Thank you for pointing it on Conan client.

**Pull request merged**
