### PR TITLE
gtk-doc-stub: use new autools helper

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **gtk-doc-stub/***

related to conan-io/conan#8476

CC @memsharded 

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@memsharded this shows two blocking points currently:

1. we pretty much have to use [AutoToolsToolchain.default_configure_install_args](https://docs.conan.io/en/latest/reference/conanfile/tools/gnu/autotoolstoolchain.html#attributes), which defines `--datarootdir=${prefix}/share` which is not compatible with [conan-center rule](https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#kb-h013-default-package-layout) to put all resources in `res` folder. `share` is not allowed
2. visual studio [fails with](https://github.com/eirikb/proof-of-conan/runs/4947988940?check_suite_focus=true#step:8:146) `'C:\Users\runneradmin\.conan\data\gtk-doc-stub\cci.20181216\_\_\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\source_subfolder/configure' is not recognized as an internal or external command,` because it does not seem to use bash ([mingw fails in the same way](https://github.com/eirikb/proof-of-conan/runs/4947988976?check_suite_focus=true#step:8:173))

**Comment by memsharded** [comment]
> we pretty much have to use AutoToolsToolchain.default_configure_install_args, which defines --datarootdir=${prefix}/share which is not compatible with conan-center rule to put all resources in res folder. share is not allowed

This seems a C3i policy issue, not a Conan tool ``AutotoolsToolchain`` issue.


> visual studio fails with 'C:\Users\runneradmin\.conan\data\gtk-doc-stub\cci.20181216\_\_\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\source_subfolder/configure' is not recognized as an internal or external command, because it does not seem to use bash (mingw fails in the same way)

This is most likely because C3i is still not prepared to handle this. With the new toolchains, the autotools environment will no longer be guessed by explicit. That means that profiles in C3i for VS will probably need to add:
```
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path=/path/to/my/msys
```
Or this might be provided by the ``msys2`` center package, via ``conf_info``, but that would need to be fixed first in the ``msys2`` package.

**Comment by ericLemanissier** [comment]
> > we pretty much have to use AutoToolsToolchain.default_configure_install_args, which defines --datarootdir=${prefix}/share which is not compatible with conan-center rule to put all resources in res folder. share is not allowed
> 
> This seems a C3i policy issue, not a Conan tool `AutotoolsToolchain` issue.

well, conan and conan-center should agree on the layout of package, or recipe maintenance will become even harder than it is. `share` folder was refused on the hooks side in https://github.com/conan-io/hooks/pull/336




> > visual studio fails with 'C:\Users\runneradmin.conan\data\gtk-doc-stub\cci.20181216__\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\source_subfolder/configure' is not recognized as an internal or external command, because it does not seem to use bash (mingw fails in the same way)
> 
> This is most likely because C3i is still not prepared to handle this. With the new toolchains, the autotools environment will no longer be guessed by explicit. That means that profiles in C3i for VS will probably need to add:
> 
> ```
> tools.microsoft.bash:subsystem=msys2
> tools.microsoft.bash:path=/path/to/my/msys
> ```
> 
> Or this might be provided by the `msys2` center package, via `conf_info`, but that would need to be fixed first in the `msys2` package.

Ok, I did not know about this `conf_info`. If it can be fixed in msys2 package, ok !

**Comment by memsharded** [comment]
> well, conan and conan-center should agree on the layout of package, or recipe maintenance will become even harder than it is. share folder was refused on the hooks side in conan-io/hooks#336

Oh, I see what you mean, I was confused with your PR doing ``os.path.join(self.package_folder, "share")))``, when it results ``share`` is already the default in ``Autootools`` integration, so it seemed that you were changing it. You are right, we might want to reconsider this default of the toolchain.

**Comment by sfhacker** [comment]
> visual studio fails with 'C:\Users\runneradmin\.conan\data\gtk-doc-stub\cci.20181216\_\_\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\source_subfolder/configure' is not recognized as an internal or external command, because it does not seem to use bash (mingw fails in the same way)

I may be wrong here but .... are we mixing toolchains? I have read on several fora that mixing toolchains is strongly discouraged. But perhaps it is required!

Just downloaded gtk-doc-stub and built it from source on Windows 10 x64.
As far as I can see, there are (at least?) two options:

a) meson
b) plain & simple configure script

Both succeed.

image
**meson build**

image
**autotools**

Is there any way I could repro this gtk-doc issue locally?

**Comment by ericLemanissier** [comment]
@sfhacker you can reproduce the issue by checking-out the recipe of this pull-request, and calling `conan create recipes/gtk-doc-stub/all gtk-doc-stub/cci.20181216@`
You will then most probably have the failure `ConanException: The config 'tools.microsoft.bash:subsystem' is needed to run commands in a Windows subsystem` which should be solved with https://github.com/conan-io/conan-center-index/pull/9094

**Comment by ericLemanissier** [comment]
I'll concentrate my efforts on porting binutils package to windows first

**Comment by sfhacker** [comment]
We haven't had any issues (so far) building Binutils & yasm from source on Windows.
Seems to be pretty straight forward: configure, make, make install

image


image

We don't quite follow the issue(s) reported here but if someone is in (dire) need of training or assistance, we are more than happy to help.

**Comment by ericLemanissier** [comment]
@sfhacker just to be sure, do you use conan ?

**Pull request closed without merging**
