### PR TITLE
[sentry-native/0.6.5] Add version

### PR DESCRIPTION
**Pull request by MartinDelille**
---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
Waiting for #18434 and #18435

**Comment by MartinDelille** [comment]
@czoido @RubenRBS @jcar87 Any idea why this PR has missing dependencies ? Is it related to https://github.com/conan-io/conan-center-index/issues/18162

**Comment by jcar87** [comment]
Hi @MartinDelille, thank you for bringing this up. I don't think it's the same problem as the one in that issue - we are re-generating the missing package and will re-launch this PR.

**Comment by MartinDelille** [comment]
Hi @jcar87 ! I wondered if there was news about this issue ?

**Comment by jcar87** [comment]
Hi @MartinDelille - we've resolved the issues with our CI service and are now re-launching PRs manually ahead of completely resuming the service. I've just got to this one, CI should report results soon

**Comment by MartinDelille** [comment]
It looks like it still fails for v1.

**Comment by MartinDelille** [comment]
I noticed some checks didn't passed after the latest PR: https://github.com/conan-io/conan-center-index/pull/18434#event-9766956062

I push some change to sentry-breakpad to regenerate those here: #19092

**Comment by MartinDelille** [comment]
@jcar87 Any idea why the conan v2 jobs didn't ran ?

**Review by RubenRBS — APPROVED** [review]

**Review by jcar87 — APPROVED** [review]

**Pull request merged**
