### PR TITLE
at-spi2-atk: deprecate in favor of at-spi2-core

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **at-spi2-atk/***

Motivation (from https://github.com/conan-io/conan-center-index/pull/17496#issuecomment-1544331198):
atk and at-spi2-atk are part of at-spi2-core since 2.45.1 cf https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/main/NEWS#L70
This is already reflected in [at-spi2-core recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/at-spi2-core/new/conanfile.py#L21) but not in atk and at-spi2-atk

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
blocked by:
- https://github.com/conan-io/conan-center-index/pull/17495
- https://github.com/conan-io/conan-center-index/pull/17499

**Review by jwillikers — APPROVED** [review]

**Comment by Croydon** [comment]
What is the meaning behind this?

**Comment by ericLemanissier** [comment]
atk and at-spi2-atk are part of at-spi2-core since 2.45.1 cf https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/main/NEWS#L70
This is already reflected in [at-spi2-core recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/at-spi2-core/new/conanfile.py#L21) but not in atk and at-spi2-atk

**Review by Croydon — DISMISSED** [review]

**Review by RubenRBS — DISMISSED** [review]

**Comment by jcar87** [comment]
From: https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/17496/5-linux-gcc/at-spi2-atk/2.38.0//summary.json -

when trying to build this recipe for gcc 5, it fails because one of the dependencies (`dbus`) no longer builds with gcc 5 and requires at minimum gcc 7 -  I suspect because `glib` has been bumped. 

If this PR is deprecating this recipe, perhaps we can keep the version as it was?

Otherwise we will verify the logic on our side, I suspect if one if the dependencies is invalid, it should not even attempt to build this with gcc5 at all.

**Comment by ericLemanissier** [comment]
dbus does not seem to be in glib's requirements dependencies. The requirement comes from at-spi2-core. I don't understand why it fails in this PR, when https://github.com/conan-io/conan-center-index/pull/17499#issuecomment-1567127137 passed without this problem

**Comment by RubenRBS** [comment]
We are investigating the logic behind the Invalid Configuration detection, please hold :)

**Comment by ericLemanissier** [comment]
blocked by:
- https://github.com/conan-io/conan-center-index/pull/17855
- https://github.com/conan-io/conan-center-index/pull/17856

**Review by jwillikers — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
I thought I had reviewed all 3 PRs in this batch, sorry for that!

**Comment by ericLemanissier** [comment]
No problem, this one could not be merged before https://github.com/conan-io/conan-center-index/pull/17855 anyway

**Pull request merged**
