### PR TITLE
[qt/6.4.2] Remove .dll extension as QSystemLibrary unconditionally adds it

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **qt/6.4.2**

Remove .dll extension as QSystemLibrary unconditionally adds it

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — DISMISSED** [review]

**Review by jwillikers — DISMISSED** [review]

**Comment by MartinDelille** [comment]
@uilianries is it fine to push the change to fix this error or I should wait before triggering the CI for such a big package ?

**Comment by prince-chrismc** [comment]
its a new error ive never seen before in the backend 🤷

**Comment by MartinDelille** [comment]
```
qt/6.4.2: Applying build-requirement: strawberryperl/5.32.1.1
[HOOK - conan-center.py] pre_source(): [IMMUTABLE SOURCES (KB-H010)] OK
qt/6.4.2: Configuring sources in C:\J\w\prod\BuildSingleReference@4/s\a78ae1\1\src
qt/6.4.2: 
ERROR: qt/6.4.2: Error in source() method, line 633
	strip_root=True, destination=destination)
	OSError: [Errno 28] No space left on device: '\\\\?\\C:\\J\\w\\prod\\BuildSingleReference@4\\s\\a78ae1\\1\\src\\qtdeclarative\\examples\\qml\\tutorials\\extending-qml\\chapter6-plugins\\app.qml'
```

**Comment by MartinDelille** [comment]
Since this changed is included in 6.4.3, I could eventually close this in favor of https://github.com/conan-io/conan-center-index/pull/16584

**Comment by MartinDelille** [comment]
I can understand that maintaining this recipe is a huge amount of work!

How do you see the future of qt recipe in CCI ? The Qt company used to offer a conan package distribution but I realized today that I missed this blog post: https://www.qt.io/blog/conan-package-manager-pilot-to-end-in-december

**Comment by ericLemanissier** [comment]
there are already other contributors submitting fixes to qt recipe, so the future of this recipe is no different than any other recipe on CCI.
The only specific part is the version bumps (and it has always been submitted by me). For this I'll add a markdown file explaining how to do it (or maybe a python script, if I find the motivation/time).

**Comment by ericLemanissier** [comment]
No, but I feel like a documentation/python script stored next to the recipe is easier to find and use than thread on github.

**Comment by MartinDelille** [comment]
Yes of course. My full question was "Is there a thread about the ongoing C3I disk space issue ?

**Comment by ericLemanissier** [comment]
OK. I don't think there is yet

**Comment by MartinDelille** [comment]
I created it here: https://github.com/conan-io/conan-center-index/issues/16857

**Comment by MartinDelille** [comment]
Close in favor of https://github.com/conan-io/conan-center-index/pull/16889

**Pull request closed without merging**
