### PR TITLE
glib 2.78.6

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **glib/2.78.6**

also, bump libmount to fix conflict with eudev, libwebsockets and libsystemd

and don't use `PkgConfig` helper in the test package, because it calls `pkg-config` executable, which is not installed on macos runners

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9076999839/attempts/1)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9076999839/attempts/2)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9076999839/attempts/3)

**Comment by ericLemanissier** [comment]
this is ready for review

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@uilianries @RubenRBS this is ready for review

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan-center-index/pull/24165

**Pull request closed without merging**
