### PR TITLE
[coin-clp] Make headers of required packages transitive

### PR DESCRIPTION
**Pull request by hedtke**
Specify library name and version:  **coin-clp/1.17.7**

The public API of coin-clp contains the headers CoinPragma.hpp (from coin-utils, see c.f. ClpMessage.hpp) and OsiSolverInterface.hpp (from coin-osi, see c.f. OsiClpSolverInterface.hpp)

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jcar87 — APPROVED** [review]
LGTM!
Having inspected the headers involved, I believe these are strictly `transitive_headers=True`) and don't require propagating the library - no implementation is called directly within the headers as far as I can see.

Thanks @hedtke for providing details about which headers were impacted - much appreciated!

**Comment by SpaceIm** [comment]
It doesn't seem sufficient: https://github.com/conan-io/conan-center-index/pull/16053#issuecomment-1512637106

**Comment by hedtke** [comment]
> It doesn't seem sufficient: [#16053 (comment)](https://github.com/conan-io/conan-center-index/pull/16053#issuecomment-1512637106)

Interestingly enough, it is not enough to change `coin-clp` and set `coin-utils` as `transitive_libs=True`, linking is still problematic (on my local machine). It only works when I explicitly add `coun-utils` to `OGDF`. Or maybe I do not understand this transitive stuff correctly. I thought that setting `transitive_libs=True` for `coin-utils` within the recipe of `coin-clp` would solve the linking problem, but it doesn't.

**Comment by SpaceIm** [comment]
Which OS?

**Comment by hedtke** [comment]
> Which OS?

Mac

**Comment by SpaceIm** [comment]
That's surprising. Looks like a conan client issue. Assuming your patch does what it's supposed to do in ogdf, coin-clp::coin-clp target is linked to OGDF target, and therefore if transitive_libs of coin-utils is True in coin-clp recipe, coin-utils lib should be linked.
It would help to add CMAKE_VERBOSE_MAKEFILE to see linker command.

**Comment by hedtke** [comment]
Might be a cache issue. I will give it another go

**Comment by hedtke** [comment]
It was a cache issue. Rebuilding worked fine. Here is a follow-up: https://github.com/conan-io/conan-center-index/pull/17115

**Pull request merged**
