### PR TITLE
libmysqlclient: bump cmake to generate v2 packages

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
libmysqlclient/8.0.29: Configuring sources in /Users/jenkins/w/prod/BuildSingleReference@5/.conan/data/libmysqlclient/8.0.29/_/_/source/src
libmysqlclient/8.0.29: Waiting 5 seconds to retry...
libmysqlclient/8.0.29: WARN: Could not download from the URL https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.29.tar.gz: Not found: https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.29.tar.gz. Trying another mirror.
libmysqlclient/8.0.29: ERROR: Download failed, check server, possibly try again
HTTPSConnectionPool(host='mirrors.huaweicloud.com', port=443): Read timed out.
libmysqlclient/8.0.29: WARN: Could not download from the URL https://mirrors.huaweicloud.com/mysql/Downloads/MySQL-8.0/mysql-8.0.29.tar.gz: Download failed, check server, possibly try again
("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer')). Trying another mirror.
ERROR: libmysqlclient/8.0.29: Error in source() method, line 111
	get(self, **self.conan_data["sources"][self.version], strip_root=True)
	ConanException: All downloads from (2) URLs have failed.
```

8.0.29 is not available anymore on https://downloads.mysql.com/archives/community/

**Comment by SpaceIm** [comment]
@danimtb @uilianries @prince-chrismc 

This INVALID CONFIGURATION for msvc 192 is problematic: https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/16610/3/libmysqlclient/8.0.31//summary.json

libmysqlclient 8.0.31 can be built with Visual Studio 2019, but it can't be built when you force C++14. Why c3i shoots itself in the foot by forcing a potentially C++ standard incompatible with a library while this compiler can support a more recent standard which would provide a pre-built package into conancenter (raising has consequences for downstream recipes, and it prevents to properly test all compilers, we can miss many issues).

**Comment by prince-chrismc** [comment]
Please be careful with your choice of words. My English brain reads that with a very harsh tone. "shoots itself in the foot" has a negative connotation and isnt pleeaesnt to see.

***

It's a workarounds for a feature that was not finished before the launch in order to work with the default client.

This recipe is part of how we discovered the problem if I'm not mistaken and it's one of the priorities we are working on fixing.

You can't see the private repo but we are working on this 😄 

c3i: design and implement cppstd fallback logic #2099
Open
[jcar87](https://github.com/jcar87) opened this issue

**Comment by prince-chrismc** [comment]
It's a temporary limitation :)

**Review by jwillikers — APPROVED** [review]

**Comment by RubenRBS** [comment]
Hi @SpaceIm thanks for the PR. Just for further context for posterity, libmysqlclient 8.0.29 has been removed by the authors because:
> This release is no longer available for download. It was removed due to a critical issue that could cause data in InnoDB tables having added columns to be interpreted incorrectly.

So after checking with the team (I didn't know how to proceed in this case) this looks good :)

Thanks for noticing this!

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
