### PR TITLE
[boost] b2 user-config.jam needs CXX binary to be quoted as path may contain spaces

### PR DESCRIPTION
**Pull request by garethsb**
Specify library name and version:  **boost/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
#3362 this was recently removed 

@madebr @SSE4 I dont know if you have any thoughts how both workflows can be supported

**Comment by mathbunnyru** [comment]
@garethsb-sony zlib was updated 4 days ago.
Could you please retrigger the build?

You need to close the PR, wait at least 10 seconds and then open it again.

I would also like to ask you to merge latest master in your branch - boost is updated quite often, so your version in a branch might be a bit old.

**Comment by mathbunnyru** [comment]
And of course, @prince-chrismc's comment is very important.

**Comment by uilianries** [comment]
Let's use the old fashion way

**Comment by prince-chrismc** [comment]
```
MSBUILD : error MSB4166: Child node "6" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.
```

**Comment by jgsogo** [comment]
It looks like it's related to memory, Windows node running out of RAM/swap memory. Too many _big_ jobs like `boost` running at the same time in the same Windows machine. Maybe it's been bad luck... 

If that is the case I see different alternatives:
 * reduce the number of jobs that can run in parallel in the same machine
 * tell Conan to use `parallel=False` (CCI configuration): if we are already running jobs in parallel, the machine can be very stressed if every compilation is using `cpu_count` processes to build.

Or maybe it is something unrelated 🤔   cc/ @danimtb 

 Meanwhile triggering the build again...

**Pull request closed without merging**
