### PR TITLE
boost: don't bootstrap and use b2

### LINKED ISSUE #1005: [question] is bootstrapping of boost correct?
The boost recipe has a `_bootstrap` method that will build `b2`.
In that method, the environment variables `CC`, `CXX`, `CFLAGS`, ... are removed
and `b2` is built.
I believe this method is very brittle.

Shouldn't this recipe just use `b2` as a build requirement?

CC'ing @SSE4 for being the main author (I think)

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **boost/[1.69.0-1.72.0]**

closes: #1005

CC'ing @SSE4 

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Excellent! Much simpler now! @madebr please, fix the conflicts and we are good.

**Comment by madebr** [comment]
This error is not new.
I can reproduce it on current master with the following profile:
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MTd
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

**Comment by madebr** [comment]
There is something suspicious going on on the CI servers.
The output log says:
```
common.copy C:\J\c3ipr\pr_1016_2_2_2\.short\fb172f\1\include\boost\detail\utf8_codecvt_facet.hpp



    copy /b "C:\J\c3ipr\pr_1016_2_2_2\.short\8521c3\1\boost_1_70_0\boost\detail\utf8_codecvt_facet.hpp" + this-file-does-not-exist-A698EE7806899E69 "C:\J\c3ipr\pr_1016_2_2_2\.short\fb172f\1\include\boost\detail\utf8_codecvt_facet.hpp"



C:\J\c3ipr\pr_1016_2_2_2\.short\8521c3\1\boost_1_70_0\boost\detail\utf8_codecvt_facet.hpp

        1 file(s) copied.

common.copy C:\J\c3ipr\pr_1016_2_2_2\.short\fb172f\1\include\boost\detail\utf8_codecvt_facet.ipp



    copy /b "C:\J\c3ipr\pr_1016_2_2_2\.short\8521c3\1\boost_1_70_0\boost\detail\utf8_codecvt_facet.ipp" + this-file-does-not-exist-A698EE7806899E69 "C:\J\c3ipr\pr_1016_2_2_2\.short\fb172f\1\include\boost\detail\utf8_codecvt_facet.ipp"



The system cannot find the path specified.

...failed common.copy C:\J\c3ipr\pr_1016_2_2_2\.short\fb172f\1\include\boost\detail\utf8_codecvt_facet.ipp...
```

So it claims to have successfully copied `C:\J\c3ipr\pr_1016_2_2_2\.short\fb172f\1\include\boost\detail\utf8_codecvt_facet.hpp` but fails to copy `C:\J\c3ipr\pr_1016_2_2_2\.short\fb172f\1\include\boost\detail\utf8_codecvt_facet.ipp`.

I've just checked the source of boost 1.70 and these files can be found in the same directory.

While tracking the source of this error, a build failed because the disk was out of space.
Might this be a cause?

**Comment by mikedld** [comment]
I'm observing "The system cannot find the batch label specified - Config_VC12" error when trying to build with VS 2013, due to one of batch files containing LF line endings after patching or something like that. This PR (given that it avoids calling bootstrap.bat) has a potential of fixing the issue, am I right?

**Comment by madebr** [comment]
@mikedld Probably, since `bootstrap` is not run anymore.
But to be 100% sure, you [should try it out](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
(Please report back)

**Comment by mikedld** [comment]
@madebr, took a bit of fiddling around to set changes from this PR up locally, but it seems to build just fine. Thanks!

**Comment by madebr** [comment]
@mikedld Thanks for investing your time to test this!

**Pull request merged**
