### PR TITLE
ffmpeg: use version range for openssl

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
waiting for https://github.com/conan-io/conan-center-index/pull/17066

**Review by MartinDelille — APPROVED** [review]

**Review by MartinDelille — DISMISSED** [review]

**Review by MartinDelille — APPROVED** [review]

**Comment by SpaceIm** [comment]
@prince-chrismc @RubenRBS @uilianries could you approve this one please to allow opencv to build in c3i?

**Comment by prince-chrismc** [comment]
This is failing v2

```
dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libarchive.2.dylib
  Expected in: /Users/jenkins/w/prod-v2/BuildSingleReference@2/p/libic50650dc30c43d/p/lib/libiconv.2.dylib
 in /usr/lib/libarchive.2.dylib
metal: error: unable to execute command: Abort trap: 6
```

And I am pretty sure it's on the v2 required list so the bot wont merge it :( https://github.com/conan-io/conan-center-index/blob/238d7079448917dfded1bac527dc37e027c40a2b/.c3i/conan_v2_ready_references.yml#L105

**Comment by SpaceIm** [comment]
Yes and I've already said that ffmpeg shouldn't be in this v2 list since it has never ever pass v2 pipeline in any PR.

**Comment by prince-chrismc** [comment]
There's merge conflicts.

V2 reference list might not get fixed before v2 is required so we can have an admin merge this in the meantime :)

**Comment by jcar87** [comment]
Hi @SpaceIm  - I have to request to please stop refraining from opening and closing PRs to trigger a new build. As the service resumes from maintenance, we have a process to re-start PRs that were marked with the maintenance label, to avoid re-starting them all at once.

As far as _this_ PR is concerned, the v2 job (`c3i/conan-v2/pr-merge` in the status checks list) was running when you closed it, thus interrupting the process and starting over. 


We are closely monitoring any issues with automatic builds of PRs - and will manually run any that need it, without any further action required from the users.

**Comment by SpaceIm** [comment]
> As the service resumes from maintenance, we have a process to re-start PRs that were marked with the maintenance label

There is something to improve in this re-processing, because most PRs were not marked with this label. Many PRs without these label were green before maintenance, and are now red without any message. It's the same thing after each maintenance. When you have dozens of opened PR (I'm probably the only one), it's super tedious, and from my past experience I know that you miss proper re-run of many of them. So ok for waiting, no problem, but you have to understand that I don't want to see PRs on which I've spent my time going stale (and eventually auto-closed) because you have forgotten many of them.

**Pull request merged**
