### PR TITLE
libwebsocket: actually build 4.3.2 and later

### PR DESCRIPTION
**Pull request by ericLemanissier**
fixes https://github.com/conan-io/conan-center-index/issues/23967

Specify library name and version:  **libwebsocket/***

@jcar87 you are the original author of this line, so you probably want to take a look at the fix

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9059029956/attempts/1)

**Comment by ericLemanissier** [comment]
https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/23968/1/libwebsockets/4.3.3//summary.json is much better than https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/23853/6/libwebsockets/4.3.3//summary.json

**Review by boofhead — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@uilianries @RubenRBS what do you think of this fix ? This is quite urgent because all consumers of libwebsocket >= 4.3.2 fall in ConanInvalidConfiguration exception currently.

**Review by SpaceIm — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
Approving after looking into it with @czoido

**Review by czoido — APPROVED** [review]

**Comment by ericLemanissier** [comment]
Thanks !

**Pull request merged**
