### PR TITLE
ffmpeg: bump dependencies + modernize a little bit more

### PR DESCRIPTION
**Pull request by SpaceIm**
This PR mainly aims to solve versions conflicts I see in `opencv 4.x` PRs (see https://github.com/conan-io/conan-center-index/pull/15193#issuecomment-1465000821)

But I've took advantage of this PR to modernize this recipe a little bit more (it's not a full conan v2 migration, since for the moment no one has been able to fix Windows build with new generators in https://github.com/conan-io/conan-center-index/pull/15818 or https://github.com/conan-io/conan-center-index/pull/15819, and few dependencies like `libx264` & `libx265` are not migrated):

- use `to_apple_arch`, `is_msvc`, `chdir`, `replace_in_file` & `rm` from conan v2 api
- add `package_type`
- use `self.dependencies` instead of `self.deps_cpp_info` or `self.options[deps]`
- define ffmpeg components versions for `PkgConfigDeps`
- fix options of type ANY for conan v2
- protect double deletion of options & settings
- use `check_min_vs` for Visual Studio version checks
- add test package for conan v2 generators, and test v1 package for legacy generators

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by MartinDelille — DISMISSED** [review]

**Review by MartinDelille — APPROVED** [review]

**Comment by RubenRBS** [comment]
Thanks for the detailed PR comment, it really helps a lot when reviewing the changes when we have a summary of those/the reasons behind them, even if we know they require more work :)

❤️

**Comment by paulharris** [comment]
Is it just me, or is ffmpeg's options a bit hard to configure?
I'd like to start with nothing enabled, and build up from there, but if you set `ffmpeg:disable_everything`, all the individual defaults are still set to true... eg: `ffmpeg:with_libfdk_aac` ... so configure is called with that option, and, conan sucks in libfdk_aac.

I understand there needs to be a "default" set of options for the CCI package,
but couldn't that be done with a `ffmpeg:conan_defaults=True`
or something like that?
And leave all the specific `--enable-FLAG` set to false by default?

**Comment by granger35** [comment]
I have closed the PR https://github.com/conan-io/conan-center-index/pull/16556 as it was already covered by this one. Moving xz-utils to version 5.4.0 is required by openCV recipe which is down for now due to version conflicts: https://github.com/conan-io/conan-center-index/issues/16534. Does it make sense to reopen the PR https://github.com/conan-io/conan-center-index/pull/16556 in order to quickly fix OpenCV issue (and check in a second step this PR), or due you think this PR can be merged quickly ?

**Comment by SpaceIm** [comment]
I can be merged quickly if at least one team member can approve it.

**Review by StellaSmith — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by SpaceIm** [comment]
@uilianries @prince-chrismc could you review please?

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
@danimtb @uilianries @prince-chrismc ffmpeg packages (at least v1 packages) have not been uploaded to conancenter after merge of this PR. It's an issue for opencv PRs.

**Comment by SpaceIm** [comment]
No update?

**Comment by prince-chrismc** [comment]
I will open an issue for the team to track this. They've been too busy and I am sure the others did not check this.

**Comment by prince-chrismc** [comment]
Thanks for the ping ❤️  trying to keep up and keep things moving not easy and you've noticed !

**Comment by granger35** [comment]
@prince-chrismc any update concerning ffmpeg packages not uploaded to conan-center? There were at least 5 PR for OpenCV and 1 PR for openimageio that failed due to the missing packages. Thx.

**Comment by prince-chrismc** [comment]
ffmpeg 1.x packages are available the problem is 2.0 packages but the recipe does not support 2.0 yet. https://github.com/conan-io/conan-center-index/pull/15819 is getting closer 🤞 

If there are missing 1.x packages please let me know

**Comment by granger35** [comment]
Looking at the the PR https://github.com/conan-io/conan-center-index/pull/16524, it seems that ffmpeg packages are still missing: https://c3i.jfrog.io/c3i/misc/logs/pr/16524/13-linux-gcc/opencv/4.5.5//e804b647903442967fd7ee18a162c46794df0aa0-build.txt

**Pull request merged**
