### PR TITLE
bump dependencies of pkgconf

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **pkgconf/all**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Comment by AndreyMlashkin** [comment]
That's the fastest approval on conan center for me ever

**Comment by AndreyMlashkin** [comment]
It seems, it stuck... Why?

**Comment by RubenRBS** [comment]
Good catch @AndreyMlashkin, investigating now :)

**Comment by RubenRBS** [comment]
Seems like the building job got stuck somehow, we're investigating what caused it, but I have restarted the builds and now everything seems fine :). (So that if in the result summary anyone sees `UPSTREAM` as the status instead of `BUILT`, it's because those were compiled in the first job before it got stuck)

**Pull request merged**
