### PR TITLE
onetbb: fix interprocedural_optimization option not being propagated correctly

### PR DESCRIPTION
**Pull request by aasmune**
### Summary
Changes to recipe:  **onetbb/[*]**

#### Motivation
Fix the bug described in #25564:

#### Details
`interprocedural_optimization=False` the option isn't propagated correctly, resulting in `TBB_ENABLE_IPO` not being set to false. 

By checking that `self.options.get_safe("interprocedural_optimization")` is not `None` instead of the boolean value of the option, we set the correct environment variable also when the option is provided and set to `False`.

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]
Hi @aasmune thanks a lot for taking the time to report the issue and open a PR, and again for your patience while we got this reviewed :)

My logs show that in fact, the feature is now properly disabled:

<details>

```
-- Using Conan toolchain: /Users/abril/.conan2/p/b/onetb41b7d59e5b28e/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Defining libcxx as C++ flags: -stdlib=libc++
-- Conan toolchain: C++ Standard 17 with extensions ON
-- The CXX compiler identification is AppleClang 16.0.0.16000026
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Checking for one of the modules 'hwloc'
-- Looking for getcontext
-- Looking for getcontext - found
-- The C compiler identification is AppleClang 16.0.0.16000026
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The tbbbind_2_5 target will be configured using the HWLOC 2.9.3
-- Configuring done (1.5s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/abril/.conan2/p/b/onetb41b7d59e5b28e/b/build/Release
```

</details>

And it's set when running with `interprocedural_optimization=True`:

<details>

```
-- Using Conan toolchain: /Users/abril/.conan2/p/b/onetb79358f7d9eba6/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Defining libcxx as C++ flags: -stdlib=libc++
-- Conan toolchain: C++ Standard 17 with extensions ON
-- The CXX compiler identification is AppleClang 16.0.0.16000026
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Checking for one of the modules 'hwloc'
-- Looking for getcontext
-- Looking for getcontext - found
-- IPO enabled
-- The C compiler identification is AppleClang 16.0.0.16000026
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The tbbbind_2_5 target will be configured using the HWLOC 2.9.3
-- Configuring done (2.0s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/abril/.conan2/p/b/onetb79358f7d9eba6/b/build/Release
```

</details>


Also I've submitted https://github.com/conan-io/conan/pull/17411 to the client to ensure that these checks are covered by our tests

**Comment by AbrilRBS** [comment]
Hi @aasmune thanks (again) a lot for taking the time to report the issue and create the PR. We have created a superset of this in https://github.com/conan-io/conan-center-index/pull/26106 that also addresses some other issues, so we'll close this one in favour of the new one, but still, thanks!

**Comment by memsharded** [comment]
Actually, it was my bad, I didn't see this PR open, I am very sorry.

We will let @jcar87 decide tomorrow, I think it would be good to be able to merge the contributor PR, it was correct back then, I can confirm, though it is true that my commit also fixes a similar issue with another option. I can do a commit on top of this to keep the contributor commit, I'll try to do that.

**Comment by memsharded** [comment]
> We will let @jcar87 decide tomorrow, I think it would be good to be able to merge the contributor PR, it was correct back then, I can confirm, though it is true that my commit also fixes a similar issue with another option. I can do a commit on top of this to keep the contributor commit, I'll try to do that.

The other option is actually good. The current checks of versions, and the fact that it is using another option as the value, not itself, makes it correct. As we are aiming to have PRs as minimal as possible, exactly as this PR did, I am going to approve it.

I have also validated in the logs that the "IPO enabled" message is correct now. Thanks again for  your contribution and sorry for the noise.

**Review by memsharded — APPROVED** [review]

**Pull request merged**
