### PR TITLE
boost/<all versions>: error: Cannot configure toolset clang-win: no 'clang-cl.exe' command found or given

### PR DESCRIPTION
**Pull request by stepanzorin**
about the problem: https://github.com/conan-io/conan-center-index/issues/18302 (my issue)

Not only me came across with the problem. Today, an unfamiliar person contacted me inquiring about how I resolved a particular issue. As a result, I have decided to proceed with creating a pull request that addresses the problem. Please pay special attention to it.

The message in telegram:
изображение

Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jcar87** [comment]
Assigning this to 

> Still an issue to this day. Using `boost/1.85.0#939ac8280c3683bfacd3bb6d89803d9b%1722339052.397`
> 
> Could you please have a look @jcar87?

Hi @Todiq ! Thanks for reaching out.
Could you provide details regarding your Conan profile and your setup? Or just simply confirm if your environment is the same as the one reported here https://github.com/conan-io/conan-center-index/issues/18302

I will try to reproduce and issue a fix (looking at the changes in this PR it's unclear why they would fix the issue).

**Comment by stepanzorin** [comment]
Hi @jcar87 !

Good to see you here. My PR fixes the issue for the environment: `Windows + llvm clang`. Linux users have not that problem. And my PR fixing the issue for version 1.85.0 is the same. Nothing breaks.

If my idea to solve the problem works, I will glad participate in a merge. Tag me in any moment.

**Comment by Todiq** [comment]
> Hi @Todiq ! Thanks for reaching out. Could you provide details regarding your Conan profile and your setup? Or just simply confirm if your environment is the same as the one reported here #18302

@jcar87 

Here is my setup:

```
version: 2.6.0
conan_path: D:\venv\Scripts\conan
python
  version: 3.9.13
  sys_version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
  sys_executable: D:\venv\Scripts\python.exe
  is_frozen: False
  architecture: AMD64
system
  version: 10.0.22631
  platform: Windows-10-10.0.22631-SP0
  system: Windows
  release: 10
  cpu: Intel64 Family 6 Model 186 Stepping 3, GenuineIntel
```

I installed LLVM 17.0.6 through https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.6 and added it to the user's path

My profile is the following:
```
{% set compiler, version, compiler_exe = detect_api.detect_clang_compiler(compiler_exe="clang") %}
{% set version = detect_api.default_compiler_version(compiler, version) %}
{% set os = detect_api.detect_os() %}

[settings]
arch={{detect_api.detect_arch()}}
build_type=Release
compiler={{compiler}}
compiler.cppstd=17
compiler.version={{version}}
os={{os}}

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.cmake.cmake_layout:build_folder_vars = ["settings.os", "settings.compiler", "settings.compiler.version", "settings.arch"]
tools.build:compiler_executables = {"c": "clang-cl", "cpp": "clang-cl", "rc": "llvm-rc"}
tools.build:cxxflags=["-fansi-escape-codes -fcolor-diagnostics"]
tools.build:exelinkflags=["-fuse-ld=lld"]
tools.build:sharedlinkflags=["-fuse-ld=lld"]

{% if os == "Windows" %}
	mypkg*/*:tools.env.virtualenv:powershell=True
	tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
{% endif %}
```

conanfile:
```
[requires]
boost/1.85.0

[options]
boost*.bzip2=False
boost*.shared=True
boost*.zlib=False
boost*.without_atomic=False
boost*.without_charconv=True
boost*.without_chrono=False
boost*.without_cobalt=True
boost*.without_container=False
boost*.without_context=True
boost*.without_contract=True
boost*.without_coroutine=True
boost*.without_date_time=False
boost*.without_exception=False
boost*.without_fiber=True
boost*.without_filesystem=False
boost*.without_graph=True
boost*.without_graph_parallel=True
boost*.without_iostreams=False
boost*.without_json=True
boost*.without_locale=False
boost*.without_log=False
boost*.without_math=True
boost*.without_mpi=True
boost*.without_nowide=True
boost*.without_program_options=False
boost*.without_python=True
boost*.without_random=False
boost*.without_regex=False
boost*.without_serialization=True
boost*.without_stacktrace=True
boost*.without_system=False
boost*.without_test=True
boost*.without_thread=False
boost*.without_timer=True
boost*.without_type_erasure=True
boost*.without_url=True
boost*.without_wave=True
```

And the command:

`conan install --profile:all clang --build=missing --remote conancenter .`

**Comment by Todiq** [comment]
Hello @jcar87

Any news?

**Comment by Todiq** [comment]
@jcar87 @perseoGI Can any of you please check this PR when you have a moment?

It would be very useful to be able to build using clang-cl, especially in CI in cross-building scenarios, when jobs run on Linux

**Comment by Todiq** [comment]
Thanks to have opened it back. @stepanzorin, would you mind having a look? Thanks in advance!

**Comment by Todiq** [comment]
Hello @jcar87 @perseoGI,

The issue still exists to this date. `boost.txt` is the same as the one provided earlier. I installed clang-cl through the LLVM setup exe on github and added it to the path. It works with other recipes. Here is the log:

```
conan install .\boost.txt --build=missing -pr Windows-x86_64-clang --envs-generation false
detect_api: Found clang 21.1
detect_api: clang>=8, using the major as version

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.runtime_version=v145
compiler.version=21
os=Windows
[options]
*:shared=True
gtest/*:shared=False
[tool_requires]
*: ninja/1.13.2, cmake/4.2.1
[conf]
tools.build:compiler_executables={'c': 'clang-cl', 'cpp': 'clang-cl', 'rc': 'llvm-rc'}
tools.build:cxxflags=['-fansi-escape-codes', '-fcolor-diagnostics']
tools.build:exelinkflags=['-fuse-ld=lld']
tools.build:sharedlinkflags=['-fuse-ld=lld']
tools.build:skip_test=False
tools.cmake.cmake_layout:build_folder_vars=['settings.os', 'settings.compiler', 'settings.compiler.version', 'settings.arch']
tools.cmake.cmakedeps:new=will_break_next
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
user.tools.build:run_tests=False
[buildenv]
PATH=+(path)C:/Program Files/LLVM/bin

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=194
os=Windows
[conf]



======== Computing dependency graph ========
Graph root
    boost.txt: D:\boost.txt
Requirements
    boost/1.85.0#a876aaf9a806cd6a6562714dbbe36c4d - Cache
Build requirements
    b2/5.3.3#107c15377719889654eb9a162a673975 - Cache
    cmake/4.2.1#951586eff155256a7b5298631d6b1416 - Cache
    ninja/1.13.2#c8c5dc2a52ed6e4e42a66d75b4717ceb - Cache
Resolved version ranges
    b2/[>=5.2 <6]: b2/5.3.3

======== Computing necessary packages ========
Connecting to remote 'cast' anonymously
Connecting to remote 'conancenter' anonymously
boost/1.85.0: Main binary package 'c9ebbd88af356e31997054e9ec51197a1a277e85' missing
boost/1.85.0: Checking 11 compatible configurations
boost/1.85.0: Compatible configurations not found in cache, checking servers
boost/1.85.0: Found 0 compatible configurations in remotes
boost/1.85.0: No compatible configuration found
Requirements
    boost/1.85.0#a876aaf9a806cd6a6562714dbbe36c4d:c9ebbd88af356e31997054e9ec51197a1a277e85 - Build
Build requirements
    b2/5.3.3#107c15377719889654eb9a162a673975:522dcea5982a3f8a5b624c16477e47195da2f84f#d08e95c38a4477339364259bc493181f - Cache
    cmake/4.2.1#951586eff155256a7b5298631d6b1416:522dcea5982a3f8a5b624c16477e47195da2f84f#fc530b68aa8a1d9a3ec55995f446d9da - Cache
    ninja/1.13.2#c8c5dc2a52ed6e4e42a66d75b4717ceb:723257509aee8a72faf021920c2874abc738e029#5f167024cd4b823987d6721464aef35b - Cache

======== Installing packages ========
b2/5.3.3: Already installed! (1 of 4)
cmake/4.2.1: Already installed! (2 of 4)
ninja/1.13.2: Already installed! (3 of 4)

-------- Installing package boost/1.85.0 (4 of 4) --------
boost/1.85.0: Building from source
boost/1.85.0: Package boost/1.85.0:c9ebbd88af356e31997054e9ec51197a1a277e85
boost/1.85.0: settings: os=Windows arch=x86_64 compiler=clang compiler.cppstd=17 compiler.libcxx=libstdc++11 compiler.runtime=dynamic compiler.runtime_type=Release compiler.runtime_version=v145 compiler.version=21 build_type=Release
boost/1.85.0: options: asio_no_deprecated=False buildid=None bzip2=False diagnostic_definitions=False error_code_header_only=False extra_b2_flags=None filesystem_no_deprecated=False filesystem_use_std_fs=False header_only=False i18n_backend_iconv=off i18n_backend_icu=False layout=system lzma=False magic_autolink=False multithreading=True namespace=boost namespace_alias=False segmented_stacks=False shared=True system_no_deprecated=False system_use_utf8=False visibility=hidden without_atomic=False without_charconv=True without_chrono=False without_cobalt=True without_container=False without_context=True without_contract=True without_coroutine=True without_date_time=False without_exception=False without_fiber=True without_filesystem=False without_graph=True without_graph_parallel=True without_iostreams=False without_json=True without_locale=False without_log=False without_math=True without_mpi=True without_nowide=True without_program_options=False without_python=True without_random=False without_regex=False without_serialization=True without_stacktrace=True without_system=False without_test=True without_thread=False without_timer=True without_type_erasure=True without_url=True without_wave=True zlib=False zstd=False
boost/1.85.0: Building your package in D:\.conan\p\b\boost404404d536d8d\b
boost/1.85.0: Calling generate()
boost/1.85.0: Generators folder: D:\.conan\p\b\boost404404d536d8d\b\build-release\conan
boost/1.85.0: Generating aggregated env files
boost/1.85.0: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
boost/1.85.0: Calling build()
boost/1.85.0: WARN: replace_in_file didn't find pattern '/* thread_local */' in 'D:\.conan\p\boost3d2f750c7d701\s\src\boost\stacktrace\detail\libbacktrace_impls.hpp' file.
boost/1.85.0: WARN: replace_in_file didn't find pattern '/* static __thread */' in 'D:\.conan\p\boost3d2f750c7d701\s\src\boost\stacktrace\detail\libbacktrace_impls.hpp' file.
boost/1.85.0: WARN: replace_in_file didn't find pattern 'local generic-os = [ set.difference $(all-os) : aix darwin vxworks solaris osf hpux ] ;' in 'D:\.conan\p\boost3d2f750c7d701\s\src\tools\build\src\tools\gcc.jam' file.
boost/1.85.0: WARN: replace_in_file didn't find pattern 'local no-threading = android beos haiku sgi darwin vxworks ;' in 'D:\.conan\p\boost3d2f750c7d701\s\src\tools\build\src\tools\gcc.jam' file.
boost/1.85.0: WARN: replace_in_file didn't find pattern '    <conditional>@numa' in 'D:\.conan\p\boost3d2f750c7d701\s\src\libs\fiber\build\Jamfile.v2' file.
boost/1.85.0: WARN: Patching user-config.jam
boost/1.85.0: WARN:
using "clang-win" :  :  "clang-cl" :
<cxxflags>"-fansi-escape-codes -fcolor-diagnostics" <linkflags>"-fuse-ld=lld"  ;
boost/1.85.0: WARN: b2 -q target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=D:\.conan\p\boost3d2f750c7d701\s\src\tools\build\user-config.jam -sNO_ZLIB=1 -sNO_BZIP2=1 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=off --disable-iconv threading=multi visibility=hidden link=shared variant=release --with-atomic --with-chrono --with-container --with-date_time --with-exception --with-filesystem --with-iostreams --with-locale --with-log --with-program_options --with-random --with-regex --with-system --with-thread toolset=clang-win cxxstd=17 define=_GLIBCXX_USE_CXX11_ABI=1 pch=on linkflags="-stdlib=libstdc++" cxxflags="-fPIC -stdlib=libstdc++" install --prefix=D:\.conan\p\b\boost404404d536d8d\p -j12 --abbreviate-paths -d0 --debug-configuration --build-dir="D:\.conan\p\b\boost404404d536d8d\b\build-release"
boost/1.85.0: RUN: b2 -q target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=D:\.conan\p\boost3d2f750c7d701\s\src\tools\build\user-config.jam -sNO_ZLIB=1 -sNO_BZIP2=1 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=off --disable-iconv threading=multi visibility=hidden link=shared variant=release --with-atomic --with-chrono --with-container --with-date_time --with-exception --with-filesystem --with-iostreams --with-locale --with-log --with-program_options --with-random --with-regex --with-system --with-thread toolset=clang-win cxxstd=17 define=_GLIBCXX_USE_CXX11_ABI=1 pch=on linkflags="-stdlib=libstdc++" cxxflags="-fPIC -stdlib=libstdc++" install --prefix=D:\.conan\p\b\boost404404d536d8d\p -j12 --abbreviate-paths -d0 --debug-configuration --build-dir="D:\.conan\p\b\boost404404d536d8d\b\build-release"
conanvcvars.bat: Activating environment Visual Studio 18 - amd64 - winsdk_version=None - vcvars_ver=14.5
[DEBUG:ext\vcvars.bat] Found potential v145 version file: 'Microsoft.VCToolsVersion.VC.14.50.18.0.txt'
[DEBUG:ext\vcvars.bat] Testing v145 version file: 'Microsoft.VCToolsVersion.VC.14.50.18.0.txt'
[vcvarsall.bat] Environment initialized for: 'x64'
notice: found boost-build.jam at D:/.conan/p/boost3d2f750c7d701/s/src/boost-build.jam
notice: loading B2 from D:/.conan/p/b242e6c94b9af14/p/bin/.b2/build-system.jam
notice: Searching 'C:\WINDOWS' 'C:\Users\Todiq' 'C:\Users\Todiq' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\build' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\contrib' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\options' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\tools' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\util' 'D:/.conan/p/b242e6c94b9af14/p/bin/.b2' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in 'C:\WINDOWS' 'C:\Users\Todiq' 'C:\Users\Todiq' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\build' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\contrib' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\options' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\tools' 'D:\.conan\p\b242e6c94b9af14\p\bin\.b2\util' 'D:/.conan/p/b242e6c94b9af14/p/bin/.b2'.
notice: Loading explicitly specified user configuration file:
    D:\.conan\p\boost3d2f750c7d701\s\src\tools\build\user-config.jam
notice: Searching 'D:\.conan\p\boost3d2f750c7d701\s\src\tools\build' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'D:/.conan/p/boost3d2f750c7d701/s/src/tools/build'.
warning: toolset clang-win initialization:
warning: can not find user-provided command 'clang-cl'
warning: initialized from D:\.conan\p\boost3d2f750c7d701\s\src\tools\build\user-config.jam:3
D:/.conan/p/b242e6c94b9af14/p/bin/.b2/tools\clang-win.jam:81: in clang-win.init from module clang-win
error: Cannot configure toolset clang-win: no 'clang-cl.exe' command found or given
D:/.conan/p/b242e6c94b9af14/p/bin/.b2/build\toolset.jam:44: in toolset.using from module toolset
D:/.conan/p/b242e6c94b9af14/p/bin/.b2/build\project.jam:1299: in using from module project-rules
D:\.conan\p\boost3d2f750c7d701\s\src\tools\build\user-config.jam:3: in modules.load from module user-config
D:/.conan/p/b242e6c94b9af14/p/bin/.b2\build-system.jam:258: in load-config from module build-system
D:/.conan/p/b242e6c94b9af14/p/bin/.b2\build-system.jam:464: in load-configuration-files from module build-system
D:/.conan/p/b242e6c94b9af14/p/bin/.b2\build-system.jam:628: in module scope from module build-system

boost/1.85.0: ERROR:
Package 'c9ebbd88af356e31997054e9ec51197a1a277e85' build failed
boost/1.85.0: WARN: Build folder D:\.conan\p\b\boost404404d536d8d\b\build-release
ERROR: boost/1.85.0: Error in build() method, line 1167
        self.run(full_command)
        ConanException: Error 1 while executing
```


EDIT : Replacing `tools.build:compiler_executables = {"c": "clang-cl", "cpp": "clang-cl", "rc": "llvm-rc"}` by  `tools.build:compiler_executables = {"c": "C:/Program Files/LLVM/bin/clang-cl.exe", "cpp": "C:/Program Files/LLVM/bin/clang-cl.exe", "rc": "C:/Program Files/LLVM/bin/llvm-rc.exe"}`  fixes the issue

**Pull request closed without merging**
