### PR TITLE
Doxygen: Add 1.9.8, 1.10.0 and 1.11.0; delete all older versions

### PR DESCRIPTION
**Pull request by Croydon**
- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Edit: Whoops, I totally missed #22052. Anyway, I am doing things differently here and a few things more. Let's see what CI says about it.

FYI; I have also opened https://github.com/doxygen/doxygen/issues/10887 / https://github.com/doxygen/doxygen/pull/10888 so that we can hopefully get rid of the Iconv patches entirely at some point.

### CODE REVIEW

**Comment by Croydon** [comment]
> [HOOK - conan-center.py] post_package(): ERROR: [DEFAULT PACKAGE LAYOUT (KB-H013)] Unknown folder 'share' in the package (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H013-DEFAULT-PACKAGE-LAYOUT)

**Comment by Croydon** [comment]
I am not sure what the failure is about, can't reproduce locally and I also didn't see the actual error in the CI logs yet.

**Comment by Croydon** [comment]
Not sure what to do here.

I can perfectly build it locally with Conan 1.x and the profile that fails on CI:
```
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]
[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True
```

And those errors are not saying anything:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\configvalues.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\configimpl.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\configimpl_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\configimpl.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\configimpl.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\configoptions.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\configvalues.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\src\src\CMakeLists.txt' exited with code 2. [C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\src\doxycfg.vcxproj]
  Building Custom Rule C:/J/workspace/prod-v1/bsr/54057/bdbfa/.conan/data/doxygen/1.9.8/_/_/build/97b1d706abc58b6e57549e40a5608035fa4c8e41/src/libversion/CMakeLists.txt
  doxyversion.cpp
  gitversion.cpp
  fullversion.cpp
  doxygen_version.vcxproj -> C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\lib\Debug\doxygen_version.lib
  Generating ../generated_src/code.l, ../generated_src/code.corr, ../generated_src/code.d
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\code.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\code.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\commentcnv.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\commentcnv.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\commentscan.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\commentscan.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\constexp.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\constexp.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\declinfo.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\declinfo.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\defargs.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\defargs.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\doctokenizer.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\doctokenizer.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\fortrancode.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\fortrancode.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\fortranscanner.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\fortranscanner.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\lexcode.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\lexcode.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\lexscanner.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\lexscanner.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pre.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pre.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pycode.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pycode.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pyscanner.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pyscanner.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\scanner.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\scanner.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\sqlcode.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\sqlcode.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\vhdlcode.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\vhdlcode.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\xmlcode.l.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\xmlcode.l.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\code_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\code.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\commentcnv_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\commentcnv.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\commentscan_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\commentscan.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\constexp_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\constexp.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\declinfo_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\declinfo.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\defargs_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\defargs.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\doctokenizer_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\doctokenizer.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\fortrancode_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\fortrancode.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\fortranscanner_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\fortranscanner.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\lexcode_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\lexcode.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\lexscanner_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\lexscanner.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pre_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pre.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pycode_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pycode.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pyscanner_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\pyscanner.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\scanner_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\scanner.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\sqlcode_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\sqlcode.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\vhdlcode_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\vhdlcode.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\xmlcode_intermediate.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\xmlcode.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\ce_parse.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\configvalues.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\ce_parse.h.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\CMakeFiles\41b6f16312164d438e59d8f07198748b\resources.cpp.rule;C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\src\src\CMakeLists.txt' exited with code 2. [C:\J\workspace\prod-v1\bsr\54057\bdbfa\.conan\data\doxygen\1.9.8\_\_\build\97b1d706abc58b6e57549e40a5608035fa4c8e41\build\src\doxymain.vcxproj]
```

**Comment by RubenRBS** [comment]
Pinging @uilianries who has some experience fighting doxygen issues :)

**Comment by Croydon** [comment]
Seems like 1.9.4 is fine, 1.9.5 introduced the problem and the issue still exists until the latest release.

**Comment by Croydon** [comment]
Closing for now. I don't know how to debug this remotely in CI nor do I have the time to dig into it.

**Pull request closed without merging**
