### PR TITLE
Rename `boost-ext-ut` to `ut`

### PR DESCRIPTION
**Pull request by krzysztof-jusiak**
Problem:
- UT is not an official Boost library and it can't use boost name.

Solution:
- Rename the package name to ut instead.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
What about the organization/code? Is that going to be rebranded further?

**Comment by Croydon** [comment]
Not sure about this, but IF it should get renamed, then the current recipe with the current name has to be marked as deprecated, the files copied to the new directory and then re-named.

I also have the same question as @prince-chrismc, if the name is so controversial then the GitHub organization should be renamed. This packaged got its name by applying the `<author>-<package>` naming convention.

**Comment by mathbunnyru** [comment]
@krzysztof-jusiak  could you please ask to add you to the EAP here?
#4

**Comment by claremacrae** [comment]
I would prefer this not to be renamed, as it will break builds.

**Comment by prince-chrismc** [comment]
The real boost organization has enough force to make this change (and assume US laws the right as well)

It's up to @krzysztof-jusiak to update the recipe so that it does not break consumers

**Comment by claremacrae** [comment]
> The real boost organization has enough force to make this change (and assume US laws the right as well)
> 
> It's up to @krzysztof-jusiak to update the recipe so that it does not break consumers

Oh I think I misunderstood - if it's Boost that's driving the change, then I understand - thank you.

**Comment by prince-chrismc** [comment]
> if it's Boost that's driving the change

That's my assumption 😃

**Pull request closed without merging**
