### PR TITLE
Add Facebook Folly

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **folly/2020.02.07.00**

This PR brings the latest version available for Folly, but also an old version from 2018 (it's the only Conan package version which is working for Bincrafters).

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Folly 2020 is a bit broken. It only works with libstdc++11 and there are many issues complaining about error when building. I gonna invest some time over 2019, which is green on their CI (the latest version green on CI).

**Comment by uilianries** [comment]
Folly is working!

**Comment by Croydon** [comment]
Wait until their next commit is breaking again everything (kinda like grpc) 🙃 

But for now, good job! 🎉 🎈

**Comment by uilianries** [comment]
> 
> 
> Wait until their next commit is breaking again everything (kinda like grpc) 🙃
> 
> But for now, good job! 🎉 🎈

Folly is terrible, they merge without checking first, there is no verification for Windows. Each release is a surprise.

**Pull request merged**
