### PR TITLE
cglm: update for conan 2.0 and add ver 0.8.9

### PR DESCRIPTION
**Pull request by kuroneko**
Specify library name and version:  **cglm/0.8.5** and **cglm/0.8.9**

This updates cglm's recipes to work with conan 2.0 and adds 0.8.9 (the current stable version).

(We use cglm in internal projects and are updating to avoid being orphaned by Conan 2.0).

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by memsharded — APPROVED** [review]

**Comment by memsharded** [comment]
Hi @kuroneko 

Thanks very much for your contribution, and sorry for the delay in reviewing it, we are quite swamped.
Could you please check and sign the CLA again? it seems it forgot it.

It seems some hook check is failing here, I will have a look.

**Comment by memsharded** [comment]
It seems the problem was that the ``shared`` and ``fPIC`` options were not being removed when ``header_only``, I have contributed https://github.com/conan-io/conan-center-index/pull/16738/commits/2de26edcdd5480f8c4150c8ec799806c7a5d184a, so hopefully that fixes it.

**Comment by memsharded** [comment]
Hi @kuroneko 

I managed to put the build in green for both 1.X and 2.0 with the latest changes, this is only pending your CLA signing, please check it when possible, thanks! 🙂

**Comment by memsharded** [comment]
Hi  @kuroneko 

This PR is only missing your CLA signing to be merged, could you please have a look and sign it? (Sorry if you had to to it twice, there were some reset in the service, that required re-signing CLA). Many thanks!

**Comment by uilianries** [comment]
Hello @kuroneko 👋 Friendly ping to sign the CLA point here: https://github.com/conan-io/conan-center-index/pull/16738#issuecomment-1486000222

It would be great merging your PR, but the CLA is a mandatory condition first.

**Comment by kuroneko** [comment]
Sorry for the delay - I set up this PR some time ago so I missed the request to sign CLA amongst other noise.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
