### PR TITLE
dfp: New Conan package

### PR DESCRIPTION
**Pull request by agdavydov81**
Add initial version if the Conan package for the [DFP](https://github.com/epam/DFP/)/1.0.2

C/C++ support is a new feature of the DFP (Decimal Floating Point) public library.
This library is developed by the [EPAM](https://github.com/epam/) company under Apache-2.0 and Intel licenses.

---

- [+] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [+] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [+] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Let us know if we can help you with getting these changes thru the finish line @agdavydov81 :)

**Comment by agdavydov81** [comment]
@RubenRBS Thank you very much
Could you please help me with current PR
https://github.com/conan-io/conan-center-index/pull/21102

**Comment by agdavydov81** [comment]
Seems I do not understand how correctly move all sources and scripts to sub-folder.

**Comment by RubenRBS** [comment]
Oh sorry I didn't see the pr, let's continue the conversation there, sorry about the noise :)

**Pull request closed without merging**
