### PR TITLE
tree-sitter: add new version 0.24.3

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **tree-sitter/0.24.3**

#### Motivation
There are several of improvements since 0.23.1.

#### Details
https://github.com/tree-sitter/tree-sitter/compare/v0.23.1...v0.24.3

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by ErniGH — DISMISSED** [review]
LGTM Thanks

**Comment by AbrilRBS** [comment]
I've asked @perseoGI to take a look at it, as he has experience with this library :)

**Review by perseoGI — APPROVED** [review]
LGTM! This is an amazing library, used by conan team to build our yet to release linter

**Review by ErniGH — APPROVED** [review]
Thanks!

**Pull request merged**
