### PR TITLE
(minor): set cmake_find_mode as 'both' for spdlog

### PR DESCRIPTION
**Pull request by kexianda**
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Why exactly do you think this should be changed, to my knowledge there is no module find file 🤔 https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html#find-modules

Is there some other official on that exists?

**Comment by SpaceIm** [comment]
why?

**Comment by uilianries** [comment]
@prince-chrismc I think is because it documented here: https://github.com/conan-io/conan-center-index/blob/3f4ce2ebdf9ed24cf12b27de6358e63a30eb9a0b/docs/v2_migration.md#translating-names-information-to-cmake_target_name-cmake_module_target_name-and-cmake_file_name

@kexianda We really avoid `both` property. Please, explain what does not work for you without it, also, add some log and your conan profile.

**Comment by prince-chrismc** [comment]
Hmm the docs could be more clear 🤔 

image

Modules should always match upstream or an official source, as long as there a good reference for why this is the case it can be accepted 😄

**Comment by SSE4** [comment]
> Modules should always match upstream or an official source, as long as there a good reference for why this is the case it can be accepted smile

is there a good reason not to use `both` always? because that way both `find_package(MyPackage MODULE)` and `find_package(MyPackage CONFIG)` work. regardless of the upstream (upstream even may not know/use CMake at all, but consumers may do).

**Comment by prince-chrismc** [comment]
🤔 The whole idea is to be transparent, right? So you should be able to seamlessly switch from upstream to conan (or back) and it should work without change yout build scripts.

If we start providing incorrect information, you would not be able to build the project using upstream.
We want to remove all the Conan specific stuff with 2.0 so the reasoning is only the correct/official targets (and find package files in this case) will be generated.

Obviously the trade-off is people need to write good build scripts but hopefully they already where?

**Comment by SSE4** [comment]
> thinking The whole idea is to be transparent, right? So you should be able to seamlessly switch from upstream to conan (or back) and it should work without change yout build scripts.

yes. I have experienced numerous times a situation like below:

1. there is a upstream project (let it be ffmpeg)
1.a. ffmpeg doesn't build via CMake
1.b. ffmpe galso doesn't install any CMake find modules or config files
1.c. there is no "official" find module or config file in public CMake repository
2. there is a consumer project (let it be KDE, for instance)
2.a. KDE doesn't use conan
2.b. KDE uses CMake to build
2.c. KDE uses CMake to find and consume ffmpeg project as a dependency
2.d. there are some hand-written module/config files in the source directory of KDE (usually, something like `<project root>/cmake/modules`)
2.e. consumer project uses either `find_package(ffmpeg CONFIG)` or `find_package(ffmpeg MODULE)`

now, you try to build KDE via conan consuming ffmpeg from conan center as a dependency, and you want to make it fully transparent, and avoid any patching of KDE's sources.
the only way you can support this (frequent enough) use case is to use `cmake_find_mode = both` in ffmpeg recipe.
I hope it explains the situation better.

**Comment by prince-chrismc** [comment]
That's exactly why I am asking why this change is needed 😄 

spdlog is build with CMake and does provide find package config files so it does not fall in that corner case... if another project requires module files then we should fix that downstream project 😄

**Comment by prince-chrismc** [comment]
I am glad we're able to help you find the issue! 

Thansk for the follow up :) don't hesitate to ask questions

**Pull request closed without merging**
