### PR TITLE
[ncurses] Add conan 2.0 compatibility

### PR DESCRIPTION
**Pull request by samuel-emrys**
This is a continuation of previous attempts to add conan 2 compatibility in https://github.com/conan-io/conan-center-index/pull/16780 and https://github.com/conan-io/conan-center-index/pull/15062

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by samuel-emrys** [comment]
@madebr I resurrected this PR (originally authored in https://github.com/conan-io/conan-center-index/pull/16780) in the hope of resolving its issues and getting ncurses integrated for conan 2.0. It looks to already be in a really good state, but it's currently failing on shared MSVC builds (see the error in CI) - it's failing to build the terminfo database. There appears to be very little in the way of error messages or logs for me to latch onto here, so I'm having a hard time identifying what the problem actually is.

To make matters worse, I'm also having a hard time getting the 1.x variant to work to identify the difference between the two recipes.

I noticed that you were responsible for upstreaming MSVC compatibility a few years ago in https://github.com/mirror/ncurses/pull/1 - wondering if you're able to point me in the right direction here? Any ideas what might be breaking? Any help you can provide is appreciated.

**Comment by madebr** [comment]
Comparing the failed log with the output of [these logs](https://github.com/conan-io/conan-center-index/pull/15062#issuecomment-1416683014), the only difference I see is conan v2 adding `DESTDIR=..` to `make install`.

**Comment by samuel-emrys** [comment]
bump

**Comment by benny-edlund** [comment]
Bump

**Pull request closed without merging**
