### PR TITLE
Feature/eigen 3.4.0

### PR DESCRIPTION
**Pull request by CAMOBAP**
**eigen/3.4-rc1**

#4806 onnxruntime/1.7.1 required `> eigen/3.3.9`, **eigen/3.4-rc1**
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SSE4 — DISMISSED** [review]

**Comment by theirix** [comment]
Shouldn't we wait for a release instead of accepting a release candidate? I think it's a good idea to keep PR as a tested draft until Eigen produces a full release.

**Comment by CAMOBAP** [comment]
@theirix this option works for me also because I still working on other issues related to https://github.com/conan-io/conan-center-index/issues/4806

**Comment by CAMOBAP** [comment]
@theirix from another side we newer know when the release will happen, but we can suspend merge to this till other issues will be resolved

**Comment by prince-chrismc** [comment]
Given the activity of this project we can wait until the last minute to merge if it's a blocker...

**Comment by uilianries** [comment]
We usually don't accept RC, Alpha, Beta and so on... I would prefer waiting  for the final version.

**Comment by sunbubble** [comment]
Version 3.4.0 has been released https://gitlab.com/libeigen/eigen/-/releases/3.4.0

**Comment by CAMOBAP** [comment]
PR updated to 3.4

**Comment by sunbubble** [comment]
> PR updated to 3.4

Awesome! Maybe it's a good idea to update the PR title as well

**Comment by CAMOBAP** [comment]
@sunbubble done, should I rename branch name as well? But it this case probably I will need to open another PR...

**Comment by sunbubble** [comment]
> @sunbubble done, should I rename branch name as well? But it this case probably I will need to open another PR...

I'm not a maintainer here. But your branch name will only matter in the merge commit

**Review by jgsogo — APPROVED** [review]
👍 

---

No need to do anything with branch name

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
> But your branch name will only matter in the merge commit

The bot actually uses the PR title to make the merge commit 😸

**Review by uilianries — APPROVED** [review]

**Pull request merged**
