### PR TITLE
Add assimp 5.1.0

### PR DESCRIPTION
**Pull request by ZombieRaccoon**
**assimp/5.1.0**

I wanted to avoid creating a separate recipe for the new minor version, so I went on to make the existing one a bit more generic. I recommend that the two commits be reviewed separately, since the cumulative changes in `conanfile.py` are deemed as a deletion and an addition owing to a minor change in the containing folder name.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]
Regularly, we don't publish unstable versions. Is there a good reason for having this version?

**Review by Croydon — CHANGES_REQUESTED** [review]
(Did not mean to approve)

**Comment by ZombieRaccoon** [comment]
> Regularly, we don't publish unstable versions. Is there a good reason for having this version?

It's been almost two years since the last release (5.0.1 @ https://github.com/assimp/assimp/releases) and countless sought-after changes and bug fixes were accumulated in the meantime that the community desires to get its hands on.

**Comment by ZombieRaccoon** [comment]
> I am in favour of waiting a stable release.

Can I consider this a final decision, or is this a matter of debate within the community? If it was final, then I would just close the pull request for now.

**Comment by SpaceIm** [comment]
> > I am in favour of waiting a stable release.
> 
> Can I consider this a final decision, or is this a matter of debate within the community? If it was final, then I would just close the pull request for now.

I'm not the maintainer of conan-center-index, so it's a debate yes.

**Comment by uilianries** [comment]
@ZombieRaccoon do you know when the next stable release will come, or at least, have an idea? If it's far to be released, and you need this RC version, I'm fine accepting this PR. It's an exception, but not first time we have it. For instance, Taocpp also have Beta releases, but not a stable release still defined.

**Comment by ZombieRaccoon** [comment]
@uilianries I'll contact the maintainer to see if anything specific is on the horizon.

**Comment by uilianries** [comment]
@ZombieRaccoon Thank you! We had some cases where the maintainer generated a new release only because we asked to release a package.

**Comment by SpaceIm** [comment]
Likely not for tomorrow: https://github.com/assimp/assimp/projects/4

**Comment by SpaceIm** [comment]
released: https://github.com/assimp/assimp/releases/tag/v5.1.0

**Comment by ZombieRaccoon** [comment]
I updated the pull request to take 5.1.0 instead of the release candidate.

**Review by uilianries — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
