### PR TITLE
websocketpp: support gcc 12

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **websocketpp/***

websocketpp failed to be compiled on gcc 12 by following constructor/destructor definitions.

```
    ~endpoint<connection,config>() {}
```

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jcar87** [comment]
Hi @toge  - thanks for your contribution. Has this issue been reported upstream to the websocketpp maintainers, or has this already been fixed in their more recent releases?

**Comment by toge** [comment]
@jcar87 
Thank your comment.
I am going to create issue on upstream after investigation of old compilers.

**Comment by toge** [comment]
@jcar87 
It has been mentioned there.
https://github.com/zaphoyd/websocketpp/issues/991

I added patch_source. 
Thanks.

**Comment by prince-chrismc** [comment]
Hi @zaphoyd, I would love to become a maintainer to websocketpp 🙏 My job has a 20% rules for open-source and I would love to put some of my time keeping your amazing work alive 😻

**Pull request merged**
