### PR TITLE
Add opengrm/1.3.8

### PR DESCRIPTION
**Pull request by npuichigo**
Specify library name and version:  **opengrm/1.3.8**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by npuichigo** [comment]
hi @uilianries, I have no idea why the compilation is killed `g++: fatal error: Killed signal terminated program cc1plus`

**Comment by uilianries** [comment]
@npuichigo Congrats, it seems like you broke the compiler 💥  I'll run locally and try to print the stack. Thank you for pinging!

**Comment by npuichigo** [comment]
@uilianries kindly ask do u have any findings？

**Comment by uilianries** [comment]
@npuichigo That's weird. I executed the same build line locally and worked for me. Need more investigation.

**Comment by npuichigo** [comment]
@uilianries That sounds like the compiler is getting killed by the OOM-killer due to using to many resources. Is it possible to restrain the resource like thread numbers during building in CI? It seems to ust `-j3` by default.

**Comment by npuichigo** [comment]
@uilianries After struggling many many times, finally it works with limited build resource. Please help to sign off.

**Comment by npuichigo** [comment]
@SSE4 @czoido

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
Amazing!

**Pull request merged**
