### PR TITLE
- [hdf4] fix cross-building

### PR DESCRIPTION
**Pull request by SSE4**
Specify library name and version:  **hdf4/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jgsogo — CHANGES_REQUESTED** [review]
Testing failed for `shared` libraries (while cross-building to M1):

https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/6188/2-tapaholes/hdf4/4.2.15//summary.json

**Comment by SSE4** [comment]
the error is puzzling one:
```
CMake Error at build/853d1c7044e2ba537c862f0cf073dcb51d12d798/FindJPEG.cmake:39 (add_library):
  Attempting to use @rpath without CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG being
  set.  This could be because you are using a Mac OS X version less than 10.5
  or because CMake's platform configuration is corrupt.
```
I'll take a look, but no promises

**Comment by jgsogo** [comment]
> the error is puzzling one:
> 
> ```
> CMake Error at build/853d1c7044e2ba537c862f0cf073dcb51d12d798/FindJPEG.cmake:39 (add_library):
>   Attempting to use @rpath without CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG being
>   set.  This could be because you are using a Mac OS X version less than 10.5
>   or because CMake's platform configuration is corrupt.
> ```
> 
> I'll take a look, but no promises

👍  If not possible (now), just raise InvalidConfig

**Review by jgsogo — APPROVED** [review]
🙌  https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/6188/3-tapaholes/hdf4/4.2.15//summary.json

**Review by danimtb — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
