### PR TITLE
[mongo-cxx-driver] separate patches, experimental polyfill, general cleanup

### PR DESCRIPTION
**Pull request by mathbunnyru**
Specify library name and version:  **mongo-cxx-driver/3.6.1**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by daravi** [comment]
Might want to also add `required_conan_version = ">=1.28.0"` to the top. (is that when components were merged?)

**Review by prince-chrismc — CHANGES_REQUESTED** [review]
Freaking amazing, please follow https://github.com/conan-io/conan-center-index/pull/3820#issuecomment-742833919 👍

**Comment by mathbunnyru** [comment]
Done, thanks

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]
I am okay with changes, but next time please use a more descriptive title (e.g. what exactly is an improvement - it helps to review) :)

**Comment by mathbunnyru** [comment]
Thanks, @SSE4 . Changed the name now, to make it easier for someone who will be opening this PR.

**Review by uilianries — APPROVED** [review]

**Pull request merged**
