### PR TITLE
allow libigl to be built as lib

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **libigl/2.3.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
Relates to https://github.com/conan-io/conan-center-index/pull/5542

**Comment by AndreyMlashkin** [comment]
@jgsogo , there is no build with header_only=False, there are only five that are explicitly set it to True (which is default) and therefore marked as duplicated

**Comment by jgsogo** [comment]
> @jgsogo , there is no build with header_only=False, there are only five that are explicitly set it to True (which is default) and therefore marked as duplicated

This is how it works: **the CI adds another configuration with `header_only=True`** if the option `header_only` is available in the recipe. So, if `header_only=True` is already the default, it will add that new configuration, but it will be already duplicated.

Use default `header_only=False` and it will generate all the configurations and it will add one more with `header_only=True`.

**Review by SSE4 — APPROVED** [review]

**Comment by Croydon** [comment]
> This is how it works: **the CI adds another configuration with `header_only=True`** if the option `header_only` is available in the recipe. So, if `header_only=True` is already the default, it will add that new configuration, but it will be already duplicated.
> 
> Use default `header_only=False` and it will generate all the configurations and it will add one more with `header_only=True`.

Is that something that CCI could improve? Adding `header_only=False` when `header_only` is `True` by default? Feels like an unnecessary restriction

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
