### PR TITLE
libcurl: honor default upstream values of with_ca_bundle & with_ca_path options

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/13910

Some explanation: https://github.com/conan-io/conan-center-index/issues/13910#issuecomment-1298379737

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Do we not install the cli tool? maybe we could run that https://github.com/conan-io/conan-center-index/blob/ad07569efce52c2478ef304f17a4d7287a03a6d3/recipes/libcurl/all/test_package/conanfile.py#L29 with a simple get one a "local" resource to make sure the it's working?

**Comment by prince-chrismc** [comment]
> I haven't had the chance to look at it yet, but planning to get to it within a couple hours. Will let you know when I've tested.

❤️ thats soo much !

**Comment by LunarWatcher** [comment]
Sorry for the delay, took me a little bit to figure out the test setup and test build. I can confirm it works; the bundle is listed in the config, and the test from the issue works like it's meant to now.

```
configure: Configured to build curl/libcurl:

  Host setup:       x86_64-pc-linux-gnu
  Install prefix:   /
  Compiler:         clang
   CFLAGS:          -m64 -fPIC -O3 -Qunused-arguments
   CPPFLAGS:        -DNDEBUG -isystem /home/olivia/.conan/data/zlib/1.2.13/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/include -isystem /home/olivia/.conan/data/openssl/1.1.1q/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/include -isystem /home/olivia/.conan/data/zlib/1.2.13/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/include -isystem /home/olivia/.conan/data/openssl/1.1.1q/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/include -isystem /home/olivia/.conan/data/openssl/1.1.1q/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/include/openssl
   LDFLAGS:         -m64 -L/home/olivia/.conan/data/zlib/1.2.13/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/lib -L/home/olivia/.conan/data/openssl/1.1.1q/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/lib -L/home/olivia/.conan/data/zlib/1.2.13/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/lib -L/home/olivia/.conan/data/openssl/1.1.1q/_/_/package/24d596ecc3e7cfef35630620092c5615473ba82a/lib
   LIBS:            -lssl -lcrypto -lz -lz -lssl -lcrypto -ldl -lpthread -lrt

  curl version:     7.80.0
  SSL:              enabled (OpenSSL)
  SSH:              no      (--with-{libssh,libssh2})
  zlib:             enabled
  brotli:           no      (--with-brotli)
  zstd:             no      (--with-zstd)
  GSS-API:          no      (--with-gssapi)
  GSASL:            no      (libgsasl not found)
  TLS-SRP:          enabled
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=no, Static=yes
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   /etc/ssl/certs/ca-certificates.crt
  ca cert path:     no
  ca fallback:      no
  LDAP:             no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS:            no      (--enable-ldaps)
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  PSL:              no      (--with-libpsl)
  Alt-svc:          enabled (--disable-alt-svc)
  HSTS:             enabled (--disable-hsts)
  HTTP1:            enabled (internal)
  HTTP2:            no      (--with-nghttp2, --with-hyper)
  HTTP3:            no      (--with-ngtcp2, --with-quiche)
  ECH:              no      (--enable-ech)
  Protocols:        DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS MQTT POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP
  Features:         AsynchDNS HSTS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets alt-svc libz
```
```
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /home/olivia/build/bad-libcurl/build
-- Conan: Compiler Clang>=8, checking major version 14
-- Conan: Checking correct version: 14
-- Configuring done
-- Generating done
-- Build files have been written to: /home/olivia/build/bad-libcurl/build

❯ make
[ 50%] Building CXX object CMakeFiles/bad-libcurl.dir/Main.cpp.o
[100%] Linking CXX executable bin/bad-libcurl
[100%] Built target bad-libcurl

❯ ./bin/bad-libcurl 
Status code: 200
Fail: 
```

So yeah, this PR fixes it. Thank you!

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
> Fail: 
> (empty is good, I didn't bother adding a conditional for whether the "Fail" bit should be printed if there isn't an error message because I'm lazy :p)

Just made my day! Cheers!

**Review by uilianries — APPROVED** [review]

**Pull request merged**
