### PR TITLE
fix libressl build error with Visual Studio 2022

### PR DESCRIPTION
**Pull request by xyz1001**
Specify library name and version:  **libressl/3.0.2**

Compiling libressl/3.0.2 with Visuao Studio 2022 will fail. Here are part of error output.
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt_malloc.h(125,24): error C2485: 'constant': unrecognized extended attribute (compiling source file C:\Users\zgzf1\.conan\data\libressl\3.0.2\_\_\build\2b1be0a8976ecd1cd27d7c3d01af9a8d736344f8\source_subfolder\crypto\ui\ui_openssl_win.c) [C:\Users\zgzf1\.conan\data\libressl\3.0.2\_\_\build\2b1be0a8976ecd1 cd27d7c3d01af9a8d736344f8\source_subfolder\crypto\crypto.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt_malloc.h(132,24): error C2485: 'constant': unrecognized extended attribute (compiling source file C:\Users\zgzf1\.conan\data\libressl\3.0.2\_\_\build\2b1be0a8976ecd1cd27d7c3d01af9a8d736344f8\source_subfolder\crypto\ui\ui_openssl_win.c) [C:\Users\zgzf1\.conan\data\libressl\3.0.2\_\_\build\2b1be0a8976ecd1 cd27d7c3d01af9a8d736344f8\source_subfolder\crypto\crypto.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt_malloc.h(140,24): error C2485: 'constant': unrecognized extended attribute (compiling source file C:\Users\zgzf1\.conan\data\libressl\3.0.2\_\_\build\2b1be0a8976ecd1cd27d7c3d01af9a8d736344f8\source_subfolder\crypto\ui\ui_openssl_win.c) [C:\Users\zgzf1\.conan\data\libressl\3.0.2\_\_\build\2b1be0a8976ecd1 cd27d7c3d01af9a8d736344f8\source_subfolder\crypto\crypto.vcxproj]                                                                          
```

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by danimtb — APPROVED** [review]

**Comment by uilianries** [comment]
@xyz1001 Please, pass it directly to cmake definition in the recipe, as we a middle of a migration to Conan v2. The CMake wrapper is no longer used on Conan v2 and soon should be deprecated.

**Comment by xyz1001** [comment]
@uilianries I do not know how to add a C/C++ macro in the recipe. Is there any example?

**Comment by uilianries** [comment]
@xyz1001 No, because it should be patched to the upstream. Please, in case you identify a bug in the project, report directly to the upstream, so anyone, including the author, could have a proper hotfix.

**Comment by xyz1001** [comment]
@uilianries  This bug is fixed in libressl 3.5.x. But 3.0.2 may not be fixed.

**Comment by uilianries** [comment]
@xyz1001 No problem, you can apply a patch here in CCI too. Please, take a look about patch policy: https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/sources_and_patches.md#policy-about-patching

**Review by toge — APPROVED** [review]

**Pull request merged**
