### PR TITLE
Qt6: fix cppstd

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **qt/6.***

fixes https://github.com/conan-io/conan-center-index/issues/20921

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6823590010)

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
I gave a try to `QT_HOST_PATH` for cross compilation but I got this failure:
```
CMake Error at qtbase/cmake/QtSetup.cmake:260 (find_package):
  Could not find a package configuration file provided by "Qt6HostInfo" with
  any of the following names:

    Qt6HostInfoConfig.cmake
    qt6hostinfo-config.cmake

  Add the installation prefix of "Qt6HostInfo" to CMAKE_PREFIX_PATH or set
  "Qt6HostInfo_DIR" to a directory containing one of the above files.  If
  "Qt6HostInfo" provides a separate development package or SDK, be sure it
  has been installed.
```
This happens because `Qt6HostInfoConfig.cmake` is removed in `def package(self)` to satisfy the hooks.
The module only contains [variables declarations](https://github.com/qt/qtbase/blob/8753bb3045d020bcae33eed67a2770a4709ac7b8/cmake/QtHostInfoConfig.cmake.in#L4)

qt tries to find this file with [`find_package(Qt6HostInfo CONFIG ..)`](https://github.com/qt/qtbase/blob/8753bb3045d020bcae33eed67a2770a4709ac7b8/cmake/QtPublicDependencyHelpers.cmake#L216C9-L216C33)

Unfortunately, conan is currently not able to generate several config files for a given package (`Qt6Config.cmake` and `Qt6HostInfoConfig.cmake` in this case) cf https://github.com/conan-io/conan/issues/9000 and https://github.com/conan-io/conan/issues/14373

If someone creative wants to push investigations on cross compilation further, do not hesitate

**Comment by jwillikers** [comment]
> I gave a try to `QT_HOST_PATH` for cross compilation but I got this failure:
> 
> ```
> CMake Error at qtbase/cmake/QtSetup.cmake:260 (find_package):
>   Could not find a package configuration file provided by "Qt6HostInfo" with
>   any of the following names:
> 
>     Qt6HostInfoConfig.cmake
>     qt6hostinfo-config.cmake
> 
>   Add the installation prefix of "Qt6HostInfo" to CMAKE_PREFIX_PATH or set
>   "Qt6HostInfo_DIR" to a directory containing one of the above files.  If
>   "Qt6HostInfo" provides a separate development package or SDK, be sure it
>   has been installed.
> ```
> 
> This happens because `Qt6HostInfoConfig.cmake` is removed in `def package(self)` to satisfy the hooks. The module only contains [variables declarations](https://github.com/qt/qtbase/blob/8753bb3045d020bcae33eed67a2770a4709ac7b8/cmake/QtHostInfoConfig.cmake.in#L4)
> 
> qt tries to find this file with [`find_package(Qt6HostInfo CONFIG ..)`](https://github.com/qt/qtbase/blob/8753bb3045d020bcae33eed67a2770a4709ac7b8/cmake/QtPublicDependencyHelpers.cmake#L216C9-L216C33)
> 
> Unfortunately, conan is currently not able to generate several config files for a given package (`Qt6Config.cmake` and `Qt6HostInfoConfig.cmake` in this case) cf [conan-io/conan#9000](https://github.com/conan-io/conan/issues/9000) and [conan-io/conan#14373](https://github.com/conan-io/conan/issues/14373)
> 
> If someone creative wants to push investigations on cross compilation further, do not hesitate

Would it be possible to solve this by putting the file in a path specified in `cpp_info.builddirs`?

**Comment by ericLemanissier** [comment]
changing the folder would not change the situation. [the hook looks for config files in all directories](https://github.com/conan-io/hooks/blob/master/hooks/conan-center.py#L1181)
What needs to be done is that the file must be renamed to anything not ending in `config.cmake` inside `package(self)`. Then, in `generate(self)` this file should be copied to the generators folder, and renamed to `Qt6HostInfoConfig.cmake`. But qt will still fail to find it because the [`find_packackage` call has `NO_DEFAULT_PATH` option](https://github.com/qt/qtbase/blame/8753bb3045d020bcae33eed67a2770a4709ac7b8/cmake/QtPublicDependencyHelpers.cmake#L216C9-L216C33) so cmake looks only in QT_HOST_PATH. We'd have to patch `QtPublicDependencyHelpers.cmake` to make it search in the generators folder instead, but this is starting to beyond the time I have available for this task, so don't hesitate to take the relay, I'm dropping the ball.

**Comment by sabelka** [comment]
What I tried back then was to rename `Qt6HostInfoConfig.cmake` to `qt_host_info.cmake` in `package(self)` and then create a new `Qt6HostInfoConfig.cmake` in generate(self) which includes `qt_host_info.cmake` and `conan_qt_executables_variables.cmake`.

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
To add more context, you can see at https://github.com/qt/qtbase/blob/8d367dec156c1aa63544bd851809caa7e72d307e/qt_cmdline.cmake#L141-L165 that when using qt's `configure` script (which wraps cmake configuration), enabling any c++ standard also enables all the previous c++ standards.

**Comment by ericLemanissier** [comment]
merged in https://github.com/conan-io/conan-center-index/pull/21263

**Pull request closed without merging**
