### PR TITLE
[scip] bump version to 9.0.1

### PR DESCRIPTION
**Pull request by hedtke**
Specify library name and version:  **scip/9.0.1**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by hedtke** [comment]
@uilianries I have bigobj problem related to the one we discussed here: https://github.com/conan-io/conan-center-index/pull/22917#issuecomment-1971454736

It does not seem to be a problem with conan 2. Is it an acceptable solution to set the minimum conan version for this recipe to conan 2?

**Comment by uilianries** [comment]
@hedtke Unfortunately we can't because Conan 1.x is still mandatory (at some point of this year we drop Conan 1.x support for ConanCenterIndex). Now about your specific case, it seems be related to https://github.com/conan-io/conan-center-index/pull/24008/files#diff-a91cae4b3a8951ebf40919b64afb15c6354779080996831d8729facdd2bb6ec1R119. I'll do a local test to validate, and bring some result here. Thank you for pinging!

**Comment by uilianries** [comment]
@hedtke I just checked locally with Conan 2.3.0 and the same error occurred:

```
 objnodesel.cpp
  objpresol.cpp
  objpricer.cpp
  objprobdata.cpp
  objprop.cpp
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\scip\reader_nl.cpp(267,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\scip\reader_nl.cpp(298,38): warning C4101: 'e': unreferenced local variable [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
  objreader.cpp
  objrelax.cpp
  objsepa.cpp
  objtable.cpp
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\scip\reader_nl.cpp(1638,1): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\scip\reader_nl.cpp(1643,1): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
  objvardata.cpp
  lpi_spx2.cpp
  compute_symmetry_bliss.cpp
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\scip\exprinterpret_cppad.cpp(1861,45): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\bliss\include\bliss/graph.hh(78,36): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\symmetry\compute_symmetry_bliss.cpp) [C:\Users\uilia\.co nan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\bliss\include\bliss/graph.hh(210,41): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\symmetry\compute_symmetry_bliss.cpp) [C:\Users\uilia\.c onan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\boost41521d32a0ebc\p\include\boost/multiprecision/gmp.hpp(2284,39): warning C4267: 'argument': conversion from 'size_t' to 'mp_bitcnt_t', possible loss of data (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85 c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\boost41521d32a0ebc\p\include\boost/multiprecision/gmp.hpp(2289,32): warning C4267: 'argument': conversion from 'size_t' to 'mp_bitcnt_t', possible loss of data (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85 c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\boost41521d32a0ebc\p\include\boost/multiprecision/gmp.hpp(2294,32): warning C4267: 'argument': conversion from 'size_t' to 'mp_bitcnt_t', possible loss of data (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85 c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\boost41521d32a0ebc\p\include\boost/multiprecision/gmp.hpp(2299,32): warning C4267: 'argument': conversion from 'size_t' to 'mp_bitcnt_t', possible loss of data (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85 c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex/stablesum.h(76,9): warning C4177: #pragma 'float_control' should only be used at global scope or namespace scope (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85c359915879b \b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp(354,1): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex/solverational.hpp(5384,54): warning C4101: 'E': unreferenced local variable (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex/solverational.hpp(5243): message : while compiling class template member function 'soplex::SPxSolverBase<soplex::Real>::Status soplex::SoPlexBase<soplex::Real>::_solveRealForRational(bool,soplex::VectorBase<R> &,soplex::VectorBase<R> &,soplex::DataArray< soplex::SPxSolverBase<R>::VarStatus> &,soplex::DataArray<soplex::SPxSolverBase<R>::VarStatus> &)' [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
          with
          [
              R=soplex::Real
          ] (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp)
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex/solverational.hpp(2113): message : see reference to function template instantiation 'soplex::SPxSolverBase<soplex::Real>::Status soplex::SoPlexBase<soplex::Real>::_solveRealForRational(bool,soplex::VectorBase<R> &,soplex::VectorBase<R> &,soplex::DataArra y<soplex::SPxSolverBase<R>::VarStatus> &,soplex::DataArray<soplex::SPxSolverBase<R>::VarStatus> &)' being compiled [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
          with
          [
              R=soplex::Real
          ] (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp)
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex.hpp(1990): message : while compiling class template member function 'const soplex::SVectorRational &soplex::SoPlexBase<soplex::Real>::colVectorRational(int) const' (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2 .cpp) [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex/solverational.hpp(3566): message : see reference to function template instantiation 'const soplex::SVectorRational &soplex::SoPlexBase<soplex::Real>::colVectorRational(int) const' being compiled (compiling source file C:\Users\uilia\.conan2\p\b\scip85c35 9915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex.hpp(3682): message : while compiling class template member function 'void soplex::SoPlexBase<soplex::Real>::clearLPRational(void)' (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b \scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex.hpp(8690): message : see reference to function template instantiation 'void soplex::SoPlexBase<soplex::Real>::clearLPRational(void)' being compiled (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\ uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex.hpp(1109): message : while compiling class template member function 'int soplex::SoPlexBase<soplex::Real>::numRows(void) const' (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\sc ip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex.hpp(771): message : see reference to function template instantiation 'int soplex::SoPlexBase<soplex::Real>::numRows(void) const' being compiled (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uili a\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex.hpp(9151): message : while compiling class template member function 'soplex::SoPlexBase<soplex::Real>::SoPlexBase(void)' (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85c35 9915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp(243): message : see reference to function template instantiation 'soplex::SoPlexBase<soplex::Real>::SoPlexBase(void)' being compiled [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\sople3864fb77b1913\p\include\soplex.hpp(128): message : see reference to class template instantiation 'soplex::SoPlexBase<soplex::Real>' being compiled (compiling source file C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp) [C:\Users\uilia\.conan2\p\b\scip85c3599158 79b\b\build\src\libscip.vcxproj]
C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\src\src\lpi\lpi_spx2.cpp : fatal  error C1128: number of sections exceeded object file format limit: compile with /bigobj [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]
cl : command line  error D8040: error creating or communicating with child process [C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build\src\libscip.vcxproj]

scip/9.0.1: ERROR:
Package 'f3ba7d90bb821ab5ad21aa1c2b72f349c08e7c68' build failed
scip/9.0.1: WARN: Build folder C:\Users\uilia\.conan2\p\b\scip85c359915879b\b\build
ERROR: scip/9.0.1: Error in build() method, line 134
        cmake.build(target="libscip")
        ConanException: Error 1 while executing
```

The thing is we no longer build Debug + Windows for Conan 2.0 due the small number of download and make the CI result faster. As side-effect, some errors like this one could happen in Conan 1.x but not be listed by Conan 2.x CI.

I would suggest adding an invalid configuration for this case. We could pass /bigobj directly, but then we need to confirm with the upstream first. TBH, I didn't find any related topic in https://github.com/scipopt/scip and did not search in the mail list because there is search bar there. As this case is particular to Debug and msvc, I also didn't find in other package managers like conda. 

```
def validate(self):
    if Version(self.version) >= "9.0.1" and is_msvc(self) and self.settings.build_type == "Debug":
        # lpi_spx2.cpp : fatal  error C1128: number of sections exceeded object file format limit: compile with /bigobj
        raise ConanInvalidConfiguration(f"{self.ref} can not be build in Debug with MSVC.")
```

**Comment by hedtke** [comment]
@uilianries thank you, I added your suggestion to the validation

**Review by uilianries — APPROVED** [review]
LGTM

**Review by toge — APPROVED** [review]

**Pull request merged**
