### PR TITLE
glog: fix transitive traits to gflags & `_cmake_new_enough()` for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/16337

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jcar87 — DISMISSED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
I also take advantage of this PR to fix https://github.com/conan-io/conan-center-index/issues/16337. gflags is indeed a public dependency of glog.

**Comment by EstebanDugueperoux2** [comment]
Hi @SpaceIm,

Thanks for your works.
Do you know what is bad in continuous integration about this PR?

Regards.

**Comment by SpaceIm** [comment]
@EstebanDugueperoux2 Nothing specific to this PR, c3i is under maintenance for almost 2 weeks.

**Comment by uilianries** [comment]
@EstebanDugueperoux2 Please, check status.conan.io

**Review by jcar87 — APPROVED** [review]

**Pull request merged**
