### PR TITLE
paho-mqtt-cpp: update paho-mqtt-c dep to 1.3.5 + add components

### PR DESCRIPTION
**Pull request by Croydon**
- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

_______________

Context: https://github.com/conan-io/conan-center-index/issues/2574#issuecomment-684512081 and https://github.com/conan-io/conan-center-index/issues/2574#issuecomment-684541579

### CODE REVIEW

**Comment by Croydon** [comment]
@danimtb @jgsogo It failed but the bot did not post logs?

**Comment by uilianries** [comment]
2 days ago we had an internal trouble.

**Comment by Croydon** [comment]
```
ERROR: Missing binary: paho-mqtt-c/1.3.4:22dbc490b4cc3d6c6ac77d96a05ed9cf9d2f1dd7
paho-mqtt-c/1.3.4: WARN: Can't find a 'paho-mqtt-c/1.3.4' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Debug, compiler=clang, compiler.version=7.0, os=Linux
- Options: asynchronous=True, fPIC=True, samples=False, shared=False, ssl=False
- Dependencies: 
- Requirements: 
- Package ID: 22dbc490b4cc3d6c6ac77d96a05ed9cf9d2f1dd7

ERROR: Missing prebuilt package for 'paho-mqtt-c/1.3.4'
Try to build from sources with "--build=paho-mqtt-c"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

```

I saw in another PR that `libcurl` packages are missing too for no obvious reason. Maybe this is related?

**Comment by uilianries** [comment]
@Croydon Probably. Thanks for reporting!

**Comment by Croydon** [comment]
Still missing packages

**Comment by danimtb** [comment]
Let's try again now that https://github.com/conan-io/conan-center-index/pull/2426 was merged

**Comment by danimtb** [comment]
Something is happening with this recipe as I see the packages for paho-mqtt-c are available. I'll look into it

**Comment by jgsogo** [comment]
Problem here is the value for the `paho-mqtt-c:ssl` option. Default value is `True`, while this recipe has default `paho-mqtt-cpp:ssl=False` that forces `paho-mqtt-c:ssl=False`. That's the reason of the missing package error.

**Comment by Croydon** [comment]
@jgsogo Thanks for the hint. The default of `paho-mqtt-c:SSL` was changed when `1.3.4` was added

https://github.com/conan-io/conan-center-index/commit/370846d9fb9b9228d739051a6c7516ed974b926e

That is why it broke

**Comment by keysight-daryl** [comment]
Yeah see I don't know or remember if what problems I had with building C++ was but it wasn't working for me on our CI systems either and ultimately I ended up hacking a much older version of the C++ package we have in-house to the new C and that is what we are still using.  In any case the new C has been released and that will need additional updates in the upstream C++ wrapper to support so maybe all this needs wrapped up in one push to 1.3.6

**Comment by Croydon** [comment]
(Weird, didn't I post this already?)

paho-mqtt-cpp seems to use `find_package()` only on macOS and Linux, so we need the `cmake_find_package` generator too

**Comment by Croydon** [comment]
@danimtb labels can be removed

Ready for review 😄

**Review by danimtb — APPROVED** [review]

**Review by uilianries — CHANGES_REQUESTED** [review]
Consider https://github.com/bincrafters/conan-center-index/pull/15

**Comment by Croydon** [comment]
Thanks @uilianries!

**Comment by Croydon** [comment]
Ready for review (again) 😄

**Review by uilianries — APPROVED** [review]
LGTM

**Review by danimtb — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by keysight-daryl** [comment]
I tried updating our c and cpp packages with conan-center-index latest and am getting conan create errors now for both the c and cpp packages that seems to be some issue with the new cmake_find_package_multi stuff that has been recently added... I don't really have an understanding of what this new stuff does but I can no longer create either of the paho packages anymore.

[find-package-multi-issue.txt](https://github.com/conan-io/conan-center-index/files/5366361/find-package-multi-issue.txt)

**Comment by Croydon** [comment]
@keysight-daryl Please open a new issue so we can better track it

**Comment by keysight-daryl** [comment]
mentioning @fpagliughi (https://github.com/fpagliughi) as there may be some synergy between upstream wanting a better cmake build process (https://github.com/eclipse/paho.mqtt.cpp/issues/286) and conan needing one from upstream and knowing the best practices to use...

**Pull request merged**
