### PR TITLE
libpng: use version range for zlib

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **libpng/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
blocks:
- https://github.com/conan-io/conan-center-index/pull/19644

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6108739527)

**Comment by SpaceIm** [comment]
> libpng: use version range for glib

You mean for zlib?

**Comment by ericLemanissier** [comment]
Yes, thanks!

**Review by SpaceIm — APPROVED** [review]

**Comment by RubenRBS** [comment]
Hi @ericLemanissier thanks a lot for your contribution.

In order to avoid missing binaries & conflicts, we're holding off from merging zlib bumps to versions ranges. We are handling this internally and will create the appropriate PRs in order. 
([See the note in here](https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges))

When it's time for this recipe to be merged, we'll use this PR to keep your contribution, and we'll take care of the rest of the recipes, no need to open new PRs with them :)

**Pull request closed without merging**
