### PR TITLE
add paho-mqtt-c/1.3.8

### PR DESCRIPTION
**Pull request by Croydon**
Specify library name and version:  **paho-mqtt-c/1.3.8**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
I have not applied the CMake patch for this, since it is kinda unclear what it is for and it seems to work just fine without

That said, this patch goes back to the original recipe in https://github.com/conan-community/conan-paho-c

And it seems like @uilianries wrote the patch in order to "Install only SSL when required"

https://github.com/conan-community/conan-paho-c/commits/stable/1.3.0/0002-fix-cmake-install.patch

// @icraggs

**Comment by prince-chrismc** [comment]
It also apears to delete some of the test targets https://github.com/conan-io/conan-center-index/blob/1f93611dcd748361ec7551f99f525f70d5c15d05/recipes/paho-mqtt-c/all/patches/0004-fix-cmake-install.patch#L523

**Comment by Croydon** [comment]
True, but they are excluded anyway:

https://github.com/eclipse/paho.mqtt.c/blob/317fb008e1541838d1c29076d2bc5c3e4b6c4f53/src/CMakeLists.txt#L320

https://cmake.org/cmake/help/latest/prop_tgt/EXCLUDE_FROM_ALL.html

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by a4z — APPROVED** [review]
just a note:
the still used pack fix MingGW and OSX, seems to have nothing to do with OSX and MingGW

all it does is removing the -MD flag

```
 IF(WIN32)
-  ADD_DEFINITIONS(-D_CRT_SECURE_NO_DEPRECATE -DWIN32_LEAN_AND_MEAN -MD)
+  ADD_DEFINITIONS(-D_CRT_SECURE_NO_DEPRECATE -DWIN32_LEAN_AND_MEAN)
 ELSEIF(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
   ADD_DEFINITIONS(-DOSX)
 ENDIF()
```

so the name is a bit misleading .. ?

(and I wonder if this patch is needed at all ?)


PS: 
this seems the way to handle that, but requires cmake 3.15 , what is actually ok, but paho is still on 2.8.??
https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html

**Review by SpaceIm — APPROVED** [review]

**Comment by SpaceIm** [comment]
> 
> 
> just a note:
> the still used pack fix MingGW and OSX, seems to have nothing to do with OSX and MingGW
> 
> all it does is removing the -MD flag
> 
> ```
>  IF(WIN32)
> -  ADD_DEFINITIONS(-D_CRT_SECURE_NO_DEPRECATE -DWIN32_LEAN_AND_MEAN -MD)
> +  ADD_DEFINITIONS(-D_CRT_SECURE_NO_DEPRECATE -DWIN32_LEAN_AND_MEAN)
>  ELSEIF(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
>    ADD_DEFINITIONS(-DOSX)
>  ENDIF()
> ```
> 
> so the name is a bit misleading .. ?
> 
> (and I wonder if this patch is needed at all ?)
> 
> PS:
> this seems the way to handle that, but requires cmake 3.15 , what is actually ok, but paho is still on 2.8.??
> https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html

patch name is misleading, but I'm pretty sure this patch is required. MD shouldn't be forced.

**Comment by a4z** [comment]
I wonder if anyone is successfully using this recipe in the version

I get strange errors, 

I do not have them with the 1.3.7 version, that was successfully ignored here , https://github.com/conan-io/conan-center-index/pull/3834

difference is in the cmake files, here all the patches are missing ....

```
duplicate symbol '_SHA1_Init' in:
    /Users/a4z/elux/nsdk/.conan/data/paho-mqtt-c/1.3.8/_/_/package/c0e6b2a0b169ea50c3ed9c3ac7f2ea9f2263e4b5/lib/libpaho-mqtt3a.a(SHA1.c.o)
    /Users/a4z/elux/nsdk/.conan/data/openssl/1.1.1i/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libcrypto.a(sha1dgst.o)
duplicate symbol '_SHA1_Final' in:
    /Users/a4z/elux/nsdk/.conan/data/paho-mqtt-c/1.3.8/_/_/package/c0e6b2a0b169ea50c3ed9c3ac7f2ea9f2263e4b5/lib/libpaho-mqtt3a.a(SHA1.c.o)
    /Users/a4z/elux/nsdk/.conan/data/openssl/1.1.1i/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libcrypto.a(sha1dgst.o)
duplicate symbol '_SHA1_Update' in:
    /Users/a4z/elux/nsdk/.conan/data/paho-mqtt-c/1.3.8/_/_/package/c0e6b2a0b169ea50c3ed9c3ac7f2ea9f2263e4b5/lib/libpaho-mqtt3a.a(SHA1.c.o)
    /Users/a4z/elux/nsdk/.conan/data/openssl/1.1.1i/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libcrypto.a(sha1dgst.o)
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by a4z** [comment]
also that erorr, what does that mean

```
duplicate symbol '_MQTTClient_strerror' in:
    /Users/a4z/elux/nsdk/.conan/data/paho-mqtt-c/1.3.8/_/_/package/c0e6b2a0b169ea50c3ed9c3ac7f2ea9f2263e4b5/lib/libpaho-mqtt3c.a(MQTTClient.c.o)
    /Users/a4z/elux/nsdk/.conan/data/paho-mqtt-c/1.3.8/_/_/package/c0e6b2a0b169ea50c3ed9c3ac7f2ea9f2263e4b5/lib/libpaho-mqtt3cs.a(MQTTClient.c.o)
```
this , libpaho-mqtt3cs.a / libpaho-mqtt3c.a 
is super strange .... 

@Croydon , do you actually use that package in a project ?

**Comment by SpaceIm** [comment]
`libpaho-mqtt3c` and `libpaho-mqtt3cs` shouldn't be package together.

AFAIK, it was the purpose of `fix-cmake-install.patch` to filter build and installation of libs. I thought that it was fixed upstream in 1.3.8 since you didn't add this patch in this version :s

**Comment by a4z** [comment]
yes, just tested, I built 1.3.8 base on  #3834 where I adopted the cmake patches so they work with the new files

I haven't tested all the profile I use, but that one I did work.

I have pretty strong negative feelings for this package, its wasting my time like no other package 😠 
This cmake should be fixed upstream, it is a mess. But after the author behaved so bad against me, I will not do that.
But this needs to be fixed upstream , the patches are nearly not reproducible, when the upstream project again does changes with files, it will be hard to adopt the patches , did it once and do not want to do it again

**Comment by a4z** [comment]
I committed a fix 
https://github.com/conan-io/conan-center-index/pull/4293

**Comment by prince-chrismc** [comment]
@a4z I know your pain #4096 took me a week to understand, the team responsible for those projects is not interested upgrading the CMake, there's little we can do 🤷 

Based on Space's comments above, we need to use explicit libs to avoid the patches, I might follow up on this next week

**Pull request merged**
