### PR TITLE
Some 2.0 modernizations to Cpython

### PR DESCRIPTION
**Pull request by memsharded**
Specify library name and version:  **cpython**

---
- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by tannerbitz** [comment]
@memsharded would you like some help with this?  I would be happy to help get the cpython recipe working with conanv2

**Comment by samuel-emrys** [comment]
> @memsharded would you like some help with this? I would be happy to help get the cpython recipe working with conanv2

If you'd like to help, it would be useful to help make sure all of the dependencies have been migrated to conan 2 - I'm not sure how far this recipe will get without them.

**Comment by AndreyMlashkin** [comment]
@memsharded , what should be used instead AutoToolsBuildEnvironment? 

Also, please consider merging my PR to your draft

**Comment by AndreyMlashkin** [comment]
That's sad :(

**Pull request closed without merging**
