### PR TITLE
openssl: add versions `3.0.15`, `3.1.7`, `3.2.3`, `3.3.2`

### PR DESCRIPTION
**Pull request by gegles**
### Summary
Changes to recipe:  **openssl/[3.0.15, 3.1.7, 3.2.3, 3.3.2]**

#### Details

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by exief — APPROVED** [review]
changes look good to me; eagerly await merge

**Comment by gegles** [comment]
> changes look good to me; eagerly await merge

Hello @exief ... Sadly, the Windows builds are failing and most likely the patch steps will need to be tweak for this version... but I am no expert and don't really have the setup for it, so I am hoping somebody else will be able to look into it and add the tweaks to this branch/PR...

**Comment by exief** [comment]
> > changes look good to me; eagerly await merge
> 
> Hello @exief ... Sadly, the Windows builds are failing and most likely the patch steps will need to be tweak for this version... but I am no expert and don't really have the setup for it, so I am hoping somebody else will be able to look into it and add the tweaks to this branch/PR...
> 

The changes made for 3.3.1 by @jcar87 on previous PR should be working here too weird that it isn't 

Unfortunately I don't have a windows environment to test on at present either

**Comment by Nekto89** [comment]
I've tried to update workaround on newer OpenSSL code. It changed
```
our @PREFIX                     = ( 'C:\' );
our @libdir                     = ( 'C:\lib' );
```
to
```
our @PREFIX                     = ( 'C:/' );
our @libdir                     = ( 'C:/lib' );
```

https://github.com/Nekto89/conan-center-index/commit/bc448aab59eed237783651342dfc2cd5762ab7ae

**Comment by exief** [comment]
> I've tried to update workaround on newer OpenSSL code. It changed
> 
> ```
> our @PREFIX                     = ( 'C:\' );
> our @libdir                     = ( 'C:\lib' );
> ```
> 
> to
> 
> ```
> our @PREFIX                     = ( 'C:/' );
> our @libdir                     = ( 'C:/lib' );
> ```
> 
> [Nekto89@bc448aa](https://github.com/Nekto89/conan-center-index/commit/bc448aab59eed237783651342dfc2cd5762ab7ae)

@gegles can you incorporate the changes made by @Nekto89 onto your branch and maybe we'll be able to move this PR along

**Review by uilianries — APPROVED** [review]
LGTM.

**Review by samuel-emrys — APPROVED** [review]

**Pull request merged**
