### PR TITLE
pcl: add a patch fixing missing functional include in ply_parser.h

### PR DESCRIPTION
**Pull request by SpaceIm**
### Summary
Changes to recipe:  **pcl/1.13.1**

#### Motivation

An include is missing in `ply_parser.h`, leading to compilation failure for some compilers.

closes https://github.com/conan-io/conan-center-index/issues/24556

#### Details

include of `functional` is missing in `ply_parser.h`. It has been fixed upstream by https://github.com/PointCloudLibrary/pcl/pull/5964 (available since 1.14.1), so this commit is backported as a patch in recipe of 1.13.1

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by perseoGI** [comment]
Hi @SpaceIm, thank you for your contributions!

At conan we try not to be project maintainers. In this case this is fine as upstream has fix the issue. 
I was thinking if patching a minor could be worth it... 
There is an [open PR](https://github.com/conan-io/conan-center-index/pull/22152) which aims to add `v1.14.0`, but it is failing. Maybe we can consider dropping the support for this current version and updating to `v1.14.1` to avoid this patch.

**Review by jcar87 — APPROVED** [review]

**Review by perseoGI — APPROVED** [review]
As it is just a backport we are approving this PR. 
And lets try to add the new version!

**Review by AbrilRBS — APPROVED** [review]

**Comment by SpaceIm** [comment]
Is CI running on this PR?

**Comment by AbrilRBS** [comment]
@SpaceIm there are some infra issues with Jenkins currently, we'll retrigger the PR once it is addressed :)

**Review by AbrilRBS — APPROVED** [review]

**Pull request merged**
