### PR TITLE
[xnnpack] Add xnnpack cci.20220621

### PR DESCRIPTION
**Pull request by talyz**
Specify library name and version:  **xnnpack/cci.20220621**

This is done as part of #11477, but split into a separate PR, since the bot complains. This needs to be merged first!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by talyz** [comment]
There seems to be a conflict between the Conan hook and successfully building the package. If the `fPIC` option is removed when the shared library version is built, I get the following error:
```
/usr/bin/ld: CMakeFiles/allocator.dir/src/memory.c.o: relocation R_X86_64_PC32 against symbol `xnn_allocate_code_memory' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```
If `fPIC` is allowed for shared builds, it succeeds, but instead the Conan hook throws the following error:
```
[HOOK - conan-center.py] pre_build(): ERROR: [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not managed correctly. Please remove it for shared option: del self.options.fPIC (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H007) 
```
Not sure how to solve this conflict.

**Comment by uilianries** [comment]
@talyz fPIC is removed when building shared, because building shared library without fPIC makes almost no sense. That's why the option fPIC is removed. Maybe, fPIC is really missing when building xnnpack as shared.

**Comment by talyz** [comment]
@uilianries Yes, this seems to be one of the few cases where `fPIC` is actually needed when building a shared library, then. At least the build fails without it.

**Comment by talyz** [comment]
Is the assumption that the Makefile should handle this automatically and that's why `fPIC` is removed? Maybe it makes more sense to force it true here rather than deleting the option?

**Comment by uilianries** [comment]
@talyz fpic should be True when shared, it's automatically managed by conan build helpers. In the very past, we forced to true, but we realized that it does not make sense, since fpic + shared is the standard option.

If it fails for you, probably your project is forcing fPIC and a patch.

**Comment by talyz** [comment]
For some reason, that isn't what happens here - the build succeeded if I removed the code that deleted the `fPIC` option, so it obviously made a difference.

I've pushed a new change now that defaults `CMAKE_POSITION_INDEPENDENT_CODE` to true when the `fPIC` option is deleted. This seems to fix the issue locally for me.

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
