### PR TITLE
[boost] [simplification] Out of source build; remove option to use bcp

### PR DESCRIPTION
**Pull request by david-sinuela-pix4d**
Specify library name and version:  **boost/***

This PR changes the build process to build of of the source directory and remove the need for a `_clean` method.

I guess this change can be controversial because it removes the bcp feature. Please let me know if the change is acceptable and/or what would be the impact.

The patch to the bat file was necessary to build from outside of sources, it is also reported upstream in https://github.com/boostorg/boost/pull/354.

### CODE REVIEW

**Comment by david-sinuela-pix4d** [comment]
> boost/1.70.0:
> 
>     * **Error processing recipe: Linux x86_64, Release, gcc 5, libstdc++ . Options:  boost:shared-True**
>       Unexpected error happened:
> 
> 
> ```
> ERROR: /tmp/c3ipr/info_home_pr_509_2/.conan/data/boost/1.70.0/_/_/export/conanfile.py: Error while initializing options. 'options.namespace' doesn't exist
> Possible options are ['shared', 'header_only', 'error_code_header_only', 'system_no_deprecated', 'asio_no_deprecated', 'filesystem_no_deprecated', 'fPIC', 'layout', 'magic_autolink', 'python_executable', 'python_version', 'zlib', 'bzip2', 'lzma', 'zstd', 'segmented_stacks', 'extra_b2_flags', 'without_math', 'without_wave', 'without_container', 'without_contract', 'without_exception', 'without_graph', 'without_iostreams', 'without_locale', 'without_log', 'without_program_options', 'without_random', 'without_regex', 'without_mpi', 'without_serialization', 'without_coroutine', 'without_fiber', 'without_context', 'without_timer', 'without_thread', 'without_chrono', 'without_date_time', 'without_atomic', 'without_filesystem', 'without_system', 'without_graph_parallel', 'without_python', 'without_stacktrace', 'without_test', 'without_type_erasure']
> ```

I forgot to remove the default settings of the options removed. I pushed a fix.

**Comment by SSE4** [comment]
@david-sinuela-pix4d unfortunately, bcp is required thing in many use-cases, many people use custom boost namespace

**Comment by david-sinuela-pix4d** [comment]
@SSE4 thanks for the feedback, I'll check if I can add the `bcp` feature back without too many headaches.

**Comment by danimtb** [comment]
Please solve the conflicts and update this PR to the latest changes in master. Thanks!

**Comment by SSE4** [comment]
I would say this is no longer needed/relevant - with #1016 bootstrap is no longer done as part of boost build, instead `b2` executable used as its own conan package (which also simplifies the recipe and improves cross-building use-cases).

**Pull request closed without merging**
