### PR TITLE
wayland-protocols: Conan V2

### PR DESCRIPTION
**Pull request by jwillikers**
Update for Conan V2.
Use build context for PkgConfigDeps in test package.
Allows cross-compilation.

Specify library name and version:  **wayland-protocols/***

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jwillikers** [comment]
Requires a build profile to be specified. :'(

```
ERROR: wayland-protocols/1.26 (test package): Error in generate() method, line 33
	pkg_config_deps.generate()
	ConanException: The 'build_context_activated' and 'build_context_build_modules' of the PkgConfigDeps generator cannot be used without specifying a build profile. e.g: -pr:b=default
```

**Comment by prince-chrismc** [comment]
Could I talk you into writing a blog like https://github.com/conan-io/conan-io.github.io/pull/226? 🙏 

Even if you give me the bullet points I can make something out of that would be amazing for all the others looking at Meson and what's required

**Comment by prince-chrismc** [comment]
V2 pipeline failed with a java exception 🙈 flagged the infra team :)

**Review by prince-chrismc — APPROVED** [review]

**Comment by jwillikers** [comment]
> Could I talk you into writing a blog like [conan-io/conan-io.github.io#226](https://github.com/conan-io/conan-io.github.io/pull/226)? pray
> 
> Even if you give me the bullet points I can make something out of that would be amazing for all the others looking at Meson and what's required

@prince-chrismc Sure, for Meson in particular? I can start a draft PR like based off the one you've linked this week.

**Comment by prince-chrismc** [comment]
Yes exactly for Meson ❤️ mention me when you do so I fuss with the metadata stuff 😄

**Review by uilianries — APPROVED** [review]
I'll push this recipe as Meson template on docs.

**Comment by uilianries** [comment]
Done: https://github.com/conan-io/conan-center-index/pull/13603/

**Pull request merged**
