### PR TITLE
meson: remove outdated versions

### PR DESCRIPTION
**Pull request by ericLemanissier**
as per https://github.com/conan-io/conan-center-index/issues/2813#issuecomment-815844761

Specify library name and version:  **meson/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jgsogo — COMMENTED** [review]
👍 

Thanks. I agree with this PR. I'm not approving right away because I want other reviewers to have a look at it and we would like to hear anyone that has something to say about it.

Recipes and packages for **the removed versions will always be available in ConanCenter**. Using or not revisions, a consumer will always be able to consume `meson/0.51.0`, the server will resolve to the latest revision of that recipe.

**Review by madebr — DISMISSED** [review]

**Review by prince-chrismc — DISMISSED** [review]

**Comment by uilianries** [comment]
> +1
> 
> Thanks. I agree with this PR. I'm not approving right away because I want other reviewers to have a look at it and we would like to hear anyone that has something to say about it.
> 
> Recipes and packages for **the removed versions will always be available in ConanCenter**. Using or not revisions, a consumer will always be able to consume `meson/0.51.0`, the server will resolve to the latest revision of that recipe.

I agree too.

**Comment by Croydon** [comment]
I would find it much more appealing when the version information would stay in the `conandata.yml` file, so we would still be able to build these versions locally with the current master branch of CCI without any modification.

I understand that these versions would not be tested anymore, but honestly, there are tons of configurations we never test and which can still be built without any modification. 

Maybe we need a way to dynamically add/"trigger" the `deprecated` recipe attribute based on `conandata.yml` values? Then we could let the versions stay in `conandata.yml` while clearly communicate: "not tested"

Or again something like https://github.com/conan-io/conan-center-index/issues/2813

**Comment by ericLemanissier** [comment]
Until a solution is found for #2813, maybe we could simply comment out lines in .yml files, instead of removing them, so at least the information is not lost in git history

**Comment by SSE4** [comment]
I agree, it's better to implement something like:
```
  "0.51.0":
    url: "https://github.com/mesonbuild/meson/archive/0.51.0.tar.gz"
    sha256: "ec1e3942215a858d82c3d2e095d18adcf1ede94a34144662643d88db4dcb5263"
    cci_attributes:
        cci_attribute_untested
  "0.51.2":
    url: "https://github.com/mesonbuild/meson/archive/0.51.2.tar.gz"
    sha256: "96871cf62c9cf2b212e2f38aa3e543323403b1314fd3835e14120ef837c00f01"
```
and if CI reads `cci_attribute_untested`, it just skips version (e.g. `0.51.0`) from the build completely.
meanwhile, consumers should be still able to do `conan create . meson/0.51.0@` locally.
@jgsogo WDYT?

**Comment by ericLemanissier** [comment]
I feel like this information would be better placed in config.yml. conandata.yml is used during the build itself, so it seems conceptually to late to abort the build. Also, conandata.yml ends up in the local cache of consumers, so it'd better be free of CCI specificities.

**Comment by jgsogo** [comment]
If we want to keep that information easily accessible to the future, IMHO I would prefer to comment out those lines. At least the user will get an error, will have a look to `conandata.yml` and it requires an action on their side before submitting an issue with a `meson/0.51.0@` that doesn't work.

**Comment by SSE4** [comment]
> I agree, it's better to implement something like:
> 
> ```
>   "0.51.0":
>     url: "https://github.com/mesonbuild/meson/archive/0.51.0.tar.gz"
>     sha256: "ec1e3942215a858d82c3d2e095d18adcf1ede94a34144662643d88db4dcb5263"
>     cci_attributes:
>         cci_attribute_untested
>   "0.51.2":
>     url: "https://github.com/mesonbuild/meson/archive/0.51.2.tar.gz"
>     sha256: "96871cf62c9cf2b212e2f38aa3e543323403b1314fd3835e14120ef837c00f01"
> ```
> 
> and if CI reads `cci_attribute_untested`, it just skips version (e.g. `0.51.0`) from the build completely.
> meanwhile, consumers should be still able to do `conan create . meson/0.51.0@` locally.
> @jgsogo WDYT?



> I feel like this information would be better placed in config.yml. conandata.yml is used during the build itself, so it seems conceptually to late to abort the build. Also, conandata.yml ends up in the local cache of consumers, so it'd better be free of CCI specificities.

yes, definetely, `config.yml` is much better, I actually wanted this one lol

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Pull request merged**
