### PR TITLE
add config listing sub folders

### PR DESCRIPTION
**Pull request by a4z**
Specify library name and version:  **zlib/1.2.8**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

try to submit both sub folders in the config, sind ***I*** do not add 2 versions, they already exist ..

### CODE REVIEW

**Comment by uilianries** [comment]
It's not required. The CI service will mimic it automatically, it only requires the config.yml when using a generic folder (all), where many one or more versions are shared to the same recipe folder.

**Comment by a4z** [comment]
hm  .... but can we add it ?
because I have tools testing the config.yml si I will never miss to update it
but when this can not exits, I have to add an other branch in the tool .... 
but seriously, what is the recommendation?  
not having the file if there are explicit version folders, or, it can be there and it's ok

**Comment by danimtb** [comment]
It is documented right here https://github.com/conan-io/conan-center-index/wiki#the-version-folders, so this file is not needed

**Comment by a4z** [comment]
ok, thanks for the info!

**Pull request closed without merging**
