### PR TITLE
Qt6: Added option to be able to disable features

### PR DESCRIPTION
**Pull request by Cyriuz**
Follow up PR to #9254 without the bundled dependencies.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — DISMISSED** [review]

**Review by SSE4 — DISMISSED** [review]

**Comment by ericLemanissier** [comment]
What is the modification between this and the commit that was previously approved?

**Comment by Cyriuz** [comment]
Nothing but a rebase and conflict resolve with #9337, what's the usual workflow for this case?

**Comment by ericLemanissier** [comment]
I did not notice the conflict. I thought all CI was green.
In case of merge conflict you usually do a merge, so that we can review the conflict resolution alone

**Comment by Cyriuz** [comment]
Gotcha, yeah the checks were green but the merging said it will conflict with that change so I thought I would be on the ball with that, sorry for the confusion.

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
