### PR TITLE
jemalloc conan2

### PR DESCRIPTION
**Pull request by jabbas**
jemalloc/5.2.1
jemalloc/5.3.0

This is continuation of work of @0xFireWolf from that PR: https://github.com/conan-io/conan-center-index/pull/17722

---

- [*] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [*] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [*] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jabbas** [comment]
If there's a way to distinguish if we are running in container vs native i would add additional check for forcing that vaddr setting

**Review by RubenRBS — COMMENTED** [review]
Hi @jabbas thanks a lot for your patience :)

I've reviewed the PR and it looks good. The only remaining issue is the current build fail, and I'd say this would then bee good to merge!

I've pushed 2 minor fixes to the recipe now that we're on it. I'm worried about the xmalloc thing. This seems to have been a typo of the original PR, as otherwise that option was not used. It seems to work locally for me, but I'd appreciate it if you could double check :)

**Comment by Jihadist** [comment]
Ping. Are there any chances for this pr?

**Comment by RubenRBS** [comment]
Finally ported, closing this one, thanks a lot for your initial contribution! :)

**Pull request closed without merging**
