### PR TITLE
aws-c-http/0.6.5

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **aws-c-http/0.6.5**

ref #6346

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
Any idea why I still have this linker error despite adding shlwapi to the system libs?

```
aws-c-io.lib(file_utils.obj) : error LNK2019: unresolved external symbol __imp_PathFileExistsA referenced in function aws_path_exists [C:\J\w\BuildSingleReference@2\.conan\data\aws-c-
```

**Comment by intelligide** [comment]
> 
> 
> Any idea why I still have this linker error despite adding shlwapi to the system libs?
> 
> ```
> aws-c-io.lib(file_utils.obj) : error LNK2019: unresolved external symbol __imp_PathFileExistsA referenced in function aws_path_exists [C:\J\w\BuildSingleReference@2\.conan\data\aws-c-
> ```

`shlwapi ` must be added to the `system_libs` of `aws-c-io `.

**Comment by MartinDelille** [comment]
> `package_info` is not called when you build the recipe. It's only called when the recipe is used as dependency

So why the test didn't complained about it during aws-c-io CI job?

**Comment by MartinDelille** [comment]
Trying locally the shared profile I have the following error:

```
CMake Error: install(EXPORT "aws-c-http-targets" ...) includes target "aws-c-http" more than once in the export set.                                         
```

**Review by intelligide — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
