### PR TITLE
quill: add version 2.7.0, remove older versions

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **quill/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jwillikers** [comment]
@toge Thanks for adding this new version! Could you add the preprocessor definition `QUILL_X86ARCH` in the `generate` method and the `package_info` method when the architecture matches `x86` or `x86_64`? This is new in version 2.7.0 and will optimize quill for x86.

**Comment by toge** [comment]
@jwillikers 
Thanks a lot for information!
I fixed it.

**Review by jwillikers — APPROVED** [review]
Awesome, thank you!

**Review by jwillikers — DISMISSED** [review]

**Review by jwillikers — DISMISSED** [review]

**Review by prince-chrismc — APPROVED** [review]
FYI the 2.0 fails from syntax if you want to follow up another PR

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
You'll need to re-approve :/

**Review by prince-chrismc — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
