### PR TITLE
add geos/3.8.0

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **geos/3.8.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@SpaceIm consider https://github.com/SpaceIm/conan-center-index/pull/1

**Comment by SpaceIm** [comment]
Seems like build 2 was not really launched on Jenkins

**Comment by uilianries** [comment]
Which build? The latest is the accepted PR, which triggered a build. I looks correct.

**Comment by SpaceIm** [comment]
I can only see one build here: https://c3i.jfrog.io/c3i/misc/logs/pr/829/
The second one is missing.

**Comment by uilianries** [comment]
No, take a look on the comment https://github.com/conan-io/conan-center-index/pull/829#issuecomment-584758145. It's pointing to build 2, it's described on the url.

**Comment by SpaceIm** [comment]
But build 2 has no log. If I click on "All logs here", it points to "{\"error\":\"Item misc:logs/pr/829/2/geos/3.8.0 does not exist\"}"

**Comment by danimtb** [comment]
For some reason, this did not generate any new package on build 2. I am gonna relaunch the job manually. Thanks for reporting @SpaceIm

**Comment by danimtb** [comment]
It seems that only the first commit is taken into account. I will investigate this

**Comment by danimtb** [comment]
Fix for the issue above has been deployed to production. I will relaunch the CI manually for this PR and it should pick the latest commit

**Comment by danimtb** [comment]
It is taking the commit from the tentative merge, so it does not match with the last commit here. I will have to revert the fix and wait until we have a better detection for this 😞

**Comment by danimtb** [comment]
The fix was rolled back and now we are relaunching the CI for this PR. It should behave as it initially did. We will continue working on a fix for this. Please @SpaceIm leave this PR unchanged so we can test a future fix later and sorry again for the inconvenience

**Comment by danimtb** [comment]
For some reason, it picked the right commit now. Relaunching the job again to test it

**Comment by SpaceIm** [comment]
@danimtb Can I push a new commit (fix for MinGW if shared and inline)?

**Comment by danimtb** [comment]
@SpaceIm sorry for the late reply. Sure, go ahead!

**Pull request merged**
