### PR TITLE
sdl: update libiconv

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **sdl/***

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
```
CMake Error at source_subfolder/cmake/sdlchecks.cmake:627 (find_program):
  Could not find WAYLAND_SCANNER using the following names: wayland-scanner
Call Stack (most recent call first):
  source_subfolder/CMakeLists.txt:1262 (CheckWayland)
```

wayland-scanner which is provided by wayland recipe is not detected by sdl.

**Comment by paulocoutinhox** [comment]
My problem is related to this?
https://github.com/conan-io/conan-center-index/issues/11460

**Comment by uilianries** [comment]
@toge and @paulocoutinhox I've added the PR https://github.com/conan-io/conan-center-index/pull/11986 which should fix that error.

**Comment by toge** [comment]
@paulocoutinhox 
I'm sorry for late response.
I comment your issue.

@uilianries 
Thank you for your help.
I will try to build this recipe after your PR will be merged.

**Comment by paulocoutinhox** [comment]
@toge it was merged

**Comment by toge** [comment]
@paulocoutinhox 
Thank you!
I close this PR.

**Pull request closed without merging**
