### PR TITLE
libgettext: .lib extension for msvc import lib

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **libgettext/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

for the same reason than https://github.com/conan-io/conan-center-index/pull/3073

### CODE REVIEW

**Comment by ericLemanissier** [comment]
thanks !  are we sure that this change and #3073 has no adverse effect on other recipes ?

**Comment by SpaceIm** [comment]
I don't know. It should not, except if they rely on hardcoded Visual Studio import lib name.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
I hope it's not breaking, e.g. there are no makefiles looking for hard-coded `gnuintl.dll.lib` name

**Review by ericLemanissier — APPROVED** [review]
Let's try and see, I guess

**Pull request merged**
