### PR TITLE
freetype: use correct versioning scheme for pkg_config

### PR DESCRIPTION
**Pull request by mmomtchev**
Specify library name and version:  **freetype/2.13.2**

Use the correct versioning scheme as described in #22801 - fixes a `FIXME`

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by mmomtchev** [comment]
Do not merge! cairo is not compatible with the versioning, looking for a solution

It seems that the meson generated by conan expects to find a 2.x version

**Comment by mmomtchev** [comment]
These must be changed at the same time, I am removing a workaround for a problem in another library

**Comment by RubenRBS** [comment]
Hi @mmomtchev thanks a lot for your contribution

As per CCI policy (The CI is currently only setup to work under this asumption), a PR may only modify 1 recipe, so we'd appreciate it if you could split this PR into 3, thanks!

**Comment by mmomtchev** [comment]
@RubenRBS The result will be 3 PRs that do not work unless merged together?

**Pull request closed without merging**
