### PR TITLE
meson: add version 0.62.0

### PR DESCRIPTION
**Pull request by ericLemanissier**
Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot)
Find more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)

Specify library name and version:  **meson/0.62.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Are macos workers running python <3.7 ?

**Comment by SSE4** [comment]
> Are macos workers running python <3.7 ?

it's `3.6.13` right now.

**Comment by ericLemanissier** [comment]
OK, so this forbids use of meson 0.62.0 on CC Ihttps://mesonbuild.com/Release-notes-for-0-62-0.html#minimum-required-python-version-updated-to-37 
They say 3.6 has been EOL for 3 months already. Maybe it'd be good to upgrade?

**Comment by SSE4** [comment]
> OK, so this forbids use of meson 0.62.0 on CCI https://mesonbuild.com/Release-notes-for-0-62-0.html#minimum-required-python-version-updated-to-37 They say 3.6 has been EOL for 3 months already. Maybe it'd be good to upgrade?

if it's EOL, it might be a good time to move. we will discuss it, and I'll let you know about decision.

**Comment by SSE4** [comment]
> OK, so this forbids use of meson 0.62.0 on CCI https://mesonbuild.com/Release-notes-for-0-62-0.html#minimum-required-python-version-updated-to-37 They say 3.6 has been EOL for 3 months already. Maybe it'd be good to upgrade?

we're going to upgrade our docker images and Window/macOS python versions to 3.7. no ETA yet, but definetely not earlier than next week.

**Comment by ericLemanissier** [comment]
will be done when CI is upgraded

**Pull request closed without merging**
