### PR TITLE
objectbox: add recipe

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **objectbox/0.17.0**

Try to fix https://github.com/conan-io/conan-center-index/issues/11235.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
```
ConanException: Error 3221225781 while executing bin\test_package
```
It may be caused by failing to find objectbox.dll.
I am going to find the solution...

**Comment by toge** [comment]
@SSE4 
Thank you!

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
FYI this recipe doesn't follow CCI policies. It silently downloads pre-compiled binaries of objectbox at build time instead of building from source.

**Comment by prince-chrismc** [comment]
The implementation of the database is closed but the API and libs are free to distribute. It's an edge case I added it to the shepherds meetings for the team to discuss. Gut reaction this is fine, it did not raise alram bells when I reviewed.

I think it this is not covered under our current guidelines but hopefully we can clarify that :)

**Pull request merged**
