### PR TITLE
Harfuzz: enable glib by default

### PR DESCRIPTION
**Pull request by ericLemanissier**
it's ok now that it builds on windows (and required by several coming libraries, eg pango)

Specify library name and version:  **harfbuzz/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
blocked by https://github.com/conan-io/conan-center-index/pull/2285

**Comment by ericLemanissier** [comment]
blocked by https://github.com/conan-io/conan-center-index/pull/2291

**Comment by ericLemanissier** [comment]
retrigger CI

**Comment by ericLemanissier** [comment]
The build went from [82 binaries](https://conan.io/center/harfbuzz/2.6.8/?user=_&channel=_&tab=overview) to 73.
There was previously 18 windows binaries: (3 msvc versions)*(debug + release)*(static/MT + static/MD + shared/MD)
With glib now rejecting MT(d) runtime, there should be 12 windows binaries: (3 msvc versions)*(debug + release)*(static/MD + shared/MD)
18-12=6, so I would have expected to get 6 fewer binaries, but we get 82-73=9 fewer binaries. We are the 3 missing binaries ?

**Comment by ericLemanissier** [comment]
I just recounted, there should be 4 binaries (debug+release)*(shared+static) for each compiler. There are 19 compilers (3 mac + 6 gcc + 7 clang + 3 msvc), so there should effectively be 19*4 = 76 binaries. The bot says `Generated 73 packages.` but https://c3i.jfrog.io/c3i/misc/logs/pr/2282/3/harfbuzz/2.6.8/ shows only 61 folders. Maybe it's just a problem with the bot ? can we retrigger a build to clear this up ?

**Comment by uilianries** [comment]
@ericLemanissier The detail of generated packages:

Screenshot_2020-07-31 Screenshot


I created a small script to generate for any CCI result, e.g. `main.py https://c3i.jfrog.io/c3i/misc/logs/pr/2282/3/harfbuzz/2.6.8/`

https://gist.github.com/uilianries/4f2e2739a91c10f63b08e078fa0d1ca5

**Comment by ericLemanissier** [comment]
I love your script (really) ! That said the number of builds (61) still makes no sense, and is not coherent with the bot's message ` Generated 73 packages.` (which does not make more sense). So I'm going to blame the CI for being drunk.

**Comment by ericLemanissier** [comment]
and now we get no log at all. the bot does not like this PR :(

**Comment by uilianries** [comment]
Indeed we had a problem with on the last week. I gonna restart again.

**Comment by uilianries** [comment]
Same error!

@jgsogo Could you please check why https://github.com/conan-io/conan-center-index/pull/2282#issuecomment-668184742 shows 73 builds, but actually the link offers 404? It's interesting, because on CI log, I can see the "Computing IDS", but there is no build steps.

**Comment by jgsogo** [comment]
⚠️  The link of the `all logs here` points to the last build-number, but CCI detects packages are already built and runs nothing. They are already available in build number 3: [https://c3i.jfrog.io/c3i/misc/logs/pr/2282/3/harfbuzz/2.6.8/](https://c3i.jfrog.io/c3i/misc/logs/pr/2282/3/harfbuzz/2.6.8/).

**Comment by ericLemanissier** [comment]
the link you showed has only 61 subfolders, whereas the bot reported `Generated 73 packages`. where are the 12 missing folders ?

**Comment by jgsogo** [comment]
Even if build number 1 failed, it was able to build successfully some packages before the failure: https://c3i.jfrog.io/c3i/misc/logs/pr/2282/1/harfbuzz/2.6.8/ Those belong to the same recipe revision and they were already available in the repository, they are not built again

**Comment by jgsogo** [comment]
👍  I'd have done the same, trigger a new build... I really want to know about those packages... but right now I'm very busy with the disk-space in the windows machines, trying to apply a hotfix to alleviate that pain.

I really know the output needs to be improved, something like [this](https://github.com/conan-io/conan-center-index/issues/2145#issuecomment-654818105) is my proposal, it should be much easier to navigate and understand.

**Comment by ericLemanissier** [comment]
finally, 76 builds, as expected !

**Comment by uilianries** [comment]
Thanks a lot @jgsogo!

**Pull request merged**
