### PR TITLE
Meson 0.54.3

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **meson/0.54.3**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
@ericLemanissier 
I'm seeing the following error when using meson:
https://github.com/conan-io/conan-center-index/pull/2000#issuecomment-648901234

Meson contains a cmake script to which KB-H019 complains: `./bin/mesonbuild/cmake/data/preload.cmake`

/cc @uilianries

**Comment by ericLemanissier** [comment]
this hook message happens with all projects consuming meson, in all configurations. The strange part is that the bot reports it only for gcc4.9 configuration,  and if you look at the log, you realize that the failure happens actually later, and is the usual `ninja: relocation error: ninja: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`, so it is actually #213

So there are several issues colliding :

1. as @madebr, I think we should add an exception to the hook to allow this file in meson package.
2. the bot should be checked to understand why this error is only reported in case of build failure
3. #213. In the case of ninja, it could be solved by modifying the recipe to simply download upstream binaries: https://github.com/ninja-build/ninja/releases

**Comment by madebr** [comment]
@ericLemanissier 
I'm seeing this error/warning at the end of `ninja install` ([log here](https://github.com/conan-io/conan-center-index/pull/1013#issuecomment-653563244))
```
Error in atexit._run_exitfuncs:


Traceback (most recent call last):


  File "C:\Python36\lib\site-packages\colorama\ansitowin32.py", line 59, in closed


    return stream.closed


ValueError: underlying buffer has been detached
```

Would it make sense to build/install meson for all operating systems (add `os` to `settings`)
in order to test meson/ninja on all operating systems when creating the meson package?

I'm doing something similar with `autoconf`/`automake`.
Even though these are script-only package, they are available for each operating system as a dedicated package.

**Comment by ericLemanissier** [comment]
regarding pkgconf, I don't have this error on my computer:
```
pkgconf/1.7.3 (test package): Running test()
error callback: C:\pf\conan-center-index\recipes\pkgconf\all\test_package\test_package.c:19 main: test error
-L/usr/lib -lexample1
-I/usr/include/libexample1 -I/usr/include -DEXAMPLE1_STATIC
```
regarding meson, making a PR adding `os` to `settings` should be enough to see if it works ok in CCI's jenkins environment.

**Comment by madebr** [comment]
@ericLemanissier 
I manually create that error message.
It's normal to have one.
So not seeing it is an error.

**Comment by ericLemanissier** [comment]
Yes, I was just trying to show that it did not fail on my machine ;)

**Pull request merged**
