### PR TITLE
pffft: add shared option + cleanup

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Review by theirix — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by ruilvo** [comment]
Thanks for the cleanup, but this won't work on Windows. The header files don't have declspec specifiers for using it on a shared lib scenario and I left the CMakeLists file hardcoded as static. So I suggest adding a ConanInvalidConfig for shared+windows and remove the STATIC hardcoded specifier in the CMakeLists file.

**Comment by SpaceIm** [comment]
I've removed `STATIC` from CMakeLists, and added `WINDOWS_EXPORT_ALL_SYMBOLS` (our friend for shared libraries which don't properly hide/export symbols). This is why it works.

**Comment by ruilvo** [comment]
Ah okay, thanks. I only saw the recipe at first and was confused. Thanks. It looks really great. I pretty much copied the recipe from sqlite, so that one could also use some cleanup, I guess. Thanks again!

**Comment by ruilvo** [comment]
Ah okay, thanks. I only saw the recipe at first and was confused. Thanks. It looks really great. I pretty much copied the recipe from sqlite, so that one could also use some cleanup, I guess. Thanks again!

**Pull request merged**
