### PR TITLE
add botan/2.17.2

### PR DESCRIPTION
**Pull request by reneme**
Specify library name and version:  **botan/2.17.2**

Bumping patch version of Botan. Release notes: https://github.com/randombit/botan/blob/master/news.rst#version-2172-2020-11-13

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — DISMISSED** [review]

**Comment by reneme** [comment]
Frankly, I'm not sure what happened with that build. The last hotfix release (2.17.1) went through smoothly and there is no obvious change between those versions that might result in such a failure on Windows. CI hiccup? Could somebody re-trigger please?

**Comment by hrantzsch** [comment]
@Croydon any idea on this? Maybe really just re-trigger the build?

**Comment by Croydon** [comment]
@reneme can re-trigger CI by closing the PR for ~10 seconds and then re-open it

**Comment by reneme** [comment]
Mhh, I tried that a few days ago but unknowingly skipped the "wait 10 seconds". :) Thanks for the hint.... now, let's see.

**Review by ericLemanissier — DISMISSED** [review]

**Comment by reneme** [comment]
... trying again. Still fairly convinced that something's flaky.

**Comment by hrantzsch** [comment]
FYI @reneme and I are still working on fixing this. There's a problem in Botan's build system where the install command silently fails. Hence `empty package`.
We're trying to reproduce the issue in Botan's CI and fix it. I suspect we'll have to skip 2.17.2 in this recipe and update to the version that fixes it then.

**Comment by reneme** [comment]
Turned out that Botan 2.17.1 introduced a fix for compiling on newer versions of macOS. Specifically, Botan's internal build scripts failed to properly detect the python interpreter due to some `$PATH` and symlink foo (See [this comment for further details](https://github.com/randombit/botan/pull/2526#issuecomment-736506580)). Unfortunately, this introduced build issues on MinGW that were "quickfixed" in 2.17.2 and silently broke Botan's internal installation scripts on Windows with Visual Studio 2015.

The [referenced PR](https://github.com/randombit/botan/pull/2526) introduces a basic check into Botan's CI to validate the installation script result and fixes the issues explained above. I condensed the necessary hunks (minus the Botan CI tests) into a one-shot patch fixing the build of this conan recipe on VS 2015. With the next release of Botan, this patch won't be required any longer.

**Comment by reneme** [comment]
@Croydon We're out of luck here. There was a build error in botan 2.17.2 [that we fixed](https://github.com/randombit/botan/pull/2526) and patched for this recipe. Now CI failed internally for the third time. Please help. :)

**Comment by Croydon** [comment]
I believe CI has some general issues right now affecting many PRs. Pinging @jgsogo

**Review by jgsogo — APPROVED** [review]

**Review by Croydon — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
