### PR TITLE
json-schema-validator: restore correct CMake target name in CMakeDeps

### PR DESCRIPTION
**Pull request by SpaceIm**
handle this regression: https://github.com/conan-io/conan-center-index/pull/13959#discussion_r1022160270

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by garethsb** [comment]
I don't quite understand...

I have a project which has always used the target `nlohmann_json_schema_validator::nlohmann_json_schema_validator`, which worked with the pre- and post-13959 recipe, and having tested it again, doesn't work with this PR.

Did the _cmake_find_package_ generator rely on that alias too, and that's why this recipe uses `_create_cmake_module_alias_targets`?

Why would that no longer be effective when used with the _CMakeDeps_ generator?
It may be the case that this alias was not aligned with the upstream _CMakeLists.txt_, but its absence is unfortunately still a breaking change.


The downstream project is like:

* _conanfile.txt_
  ```
  [requires]
  json-schema-validator/2.1.0
  ```
* _CMakeLists.txt_
  ```
  find_package(nlohmann_json_schema_validator REQUIRED)
  ...
  add_library(json_schema_validator INTERFACE)
  target_link_libraries(json_schema_validator INTERFACE nlohmann_json_schema_validator::nlohmann_json_schema_validator)
  ```

**Comment by SpaceIm** [comment]
It's not a breaking change because CMakeDeps has always produced non-namespaced target until your PR (which was a breaking change). Non-namespaced target is the official upstream target, namespaced target was a side effect of cmake_find_package behavior. Purpose of `_create_cmake_module_alias_targets` was to provide non-namespaced target in cmake_find_package as well.

**Comment by SpaceIm** [comment]
> For sure we need the non-namespaced target back, but this _is_ a breaking change removing the namespaced target. In that a downstream project that previously used this Conan recipe will no longer work.

It doesn't break anything for a given generator. Folks using CMakeDeps were already relying on non-namespaced target, and if it doesn't work for you anymore it's because you have switched from cmake_find_package to CMakeDeps, so a good opportunity to fix your CMakeLists.

**Comment by garethsb** [comment]
OK, makes sense. Thanks very much for the explanation.

**Review by danimtb — APPROVED** [review]

**Review by garethsb — APPROVED** [review]

**Comment by prince-chrismc** [comment]
https://github.com/pboettch/json-schema-validator/blob/56bb4a4af43ee12b81fcf079acd19fda725e732f/CMakeLists.txt#L93

Matches upstream 👍

**Comment by SpaceIm** [comment]
> https://github.com/pboettch/json-schema-validator/blob/56bb4a4af43ee12b81fcf079acd19fda725e732f/CMakeLists.txt#L93

@prince-chrismc this line is irrelevant. The only relevant commande to know wheter an imported target is namespaced or not in install tree is `install(EXPORT ...)`: https://github.com/pboettch/json-schema-validator/blob/56bb4a4af43ee12b81fcf079acd19fda725e732f/CMakeLists.txt#L132-L134

**Comment by prince-chrismc** [comment]
@SpaceIm can you please becareful with your choice of words when answer? 

Instead of what you wrote you could have said

"Hey Chris, I think you might have linked the wrong line. The install function that sets the namespace is actually... and you can see it here"

This would provide a far superior experience to contributors by politely correcting them :)

Hopefully you can apply this advice when interacting with others!

**Pull request merged**
