### PR TITLE
h3: add version 3.7.1

### PR DESCRIPTION
**Pull request by qchateau**
Specify library name and version:  **h3/3.7.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Generated and committed by [conan-center-bot](https://github.com/qchateau/conan-center-bot)

### CODE REVIEW

**Comment by Croydon** [comment]
Could you improve the bot that it does not remove quotes from strings from the yaml files?

I believe it will make trouble with source mirrors, also it is unnecessary re-formatting

**Comment by SpaceIm** [comment]
Also if it could keep original ordering of the files (sources before patches keys, url before sha256 keys in this recipe).

**Comment by qchateau** [comment]
The bot can indeed be changed, though it's always a pain to handle these kind of things. 

You both suggest to "keep the original" but I'd argue it would be cleaner (and easier to automate) if you could define the expected format, such as "always use quotes" and the order of keys

**Comment by SpaceIm** [comment]
Currently, CCI doesn't enforce such format.

All recipes have `sources` before `patches`, it's more natural.

Usually I try to:
- use double quotes around versions, url, sha255, patch_file and base_path values
- ordering: url before sha256, patch_file before base_path, versions in descending order

But as I said, there are no guidelines currently.

**Review by SSE4 — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Then endless battle of do we make it easy for humans to look at or easy for machines to do....

I am solidly in the camp of make it human readable, having the patches -> sources is not intuitive... does a bot really care? I think a few extras to help human make sure the bot isn't on a bender is reasonable future improvement.

That being said, 🏆 amazing work on the bot, it makes life better and I am 100% for it. 👍

**Pull request merged**
