### PR TITLE
onetbb: remove shared option + fix tbbmaloc & tbbproxy logic

### PR DESCRIPTION
**Pull request by SpaceIm**
- regarding removal of shared option: see https://github.com/conan-io/conan/issues/15040#issuecomment-1790753531
- for tbbmaloc & tbbproxy, well current logic was super weird. It comes from https://github.com/conan-io/conan-center-index/pull/17311, but it doesn't really make sense. These options didn't exist before 2021.5.0 or 2021.6.0, so they have to be removed in config_option, that's all.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by valgur — APPROVED** [review]
Thanks! I really hope this fixes the issue.

**Comment by SpaceIm** [comment]
Hum, another option I don't like in this recipe: `interprocedural_optimization`. It shouldn't be an option. There shouldn't be option doing babysitting of compiler flags. And LTO must not be enabled by default (well in shared lib it's harmless but still).

**Comment by SpaceIm** [comment]
@danimtb @uilianries @RubenRBS I'm not even sure it will fix all issues related to missing packages in v2 pipeline. Since onetbb has dependencies, if I remove shared option of onetbb, it will build onetbb flavor with static dependencies only? So if a downstream recipe has a shared option, it will break with shared=True since conancenter won't have the flavor of onetbb with hwloc shared=True, correct?

**Review by jwillikers — APPROVED** [review]

**Review by ilya-lavrenov — APPROVED** [review]

**Review by uilianries — CHANGES_REQUESTED** [review]
Removing the shared option sounds good to me.

I'll block to discuss first with Conan team, in case of side-effects.

We still could list all affected packages and run an internal CI build to regenerate after merging it, but still need to check what could happen with CI composition, like `*/*:shared=True/False` and even mixed (Conan 1.x) for future PRs.

**Comment by uilianries** [comment]
After discussing with Conan team about this situation, indeed the `hwloc` will cause trouble due Conan 2.x CCI build configuration. So our better shot now is restricting `hwloc` to a shared library only.

I opened the PR https://github.com/conan-io/conan-center-index/pull/20976/. That PR should be merged first, then we can update this one and merge it too. 

Thank you @SpaceIm for not only opening the PR, but also sharing your investigation.

**Comment by fschoenm** [comment]
@uilianries Can this be merged now or is there something left to do?

**Comment by SpaceIm** [comment]
I've triggered a new build, now that https://github.com/conan-io/conan-center-index/pull/20976 has been merged.

**Review by uilianries — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
