### PR TITLE
linter workflow: fix linter change test on test_package

### PR DESCRIPTION
**Pull request by ericLemanissier**
it has been broken by https://github.com/conan-io/conan-center-index/pull/15005
the error was
```
line 10: syntax error near unexpected token `)'
```
broken runs:
- https://github.com/conan-io/conan-center-index/actions/runs/3803517584/jobs/6469976580#step:9:26
- https://github.com/conan-io/conan-center-index/actions/runs/4023629343/jobs/6914721612#step:9:26
- https://github.com/conan-io/conan-center-index/actions/runs/4023635893/jobs/6914735878#step:9:26

Instead of taking the 250 first recipes in alphabetical order, use `shuf` to randomize the selection
Also, fix the grouping of error messages, and order by decreasing occurance

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
it's also now faster to run.
Compare [the new run](https://github.com/conan-io/conan-center-index/actions/runs/4025392551)  with [the old run](https://github.com/conan-io/conan-center-index/actions/runs/4025313885)

**Review by danimtb — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by ericLemanissier** [comment]
For review, the last summary generated by this PR: https://github.com/conan-io/conan-center-index/actions/runs/4035760268#summary-10955058022
Sorry for dismissing your reviews @SSE4 @danimtb. I won't touch the PR if no review requests changes.

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
in future, I would love to move script/logic outside of the YAML (as it's a format for data, not for code).
these jq language also isn't something common and well-known.
maybe extracting these blocks to some scripts instead of these one-liners would help.
but PR is overall and improvement, as it leaves less code.

**Review by prince-chrismc — APPROVED** [review]
Can't be worse then already broken :)

**Pull request merged**
