### PR TITLE
nss 3.76

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **nss/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
what's wrong @SSE4 @uilianries ?

**Comment by SSE4** [comment]
> what's wrong @SSE4 @uilianries ?

I don't know, we're am getting a lot of unexpected errors today, under the hood it's just some IOException, unfortunately I have no idea why does it happen :( maybe @danimtb knows

**Comment by ericLemanissier** [comment]
Ready for review

**Review by uilianries — APPROVED** [review]

**Comment by ericLemanissier** [comment]
this blocks

- https://github.com/conan-io/conan-center-index/pull/10094

**Review by MartinDelille — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@jgsogo @toge @intelligide could you please review ? That would allow to make some progress on https://github.com/conan-io/conan-center-index/pull/10094

**Review by intelligide — APPROVED** [review]

**Pull request merged**
