### PR TITLE
[package] dav1d/1.0.0

### PR DESCRIPTION
**Pull request by theirix**
No upstream build changes.
Started modernizing to use Conan v2 helpers.

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
I don't get why doesn't it show an actual error 🤔 
running locally, the error is:
```
ERROR: Error loading conanfile at '/host/bincrafters/conan-center-index/recipes/dav1d/all/conanfile.py': Unable to load conanfile in /host/bincrafters/conan-center-index/recipes/dav1d/all/conanfile.py
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/host/bincrafters/conan-center-index/recipes/dav1d/all/conanfile.py", line 3, in <module>
    from conan.tools.files import rename, get, replace_in_file
ImportError: cannot import name 'replace_in_file' from 'conan.tools.files' (/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conan/tools/files/__init__.py)
```

**Comment by theirix** [comment]
Yes, it's strange. By the way, do you have Conan 1.46.0? It works with this version on my machine.

**Comment by SSE4** [comment]
> Yes, it's strange. By the way, do you have Conan 1.46.0? It works with this version on my machine.

nope, it's 1.44.1 still, we're a bit behind...

**Review by SSE4 — DISMISSED** [review]

**Comment by danimtb** [comment]
Just upgraded to 1.45.0 https://github.com/conan-io/conan-center-index/pull/10045 let's see if that improves something

**Comment by danimtb** [comment]
Same error. We are working on the fix to actually show the error here.

**Comment by theirix** [comment]
Is there any way to deduce from successful build logs the Conan version? It is not logged.

If the CI is on 1.44.1, I wonder why the `required_conan_version` didn't help. Maybe it's because the import error was happened before interpreting the `required_conan_version` value.

**Comment by SSE4** [comment]
I think it would be useful to add conan version to that table: https://github.com/conan-io/conan-center-index/pull/9854#issuecomment-1105305774 (/cc @jgsogo)
at least, now it reports a proper error message, kudos to @uilianries !

**Comment by jgsogo** [comment]
> I think it would be useful to add conan version to that table: [#9854 (comment)](https://github.com/conan-io/conan-center-index/pull/9854#issuecomment-1105305774) (/cc @jgsogo) at least, now it reports a proper error message, kudos to @uilianries !

I think we can add that information **also** to the comment on GitHub:

```
Failure in build 13 (4daa7255c4a5f85c68155b5b8695fa1a46942632) using Conan x.y.z
```

**Review by uilianries — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
