### PR TITLE
[boost] add patch for 1.72

### PR DESCRIPTION
**Pull request by SSE4**
closes: #711

add an official patch from boost release notes: https://www.boost.org/users/history/version_1_72_0.html

Specify library name and version:  **boost/1.72.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@SSE4 Is it another patch's bug, or this patch doesn't comport 1.72 ?

> [1m[36mpatches/0001-revert-cease-dependence-on-range.patch: source file is different - b'boost/coroutine/asymmetric_coroutine.hpp'[0m

**Comment by SSE4** [comment]
the same as https://www.boost.org/patches/1_72_0/0001-revert-cease-dependence-on-range.patch

**Comment by SSE4** [comment]
this is very suspicious an official patch doesn't apply...

**Comment by uilianries** [comment]
I need to check it, maybe that patch tool in Conan is bugged again :disappointed:

**Comment by SSE4** [comment]
okay, it turns out patch was created against the develop, and conan (patch-ng) fails to apply that as source file is different. I had to cherry pick the patch and format it again. with new line numbers, conan is finally happy.

**Comment by danimtb** [comment]
Unexpected error coming from making new commits when this PR has still conflicts. Something to be improved

**Comment by uilianries** [comment]
For some reason, I can't reproduce it when running with the Docker image conanio/gcc5:

https://gist.github.com/uilianries/7472546a1f4c404f29633791cf817252

It works pretty well actually :thinking:

**Comment by SSE4** [comment]
interesting :) I am looking into it

**Comment by SSE4** [comment]
@danimtb seems like build stuck

**Comment by uilianries** [comment]
Yes, 22h to build Boost?

**Pull request merged**
