### PR TITLE
- add vdpau/system

### PR DESCRIPTION
**Pull request by SSE4**
Specify library name and version:  **vdpau/system**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — APPROVED** [review]
all passed on https://github.com/bincrafters/system-packages-checks/actions/runs/533152448

**Comment by Croydon** [comment]
Same here, please always explain why something should be a system package

**Comment by SSE4** [comment]
this is a low-level API implemented by the video driver. basically, same case as mesa (GL API). this could be built from source, but implementation will be useless, as it won't be able to actually decode/encode anything.

**Comment by uilianries** [comment]
have you considered build from sources? The meson file requires only 2 libraries, but they are not in CCI: https://gitlab.freedesktop.org/vdpau/libvdpau/-/blob/master/meson.build

**Comment by SSE4** [comment]
> have you considered build from sources? The meson file requires only 2 libraries, but they are not in CCI: https://gitlab.freedesktop.org/vdpau/libvdpau/-/blob/master/meson.build

it's easy to build from source, just like mesa. but it's basically useless without an actual driver, so it will only cause problems for users who link with our prebuilt binaries.

**Comment by uilianries** [comment]
> it's easy to build from source, just like mesa. but it's basically useless without an actual driver, so it will only cause problems for users who link with our prebuilt binaries.

I see, hard dependent of system. In this case will be better from system package manager, otherwise we would need to enforce build from source for every `conan install` command.

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
have you considered build from sources? The meson file requires only 2 libraries, but they are not in CCI: https://gitlab.freedesktop.org/vdpau/libvdpau/-/blob/master/meson.build

**Review by prince-chrismc — APPROVED** [review]

**Comment by daravi** [comment]
@SSE4 Just wondering is it not possible to model the driver version in settings?

**Comment by SSE4** [comment]
> @SSE4 Just wondering is it not possible to model the driver version in settings?

I think it could be modelled, if it's needed. I don't know, is there a real need for that? feel free to make PR, if you wish.

**Comment by daravi** [comment]
@SSE4 For example see #6960 . This sytem package seems to be missing in my distro so I would need to build it from source. It would be great to have that managed by Conan, but then I would have to add a settings for the video card driver version, is my understanding correct? If so what are the steps to add that settings? Is that going to be in the vdpau/<version> recipe or something that would also need to be done for the Conan client?

**Pull request merged**
