### PR TITLE
Fix openssl old version access to shared option of zlib

### PR DESCRIPTION
**Pull request by czoido**
This access to the cpp_info was creating a new config shared in that object and that finally turned into this error for some users: https://github.com/conan-io/conan/issues/11856

### CODE REVIEW

**Comment by jgsogo** [comment]
Linter output says:

```
Run echo "::add-matcher::linter/recipe_linter.json"
************* Module conanfile
recipes/openssl/1.x.x/conanfile.py:615: [W[14](https://github.com/conan-io/conan-center-index/runs/7882488367?check_suite_focus=true#step:8:15)01(anomalous-backslash-in-string), ] Anomalous backslash in string: '\$'. String constant might be missing an r prefix.
recipes/openssl/1.x.x/conanfile.py:4: [E0611(no-name-in-module), ] No name 'ConanInvalidConfiguration' in module 'conans.errors'
recipes/openssl/1.x.x/conanfile.py:5: [W9006(conan-import-conanfile), ] Import ConanFile from new module: `from conan import ConanFile`. Old import is deprecated in Conan v2.
recipes/openssl/1.x.x/conanfile.py:16: [R0205(useless-object-inheritance), OpenSSLVersion] Class 'OpenSSLVersion' inherits from object, can be safely removed from bases in python3
recipes/openssl/1.x.x/conanfile.py:41: [C0209(consider-using-f-string), OpenSSLVersion.base] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:59: [R1705(no-else-return), OpenSSLVersion.compare] Unnecessary "elif" after "return", remove the leading "el" from "elif"
recipes/openssl/1.x.x/conanfile.py:230: [C0121(singleton-comparison), OpenSSLConan.requirements] Comparison 'self.options.get_safe('no_zlib') == False' should be 'self.options.get_safe('no_zlib') is False' if checking for the singleton value False, or 'not self.options.get_safe('no_zlib')' if testing for falsiness
recipes/openssl/1.x.x/conanfile.py:259: [C0209(consider-using-f-string), OpenSSLConan._target] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:275: [R1705(no-else-return), OpenSSLConan._perlasm_scheme] Unnecessary "elif" after "return", remove the leading "el" from "elif"
recipes/openssl/1.x.x/conanfile.py:292: [R1710(inconsistent-return-statements), OpenSSLConan._asm_target] Either all return statements in a function should return an expression, or none of them should.
recipes/openssl/1.x.x/conanfile.py:327: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:328: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:329: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:330: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:356: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:357: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:358: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:359: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:380: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:381: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:382: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:386: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:387: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:388: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:398: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:399: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:400: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:402: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:403: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:404: [C0209(consider-using-f-string), OpenSSLConan._targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:433: [C0206(consider-using-dict-items), OpenSSLConan._ancestor_target] Consider iterating with .items()
recipes/openssl/1.x.x/conanfile.py:466: [C0209(consider-using-f-string), OpenSSLConan._patch_makefile_org] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:468: [C0209(consider-using-f-string), OpenSSLConan._patch_makefile_org] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:470: [C0209(consider-using-f-string), OpenSSLConan._patch_makefile_org] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:473: [C0209(consider-using-f-string), OpenSSLConan._patch_makefile_org] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:475: [C0209(consider-using-f-string), OpenSSLConan._patch_makefile_org] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:477: [C0209(consider-using-f-string), OpenSSLConan._patch_makefile_org] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:495: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:497: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:498: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:503: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:512: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:537: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:549: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:550: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:556: [C0209(consider-using-f-string), OpenSSLConan._configure_args] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:490: [R0912(too-many-branches), OpenSSLConan._configure_args] Too many branches (21/12)
recipes/openssl/1.x.x/conanfile.py:560: [R0914(too-many-locals), OpenSSLConan._create_targets] Too many local variables (18/[15](https://github.com/conan-io/conan-center-index/runs/7882488367?check_suite_focus=true#step:8:16))
recipes/openssl/1.x.x/conanfile.py:593: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:595: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:596: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:597: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:599: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:600: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:602: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:607: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:609: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:636: [C0209(consider-using-f-string), OpenSSLConan._create_targets] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:657: [C0209(consider-using-f-string), OpenSSLConan._run_make] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:664: [R[17](https://github.com/conan-io/conan-center-index/runs/7882488367?check_suite_focus=true#step:8:18)05(no-else-return), OpenSSLConan._perl] Unnecessary "elif" after "return", remove the leading "el" from "elif"
recipes/openssl/1.x.x/conanfile.py:685: [C0[20](https://github.com/conan-io/conan-center-index/runs/7882488367?check_suite_focus=true#step:8:21)9(consider-using-f-string), OpenSSLConan._make] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:7[22](https://github.com/conan-io/conan-center-index/runs/7882488367?check_suite_focus=true#step:8:23): [R1705(no-else-return), OpenSSLConan._cc] Unnecessary "elif" after "return", remove the leading "el" from "elif"
recipes/openssl/1.x.x/conanfile.py:737: [C0209(consider-using-f-string), OpenSSLConan._make_context.sanitize_env_var] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:751: [C0209(consider-using-f-string), OpenSSLConan.build] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:786: [C0209(consider-using-f-string), OpenSSLConan._replace_runtime_in_file] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:786: [C0209(consider-using-f-string), OpenSSLConan._replace_runtime_in_file] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:787: [C0209(consider-using-f-string), OpenSSLConan._replace_runtime_in_file] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:787: [C0209(consider-using-f-string), OpenSSLConan._replace_runtime_in_file] Formatting a regular string which could be a f-string
recipes/openssl/1.x.x/conanfile.py:857: [C0209(consider-using-f-string), OpenSSLConan._module_file_rel_path] Formatting a regular string which could be a f-string
Error: Process completed with exit code [30](https://github.com/conan-io/conan-center-index/runs/7882488367?check_suite_focus=true#step:8:31).
```

At least there is one error: 
```
recipes/openssl/1.x.x/conanfile.py:4: [E0611(no-name-in-module), ] No name 'ConanInvalidConfiguration' in module 'conans.errors'
```


The bot won't merge the PR, this _check_run_ is required.

**Comment by jgsogo** [comment]
Now it is green 😸 

image

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by czoido** [comment]
> Now it is green 😸
> 
> image

Great! 

For me there are to things that I think could confuse users. First that the build continues after the linter fails, and second that some errors are shown in boxes in the code which is great and have more visibility and other like the ConanInvalidConfiguration one are between other warnings and are not so visible. Anyway, maybe it's just my impression.

**Comment by jgsogo** [comment]
btw, you can also consider fixing the rest of the linter warnings. Now is better than later 🙄

**Review by jcar87 — APPROVED** [review]
LGTM!

**Review by lasote — APPROVED** [review]

**Pull request merged**
