### PR TITLE
update ndk to add r23c

### PR DESCRIPTION
**Pull request by paulocoutinhox**
Specify library name and version:  **android-ndk/r23c**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by paulocoutinhox** [comment]
Error:

```
HOOK - conan-center.py] post_package_info(): ERROR: [INCLUDE PATH DOES NOT EXIST (KB-H071)] Component android-ndk::android-ndk include dir 'include' is listed in the recipe, but not found in package folder. The include dir should probably be fixed or removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H071) 
ERROR: 
	ConanException: [HOOK - conan-center.py] post_package_info(): Some checks failed running the hook, check the output
```

**Comment by paulocoutinhox** [comment]
Two things.

1 - Why the warnings happen? What i can do to fix?
2 - The fix for broken links are necessary for `r23c`?

```
if self.version in ["r23b", "r23c"] and self.settings.os in ["Linux", "Macos"]:
```

or 

```
if self.version in ["r23b"] and self.settings.os in ["Linux", "Macos"]:
```

Thanks.

**Comment by paulocoutinhox** [comment]
@uilianries now it is working

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
>  2 - The fix for broken links are necessary for `r23c`?

as I understand, it was fixed in r24 only, so fix for broken links is stiill needed for r23c

**Comment by paulocoutinhox** [comment]
@uilianries can you approve if is ok?

**Review by uilianries — APPROVED** [review]
Feito!

**Comment by paulocoutinhox** [comment]
@uilianries @SSE4 can you call more one to review?

**Comment by uilianries** [comment]
@paulocoutinhox it's no longer needed. We updated the review rule to only 2 approvals now. This PR is good to be merged. Now it's on CI bot hands.

**Pull request merged**
