### PR TITLE
onnxruntime: ensure conan dependencies are used when versions are overriden

### LINKED ISSUE #22153: [onnxruntime] build fails if we override the nlohmann_json/protobuf/gsl version
### Description

The cmake files of onnxruntime expect a given version of nlohmann_json/protobuf/gsl and fail to retrieve the configuration generated by conan if we change them.

### Package and Environment Details

* Conan version: **conan 2.0.16**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[replace_requires]
nlohmann_json/*: nlohmann_json/3.9.0

### Steps to reproduce

conan install --requires=onnxruntime/1.14.1

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

### PR DESCRIPTION
**Pull request by fdgStilla**
Fix #22153

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by valgur** [comment]
#20619 kind of already does the same by rewriting `onnxruntime_external_deps.cmake` entirely with a custom version.

**Comment by fdgStilla** [comment]
@valgur I still see a harcoded version of the Protobuf in your new cmake file: `find_package(Protobuf 3.21.12 REQUIRED CONFIG)`, shall we remove this and only rely on the version given by conan (if the version shall not be changed I guess it is be in the validate method)

**Comment by RubenRBS** [comment]
Regenerating missing binaries now

**Review by valgur — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
Hi! Sorry that this took so long to get addressed. As far as I can see these changes are looking good. If the recipe ever needs to ensure a version range for these dependencies, it should check it in its validate method :)

**Comment by perseoGI** [comment]
> Hi! Sorry that this took so long to get addressed. As far as I can see these changes are looking good. If the recipe ever needs to ensure a version range for these dependencies, it should check it in its validate method :)

Hi @fdgStilla, thanks for your contribution, could you confirm the library does not need those fixed dependency versions?

**Comment by fdgStilla** [comment]
We currently use the recipe with this change and we have been using this configuration for the last 6 months:
- protobuf/3.21.12
- onnxruntime/1.14.1
- nlohmann_json/3.9.1
- ms-gsl/4.0.0

I think I remember that it was not possible to change the major version of gsl to 3, I did not try to change the major version for the other versions, but we could improve the validate method in another PR. Currently onnxruntime is very difficult to integrate to a project because of the fixed version in the cmake.

**Comment by perseoGI** [comment]
Okey, thanks for your fast and your empirical proof, I'm approving this PR.
As you said, in the future we can add more validations on this recipe.

**Review by perseoGI — APPROVED** [review]

**Comment by RubenRBS** [comment]
Biulding missing binary now

**Comment by czoido** [comment]
Hi @fdgStilla,
Thanks a lot for the contribution. I think this should have been fixed after merging https://github.com/conan-io/conan-center-index/pull/23409 
Please, have a look. I'm closing this as solved but please feel free to reopen or open an issue if you have any more questions.

**Pull request closed without merging**
