### PR TITLE
[IMPORTANT] Updated changelog 22-February-2021

### PR DESCRIPTION
**Pull request by danimtb**
*Regarding the Conan version upgrade: The version was updated in the pipeline code but it will take 24 hours for the automatic update jobs to run and apply the new version.

### CODE REVIEW

**Comment by jgsogo** [comment]
Important to note that, although we've tried to generate all the binaries for the new compilers, some references might have failed and some PR can fail with _"Missing binaries"_ errors. In that case, it probably requires opening a PR to the _missing_ reference and (maybe) fix some errors related to the new compilers.

**Review by jgsogo — DISMISSED** [review]

**Review by uilianries — DISMISSED** [review]
Go Tapaholes!

**Comment by Croydon** [comment]
Awesome! You should also update the docs with the new configurations while at it

**Comment by danimtb** [comment]
@Croydon sure, thanks for the reminder! I have just pushed the changes

**Review by jgsogo — APPROVED** [review]

**Comment by Croydon** [comment]
> Currently, given the following supported platforms and configurations we
are generating **136 different binary packages for a C++ library**
and **88 for a C library**.

This needs updating too 😄

**Comment by jgsogo** [comment]
The next step will be to deprecate some of the configurations... the idea is to roll the configurations: deprecate the oldest one whenever we add a new one.

**Review by SSE4 — APPROVED** [review]
really great news, I've been missing apple-clang 12 packages in particular

**Review by prince-chrismc — APPROVED** [review]

**Comment by mathbunnyru** [comment]
Great news, I've been missing clang11 support 👍

**Review by mathbunnyru — APPROVED** [review]

**Pull request merged**
