### PR TITLE
add boost/1.65.1

### PR DESCRIPTION
**Pull request by sebastian-bergt**
Specify library name and version:  **boost/1.65.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
any reason to add that old version? (actual is 1.75.0)

**Comment by sebastian-bergt** [comment]
@SSE4 I need especially this version in a project I am currently working on as my dependency does not build with anything newer :(

**Comment by dmn-star** [comment]
A good chance to move the project forward.

**Comment by prince-chrismc** [comment]
There must have been some structural changes in the gap of versions 

```
clang-linux.compile.c++.pch /home/conan/w/cci_PR-4354/.conan/data/boost/1.65.1/_/_/build/c13df43a378dae2d7b4adf9ab69eae873af52906/boost/bin.v2/libs/math/build/clng-lnx-8.0.0/dbg/bst.l-on/bst.l-off/lnk-sttc/thrd-mlt/../src/tr1/pch.hpp.pth
error: unknown argument '-emit-pth', did you mean '-emit-pch'?
```

Seems like the compiler flags set by that version (from September 7th, 2017) does not support newer compilers

Might be time to move to a newer boost version 🙊

**Comment by SSE4** [comment]
yes, 10 versions behind would be a huge challenge, you will end up back-porting lots of fixes for modern compilers, if would be much easier to just upgrade instead

**Pull request closed without merging**
