### PR TITLE
sdl_net: add package_type + bump sdl + fix transitive_headers of sdl

### PR DESCRIPTION
**Pull request by SpaceIm**
- add package_type
- bump sdl
- add transitive_headers=True for sdl dependency, since SDL_net.h includes several public headers of sdl
- add sdl to direct dependencies of test package, because this test package has to initialize sdl and therefore use some symbols of sdl lib (we can't just rely on transitive_headers=True of sdl_net recipe here).

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
Graph error
    Version conflict: Conflict between libalsa/1.2.10 and libalsa/1.2.7.2 in the graph.
Conflict originates from pulseaudio/14.2
```

**Comment by SpaceIm** [comment]
waiting for https://github.com/conan-io/conan-center-index/pull/20381

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
@RubenRBS @uilianries could you review please?

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
