### PR TITLE
libmad: fix cross-build to iOS and armv8 + fix MinGW build + split build & install + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@jgsogo I've tested and it works now for Macos M1 (and also cross-build to iOS).

**Comment by SpaceIm** [comment]
@jgsogo Another expired Visual Studio license 😢 

```
----Running------
> devenv libmad.dsp /upgrade
-----------------

Microsoft Visual Studio 2015 Version 14.0.25420.1.
Copyright (C) Microsoft Corp. All rights reserved.

The license for Visual Studio has expired.

The evaluation period for this product has ended.libmad/0.15.1b: 
libmad/0.15.1b: WARN: Build folder is dirty, removing it: C:\J\w\BuildSingleReference@12\.conan\data\libmad\0.15.1b\_\_\build\df81ad20137149d7a51276fd3e24009b45e5964a
libmad/0.15.1b: ERROR: Package 'df81ad20137149d7a51276fd3e24009b45e5964a' build failed
libmad/0.15.1b: WARN: Build folder C:\J\w\BuildSingleReference@12\.conan\data\libmad\0.15.1b\_\_\build\df81ad20137149d7a51276fd3e24009b45e5964a
ERROR: libmad/0.15.1b: Error in build() method, line 56
	self._build_msvc()
```

**Comment by SpaceIm** [comment]
@SSE4 @uilianries @jgsogo This PR suffers of expired Visual Studio license

**Comment by danimtb** [comment]
sorry, it should be working again

**Review by czoido — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
