### PR TITLE
glib: pkgconf required at build time for all platforms + bump libmount

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **glib/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

closes https://github.com/conan-io/conan-center-index/issues/3707

### CODE REVIEW

**Review by ericLemanissier — DISMISSED** [review]

**Review by madebr — DISMISSED** [review]

**Review by Croydon — DISMISSED** [review]

**Review by ericLemanissier — DISMISSED** [review]

**Comment by SpaceIm** [comment]
Weird, I think that those hooks come from meson.

But I see an another error during configuration:

```
source_subfolder\meson.build:1:0: ERROR: Value "gnu99" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11".
```

**Comment by ericLemanissier** [comment]
indeed, the hook message regarding `/bin/mesonbuild/cmake/data/preload.cmake` can be ignored, it is a file present in the meson package as you just said. It is not blocking (not actually an error).

**Comment by SpaceIm** [comment]
I can reproduce this error with all glib versions on Windows. It comes from meson 0.56.0, if 0.55.3 is restored it works.

**Comment by SpaceIm** [comment]
By the way, meson might use system installed ninja instead of ninja package.

**Review by ericLemanissier — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
