### PR TITLE
Add `func-gen` recipe.

### PR DESCRIPTION
**Pull request by rturrado**
Specify library name and version:  **func-gen/0.1.1**

I would like to add at least two packages to Conan Center:
- `func-gen`: https://github.com/QuTech-Delft/func-gen, and
- `tree-gen`: https://github.com/QuTech-Delft/tree-gen.

Maybe also, later on:
- `libqasm`: https://github.com/QuTech-Delft/libqasm, and
- `OpenQL`: https://github.com/QuTech-Delft/OpenQL.

The former two packages are tools required by the latter two packages. As executables, not libraries. I want to "tool require" them as Conan packages so that I can cross compile `libqasm`. At the moment, when we compile for `armv8` or `emscripten`, both `func-gen` and `tree-gen` are compiled to the target platform and then tried to be executed from the build platform, what doesn't work.

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by rturrado** [comment]
Should I add something like `required_conan_version = ">=2.0"` to my top `conanfile.py` if I don't want this package to be used with Conan 1.x?

**Comment by rturrado** [comment]
Why cannot I get  my sources from a branch in the Git repository as stated [here](https://docs.conan.io/2/tutorial/creating_packages/handle_sources_in_packages.html)?

**Comment by RubenRBS** [comment]
Hi @rturrado, thanks a lot for your contribution, we really appreciate it.

Most of your issues/questions can be solved by basing your recipe off of the cmake package template at https://github.com/conan-io/conan-center-index/tree/master/docs/package_templates/cmake_package

That template shows how to properly handle sources, and comes with the necessary bits to make the recipe work in both Conan v1 and v2 (Which is still mandatory for now)

Please feel free to ping me once you've done so to review again, or feel free to ask any question that might arise during the process, happy to help :)

**Comment by rturrado** [comment]
Hi @RubenRBS ,

Many thanks for your comments, I'm quite relieved to know I will be getting some help getting these packages through on the Conan Center.

Just to confirm with you my two questions above:
1) Conan v1 support is then mandatory for any package, right? I cannot simply add that `required_conan_version = ">=2.0"` to my `conanfile.py`.
2) I shouldn't be using a `source` method downloading sources from Git with a URL and a commit ID. Instead, I should use a `conandata.yml`. I was preferring the `source` method solution because it allows me to specify a commit ID. The `conandata.yml` seems to force you to use a `sha256`.

**Comment by rturrado** [comment]
Cool, I have installed Conan 1.53 in an Ubuntu docker, and I have passed all the hooks and linters as indicated [here](https://github.com/conan-io/conan-center-index/blob/master/docs/developing_recipes_locally.md#running-the-python-linters).

I still have this hook error: `[HOOK - conan-center.py] post_package(): ERROR: [STATIC ARTIFACTS (KB-H074)] Package with 'shared=False' option did not contain any static artifact (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H074-STATIC-ARTIFACTS)`.

@RubenRBS, can you help me with that one? If you go to the URL indicated in the error message it actually doesn't say anything about `KB-074`. Thanks!

**Comment by rturrado** [comment]
Weird, the linters I passed in my Ubuntu docker were telling me to remove newlines at the end of some files, but the linters that are running in the Conan Center checks tell me to keep those newlines.

**Comment by rturrado** [comment]
I'm closing this pull request because we decided at our end to get rid of the `func-gen` project.

**Pull request closed without merging**
