### PR TITLE
Add cppcheck 2.14.2

### PR DESCRIPTION
**Pull request by Sneder89**
### Summary
Changes to recipe:  **lib/[version]**

#### Details

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by RubenRBS — COMMENTED** [review]
Hi @Sneder89 thanks a lot for taking the time to add a new version

Although 2.14.2 has been tagged, it was not yet been released (I can't see it in https://github.com/danmar/cppcheck/releases) - do you have any insight into this delay?

We'll probably could wait until upstream officialy releases it before merging this PR if that's ok :) (Otherwise the changes look good!)

**Comment by Sneder89** [comment]
> Hi @Sneder89 thanks a lot for taking the time to add a new version
> 
> Although 2.14.2 has been tagged, it was not yet been released (I can't see it in https://github.com/danmar/cppcheck/releases) - do you have any insight into this delay?
> 
> We'll probably could wait until upstream officialy releases it before merging this PR if that's ok :) (Otherwise the changes look good!)

When you have a look on the recent releases, only a few had an official release. especially the bugfix releases were only tagged.

**Comment by RubenRBS** [comment]
Oh I see, you are right! Thanks a lot, approving then :)

**Review by RubenRBS — APPROVED** [review]

**Review by perseoGI — APPROVED** [review]
LGTM https://github.com/danmar/cppcheck/compare/2.14.1...2.14.2

**Pull request merged**
