### PR TITLE
tomplusplus: add package_type & layout

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — DISMISSED** [review]
Thanks!

**Comment by SpaceIm** [comment]
hum, what is the actual error?

**Comment by RubenRBS** [comment]
It's trying to run the _multi target in v1 for gcc 7, which the test package recipe explicitly branches out of for gcc < 8 🤔

**Comment by RubenRBS** [comment]
Retriggering

**Review by RubenRBS — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
