### PR TITLE
scnlib: add version 2.0.0, remove older version

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **scnlib/***

- header-only has been removed since 2.0.0. https://github.com/eliaskosunen/scnlib/issues/82#issuecomment-1791578086
- simd-utf has been rquired since 2.0.0.
- C++17 has been required since 2.0.0.
- header file name has been changed since 2.0.0.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RazielXYZ** [comment]
@toge I don't believe this is an upstream issue as it builds fine locally. Not sure what's wrong.

**Comment by uilianries** [comment]
> @toge I don't believe this is an upstream issue as it builds fine locally. Not sure what's wrong.

@RazielXYZ The error is correct, I can reproduce it locally:

```
λ connan create all --version=2.0.0 -s compiler.cppstd=17

======== Exporting recipe to the cache ========
scnlib/2.0.0: Exporting package recipe: C:\Users\uilia\Development\conan\conan-center-index\recipes\scnlib\all\conanfile.py
scnlib/2.0.0: exports: File 'conandata.yml' found. Exporting it...
scnlib/2.0.0: Calling export_sources()
scnlib/2.0.0: Copied 1 '.yml' file: conandata.yml
scnlib/2.0.0: Copied 1 '.py' file: conanfile.py
scnlib/2.0.0: Copied 1 '.patch' file: 2.0.0-0001-remove-re2-version.patch
scnlib/2.0.0: Exported to cache folder: C:\Users\uilia\.conan2\p\scnli5d190256069ab\e
scnlib/2.0.0: Exported: scnlib/2.0.0#779e2ef8b000fdc9c77a8a3ed1880cf0 (2024-02-02 09:26:53 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    cli
Requirements
    fast_float/6.0.0#6c8a953c57879453982a6ce69c0ba87c - Cache
    scnlib/2.0.0#779e2ef8b000fdc9c77a8a3ed1880cf0 - Cache
    simdutf/4.0.5#cdd2fae61d5c1360874f55db5588ac61 - Cache
Build requirements
    cmake/3.28.1#92f79424d7b65b12a84a2180866c3a78 - Cache
Resolved version ranges
    cmake/[>=3.16 <4]: cmake/3.28.1

======== Computing necessary packages ========
simdutf/4.0.5: Checking 3 compatible configurations
simdutf/4.0.5: Main binary package 'dee9f7f985eb1c20e3c41afaa8c35e2a34b5ae0b' missing. Using compatible package '9bdee485ef71c14ac5f8a657202632bdb8b4482b': compiler.cppstd=14
scnlib/2.0.0: Forced build from source
Requirements
    fast_float/6.0.0#6c8a953c57879453982a6ce69c0ba87c:da39a3ee5e6b4b0d3255bfef95601890afd80709#a5e0faab5074f6f6eaa817bfb3d9e59c - Cache
    scnlib/2.0.0#779e2ef8b000fdc9c77a8a3ed1880cf0:0c3a7a907f819f40bb47ef2edb8d710e85028a61 - Build
    simdutf/4.0.5#cdd2fae61d5c1360874f55db5588ac61:9bdee485ef71c14ac5f8a657202632bdb8b4482b#4fa3ecf63a8f0253bb40d213dc33d0b6 - Cache
Build requirements
    cmake/3.28.1#92f79424d7b65b12a84a2180866c3a78:522dcea5982a3f8a5b624c16477e47195da2f84f#29e6903b5006c2b2f81003c9ebf7551b - Cache

======== Installing packages ========
cmake/3.28.1: Already installed! (1 of 4)
cmake/3.28.1: Appending PATH environment variable: C:\Users\uilia\.conan2\p\cmake615d6e26ece18\p\bin
fast_float/6.0.0: Already installed! (2 of 4)
simdutf/4.0.5: Already installed! (3 of 4)

-------- Installing package scnlib/2.0.0 (4 of 4) --------
scnlib/2.0.0: Building from source
scnlib/2.0.0: Package scnlib/2.0.0:0c3a7a907f819f40bb47ef2edb8d710e85028a61
scnlib/2.0.0: Copying sources to build folder
scnlib/2.0.0: Building your package in C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b
scnlib/2.0.0: Calling generate()
scnlib/2.0.0: Generators folder: C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\build\generators
scnlib/2.0.0: CMakeToolchain generated: conan_toolchain.cmake
scnlib/2.0.0: CMakeToolchain generated: CMakePresets.json
scnlib/2.0.0: CMakeToolchain generated: ..\..\src\CMakeUserPresets.json
scnlib/2.0.0: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(FastFloat)
    find_package(simdutf)
    target_link_libraries(... FastFloat::fast_float simdutf::simdutf)
scnlib/2.0.0: Generating aggregated env files
scnlib/2.0.0: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
scnlib/2.0.0: Calling build()
scnlib/2.0.0: Apply patch (portability): remove re2 version on find_package
scnlib/2.0.0: Running CMake.configure()
scnlib/2.0.0: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/uilia/.conan2/p/b/scnli28b93d8b459c1/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/uilia/.conan2/p/b/scnli28b93d8b459c1/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src"
-- Using Conan toolchain: C:/Users/uilia/.conan2/p/b/scnli28b93d8b459c1/b/build/generators/conan_toolchain.cmake
-- Conan toolchain: CMAKE_GENERATOR_TOOLSET=v143
-- Conan toolchain: C++ Standard 17 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:26 (message):
  No CMAKE_BUILD_TYPE set, defaulting to Release


-- Conan: Target declared 'simdutf::simdutf'
-- Conan: Component target declared 'FastFloat::fast_float'
-- Configuring done (1.6s)
-- Generating done (0.1s)
-- Build files have been written to: C:/Users/uilia/.conan2/p/b/scnli28b93d8b459c1/b/build

scnlib/2.0.0: Running CMake.build()
scnlib/2.0.0: RUN: cmake --build "C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\build" --config Release
MSBuild version 17.3.1+2badb37d1 for .NET Framework
  1>Checking Build System
  Building Custom Rule C:/Users/uilia/.conan2/p/b/scnli28b93d8b459c1/b/src/CMakeLists.txt
  scan.cpp
  scan_buffer.cpp
  scanner.cpp
  vscan.cpp
  locale.cpp
  find_whitespace.cpp
  reader.cpp
  float_reader.cpp
  integer_reader.cpp
C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\src\scn\scan_buffer.cpp(236,2): error C2953: 'scn::v2::detail::`anonymous-namespace'::file_wrapper_impl<F,enable_if<!=0,void>::type>': class template has already been defined [C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\build\scn.vcxproj]
C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\src\scn\scan_buffer.cpp(145): message : see declaration of 'scn::v2::detail::`anonymous-namespace'::file_wrapper_impl<F,enable_if<!=0,void>::type>' [C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\build\scn.vcxproj]
C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\src\scn\vscan.cpp(401,67): error C2440: 'initializing': cannot convert from 'initializer list' to 'scn::v2::detail::specs_checker<scn::v2::`anonymous-namespace'::specs_handler<scn::v2::basic_scan_context<wchar_t>>>' [C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\ build\scn.vcxproj]
C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\src\scn\vscan.cpp(403,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\build\scn.vcxproj]
C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\src\scn\vscan.cpp(387): message : while compiling class template member function 'const wchar_t *scn::v2::`anonymous-namespace'::format_handler<false,CharT>::on_format_specs(size_t,const wchar_t *,const wchar_t *)' [C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\b uild\scn.vcxproj]
          with
          [
              CharT=wchar_t
          ]
C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\include\scn/detail/format_string_parser.h(909): message : see reference to function template instantiation 'const wchar_t *scn::v2::`anonymous-namespace'::format_handler<false,CharT>::on_format_specs(size_t,const wchar_t *,const wchar_t *)' being compiled [C:\Users \uilia\.conan2\p\b\scnli28b93d8b459c1\b\build\scn.vcxproj]
          with
          [
              CharT=wchar_t
          ] (compiling source file C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\src\scn\vscan.cpp)
C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\src\scn\vscan.cpp(492): message : see reference to class template instantiation 'scn::v2::`anonymous-namespace'::format_handler<false,CharT>' being compiled [C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\build\scn.vcxproj]
          with
          [
              CharT=wchar_t
          ]
C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\src\src\scn\vscan.cpp(570): message : see reference to function template instantiation 'scn::v2::scan_expected<ptrdiff_t> scn::v2::`anonymous-namespace'::vscan_internal<wchar_t>(scn::v2::detail::basic_scan_buffer<wchar_t> &,std::basic_string_view<wchar_t,std::char_trai ts<wchar_t>>,scn::v2::basic_scan_args<scn::v2::wscan_context>,scn::v2::detail::locale_ref)' being compiled [C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\build\scn.vcxproj]

scnlib/2.0.0: ERROR:
Package '0c3a7a907f819f40bb47ef2edb8d710e85028a61' build failed
scnlib/2.0.0: WARN: Build folder C:\Users\uilia\.conan2\p\b\scnli28b93d8b459c1\b\build
ERROR: scnlib/2.0.0: Error in build() method, line 148
        cmake.build()
        ConanException: Error 1 while executing
```

**Comment by RazielXYZ** [comment]
@uilianries You are correct, it doesn't work on msvc with C++17, it works with C++20 which I accidentally tested with the first time 😅 if upstream doesn't respond or can't fix I guess we can require C++20 for msvc, but hopefully they can take a look.

**Comment by toge** [comment]
@RazielXYZ @uilianries 
Thank you for sharing the information to improve this PR!
I added logic to exclude C++17 support in MSVC for scnlib/2.0.0.
Please let me check if this will pass CCI.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by RubenRBS — APPROVED** [review]
Approving, seems like we will need to wait for upstream fixes for the next release :)

**Pull request merged**
