### PR TITLE
geotrans/3.8: patch to compile with MSVC2022 and c++20

### PR DESCRIPTION
**Pull request by paulharris**
Specify library name and version:  **geotrans/3.8**

Small simple patch to add const where required on 2 lines.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Please, send this patch to the upstream too. It can be useful there.

**Comment by paulharris** [comment]
> Please, send this patch to the upstream too. It can be useful there.

I'd love to, but I don't know where to send it, apart from an email address on this page: https://earth-info.nga.mil/

I think I'll just leave it here for now, it is a super-simple patch, not worth the trouble in this case.

**Review by uilianries — DISMISSED** [review]

**Comment by paulharris** [comment]
How do I clear this "unexpected error" ?
What is the background to these problems?
Should I continue to close+reopen PRs to try again? Or is that not going to work?

**Review by SSE4 — DISMISSED** [review]

**Comment by paulharris** [comment]
Seems to be waiting on the CLA ?

**Review by uilianries — DISMISSED** [review]

**Comment by paulharris** [comment]
Sorry guys, one more commit to add system lib 'm'.
I didn't spot the hook warning until just now.
Those hooks are great :)

But sorry, please approve the reviews when you get to it.

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
