### PR TITLE
Add deprecation warning for libgettext

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **libgettext/0.20.1**

requires https://github.com/conan-io/conan-center-index/pull/1424 first

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
In addition to this maybe we could also add something which is faster visible for contributors and automatically readable? 

Something like a `recipes/libgettext/DEPRECATED` text file?

**Comment by uilianries** [comment]
@Croydon great idea! I'll add it.

**Comment by Croydon** [comment]
Isn't that a bug in the hooks? A single file can't be a new recipe version, but the hook thinks so

**Comment by jgsogo** [comment]
> Isn't that a bug in the hooks? A single file can't be a new recipe version, but the hook thinks so

If this file is not added to the package the recipe revision should be the same. Why do you think it is a new one?

**Comment by Croydon** [comment]
I referred to this: https://github.com/conan-io/conan-center-index/pull/1425#issuecomment-617893394

Adding such a ``DEPRECATED` file to the recipe directory, causes the hook to think that two recipe version got modified

**Comment by jgsogo** [comment]
I see. This is a check in the CI not the hooks. Unless we decide that the way to deprecate a recipe is to an add file in the root of the package that failure is legit... we can consider it in the CI once we decide that adding that file with that name is the way to deprecate a package (the CI probably should return a proper message then), right now it's been some kind of improvisation (nice one, btw).

**Comment by ericLemanissier** [comment]
isn't it premature to deprecate libggettext when gettext is not actually an alternative (until https://github.com/conan-io/conan-center-index/pull/1424 is merged) ?

**Comment by jgsogo** [comment]
Probably it is 😓  Recipe still works, but the message will be there, I'll push the other one

**Pull request merged**
