### PR TITLE
json-schema-validator: add version 2.2.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **json-schema-validator/2.2.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
Oops.
I make it draft until https://github.com/conan-io/conan-center-index/pull/14353 is merged.

**Review by prince-chrismc — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by prince-chrismc** [comment]
5hr on one job thats says it's done in the logs 🤔

**Comment by prince-chrismc** [comment]
Let's try again

**Comment by garethsb** [comment]
Yippee! 6th attempt only took 15 hours in the end! 🚀🚀🚀

**Pull request merged**
