### PR TITLE
libressl: use one recipe for all versions, add 3.0.2

### PR DESCRIPTION
**Pull request by theodelrieu**
Specify library name and version:  **libressl/3.0.2**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by danimtb** [comment]
There is an issue with the change of single recipe to using *config.yaml* file. I am taking a look

**Comment by theodelrieu** [comment]
Is help still on its way @danimtb ? :sweat_smile:

**Comment by danimtb** [comment]
I am the help, yes 🤣 and yep, the fix is on its way (kind of). Will report when fixed. Thanks!

**Comment by theodelrieu** [comment]
Ahahah perfect! Thanks a lot!

**Comment by danimtb** [comment]
A fix has been proposed for the issue this PR triggered. I will relaunch the jobs once it is validated and merged

**Comment by danimtb** [comment]
Fix has been validated and deployed to production. I will restart the job for this PR 🤞

**Pull request merged**
