### PR TITLE
[do not merge][test] see if current revision of sqlcipher still builds on CI 

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Comment by jgsogo** [comment]
Quick search. Looks like it can be related to the TMP folders (https://stackoverflow.com/questions/26547214/cl-exe-returing-error-code-d8050). I'll work on staging to reproduce this issue, first idea: the TMP folder now is using a folder that doesn't exists... maybe this is the root cause, at least it is easy to check.

**Comment by jgsogo** [comment]
After changing TMP folder to be sure that it exists, the recipe builds. Windows, cryptic errors.... 😄

**Comment by ericLemanissier** [comment]
@jgsogo could it also explaim the windows part of https://github.com/conan-io/conan-center-index/pull/2847#issuecomment-706184204?

**Comment by jgsogo** [comment]
Fixed. Deployed to prod. Let's call it a day, tomorrow I'll update the changelog 🚀

**Pull request closed without merging**
