### PR TITLE
Fix an upstream bug in PostgreSQL BLOB extractor

### PR DESCRIPTION
**Pull request by db4**
Specify library name and version:  **poco/1.10.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

I've tested the fix locally and already submitted https://github.com/pocoproject/poco/pull/3166 but would like to have the working package in the meantime (the best scenario will be including this fix into poco 1.10.2, but I don't expect it to be done soon)

### CODE REVIEW

**Review by jgsogo — CHANGES_REQUESTED** [review]
Hi, This is something we've been talking about in the last days and we need a policy around it (cc/ @danimtb @uilianries @SSE4 )

In general, I feel like it is not a good practice to backport patches from incoming releases to older ones in a package manager, doing it this way you get different bugs/features depending on where you get your binaries from (Conan applies a patch, the official release doesn't behave the same,... and it may become a nightmare for library authors if issues arrive related to binaries with different behaviors). (It can be different for security patches)

So, I think it is better to wait for 1.10.2, where Poco will likely add this bugfix. https://github.com/pocoproject/poco/pull/3166

**Comment by db4** [comment]
@jgsogo it's my own fix against 1.10.1 and the bug makes the current upstream completely unusable for me. What would you recommend then knowing that the new upstream release can take weeks (if not months)? Create a private package? Can I do this not replicating conan-center-index build infrastructure locally?

**Comment by prince-chrismc** [comment]
> Create a private package?

Yes 💯 you can! You can build you're package locally via `conan create` and either use [`conan_server`](https://docs.conan.io/en/latest/uploading_packages/running_your_server.html) or https://jfrog.com/open-source/#artifactory to host it if you are working at that scale!

**Comment by db4** [comment]
> 
> 
> > Create a private package?
> 
> Yes 💯 you can! You can build you're package locally via `conan create` and either use [`conan_server`](https://docs.conan.io/en/latest/uploading_packages/running_your_server.html) or https://jfrog.com/open-source/#artifactory to host it if you are working at that scale!

I have a number of private packages in a local Artifactory, but reinventing CI for a local fork of conan-center-index seems to be a challenging task. Anyway, since everyone thinks this PR should not be merged, I'm closing it.

**Pull request closed without merging**
