### PR TITLE
imagl: migrate to Conan v2, update URLs

### PR DESCRIPTION
**Pull request by valgur**

### CODE REVIEW

**Comment by valgur** [comment]
Closing temporarily to avoid unnecessary load on the CI. Will reopen when I'm actively working on the PR again.

**Comment by valgur** [comment]
@RubenRBS Do you know what might be causing the "Invalid JSON String" failures?

**Comment by RubenRBS** [comment]
Super weird @valgur, but the good news is that the builds look ok from here, but something broke while reporting the results 🤔 
Investigating now, thanks for the ping

**Comment by uilianries** [comment]
Fixed on #19614 !

**Pull request closed without merging**
