### PR TITLE
aws-sdk-cpp use openssl

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **aws-sdk-cpp/...**

The purpose of this pull request is to make the SDK compliant with the Apple Store which reject private API usage on MacOS and [iOS](https://github.com/aws/aws-sdk-cpp/issues/1619).

Switching to openssl fix the issue. This change seems reasonable since openssl is already in the recipe requirements.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
@jgsogo Any idea why this recipe doesn't build?

**Comment by MartinDelille** [comment]
I updated the description.

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by MartinDelille** [comment]
I closed and reopened the PR in order to try to remove the `Unexpected Error` tag but the CI behavior is very erratic.

**Comment by uilianries** [comment]
All good now

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
