### PR TITLE
add poly2tri/cci.20130502

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **poly2tri/cci.20130502**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
We have waf available in cci.

**Comment by SpaceIm** [comment]
Is it worth the effort to use waf in this recipe? Is is possible to export all symbols for shared msvc?

**Comment by SpaceIm** [comment]
I'm not familiar with waf, but wscript seems to build testbed application, not core lib as a standalone.

**Comment by madebr** [comment]
Possible? Yes. But the last commit to this repo is from 8 years ago and the build script is only rudimentary.
So probably not worth the time.

**Comment by madebr** [comment]
> I'm not familiar with waf, but wscript seems to build testbed application, not core lib as a standalone.

I'm also not too familiar with it.
I have created only 2 recipes for it and even those two had problems with shared vs static.

**Review by madebr — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Pull request merged**
