### PR TITLE
android-ndk: add NDK r19c and r20b

### PR DESCRIPTION
**Pull request by Linux13524**
This will add NDK r19c and r20b to the list of supported NDK versions. Since we still depend on r19c for our internal builds and we are not able to upgrade for some reasons it would be great if they could be added to the Conan Center Index.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
https://c3i.jfrog.io/c3i/misc/logs/pr/15235/2-linux-gcc/android-ndk/r19c//4db1be536558d833e52e862fd84d64d75c2b3656-build.txt

:)


```
/usr/bin/objdump: ./bin/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/18/libc++.so: File format not recognized
[HOOK - conan-center.py] post_package(): ERROR: [CMAKE-MODULES-CONFIG-FILES (KB-H016)] The conan-center repository doesn't allow the packages to contain CMake find modules or config files. The packages have to be located using generators and the declared `cpp_info` information (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H016) 
[HOOK - conan-center.py] post_package(): ERROR: [CMAKE-MODULES-CONFIG-FILES (KB-H016)] Found files: ./bin/toolchains/llvm/prebuilt/linux-x86_64/lib64/cmake/clang/ClangConfig.cmake; ./bin/toolchains/llvm/prebuilt/linux-x86_64/lib64/cmake/llvm/FindLibpfm.cmake; ./bin/toolchains/llvm/prebuilt/linux-x86_64/lib64/cmake/llvm/FindOCaml.cmake; ./bin/toolchains/llvm/prebuilt/linux-x86_64/lib64/cmake/llvm/FindSphinx.cmake; ./bin/toolchains/llvm/prebuilt/linux-x86_64/lib64/cmake/llvm/LLVM-Config.cmake; ./bin/toolchains/llvm/prebuilt/linux-x86_64/lib64/cmake/llvm/LLVMConfig.cmake (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H016) 
```

**Comment by prince-chrismc** [comment]
If that's expected we can add an exception to the Hooks repo but I am no android expert (though I am hoping to learn)

**Comment by Linux13524** [comment]
Hmm. Im also not an expert on that. However this package is quiet different to "normal" packages in that it contains the actual toolchain and thus I would say it is fine to have CMake configs in it. On the other side it is strange that newer versions of the NDK do not include such files..

From https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H016:
> In order to make sure that the package will be consumed with any build-system, conan-center repository encourages to declare a [def package_info(self)](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info) method with all the needed information about the package.

But the package should not be consumed by a build-system, it is the build-system :)

BTW: I already tested and integrated the `android-ndk/r19c` package in our internal builds and everything seems to work fine.

**Comment by uilianries** [comment]
The hook found `Findxxx.cmake` and `xxxConfig.cmake` which are not needed in ConanCenterIndex 99% of cases. Usually we create exceptions we a project exports a cmake find with functions, like Protobuf. Please, remove those cmake file from the package folder, you will need to update the recipe with:

```python
from conan.tools.files import rm

...

def package(self):
    rm(self, "*.cmake", os.path.join(self.package_folder, "bin"), recursive=True)
```

On the other hand, if those files are really needed, like they provide some cmake helper, we can add an exception with no problems.

**Comment by Linux13524** [comment]
OK, thanks for your ideas! I just quickly removed the module and config files from the package, see 28a7bc968799860604c044f744daf729351ec928, built one of our packages and it worked. Still not sure if they are needed but I would just say we go ahead and remove them and add them at any point in the future again if we see they are needed.

**Review by prince-chrismc — APPROVED** [review]

**Comment by Linux13524** [comment]
@prince-chrismc Any idea why this wasn't merged? We are using Android r19c since I open this PR in our pipelines  without problem.

**Comment by prince-chrismc** [comment]
It never passed CI.

**Comment by prince-chrismc** [comment]
Being 5 months old there might be new things to do 🙊

**Comment by Linux13524** [comment]
Seems they failed again. Is it normal not even having read access to the CI jobs?

**Pull request merged**
