### PR TITLE
boost: fix build with icu + improve injection of cpp_info of dependencies

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/14817
closes https://github.com/conan-io/conan-center-index/issues/15164

see https://github.com/conan-io/conan/issues/12733

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by stefan-floeren — APPROVED** [review]

**Review by jwillikers — DISMISSED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
@uilianries @prince-chrismc could you review please? I would like to not have to rebase again if another boost PR is merged.

**Review by SSE4 — APPROVED** [review]

**Comment by uilianries** [comment]
@SpaceIm Thank you for providing this fix! I'm just checking about `aggregated_components` first. I see you already asked about it in Conan Client repository. It's not documented yet in the documentation, but its interface is public in Python, so I need so insight from Devs what should be done. Thank you again for pinging us!

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by SSE4** [comment]
@SpaceIm  `Logs for packageID null:` looks suspicious :thinking:

**Comment by SpaceIm** [comment]
c3i seems to be broken again

**Comment by prince-chrismc** [comment]
It was slow yestureday but yeah it's down

The error message is super helpful too

```
General error during conversion: Error grabbing Grapes
```

**Comment by uilianries** [comment]
The CI job #9 passed, but Jenkins started a new CI job #10 which is running right now. We can't just cancel it, because Jenkins always consider the latest result.

**Comment by SpaceIm** [comment]
It shouldn't take too long, it should reuse existing package id of previous CI job and just run test packages.

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
