### PR TITLE
libaec: add version 1.0.6

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **libaec/1.0.6**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
> LINK : fatal error LNK1104: cannot open file 'C:\J\w\BuildSingleReference@6\.conan\data\libaec\1.0.6\_\_\build\4f1710918aa542fccb5a54d7bd712e4b0750b50d\build_subfolder\bin\aec.ilk' [C:\J\w\BuildSingleReference@6\.conan\data\libaec\1.0.6\_\_\build\4f1710918aa542fccb5a54d7bd712e4b0750b50d\build_subfolder\source_subfolder\src\aec_client.vcxproj]

**Comment by jgsogo** [comment]
I've checked Windows servers and it shouldn't be a problem with disk space... unless one of these builds takes around 70Gb

**Comment by toge** [comment]
@jgsogo 
Thank you for your advice.
I agree with you. It is not caused by disk space problem.

**Review by uilianries — DISMISSED** [review]

**Comment by toge** [comment]
Sorry.  I forget to make it draft.
Currently  this recipe don't support providing aec-client command.
because building aec-client in MSVC with shared and debug is failed :
```
LINK : fatal error LNK1201: error writing to program database 'C:\J\w\BuildSingleReference@5\.conan\data\libaec\1.0.6\_\_\build\21206bd73c3636750497f5d1a65364cc6adec885\bin\aec.pdb'; check for insufficient disk space, invalid path, or insufficient privilege [C:\J\w\BuildSingleReference@5\.conan\data\libaec\1.0.6\_\_\build\21206bd73c3636750497f5d1a65364cc6adec885\source_subfolder\src\aec_client.vcxproj]
```

**Comment by uilianries** [comment]
> Sorry. I forget to make it draft. Currently this recipe don't support providing aec-client command. because building aec-client in MSVC with shared and debug is failed :
> 
> ```
> LINK : fatal error LNK1201: error writing to program database 'C:\J\w\BuildSingleReference@5\.conan\data\libaec\1.0.6\_\_\build\21206bd73c3636750497f5d1a65364cc6adec885\bin\aec.pdb'; check for insufficient disk space, invalid path, or insufficient privilege [C:\J\w\BuildSingleReference@5\.conan\data\libaec\1.0.6\_\_\build\21206bd73c3636750497f5d1a65364cc6adec885\source_subfolder\src\aec_client.vcxproj]
> ```

Only that configuration is failing? You could skip it on `validate()` and build others. No need to spend a lot of time to fix only a single configuration, it can be fixed later, in a future PR.

**Comment by toge** [comment]
@uilianries 
Thank you for your advice.

> Only that configuration is failing?

Yes, as far as I know.

As you wrote, I will skip this configuration on `validate()`.

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
