### PR TITLE
Glib 2.80.0

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **glib/2.80.0**

Patch is necessary to remove dependency to python packaging, following https://github.com/conan-io/conan-docker-tools/pull/554#issuecomment-1999860485

don't use `PkgConfig` because it invokes `pkg-config` which is not installed on macos runners.

remove unused versions:
- https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.75.3&type=code
- https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.77.0&type=code
- https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.77.1&type=code
- https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.77.2&type=code

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8373751662/attempts/1)

**Comment by ericLemanissier** [comment]
blocked by https://github.com/conan-io/conan-center-index/pull/23191

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8373751662/attempts/2)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8373751662/attempts/3)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8373751662/attempts/4)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8373751662/attempts/6)

**Comment by ericLemanissier** [comment]
this is ready for review @uilianries @RubenRBS

**Review by valgur — APPROVED** [review]

**Comment by ericLemanissier** [comment]
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3976 has been rejected. glib's dependency on `packaging` is not going away. I don't have time nor energy to continue proposing solutions to make progress on this package.

**Pull request closed without merging**
