### PR TITLE
libwebp: relocatable shared lib on macOS + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
see https://github.com/conan-io/hooks/issues/376

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SSE4 — DISMISSED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by prince-chrismc** [comment]
😖 


```
conan test conan-center-index/recipes/libwebp/all/test_package/conanfile.py libwebp/1.2.2@ --profile=/Users/jenkins/w/BuildSingleReference/78257/d92a02be-9c85-4288-8737-60d279a475af/profile.txt

libwebp/1.2.2: Retrieving package 859f8116a362ef830363626989ec41f658f4e574 from remote 'c3i_PR-9036' 
ERROR: Binary package not found: 'libwebp/1.2.2:859f8116a362ef830363626989ec41f658f4e574'
```

**Comment by SpaceIm** [comment]
```
Installing (downloading, building) binaries...
libwebp/1.2.2: Retrieving package 859f8116a362ef830363626989ec41f658f4e574 from remote 'c3i_PR-9036' 
ERROR: Binary package not found: 'libwebp/1.2.2:859f8116a362ef830363626989ec41f658f4e574'
```

@jgsogo Any idea on this one? test package fails to retrieve the package.

**Comment by jgsogo** [comment]
If it is a dependency of the `test_package/conanfile.py` it's probably this same issue: https://github.com/conan-io/conan-center-index/pull/9089#issuecomment-1024047411

I'll try to bypass it with the tools we have currently (it might work), if not, I'm preparing some changes to be deployed soon

**Comment by jgsogo** [comment]
Here the problem was a wrong package (incomplete one) uploaded to Artifactory, the `conanmanifest.txt` file was missing. We have requested Artifactory team to provide some kind of atomic uploads for Conan packages, but still the feature is in the backlog. While this is developed, Conan packages can face this issue in concurrent scenarios.

**Review by jgsogo — APPROVED** [review]

**Comment by prince-chrismc** [comment]
The merge commit persevered our approvals but the bot only looks at the head commit

This needs one more uilianries review is not being counted according to my bot 😢

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
let's try to recount

**Pull request merged**
