### PR TITLE
ZBar 0.10 update

### PR DESCRIPTION
**Pull request by ericriff**
Specify library name and version:  **ZBar/0.10**

The main change introduced by this PR is a patch that updates `config.guess` and `config.sub` since the ones present in the source code are from 2009 and do not support (among others) `aarch64`.
There is also some cleanup in the test package and I changed the name of the findPkg.cmake to ZBar. Online you can find it as `findZBAR.cmake` or `findZBar.cmake`.

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
5k lines of patch?! This not a patch, it's an entire new project :sweat_smile: What's the source of that patch?

**Comment by ericriff** [comment]
I believe I left the link to the source in the commit message

**Comment by madebr** [comment]
Isn't this the result of a more recent autoconf?

**Comment by ericriff** [comment]
I'm not really sure. I googled the error I was having and I saw that it is pretty common to get this files outdated and they have to be manually updated using the sources I used.

**Comment by madebr** [comment]
@ericriff 
Try the following:
1. Remove your gigantic patch
2. Add `libtool/2.4.6` to the build requirements
3. In build, after eventual other patches:
```python
with tools.chdir(self._source_subfolder):
    self.run("autoreconf -fiv", run_environment=tools.os_info.is_windows)
```

**Comment by ericriff** [comment]
I did a quick test and I've got a bunch of errors
```
configure.ac:109: warning: macro 'AM_ICONV' not found in library
autoreconf: running: /home/eric/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/autoconf --force
configure.ac:1: error: possibly undefined macro: dnl
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:109: error: possibly undefined macro: AM_ICONV
configure.ac:131: error: possibly undefined macro: AC_MSG_FAILURE
autoreconf: /home/eric/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/autoconf failed with exit status: 1
```

**Comment by madebr** [comment]
I'll look into it.

**Comment by ericriff** [comment]
If i try to crosscompile with `libtool` as a `build_requirement` I get errors saying that libtool is not available for that particular architecture. I'm using an older version of conan (1.21) so it doesn't support the two profiles approach, maybe that fixes it. 
Regardless, it is an error that I only get with `libtool`. I can use other x86 tools while crosscompiling and ir works. Somehow when it comes to `libtool` it tries to use the host arch instead of x86.
For example I can set `cmake` as a `build_requirement` and then crosscompile and conan will not try to use a cmake package built for the host arch, it will use the one for x86 as it should. 
Am I doing something wrong?

**Comment by madebr** [comment]
@ericriff 
Try applying this patch, using your system libtool.
```
--- configure.ac
+++ configure.ac
@@ -3,10 +3,11 @@
 AC_INIT([zbar], [0.10], [spadix@users.sourceforge.net])
 AC_CONFIG_AUX_DIR(config)
 AC_CONFIG_MACRO_DIR(config)
-AM_INIT_AUTOMAKE([1.10 -Wall -Werror foreign subdir-objects std-options dist-bzip2])
+AM_INIT_AUTOMAKE([1.10 -Wall foreign subdir-objects std-options dist-bzip2])
 AC_CONFIG_HEADERS([include/config.h])
 AC_CONFIG_SRCDIR(zbar/scanner.c)
 LT_PREREQ([2.2])
+AM_PROG_AR
 LT_INIT([dlopen win32-dll])
 LT_LANG([Windows Resource])
```

**Comment by madebr** [comment]
For using conan's automake, I've opend #2038 to let recipes add include paths for m4 files.
zbar requires the function `AM_ICONV`, which is provided by `iconv.m4`.
This is available through `coreutils` or `gettext`.

But I'm unsure how to add these to the recipe because they look overkill for reconfiguration only.

**Comment by ericriff** [comment]
OK, I'll try tomorrow.
I'm not keen to use conan's libtool since it breaks crossbuilding for conan versions older than 1.24.
If you try to run something like
```
conan create recipes/zbar/all zbar/0.10@user/channel -pr armv7
```
Conan tries to pull libtool for armv7 instead of x86 and the build fails. If you use the newer approach with a build and a host profile this works as intended.
Using system's autotools to run autoreconf implies a bunch of system requirements that the user must have or the build will fail. 
The gigantic patch seemed to be the the path of least resistance.

**Comment by Croydon** [comment]
> The gigantic patch seemed to be the the path of least resistance.

I disagree. A patch with 5k lines of code is unacceptable complex for package maintainers.

**Comment by ericriff** [comment]
> > The gigantic patch seemed to be the the path of least resistance.
> 
> I disagree. A patch with 5k lines of code is unacceptable complex for package maintainers.

I also considered putting those files in `export_sources` and then overriding the original ones with those. Maybe that's more maintainer friendly?

**Comment by madebr** [comment]
Ideal would be to have a release. Is the project (temporary) dead?
Ideally 2nd would be to `autoreconf.
Ideally 3re would be to extract the armv8 specific portions, and apply those in a patch.

**Comment by madebr** [comment]
See https://sourceforge.net/p/zbar/discussion/664595/thread/abb00b45/
-> https://git.linuxtv.org/zbar.git/about/

**Comment by ericriff** [comment]
I believe the project is dead. There is also a [mirror in github](https://github.com/ZBar/ZBar). On that one the latest release is also 0.10 but they continued developing for android and iOS. But it is weird because if you compare the sources of github and the official ones (sourceforge), on the same release (0.10) they're not the same. Specifically, `configure` is missing on the github clone, I'm not sure about the rest of the files. When had this conversation when we merged the original recipe for zbar and we decided to stick with the official sources.

**Comment by ericriff** [comment]
> @ericriff
> Try applying this patch, using your system libtool.
> 
> ```
> --- configure.ac
> +++ configure.ac
> @@ -3,10 +3,11 @@
>  AC_INIT([zbar], [0.10], [spadix@users.sourceforge.net])
>  AC_CONFIG_AUX_DIR(config)
>  AC_CONFIG_MACRO_DIR(config)
> -AM_INIT_AUTOMAKE([1.10 -Wall -Werror foreign subdir-objects std-options dist-bzip2])
> +AM_INIT_AUTOMAKE([1.10 -Wall foreign subdir-objects std-options dist-bzip2])
>  AC_CONFIG_HEADERS([include/config.h])
>  AC_CONFIG_SRCDIR(zbar/scanner.c)
>  LT_PREREQ([2.2])
> +AM_PROG_AR
>  LT_INIT([dlopen win32-dll])
>  LT_LANG([Windows Resource])
> ```

This patch works using libtool from system. I'm able to crosscompile for aarch64 without the gigapatch.

**Comment by madebr** [comment]
> I believe the project is dead. There is also a [mirror in github](https://github.com/ZBar/ZBar). On that one the latest release is also 0.10 but they continued developing for android and iOS. 

Check this list: https://git.linuxtv.org/zbar.git/refs/
It contains both the original, the iphone versions and new more recent tags.


> But it is weird because if you compare the sources of github and the official ones (sourceforge), on the same release (0.10) they're not the same. Specifically, `configure` is missing on the github clone, 

It looks like the tagged commits are not the releases. The releases are probably the commits + running autoreconf on the repo.

> I'm not sure about the rest of the files. When had this conversation when we merged the original recipe for zbar and we decided to stick with the official sources.

Nevertheless, we will need to run autoreconf on the sources, irrespective it is a release or a tagged release.

**Comment by ericriff** [comment]
OK so do you want to switch to this unofficial fork?

**Comment by madebr** [comment]
This is not up to me.
Since you're using zbar apparently, does the fork fix any issues?

**Comment by ericriff** [comment]
The company where I work has a internal mirror of conan-index and we're sticking with the latest official sources there, at least for now.
I don't have a preference for which sources to use here.

**Comment by madebr** [comment]
@ericriff 
fedora is using zimg from https://github.com/sekrit-twc/zimg

see https://src.fedoraproject.org/rpms/zimg/blob/master/f/zimg.spec#_6

**Comment by ericriff** [comment]
> @ericriff
> fedora is using zimg from https://github.com/sekrit-twc/zimg
> 
> see https://src.fedoraproject.org/rpms/zimg/blob/master/f/zimg.spec#_6

This is ZBAR not ZIMG.

**Comment by madebr** [comment]
Oops! :head
See https://src.fedoraproject.org/rpms/zbar/blob/master/f/zbar.spec#_2
They are building 0.23 from linuxtv

**Comment by ericriff** [comment]
I'll move to that sources then. That was enough to tilt the balance haha
Thanks for the research and help!

**Comment by madebr** [comment]
Btw, it looks like fedora is adding `gettext` as a build requirement.
Probably for the same reason as https://github.com/conan-io/conan-center-index/pull/2029#issuecomment-649151994
Probably something to look into.

**Comment by ericriff** [comment]
> Btw, it looks like fedora is adding `gettext` as a build requirement.
> Probably for the same reason as [#2029 (comment)](https://github.com/conan-io/conan-center-index/pull/2029#issuecomment-649151994)
> Probably something to look into.

The build fails without it now so we definitely need it. Regardless the build keeps failing on my PC and complains about a missing file in `gettext/package/share` which is being manually deleted in gettext's recipe. I've launched a build in the CI just in case.
The build succeeds locally with my system tools (libtool 2.4.6 + gettext 0.19.7)

**Comment by ericriff** [comment]
@madebr I've been doing some tests and:
1. Using `gettext` as a `build_requirement` makes the build fail because is `autopoint` tries to extract the infrastructure files for version 0.20 from `package/hash/share/gettext/archive.dir.tar.xz` but the share folder has been manually deleted from `gettext`'s recipe. See https://www.gnu.org/software/gettext/manual/html_node/autopoint-Invocation.html

2. Adding the next statements makes the build pass using conan's `libtool` (as you said) but it depends on system files.
```
with tools.chdir(self._source_subfolder):
   with tools.environment_append({"AUTOMAKE_CONAN_INCLUDES": ["/usr/share/aclocal"]}):
      self.run("autoreconf -fiv")
```
This files are also present in the `share` folder of `gettext`.
Can we leave that folder (or at least a part of if) in the `gettext` package?

3. Removing `AM_GNU_GETTEXT_VERSION(0.20)` and `AM_GNU_GETTEXT_REQUIRE_VERSION(0.18)` make the build pass with a message saying "not using gettext", but I don't know the implications of that.

4. I build `gettext` locally without removing the `share` folder and with that package the build succeeds. I'm not sure how to point `AUTOMAKE_CONAN_INCLUDES` to that package.

**Comment by ericriff** [comment]
I've completely forgotten about this PR since we stuck with version 0.10.
I managed to get it to build locally by adding `gettext` as a build requirement, but it doesn't work out of the box since it needs the flowing file that is being deleted on the gettext recipe (the whole `share` folder is being deleted):
`gettextPackage/recipeHash/share/gettext/archive.dir.tar.xz`
I modified the `gettext` recipe so it keeps that file and it works, but the hooks complain about it:
`ERROR: [DEFAULT PACKAGE LAYOUT (KB-H013)] Unknown folder 'share' in the package (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H013)`
What should I do in this situation?

**Comment by madebr** [comment]
> What should I do in this situation?

This is what I would do:
First, I would fix the gettext recipe and change the installation directory of the `share` folder (=datarootdir) to `bin/share`.
  Remove the other superfluous files from the `bin/share` folder.
  Eventually add some `self.user_info` variables so consumers know the location of certain files.
  e.g. `self.user_info.GETTEXT_TAR = os.path.join(self.package_folder, "bin", "share", "gettext", "archive.dir.tar.xz")`
  I'm not sure about the naming of the variables.
Then I think this information can be used in zbar.

**Pull request closed without merging**
