### PR TITLE
Use set_property for boost

### PR DESCRIPTION
**Pull request by db4**
Specify library name and version:  **boost**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
If I understand https://github.com/conan-io/conan/pull/8533#issuecomment-972860669, we should avoid to move to `set_property()` in CCI for the moment.

**Comment by db4** [comment]
> If I understand [conan-io/conan#8533 (comment)](https://github.com/conan-io/conan/pull/8533#issuecomment-972860669), we should avoid to move to `set_property()` in CCI for the moment.

You may be right but
- there are many PRs already merged that add set_propery to CCI. e.g. https://github.com/conan-io/conan-center-index/pull/8059 https://github.com/conan-io/conan-center-index/pull/8010 etc.
- conan 1.42.x makes my recipes without set_property just unusable with CMakeDeps generator. What can be done right now? I understand CMakeDeps is experimental but breaking everything by releasing the next version of Conan is too much.

**Comment by SpaceIm** [comment]
> conan 1.42.x makes my recipes without set_property just unusable with CMakeDeps generator. What can be done right now? I understand CMakeDeps is experimental but breaking everything by releasing the next version of Conan is too much.

Yes, here is the issue: https://github.com/conan-io/conan/issues/9943. Due this issue and unstability of `set_property()` (https://github.com/conan-io/conan/pull/8533#issuecomment-972860669), there is no way support both `cmake_find_package_*` and `CMakeDeps` generators.

**Comment by db4** [comment]
@SpaceIm your point is taken. So what do now: just close the PR or live it open until better times arrive?

**Comment by madebr** [comment]
I would close it.
There will be a point in the not-so-distant-future where we will have to modify all recipes to support conan 2.0.

**Pull request closed without merging**
