### PR TITLE
osmanip: add package_type + modernize a little bit more

### PR DESCRIPTION
**Pull request by SpaceIm**
- add package_type
- use self.settings/self.compiler in validate() instead of self.info
- consistent value between Visual Studio & msvc in _compiler_required_cpp17()
- bump boost & arsenalgear

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by RubenRBS** [comment]
building the missing binary now, will re-trigger once it finishes

**Comment by SpaceIm** [comment]
> building the missing binary now, will re-trigger once it finishes

@RubenRBS did you build missing binaries?

**Comment by SpaceIm** [comment]
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
*/*:shared=True

(...)

osmanip/4.1.0: Forced build from source
Requirements
    arsenalgear/1.2.2#6ad6d73fc766aaf49c24a28912e3ab7d:7f0bbd5375c4a3e4ada12caa76a83f769182d3fc - Missing
    boost/1.83.0#7825569cd0622461dec7bc87dfdf47ae:429e7ec76eac4cedcc1132ba92cb583d1a722d90#12c403972c67557de33f461ed70e5faa - Download (conan-center)
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d:582795513620c02434315fe471662206b3a90c44#b812d992549c98cd781d28fb30f67c84 - Download (conan-center)
    exprtk/0.0.2#7c52632dc5320bf71832189b33d0fee8:da39a3ee5e6b4b0d3255bfef95601890afd80709#61d06332deb8b42ee2e2d6fdd71467f6 - Download (conan-center)
    libbacktrace/cci.20210118#ec1aa63bbc10145c6a299e68e711670c:abe5e2b04ea92ce2ee91bc9834317dbe66628206#45e9c64d8dbd428762c1a7ca0bdc9456 - Download (conan-center)
    osmanip/4.1.0#8b949b3bf0e1c8b5fc0bf8984d1dc2a4:802bfe2e283b8306a1236d24637fecfaa61355e8 - Build
    zlib/1.3#06023034579559bb64357db3a53f88a4:abe5e2b04ea92ce2ee91bc9834317dbe66628206#be744f18843976f205e00744293521b8 - Download (conan-center)
Build requirements
Skipped binaries
    b2/4.10.1

======== Installing packages ========
ERROR: Missing binary: arsenalgear/1.2.2:7f0bbd5375c4a3e4ada12caa76a83f769182d3fc
```

Ok I understand now, it's a know 2 pipeline bug (or wrong logic), the same one for which we have forced hwloc to be shared only instead of static or shared, just because onetbb is shared only.

So arsenalgear is static only, it doesn't have a shared option, but it has dependencies before 2.0.0 (boost, and eventually exprtk). exprtk is header-only so no problem, but boost has a shared option. So because arsenalgear doesn't have a shared option, v2 pipeline doesn't try to build `*:shared=True` flavor. But when a recipe depending on arsenalgear has a shared option, `*:shared=True` fails because these binaries are missing...

**Comment by SpaceIm** [comment]
see https://github.com/conan-io/conan-center-index/issues/21283

**Comment by SpaceIm** [comment]
`shared` option in arsenalgear restored by https://github.com/conan-io/conan-center-index/pull/21282, just waiting to be merged.

**Comment by SpaceIm** [comment]
This PR has been reused in https://github.com/conan-io/conan-center-index/pull/22309, which has been merged, so it's not relevant anymore.

**Pull request closed without merging**
