### PR TITLE
cmake: add version 3.29.7

### PR DESCRIPTION
**Pull request by j-carl**
### Summary
Changes to recipe:  **cmake/3.29.7**

#### Motivation

Add CMake version 3.29.7.

#### Details

Support latest CMake of the 3.29.x releases.

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]
We can probably start to drop versions for this config.yml - As we just package the binaries, the recipe itself sees not too many changes, and deleting them from here keeps them available in the `conancenter` remote, just not present in the file, which might help with future maintainability

```
56d9c70c4d8bf086b768496db8cc2542803a3b48a7484997c6df6740854e163  cmake-3.29.7-linux-aarch64.sh
ee8cf1ceaef011578ec070c13471c4b26e87f065315155e11177063b0743da68  cmake-3.29.7-linux-aarch64.tar.gz
9d1679c5b1058066484cbf8d36ad9c6f03ed7815f707b275b72da3d422292eef  cmake-3.29.7-linux-x86_64.sh
fb0837495a3a1d044f5101d0a76d294c825ff85c10a32c42d7167604278344f7  cmake-3.29.7-linux-x86_64.tar.gz
1927ad1392283d76e4657b579ac2e72c6c5d72438b8049f1a00cc4aff1d6e63e  cmake-3.29.7-macos-universal.dmg
79d8ce842c083c4829c1b614ce4cf1054312348fcf7fd4101a3b35b5b81d33b8  cmake-3.29.7-macos-universal.tar.gz
d297001414b883ac9691a53653da896ed553735eb034a7ef539baec498be21ae  cmake-3.29.7-macos10.10-universal.dmg
3a148e37bf57c419e40817d6208916a33eff8c1757b0947d9991eca902916559  cmake-3.29.7-macos10.10-universal.tar.gz
adef5f556e54ba3da884d701100ea0952a9d965b8bcb2f6b3c7f831d2c514b16  cmake-3.29.7-windows-arm64.msi
7a7053886069841b90990303283c546d4b3fd531a68972a601e124d95b4e333d  cmake-3.29.7-windows-arm64.zip
b0954f6962af2ef94bc053a8892dec1dca1268bc433ffe38fd27d55fa5e6952b  cmake-3.29.7-windows-i386.msi
ae87f2ff173deeb3ae8891d31c8f92ebabab8a4c29a074c5c5d39b38dde706d2  cmake-3.29.7-windows-i386.zip
454c1b68d61b8945c1566c598a8ec77caf799ebd2d51277e6de96acbde652046  cmake-3.29.7-windows-x86_64.msi
3d9580b54faa0651f4cb0bccdff222bd123366b35a8b1051ee33a64915384ee4  cmake-3.29.7-windows-x86_64.zip
```

**Comment by jcar87** [comment]
> We can probably start to drop versions for this config.yml - As we just package the binaries, the recipe itself sees not too many changes, and deleting them from here keeps them available in the `conancenter` remote, just not present in the file, which might help with future maintainability
> 
> ```
> 56d9c70c4d8bf086b768496db8cc2542803a3b48a7484997c6df6740854e163  cmake-3.29.7-linux-aarch64.sh
> ee8cf1ceaef011578ec070c13471c4b26e87f065315155e11177063b0743da68  cmake-3.29.7-linux-aarch64.tar.gz
> 9d1679c5b1058066484cbf8d36ad9c6f03ed7815f707b275b72da3d422292eef  cmake-3.29.7-linux-x86_64.sh
> fb0837495a3a1d044f5101d0a76d294c825ff85c10a32c42d7167604278344f7  cmake-3.29.7-linux-x86_64.tar.gz
> 1927ad1392283d76e4657b579ac2e72c6c5d72438b8049f1a00cc4aff1d6e63e  cmake-3.29.7-macos-universal.dmg
> 79d8ce842c083c4829c1b614ce4cf1054312348fcf7fd4101a3b35b5b81d33b8  cmake-3.29.7-macos-universal.tar.gz
> d297001414b883ac9691a53653da896ed553735eb034a7ef539baec498be21ae  cmake-3.29.7-macos10.10-universal.dmg
> 3a148e37bf57c419e40817d6208916a33eff8c1757b0947d9991eca902916559  cmake-3.29.7-macos10.10-universal.tar.gz
> adef5f556e54ba3da884d701100ea0952a9d965b8bcb2f6b3c7f831d2c514b16  cmake-3.29.7-windows-arm64.msi
> 7a7053886069841b90990303283c546d4b3fd531a68972a601e124d95b4e333d  cmake-3.29.7-windows-arm64.zip
> b0954f6962af2ef94bc053a8892dec1dca1268bc433ffe38fd27d55fa5e6952b  cmake-3.29.7-windows-i386.msi
> ae87f2ff173deeb3ae8891d31c8f92ebabab8a4c29a074c5c5d39b38dde706d2  cmake-3.29.7-windows-i386.zip
> 454c1b68d61b8945c1566c598a8ec77caf799ebd2d51277e6de96acbde652046  cmake-3.29.7-windows-x86_64.msi
> 3d9580b54faa0651f4cb0bccdff222bd123366b35a8b1051ee33a64915384ee4  cmake-3.29.7-windows-x86_64.zip
> ```

Wouldn't worry _too_ much - if the recipe doesn't change, CI should only be building the new versions anyway - although I suspect it is testing all of them unnecessarily.

@j-carl  - given that cmake 3.30 is alrady out, is there much of publishing this version? trying to understand clear motivations behind publishing a version that may not be used at all anyway

**Comment by j-carl** [comment]
@jcar87 The reason to publish this version is that is not always possible to update to the latest version, but you can update without any problems a patch level. I can speak from my personal and professional experience.
Also sometimes people are stuck on certain version and didn't have the time to address the problem to fix it, so they stay on that version.

**Review by perseoGI — APPROVED** [review]
LGTM https://github.com/Kitware/CMake/releases/download/v3.29.7/cmake-3.29.7-SHA-256.txt

**Pull request merged**
