### PR TITLE
WIP [c-ares] try simple things first

### PR DESCRIPTION
**Pull request by dmn-star**
Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by anton-dirac** [comment]
@dmn-star Thx for the help :)
I think it might be the logic that select `tools` based on cross building that fails. When I replace it:
https://github.com/conan-io/conan-center-index/pull/4492/commits/ce6996579142916766ec41fe6fed766cb3f4bfff
It seems to work on CCI.
I don't understand why though...

**Comment by prince-chrismc** [comment]
Please put the recipe name in the title 🙏

**Comment by dmn-star** [comment]
I hope that the unexpected error will be gone when I do. 😂

**Comment by dmn-star** [comment]
> @dmn-star Thx for the help :)
> I think it might be the logic that select `tools` based on cross building that fails. When I replace it:
> [ce69965](https://github.com/conan-io/conan-center-index/commit/ce6996579142916766ec41fe6fed766cb3f4bfff)
> It seems to work on CCI.
> I don't understand why though...

Don't mention it. I would also like to understand it, but as you can see it is not so easy with the CCI.

**Comment by prince-chrismc** [comment]
CI failed but did not post a message 😖

**Comment by dmn-star** [comment]
The simple things are not so simple after all. :-)

**Pull request closed without merging**
