### PR TITLE
OneDPL: add versions 2021.6.1 & 2021.7.0

### PR DESCRIPTION
**Pull request by jhabermas**
Specify library name and version:  **OneDPL/2021.7.0**

This PR adds two of the latest versions of OneDPL to the recipe, which allow integration of latest OneTBB and fix C++20 compilation errors.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@jhabermas I see both recipes are pretty similar. Why not combine both on same folder (all)?

**Comment by jhabermas** [comment]
As the old recipe has not been maintained since creation I thought it may be easier to just create a new one. The OneDPL project has changed in terms of folders/files layout, but it is possible to merge the two if you think that would be better.

**Comment by jhabermas** [comment]
@jgsogo How would you suggest dealing with different include file structure, i.e. `<pstl/execution>` in 2020x vs `<oneapi/dpl/execution>` in 2021.x, in test packages?

**Comment by jgsogo** [comment]
There are several options, but I would just go with the most straightforward one: duplicate the `main.cpp` file and use a different one for each version (like `main.2020x.cpp` and `main.2021x.cpp`, then:

**test_package/conanfile.py**
```

def build(self):
   ...
   cmake.definitions["VERSION"] = "2020x"/"2021x"
```

and the `CMakeLists.txt` with something like:

```
add_executable(${PROJECT_NAME} main.${VERSION}.cpp)
```

But any approach will probably be ok.

**Review by jgsogo — COMMENTED** [review]
Looks good, but now linter errors need to be fixed before merging:

image

I hope the help on the linked docs page is enough. If not, please let me know and I can submit a PR with the required changes to your branch.

Thanks!

**Review by jgsogo — APPROVED** [review]
Thanks for taking care of linter errors! 🙌

**Review by uilianries — APPROVED** [review]

**Pull request merged**
