### PR TITLE
libzippp: fix all shared build on Linux for conan v2 + add package_type

### PR DESCRIPTION
**Pull request by SpaceIm**
When it has been migrated to CMakeToolchain, a tricky detail has been skipped: this recipe was relying on the implicit behavior that it was built as a subdirectory through the old CMakeLists wrapper, and since upstream CMakeLists has a special logic to enable tests by default if CMakeLists is top project (https://github.com/ctabin/libzippp/blob/libzippp-v6.0-1.9.2/CMakeLists.txt#L30) and that this recipe did not explicitly manage this option, therefore tests were built after the migration and failed on Linux with conan v2 client (see https://github.com/conan-io/conan/issues/13560).

This PR explicitly disables the build of upstream tests.

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
ERROR: libzip/1.7.3: Error in config_options() method, line 50
	del self.options.zstd
	ConanException: option 'zstd' doesn't exist
Possible options are ['shared', 'fPIC', 'with_bzip2', 'with_lzma', 'with_zstd', 'crypto', 'tools']
```

libzip needs a fix for conan v2

**Comment by SpaceIm** [comment]
waiting https://github.com/conan-io/conan-center-index/pull/16777

**Comment by SpaceIm** [comment]
pre-built packages, are you there?

**Comment by SpaceIm** [comment]
```
ERROR: Missing binary: libzippp/4.0:ca77165b27bdde1da1fc1239bc0a2283a66191cd
libzippp/4.0: WARN: Can't find a 'libzippp/4.0' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++11, compiler.version=5, os=Linux
- Options: fPIC=True, shared=False, with_encryption=False, bzip2:build_executable=True, bzip2:fPIC=True, bzip2:shared=False, libzip:crypto=openssl, libzip:fPIC=True, libzip:shared=False, libzip:tools=True, libzip:with_bzip2=True, libzip:with_lzma=True, openssl:386=False, openssl:enable_weak_ssl_ciphers=False, openssl:fPIC=True, openssl:no_aria=False, openssl:no_asm=False, openssl:no_async=False, openssl:no_bf=False, openssl:no_blake2=False, openssl:no_camellia=False, openssl:no_cast=False, openssl:no_chacha=False, openssl:no_cms=False, openssl:no_comp=False, openssl:no_ct=False, openssl:no_deprecated=False, openssl:no_des=False, openssl:no_dgram=False, openssl:no_dh=False, openssl:no_dsa=False, openssl:no_dso=False, openssl:no_ec=False, openssl:no_ecdh=False, openssl:no_ecdsa=False, openssl:no_engine=False, openssl:no_filenames=False, openssl:no_gost=False, openssl:no_hmac=False, openssl:no_idea=False, openssl:no_md4=False, openssl:no_md5=False, openssl:no_mdc2=False, openssl:no_ocsp=False, openssl:no_pinshared=False, openssl:no_rc2=False, openssl:no_rfc3779=False, openssl:no_rmd160=False, openssl:no_rsa=False, openssl:no_seed=False, openssl:no_sha=False, openssl:no_sm2=False, openssl:no_sm3=False, openssl:no_sm4=False, openssl:no_sock=False, openssl:no_srp=False, openssl:no_srtp=False, openssl:no_sse2=False, openssl:no_ssl=False, openssl:no_ssl3=False, openssl:no_stdio=False, openssl:no_tests=False, openssl:no_threads=False, openssl:no_tls1=False, openssl:no_ts=False, openssl:no_whirlpool=False, openssl:openssldir=None, openssl:shared=False, xz_utils:fPIC=True, xz_utils:shared=False, zlib:fPIC=True, zlib:shared=False
- Dependencies: zlib/1.2.13, libzip/1.7.3
- Requirements: libzip/1.Y.Z, zlib/1.Y.Z
- Package ID: ca77165b27bdde1da1fc1239bc0a2283a66191cd

ERROR: Missing prebuilt package for 'libzippp/4.0'
Use 'conan search libzippp/4.0@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=libzippp'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

@danimtb @uilianries https://github.com/conan-io/conan-center-index/pull/16777 has been merged yesterday, but some packages have not been generated.

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
