### PR TITLE
simdjson: add version 1.1.0

### PR DESCRIPTION
**Pull request by theirix**
Specify library name and version:  **simdjson/1.1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by theirix** [comment]
Should it restart after reopening the PR? The first build failed due to github timeout.

**Comment by uilianries** [comment]
@theirix if you re-open, it will put a new build in the work queue. Right now it's running already, and it's computing the package IDs to be built. 

Screenshot 2022-05-19 at 15-19-46 simdjson add version 1 1 0 by theirix · Pull Request #10857 · conan-io_conan-center-index

The important thing is the build `pr-merge`. If it's yellow (running), it means, your PR is listed to be built. When is red, so we need to restart or fix the PR.

**Comment by theirix** [comment]
@uilianries thanks! now I can see it, the entry "continuous-integration/jenkins/pr-merge" was somewhere at the middle of the list. If this check can be moved to the top, it will be more visible.

**Comment by uilianries** [comment]
@theirix Indeed a good idea. I'll put it in the work list!

**Review by toge — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by jgsogo** [comment]
> @uilianries thanks! now I can see it, the entry "continuous-integration/jenkins/pr-merge" was somewhere at the middle of the list. If this check can be moved to the top, it will be more visible.

Yes, we can add some symbol so it is ordered before those `[required]...` entries (it uses lexicographic for the same status level)... but while it is running it will go always after failed ones, IIRC: first failed, then running, then success ones.

**Review by uilianries — APPROVED** [review]

**Pull request merged**
