### PR TITLE
Add sigslot 1.2.0

### PR DESCRIPTION
**Pull request by IceflowRE**
Specify library name and version:  **sigslot/1.2.0**
https://github.com/palacaze/sigslot

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by IceflowRE** [comment]
Only gcc with listdc++? or others too?

**Comment by uilianries** [comment]
It's fast fail

**Comment by IceflowRE** [comment]
https://gcc.godbolt.org/z/84GKqr

No clue what it is causing but it fails with gcc 7.3 downwards and clang 3.7 downwards.

**Comment by madebr** [comment]
```
However, be aware of a potential gotcha on Windows with MSVC and Clang-Cl compilers, which may need the /OPT:NOICF linker flags in exceptional situations. Read The Implementation Details chapter for an explanation.
```

```
MSVC and Clang-cl in Release mode optimize functions with the same definition by merging them. This is a behaviour that can be deactivated with the /OPT:NOICF linker option. Sigslot tests and examples rely on a lot a identical callables which trigger this behaviour, which is why it deactivates this particular optimization on the affected compilers.
```

**Comment by IceflowRE** [comment]
> 
> 
> https://github.com/palacaze/sigslot#installation
> 
> > However, be aware of a potential gotcha on Windows with MSVC and Clang-Cl compilers, which may need the /OPT:NOICF linker flags in exceptional situations. Read The Implementation Details chapter for an explanation.
> 
> https://github.com/palacaze/sigslot#implementation-details
> 
> > MSVC and Clang-cl in Release mode optimize functions with the same definition by merging them. This is a behaviour that can be deactivated with the /OPT:NOICF linker option. Sigslot tests and examples rely on a lot a identical callables which trigger this behaviour, which is why it deactivates this particular optimization on the affected compilers.

I set those values:
https://github.com/conan-io/conan-center-index/pull/2202/files#diff-84cda6e8aec631422e9c3617c586f38dR55-R56
(And it is working with the latest Visual Studio)

**Comment by madebr** [comment]
> I set those values:
> https://github.com/conan-io/conan-center-index/pull/2202/files#diff-84cda6e8aec631422e9c3617c586f38dR55-R56
> (And it is working with the latest Visual Studio)

Sorry, I didn't check your recipe.
Too bad godbolt does not support running Windows code.
I'd suggest opening an issue at the project's page or disabling VS2015.

**Comment by IceflowRE** [comment]
Reported here https://github.com/palacaze/sigslot/issues/15
But will disable VS2015 for now.

**Comment by palacaze** [comment]
Thank you for opening a bug upstream.

> https://gcc.godbolt.org/z/84GKqr
> 
> No clue what it is causing but it fails with gcc 7.3 downwards and clang 3.6 downwards.

This is caused by an unfortunate bug in GCC. Here is the bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68071

There is no obvious way of getting around it. I can change the basic.cpp example to use a non-empty signal, or deactivate generic lambdas for old GCC.

For the MVSC 2015 problem, this seems like a bogus warning to me (Error C4996). I do not see how comparing 2 char arrays of the same size should warrant such message. I can disable C4996 using a pragma if you want.

**Comment by IceflowRE** [comment]
Wow that is a quick reply.

> This is caused by an unfortunate bug in GCC. Here is the bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68071

Yes, i already found out too. Thus i disabled the library generation for the buggy compiler versions. I think there's no need to create a work around (at least from my side).

> For the MVSC 2015 problem, this seems like a bogus warning to me (Error C4996). I do not see how comparing 2 char arrays of the same size should warrant such message. I can disable C4996 using a pragma if you want.

Disabling the warning will not help, as the crash happens at runtime.

**Comment by palacaze** [comment]
I answered in the upstream bug. I basically cannot do anything about MSVC 2015 at this point because I do not have a means of reproducing it.

Is MSVC 2015 update 3 supposed to be c++14 compliant?

**Comment by palacaze** [comment]
I fixed the basic example to avoid the GCC bug on old compilers and improved MSVC handling somewhat. However MSVC 2015 still is not a supported platform.

**Pull request merged**
