### PR TITLE
[fix hooks] json-c

### PR DESCRIPTION
**Pull request by danimtb**
Specify library name and version:  **json-c/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by danimtb** [comment]
Ok, I will wait for #3748 to be merged if the reviews arrive there and close this. Meanwhile I will make this a draft to avoid it is merged.

**Review by Croydon — APPROVED** [review]

**Comment by uilianries** [comment]
@danimtb Another unexpected error, is it kind expected?

**Comment by danimtb** [comment]
We are having some performance issues creating new repositories...

**Comment by danimtb** [comment]
Yep, changes in this PR got merged in  #3748, closing this one

**Pull request closed without merging**
