### PR TITLE
add sdl2 2.0.10

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **sdl2/2.0.10**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
what would that mean ?
```
ERROR: sdl2/2.0.10: Error in package_info() method, line 350
	self.cpp_info.frameworks.extend(['Cocoa', 'Carbon', 'IOKit', 'CoreVideo', 'CoreAudio', 'AudioToolbox', 'ForceFeedback'])
	AttributeError: '_CppInfo' object has no attribute 'extend'
```

**Comment by madebr** [comment]
@ericLemanissier 
https://docs.conan.io/en/1.18/reference/conanfile/attributes.html#cpp-info has no `self.cpp_info.frameworks`.
So I think the conan version on conan-center-index is 1.18 (or older) because it was introduced in conan 1.19.
Also, I cannot find the conan version in the logs.

**Comment by Croydon** [comment]
SDL is really heavy on system requirements. 
Don't we want to concentrate first on getting recipes into CCI who aren't relying on them in a first step?

**Comment by SSE4** [comment]
I fully support Croydon on this

**Pull request closed without merging**
