### PR TITLE
add range-v3/cci.20211210

### PR DESCRIPTION
**Pull request by pdavydov108**
Specify library name and version:  **range-v3/cci.20211210**

This merge request closes https://github.com/conan-io/conan-center-index/issues/8386. Why I need this:
 - [this issue](https://github.com/ericniebler/range-v3/issues/1633) breaks compilation on clang-13, and is fixed in the latest master
 - range-v3 has no release for more then a year

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — DISMISSED** [review]

**Comment by david-fong** [comment]
I'm a little sad this died. Any chance of reviving it?

**Comment by pdavydov108** [comment]
@david-fong I was not able to debug the build on windows, cause I don't have a windows machine. I will try to fix it when I have time.

**Comment by david-fong** [comment]
I have a windows 10 machine. Is there a way I can help debug? I have visual studio 17 only right now but I can install 16.

It's strange though- isn't the build failing for range-v3 `0.10.0` on windows visual studio? Isn't that completely unrelated to this PR?

**Comment by madebr** [comment]
> I have a windows 10 machine. Is there a way I can help debug?

Every helping hand is useful and is very much appreciated!
You can help by trying to build + run the test package of range-v3 on the set of compilers you have access to.

It looks like the test on Visual Studio 2019 with MT runtime is failing, building a Release executable.
So trying to run
```
conan create recipes/range-v3/all range-v3@0.9.1 -s compiler.runtime=MT -s build_type=Release
conan create recipes/range-v3/all range-v3@0.10.0 -s compiler.runtime=MT -s build_type=Release
conan create recipes/range-v3/all range-v3@0.11.0 -s compiler.runtime=MT -s build_type=Release
conan create recipes/range-v3/all range-v3@cci.20211210 -s compiler.runtime=MT -s build_type=Release
```

> I have visual studio 17 only right now but I can install 16.

You can first try to build with Visual Studio 2022, and if that version does not reproduce the error you can try installing 2019.
There is of course always the possibility that this is a c3i (=name of the build service) specific issue.

If you are able to reproduce, but do not know how to fix it, explaining the issue here with eventual links to code in the range repo might also be useful. Other people can suggest fixes.

> It's strange though- isn't the build failing for range-v3 `0.10.0` on windows visual studio? Isn't that completely unrelated to this PR?

This pr also modified the main recipe, so c3i decided it had to rebuild all versions.
If OP would only have modified config.yml and conandata.yml, older versions would not have been touched.
If OP would have touched the test package, c3i would also have re-run the tests for all versions.

**Comment by david-fong** [comment]
My tool info:

```
MSVC version: 19.32.31328.0
compiler version: 17
arch: x86_64
```

I was able to run the commands for `0.11.0` and `cci.20211210` with no issue- tests passed. But for `0.9.1` and `0.10.0` I got a bunch of warnings and errors all for the `concepts/concepts.hpp` file. There were much more for `0.9.1`.

<details>
<summary>Here are the diagnostics I got for `0.10.0`</summary>
<code>
C:\...\.conan\...\include\concepts/concepts.hpp(890,13): warning C4002: too many ar
guments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\0b1ab9468058b3e23c47f8
9801b8501bcc1031e3\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(890,1): error C3861: 'u': identifie
r not found [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1016,13): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1016,1): error C3861: 'u': identifier not found [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1024,13): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1024,1): error C3861: 'u': identifier not found [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1032,13): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1032,1): error C3861: 'u': identifier not found [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1064,13): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1064,1): error C3861: 'u': identifier not found [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1079,13): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1079,1): error C3861: 'u': identifier not found [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1169,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1174,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1179,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1183,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1187,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1191,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1207,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1215,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1223,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\concepts/concepts.hpp(1231,17): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1' [C:\...\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
C:\...\.conan\...\include\range/v3/detail/config.hpp(223,1): fatal error C1189: #er
ror:  range-v3 requires Visual Studio 2019 with the /std:c++17 (or /std:c++latest) /permissive- and /experimental:preprocessor options. [C:\...\code\fork\conan-ce
nter-index\recipes\range-v3\all\test_package\build\...\test_package.vcxproj]
ERROR: range-v3/0.10.0@conan/stable (test package): Error in build() method, line 12
   cmake.build()
   ConanException: Error 1 while executing cmake --build C:\...\recipes\range-v3\all\test_package\build\... --config Release -- /m:8 /verbosity:minimal
</code>
</details>

I have no idea how those preprocessor macros work :P

Note: I had to add "`user/channel`" args when running the commands. I don't know what those mean but I see they decide what folders to put things in under `~/.conan/data/range-v3`. I used "conan/stable".

**Comment by madebr** [comment]
I just happened to be logged in on a Windows machine right now, so I tested the range-v3 recipe using Visual Studio 16 2019.
Indeed, versions 0.9.1 and 0.10.0 fail to run the test package.
Weird, since its `test_package.cpp` hasn't been touched significantly since the first range-v3 commit
https://github.com/conan-io/conan-center-index/commits/master/recipes/range-v3/all/test_package/test_package.cpp

0.9.1 and 0.10.0 claim to support Visual Studio 2019.
But I'm fine with removing Visual Studio support in `recipes/range-v3/all/conanfile.py` (for versions <0.11)

**Comment by ericniebler** [comment]
This PR has been superseded by #11318 and can therefore be closed. It doesn't correspond to an official release of range-v3. #11318 adds the 0.12.0 release of range-v3.

**Pull request closed without merging**
