### PR TITLE
freetype: add 2.13.0 + modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
I guess these errors in apple-clang 11 come from this commit: https://gitlab.freedesktop.org/freetype/freetype/-/commit/ac5babe87629107c43f627e2cd17c6cf4f2ecd43

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by Nekto89** [comment]
Just accidentally saw this in log of 2.12.1.
"
-- Conan: Target declared 'BZip2::BZip2'
-- Conan: Including build module from '/home/conan/w/prod/BuildSingleReference/.conan/data/bzip2/1.0.8/_/_/package/76bd63d0cd275bc555bda09b7f93740254ba3515/lib/cmake/conan-official-bzip2-variables.cmake'
-- Checking for module 'bzip2'
--   No package 'bzip2' found
"

Is bzip2 properly consumed?

**Comment by SpaceIm** [comment]
> Just accidentally saw this in log of 2.12.1. " -- Conan: Target declared 'BZip2::BZip2' -- Conan: Including build module from '/home/conan/w/prod/BuildSingleReference/.conan/data/bzip2/1.0.8/_/_/package/76bd63d0cd275bc555bda09b7f93740254ba3515/lib/cmake/conan-official-bzip2-variables.cmake' -- Checking for module 'bzip2' -- No package 'bzip2' found "
> 
> Is bzip2 properly consumed?

Yes it's properly consumed. This message is a consequence of https://github.com/freetype/freetype/blob/master/CMakeLists.txt#L278-L289, but it doesn't matter since bzip2 is found through `find_package()`.

**Pull request merged**
