### PR TITLE
capnproto: zlib is a dependency of kj-http

### PR DESCRIPTION
**Pull request by fabiorossetto**
The conanfile of capnproto was failing to list zlib::zlib as a requirement for kj-http. This is wrong, as kj-http uses zlib directly in the websocket implementation, if zlib is used.

Specify library name and version:  **capnproto**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi @fabiorossetto thanks a lot for your contribution. We'd appreciate if you could get the CLA signed so that we're able to approve and merge this PR :)

**Comment by uilianries** [comment]
@fabiorossetto Thank you for your PR! Please, follow the access request instruction from the comment above: https://github.com/conan-io/conan-center-index/pull/18983#issuecomment-1792108430

**Comment by RubenRBS** [comment]
Will unblock this Pr in a bit, sorru for the confusion of the bot

**Review by uilianries — APPROVED** [review]
The change follows the upstream CMakeLists.txt: https://github.com/capnproto/capnproto/blob/bfe666ca97df24ac04dad008334b88da4ba32612/c%2B%2B/src/kj/CMakeLists.txt#L179

**Review by ericLemanissier — APPROVED** [review]

**Comment by SpaceIm** [comment]
It's incorrect for versions < 1.0.0. Moreover I don't think it's a good design to create components in two differents branches. Create it once, then extend its properties.

**Pull request merged**
