### PR TITLE
add portmidi/217

### PR DESCRIPTION
**Pull request by illume**
Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

My portmidi request issue: https://github.com/conan-io/conan-center-index/issues/3009

### CODE REVIEW

**Comment by illume** [comment]
I made a request yesterday.

**Comment by illume** [comment]
I don't think this is ready to be merged.

**Comment by Croydon** [comment]
@illume Approvals always take same time. In the meantime you got approved

Are you still interested in bringing in portmidi? 😃

**Comment by illume** [comment]
It's complicated. Portmidi isn't really maintained, and is kind of bitrotted. Except for random patches floating around the interwebs. I think I still have subversion access to the repo... but I don't know. I'm not sure if I want to try and maintain it, since I already have a lot to do.

**Comment by Croydon** [comment]
Understood :)

**Pull request closed without merging**
