### PR TITLE
rocksdb: patching thirdparty.inc. Modernized.

### PR DESCRIPTION
**Pull request by franramirez688**
ORIGINAL PR: https://github.com/conan-io/conan-center-index/pull/23090 ( I just added a commit to modernize the recipe but can not push directly to the original branch. Keeping the original author's commits anyway)

### Summary
Changes to recipe:  **rocksdb/x.x.x**

* Modernized recipe.
* Ignoring the `thirdparty.inc` file through more patches for all the versions.

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]

**Comment by thejohnfreeman** [comment]
Thank you for working on this! I see you changed `required_conan_version` to ">=2.0". Was that necessary or just recommended? My team is still largely using Conan 1.x. I _think_ we are ready to switch to 2.x, but would love to leave the 1.x option open if possible. For now, we keep a recipe for RocksDB, with the patch, in our own project, but I would love to get rid of that in favor of the version in Conan Center.

**Comment by RazielXYZ** [comment]
@thejohnfreeman Conan Center is no longer accepting packages/recipe updates/anything for Conan 1.x, so even if the 1.x stuff is left in the recipe, it won't propagate to the 1.x CC

**Review by RazielXYZ — APPROVED** [review]

**Comment by RazielXYZ** [comment]
@thejohnfreeman @franramirez688 if I'm reading rocksdb's CMakeLists right, setting ROCKSDB_SKIP_THIRDPARTY makes it so none of the third party libs are handled or included/linked on MSVC, only on the else() branch if the if(MSVC) check. The MSVC branch only handles libs through thirdparty.inc. So I think the patch is actually necessary for versions that have ROCKSDB_SKIP_THIRDPARTY as well.

**Review by RazielXYZ — CHANGES_REQUESTED** [review]
Patch still needed even with ROCKSDB_SKIP_THIRDPARTY

**Comment by thejohnfreeman** [comment]
That's correct. If `ROCKSDB_SKIP_THIRDPARTY` is passed, then _no_ third-party dependencies are searched when compiling with MSVC. We don't want that. We just want them searched with `find_package()`, with the additional handling that non-MSVC compilers enjoy.

**Comment by franramirez688** [comment]
@thejohnfreeman @RazielXYZ Thanks a lot for your comments! I did not realize about that, my bad 🙏 
I'll be working on the new patch 😉 I'll keep you posted

**Review by AbrilRBS — APPROVED** [review]

**Review by ErniGH — APPROVED** [review]
LGTM

**Pull request merged**
