### PR TITLE
pagmo2: migrate to Conan v2

### PR DESCRIPTION
**Pull request by valgur**

### CODE REVIEW

**Comment by valgur** [comment]
Closing temporarily to avoid unnecessary load on the CI. Will reopen when I'm actively working on the PR again.

**Review by jwillikers — APPROVED** [review]

**Review by RubenRBS — COMMENTED** [review]
Hi! Sorry that it took this long to get this PR reviewed. When closing a PR, GitHub marks it as done so we did not have it in our project list. This looks good to me, except for the dependency versions which maybe could get updated to better align with the rest of the repository? Wdyt @valgur?

**Comment by valgur** [comment]
@RubenRBS Updated the dependency versions. Thanks!

**Review by RubenRBS — APPROVED** [review]

**Comment by RubenRBS** [comment]
bump, dont close this

**Pull request merged**
