### PR TITLE
Remove name for openssl

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **openssl/all**

Related issue: https://github.com/conan-io/conan/issues/6269#issuecomment-570182130

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by danimtb** [comment]
I need to check what is happening here and if the packages were generated or not

**Comment by uilianries** [comment]
@danimtb I just solved the conflicts by merging the upstream

**Comment by danimtb** [comment]
> All green in build 7 (5ac4180099b1246237f07a1acd644a8facfc4743)! 😊

Well, I don't think that's true. Please @uilianries rename the folders in the *config.yml* file as well and let's see if that works

**Comment by uilianries** [comment]
I could revert only the commit, easier and faster, but no ... :man_facepalming:

**Comment by uilianries** [comment]
Well, it didn't work ...

**Comment by uilianries** [comment]
@danimtb This PR is a total mess, many commits to change only a simple point, I gonna close it and open a new one

**Comment by uilianries** [comment]
Moved to https://github.com/conan-io/conan-center-index/pull/690

**Pull request closed without merging**
