### PR TITLE
grpc : add version 1.64.2

### LINKED ISSUE #23084: [request] grpc/1.55.0
### Package Name/Version

grpc/1.55.0

### Changelog

https://github.com/grpc/grpc/releases/tag/v1.55.0

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

### PR DESCRIPTION
**Pull request by sophieeihpos**
grpc/1.64.2

fixes #23084 
---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

© 2024 Morgan Stanley.
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE Conan-io project Contributor License Agreement.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by sophieeihpos** [comment]
Thanks @RubenRBS I created a separate PR for protobuf #23095

**Comment by jcar87** [comment]
Hi @sophieeihpos - thank you for this PR and the time you dedicated to it! It's a remarkable effort!

In the end, in https://github.com/conan-io/conan-center-index/pull/24215 we opted to keep a static list of the grpc dependencies, similar to what is done for Qt and Boost, as we want to avoid text-parsing the CMake output. Parsing the CMake config files textually via regex was too complex for us to be comfortable.

Other points:
* macOS shared is supported in the newer version as per https://github.com/conan-io/conan-center-index/pull/24215 - after troubleshooting with upstream
* disabled downloading external files was merged in https://github.com/conan-io/conan-center-index/pull/24765

So I think the only feature missing in this PR that is not yet merged is the ability to switch off systemd support, correct? Please let me know how you'd like to proceed with that, thanks!

**Comment by sophieeihpos** [comment]
> Hi @sophieeihpos - thank you for this PR and the time you dedicated to it! It's a remarkable effort!
> 
> In the end, in #24215 we opted to keep a static list of the grpc dependencies, similar to what is done for Qt and Boost, as we want to avoid text-parsing the CMake output. Parsing the CMake config files textually via regex was too complex for us to be comfortable.
> 
> Other points:
> 
> * macOS shared is supported in the newer version as per [grpc add version 1.65 #24215](https://github.com/conan-io/conan-center-index/pull/24215) - after troubleshooting with upstream
> * disabled downloading external files was merged in [grpc : remove download_archive in CmakeLists.txt #24765](https://github.com/conan-io/conan-center-index/pull/24765)
> 
> So I think the only feature missing in this PR that is not yet merged is the ability to switch off systemd support, correct? Please let me know how you'd like to proceed with that, thanks!

Hi @jcar87 ,

Thank you for checking the PR.
I still see issue for the shared build in 1.65.0 as described here: https://github.com/grpc/grpc/issues/36654. We will use 1.62 as a workaround for now.
with_systemd is add as an option in the recipe, and it works fine.
I will close the PR for now, as the issues are resolved in other PRs.

**Comment by sophieeihpos** [comment]
Fixed in other PRs

**Comment by jcar87** [comment]
Thanks @sophieeihpos  for checking.

I'm surprised! The `shared=True` configuration on macOS should work as per: https://github.com/jcar87/conan-center-index/blob/ab602fc61b892c624f864198fd3cebe922d3b48f/recipes/grpc/all/conanfile.py#L226-L232 

If this doesn't work please let us know opening a new issue and we can certainly look into this

**Pull request closed without merging**
