### PR TITLE
[iir] Add a patch making exception throwing optional

### PR DESCRIPTION
**Pull request by wouterz**
Specify library name and version:  **iir1/1.9.0**

Through this patch throwing exceptions is made optional; I have also submitted a PR to upstream these changes but in the mean time an update to the repo also seems logical.
---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Why not waiting a new version? The patch is huge, it adds a feature, it's not a build fix. Moreover, there should be a new option in conanfile anyway.

**Comment by wouterz** [comment]
It doesn't break the library build, but it is breaking for `no-exception` projects using this library. However I do agree that it is also kind of a (big) feature, although the actual changes are only +- 90 lines (rest is padding in the `diff`).

The main reason for patching on conan, is for speed as Im not sure when a new release of the library is due.

I did forget the conanfile option... I will add this if the PR is considered viable

**Comment by uilianries** [comment]
I suggest asking to the author for a new release, or at least, a date to understand when we will have it available.

I would not include it on 1.9.0, because it will cause a different behavior from the official release.

If the author don't have a release in mind for now, you can create a custom version like `cci.<YYYYMMDD>` as documented [here](https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases).

**Comment by wouterz** [comment]
i have created a new PR #8835 creating a cci bump, so closing this one

**Pull request closed without merging**
