### PR TITLE
[mpir] there is only one Release build_type with MSVC

### PR DESCRIPTION
**Pull request by ohanar**
Specify library name and version:  **mpir/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
The different build_types set different compiler flags.
It's just not built using cmake.

So I think your assumption is invalid.

**Comment by ohanar** [comment]
Yes, when you are building with Autotools, I agree, different flags are use. For MSVC, mpir is not built with autotools, it is built with Visual Studio project files, which only support the notions of a Debug build and a Release build. Hence, my PR only makes this change for when mpir is built with MSVC.

**Comment by madebr** [comment]
Yeah sorry, but conan still tries to insert the correct compiler flags.
See the msbuild file: https://github.com/conan-io/conan/blob/c829789c2cd96a888494e6b994de37b52d26e707/conans/client/build/msbuild.py#L201

**Comment by ohanar** [comment]
Actually, it doesn't.
See same file: https://github.com/conan-io/conan/blob/c829789c2cd96a888494e6b994de37b52d26e707/conans/client/build/msbuild.py#L29.
As well as comment: https://github.com/conan-io/conan/blob/c829789c2cd96a888494e6b994de37b52d26e707/conans/client/build/visual_environment.py#L141.

Having read through the code, that does nothing that depends upon anything other than Debug vs Release. What it does
 - inject cflags from dependencies
 - set the MSVC runtime
 - sets the NDEBUG define if not a Debug build
 - set the c++ standard
 - set defines that were passed to `msbuild.build`

Seems fairly clear from the comment that this is intentional. Visual Studio project files are not as amiable to injection as some other build systems, so it makes perfect sense to do exactly what I did -- take what is supported by the library author, and use it where it is valid.

**Comment by madebr** [comment]
You're correct, thanks for guiding me.
Sounds like a limitation of conan to me.
Can't mpir really be built using autotools and MSVC?

**Comment by ohanar** [comment]
After reading a bit, it's probably not possible to build mpir using autotools and msvc. It sounds like the autotools build system has been heavily customized to support all of the hand-written assembly in the library.

**Comment by madebr** [comment]
You can do the following:
```python
msbuild = MSBuild(self)
msbuild.build_env = VisualStudioBuildEnvironment(self, True)
```

I would open a issue at the conan tracker.
Maybe `VisualStudioBuildEnvironment` should make the `_with_build_type_flags` member public.

**Comment by ohanar** [comment]
@madebr You are welcome to open an issue with conan about it. I don't personally consider it a bug -- not everything is built with CMake, and not everything should be pounded into the square hole that is CMake. This is one of those instances -- mpir has two build types with MSVC, Release and Debug, so choose among those two for all of the build configurations that conan supports.

**Comment by madebr** [comment]
@ohanar 
You're right.
I'm wondering whether the recipe needs this, instead of doing it in `package_id`.
```python
def configure(self):
    if self.settings.build_type not in ("Release", "Debug"):
        raise ConanInvalidConfiguration("mpir only supports the Release and Debug build_type")
```

**Pull request closed without merging**
