### PR TITLE
lcms: fix pkg_config name

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **lcms/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — DISMISSED** [review]

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@danimtb @SSE4 current recipe on CCI does not have this PR: https://conan.io/center/lcms/2.11/?user=_&channel=_&revision=&os=&tab=recipe
What's happening ?

**Comment by danimtb** [comment]
You are right. For some reason it seems that the master job to promote packages did not arrive to jenkins (see there is no ✔️ ) in the master commit:
image

**Comment by danimtb** [comment]
THe issue was github not notifying jenkins about this merge. I redeliver the request but the build was not triggered. Probably because Jenkins discards it due to having more recent builds in master. We are working on a job that runs "nightly" covering this kind of missing packages, meanwhile we have to solve the issue by hand opening a new PR

**Comment by ericLemanissier** [comment]
ok. https://github.com/conan-io/conan-center-index/commit/4bb2229556708660ec5c27e20e26f2a6fd1d1d03 and https://github.com/conan-io/conan-center-index/commit/327bf947d09b0c398263168dbb68fdaff4175719 don't have the tick either FYI

**Comment by danimtb** [comment]
Apparently the changes in https://github.com/conan-io/conan-center-index/commit/4bb2229556708660ec5c27e20e26f2a6fd1d1d03 are in conancenter, so no further action required.

Changes in https://github.com/conan-io/conan-center-index/commit/327bf947d09b0c398263168dbb68fdaff4175719 are not critical as they only affect the test_package files.

**Pull request merged**
