### PR TITLE
fix clang build of lemon

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **coin-lemon/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
When compiling with clang it failed here:
[ 87%] Building CXX object source_subfolder/lemon/CMakeFiles/lemon.dir/bits/windows.cc.o
In file included from /home/andrei/.conan/data/coin-lemon/1.3.1/_/_/build/3b1f65946d4569e4fd6d2f66c97efa1bef970855/source_subfolder/lemon/random.cc:22:
/home/andrei/.conan/data/coin-lemon/1.3.1/_/_/build/3b1f65946d4569e4fd6d2f66c97efa1bef970855/source_subfolder/lemon/random.h:252:9: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register Word *curr = state + length - 1;
        ^~~~~~~~~
/home/andrei/.conan/data/coin-lemon/1.3.1/_/_/build/3b1f65946d4569e4fd6d2f66c97efa1bef970855/source_subfolder/lemon/random.h:253:9: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register long num;
        ^~~~~~~~~

**Comment by uilianries** [comment]
If it requires C++14, need to validate minimal compiler version and self.settings.compiler.cppstd

**Comment by jgsogo** [comment]
> If it requires C++14, need to validate minimal compiler version and self.settings.compiler.cppstd

Please, @AndreyMlashkin , I think it makes sense to add here this suggestion.

Thanks!

**Comment by AndreyMlashkin** [comment]
The compiler should be "not higher then CPP 14", as 'register' keyword is removed after
Do you still think I need a check in this case?

Is there any example of new compilers, that support cpp17/20 and does not support cpp14?
If you name any, I will build in this check.

**Comment by uilianries** [comment]
@AndreyMlashkin take a look on args-parser recipe, that's the regular approach when we validate minimal compiler verison + cppstd

**Comment by AndreyMlashkin** [comment]
> @AndreyMlashkin take a look on args-parser recipe, that's the regular approach when we validate minimal compiler verison + cppstd

Again, in this case any old compiler should be ok. We need to ensure, it's less than cpp17.

**Comment by SSE4** [comment]
> @AndreyMlashkin take a look on args-parser recipe, that's the regular approach when we validate minimal compiler verison + cppstd

that seems to be not minimal, but maximal. see also https://github.com/conan-io/conan/issues/11080

**Comment by AndreyMlashkin** [comment]
Much easier would be a patch removing "register" from the code. I will open a separate PR

**Pull request closed without merging**
