### PR TITLE
imagemagick: don't set LIBS environment variable for autotools

### PR DESCRIPTION
**Pull request by Renari**
Specify library name and version:  **imagemagick/all**

Same fix as #3080

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Renari** [comment]
Hm, I'm not able to replicate this issue locally.

**Comment by ericLemanissier** [comment]
the error is caused by this:
```
checking for TIFF... 
checking tiff.h usability... yes
checking tiff.h presence... yes
checking for tiff.h... yes
checking tiffio.h usability... yes
checking tiffio.h presence... yes
checking for tiffio.h... yes
checking for TIFFOpen in -ltiff... no
checking for TIFFClientOpen in -ltiff... no
checking for TIFFIsByteSwapped in -ltiff... no
checking for TIFFReadRGBATile in -ltiff... no
checking for TIFFReadRGBAStrip in -ltiff... no
checking if TIFF package is complete... no -- some components failed test
```
Could it be caused by the fact that libtiff needs to link to `-lm` https://github.com/conan-io/conan-center-index/blob/master/recipes/libtiff/all/conanfile.py#L190 ?
Anyway, I cannot reproduce the error on https://github.com/eirikb/proof-of-conan/runs/4310846544?check_suite_focus=true

**Comment by Renari** [comment]
It's odd because the first CI and second CI run are inconsistent. The first run passed gcc10+libstdc++. The second run failed it.

**Comment by ericLemanissier** [comment]
no, gcc10 was properly built in both cases. The difference is that it was not tested in the 1st run, but it was tested in the 2nd run (and it's the test which failed)
https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/8164/1-configs/linux-gcc/imagemagick/7.0.11-14//summary.json
https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/8164/2-configs/linux-gcc/imagemagick/7.0.11-14//summary.json

**Pull request closed without merging**
