### PR TITLE
zoe: add version 3.6

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **zoe/3.6**

#### Motivation
- disable SHA1
- support macOS without patch

#### Details
https://github.com/winsoft666/zoe/compare/v3.3...v3.6

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]
Thanks!

**Review by AbrilRBS — CHANGES_REQUESTED** [review]
Checking a potential issue with curl requirement, sec

**Review by AbrilRBS — DISMISSED** [review]
False alarm, all looks good on my end, sorry for the scare :)

**Review by AbrilRBS — COMMENTED** [review]
Blocking yet again, sorry @toge! The release currently has 3.4 in the CMakeLists, see https://github.com/winsoft666/zoe/issues/36

**Comment by toge** [comment]
@AbrilRBS 
Thank you for your improvements!
I have not addressed this version difference until now as it is not relevant to packaging, but I will submit an update request to upstream in the future.

**Comment by AbrilRBS** [comment]
Yes, I see why this would be a non-issue. I think in this case the question would be wether a new release to fix this would happen soon/(a re-tag is also possible but less desired), or if 3.6/3.5.1 is still a ways off, we can then merge as-is

**Comment by toge** [comment]
@AbrilRBS 
I agree with you.

**Review by AbrilRBS — APPROVED** [review]
Thanks!

**Review by ErniGH — APPROVED** [review]
LGTM Thanks

**Pull request merged**
