### PR TITLE
[google-cloud-cpp]: add v2.19.0 version

### PR DESCRIPTION
**Pull request by coryan**
Specify library name and version:  **google-cloud-cpp/2.19.0**

Update `google-cloud-cpp` to the latest release. Remove 2.5.0 because that would make 4 minor releases in the 2.x series. Bump dependency versions (`nohmann_json`).  And some fixes in the tests for Conan v1.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
The Conan 2.x package for gprc is missing in Conan Center. I just started an internal build to generate that missing package.

**Comment by coryan** [comment]
> The Conan 2.x package for gprc is missing in Conan Center. I just started an internal build to generate that missing package.

Thanks.  Is there something I can monitor to see when I can try again?

**Comment by coryan** [comment]
Any news on the Conan 2.x package for gRPC?

**Comment by coryan** [comment]
Ping?

**Comment by coryan** [comment]
Sadly, it looks like the gRPC binary is still missing.

**Comment by RubenRBS** [comment]
Regenerating missing binaries now, thanks a lot for your patience

**Comment by coryan** [comment]
> Regenerating missing binaries now, thanks a lot for your patience

Thanks.  Can you let me know how the regeneration went?  I would like to restart the builds for this PR when that is ready.

**Review by RubenRBS — APPROVED** [review]

**Comment by coryan** [comment]
Anything I can do to help move this along?

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
