### PR TITLE
clipper: add 4.10.0 + fix http post for url generation of 4.8.8

### PR DESCRIPTION
**Pull request by SpaceIm**
HTTP POST was wrong in https://github.com/conan-io/conan-center-index/pull/9992

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
`Download Snapshot` element at https://sourceforge.net/p/polyclipping/code/HEAD/tree/tags/4.8.8/:

```html
<form class="tarball" action="/p/polyclipping/code/HEAD/tarball" method="post">
<input type="hidden" name="path" value="/tags/4.8.8" tabindex="6">
<button tabindex="7"><span class="icon" title="Download Snapshot"><i class="fa fa-download"></i>&nbsp;Download Snapshot</span></button>
<input name="_session_id" type="hidden" value="1ba447e0a952b5101cd83dfbedf7b3518b81064e4facf5492470ea421d098981f98a7ee1bc9be371" tabindex="8">
</form>
```

**Review by intelligide — DISMISSED** [review]

**Review by uilianries — DISMISSED** [review]

**Comment by SpaceIm** [comment]
sha256 has changed again...

**Comment by SpaceIm** [comment]
Let's add clipper/4.10.0, it has a regular tarball and is compatible with assimp (I've tested on macOS).

**Comment by SpaceIm** [comment]
> libnova uses the same trick and sha256 didn't change in months, even when link is generated again.

libnova source control is git, while clipper in source forge is svn, so maybe their auto zip generator doesn't generate reproducible archives for svn?

**Review by intelligide — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
