### PR TITLE
ffmpeg: fix target_os deduction for embedded platform

### PR DESCRIPTION
**Pull request by LevWi**
Specify library name and version:  **ffmpeg/4.4**

---

- [+] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [+] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [+] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@LevWi Thank you for your hotfix. Please, write a comment on the PR #4 so the CI bot can add you to the access request list. Otherwise, your PR will not run by the CI.

**Comment by LevWi** [comment]
Hello @uilianries 
Done: https://github.com/conan-io/conan-center-index/issues/4#issuecomment-1419093214
But nothing happen

**Comment by prince-chrismc** [comment]
You need to wait for the next PR to get merged with your name

**Review by MartinDelille — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by prince-chrismc** [comment]
The bot didn't rebuild this despite being approved

**Comment by prince-chrismc** [comment]
I opened an issue for the team to investigate :) I am pretty sure that it used to be automatic

**Review by SpaceIm — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
You'll need to re approve after a merge commit, save it for when there's merge conflicts 🙏

**Review by Croydon — APPROVED** [review]

**Pull request merged**
