### PR TITLE
libmysqlclient: fix hooks

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **libmysqlclient/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "auth_win_client_objlib.dir\Release\auth_win.ADD23B0F.tlog\auth_win_client_objlib.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\J\w\cci_PR-2771\2\5888ee66-9e83-48f9-aa37-8addcead0ed9\.conan\data\libmysqlclient\8.0.17\_\_\build\4f07e2a55a61c6bea81b783ce58c7dfbce6217e6\libmysql\authentication_win\auth_win_client_objlib.vcxproj]` :/

**Comment by jgsogo** [comment]
Hi! Yes, we moved the working directories, now all of them run inside the workspace (which is useful to ensure that we are cleaning everything after each job). 

Probably we don't need a full UUID for the tmp directories, this is something I'll fix in the next release. Nevertheless, I count characters and `C:\J\w\cci_PR-2771\2\5888ee66-9e83-48f9-aa37-8addcead0ed9\.conan\data\libmysqlclient\8.0.17\_\_\build\4f07e2a55a61c6bea81b783ce58c7dfbce6217e6\libmysql\authentication_win\auth_win_client_objlib.vcxproj` is only 201 characters long, I suppose MSBuild is adding `auth_win_client_objlib.dir\Release\auth_win.ADD23B0F.tlog\auth_win_client_objlib.lastbuildstate` to that dirname, and then you get 267 characters 😓 

Right now, the only way to fix it is by activating `short_paths` in the recipe (or waiting for the next release to CCI).

I'm really sorry for the inconvenience.

**Comment by danimtb** [comment]
We are looking into this issue in staging as well and will report back

**Comment by danimtb** [comment]
yes, this will be fixed in the next the deployment as it worked in out staging environment 👍

**Review by jgsogo — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
