### PR TITLE
google-cloud-cpp/all: disable werror

### PR DESCRIPTION
**Pull request by hoyhoy**
**google-cloud-cpp/all**

There are various problems with warning as errors.

I'm already ignoring....

```
 -Wno-dangling-reference -Wno-elaborated-type-specifier -Wno-deprecated-declarations -Wno-elaborated-type-specifier 
```

This is the latest issues...
```
internal/streaming_subscription_batch_source.cc:141:29: error: redundant move in initialization [-Werror=redundant-move]
  141 |     OnInitialError(std::move(rs));
```
---
- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by hoyhoy** [comment]
@uilianries I ended up having to fork the google-cloud-cpp v1.X recipe.  It's not conan2 compatible.  In fact, we had to fork nearly all of our recipes because nearly all of the conan center recipes have bugs, don't build on s/390, don't build on clang17 with warnings enabled, don't build on windows, and so on.  I was going to try to port some of this upstream, but it takes three to four weeks to get PRs reviewed on conan-center.

**Comment by hoyhoy** [comment]
@uilianries And I don't see why you'd want to have Werror on for a production build.  These C++ warnings are all over the place depending on what compiler and OS you happen to be using.  Basically, what you just told me is, "WORKS ON MY MACHINE!".  Ok, great, but did you test it s/390, windows, clang 17, gcc 13.2, gcc 8.5, AIX, and MSVC?  Because I have, and I can 100% assure Werror does not on all of those platforms.

**Comment by uilianries** [comment]
@hoyhoy Your PR can be genuine, but when I asked to open the issue is because your PR has no issue associated and was not clear enough about your error. It's true we can not test all users configurations in the CI, but it does not block from merging fixes, since it's well documented, including with a build log where we consult, not only a prove, in case needing to revisit it in the future.

There is a second problem regarding this recipe: It's not ported to Conan 2.x yet, and the CI requires it as a mandatory rule. We will need to open a separated PR to update his recipe. Anyway, we could merge it manually in case not passing.

Also, could you please check the account reserved to `Tony Perrie`, this used needs to sign the CLA too.

**Comment by SpaceIm** [comment]
An issue could be opened, but this fix looks quite trivial to me, and we all know that warnings as errors must not be enabled in conancenter recipes.

FYI, warnings as errors are disabled by default in google-cloud-cpp since https://github.com/googleapis/google-cloud-cpp/pull/10819 (2.8.0).

**Comment by SpaceIm** [comment]
conan v2 migration: https://github.com/conan-io/conan-center-index/pull/22591

**Comment by hoyhoy** [comment]
Yeah, it was easier just to fork the recipe.  I signed the SLA three times.  I think there was some issue with my corporate email being in my .gitconfig previously, but I thought I fixed it.

**Comment by memsharded** [comment]
> Yeah, it was easier just to fork the recipe. I signed the CLA three times. I think there was some issue with my corporate email being in my .gitconfig previously, but I thought I fixed it. Eventually I just gave up.

Ok, we were trying to force-merge this by hand, we can bypass the CI, but we cannot bypass the CLA. 
If you are not interested in this anymore, I think we can close the PR. If you would like the PR to be merged, please try to sign the CLA, and lets see if this time we succeed.

**Comment by hoyhoy** [comment]
V1 is EOL anyway.  We have a library still using it that we haven't upgraded.

**Comment by AbrilRBS** [comment]
Closing in favour of https://github.com/conan-io/conan-center-index/pull/22591 which already ahs done the Conan v2 support work

**Pull request closed without merging**
