### PR TITLE
opencv 4.x: honor dynamic runtime from conan profile when compiler is clang-cl

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/24056

`is_msvc()` and `is_msvc_static_runtime()` helpers don't understand clang-cl profiles (os=Windows, compiler=clang, compiler.runtime defined). They are too specific and not a proper mapping with the meaning of `MSVC` variable in CMake  (`MSVC` is TRUE in CMake for any cl like compiler).
In opencv, runtime is changed through a CMake option which must be passed by the recipe, so opencv recipe must pass compiler.runtime if it is defined, irrespective of compiler.

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by danimtb** [comment]
I was trying to compile opencv with and without the changes here with clang-cl on windows but the build keeps getting stuck at:

```
opencv/4.9.0: RUN: cmake --build "C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build" --config Release
MSBuild version 17.10.4+10fbfbf2e for .NET Framework

  Checking Build System
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/core/CMakeLists.txt
  opencv_core_AVX.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\core\opencv_core_AVX.dir\Release\opencv_core_AVX.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/core/CMakeLists.txt
  opencv_core_AVX2.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\core\opencv_core_AVX2.dir\Release\opencv_core_AVX2.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/core/CMakeLists.txt
  opencv_core_AVX512_SKX.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\core\opencv_core_AVX512_SKX.dir\Release\opencv_core_AVX512_SKX.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/core/CMakeLists.txt
  opencv_core_SSE4_1.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\core\opencv_core_SSE4_1.dir\Release\opencv_core_SSE4_1.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/core/CMakeLists.txt
  opencv_core_SSE4_2.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\core\opencv_core_SSE4_2.dir\Release\opencv_core_SSE4_2.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/CMakeLists.txt
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/CMakeLists.txt
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/imgproc/CMakeLists.txt
  opencv_imgproc_AVX.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_AVX.dir\Release\opencv_imgproc_AVX.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/imgproc/CMakeLists.txt
  opencv_imgproc_AVX2.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_AVX2.dir\Release\opencv_imgproc_AVX2.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/imgproc/CMakeLists.txt
  opencv_imgproc_AVX512_SKX.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_AVX512_SKX.dir\Release\opencv_imgproc_AVX512_SKX.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/imgproc/CMakeLists.txt
C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\src\modules\imgproc\src\imgwarp.sse4_1.cpp(135,46): warning : arithmetic between floating-point type 'const float' and enumeration type 'c v::InterpolationMasks' is deprecated [-Wdeprecated-enum-float-conversion] [C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_SSE4_1.vcxproj]
C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\src\modules\imgproc\src\imgwarp.sse4_1.cpp(136,46): warning : arithmetic between floating-point type 'const float' and enumeration type 'c v::InterpolationMasks' is deprecated [-Wdeprecated-enum-float-conversion] [C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_SSE4_1.vcxproj]
C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\src\modules\imgproc\src\imgwarp.sse4_1.cpp(168,50): warning : arithmetic between floating-point type 'const float' and enumeration type 'c v::InterpolationMasks' is deprecated [-Wdeprecated-enum-float-conversion] [C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_SSE4_1.vcxproj]
C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\src\modules\imgproc\src\imgwarp.sse4_1.cpp(169,54): warning : arithmetic between floating-point type 'const float' and enumeration type 'c v::InterpolationMasks' is deprecated [-Wdeprecated-enum-float-conversion] [C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_SSE4_1.vcxproj]
C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\src\modules\imgproc\src\imgwarp.sse4_1.cpp(483,36): warning : arithmetic between enumeration type 'cv::InterpolationMasks' and floating-po int type 'double' is deprecated [-Wdeprecated-enum-float-conversion] [C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_SSE4_1.vcxproj]
  opencv_imgproc_SSE4_1.vcxproj -> C:\Users\danielm\.conan2\p\b\openc8da7fbfc076e5\b\build\modules\imgproc\opencv_imgproc_SSE4_1.dir\Release\opencv_imgproc_SSE4_1.lib
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/videoio/CMakeLists.txt
  Processing OpenCL kernels (core)
  Building Custom Rule C:/Users/danielm/.conan2/p/b/openc8da7fbfc076e5/b/src/modules/core/CMakeLists.txt
```
Was this your experience @SpaceIm? Any clue what's happening here? Thank you!

**Comment by SpaceIm** [comment]
No idea, I've just fixed the most obvious issue reported by https://github.com/conan-io/conan-center-index/issues/24056 (runtime not honored if clang-cl), but not tested myself since I'm not on Windows currently. I don't know why it's stuck now (I guess when `opencv_core490.lib` is created?).

@Jimbopython Do you have a better luck?

**Comment by Jimbopython** [comment]
I will take a look next week if the changes fix my issue. I had the issue from @danimtb as well, when building with clang-cl 17.
Clang-cl 16 is working fine.

**Comment by Jimbopython** [comment]
I just checked it and the fix works with clang-cl 16.

Note that the hanging of clang-cl 17 is known and already fixed in a newer version:

https://github.com/llvm/llvm-project/issues/69428

**Comment by SpaceIm** [comment]
May I ask to conan folks maintaining conancenter to push for adding these helpers to conan API? I've opened https://github.com/conan-io/conan/issues/12336 long time ago, and I don't have the time to argue more.

**Review by danimtb — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
Thanks for double checking @Jimbopython :)

**Pull request merged**
