### PR TITLE
[gdk-pixbuf] link against older glib only when building debug version

### PR DESCRIPTION
**Pull request by hesham-essam**
Specify library name and version:  **gdk-pixbuf**

When building gdk-pixbuf with clang debug mode, it adds extra runtime checks which require linking against the "compiler-rt" clang library. See https://bugs.llvm.org/show_bug.cgi?id=16404
I'm not sure why this only happens with newer versions of glib, and why the extra sanitization flags are added since they are not on by default, but this seems like a reasonable patch to enable building in release mode with clang.

This should enable building gtk on linux with clang in release mode.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@hesham-essam please, provide a complete log with your error. Restricting a functional profile requires more information. Regards.

**Comment by hesham-essam** [comment]
gdk-pixbuf can't be built with clang debug mode as discussed here
https://github.com/conan-io/conan-center-index/pull/10154#issuecomment-1094224794

**Comment by planetmarshall** [comment]
> gdk-pixbuf can't be built with clang debug mode as discussed here [#10154 (comment)](https://github.com/conan-io/conan-center-index/pull/10154#issuecomment-1094224794)

gdk-pixbuf can be built by clang in debug mode by adding the following in the user's profile:

```
[env]
LDFLAGS=-rtlib=compiler-rt
```

If you restrict the compiler at the recipe level, it makes it impossible for the user to override that behaviour. Gtk cannot currently be built by clang on CCI because the dependency graph resolves glib to 2.73.0 and a binary for gdk-pixbuf with that dependency does not exist.

**Comment by hesham-essam** [comment]
I will turn this into a draft then until your PR is merged, then I will close this.

**Pull request closed without merging**
