### PR TITLE
fixed patch for tvos and watchos on openssl

### PR DESCRIPTION
**Pull request by paulo-coutinho**
Specify library name and version:  **openssl/1.1.1x**

fixes https://github.com/conan-io/conan-center-index/issues/5061

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@paulo-coutinho Could you paste your log building for WatchOS or TvOS? Indeed I don't have support for those platforms and CCI can't build too. It would be great having a log just to be sure and use as example for the future.

Just past conan create command output, including conan create command line. Regards!

**Comment by paulo-coutinho** [comment]
Está em anexo.
[openssl-watchos-log.txt](https://github.com/conan-io/conan-center-index/files/6223258/openssl-watchos-log.txt)

**Comment by uilianries** [comment]
Obrigado!

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by paulo-coutinho** [comment]
Please review it :(

**Review by SSE4 — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]
it's a bit unfortunate that the hunks order is modified, because it makes the review more complicated that it could be, but LGTM anyway

**Pull request merged**
