### PR TITLE
Bumping ixwebsocket to ixwebsocket/11.4.5

### PR DESCRIPTION
**Pull request by MattBelanger321**
Bumping to ixwebsocket/11.4.5

---

- [y] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [y] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [y] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MattBelanger321** [comment]
> I detected other pull requests that are modifying ixwebsocket/all recipe:
> - #22315
> 
> This message is automatically generated by https://github.com/ericLemanissier/conan-center-conflicting-prs so don't hesitate to report issues/improvements there.
> 

Mine is newer and passes more checks. I believe the checks I fail are due to permissions

**Review by MattBelanger321 — COMMENTED** [review]
👍

**Review by RubenRBS — DISMISSED** [review]
Hi! Thanks a lot for taking the time to keep the library updated, we appreciate it!

The PR is now queued in the CI systems, there's no further action required from your part, thanks!

**Comment by MattBelanger321** [comment]
> Hi! Thanks a lot for taking the time to keep the library updated, we appreciate it!
> 
> The PR is now queued in the CI systems, there's no further action required from your part, thanks!

No problem, do you think it will be ready sometime today? There was a bug in the older versions of the library that won't allow it to build with GCC 13

**Comment by MattBelanger321** [comment]
Could I have some help @RubenRBS? not sure what's going wrong.

**Comment by RubenRBS** [comment]
Hi, sorry for the delay. I'll push the fix directly to your branch in a second, thanks a lot for the ping and for taking the time to create the PR in the first place, really appreciated!

**Comment by MattBelanger321** [comment]
@RubenRBS yay it passed, how do I get it merged?

**Review by RubenRBS — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Pull request merged**
