### PR TITLE
config: drop openssl from v2 ready since it does not work for 3.x version

### PR DESCRIPTION
**Pull request by prince-chrismc**
Specify library name and version:  **lib/1.0**

to unblock https://github.com/conan-io/conan-center-index/pull/15336

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Actually https://github.com/conan-io/conan-center-index/pull/15336 changes both openssl 1.x.x & 3.x.x, and c3i should ensure that 1.x.x still work with conan v2

**Comment by jngrb** [comment]
OpenSSL 3.x.x is v2 ready in the sense that you can enable `CONAN_V2_MODE` on the cmake_find_package-based test package:

```
CONAN_V2_MODE=1 conan create . openssl/3.0.8@
````

builds successfully.

It is not v2 ready in the sense that you can consume OpenSSL 3.x.x with a CMakeDeps & CMakeToolchain-based recipe. That only works for OpenSSL 1.x.x for which a v2 test package using the new generators is already on the master branch.

The v2 test package with the new generators for OpenSSL 3.x.x and the fixed necessary to make it work will come with my PR #14426

I am not sure what the "c3i/conan-v2" CI tests for because I don't know the specifics and I cannot see results.

If it only runs the command above and does not make sure that the test package uses the CMakeDeps generator, this PR is not needed.

**Comment by SpaceIm** [comment]
openssl 3.x.x is not v2 ready because it just can't work with conan v2 client, and therefore it can't pass v2 pipeline, that's what this conan_v2_ready_references.yml is tracking, to ensure that once a recipe passes v2 pipeline, a new PR cannot break it.

**Comment by prince-chrismc** [comment]
> OpenSSL 3.x.x is v2 ready in the sense that you can enable CONAN_V2_MODE on the

The variable does not actually change anything and only softly reports warnings. For example bad imports and not reported, it's very incomplete 

The v2 pipeline runs the 2.0 client and does a `conan create`

**Comment by prince-chrismc** [comment]
I'd highly recommend taking a look at the logs posted by the bot if you want a detailed break down of all the different commands.

Conan 2.0 was released a few weeks ago and it's being used for CCI exclusively in its entirely for the v2 pipeline (aka there no v1 client)

**Review by jcar87 — APPROVED** [review]

**Review by davidsanfal — APPROVED** [review]

**Comment by SpaceIm** [comment]
By the way, is this file updated regularly?

Its content is a little bit odd:
- many duplicated entries
- several recipes marked as ready references but with missing v2 packages
- many missing recipes for which v2 pipeline passed in recent PRs

**Comment by prince-chrismc** [comment]
AutoMerge is not running over config PRs :/

**Comment by prince-chrismc** [comment]
@SpaceIm @jwillikers @toge Can you please review? The auto merge is bugged with team reviews 🙏

**Review by SpaceIm — APPROVED** [review]

**Pull request merged**
