### PR TITLE
llvm-core: additional 11x versions for the recipe

### PR DESCRIPTION
**Pull request by newlawrence**
Library versions added: **llvm-core/11.0.0**, **llvm-core/11.0.1**

Unmodified recipe. I just added two previous working versions of the package.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Is there a particular reason why you need these?

**Comment by newlawrence** [comment]
In my personal case, not at all. I just had them already done and wanted to share.

Is there any policy regarding which versions to contribute? I just followed the example given by libraries like **boost** or **openssl** where you can find each version since the first contributed package consistently.

**Comment by prince-chrismc** [comment]
> Is there any policy regarding which versions to contribute?

Looking over the docs I did not find it written down. (i'll open a PR shortly)

We tend to discourage adding _older_ versions, as I understand, they are almost never used and place an additional burden on the build system.

Technically speaking there's zero issues with your PR... boost has every very since we are quick at adding them but we never add older versions

**Comment by newlawrence** [comment]
Ok, I find the answer reasonable. Versions already published do not get removed as someone can be still depending on them and it is very unlikely for any previous version to be required by anybody (unless critical bugs or some kind of behavior that people relies on).

Should we close the **PR** then?

**Comment by newlawrence** [comment]
Well, let's keep moving forward @prince-chrismc. I'll close this **PR**, here we have [another one](https://github.com/conan-io/conan-center-index/pull/5720) with a newer version of the library 😁.

In case someone needs versions **11.0.0** or **11.0.1**, they can be found in my fork [here](https://github.com/newlawrence/conan-center-index/tree/llvm-core_11x).

Thank you for your time @prince-chrismc!

**Pull request closed without merging**
