### PR TITLE
arrow: add version 18.0.0

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **arrow/18.0.0**

#### Motivation
There are lots of improvements in 18.0.0.

#### Details
https://github.com/apache/arrow/compare/apache-arrow-17.0.0...apache-arrow-18.0.0

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by toge** [comment]
@robomics
This is new one.
Sorry for your inconvenience.

**Comment by robomics** [comment]
Thanks re-submitting the PR!

**Comment by toge** [comment]
CI failed with strange error.
Following url is valid at least now.
```
NotFoundException: Not found: https://www.apache.org/dyn/closer.lua/arrow/arrow-14.0.0/apache-arrow-14.0.0.tar.gz?action=download
```

**Review by danimtb — APPROVED** [review]

**Review by jcar87 — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Review by jcar87 — APPROVED** [review]
Thanks @toge  - 

have lightened up the versions - I will open a follow up PR for further cleanup, didn't want to delay the adding of the new version any longer

**Comment by doge-liang** [comment]
why you remove the 16.0.0 version?

**Comment by franramirez688** [comment]
> why you remove the 16.0.0 version?

@doge-liang It's not removed, but stopped publishing new revisions for that version.

We're trying to minimize the impact on our CI when a PR changes any recipe, as we have to rebuild all the existing versions in the conandata.yml to publish new revisions/packages for them. Given that fact, when any recipe in CCI no longer uses a specific version, we tend to remove it from the conandata.yml. This does not mean that we're removing the existing binaries or revisions for that version for sure.

As you can see, you can still find all the packages built for the latest revision published for arrow/16.0.0:

```bash
conan list "arrow/16.0.0:*" -r conancenter -f compact
Connecting to remote 'conancenter' anonymously
conancenter
  arrow/16.0.0
    arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec%1730205008.903 (2024-10-29 12:30:08 UTC)
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:95e2d0f355047dbb84c4fad21a32952081a6127a
        settings: Linux, x86_64, Release, gcc, 17, libstdc++11, 11
        options(diff): fPIC=True, shared=False
        requires: boost/1.85.Z, bzip2/1.0.Z, libbacktrace/cci, libevent/2.1.Z, openssl/3.3.Z, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:539b6ff51d3dba2461c8a73529b6555a89b2b26c
        settings: Windows, x86_64, Release, msvc, 17, dynamic, Release, 193
        options(diff): shared=True
        requires: boost/1.85.Z, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:5ef121e5077e99580a4b8452538dd8683e83ebc3
        settings: Macos, armv8, Release, apple-clang, 17, libc++, 13
        options(diff): fPIC=True, shared=False
        requires: boost/1.85.Z, bzip2/1.0.Z, libbacktrace/cci, libevent/2.1.Z, libiconv/1.17.Z, openssl/3.3.Z, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:ec729b845c953bca4b0e8224aaa720ec7b25b9ce
        settings: Windows, x86_64, Release, msvc, 17, dynamic, Release, 193
        options(diff): shared=False
        requires: boost/1.85.Z, bzip2/1.0.Z, libevent/2.1.Z, openssl/3.3.Z, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:a483dc2338626e390f5effe15cb6307a02778728
        settings: Macos, armv8, Release, apple-clang, 17, libc++, 13
        options(diff): shared=True
        requires: boost/1.85.Z, libbacktrace/cci, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:646268f63f7f53e2a08cc7ab2ba12b52be786e2c
        settings: Windows, x86_64, Release, msvc, 17, dynamic, Release, 192
        options(diff): shared=False
        requires: boost/1.85.Z, bzip2/1.0.Z, libevent/2.1.Z, openssl/3.3.Z, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:816823736c77deca890c4b10c2fea89b50920b1c
        settings: Macos, x86_64, Release, apple-clang, 17, libc++, 13
        options(diff): shared=True
        requires: boost/1.85.Z, libbacktrace/cci, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:90593eadd9ea8c8954e773e63ae911da205b47b8
        settings: Linux, x86_64, Release, gcc, 17, libstdc++11, 11
        options(diff): shared=True
        requires: boost/1.85.Z, libbacktrace/cci, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:b954c806c05d95d32760963f6cfebc1c2f59922a
        settings: Windows, x86_64, Release, msvc, 17, dynamic, Release, 192
        options(diff): shared=True
        requires: boost/1.85.Z, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
      arrow/16.0.0#8c4d6627e1918a248c655dceaf297bec:76369098accfe7266fd258a5933171fa2cc6814a
        settings: Macos, x86_64, Release, apple-clang, 17, libc++, 13
        options(diff): fPIC=True, shared=False
        requires: boost/1.85.Z, bzip2/1.0.Z, libbacktrace/cci, libevent/2.1.Z, libiconv/1.17.Z, openssl/3.3.Z, thrift/0.20.Z, xsimd/13.0.0#3e7543dc526b0f612fe291e0f198c9dc:da39a3ee5e6b4b0d3255bfef95601890afd80709, zlib/1.3.Z
```

**Pull request merged**
