### PR TITLE
mpfr: update to mpfr/4.1.0

### LINKED ISSUE #2386: [request] mpfr/4.1.0
### Package Details
  * Package Name/Version: **mpfr/4.1.0**
  * Changelog: **https://www.mpfr.org/mpfr-current/#changes**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

### PR DESCRIPTION
**Pull request by madebr**
closes #2386 

Specify library name and version:  **mpfr/4.1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
```
CMake Error at CMakeLists.txt:274 (add_library):
  Cannot find source file:

    src/cmp_abs.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:274 (add_library):
  No SOURCES given to target: mpfr
```

Need to update the cmake

**Comment by SSE4** [comment]
@madebr conflicts

**Comment by madebr** [comment]
@sse4 What conflicts? The last ci run was successful?

**Comment by SSE4** [comment]
```
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
recipes/mpfr/all/conanfile.py
```

**Comment by madebr** [comment]
@SSE4 Ok, resolved them.
The mobile view of github didn't show these conflicts.

**Review by uilianries — DISMISSED** [review]

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
