### PR TITLE
Bump google-cloud-cpp's zlib requirement to [>=1.2.11 <2] range

### PR DESCRIPTION
**Pull request by RubenRBS**

### CODE REVIEW

**Comment by RubenRBS** [comment]
Weird, seems like the graph conflict detection I used to generate this PR is faulty, seems like grpc should be moved to ranges first! I wonder why the script marked this as ready then

**Comment by RubenRBS** [comment]
Oh my 🤦 
The last change I made was missing a negation - This level seems to have been recipes that did not have zlib as a direct dependency in the graph! No wonder this showed up before glib then :)

**Comment by RubenRBS** [comment]
After re-running with proper logic, seems like grpc can now be opened - will re-trigger this one after https://github.com/conan-io/conan-center-index/pull/20223 is merged

**Review by czoido — APPROVED** [review]

**Comment by coryan** [comment]
You may want to consider using #20721 instead.  There are other requirements (beyond `zlib`) that need bumps, and new patches are needed to compile the code [^1].  I expect that PR will build cleanly in this round, should be just a few more hours.


[^1]: I am guessing because the toolchain(s) and/or the base OS changed.

**Comment by coryan** [comment]
> I expect that PR will build cleanly in this round, should be just a few more hours.

"a few" turned out to be about 13 hours. But it is now passing.

**Comment by RubenRBS** [comment]
Closing in favour of https://github.com/conan-io/conan-center-index/pull/20721, thanks @coryan!

**Pull request closed without merging**
