### PR TITLE
cairo: bump deps

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **cairo/1.0**

Generated and committed by [Conan Center Bump Deps](https://github.com/ericLemanissier/conan-center-index-bump-deps)
Find more updatable recipes in the [GitHub Pages](https://ericlemanissier.github.io/conan-center-index-bump-deps/)

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@uilianries unfortunately it does not seem to fix the problem. Also, none of the requirements of cairo use full_package_mode.

**Comment by ericLemanissier** [comment]
@uilianries it's the third time in a row that pixman's binaries are regenerated, but somehow we end up with no new binaries promoted. This is not a simple transient flakiness problem :/

**Comment by uilianries** [comment]
@ericLemanissier I see errors again to upload, there is something wrong with that package 😞 I gonna open a new PR to bump it, just in case.

**Comment by ericLemanissier** [comment]
let's gooo ! thanks @uilianries

**Review by uilianries — APPROVED** [review]
LGTM!

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
