### PR TITLE
Bump spirv-tools to 2021.2

### PR DESCRIPTION
**Pull request by espositofulvio**
Specify library name and version:  **spirv-tools/2021.2**

This pull request updates spirv-tools to 2021.2

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by espositofulvio** [comment]
@prince-chrismc I'm not sure what's happening but two old versions are failing to build even though my changes just add a new version. Could someone check what's the specific error?

**Comment by prince-chrismc** [comment]
When you change a recipe all the versions are rebuilt to ensure things are in sync.

Given everything passed in the logs it might be a random issue in the backend... the CCI infra team might comment on what...

For now... 
You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁

**Comment by jgsogo** [comment]
There are some errors that we label as _random_. They happen from time to time. Probably they are not random, but we don't have time to investigate (and implement) all of them, usually, there are other priorities 😞 

In this case, the two builds have failed with this error:

```
org.jenkinsci.plugins.workflow.cps.CpsCompilationErrorsException: startup failed:
General error during conversion: java.util.ConcurrentModificationException

java.util.ConcurrentModificationException
```

I know sometimes it can be annoying, we might eventually try to fix this specific error, but there will always be something unexpected. Triggering the build again is usually the (easiest) way to go.

**Comment by espositofulvio** [comment]
Hi @jgsogo, thanks for your reply, I've just started using Conan and don't know in depth all the CI build process, but thanks for all your effort, I do think Conan is really wonderful piece of software and I hope to contribute more 😊. I restarted the build as both you and Chris suggested.
Thanks again!

**Comment by prince-chrismc** [comment]
Do not continue restarting there might be something wrong

**Comment by espositofulvio** [comment]
I thought it was only a matters of the right time. I'll hold off then

**Comment by prince-chrismc** [comment]
It's still building so we might actually be lucky!

**Review by SSE4 — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Review by AndreyMlashkin — APPROVED** [review]

**Comment by AndreyMlashkin** [comment]
@uilianries, please review.
Many other recipes are depending on this one

**Comment by prince-chrismc** [comment]
@AndreyMlashkin Please be patient! there's lot of PR's that need attention ❤️ We'll get there soon!

**Comment by espositofulvio** [comment]
@prince-chrismc I'm still learning a bit about the review process, so my question is: am I allowed to review and approve pull requests from other contributors?

**Comment by prince-chrismc** [comment]
@espositofulvio Yes! it's not counted towards merging PRs but it's by far the best way to get noticed and earn a spot as a community reviewer like myself (highly recommended) 😉

**Comment by espositofulvio** [comment]
> @espositofulvio Yes! it's not counted towards merging PRs but it's by far the best way to get noticed and earn a spot as a community reviewer like myself (highly recommended) 😉

Great thanks! I'm re-entering the c++ world after a few years and a project like conan eased my transition back a lot (I'm used to web languages with package managers now) and found that following this repo allows me to get on top of some of the best libraries for C++!

**Pull request merged**
