### PR TITLE
ImageMagick: Add 7.1.0-29 and build it with cmake on all platforms.

### PR DESCRIPTION
**Pull request by Cyriuz**
This fixes the previously broken Windows build and adds a bunch of new possible dependencies.

Specify library name and version:  **imagemagick/7.1.0-29**

I was a bit sad when I realized that the current ImageMagick package in conan-center did not support Windows and after looking around a bit for solutions I found some previous discussions about its build scripts being very complicated for Windows and some attempts at contributing a CMake build script instead ([here](https://github.com/ImageMagick/ImageMagick/issues/743) and [here](https://github.com/ImageMagick/ImageMagick/issues/4536)). So I continued the work on the CMake scripts to make it work with the latest release and on windows/linux/mac. The patch provided in this PR is based on my fork [here](https://github.com/Cyriuz/ImageMagick).

The maintainers of ImageMagick have stated an interest in a CMake build script but would like some more people to test and use it before adapting it as stated [here](https://github.com/ImageMagick/ImageMagick/issues/4536#issuecomment-1025052810). So I thought this would be a good way to get it used even if it is not merged to ImageMagick itself yet, as the CMake build script simplifies the build by miles.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Cyriuz** [comment]
Sorry for being slow on this, how do you usually handle missing prebuilts?

**Comment by uilianries** [comment]
@Cyriuz I gonna check will cairo is missing and try to regenerate it. THanks for reporting.

**Comment by Cyriuz** [comment]
@uilianries Did you get a chance to look into this? I could disable these deps by default I guess but maybe that is the wrong way to handle it :)

**Comment by jgsogo** [comment]
Hi! Here the issue (at least one of them) with `cairo` is related to `glib`:
 * `cairo` requires `glib/2.73.3`
 * ...but this requirement is overridden by `pango`:
 
    ```
    WARN: cairo/1.17.4: requirement glib/2.73.3 overridden by pango/1.50.7 to glib/2.73.0
    ```
    
 * and `cairo` recipe, on it side, has decided to depend on every single bit from `glib`:
 
    ```
    self.info.requires["glib"].full_package_mode()
    ```
    
    As a consequence, the different patch version, results in different package-id for `cairo`.

We just need to upgrade `glib` in `pango` to `glib/2.73.3` so the version is not overridden

**Comment by uilianries** [comment]
@jgsogo thank you very much!!

**Comment by Cyriuz** [comment]
Sorry for being so slow with this and thanks for pointing out the issue. I wanted to try to bump pango but got hit by the linter now, I had hoped I wouldn't need to change the 7.0 recipe since it doesn't build on my Windows dev env but maybe its unavoidable? Not sure if it is worth fixing this PR since we now have #12371? This one makes the recipe super easy but it depends on my cmake patch which I had hoped would be adopted by imagemagick, but that might be wishful thinking since I have had so little time to spend on this lately.

**Pull request closed without merging**
