### PR TITLE
Downgrade tesseract recipe minimum gcc to >=7

### LINKED ISSUE #9678: [package] Tesseract/5.0.0: GCC Requirement too restrictive
I am working to compile the tesseract library into binaries for deployment on various Linux distros (with Ubuntu 18.04+ as my primary target right now).

The tesseract package (versions >=5.0.0) uses too restrictive of a GCC version (9+) to support C++17, when GCC 7 supports the C++17 standard (see references below). I have tried many different combinations of docker images/compilers and cannot produce a binary that "just works" on Ubuntu 18.04 due to GLIBC/CXX issues.

For reference: 
 * [GCC C++17 standard support](https://gcc.gnu.org/projects/cxx-status.html)
 * [Clang C++ Standard support](https://clang.llvm.org/cxx_status.html) - seems full support is around clang ~7
 * [Visual Studio C++ Standard Support](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170)

I've tried a combination of different solutions to target Ubuntu 18.04 (with glibc 2.27):
* Conanio/gcc9 - glibc (2.30)
* Conanio/gcc8 - glibc (2.27) - fails to meet tesseract conanfile min gcc >=9 criteria, likely would work to meet needs
* Conanio/gcc7 - glibc (2.26) - fails to meet tesseract conanfile  min gcc >= 9 criteria, likely would work to meed needs
* Conanio/clang7 - glibc (2.28), glibc too new and won't be compatible with target glibc
* Using various centos images with upgrading the gcc to version 9.0 (GLIBC compatibility issues gone, but GLIBCXX compatibility issues)

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **tesseract/5.0.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 9**
  * Docker image: **conanio/gcc9**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

Not using a custom profile

### Steps to reproduce (Include if Applicable)

1. Use docker to build lightweight project that uses tesseract in `conanio/gcc9`, builds against GLIBC 2.30
2. `docker cp` the binaries to an `ubuntu:18.04` image, uses GLIBC 
3. Run `ldd /path/to/binary` to confirm GLIBC/GLIBCXX compatiblity issues

### Logs (Include/Attach if Applicable)
<details><summary>ldd result on Ubuntu 18.04 for binary built with conanio/gcc9</summary>

```
# ldd libocr.so
./libocr.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./libocr.so)
./libocr.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./libocr.so)
	linux-vdso.so.1 (0x00007fffb9d83000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8c536f6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8c5336d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8c5314e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8c52db0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8c529bf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8c54de5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8c527a7000)
```

</details>

### PR DESCRIPTION
**Pull request by brandonmkunkel**
Specify library name and version:  **tesseract/5.0 + tesseract/5.1**

[Submitting this PR to address issue I created.](https://github.com/conan-io/conan-center-index/issues/9678)

closes #9678

---

- [ X ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ X ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ X ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ X ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@brandonmkunkel Thank you for your contribution, please, sign our CLA and ask for member inclusion on #4 please. Otherwise, the CI will not start.

**Comment by brandonmkunkel** [comment]
Hi I requested access on #4 and am currently waiting!

**Comment by uilianries** [comment]
> Hi I requested access on #4 and am currently waiting!

Thank you! Your request should be approved on Monday. 

https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#request-access

**Review by uilianries — APPROVED** [review]

**Comment by brandonmkunkel** [comment]
@uilianries Thanks for the help with resolving this issue/PR . What's the estimated time for a package update to be reflected in the registry after a merge?

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
> @uilianries Thanks for the help with resolving this issue/PR . What's the estimated time for a package update to be reflected in the registry after a merge?

hard to say, it just need to get enough approvals as described in https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md
for simple PRs it usually takes a couple of days, for complex it may take significantly longer
keep in mind, reviewers are located in different parts of the world, live in different time zones, have different public holidays and usually review in their spare time
check this out: https://github.com/prince-chrismc/conan-center-index-pending-review/issues/1
it contains some infographics which show how much does it take in average to get PR merged

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
super easy pr with easy description === super fast review === quick merge!

Should be too long before you can use it 🚀

**Pull request merged**
