### PR TITLE
- [pango] bump glib to 2.70.1

### PR DESCRIPTION
**Pull request by SSE4**
for #7691

Specify library name and version:  **pango/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
something is weird with compiler.runtime:
```
[5/48] Compiling C object pango/pango-1.0-0.dll.p/pango-coverage.c.obj
cl : Command line warning D9025 : overriding '/MT' with '/MD'
cl : Command line warning D9025 : overriding '/MD' with '/MT'
```

**Comment by SSE4** [comment]
`cairo.lib` (with `compiler.runtime=MT`) contains `DEFAULTLIB:MSVCRT` which is weird as well.

**Review by ericLemanissier — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by ericLemanissier** [comment]
It's probably time to stop building all the 1.48.* except 1.48.9 right?

**Comment by SSE4** [comment]
> It's probably time to stop building all the 1.48.* except 1.48.9 right?

yes, fair enough

**Review by ericLemanissier — DISMISSED** [review]

**Comment by ericLemanissier** [comment]
@SSE4 please consider https://github.com/SSE4/conan-center-index/pull/11

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
