### PR TITLE
(#23474) simdjson/3.9.1: remove unnecessary constraints

### PR DESCRIPTION
**Pull request by Jie-Cheng**
The existing recipe aborts building when gcc9 and libstdc++11 are used. But I tried manually building from source, simdjson works fine in this situation. And simdjson documentation says gcc9 and above should work too. 

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Jie-Cheng** [comment]
@RubenRBS could you take a look at this PR please?

**Comment by Jie-Cheng** [comment]
@RubenRBS please take a look

**Comment by RubenRBS** [comment]
Hi @Jie-Cheng - Sorry that this took so long to get addressed. As you can read from the message that the bot posted, for this PR to me mergeable, we need you to comment on [this issue](https://github.com/conan-io/conan-center-index/issues/4) first :) I'll make sure to fast forward this PR once thats done!

**Review by RubenRBS — COMMENTED** [review]
Hi @Jie-Cheng thanks a lot! Could you please provide successful compilation logs for the configuration you mention does work after removing these constrains? Thanks!

**Review by RubenRBS — COMMENTED** [review]
Hi @Jie-Cheng thanks a lot! Could you please provide successful compilation logs for the configuration you mention does work after removing these constrains? Thanks!

**Comment by Jie-Cheng** [comment]
> Hi @Jie-Cheng thanks a lot! Could you please provide successful compilation logs for the configuration you mention does work after removing these constrains? It helps inmensely for future maitenance and traceability :) Thanks!

Hi @RubenRBS , how can I build the package using my updated recipe? I am in a docker env with gcc=9

**Comment by RubenRBS** [comment]
> Hi @RubenRBS , how can I build the package using my updated recipe? I am in a docker env with gcc=9

Hi @Jie-Cheng. Once you get your branch inside your docker container (either cloning it or sharing the volume works), you can navigate to the folder containing your `conanfile.py` and after running `conan profile detect`, run `conan create . --version=3.9.1 -b=missing -s="build_type=Debug"`. The `-s="build_type=Debug"` bit will ensure you test with recipe in one of the now allowed modes. You'll also want to then re-create it changing that bit to `-s="compiler.libcxx=libstdc++11` to check the other change.

Feel free to ping me once you have these logs, thanks!

**Comment by Jie-Cheng** [comment]
Hi @RubenRBS  thanks for the help. Please check out the attached logs, where I built in debug and release modes respectively (both with libstdc++11). 

[debug.log](https://github.com/user-attachments/files/15756847/debug.log)
[release.log](https://github.com/user-attachments/files/15756858/release.log)

**Review by jcar87 — APPROVED** [review]
Thanks @Jie-Cheng !

**Pull request merged**
