### PR TITLE
[spdlog] bump deps version

### PR DESCRIPTION
**Pull request by prince-chrismc**
to trigger CCI bot based on #3365

Specify library name and version:  **spdlog/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
By the way, the check in `build()` doesn't seem to be consistent with the logic in `requirements()`

**Comment by prince-chrismc** [comment]
So I can compare...

```py
        if Version(self.version) < "1.7" and Version(self.deps_cpp_info["fmt"].version) >= 7:
            raise ConanInvalidConfiguration("The project {}/{} requires fmt < 7.x".format(self.name, self.version))
```

Yes it's missing one of the API gaps that prevents compiling.... What did you see as the problem?

**Review by Croydon — DISMISSED** [review]

**Comment by prince-chrismc** [comment]
Not sure what the failure was ...

logs show
>[2020-11-04 16:13:54.877] [console] [info] End of example.

but run test_package failed 😖

**Comment by jgsogo** [comment]
I can see this error in the CI logs:

```
ERROR: spdlog/1.8.0 (test package): Error in test() method, line 18
	self.run(bin_path, run_environment=True)
	ConanException: Error 3221225477 while executing bin\test_package
```

It looks like an (undefined?) return code from the test_package?

**Comment by jgsogo** [comment]
I would say it is related to this fix: https://github.com/conan-io/conan/pull/7799, previous builds (Sep 30th) were using Conan 1.29.

**Comment by jgsogo** [comment]
Same error 🤔 

```
ERROR: spdlog/1.8.0 (test package): Error in test() method, line 18
	self.run(bin_path, run_environment=True)
	ConanException: Error 3221225477 while executing bin\test_package
```

Let's see if any Windows user can reproduce it locally and debug the return value and what Conan is doing with it cc/ @danimtb  🥺

**Comment by prince-chrismc** [comment]
> Let's see if any Windows user can reproduce it locally and debug the return value

My `PATH` got broken and I can not detect Visual Studio. I'll check into this on the weekend

**Comment by prince-chrismc** [comment]
Tried re-running a dozen times, can not repro

`conan create all 1.8.0@ -o spdlog:shared=True`
[log.txt](https://github.com/conan-io/conan-center-index/files/5503848/log.txt)

**Comment by jgsogo** [comment]
We need to debug Conan itself using this PR, something weird in this recipe. Please, any @conan-io/barbarians with a Windows at hand can do it? Thanks!

**Comment by memsharded** [comment]
Trying locally got: 
image

**Comment by prince-chrismc** [comment]
Thank you @memsharded I must have not been configuring myself locally to reproduce!

**Review by jgsogo — APPROVED** [review]
Thanks, @prince-chrismc !

**Review by danimtb — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
