### PR TITLE
Boost leaf

### PR DESCRIPTION
**Pull request by kammce**
Resolves https://github.com/boostorg/leaf/issues/47

Specify library name and version: boost-leaf/1.81.0

I work with and have consent by the author to put Boost.LEAF on the Conan Center Index. This library is a dependency of my library libhal.

Boost.LEAF is a Level 0 module, no dependencies on any other Boost library.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by zajo** [comment]
There was a bit of confusion with the previous PR, about possible interference with the Boost library release procedure, which is currently in progress. To clarify, Boost LEAF is a Level 0 module in Boost (see the [Boost Dependency Report](https://pdimov.github.io/boostdep-report/master/module-levels.html)), which means that it has no dependencies, and therefore can be released as a stand-alone library (this PR), as well as included in official Boost releases.

**Comment by SSE4** [comment]
> There was a bit of confusion with the previous PR, about possible interference with the Boost library release procedure, which is currently in progress. To clarify, Boost LEAF is a Level 0 module in Boost (see the [Boost Dependency Report](https://pdimov.github.io/boostdep-report/master/module-levels.html)), which means that it has no dependencies, and therefore can be released as a stand-alone library (this PR), as well as included in official Boost releases.

there are libraries that are distributed both as a part of boost and independently on their own. one example is `asio` (standalone) and `boost::asio`. I don't see any reason why other boost modules (e.g. `leaf` or `hana`) can't use the same approach. but that's probably outside of conan-center-index scope, it's something to be decided by project mantainers.

**Comment by ericLemanissier** [comment]
I'd say it's okay if the namespace is different, so that there cannot be odr violations

**Review by uilianries — CHANGES_REQUESTED** [review]
Splitting Boost modules is not a good idea for maintenance. Boost Leaf is available in Boost since 1.75.0, please, use the official Boost package.

**Comment by zajo** [comment]
Including LEAF in Conan would allow painless distribution for users who do not want to, or are not allowed to, depend on the Boost distro.

**Comment by kammce** [comment]
> Including LEAF in Conan would allow painless distribution for users who do not want to, or are not allowed to, depend on the Boost distro.

+1 to this

**Pull request closed without merging**
