### PR TITLE
opentdf-client release 1.5.3 & 1.5.4

### PR DESCRIPTION
**Pull request by patmantru**
Specify library name and version:  **opentdf-client/1.5.3** **opentdf-client/1.5.4**

Updates to makefiles to remove need for patches from CCI.
Performance improvements.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by toge — APPROVED** [review]

**Comment by patmantru** [comment]
@toge what is this waiting on?  It's a version bump that should be an automatic approval.

**Comment by patmantru** [comment]
I did a 'merge to current main' and now it looks like openssl and libxml2 prebuilt packages are missing.  This has nothing to do with my submission from what I can tell, and I don't have authority to rerun the job.  Help!!

**Comment by toge** [comment]
@patmantru 
Yes, you are right.
My review is not important.
If you don't modify any more, it will be merged automatically.

There are same issue on lots of PRs.
Let's wait for solve.

**Comment by RubenRBS** [comment]
CI is now generating the missing binaries, thanks for the ping :)

**Comment by patmantru** [comment]
@RubenRBS so someone will rerun this CI and it will automatically get merged after the binaries are available?  3 days seems like a long time to get a version bump PR processed.  :(

**Comment by RubenRBS** [comment]
Yes, no worries, I'll keep an eye on the PR

We understand the frustration with bumps taking longer than expected: In the last 24h, we've gotten almost 50 PRs bumping them, and our servers are having some trouble dealing with the associated load - slowing everything down. We're working on ways to mitigate the impact on contributors with high PR loads, but it's still early in development, so we thank you for your patience meanwhile :)

**Review by RubenRBS — DISMISSED** [review]

**Comment by patmantru** [comment]
@RubenRBS I'm back from vacation and...seriously disappointed that this version bump PR has not been merged.  What can we do to get this resolved?

**Comment by czoido** [comment]
> @RubenRBS I'm back from vacation and...seriously disappointed that this version bump PR has not been merged. What can we do to get this resolved?

Hi @patmantru,
We have been experiencing some problems with the system in this past month, so some PR's have been affected by this, sorry. We also had this PR for the package: https://github.com/conan-io/conan-center-index/pull/20423 can you please check if you want to make some comments about that? If we need changes there we can incorporate the changes from this PR so we can save some time and merge soon.

**Comment by patmantru** [comment]
>We also had this PR for the package: #20423 can you please check if you want to make some comments about that? If we >need changes there we can incorporate the changes from this PR so we can save some time and merge soon.

That looks to me like a cleanup PR to remove older versions.  I'm OK with that, but it's not immediately necessary.  I'd prefer that we get this version bump PR merged first, and then we can discuss other PRs trying to update this recipe.  I have no idea who the developer is for #20423 , and while I appreciate their interest in contributing, I'm more interested in getting my PR merged.

**Comment by czoido** [comment]
> > We also had this PR for the package: #20423 can you please check if you want to make some comments about that? If we >need changes there we can incorporate the changes from this PR so we can save some time and merge soon.
> 
> That looks to me like a cleanup PR to remove older versions. I'm OK with that, but it's not immediately necessary. I'd prefer that we get this version bump PR merged first, and then we can discuss other PRs trying to update this recipe. I have no idea who the developer is for #20423 , and while I appreciate their interest in contributing, I'm more interested in getting my PR merged.

Ok, we need the changes in the other PR because of the zlib ranges, that we had to add to the recipes to minimize conflicts. It's already green so as soon as that gets merged we will merge this one after relaunching. The process should be fast. Thanks a lot for your patience.

**Review by czoido — APPROVED** [review]

**Comment by patmantru** [comment]
I've updated this PR to add 1.5.4 also.  As long as it's taken 3 weeks to get a simple version bump PR through, I might as well start getting that release going.

It's super frustrating that this is delayed by zlib because we do not use zlib in our code, and we're not allowed to disable zlib usage by the packages that we do directly use, but in order to get this recipe to build, we have to override zlib so there is not a version conflict.  It adds a dependency in this recipe that has zero business being there in the first place.

I patiently await the approval and merge of this PR, and appreciate your help.

@czoido @RubenRBS

**Review by RubenRBS — APPROVED** [review]

**Comment by RubenRBS** [comment]
> I patiently await the approval and merge of this PR, and appreciate your help.

We appreciate your kind words, a thank you for your patience, we know that it can getting PRs in limbo can be frustrating after employing time and effort to create the patches - We're working on internal processes to help alleviate some of these concerns and to improve our response time to follow up on PRs

We're now waiting for the code the get built, should get automatically merged afterwards

> It's super frustrating that this is delayed by zlib because we do not use zlib in our code

Could you please explain this further/create an issue about it? How come? I see zlib being used in https://github.com/search?q=repo%3Aopentdf%2Fclient-cpp%20zlib&type=code and the original zlib requirement comes from your original PR introducing this library

**Comment by patmantru** [comment]
@RubenRBS see:
https://github.com/conan-io/conan-center-index/pull/12002#issuecomment-1202851022
https://github.com/conan-io/conan-center-index/pull/9396#discussion_r815682915

**Comment by patmantru** [comment]
Thanks for your assistance! @RubenRBS @czoido

**Pull request merged**
