### PR TITLE
icu: fix cross build with Visual Studio

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/14205

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
I see. Let's remove this skip_86_,64

**Comment by SpaceIm** [comment]
and now?

**Comment by stefan-floeren** [comment]
It now builds. The results seem to work as well.

The only difference to the old behavior is that it builds twice, once for the build platform and once for the host platform. I guess for the binary tools?

**Review by jwillikers — APPROVED** [review]
Awesome!

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
