### PR TITLE
[thrift] remove dead options

### LINKED ISSUE #5022: [package] thrift/0.13.0: recipe has dead options
### Package and Environment Details
  * Package Name/Version: **thrift/0.13.0**

The thrift recipe has some options and sets some variables that don't map to any cmake variables used by thrift, like:
* `with_boost_functional`
* `with_boost_smart_ptr`
* `with_boost_static`
* `with_boostthreads`
* `with_stdthreads`
* `with_plugin`
* `BUILD_EXAMPLES`

It looks like most of them were just removed without replacement some time before the thrift 0.13.0 release, 
so these shouldn't have caused any problems.

One exception is `with_boost_static` which should be remapped to the cmake `Boost_USE_STATIC_LIBS` variable.

### PR DESCRIPTION
**Pull request by srnwk**
Specify library name and version:  **thrift/0.13.0**

Fixes #5022

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — DISMISSED** [review]
I usually disagree removing options, but those options are useless, I don't think any user will be break.

```
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_ROOT
    BUILD_EXAMPLES
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
    FPIC
    LIBEVENT_ROOT
    OPENSSL_ROOT_DIR
    SHARED
    USE_BOOST_THREAD
    USE_STD_THREAD
    WITH_BOOSTTHREADS
    WITH_BOOST_FUNCTIONAL
    WITH_BOOST_SMART_PTR
    WITH_BOOST_STATIC
    WITH_PLUGIN
    WITH_QT
    WITH_STDTHREADS


-- Build files have been written to: /home/conan/.conan/data/thrift/0.13.0/_/_/build/42dc464f6779489959984cabc224ce074bfc0cae/build_subfolder

```

**Comment by SpaceIm** [comment]
Here is the original PR by @ericLemanissier https://github.com/conan-io/conan-center-index/pull/1700, maybe there are discussions about these options (didn't check in detail).

**Comment by SpaceIm** [comment]
Looking a little bit a source code, does boost ever reguired oustide of tests?

**Comment by srnwk** [comment]
> Looking a little bit at source code, it seems to require only boost header only. Others components are for tests.

Ah, even better.

Would this PR be a good chance to sneak in some updates for the deps, like openssl/1.1.1j, boost/1.75.0?

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
related: #5020

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
