### PR TITLE
add librttopo/1.1.0

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

I've decided to write a custom CMakeLists (in the first commit, you can see an iteration without CMake, but msvc build was still broken, and quite tedious to fix it). This project doesn't seem to be maintained anymore, so I think it's harmless.

It's a dependency of `libspatialite`.

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by madebr** [comment]
Did you try the autotools build system?

**Comment by SpaceIm** [comment]
In the first commit, it works (and it takes ages with MinGW windows as usual), but nmake build is more or less broken and tedious to fix.

**Comment by SpaceIm** [comment]
Is it worth the effort? Shared would be broken, and it would just take 50 times longer to build than CMake on Windows.

**Review by madebr — APPROVED** [review]
I feel your pain.
Cmake makes life much easier.

**Pull request merged**
