### PR TITLE
bison/all: Bump required m4 version

### PR DESCRIPTION
**Pull request by TheClonerx**
Specify library name and version:  **bison/all**

- [ ] Depends on #7626

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
super weird, it passes locally for me...

**Comment by ericLemanissier** [comment]
https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/7624/3-configs/macos-clang/bison/3.7.6//summary.json the last CI is reusing an existing binary. Maybe the recipe needs to be touched in order to restart a full build ?

**Comment by ericLemanissier** [comment]
few weeks ago, [he did not have an idea](https://github.com/conan-io/conan-center-index/pull/7263#issuecomment-918639475)
The same error happens in Github Actions context (thanks @eirikb !) https://github.com/eirikb/proof-of-conan/runs/3859002345?check_suite_focus=true#step:8:156 and https://github.com/eirikb/proof-of-conan/runs/3859002291?check_suite_focus=true#step:8:156

**Comment by ericLemanissier** [comment]
I'm fine with this plan. Maybe we can continue on https://github.com/conan-io/conan-center-index/pull/7633 ?

**Pull request closed without merging**
