### PR TITLE
libxml2: Add version 2.13.4, fixes a few CVE issues

### PR DESCRIPTION
**Pull request by gsantner**
### Summary
Changes to recipe:  **libxml2**

#### Motivation
Stay up to date with somewhat recent releases of upstream, fix CVE issues. Update to latest patch version.

See also: <https://gitlab.gnome.org/GNOME/libxml2/-/releases>

#### Details
Version bump

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by uilianries** [comment]
@gsantner Thank you for your PR. Checking the previous build log on Windows:

https://c3i.jfrog.io/c3i/misc-v2/logs/pr/25322/1-windows-msvc/libxml2/2.13.4//6211ea34ed7b04dcc66f5ff3bdfd60394f228be5-build.txt

It failed because `mem-debug` is no longer available.

Could you please revert your latest commit and getting back 2.13 instead. Then, update the recipe with the follow change:

```python
def config_options(self):
    ...
    if Version(self.version) >= "2.13.0":
        self.options.rm_safe("mem-debug")
```

Regards!

**Comment by gsantner** [comment]
@uilianries 
Thanks for your reply! I added your suggestion, squashed and force pushed the branch. So only updated 2.13 one is in the commit list now.

**Comment by gsantner** [comment]
It failed again. Missing pdb files but copy statment?

**Comment by gsantner** [comment]
It failed again. pdb files not created but tried to copy?

**Comment by uilianries** [comment]
> It failed again. pdb files not created but tried to copy?

@gsantner It seems like it's missing some symbols. I'll take a look by Monday. Thank you again!

**Comment by gsantner** [comment]
Thanks for help!

**Comment by AbrilRBS** [comment]
@uilianries @gsantner the issue was a missing bcrypt dependency in the new version, see https://gitlab.gnome.org/GNOME/libxml2/-/blob/2.13/win32/Makefile.msvc?ref_type=heads#L84

**Review by AbrilRBS — DISMISSED** [review]
Checked https://gitlab.gnome.org/GNOME/libxml2/-/compare/2.12...2.13?from_project_id=1665&page=2&straight=false, seems like we're not missing anything else, thanks!

**Comment by gsantner** [comment]
Thats unfortunate from upstream, yet another dependency to take care off

**Comment by uilianries** [comment]
@AbrilRBS Thank you so much!!

**Review by uilianries — APPROVED** [review]
LGTM. Nice addition pointing the origin of bcrypt as dependency.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by AbrilRBS — APPROVED** [review]

**Comment by gsantner** [comment]
Hello @AbrilRBS ,
just wanted to make use of the new version. Unfortunatley libxslt fails to build now (which depends on libxml2).

Is this reproducable on msvc on CI too?

**Comment by AbrilRBS** [comment]
@gsantner I'll take a look now, thanks for the ping

**Comment by gsantner** [comment]
@AbrilRBS 
Windows, MSVC 139 toolset, VS2022

**Comment by AbrilRBS** [comment]
Thanks @gsantner, I've proposed https://github.com/conan-io/conan-center-index/pull/25404 to fix the issue. Old versions of libxslt were using deprecated functions that were removed in libxml2 1.13. I've now fixed its version ranges and added a new version of libxslt that supports the newer versions, feel free to use it once it gets merged :)

**Comment by gsantner** [comment]
Thanks for fixing it! 😄

**Pull request merged**
