### PR TITLE
libavif: Add version 1.0.1

### PR DESCRIPTION
**Pull request by Nerixyz**
Specify library name and version:  **libavif/1.0.1**

Adds `libavif` 1.0.1. The same patch as before is needed, but otherwise nothing changed.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by czoido** [comment]
Thanks a lot for the contribution @Nerixyz 
You should have access now, I have relaunched the PR.

**Comment by Nerixyz** [comment]
I can't see the logs of `continuous-integration/jenkins/pr-merge`, so I don't really know what went wrong.

**Comment by czoido** [comment]
> I can't see the logs of `continuous-integration/jenkins/pr-merge`, so I don't really know what went wrong.

Don't worry about that, the bot should post the logs when the build finishes. Let's wait a bit, I can see that it's still building.

**Comment by Nerixyz** [comment]
It seemed to have built on all platforms. Do I need to update the branch or something?

**Comment by czoido** [comment]
> It seemed to have built on all platforms. Do I need to update the branch or something?

@Nerixyz we have been under maintenance for some days, sorry for the inconvenience, let me relaunch the PR.

**Review by czoido — APPROVED** [review]

**Pull request merged**
