### PR TITLE
Add LEAF to Conan Center

### PR DESCRIPTION
**Pull request by kammce**
Specify library name and version: leaf/1.81.0

I work with and have consent by the author to put LEAF on the Conan Center Index. This library is a dependency of my library libhal.

Original github library can be found here: https://github.com/zajo/leaf

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
AFAIK, conan-center maintainers have decided to not modularize boost libraries. I'm not sure that packaging a fork of a boost library to bypass this decision is a good idea.

**Comment by prince-chrismc** [comment]
Nor do we add forks which dont add much value to the original project especially when it for an actively maintained project. This is a tough sell

**Comment by prince-chrismc** [comment]
@kammce Can you please explain why this project should be included in ConanCenter?

**Comment by zajo** [comment]
This is not "modularizing Boost libraries". This is making a library which is not coupled with Boost (does not depend on Boost, does not include Boost headers, does not use Boost Config) available in Conan.

**Comment by prince-chrismc** [comment]
If that's the case why was it added to Boost? 🤔 I am trying to find a good argument to change out policy

- it's already available under https://github.com/conan-io/conan-center-index/blob/3dd67b75f4baf48d6fb66f38ee21d1f67a173787/recipes/boost-leaf/all/conanfile.py#L12 albeit with a deprecation warning.
- Also its not listed in https://github.com/conan-io/conan-center-index/tree/3dd67b75f4baf48d6fb66f38ee21d1f67a173787/recipes/boost/all/dependencies for any version

I understand the "make it more widely available so it can be adopted" but I am not sure how a third copy on ConanCenter will help any further.

I'd love to understand your motivation better

**Comment by zajo** [comment]
LEAF is an error handling library. For such libraries any coupling is a problem, so it has zero dependencies: a stand-alone library available as a single header. At the same time, LEAF has passed Boost review and it is part of the Boost distro.

In general I agree that it is not a good idea to distribute Boost libraries separately, but that's because they're coupled with (usually many) other Boost components. For example, managing compatibility between a Boost library and another Boost library it depends on would be a nightmare. Boost has a rigorous release process in order to ensure that everything works together.

Yet, this reasoning does not apply to LEAF.

It would serve the users if LEAF is available in Conan as a separate component as well. It is unpleasant to install Boost only to use something as lightweight as LEAF.

**Comment by prince-chrismc** [comment]
You should be able to `conan install boost-leaf/1.81.0@`  today so I am not sure adding another copy is the best approach. 

I'll put in on the discussion list for this week

**Comment by kammce** [comment]
@prince-chrismc this is the latest PR https://github.com/conan-io/conan-center-index/pull/14660 that effected the boost-leaf package. It was deprecated by the Conan team. We are more than fine with removing the `boost-leaf` package from the index. But we want a version of the LEAF error handling library in the conan center index. It is a error handling library that just so happens to also be apart of the Boost Org but can exist completely on its own. I want to make that (LEAF) package have its own spot in the index. The justification for its own spot in the index is that its a small dependency relative to all of Boost.

But as I thought more about this I realized that there is a critical flaw with having a module of Boost outside of Boost. I bet your team has already figured this out. If you have a package A that depends on Boost-LEAF and package B that depends on Boost and an application C that depends on both package A and B and the versions of Boost-LEAF and the version of LEAF within Boost are different, then we will get ODR violations at best and UB at worst.

But keeping LEAF on their own is still really beneficial. So I ask, if its possible to have Boost-LEAF package to be a dependency such that, if its ever used in a `conanfile.txt` dependency list, if Boost is also there, Boost-LEAF should disappear.

**Comment by SpaceIm** [comment]
I'm not an expert of boost internal dependencies, but here is a proposal for conan-center maintainers:

- allow to package boost libraries which don't have dependencies with a recipe name `boost-<lib>`
- in boost recipes, list these libs in `provides` to avoid duplicated libs in dependency graph of consumers
- in conan-center recipes, prevent to depend on these boost libs, only boost should be added to requirements. Consumers are free to depend on these specific boost libs if they want.

**Comment by zajo** [comment]
It would certainly be nice if we can work out some general rule for this situation (a stand-alone library that is part of the Boost distro); there is at least one super useful such library, mp11, but there are a couple others.

That said, these cases are very few and it would probably be fine if each is handled as an exception.

**Comment by jcar87** [comment]
Hi @kammce, @zajo - thanks so much for considering Conan Center and submitting Leaf for inclusion.

If this is a standalone version that has no cross-dependency on Boost (i.e. includes are not in `boost/`, C++ namespace is not `boost::`, and boost is not referenced) I don't see any issues. What we are trying to avoid is standalone boost libraries that can have dependencies between them, and avoid users/consumers running the risk of including both (boost + the standalone). We need to keep in mind that Boost is one of the most common C++ dependencies, so it's not unusual for users to require it, even if they don't directly. 

If we are in this situation, it would be roughly similar to ASIo and boost.asio being different things.

I can still see in the test_package that there are references to macros with the `BOOST_` prefix - so I was wondering whether this is yet fully standalone. 

> It is unpleasant to install Boost only to use something as lightweight as LEAF.
I don't disagree - however bear in mind that if boost.leaf itself is a header-only library, I would imagine that a user that specifies the `boost:header_only=True` option should be able to get the package close to trivially. It would be different if it was a compiled library, of course.

**Comment by zajo** [comment]
Luis, thank you for the thoughtful reply.

First, let me clarify that what we want to distribute in Conan isn't just header-only, it is a single header with no dependencies.

I understand your concern about naming and clashes, but let's also consider that in some cases LEAF is used on embedded systems, and it isn't appropriate to make such projects drag the whole of Boost with them, _especially given that the library itself has been carefully engineered to make that unnecessary_.

Now, can I delete the boost namespace and change all the macro prefixes, yes I could, but this would be a nightmare to maintain, not to mention confusing for the users. Imagine reading the documentation on the [configuration macros](https://www.boost.org/doc/libs/release/libs/leaf/doc/html/index.html#configuration), having to understand that you don't use the `BOOST_` prefix if you took the library from Conan.

I am not super familiar with Conan, is one of the options below possible?

* To somehow mark the two packages as incompatible, and not allow both to be installed.
* To somehow mark the two packages as version-dependent (they are guaranteed to be 100% compatible if they're using the same version of the library, after all, we're talking about a single header in the Conan package).

If not, I still think it makes sense to allow the the standalone package just because the alternative is such a burden on some users.

**Comment by kammce** [comment]
@zajo  I don't know conan well enough to make the cross check work. So I'll need some guidance from the Conan team if we were to make this work.

**Comment by kammce** [comment]
This change is currently stale. Do we have any decisions on this? Just to give a point of reference, because this isn't a stand alone library, I currently directly include this header only library in my application. I would use conan, but paying the cost of having to build all of boost is a cost for developer time and CI time that I'd like to not pay. I'm on conan2 and I'm having trouble using the header_only option. It says its deprecated. Would you be able to guide me to now to use this conan2 so I can test it out. Sorry I wasn't able to test this before.

**Comment by prince-chrismc** [comment]
We currently do not allow forks which are not adding anything significant to the original project which is very well maintained. This also includes files which could erroneously collide with the full boost package https://github.com/zajo/leaf/tree/master/include/boost so to avoid any issue there would need to be a package without it.

There's a `boost-leaf` standalone that was already publishing the original so you should use that one :)

***

This issues is covered by https://github.com/conan-io/conan-center-index/pull/15190#issuecomment-1376377626 

I am going to mark it as closed but would happily reconsider this addition if there was better seperation :)

**Comment by kammce** [comment]
The standalone version still shows this:

image

May I remove the deprecation notice/error on the package so the package can be used?

**Comment by prince-chrismc** [comment]
I should not have been given an error. Thanks fot sharing, I opened the PR so it's more official.

The other related recipes were not 🤷

**Pull request closed without merging**
