### PR TITLE
aws-c-common: add AWS_COMMON_USE_IMPORT_EXPORT interface definition if shared

### PR DESCRIPTION
**Pull request by SpaceIm**
see https://github.com/awslabs/aws-c-common/blob/v0.8.17/include/aws/common/exports.h

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by cardinotGV** [comment]
This is breaking most of the other aws-* as they look for `aws-c-common::aws-c-common-lib`

(msvc)
image

**Comment by prince-chrismc** [comment]
Please refer to the "consuming recipes" docs for how to enable revisions and store your own copies of recipes
https://github.com/conan-io/conan-center-index/blob/master/docs/consuming_recipes.md

In ConanCenter we can only do one at a time :) so it will take a while for the rest of the AWS family to get updated

**Comment by SpaceIm** [comment]
Yes sorry for that. Maybe it could have been done in 2 steps to avoid breakage but it would have been super tedious (keep component and not define AWS for cmake_find_package & cmake_find_package_multi in each aws recipe, and do not depend anymore on component explicitly, then few weeks later remove component in each recipe).

**Comment by cardinotGV** [comment]
No problem, thanks @SpaceIm and @prince-chrismc. I'm sticking to the previous revisions while it's in progress

**Pull request merged**
