### PR TITLE
quill: add version 4.4.0, remove older versions

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **quill/4.4.0**

https://github.com/odygrd/quill/compare/v4.3.0...v4.4.0

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by perseoGI — APPROVED** [review]
Thanks for the clean up Toge! ❤️

**Review by RubenRBS — COMMENTED** [review]
Hi @toge thanks a lot!
Going by the diff, seems like newer versions of the library support building as shared. is this something you tried? Or should we move this to a different PR? Would be totally fair not to do that extra work now, you have done more than plenty enough already! :)

**Comment by toge** [comment]
@RubenRBS 
I think it is an example to make quill a shared lib.
It seems not to be a part of library.

**Comment by RubenRBS** [comment]
> I think it is an example to make quill a shared lib. 

But theh that configuration would be supported if I'm not misunderstanding something right?

Either way, that can way for a follow up PR where we add support for it if we end up wanting it, thanks a lot for adding the new version in the first place :)

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
