### PR TITLE
add cmake 3.18.4

### PR DESCRIPTION
**Pull request by a4z**
Specify library name and version:  **cmake/3.18.4**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
Well, I was going to add 3.18.4 in my other PR too. I just didn't push the commit yet, because CI will fail anyway until #3109 is merged 💁🏼

**Review by uilianries — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Comment by jgsogo** [comment]
Once more, Jenkins is failing to update the status 😠 ....so merging manually (good old times).

**Comment by a4z** [comment]
The details link brings me to forbidden places, so I don't know, does this mean I have something to update for the PR?

**Comment by jgsogo** [comment]
> The details link brings me to forbidden places, so I don't know, does this mean I have something to update for the PR?

No, I will merge it manually.

**Comment by a4z** [comment]
Thanks a lot Javier!

**Pull request merged**
