### PR TITLE
Add data for expat 2.3.0

### PR DESCRIPTION
**Pull request by datalogics-robb**
Specify library name and version:  **expat/2.3.0**

Patch support is now needed to work around expat-2.3 explicitly rejecting VS 2015 and earlier.

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Actually, I suggested to close/open the original PR, not opening a new one :smile:

**Comment by datalogics-robb** [comment]
@SpaceIm I'm not sure what happened, but after I closed it, I was unable to open it again :)

**Review by SpaceIm — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Comment by Croydon** [comment]
Why did you overwrite the unsupported compiler check? Doesn't this break stuff? Upstream probably hasn't added it for no reason?

**Comment by datalogics-robb** [comment]
@Croydon I didn't see any specific reason this would not work - the documentation upstream simply stated that they didn't want to support Visual Studio compilers more than 5 years old.

**Comment by SpaceIm** [comment]
@Croydon see https://github.com/libexpat/libexpat/issues/454

**Comment by Croydon** [comment]
Okay, so the patch can probably be dropped in the future https://github.com/libexpat/libexpat/pull/455

**Pull request merged**
