### PR TITLE
scip: add version 9.1.1

### PR DESCRIPTION
**Pull request by hedtke**
### Summary
Changes to recipe:  **scip/9.1.1**

#### Motivation
SCIP released version 9.1.1

#### Details
For symmetry computation, SCIP switched from bliss as default to snauty.
Until version 9.0.1 this recipe had a flag to use bliss or not. All deployed versions always used bliss.
My proposal is to drop the flag and always use the default: until version 9.0.1 bliss, from 9.1.0 on snauty

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by hedtke** [comment]
I am not sure why the CI fails here. Package dependencies haven't been touched.

**Comment by perseoGI** [comment]
Hi @hedtke, it is a missing binaries issue, I'm regenerating binaries now...

**Comment by AbrilRBS** [comment]
Hi @hedtke thanks a lot for your patience. I'm okey with these changes, I just have a follo-up question to understand a bit more, in:

> My proposal is to drop the flag and always use the default: until version 9.0.1 bliss, from 9.1.0 on snauty

Do you then see no value for the recipe to provide the alternative? What's your insight on that?

**Comment by hedtke** [comment]
@AbrilRBS I don't know whether anybody every used the recipe with the non-default options. Yes, this would be a recipe feature that would be missing. I am not able to judge on the impact. My team and I always use this recipe with default options.

> Do you then see no value for the recipe to provide the alternative? What's your insight on that?

**Comment by hedtke** [comment]
I updated to the bugfix release 9.1.1

**Review by AbrilRBS — COMMENTED** [review]
i'll be looking into the flag defaults with @perseoGI tomorrow, thanks a lot for your patience

**Comment by hedtke** [comment]
v9.2.0 was released, maybe we skip v9.1.1

**Comment by AbrilRBS** [comment]
@hedtke sounds good to me, please ping me once this is done

I've yet still to come to a conclusion regarding the `bliss` handling with @uilianries, but we can probably discuss it tomorrow

**Comment by hedtke** [comment]
I opened a new MR for v9.2.0 which also handles bliss. I think we can close this MR and skip a version of SCIP

**Pull request closed without merging**
