### PR TITLE
faac: modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
- remove useless CMakeLists file
- no need for patch to bootstrap script, just call autoreconf
- relocatable shared lib on macOS: see https://github.com/conan-io/hooks/issues/376
- add msys2 to build requirements if building on windows
- cache configuration with lru_cache

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Few comments:
- this lib seems to depend on a bundled `kissfft`
- msvc is supported upstream, but it's not properly handled by the recipe, so the invalid configuration message is misleading.

**Review by jgsogo — APPROVED** [review]

**Review by dvirtz — COMMENTED** [review]
mingw build fails with this unless https://github.com/SpaceIm/conan-center-index/pull/12 is applied

**Comment by SpaceIm** [comment]
Because of out of source build? I can revert this part instead of patching Makefile.

**Comment by dvirtz** [comment]
yes, because of out of source. It's backporting a patch from upstream. Seems harmless to me.

**Comment by SpaceIm** [comment]
Indeed, I've tested locally on Windows with MinGW. It fails without this patch.

**Comment by SpaceIm** [comment]
1.28 needs a slightly different patch

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
