### PR TITLE
amqp-cpp: add package_type + bump openssl

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@uilianries Do you know why `[service] Alert Community / comment (pull_request_target)` is always red even after close/open?

**Comment by uilianries** [comment]
> @uilianries Do you know why `[service] Alert Community / comment (pull_request_target)` is always red even after close/open?

The GH api command failed, but no clue about. Locally, it works for me:

```
gh api /repos/conan-io/conan-center-index/pulls/17078/files 
[
  {
    "sha": "11f86452648a6bac614b56e7a74df05ccdb3f43f",
    "filename": "recipes/amqp-cpp/all/conanfile.py",
    "status": "modified",
    "additions": 2,
    "deletions": 2,
    "changes": 4,
    "blob_url": "https://github.com/conan-io/conan-center-index/blob/4d9f67a21fc6f8474026bf81dda7549bf2758ef5/recipes%2Famqp-cpp%2Fall%2Fconanfile.py",
    "raw_url": "https://github.com/conan-io/conan-center-index/raw/4d9f67a21fc6f8474026bf81dda7549bf2758ef5/recipes%2Famqp-cpp%2Fall%2Fconanfile.py",
    "contents_url": "https://api.github.com/repos/conan-io/conan-center-index/contents/recipes%2Famqp-cpp%2Fall%2Fconanfile.py?ref=4d9f67a21fc6f8474026bf81dda7549bf2758ef5",
    "patch": "@@ -14,7 +14,7 @@ class AmqpcppConan(ConanFile):\n     topics = (\"amqp\", \"network\", \"queue\")\n     license = \"Apache-2.0\"\n     description = \"C++ library for asynchronous non-blocking communication with RabbitMQ\"\n-\n+    package_type = \"library\"\n     settings = \"os\", \"arch\", \"compiler\", \"build_type\"\n     options = {\n         \"shared\": [True, False],\n@@ -44,7 +44,7 @@ def layout(self):\n \n     def requirements(self):\n         if self.options.get_safe(\"linux_tcp_module\"):\n-            self.requires(\"openssl/1.1.1s\")\n+            self.requires(\"openssl/3.1.0\")\n \n     def source(self):\n         get(self, **self.conan_data[\"sources\"][self.version], strip_root=True)"
  }
]
```

Plus, the command error code is zero. Would need to debug, my guess is too many requests and GH is returning error.

**Comment by ericLemanissier** [comment]
yes, because this workflow is intentionally run only when pull requests are originally opened, cf https://github.com/conan-io/conan-center-index/actions/runs/4730776617/workflow?pr=17078#L5
This avoids tagging users each-time a PR is closed/reopenned just to trigger CI. The easy way out is to create another PR

**Comment by SpaceIm** [comment]
It may not be a blocker, but as a reviewer I usually don't even look at PR with red status, so I suspect that other reviewers do the same.

**Review by ericLemanissier — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
