### PR TITLE
Add Thrift 0.9.3

### PR DESCRIPTION
**Pull request by jheaff1**
This commit adds package Thrift 0.9.3 to CCI.

The previous test_package Calculator application was dependent on code generated
using the Thrift 0.13.0 compiler. As such, the Calculator application cannot support
Thrift 0.13.0 and 0.9.3. Therefore, the recipes for 0.9.3 and 0.13.0 are in individual folders.

This could likely be resolved so that the Thrift recipe was dependent on a Conan package containing
the Thrift compiler and the test_package conanfile.py generated the C++ code using the correct Thrift
compiler version

Specify library name and version:  **thrift/0.9.3**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
> The previous test_package Calculator application was dependent on code generated
using the Thrift 0.13.0 compiler.

You can create different test_package, according its version. For instance, you can build one cpp file or other, according thrift version. As example: https://github.com/conan-io/conan-center-index/blob/01d116654449cb4c2975775d39aeaa67e3311a1b/recipes/openssl/1.x.x/test_package/conanfile.py#L15

**Comment by jheaff1** [comment]
Thank you for that information. On reflection, I think I will try to generate the Calculator cpp code using the thrift compiler which is built using the package recipe.

For some reason I thought it wasn’t included in the recipe, like how protobuf and protoc are separate

**Comment by uilianries** [comment]
> For some reason I thought it wasn’t included in the recipe, like how protobuf and protoc are separate

They are no longer separated! The separation create many problems, now they are included at same recipe.

**Comment by jheaff1** [comment]
I just discovered this myself about 30 seconds ago :)

Thanks

**Comment by uilianries** [comment]
@jheaff1 no problem, just to understand. Keeping protoc and protobuf separated, was a nightmare to maintain, we needed  to create specific patch for each new version, as both project are in the same cmake files. But now with [context](https://docs.conan.io/en/latest/devtools/build_requires.html#build-and-host-contexts) we can use the same package with different profile when building, that was our earlier limitation.

**Comment by jheaff1** [comment]
@uilianries  I have now rewritten the PR to use the thrift compiler to generate the test source code (if not cross compiling). I took inspiration from the protobuf test_package

**Comment by uilianries** [comment]
Please, use a small example for test_package, Calculator is huge! The idea is validating the package generator, so it can be simple, like 100 lines is more than enough.

**Comment by jheaff1** [comment]
The Calculator.cpp file is autogenerated by Thrift. This is true on master of CCI: https://github.com/conan-io/conan-center-index/blob/master/recipes/thrift/all/test_package/Calculator.cpp

The actual test application is test_package.cpp

**Pull request closed without merging**
