### PR TITLE
wasmtime-cpp: update wasmtime/12.0.1

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **wasmtime-cpp/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — COMMENTED** [review]
Question

**Comment by toge** [comment]
@RubenRBS 
Thank you for your review.
Please add question detail.

**Comment by RubenRBS** [comment]
Welp that's funny @toge I didn't actually send any question hahaha - no idea what my question was about, so I'm approving this one, sorry about the confussion :P

**Review by RubenRBS — APPROVED** [review]

**Comment by RubenRBS** [comment]
Oh I guess my question was about where the compatibility table for wasmtime is - up until your change, the rest of the entries seem to go 1 to 1 with their respective major versions, so I¡m wondering what changed

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
