### PR TITLE
Add cppzmq 4.8.0

### PR DESCRIPTION
**Pull request by PatSche**
Specify library name and version: cppzmq/4.8.0

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericriff** [comment]
Is there a reason to add an older version?

**Review by intelligide — APPROVED** [review]

**Comment by PatSche** [comment]
> Is there a reason to add an older version?

This is a good question. Well, since version `4.8.1` is already released and included in this repository, as a package consumer I would prefer this new version.

I honestly don`t know if it`s common practice to keep the recipe repository as complete as possible - i.e. also make all versions accessible.

**Comment by ericLemanissier** [comment]
see https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-is-the-policy-for-adding-older-versions-of-a-package

**Comment by SSE4** [comment]
> 
> I honestly don't know if it's common practice to keep the recipe repository as complete as possible - i.e. also make all versions accessible, including version `4.8.0`.


I don't think it's needed to add `4.8.0` if `4.8.1` is already available.
they should be fully API and ABI compatible (as it's a minor version).
unless 4.8.1 has some breaking changes that prevents upgrade for you, I think 4.8.0 is an unnecessary addition to the ConanCenter.

**Comment by PatSche** [comment]
Okay, learned something again. I did not know the policy yet. I will close the PR with it.

**Pull request closed without merging**
