### PR TITLE
GTest - Flag packages built with different cxx langauge support as incompatible

### PR DESCRIPTION
**Pull request by Twon**
Specify library name and version:  **gtest/1.14.0**

GTest packages built with a C++14 compiler result in linkage errors when used in a C++17 program and attempting to use C++17 features such as `std::sting_view`.  I have built a reproduction of this issue here: https://github.com/Twon/ConanGTestIssueWithCxx17/pull/1

Note this mirrors the fix applied to Catch2 to ensure packages were compatible with C++17 caused the same underlying cause.  This change applies the same solution to GTest: https://github.com/conan-io/conan-center-index/pull/21792

Fixes: #23854

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by CJCombrink — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
Thanks for taking the time to implement the fix, we appreciate it :)

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@hhowe29 I just talked to @RubenRBS now and we will revert the minimum Conan client required. 

As result, older Conan version will not break, just will not use the feature, because is an attribute.

**Comment by uilianries** [comment]
@hhowe29 I just opened the PR https://github.com/conan-io/conan-center-index/pull/23909

**Comment by hhowe29** [comment]
> It's specially recommended for companies and users that are using ConanCenterIndex in production to keep a lockfile or your own server, to avoid any unexpected behavior from CCI recipes/packages.

Thanks for the advice. Obviously we are not using a lock file. Will look into getting one added.

**Comment by jcar87** [comment]
> @Twon, [This change](https://github.com/conan-io/conan-center-index/pull/23856/files#diff-30c143c486109e8ef87666fdfc05fe43889e15121afa1addd541aa409c91ee95R10) broke our build because we are still on conan 2.0.x.
> 
> ```
> ERROR: Package 'gtest/1.14.0' not resolved: gtest/1.14.0: Cannot load recipe.
> Error loading conanfile at '/root/.conan2/p/gtestc561d3ff51c0d/e/conanfile.py':
> Current Conan version (2.0.13) does not satisfy the defined one (>=1.53.0 <2 || >=2.1.0)..
> ```
> 
> Is forcing 2.1.x necessary? Seems odd that 1.64 is allowed, but a version 2.0 release from a few months ago is forcibly rejected. I get that 2.1 is the first version the implements `extension_properties`, but it seems like 2.0 users who had green CI builds would prefer to keep those builds green instead of being compelled to upgrade conan without warning.

While it happens to be the case that we could keep the recipe compatible with older versions as unknown attributes are ignored - it has always been the longstanding practice in Conan Center recipes to assume that the client can be updated to the latest. Significant efforts go into making sure Conan is backwards compatible and we don't introduce behaviour changes. We are relaxing the version constraint for this recipe, however - if the mindset is "users who had green CI builds would prefer to keep them green", it does make me wonder why users would pull the latest recipe revision in the first place - lockfiles are recommended here, in the same way that they are for pip (python) and cargo (Rust), for exactly the same reasons.

**Pull request merged**
