### PR TITLE
openjdk: Remove x86_64 architecture restriction

### PR DESCRIPTION
**Pull request by MartinDelille**
I tried removing this restriction on my Mac M1 and it worked so I wonder if we can delete it.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jcar87 — CHANGES_REQUESTED** [review]
Hi @MartinDelille  - thanks so much for opening this PR!

The openjdk recipe is currently re-packaging existing binaries: https://github.com/conan-io/conan-center-index/blob/5b99d22c09251c50e38740967bc2c584a6836010/recipes/openjdk/all/conandata.yml#L10

Removing that restriction "works" if Rosetta is installed on Apple Silicon mac, which I believe is the reason it works for you. However,  with the changes in this PR we would now be generating a package with `os=Macos`, `arch=armv8` settings, but with x86_64 binaries. Bear in mind that while Rosetta is very likely to be installed, we have already seen issues where users don't have it installed, and our policy is that if a user requests binaries for the armv8 architecture, that they contain native binaries. 

However, it seems that more recent versions of OpenJDK do provide native Apple Silicon binaries: (from [here](https://jdk.java.net/19/))
https://download.java.net/java/GA/jdk19.0.2/fdb695a9d9064ad6b064dc6df578380c/7/GPL/openjdk-19.0.2_macos-aarch64_bin.tar.gz

perhaps the recipe can be amended to cover this case? The conandata.yml would need to get an entry for ARM macs, and there should be some logic in the following lines to take the architecture into consideration as well:
https://github.com/conan-io/conan-center-index/blob/5b99d22c09251c50e38740967bc2c584a6836010/recipes/openjdk/all/conanfile.py#L28-L29

I think the rest can stay the same

**Comment by MartinDelille** [comment]
Ok I will do that! Can I ask you where did you find the download link ?

**Comment by jcar87** [comment]
> Ok I will do that! Can I ask you where did you find the download link ?

Oops sorry! Found it on this page: https://jdk.java.net/19/

**Comment by MartinDelille** [comment]
Any idea what is going wrong here ?

**Comment by jcar87** [comment]
> Any idea what is going wrong here ?

Hi @MartinDelille - thanks for taking the time to update the recipe with the proposed changes! 
I've just pushed some changes that should hopefully fix the test package - hopefully it passes CI on all platforms and we can merge this.

**Comment by MartinDelille** [comment]
For information it runs without issue on my side:

```
Configuration (profile_host):
[settings]
arch=armv8
arch_build=armv8
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=14.0
os=Macos
os.version=11.0
os_build=Macos
```

**Comment by jcar87** [comment]
Thanks @MartinDelille  - This also works for me locally, so we need to investigate on our end I'm afraid.

**Comment by MartinDelille** [comment]
@jcar87 Any news?

**Review by SSE4 — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
