### PR TITLE
zxing-cpp: fix two issues with the recent inclusion of 2.0

### PR DESCRIPTION
**Pull request by axxel**
Specify library name and version:  **zxing-cpp/2.0**

@prince-chrismc requested this PR

I'm the maintainer of the zxing-cpp project. I'm not a conan users and have no infrastructure to test those changes.

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — DISMISSED** [review]

**Comment by prince-chrismc** [comment]
Make sure to comment int #4

**Comment by axxel** [comment]
> Make sure to comment int #4

I did and my name has been added (#15375). Trying to look at the [details](https://ci-conan-prod.jfrog.team/job/prod/job/cci/job/PR-15357/2/display/redirect) (still) gives me a 403. What is next? Just waiting for 2 more reviews?

**Review by jwillikers — DISMISSED** [review]

**Comment by prince-chrismc** [comment]
Let me kick the bot :)

**Comment by prince-chrismc** [comment]
There a backend (we call is c3i) and it loops over all the open PRs and since there's a lot it can take a while.

Review process and reviews are docs here https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md#rule-of-2-reviews :)

**Comment by axxel** [comment]
The build fails foremost because the test project is build with `cxx_std_14` but starting from 2.0 the client code needs to be compiled with a c++17 conforming compiler. That said, it seems some configurations did actually build and test OK, which I don't understand with my total lack of knowledge about the conan infrastructure.

I had a quick look at the different test sources and wonder what their purpose is. Why not use the ctests that come with the library? Or is the idea to check that a client code can actually be built from the installed library (which is actually a good idea, since we don't test that properly)? Why only test the writer part of the library?

Note: there is a deprecation warning about `ZXing::TextUtfEncoding::FromUtf8`. That function can simply be removed for 2.0, there is now an `encode(std::string)` overload.

Anyway: I don't have the time to first get sufficiently knowledgeable with your project to properly fix this the way you do things around here (e.g. simply build all tests with c++17 or add a new config just for version 2.0). So either someone tells me explicitly how you'd like this resolved (like sending me a diff), then I can update my PR or someone else needs to start from scratch.

**Comment by toge** [comment]
Sorry for the delay in responding.
I missed your PR and assignment.

My mistake.
Sorry for the inconvenience.

In order to get cci's CI to work, there are several fixes that need to be made.
As far as I have confirmed in my local environment, test_package should work with the following modifications.

test_package/CMakeLists.txt
```cmake_minimum_required(VERSION 3.8)
project(test_package LANGUAGES CXX)

find_package(ZXing REQUIRED CONFIG)
find_package(stb REQUIRED CONFIG)

if (ZXing_VERSION VERSION_LESS "1.1.0")
    add_executable(${PROJECT_NAME} test_package.cpp)
elseif (ZXing_VERSION VERSION_LESS "2.0.0")
    add_executable(${PROJECT_NAME} test_package_1.1.cpp)
else()
    add_executable(${PROJECT_NAME} test_package_2.0.cpp)
endif()
target_link_libraries(${PROJECT_NAME} PRIVATE ZXing::ZXing stb::stb)

if (ZXing_VERSION VERSION_LESS "2.0.0")
    target_compile_features(${PROJECT_NAME} PRIVATE cxx_std_14)
else()
    target_compile_features(${PROJECT_NAME} PRIVATE cxx_std_17)
endif()
```

test_package/test_package_2.0.cpp
```
#include "ZXing/BarcodeFormat.h"
#include "ZXing/BitMatrix.h"
#include "ZXing/BitMatrixIO.h"
#include "ZXing/CharacterSet.h"
#include "ZXing/MultiFormatWriter.h"
#include "ZXing/TextUtfEncoding.h"

#include <algorithm>
#include <cctype>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb_image_write.h>

using namespace ZXing;

int main(int argc, char* argv[])
{
    int width = 100, height = 100;
    int margin = 10;
    int eccLevel = 8;
    auto encoding = CharacterSet::Unknown;
    auto format = BarcodeFormat::QRCode;
    std::string text = "Hello conan world!";
    std::string outPath = "output.png";

    try {
        auto writer = MultiFormatWriter(format).setMargin(margin).setEncoding(encoding).setEccLevel(eccLevel);
        auto matrix = writer.encode(text, width, height);
        auto bitmap = ToMatrix<uint8_t>(matrix);

        int success = stbi_write_png(outPath.c_str(), bitmap.width(), bitmap.height(), 1, bitmap.data(), 0);
        if (!success) {
            std::cerr << "Failed to write image: " << outPath << std::endl;
            return -1;
        }
    } catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        return -1;
    }

    return 0;
}
```

**Comment by axxel** [comment]
@toge Thanks for picking this up and providing me with the code to fix the build issues. As you can see there was one line missing in `CMakeLists.txt` I added this back in with my last commit but the jenkins build bot says "This commit cannot be built". The "Details" are still not accessible to me. So I don't know what the issue is this time.

**Comment by toge** [comment]
@axxel 
Sorry for the missing lines in CMakeLists.txt.
In most cases of "This commit cannot be built", a reopen (close, wait 10 seconds and open) will solve the problem.

I wish I could do it for you, but I don't have the right.
Could you please do that?

**Review by toge — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
