### PR TITLE
qt6: add new components

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **qt/6.x**

fixes https://github.com/conan-io/conan-center-index/issues/18775

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@ericLemanissierBot build

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/5741609882)

**Comment by uilianries** [comment]
I just started a new CI build, let's see the new result.

**Comment by ericLemanissier** [comment]
Let's goo!

**Review by uilianries — APPROVED** [review]
It's really working with Conan 2!!

**Comment by uilianries** [comment]
Well, only Windows and Mac. Linux is giving invalid configuration 😞

**Comment by ericLemanissier** [comment]
Linux invalid configuration is because of CCI limitation, it works on non-outdated distros https://github.com/ericLemanissier/proof-of-conan/commit/9a762fd93d8e39cf505354de67ff42c05d7008d7/checks?check_suite_id=14767547752

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
