### PR TITLE
meson: add os settings

### PR DESCRIPTION
**Pull request by ericLemanissier**
this makes sure it is tested on all platforms

Specify library name and version:  **meson/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jgsogo** [comment]
> this makes sure it is tested on all platforms
> 

Not really, CCI will identify that all the profiles compute the same package-id and will _compiler_ and _test_ only one of them.

**Comment by uilianries** [comment]
Why do you need OS if meson should be multi-platform?

**Comment by ericLemanissier** [comment]
this PR follows https://github.com/conan-io/conan-center-index/pull/2034#issuecomment-653573472

**Comment by uilianries** [comment]
@ericLemanissier Thanks for the reference. Now it's clear.

**Comment by ericLemanissier** [comment]
@madebr no problem appear with this :/

**Comment by madebr** [comment]
The problem appeared in a `ninja install`.

**Comment by ericLemanissier** [comment]
I just noticed @madebr did some more usefull modifications to the test recipe : https://github.com/madebr/conan-center-index/commit/19b460e7299443e1b041212851b1feef4aeb1029
Do you want me to merge this in my branch ?

**Comment by SSE4** [comment]
@ericLemanissier yes, looks good

**Comment by madebr** [comment]
Ok, the weird error is visible on Windows:

```
Found ninja.EXE-1.10.0 at C:\J\workspace\onan-center-pull-request_PR-2119\3\pr_2119_3_18_1\.conan\data\ninja\1.10.0\_\_\package\f27dcd2d5e453cb01f9324a959461903ce8116a0\bin\ninja.EXE
Error in atexit._run_exitfuncs:


Traceback (most recent call last):


  File "C:\Python36\lib\site-packages\colorama\ansitowin32.py", line 59, in closed


    return stream.closed


ValueError: underlying buffer has been detached
```

It looks like this is a problem with colorama, which is a requirement of conan.

**Comment by madebr** [comment]
I don't think this pr needs to be merged.
It was opened by @ericLemanissier to show a potential problem during `meson install`.

**Comment by ericLemanissier** [comment]
If someone thinks this PR is actually needed, ping me and I'll reopen this PR !

**Pull request closed without merging**
