### PR TITLE
[easyhttpcpp] fix hook KB-H048

### PR DESCRIPTION
**Pull request by mathbunnyru**
Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by mathbunnyru** [comment]
Hook is going crazy?

**Comment by ericLemanissier** [comment]
no it's not : https://github.com/conan-io/conan-center-index/blob/master/recipes/easyhttpcpp/all/CMakeLists.txt#L1

**Comment by mathbunnyru** [comment]
Thanks @ericLemanissier

**Review by Croydon — APPROVED** [review]

**Comment by mathbunnyru** [comment]
Should be fixed by https://github.com/conan-io/conan-center-index/pull/4205

**Review by ericLemanissier — APPROVED** [review]

**Comment by mathbunnyru** [comment]
I merged master just to make sure there are no other changes in this recipe.

I will wait for https://github.com/conan-io/conan-center-index/pull/4205 to get to CCI artifactory and then I will retrigger the CI.
Should work fine.

**Comment by mathbunnyru** [comment]
@danimtb my PRs are not feeling well, some weird errors, it makes me sad :(

**Comment by danimtb** [comment]
checking

**Review by danimtb — APPROVED** [review]

**Comment by prince-chrismc** [comment]
@Croydon @ericLemanissier your approvals won't be counts by the bot 

***

I have a bug apparently 😄 

✔️ Ready to Merge

PR | By | Recipe | Reviews | 🛑 Blockers | 🌟 Approvers
-- | -- | -- | -- | -- | --
#4109 | mathbunnyru | 📝 easyhttpcpp | 3 |   | danimtb

**Review by prince-chrismc — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Pull request merged**
