### PR TITLE
[pdcurses] fix hooks and conventions, add FreeBSD support

### PR DESCRIPTION
**Pull request by mathbunnyru**
Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Comment by mathbunnyru** [comment]
@madebr may I ask you to take a look? I'm no Windows expert.

**Comment by madebr** [comment]
> 
> 
> @madebr may I ask you to take a look? I'm no Windows expert.

@mathbunnyru 

See https://github.com/mathbunnyru/conan-center-index/pull/4

Can you also modify the title to include FreeBSD?
@ericLemanissier has a bot that will run tests on FreeBSD when that os is mentioned in the title.

**Comment by mathbunnyru** [comment]
> > @madebr may I ask you to take a look? I'm no Windows expert.
> 
> @mathbunnyru
> 
> See [mathbunnyru#4](https://github.com/mathbunnyru/conan-center-index/pull/4)
> 
> Can you also modify the title to include FreeBSD?
> @ericLemanissier has a bot that will run tests on FreeBSD when that os is mentioned in the title.

@madebr you're the best. Done :)

**Comment by ericLemanissier** [comment]
build started https://github.com/ericLemanissier/conan-center-index/runs/1677926262?check_suite_focus=true (I have to trigger it manually, so please tag me when you need it !)

**Comment by madebr** [comment]
Thanks Eric, the thing works!

**Review by SSE4 — APPROVED** [review]

**Review by madebr — APPROVED** [review]
@uilianries 
This PR needs a final approval from you.

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
