### PR TITLE
Add CMake 3.16.2

### PR DESCRIPTION
**Pull request by Croydon**
Specify library name and version:  **cmake/3.16.2**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

_______

Based on https://github.com/conan-community/conan-cmake-installer

I decided on purpose to only add the latest release. If there is demand for the older versions we can still add them later

### CODE REVIEW

**Comment by Croydon** [comment]
I can't successfully move the `share` directory in a way CMake seems to accept, despite changing the `CMAKE_ROOT` variable https://cmake.org/cmake/help/latest/variable/CMAKE_ROOT.html

**Comment by danimtb** [comment]
I think we can whitelist this one in the hook

**Comment by gocarlos** [comment]
will this make it possible to do `conan install cmake`?

**Comment by jgsogo** [comment]
@gocarlos, Yes, really useful as a `build_requires`; or you can use a `virtualenv` generator to put it in the PATH and use the CMake version you want in the command line.

---

@Croydon Not merged yet, but I'm already asking you to include older versions 😅 This is a recipe I use a lot while developing CMake-related features for Conan, or triaging issues. There are some versions that come to my mind right now: 
 * 2.8.12: the oldest one I use now (probably we should think about dropping support for this one)
 * ~3.0: targets support
 * ~3.4: introduces `WINDOWS_EXPORT_ALL_SYMBOLS`
 * ~3.15: introduces `CMAKE_PROJECT_INCLUDE` (for the toolchain feature)

But don't worry too much about it, we already have the `cmake_installer...@conan/stable` ones.

**Comment by Croydon** [comment]
> I think we can whitelist this one in the hook

I created a pull request https://github.com/conan-io/hooks/pull/144

**Comment by madebr** [comment]
The built cmake will use vendorized versions of libraries that CCI ships.
I'm talking about libraries such as: libcurl, expat, zlib, bzip2, libarchive, jsoncpp, xz_utils, zstd

**Comment by Croydon** [comment]
Do closing/reopening not trigger anymore a new build?

**Comment by danimtb** [comment]
Merging this one. Let's add older versions later. Thanks @Croydon!

**Pull request merged**
