### PR TITLE
gdbm: Support Conan V2

### PR DESCRIPTION
**Pull request by jwillikers**
Required for PR #17355.

Also, added version 1.23.

For some reason, these changes result in the preprocessor macro `YYDEBUG` not being defined to `1` in the currently packaged versions of `gdbm` when the `gdbmtool_debug` option is enabled.
I've mitigated this by defining the macro appropriately when `gdbmtool_debug` is enabled.
Note that this definition does not need to be specified manually for version 1.23, only for the previous versions.

Specify library name and version:  **gdbm/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jwillikers** [comment]
@RubenRBS It looks like this is hitting the same issue as #13400. Considering the v2 test package worked earlier, the `test_v1_package` must be where the problem is.

**Comment by jwillikers** [comment]
@RubenRBS Looks like I was able to sneak past the test package timeout with the latest rebuild. If you could review, it would be much appreciated. I'm trying to get this updated so that I can get V2 builds for #17355 passing. Thanks!

**Comment by RubenRBS** [comment]
Sure thing! Sorry about the timeout issue, we have planned a deep investigation into its root cause this week to see if we can come up with something, as such a test should not be timing out

**Review by RubenRBS — APPROVED** [review]
Thanks!

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
