### PR TITLE
civetweb: Bump versions

### PR DESCRIPTION
**Pull request by alejandro-colomar**
**civetweb/1.14**

prometheus-cpp 0.12.3 bumped the dependency of civetweb in their upstream source to 1.14.
To be able to package prometheus-cpp, we need to produce the civetweb/1.14 pkg.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
I have some doubts:  When I bump a version of a requirement, I can't specify to which version it applies.  Does it apply to all of them?  By looking at the CI logs, it does, but then, if a new version of a dependency should be updated only for the latest (or any specific one) version of the package, how should I do it?

It's not this case, but I'm curious on how you normally proceed.

**Comment by jgsogo** [comment]
We try to update all the requirements always, it is the _best_ way to avoid conflicts when consuming unrelated packages (unrelated in CCI) from a consumer project.

If for any reason, one of the versions doesn't work with the new version of the requirement, you can add `if/else` clause:

```python
def requirements(self):
  if self.version == '1.0':
    self.requires('req/v1')
  else:
    self.requires('req/v2')
```

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by alejandro-colomar** [comment]
What is that license/cla check that is still not completed?

**Comment by jgsogo** [comment]
> What is that license/cla check that is still not completed?

It is the Contributor License Agreement. If you have already signed it, then it looks like there is some problem on their side and they are not notifying the status. I'll close and open this PR again, sometimes it triggers and event and the notification arrives.

**Comment by prince-chrismc** [comment]
It worked this time 👍

**Pull request merged**
