### PR TITLE
bison: add version 3.8.2

### PR DESCRIPTION
**Pull request by jkimblad**
**bison/3.8.2**

Looking forward to using the new features from the latest release of bison in my project.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@jkimblad thank you for your contribution, please, do not forget to sign the CLA, otherwise, we will not be able to merge your PR.

**Review by remi-aniah — COMMENTED** [review]
I don't understand why you change os.rename in tools.rename, but the other changes ares what I wanted to do !

**Comment by uilianries** [comment]
> I don't understand why you change os.rename in tools.rename, but the other changes ares what I wanted to do !

@remi-aniah Please, read the official documentation: https://docs.conan.io/en/latest/reference/conanfile/tools/files/basic.html#conan-tools-files-rename

**Review by remi-aniah — APPROVED** [review]

**Comment by SSE4** [comment]
the error looks similar to #506 🤔

**Pull request closed without merging**
