### PR TITLE
dcmtk: fix regression on `enable_stl` option

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/20376

also improve a little bit `_collect_cmake_required()` (see https://github.com/conan-io/conan-center-index/pull/20239#discussion_r1343248844)

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Tested locally and now I see:

```
-- Checking whether STL vector works correctly
-- Checking whether STL vector works correctly -- yes
-- Info: STL vector support enabled
-- Checking whether STL algorithm works correctly
-- Checking whether STL algorithm works correctly -- yes
-- Info: STL algorithm support enabled
-- Checking whether STL limits works correctly
-- Checking whether STL limits works correctly -- yes
-- Info: STL limits support enabled
-- Checking whether STL list works correctly
-- Checking whether STL list works correctly -- yes
-- Info: STL list support enabled
-- Checking whether STL map works correctly
-- Checking whether STL map works correctly -- yes
-- Info: STL map support enabled
-- Checking whether STL memory works correctly
-- Checking whether STL memory works correctly -- yes
-- Info: STL memory support enabled
-- Checking whether STL stack works correctly
-- Checking whether STL stack works correctly -- yes
-- Info: STL stack support enabled
-- Checking whether STL string works correctly
-- Checking whether STL string works correctly -- yes
-- Info: STL string support enabled
-- Checking whether STL type_traits works correctly
-- Checking whether STL type_traits works correctly -- yes
-- Info: STL type_traits support enabled
-- Checking whether STL tuple works correctly
-- Checking whether STL tuple works correctly -- yes
-- Info: STL tuple support enabled
-- Checking whether STL system_error works correctly
-- Checking whether STL system_error works correctly -- yes
-- Info: STL system_error support enabled
```

Without this fix there was:

```
-- Info: STL vector support disabled
-- Info: STL algorithm support disabled
-- Info: STL limits support disabled
-- Info: STL list support disabled
-- Info: STL map support disabled
-- Info: STL memory support disabled
-- Info: STL stack support disabled
-- Info: STL string support disabled
-- Info: STL type_traits support disabled
-- Info: STL tuple support disabled
-- Info: STL system_error support disabled
```

**Comment by RubenRBS** [comment]
Thanks for your quick fix, really appreciated!

**Review by RubenRBS — APPROVED** [review]
Thanks for the extra link to context about the origin of the collect_cmake_required changes :)

**Comment by RubenRBS** [comment]
Retriggered v1

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
