### PR TITLE
SystemC: Patch Accellera release to enable work with Address Sanitizer

### PR DESCRIPTION
**Pull request by staskau**
Patch Accellera release to enable work with Aderess Sanitizer

Specify library name and version:  **systemc/2.3.3_asan**

SystemC 2.3.3 does not work with AddressSanitizer (https://forums.accellera.org/topic/7085-systemc-233-member-access-within-misaligned-address-error/). 
This issue is planed to be resolved in the upcomming Accellera release (https://github.com/accellera-official/systemc/pull/17) of the library. Currently it is not clear when the next release will take place.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — CHANGES_REQUESTED** [review]
Release the version 2.3.4. Conan Center Index accepts only patches related to security or build support. More information: https://github.com/conan-io/conan-center-index/blob/master/docs/policy_patching.md#rules

**Comment by staskau** [comment]
> Release the version 2.3.4. Conan Center Index accepts only patches related to security or build support. More information: https://github.com/conan-io/conan-center-index/blob/master/docs/policy_patching.md#rules

I must correct myself. This is not a bugfix or backported feature. This change enables the user to work with AddressSanitizer. There is currently no release newer than 2.3.3 and it is not foreseeable when an official release will be made. I got confused by this comment https://github.com/accellera-official/systemc/pull/17#issuecomment-920193674, but the fact is 2.3.3 is latest release.

So I can't change the 2.3.3 release (because it wouldn't fit the source code of the official release, of course), but I can't make a 2.3.4 release either (because Accellera hasn't made it yet). 
For this reason I have prepared 2.3.3_asan package, so the official releases are not broken and you still have the possibility to use SystemC with ASAN.

**Comment by uilianries** [comment]
And does consist the version https://github.com/accellera-official/systemc/releases/tag/2.3.4_pub_rev_20190614 ? 

Also, any non-official release, should follow the cci version pattern: https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases

**Comment by staskau** [comment]
https://github.com/accellera-official/systemc/releases/tag/2.3.4_pub_rev_20190614  is not an official release, but only a pre-release for public review and there has been no update for 3 years. 
We and also our custommers are using the latest official release 2.3.3, so we would like to enable the ASAN support for this version. I'm just not sure how to do it correctly. According https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases  this release would be systemc/2.3.3-cci.20220816, but since cci is a name of another library systemc-cci  (https://conan.io/center/systemc-cci) and this fix has nothing to to with systemc-cci I find this naming very confusing.

I think this case fits the situation described here: https://github.com/conan-io/conan-center-index/blob/master/docs/policy_patching.md#exceptions

SystemC consumers will benefit from having these patches applied to previous versions while waiting for the next release.
I just don't understand what I have to do to satisfy this rule and how to use PLACEHOLDER_FOR_RELEASE_FORMAT.
Could you please help me with that?

**Comment by uilianries** [comment]
> systemc/2.3.3-cci.20220816, but since cci is a name of another library systemc-cci ([conan.io/center/systemc-cci](https://conan.io/center/systemc-cci)) and this fix has nothing to to with systemc-cci I find this naming very confusing.

The correct name is `systemc/cci.<yyyymmdd>` where the date is related to the commit date. You should use it if that project does not release a new version for so long. Still, creating a new custom release name does not follow CCI standard. There are many projects using it: https://github.com/conan-io/conan-center-index/search?l=yaml&q=cci.&type=code

**Pull request closed without merging**
