### PR TITLE
Bugfix/qt packages not used in requires

### PR DESCRIPTION
**Pull request by CAMOBAP**
**qt/5.15.2**

Related issue https://github.com/conan-io/conan-center-index/issues/5931

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
A conflicting PR was merged with parts of the same fixes

**Comment by CAMOBAP** [comment]
@prince-chrismc yep, I will update my PR because it include handling of `alsa` and `glib` too

**Comment by SpaceIm** [comment]
FYI, I'm working on a big fix in `package_info()` of qt6:
- add missing dependencies in `requires` (`glib`, `zstd`, `vulkan-loader`)
- add missing plugins and modules (too many to list them here 😄 )
- add modules/plugins only when proper options are set (it can be very complex) or dependencies missing.
- fix few internal dependencies in modules
- add a lot of system libs and frameworks in several modules and plugins
- unvendor few libs (`libtiff` and `libwebp` for `qtimageformats`)

**Comment by CAMOBAP** [comment]
@SpaceIm oh, thanks for sharing this, will it backported to qt5? I mean should I keep this PR or close it because of the upcoming one?

**Comment by SpaceIm** [comment]
Keep it, I do not plan to work on qt5 recipe soon.

**Comment by prince-chrismc** [comment]
> AssertionError: PREV for opengl/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 is None

CI bug...

You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁

**Review by AndreyMlashkin — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@CAMOBAP you can retrigger CI, this kind of failure should go away.

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
