### PR TITLE
fix arrow typo

### PR DESCRIPTION
**Pull request by wgtmac**
Specify library name and version:  **arrow/15.0.0**

Fix a typo

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by wgtmac** [comment]
@RubenRBS @danimtb Just fix some typos. PTAL. Thanks!

**Comment by RubenRBS** [comment]
Hi @wgtmac, thanks a lot for your contribution!

Please note that we usually don't merge PRs that simply fix typos, because it leads to a new recipe revision - this in turn makes people download new binaries (if they call --update) that are identical to their previous one.

I'm approving this one because https://github.com/conan-io/conan-center-index/pull/23480 is also going to get merged soon which actually changes things, so users will want to update to the newer version either way

Thanks a lot!

(Please disregard the CI errors, Jenkins is having some stability issues at the moment, we'll run the CI after it gets fixed)

**Review by RubenRBS — APPROVED** [review]

**Comment by uilianries** [comment]
It's not a typo, it's Latin!!! `Utilis` means `useful` 😹

**Review by toge — APPROVED** [review]

**Comment by wgtmac** [comment]
> It's not a typo, it's Latin!!! `Utilis` means `useful` 😹

Good to learn something new :)

**Comment by danimtb** [comment]
Added this small changes in https://github.com/conan-io/conan-center-index/pull/23480, this way we avoid regenarating arrow again and create many recipe revisions in the center. Thanks @wgtmac!

**Comment by danimtb** [comment]
nevermind, it got merged anyway 😆

**Comment by wgtmac** [comment]
Thanks everyone!

**Pull request merged**
