### PR TITLE
bump cpprestsdk/2.10.17

### PR DESCRIPTION
**Pull request by prince-chrismc**
Specify library name and version:  **cpprestsdk/2.10.17**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Review by Croydon — APPROVED** [review]

**Review by dmn-star — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Lol cci bot hates this PR thanks ❤️  for restarting it xD  its stuck again

**Comment by dmn-star** [comment]
The cci bot  celebrates New Year's Eve already. 😆

**Comment by prince-chrismc** [comment]
Passed but CCI status is in progress so something went wrong =/

**Review by mathbunnyru — APPROVED** [review]

**Comment by prince-chrismc** [comment]
#2857 

Can I bother you guys for an easy bump review please 🙏 CCI is finally passing 🎉 

@madebr
@SpaceIm
@ericLemanissier
@intelligide
@theirix

**Review by SpaceIm — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Thank you!

**Pull request merged**
