### PR TITLE
[fix] fix onnxruntime android build

### PR DESCRIPTION
**Pull request by JonathanGirardeau**
Specify library name and version:  **onnxruntime/1.15.1**

Fix issue #22358 

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by JonathanGirardeau** [comment]
Hello, can someone helps this pull request to be merged please ?
The CI fails randomly because of errors:
```"Can't find a '<deps>' package for the specified settings"```

**Comment by JonathanGirardeau** [comment]
Hello @ericLemanissier @prince-chrismc, could you review this PR please ?

**Review by ericLemanissier — APPROVED** [review]

**Comment by JonathanGirardeau** [comment]
Hi @jwillikers could you review my PR ?

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
