### PR TITLE
- add luajit/2.0.5

### PR DESCRIPTION
**Pull request by SSE4**
Specify library name and version:  **luajit/2.0.5**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Lua is the favorite @SSE4 programming language! :joy:

**Comment by madebr** [comment]
When reviewing the build logs, both a static library and a shared library are built/copied:
```
luajit/2.0.5 package(): Packaged 1 '.a' file: libluajit.a
luajit/2.0.5 package(): Packaged 1 '.so' file: libluajit.so
```

**Comment by SSE4** [comment]
@madebr was tricky, required patching makefiles, as by default it tries both...

**Review by uilianries — APPROVED** [review]
It could be well simplified by CMake, but it seems like LuaJIT team doesn't like it: https://github.com/LuaJIT/LuaJIT/issues/476#issuecomment-562999473

**Comment by SpaceIm** [comment]
O2 should be removed from msvc build: https://github.com/LuaJIT/LuaJIT/blob/0bf80b07b0672ce874feedcc777afe1b791ccb5a/src/msvcbuild.bat#L17

**Review by prince-chrismc — APPROVED** [review]

**Review by theirix — APPROVED** [review]
Unix builds look good

**Pull request merged**
