### PR TITLE
pcapplusplus: update libpcap dependency to 1.10.1

### PR DESCRIPTION
**Pull request by seladb**
Specify library name and version:  **pcapplusplus/22.11**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by leoparente** [comment]
Hello Folks. We use `PcapPlusPlus` through Conan in our project and this is a important update because `libpcap` releases have important bugfixes and improvements.

**Comment by uilianries** [comment]
@seladb https://status.conan.io/

**Review by Croydon — APPROVED** [review]

**Comment by seladb** [comment]
@uilianries @prince-chrismc @Croydon now it seems Visual Studio license has expired, can you please assist?

**Comment by prince-chrismc** [comment]
Let's see if it passes this time, you have others interested in this recipe https://www.reddit.com/r/cpp/comments/11sutfa/pcapplusplus_in_conan_20/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by seladb** [comment]
> Let's see if it passes this time, you have others interested in this recipe https://www.reddit.com/r/cpp/comments/11sutfa/pcapplusplus_in_conan_20/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

Thank you @prince-chrismc for the callout! I responded on the Reddit thread, I really hope to make this change in the next release of PcapPlusPlus but I think I'll need Conan team's help in this rewrite.

In the meantime - this small PR still fails 😕 
Any idea why?

**Comment by seladb** [comment]
The libpcap upgrade is already covered in [this PR](https://github.com/conan-io/conan-center-index/pull/16605#) that upgrades the PcapPlusPlus recipe to Conan 2.0. 

Closing this PR

**Pull request closed without merging**
