### PR TITLE
Update serf/1.3.9 dependencies

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **serf/1.3.9**

Related to conan-io/conan-center-index#9311

blocked by https://github.com/conan-io/conan-center-index/issues/9308

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Our scons Conan package is not able to deal with white spaces ... Reported here: https://github.com/conan-io/conan-center-index/issues/9308

**Comment by SSE4** [comment]
@uilianries what was a conclusion about scons? I remember there was a conversation in main conan-io repo, but I couldn't find it any more

**Comment by uilianries** [comment]
> @uilianries what was a conclusion about scons? I remember there was a conversation in main conan-io repo, but I couldn't find it any more

After adding that bash script to Scons recipe it was no longer able to parse commands with white spaces. It was not able to fix (lack of skills). We would need a fix there and that's it.

**Comment by puetzk** [comment]
@uilianries if you want to restart the CI on this one, I think it should pass now that #11219 is in. I'll rebase #11215 after your recipe cleanups have gone in.

**Pull request closed without merging**
