### PR TITLE
hictk: new recipe

### PR DESCRIPTION
**Pull request by robomics**
Specify library name and version:  **hictk/0.0.1**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by robomics** [comment]
It looks like `find_package(FastFloat)` is not called when configuring the test package in conan v2 CI.
I can reproduce this locally but I am not sure how to further debug the issue.

**Comment by fschoenm** [comment]
You probably need `transitive_headers` in your dependency because one of the headers is visivle in your own public header.

**Comment by robomics** [comment]
You are right, thanks for the pointer!

**Review by uilianries — COMMENTED** [review]
only a small detail, but looking good.

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
