### PR TITLE
New glm version in recipes/glm/all/conandata.yml

### PR DESCRIPTION
**Pull request by joaotavora**
Thanks Paul Harris for the hand-holding and bug hunting.

* recipes/glm/all/conandata.yml (sources): Add a source for the latest
commit of 20220420.

* recipes/glm/config.yml: Also mention new version here.

* recipes/glm/all/conanfile.py (GlmConan.package): Tweak for
  "cci.*" versions.

Specify library name and version:  **glm/cci.20220420** built from GitHub's on-demand per-commit zip service.

> This is also a good place to share with all of us **why you are submitting this PR**

Oh, just because the latest tagged verion 0.9.9.8 is from ~2018~2020 but it has a nagging warning (which converts to error with `-Werror` with C++20 that has been fixed 2 years ago.  They should really make a new version tag.

I'm afraid I didn't do any of the below items  :point_down:  :grimacing:   I'm very new to conan and I also don't have much time.
---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
0.9.9.8 is from April 2020, not 2018. Could you ask upstream to release a new version instead? cci versions can be confusing when there are also proper releases, and here I'm not sure that it's a good reason to package a cci version.

**Comment by joaotavora** [comment]
that issue already exists.  https://github.com/g-truc/glm/pull/1108 by @paulharris 

> cci versions can be confusing when there are also proper releases, and here I'm not sure that fixing a warning is good reason to package a cci version.

I guess, but it's better than the current situation? The warning is annoying enough to break anyone who has `-Werror` in the CMake `CXXFLAGS` :shrug: Not sure I can/should turn off warnings for a particular header (unless maybe I precompile it).

**Comment by joaotavora** [comment]
> 0.9.9.8 is from April 2020, not 2018. 

You're right, sorry.  I was looking at the last commit of the 0.9.9.8 branch, that does seem to be from 2018. https://github.com/g-truc/glm/tree/0.9.8.  I guess I don't understand how they do versioning around those parts.  Pretty good library though.

**Comment by paulharris** [comment]
> 0.9.9.8 is from April 2020, not 2018. Could you ask upstream to release a new version instead? cci versions can be confusing when there are also proper releases, and here I'm not sure that fixing a warning is good reason to package a cci version.

I was wondering how best to handle an "intermediate" version number.
I don't think it is reasonable to have to wait for upstream to tag a release, especially in this situation where the library is stable and the users probably just use origin/master anyway.

Perhaps instead, we do 0.9.9.8-cci.date

So at least conan users can see the version ordering.
It breaks (?) semver, but still at least the human can tell the ordering when 0.10.0.0 or 0.9.9.9 comes along.

Debian do this a lot with their ~version suffixes.

**Comment by SpaceIm** [comment]
How do you consume glm? You should use `-isystem` to avoid warnings in your dependencies.

**Comment by joaotavora** [comment]
Seems Conan's Cmake integration doesn't use `-isystem`.  This is what it plugs in for me:
```
-I$HOME/.conan/data/glm/cci.20220420/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
```

**Comment by SpaceIm** [comment]
Add `cmake_find_package` generator, `find_package(glm REQUIRED)` and `target_link_libraries(myapp PRIVATE glm::glm)`. Eventually replace `conan_basic_setup()` by `conan_basic_setup(TARGETS)`.

**Review by prince-chrismc — COMMENTED** [review]
Barely maintained projects are a pain... this matches with our policy https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases

So it's fine... there's lost of other fixes and improvements that are going to be added which is good

**Comment by prince-chrismc** [comment]
@paulharris thanks for help @joaotavora, was reading the slack convo 🤗

**Comment by joaotavora** [comment]
> Add cmake_find_package generator, find_package(glm REQUIRED) and target_link_libraries(myapp PRIVATE glm::glm). Eventually replace conan_basic_setup() by conan_basic_setup(TARGETS).

Isn't there an alternative that doesn't involve me adding "package-x"-specific stuff to my `CMakeLists.txt`?  Maybe some option in `conanfile.txt`? Or tell conan to use `-isystem` instead of `-I`?

Because avoiding solutions like yours is kind of the reason I started using Conan in the first place: to separate concerns.  I might as well go back to `vendor/` or `external/` schemes, otherwise. 

Just speaking as a beginner Conan user, but I've experience with other package repositories. I don't understand why given a half-decent way to deal with a library that hasn't gotten a new version in 2+ years, canon-io doesn't take it.

I don't understand what can possibly be confusing about having `cci.*` versions vs tagged releases.  The latter are probably more stable, the former less so but sometimes more useful.  It could other things other than warning avoidance, like features or the bugfixes that happened in these 2 years.

Anyway, I leave this here in good faith.  My problem is solved for the moment, and I can always host my own artifact repository I guess.

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
> > Add cmake_find_package generator, find_package(glm REQUIRED) and target_link_libraries(myapp PRIVATE glm::glm). Eventually replace conan_basic_setup() by conan_basic_setup(TARGETS).
> 
> Isn't there an alternative that doesn't involve me adding "package-x"-specific stuff to my `CMakeLists.txt`? Maybe some option in `conanfile.txt`? Or tell conan to use `-isystem` instead of `-I`?
> 
> Because avoiding solutions like yours is kind of the reason I started using Conan in the first place: to separate concerns. I might as well go back to `vendor/` or `external/` schemes, otherwise.
> 
> Just speaking as a beginner Conan user, but I've experience with other package repositories. I don't understand why given a half-decent way to deal with a library that hasn't gotten a new version in 2+ years, there's resistance to this.
> 
> I don't understand what can possibly be confusing about having `cci.*` versions vs tagged releases. The latter are probably more stable, the former less so but sometimes more useful. It could other things other than warning avoidance, like features or the bugfixes that happened in these 2 years.
> 
> Anyway, I leave this here in good faith. My problem is solved for the moment, and I can always host my own artifact repository I guess.

Your way to inject libraries with `cmake` generator will be removed in conan v2 anyway, so I advice to use `CMakeToolchain` & `CMakeDeps`, rely on imported targets, and write an agnostic CMakeLists. I don't understand what you mean by "separate concerns".

**Comment by joaotavora** [comment]
> Your way to inject libraries with cmake generator will be removed in conan v2 anyway,

Yes, @paulharris has let me know as well.  Well I hope do hope there's the usual generous deprecation period between now and "removal".  I mean, the "current way" is still the one recommended in the tutorial today.

> and write an agnostic CMakeLists.  I don't understand what you mean by "separate concerns".

I think you answered exactly in the preceding earlier :-).  "Separate concerns" means the same as "agnostic CMakeLists.txt". Like the one I have now. A package-agnostic one.  IOW, a CMakeLists.txt where the names of the dependencies can be completely absent.

So currently, if I add a new dependency, say `boost`, `glm`, `catch2` or `wunderfoo`, I only have to mention it 2.  Once in my `conanfile.txt` and again in my actual code that `#include <x>` 's it.  

So if there are _other_, more modern 2.0  ways to write "agnostic CMakeLists.txt", I'm in.  It's just that your earlier suggestion didn't seem to point in that direction.

**Comment by SpaceIm** [comment]
By agnostic CMakeLists, I mean not dependent to a specific package manager, something like this:

```cmake
cmake_minimum_required(VERSION 3.12)
project(myproject CXX)

find_package(glm REQUIRED)

add_executable(myapp ...)
target_compile_features(myapp PRIVATE cxx_std_20)
target_link_libraries(myapp PRIVATE glm::glm)
```

By separation of concerns, you mean a generic CMakeLists for all your projects without explicit link of your targets to their dependencies. It's not the direction taken by conan v2, it's not even recommended in conan v1 I think, and it's a good thing.

**Comment by joaotavora** [comment]
> By agnostic CMakeLists, I mean not dependent to a specific package manager,

Interesting.  I prefer being tied to a package manager than tied to a specific package in multiple places. That's because I change package managers much less often than I do dependencies.

> It's not the direction taken by conan v2, it's not even recommended in conan v1 I think, 

Well, it _is_ the version recommended in the ["Getting Started"](https://docs.conan.io/en/latest/getting_started.html) document.  As I am also "getting started" I though that would be good place to start :-).  

> and it's a good thing.

Sure, we can disagree. Personally, I hate repeating myself.  This is why I like things like package-agnostic CMakeLists , file-agnostic CMakeLists (using `GLOB`, which other don't like) and things as `auto` and template argument deduction, among so many others.

**Review by prince-chrismc — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]
I understand the need for `cci.<date>` version, it's 2 years without a release...

**Pull request merged**
