### PR TITLE
libpqxx: add version 7.8.0

### PR DESCRIPTION
**Pull request by tt4g**
Specify library name and version:  **libpqxx/7.8.0**

New minor version release.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by tt4g** [comment]
I merged the master branch because I mistakenly thought that CI was not working because `.c3i/conan_v2_ready_references.yml` was changed.
It seems that CI is just having trouble, so I will revert.

**Review by uilianries — CHANGES_REQUESTED** [review]
Please, include only changes related to libpqxx in this PR.

**Comment by tt4g** [comment]
@uilianries Removed all commits not related to libpqxx.

**Review by uilianries — DISMISSED** [review]
LGTM

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
