### PR TITLE
opencv: update libwebp 1.2.1 -> 1.2.2

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **opencv/4.x**

Try to resolve https://github.com/conan-io/conan-center-index/pull/9289#issuecomment-1034351007

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
You can also update libwebp in 3.x branch in the meantime.

**Comment by toge** [comment]
@SpaceIm 
I agree with you.
I will try.

**Comment by SpaceIm** [comment]
All these linter messages make PR harder to review.

**Comment by ericLemanissier** [comment]
@SpaceIm I just whitelisted the FIXMEs and TODOs from the linter. it seems to work as expected: https://github.com/conan-io/conan-center-index/pull/9247/files#diff-8938123ce86db129790cfb63fac38df04c5cefb2bbfda9cf37a9b8925061a9cf

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
