### PR TITLE
add botan 2.16.0

### PR DESCRIPTION
**Pull request by hrantzsch**
Specify library name and version:  **botan/2.16.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Review by reneme — APPROVED** [review]

**Comment by hrantzsch** [comment]
CI seems a bit stuck. @uilianries ?

**Comment by uilianries** [comment]
@hrantzsch Yes, let's retry.

**Review by uilianries — APPROVED** [review]

**Comment by hrantzsch** [comment]
That helped, thanks! I'll look into what went wrong.

**Comment by hrantzsch** [comment]
Unfortunately I cannot reproduce the issue locally. Conan builds the recipe just fine, both with msvc 15 (2017) and 16 (2019).

It seems the visual studio tooling cannot be discovered on the CI. I'm not sure if this is an issue in the botan build system or on the build agent. I am pretty stuck on the issue. @uilianries do you have any ideas? These parts of the log seem most interesting:

In the output from `configure.py`:

```
WARNING: Could not execute ['cl', '/nologo', '/EP', '.\\src\\build-data\\detect_version.cpp']: [WinError 2] The system cannot find the file specified
WARNING: Tried to get msvc version, but output '0.0' does not match expected version format
WARNING: Could not execute ['cl', '/nologo', '/EP', '/MT', '/bigobj', '', '', '.\\src\\build-data\\detect_arch.cpp']: [WinError 2] The system cannot find the file specified
WARNING: Unable to detect target architecture via compiler macro checks
INFO: Target is msvc:0.0-windows-x86_64
 ```

Here botan cannot detect the mvsc version. I have seen this happen when vs tooling is not available in the shell.

Later in the compiler output:

```
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\J\w\cci_PR-3134/t\_CL_3fddbd3fex': No such file or directory
```

The forward slash in the path seems suspicious. Could this be a problem?

**Comment by hrantzsch** [comment]
I am still unable to reproduce the issue.

I tried to replicate the setup in an appveyor build: https://ci.appveyor.com/project/hrantzsch/conan-center-index

The build succeeds, but it also shows the toolchain warnings and the `INFO: Target is msvc:0.0-windows-x86_64`. So this is apparently not the issue.

I'm still suspicious of the forward slash in `'C:\J\w\cci_PR-3134/t\_CL_3fddbd3fex'`. Could this be something we should not get on Windows?

Is there anything else I can do to reproduce the problem? Did I miss any important configuration in my appveyor setup?

**Comment by hrantzsch** [comment]
Wait what? I just triggered a rebuild because I accidentally hit 'close with comment' :sweat_smile: 
So just a CI hiccup last time?

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
