### PR TITLE
serf: relocatable shared lib for macOS

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by uilianries** [comment]
hi @SpaceIm Could you please link a related issue, or at least, post a build log that proves your change? Regards.

**Comment by SpaceIm** [comment]
I can post result of otool -L with and without this PR when I'll be on my mac.

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
> @uilianries
> 
> ```
> cd <package_folder>/lib
> otool -L libserf-1.dylib
> ```
> 
> Without this PR:
> 
> ```
> libserf-1.dylib:
> 	/Users/spaceim/.conan2/p/b/serf4f40af08858cd/p/lib/libserf-1.dylib (compatibility version 1.3.0, current version 1.3.0)
> 	@rpath/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
> 	@rpath/libcharset.1.dylib (compatibility version 2.0.0, current version 2.0.0)
> 	@rpath/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
> 	@rpath/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
> 	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.3.0)
> 	@rpath/libapr-1.0.dylib (compatibility version 8.0.0, current version 8.4.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
> 	@rpath/libaprutil-1.0.dylib (compatibility version 7.0.0, current version 7.1.0)
> 	@rpath/libexpat.1.dylib (compatibility version 10.0.0, current version 10.10.0)
> ```
> 
> With this PR:
> 
> ```
> libserf-1.dylib:
> 	@rpath/libserf-1.dylib (compatibility version 1.3.0, current version 1.3.0)
> 	@rpath/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
> 	@rpath/libcharset.1.dylib (compatibility version 2.0.0, current version 2.0.0)
> 	@rpath/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
> 	@rpath/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
> 	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.3.0)
> 	@rpath/libapr-1.0.dylib (compatibility version 8.0.0, current version 8.4.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
> 	@rpath/libaprutil-1.0.dylib (compatibility version 7.0.0, current version 7.1.0)
> 	@rpath/libexpat.1.dylib (compatibility version 10.0.0, current version 10.10.0)
> ```

Thank you!!

**Pull request merged**
