### PR TITLE
flint: migrate to Conan v2

### PR DESCRIPTION
**Pull request by valgur**
TODO

- [x] `Could NOT find PThreads (missing: PThreads_LIBRARIES)`
- [x] `ERROR: Missing prebuilt package for 'mpfr/4.1.0'`

### CODE REVIEW

**Comment by valgur** [comment]
@uilianries `ERROR: Missing prebuilt package for 'mpfr/4.1.0'`

**Comment by uilianries** [comment]
@valgur I added `mpfr/4.1.0` in the build queue now. Thank you for reporting!

**Comment by valgur** [comment]
Closing temporarily to avoid unnecessary load on the CI. Will reopen when I'm actively working on the PR again.

**Comment by uilianries** [comment]
I just add a new PR fixing the situation with mpfr: https://github.com/conan-io/conan-center-index/pull/19150

**Comment by uilianries** [comment]
Just restarted this PR Build CI as now we have #19150 merged.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by toge — APPROVED** [review]

**Pull request merged**
