### PR TITLE
open62541: add v1.0.6 and v1.1.5 

### PR DESCRIPTION
**Pull request by saukijan**
add v1.0.6 and v1.1.5 releases. Patch files remain unchanged

Specify library name and version:  **open62541/1.0.6** and **open62541/1.1.5**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by saukijan** [comment]
that is weird, why is CI failing to build previous release? And why is it failing to recognize flags ` "-Wno-static-in-inline" `? 

The only changes to v1.0.3 and v.1.1.3 where hash calculations for `ua-nodeset` dependency (OPC UA Foundation, in there infinite wisdom, decided to update a tag, hence the change in hash code...)

**Comment by prince-chrismc** [comment]
The culprit is the `-Werror` that was added

https://github.com/open62541/open62541/blame/002750cba6151c3d353433c6199b16c9b7b36c79/CMakeLists.txt#L439

They also expanded the usage of it here

https://github.com/open62541/open62541/blame/master/CMakeLists.txt#L519

https://github.com/open62541/open62541/commit/c04429b824c790443d404fe96871342f432b6d75

Which is `v1.0.4`

... I do know why it changed by you'll need to remove that from the sources I believe

**Comment by saukijan** [comment]
Yeah, I suspected it was the `-Werror`, however, it was added 2 years ago, and the original v1.0.3 and v1.1.3 compiled without a problem... I'll guess I'll have to play around with this a bit more next week.

**Comment by prince-chrismc** [comment]
You can make a patch since it's only it one place and this should unblock your issue

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
