### PR TITLE
ffmpeg: bump dependencies

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
make: *** [/c/j/w/prod/buildsinglereference/.conan/data/ffmpeg/5.0/_/_/build/ad77562fc8851a7dea050484b3ad11a256f04262/source_subfolder/ffbuild/common.mak:100: libavfilter/x86/af_afir.o] Error 127
```

? I've just bumped few deps, so what's wrong?

**Comment by SSE4** [comment]
errno 127 is command not found
`af_afir.o` is `af_afir.asm` compiled with assembler.
it seems like assembler executable (nasm? yasm?) wasn't found for some reason? might it be because it suddenly resolved new package revision of build requirement?

**Comment by SpaceIm** [comment]
`yasm` is indeed in build requirements, and was updated recently in https://github.com/conan-io/conan-center-index/pull/13185 & https://github.com/conan-io/conan-center-index/pull/13573.

**Comment by SpaceIm** [comment]
There was a major change in https://github.com/conan-io/conan-center-index/pull/13185, msvc build was migrated from `sln` files to CMake.

**Comment by MartinDelille** [comment]
No. The cmake build was done here: https://github.com/conan-io/conan-center-index/pull/13185/commits/b48225081366c31969a2e0b588e312004bc95f6b

**Comment by SpaceIm** [comment]
> No. The cmake build was done here: [b482250](https://github.com/conan-io/conan-center-index/commit/b48225081366c31969a2e0b588e312004bc95f6b)

@madebr any idea why yasm fails on Windows?

**Comment by madebr** [comment]
How is the configured script informed about yasm?
`configure` of current ffmpeg has:
```
  --x86asmexe=EXE          use nasm-compatible assembler EXE [nasm]
```

**Comment by SpaceIm** [comment]
`--x86asmexe` is not passed to configure.

But during configure yasm seems to be detected:

```
install prefix            C:/J/w/prod/BuildSingleReference/.conan/data/ffmpeg/5.0/_/_/package/ad77562fc8851a7dea050484b3ad11a256f04262
source path               /c/j/w/prod/buildsinglereference/.conan/data/ffmpeg/5.0/_/_/build/ad77562fc8851a7dea050484b3ad11a256f04262/source_subfolder
C compiler                cl.exe
C library                 msvcrt
ARCH                      x86 (generic)
big-endian                no
runtime cpu detection     yes
standalone assembly       yes
x86 assembler             yasm
MMX enabled               yes
MMXEXT enabled            yes
3DNow! enabled            yes
3DNow! extended enabled   yes
SSE enabled               yes
SSSE3 enabled             yes
AESNI enabled             yes
AVX enabled               yes
AVX2 enabled              yes
AVX-512 enabled           yes
XOP enabled               yes
FMA3 enabled              yes
FMA4 enabled              yes
i686 features enabled     yes
CMOV is fast              yes
EBX available             no
EBP available             no
debug symbols             yes
strip symbols             no
optimize for size         no
optimizations             yes
static                    yes
shared                    no
postprocessing support    yes
network support           yes
threading support         w32threads
safe bitstream reader     yes
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          yes
makeinfo supports HTML    yes
xmllint enabled           yes
```

moreover we can see bin dir of yasm package in environment:

```
----Running------
> C:\J\w\prod\BuildSingleReference\s\c5811a\1\bin\msys64\usr\bin\bash.exe --login -c ^"cd \^"/c/j/w/prod/buildsinglereference/.conan/data/ffmpeg/5.0/_/_/build/ad77562fc8851a7dea050484b3ad11a256f04262\^" ^&^& PATH=\^"/c/j/w/prod/buildsinglereference/.conan/data/yasm/1.3.0/_/_/package/0a420ff5c47119e668867cdb51baff0eca1fdb68/bin:/c/j/w/prod/buildsinglereference/.conan/data/pkgconf/1.9.3/_/_/package/0a420ff5c47119e668867cdb51baff0eca1fdb68/bin:/c/j/w/prod/buildsinglereference/s/c5811a/1/bin/msys64/usr/bin:/c/j/w/prod/buildsinglereference/.conan/data/libiconv/1.17/_/_/package/7bd6f2c3d5c4e48a75805376b58cde753392f711/bin:/c/j/w/prod/buildsinglereference/.conan/data/freetype/2.12.1/_/_/package/c2481f7bf9fa68e77ac5e32c67eff32d33d0909e/bin:/c/j/w/prod/buildsinglereference/.conan/data/bzip2/1.0.8/_/_/package/f346bbbb687a20f72b88f02617b6b8f1300bad72/bin:$PATH\^" ^&^& make -j8 ^"
-----------------
```

In the new build of yasm recipe, I see that more executables than before are packaged in windows build, and a dll which was not here in previous build.

**Comment by madebr** [comment]
72c835918e33c73a5340d2bb1a765a1e99c606c9 goes from using the visual studio project to a cmake project.
Maybe the executables are not 100% compatible/supported?

**Comment by madebr** [comment]
I can reproduce this error when I build yasm with `MT` runtime, and not when yasm is built with `MD` runtime.
So when yasm is built with shared libraries, the runtime cannot be `MT(d)`.

**Comment by SpaceIm** [comment]
Thanks. It might be a good idea to build static flavor by default on Windows, to be consistent with autotools build, and remove lib since it's not even propagated in `package_info()` of yasm recipe currently.

**Pull request merged**
