### PR TITLE
qt6: bump dependencies

### PR DESCRIPTION
**Pull request by ericLemanissier**
fixes conan-io/conan-center-index#10443

Specify library name and version:  **qt/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by AndreyMlashkin — DISMISSED** [review]

**Comment by uilianries** [comment]
@ericLemanissier All good here. Is it still a Draft?

**Comment by ericLemanissier** [comment]
yes, because it does not solve anything actually.

**Review by AndreyMlashkin — APPROVED** [review]

**Comment by AndreyMlashkin** [comment]
maybe it's better then to remove with_pcre2 flag at all? Now it does not do anything meanful

**Comment by ericLemanissier** [comment]
yes, but it would break users using qt:with_pcre2=True, and it's probably temporary (hoping that https://bugreports.qt.io/browse/QTBUG-92454 will be fixed some day)

**Review by AndreyMlashkin — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Pull request merged**
