### PR TITLE
Fix benchmark/1.6.2 checksum

### PR DESCRIPTION
**Pull request by Croydon**
Fixes https://github.com/conan-io/conan-center-index/issues/11801

Specify library name and version:  **benchmark/1.6.2**
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
I don't understand how 1.5.0 can fail now

**Comment by Croydon** [comment]
@leha-bot Could you perhaps clarify this issue upstream?

**Comment by uilianries** [comment]
@Croydon please, drop all versions older than 1.5.6.

The include `limits` is missing and when we introduced 1.5.x, GCC 11 was not available yet in Conan Center.

The version 1.5.6 has limits included, so it works.

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by jgsogo** [comment]
Please, can someone add links to upstream issues where the checksum change is explained? (this is for traceability reasons)

Thanks! cc/ @jcar87

**Comment by SSE4** [comment]
https://github.com/google/benchmark/issues/1453#issuecomment-1204158460

**Pull request merged**
