### PR TITLE
coin-osi: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
This PR needs https://github.com/conan-io/conan-center-index/pull/15746 (to fix pkg_config_name of PkgConfigDeps generator).

**Comment by SpaceIm** [comment]
```
Perhaps you should add the directory containing `coinutils.pc'
to the PKG_CONFIG_PATH environment variable
Package 'coinutils', required by 'virtual:world', not found
coin-osi/0.108.6: 
configure: WARNING: Failed to find a Fortran compiler!
configure: WARNING: Using pkg-config together with MS or Intel Compiler on Windows is not support by example Makefiles. Consider using --disable-pkg-config.
configure: error: Required package CoinUtils not available.
configure: error: /bin/sh '/c/j/w/prod/buildsinglereference@3/.conan/data/coin-osi/0.108.6/_/_/build/e363b996481dec7f9909b333d17ccaa8bb269381/src/Osi/configure' failed for Osi
```

Works fine with legacy AutotoolsBuildEnvironment but not with AutotoolsToolchain... Could it come from a missing `unix_path()` conversion here https://github.com/conan-io/conan/blob/1.58.0/conan/tools/gnu/autotoolstoolchain.py#L142?

**Comment by SpaceIm** [comment]
> ```
> Perhaps you should add the directory containing `coinutils.pc'
> to the PKG_CONFIG_PATH environment variable
> Package 'coinutils', required by 'virtual:world', not found
> coin-osi/0.108.6: 
> configure: WARNING: Failed to find a Fortran compiler!
> configure: WARNING: Using pkg-config together with MS or Intel Compiler on Windows is not support by example Makefiles. Consider using --disable-pkg-config.
> configure: error: Required package CoinUtils not available.
> configure: error: /bin/sh '/c/j/w/prod/buildsinglereference@3/.conan/data/coin-osi/0.108.6/_/_/build/e363b996481dec7f9909b333d17ccaa8bb269381/src/Osi/configure' failed for Osi
> ```
> 
> Works fine with legacy AutotoolsBuildEnvironment but not with AutotoolsToolchain... Could it come from a missing `unix_path()` conversion here https://github.com/conan-io/conan/blob/1.58.0/conan/tools/gnu/autotoolstoolchain.py#L142?

Well no, it doesn't change anything to pass unix_path() in generated `conanautotoolstoolchain.sh`:

```
echo "echo Restoring environment" > "C:\Users\spaceim\.conan\data\coin-osi\0.108.7\_\_\build\836812841adeb5158788d3ad3822fa734ac759f4\build-release\conan\deactivate_conanautotoolstoolchain.sh"
for v in CC CXX CPPFLAGS CXXFLAGS CFLAGS LDFLAGS PKG_CONFIG_PATH LD AR
do
    is_defined="true"
    value=$(printenv $v) || is_defined="" || true
    if [ -n "$value" ] || [ -n "$is_defined" ]
    then
        echo export "$v='$value'" >> "C:\Users\spaceim\.conan\data\coin-osi\0.108.7\_\_\build\836812841adeb5158788d3ad3822fa734ac759f4\build-release\conan\deactivate_conanautotoolstoolchain.sh"
    else
        echo unset $v >> "C:\Users\spaceim\.conan\data\coin-osi\0.108.7\_\_\build\836812841adeb5158788d3ad3822fa734ac759f4\build-release\conan\deactivate_conanautotoolstoolchain.sh"
    fi
done


export CC="cl -nologo"
export CXX="cl -nologo"
export CPPFLAGS="$CPPFLAGS -DNDEBUG"
export CXXFLAGS="$CXXFLAGS -MD -O2 -Ob2 -EHsc -FS"
export CFLAGS="$CFLAGS -MD -O2 -Ob2 -FS"
export LDFLAGS="$LDFLAGS"
export PKG_CONFIG_PATH="/c/users/spaceim/.conan/data/coin-osi/0.108.7/_/_/build/836812841adeb5158788d3ad3822fa734ac759f4/build-release/conan:$PKG_CONFIG_PATH"
export LD="link -nologo"
export AR="lib -nologo"
```

I don't understand what's wrong.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
