### PR TITLE
xkbcommon: update dependencies and use VirtualBuildEnv

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **xkbcommon/***

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
LGTM!

**Comment by toge** [comment]
@uilianries 
Please give me some advice if possible.
I am trying to solve the same problem for SDL at https://github.com/conan-io/conan-center-index/pull/11817.
However, SDL CMakeLists.txt cannot find `wayland-scanner`.
Is there an additional definition to make `find_program` find `wayland-scanner` in `VirtualBuildEnv`?

**Review by jwillikers — APPROVED** [review]

**Comment by jwillikers** [comment]
@toge I'm working on this for `xkbcommon` in my updates to switch it to the MesonToolchain generator. See #11636. Still working out the correct way to do so, see the comments.

For CMake, this should work if its _prepended_ to the `PATH` environment variable, given they are using the standard search paths for `find_program`. Is that true? You could pass the variable used for the first argument to `find_program` set to the path of the `wayland-scanner` binary and this would also work.

**Comment by uilianries** [comment]
@toge I think @jwillikers idea's worth a try.

**Comment by toge** [comment]
@jwillikers @uilianries 
Thank you for your advices.
I will try your idea.

By the way, Now I realize I have missed your PR.
Because I think your PR is more valuable, shall I close this PR?

**Comment by jwillikers** [comment]
> @jwillikers @uilianries Thank you for your advices. I will try your idea.
> 
> By the way, Now I realize I have missed your PR. Because I think your PR is more valuable, shall I close this PR?

If you wish, I'm just waiting on #11927 to go in so that my PR can pass in CI. I hope.

**Comment by toge** [comment]
@jwillikers 
All right.
I will close this PR.
I wish your PR will be merged.

**Pull request closed without merging**
