### PR TITLE
ffmpeg: fix shared with apple clang 15 + use version range for zlib + bump deps

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/20088

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Building the missing v1 binary and prioritizing due to the zlib changes, thanks! :)

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/18416 has been merged during build of this PR in c3i I guess, and since conancenter remote seems to expose new RREV before availability of all corresponding PREV expected by c3i, it can break a tests of a PR.

**Comment by RubenRBS** [comment]
Yes, we're planning on implementing lockfiles into the CCI builds to ensure this does not happen again now that v2 lockfiles are much easier to work with :)

**Review by czoido — APPROVED** [review]

**Comment by SpaceIm** [comment]
v2 pipeline

```
ERROR: Missing binary: pulseaudio/14.2:4236ecb3e7785f54fd13d0bc1aae1d067cd2e366
```

/cc @RubenRBS

**Comment by RubenRBS** [comment]
Yes, the build I mentioned in https://github.com/conan-io/conan-center-index/pull/20152#issuecomment-1741633190 is still going :)

We usually take the weekends to run a TapaHoles over the whole repo so it's the only one that usually runs, will relaunch the PR when it finishes, no worries :)

**Review by jwillikers — APPROVED** [review]

**Comment by RubenRBS** [comment]
Rebuilding now

**Pull request merged**
