### PR TITLE
libpng: use autotools for non-windows builds + add neon/msa/sse/vsx options

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

In libpng, Autotools is more robust than current CMake build regarding ARM. I've tested native build on Macos x86_64, and cross-build to armv8 (Macos & iOS).

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
FYI, we keep libpng and libpng16 in lib folder, because many downstream libraries look for libpng, not libpng16.

**Review by madebr — DISMISSED** [review]

**Review by intelligide — APPROVED** [review]

**Comment by SSE4** [comment]
is it recommended officially? what exactly is more robust?

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
> is it recommended officially? what exactly is more robust?

I don't think they recommend any build system between autotools or CMake. See https://github.com/glennrp/libpng/blob/libpng16/INSTALL

Current autotools files are more robust for cross-compilation to ARM. See what I have removed in CMake configure, a fragile injection of CMAKE_SYSTEM_PROCESSOR very specific to armv8, and we have to force disable NEON if iOS while it works out of the box with autools.

**Comment by SpaceIm** [comment]
Maybe I should add sse and neon options.

**Comment by SpaceIm** [comment]
I don't know what to set for default values of neon and sse.

Upstream CMakeLists:
- neon: check (doesn't work for iOS/tvOS/watchOS)
- sse: True

Upstrem configure.ac:
- neon: False
- sse: False

**Review by madebr — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]
I am not a fan of adding auto-tools if we have CMake, but if CMake build is really problematic to maintain (especially, for cross-building), let's do that

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
CMake build might be used unconditionally later when CMake helper will be able to properly inject `CMAKE_SYSTEM_PROCESSOR` in case of cross-build.

**Pull request merged**
