### PR TITLE
add voropp/0.4.6

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Is `voro++` recipe name is allowed?

**Comment by uilianries** [comment]
> @uilianries Is `voro++` recipe name allowed?

It's valid. The current error is related to Mac:

```
dyld: Library not loaded: libvoro++.dylib
     Referenced from: /Users/jenkins/w/BuildSingleReference@3/conan-center-index/recipes/voro++/all/test_package/build/ad56ec13495fda3b9c443f5557b2cd8a95c89daf/bin/test_package
     Reason: image not found
   ERROR: voro++/0.4.6 (test package): Error in test() method, line 17
   	self.run(bin_path, run_environment=True)
   	ConanException: Error -6 while executing DYLD_LIBRARY_PATH="" DYLD_FRAMEWORK_PATH="" bin/test_package
```

**Comment by SpaceIm** [comment]
Yes, it's unrelated, I asked the question even before knowing that shared on macOS could fail.

**Comment by uilianries** [comment]
I just checked Microsoft page and `+` is totally fine, so we are safe. Thanks for asking.

**Comment by SpaceIm** [comment]
But not unrelated actually, if I change to voropp it works, so I guess that DYLD_LIBRARY_PATH is not very happy with `+` in the path.

**Comment by uilianries** [comment]
Interesting, we will need to rename or override `+` with `\+`

**Comment by uilianries** [comment]
It should work anyway, passing manually DYLD path it works:

```
$ DYLD_LIBRARY_PATH="/Users/user925459/.conan/data/voro++/0.4.6/_/_/package/e46341e9b52d3e4c66657dc8fb13ab6cdd5831c6/lib" /Users/user925459/Development/conan-center-index/recipes/voro++/all/test_package/build/6fa3b5fabe01897ef1f42f07896f75820389173f/bin/test_package
$ echo $?
0
```

**Review by uilianries — DISMISSED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
