### PR TITLE
Sqlcipher 4.4.0

### PR DESCRIPTION
**Pull request by madduci**
Specify library name and version:  **sqlcipher/4.4.0**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @madduci is there any reason for closing this PR? It looks promising ..

**Comment by madduci** [comment]
Hi @uilianries 

I closed it temporary because there was an error in the patch for visual studio, that I've fixed lately.

In addition to it, I've already another pending request about OpenSSL extension.

I hope it's fine so

**Comment by uilianries** [comment]
@madduci Thanks for your answer. I thought it was mistake, trying to retrigger the CI

**Comment by madduci** [comment]
closing the pull request, as someone else already added SQLCipher 4.4.0 to the repo

**Pull request closed without merging**
