### PR TITLE
Add waf/2.0.19 recipe

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **waf/2.0.19**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
@uilianries In my last push, I removed `no_copy_sourdce=True`.
Having this option in your recipe causes the CI to only create one package.

**Comment by uilianries** [comment]
> @uilianries In my last push, I removed `no_copy_sourdce=True`.
> Having this option in your recipe causes the CI to only create one package.

Interesting :thinking:

**Comment by madebr** [comment]
@SSE4 conan support for waf is lacking though. The same applies to scons.
I don't use these too, but needed it for some dependency.

**Comment by SSE4** [comment]
@madebr check [this](https://blog.conan.io/2019/07/24/C++-build-systems-new-integrations-in-Conan-package-manager.html) out, might be helpful

**Comment by madebr** [comment]
@SSE4 Thanks for the link.
I read it while trying to come up with a good test_package but struggled a bit.
I meant the support is not on par as those of cmake, autotools and meson.

**Comment by madebr** [comment]
@danimtb Final review please :relaxed:

**Pull request merged**
