### PR TITLE
flecs: add 4.0.0

### PR DESCRIPTION
**Pull request by NukeBird**
### Summary
Changes to recipe:  **flecs/4.0.0**

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by NukeBird** [comment]
https://www.flecs.dev/flecs/md_docs_2MigrationGuide.html

> ecs_new_id got renamed to ecs_new

probably that's the issue?

**Comment by AbrilRBS** [comment]
Hi @NukeBird thanks for pointing to the new name, I've added the necessary changes to the test package, I still need to fix the Conan 1 version, will do so momentarely :)

**Review by AbrilRBS — APPROVED** [review]
Thanks for taking the time to keep the library up-to-date, we appreciate it :)

**Review by AbrilRBS — APPROVED** [review]

**Comment by NukeBird** [comment]
@AbrilRBS thanks for your work!

looks like it needs one more assignee

**Review by perseoGI — APPROVED** [review]
LGTM https://github.com/SanderMertens/flecs/compare/v3.2.12...v4.0.0

**Pull request merged**
