### PR TITLE
Fix protobuf test_package

### PR DESCRIPTION
**Pull request by db4**
Specify library name and version:  **protobuf/3.9.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @db4 ! Could you explain the motivation of this change? 

Regards!

**Comment by db4** [comment]
> Hi @db4 ! Could you explain the motivation of this change?

Sure. `test_package` uses `protoc` prebuilt binary to compile testing code - that means you need it for the host platform, not for the target one. There were also some errors besides that:
https://github.com/conan-io/conan-center-index/blob/b461c1f26037ce1fbf3d3aa67ef5ad286f18781e/recipes/protobuf/all/test_package/CMakeLists.txt#L21
Actually, it should be `x86`
https://github.com/conan-io/conan-center-index/blob/b461c1f26037ce1fbf3d3aa67ef5ad286f18781e/recipes/protobuf/all/test_package/CMakeLists.txt#L28-L29
This is not correct for Linux/arm and Linux/x86. Google's arm suffix `aarch_64` differs from Conan's `armv8` and Google's `x86_32` differs from Conan's `x86`

**Comment by uilianries** [comment]
@db4 Have you tried the [Build Context](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer) feature? 

I see your problem is related to cross-building, now you can distinguish according your profile, which means, protoc should be able to run when cross-building.

**Comment by db4** [comment]
> @db4 Have you tried the [Build Context](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer) feature?
> 
> I see your problem is related to cross-building, now you can distinguish according your profile, which means, protoc should be able to run when cross-building.

Not exactly.  Linux/amv8, Linux/x86, Windows/x86 builds failed with no cross-building involved (with cross-building they would fail as well).  As for Build Context feature, I just tried to fix `test_package` changing as least as possible.

**Comment by db4** [comment]
The recipe is updated another way so close this PR

**Pull request closed without merging**
