### PR TITLE
gperftools: add new recipe

### LINKED ISSUE #1362: [request] gperftools/2.7
### Package Details
  * Package Name/Version: **gperftools/2.7**
  * Website: **https://github.com/gperftools/gperftools**
  * Source code: **https://github.com/gperftools/gperftools**

### Description Of The Library / Tool

gperftools is a collection of a high-performance multi-threaded malloc() implementation, plus some pretty nifty performance analysis tools.

### PR DESCRIPTION
**Pull request by valgur**
Specify library name and version:  **gperftools/2.10**

This package has quite a few options affecting the library files being generated. I have tested all relevant combinations locally on Linux.

Resolves #1362.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by valgur** [comment]
The build is failing on `armv8` during `./configure` with
```
checking whether we are cross compiling... configure: error: in `/Users/jenkins/w/prod-v2/BuildSingleReference/p/t/gperfe4f302d3f36ff/b/build/Release':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```
Does anyone have any ideas how to handle this? @uilianries?

Also, I initially used the CMakeLists.txt in the project, but switched to Autotools due to the static libraries generated by the CMake build script missing a lot of symbols (and corresponding translation units) in its static library output. Could also consider switching back and looking into the issues there instead. Would make adapting the recipe for Windows much easier, probably.

**Comment by uilianries** [comment]
@valgur probably you will need to pass --host just like https://github.com/conan-io/conan-center-index/blob/master/recipes/libx264/all/conanfile.py#L94

There are more recipes that need to configure manually when cross-building, you can find them by search `--host`. The thing is, gperftools is not natively prepared for Mac M1 and we have Mac Intel generating packages for M1 in CI, that's why you that error.

**Comment by valgur** [comment]
Thank you, @uilianries! That worked perfectly.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
