### PR TITLE
eastl: add 3.17.03 release + fix hooks

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **eastl/3.17.03**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
@ericLemanissier good bot! closed a bad/stale PR 🎉

**Comment by prince-chrismc** [comment]
```
C:\J\w\cci_PR-3643@6\.conan\data\eastl\3.17.03\_\_\build\78cc49134290dad53c2709997e72b7231e8c4d2b\source_subfolder\include\EASTL/internal/char_traits.h(274): error C3250: 'pCurrent': declaration is not allowed in 'constexpr' function body [C:\J\w\cci_PR-3643@6\.conan\data\eastl\3.17.03\_\_\build\78cc49134290dad53c2709997e72b7231e8c4d2b\build_subfolder\source_subfolder\EASTL.vcxproj]
```

https://github.com/electronicarts/EASTL/blob/3da94c98cf659dad79d43897bf3b0828ca850931/include/EASTL/internal/char_traits.h#L274

Seems like EASTL is correctly setting constexpr on for MSVC 14... it does not support constexpr auto

**Comment by ericLemanissier** [comment]
> @ericLemanissier good bot! closed a bad/stale PR 🎉

That's the least spamming bots can do: do something useful at least once a year 😄

**Comment by madebr** [comment]
> 
> 
> > @ericLemanissier good bot! closed a bad/stale PR 🎉
> 
> That's the least spamming bots can do: do something useful at least once a year 😄

A broken analog clock is correct twice a day 😆

**Comment by ericLemanissier** [comment]
Which is infinitely more than most of the working clocks!

**Comment by madebr** [comment]
@prince-chrismc 

> https://github.com/electronicarts/EASTL/blob/3da94c98cf659dad79d43897bf3b0828ca850931/include/EASTL/internal/char_traits.h#L274
> 
> Seems like EASTL is incorrectly setting constexpr on for MSVC 14... it does not support constexpr auto

It's enabled here (by a header in eabase)

**Comment by madebr** [comment]
I've opened https://github.com/electronicarts/EASTL/issues/402 so upstream knows about the problem.

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
