### PR TITLE
Add ogg/1.3.4

### PR DESCRIPTION
**Pull request by Croydon**
Specify library name and version:  **ogg/1.3.4**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
The patch got successfully applied locally

And CI only responded at all after the second commit, so is CI caused problems?

**Comment by SSE4** [comment]
let's re-run to check

**Comment by Croydon** [comment]
CI doesn't seem to re-run

**Comment by madebr** [comment]
@Croydon  Your patch is doing the reverse as the upstream patch: https://github.com/xiph/ogg/commit/c8fca6b4a02d695b1ceea39b330d4406001c03ed

**Comment by Croydon** [comment]
giphy

**Comment by Croydon** [comment]
@madebr Thanks a lot for noticing 😅

**Pull request merged**
