### PR TITLE
libarchive: add 3.5.1 + bump deps + cache cmake + del fPIC if shared + minor cosmetic changes

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **libarchive/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by mathbunnyru — DISMISSED** [review]
👍

**Review by prince-chrismc — APPROVED** [review]

**Comment by dmn-star** [comment]
You can back us VS 2019 build again, if you want. :-)
https://github.com/conan-io/conan-center-index/pull/3778#issuecomment-758947988

**Comment by SpaceIm** [comment]
I'll add a patch

**Comment by mathbunnyru** [comment]
And, to be 100% done with this recipe, you might want to add versions 3.5.0 and 3.5.1 :)
https://github.com/libarchive/libarchive/releases

**Comment by SpaceIm** [comment]
Only 3.5.1 eventually. There are no significant modifications between 3.4.3 and 3.5.1 in build files, so I guess I can try.

**Comment by dmn-star** [comment]
+1 for 3.5.1 only.
from release log various _compilation fixes_ (#1461, #1462, #1463, #1464) for  3.5.0.

**Comment by mathbunnyru** [comment]
Agree with 3.5.1 only 👍

**Review by mathbunnyru — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by mathbunnyru — APPROVED** [review]

**Review by mathbunnyru — APPROVED** [review]

**Review by theirix — APPROVED** [review]

**Review by dmn-star — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
