### PR TITLE
[oatpp] upgrade to 1.1.0


### PR DESCRIPTION
**Pull request by SSE4**
[oatpp] upgrade to 1.1.0
NOTE: this is automated commit created by conan-bump32!
command line: C:\bincrafters\conan-bump32\conan-bump32.py -p oatpp -v 1.1.0 -c 1983
closes: https://github.com/conan-io/conan-center-index/issues/1983

### CODE REVIEW

**Comment by lganzzzo** [comment]
Hey guys,

Please update the package test. The updated package test file you can find here - https://github.com/oatpp/oatpp/blob/master/test/oatpp/parser/json/mapping/DeserializerTest.cpp

Since `oatpp 1.1.0` introduces breaking changes the old file won't compile.

**Comment by jgsogo** [comment]
@SSE4 Looks like this PR requires a change 😉

**Comment by Alberto-Izquierdo** [comment]
@SSE4 are you still working on this? Is it fine if I open a new PR with the necessary changes?

**Comment by SSE4** [comment]
@Alberto-Izquierdo feel free to open new PR. this one is automated PR opened by bot. right now, bot can only update **config.yml** and **conandata.yml**. it would be hard to teach him to apply patches, so go ahead.

**Pull request closed without merging**
