### PR TITLE
libcpuid: add version 0.6.1 and support conan v2

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **libcpuid/***

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — DISMISSED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
Just restarted this job now. It failed internally again ...

**Comment by prince-chrismc** [comment]
It failed to post the update `logs/pr/13358/4-configs/windows-visual_studio/libcpuid/0.5.1//summary.json` again 😖

**Comment by prince-chrismc** [comment]
You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁

**Comment by uilianries** [comment]
I just restarted it again. Let's hope it passes now.

**Comment by prince-chrismc** [comment]
MacOS are done but still pending 😖

**Comment by prince-chrismc** [comment]
I clicked the wrong button sorry

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — DISMISSED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by uilianries** [comment]
Just re-re-re-triggered again. I start to think that this PR is cursed for some reason on Jenkins. Maybe opening a new entire PR (a copy of this one) could work.

**Review by uilianries — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Exact same failure 

...


Please open a new PR 🤞 that will work. Just please tag us and link to this one so we can watch it

**Comment by toge** [comment]
@uilianries  @prince-chrismc 
I see.
I recreate PR.

**Comment by toge** [comment]
I created new PR.
https://github.com/conan-io/conan-center-index/pull/13764

**Pull request closed without merging**
