### PR TITLE
[libffi] conan v2 ready

### PR DESCRIPTION
**Pull request by jellespijker**
Specify library name and version:  **libffi/x.x.x**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jellespijker** [comment]
Depended on #12898 for the: `env.define("AR", f"{unix_path(self, self.conf.get('tools.automake:ar-lib'))} lib")` statement

**Comment by jellespijker** [comment]
Closing and reopening to trigger CI/CT again, due to an unexpected failure

**Comment by uilianries** [comment]
@jellespijker The CI is more busy than usual due boost and Qt builds. Your PR will take more time to be built. In case an unexpected error occur, the CI will restart your PR automatically. Please, avoid closing/opening for now, because every time you do it, your PR goes to the last position in the build queue. Sorry for the delay

**Comment by jellespijker** [comment]
Thx for lettinge know. I will refrain myself from pushing any random buttons 😉

**Comment by uilianries** [comment]
@jellespijker as extra information, the check `continuous-integration/jenkins/pr-merge` is what matters. If it's `Pending — This commit is being built`, means that your PR is running on CI. Other checks (except for GH linters and CLA), they are updated only after `jenkins/pr-merge` result. It's a bit confusing, because GH caches the last build result and we can't remove it, neither put `jenkins/pr-merge` on the top.

**Comment by jellespijker** [comment]
Failing on Windows due to https://github.com/conan-io/conan/issues/11980 with a proposed fix for Conan here: https://github.com/conan-io/conan/pull/11981

```
"C:\J\w\prod\BuildSingleReference@2\.conan\data\libffi\3.2.1\_\_\build\b2b69efcc79a149e0bc765fb12ba0278d52fc260\build-debug\conan\conanbuild.bat" && "C:\J\w\prod\BuildSingleReference@2\.conan\data\libffi\3.2.1\_\_\build\b2b69efcc79a149e0bc765fb12ba0278d52fc260\build-debug\conan\msys2_mode.bat" && C:\J\w\prod\BuildSingleReference@2/s\9dc46d\1\bin\msys64\usr\bin\bash.exe -c ^". \^"C:\J\w\prod\BuildSingleReference@2\.conan\data\libffi\3.2.1\_\_\build\b2b69efcc79a149e0bc765fb12ba0278d52fc260\build-debug\conan\conanbuild.sh\^" ^&^& \^"/c/j/w/prod/buildsinglereference@2/.conan/data/libffi/3.2.1/_/_/build/b2b69efcc79a149e0bc765fb12ba0278d52fc260/libffi/configure\^" --disable-shared --enable-static --prefix=/ --bindir=${prefix}/bin --sbindir=${prefix}/bin --libdir=${prefix}/lib --includedir=${prefix}/include --oldincludedir=${prefix}/include --enable-debug=yes --datarootdir=${prefix}/res --enable-builddir=no --enable-docs=no --build=x86_64-win64-mingw64 --host=x86_64-win64-mingw64 ^"
-----------------
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.17
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Capturing current environment in C:\J\w\prod\BuildSingleReference@2\.conan\data\libffi\3.2.1\_\_\build\b2b69efcc79a149e0bc765fb12ba0278d52fc260\build-debug\conan\deactivate_msys2_mode.bat
Configuring environment variables
Capturing current environment in C:\J\w\prod\BuildSingleReference@2\.conan\data\libffi\3.2.1\_\_\build\b2b69efcc79a149e0bc765fb12ba0278d52fc260\build-debug\conan\deactivate_conanautotoolstoolchain.sh
Configuring environment variables
Capturing current environment in C:\J\w\prod\BuildSingleReference@2\.conan\data\libffi\3.2.1\_\_\build\b2b69efcc79a149e0bc765fb12ba0278d52fc260\build-debug\conan\deactivate_conanbuildenv-debug-x86_64.sh
Configuring environment variables
checking build system type... x86_64-win64-mingw64
checking host system type... x86_64-win64-mingw64
checking target system type... x86_64-win64-mingw64
checking for gsed... sed
checking for a BSD-compatible install... /c/j/w/prod/buildsinglereference@2/.conan/data/libffi/3.2.1/_/_/build/b2b69efcc79a149e0bc765fb12ba0278d52fc260/libffi/install-sh
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /c/j/w/prod/buildsinglereference@2/s/9dc46d/1/bin/msys64/usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for x86_64-win64-mingw64-gcc... /c/j/w/prod/buildsinglereference@2/.conan/data/libffi/3.2.1/_/_/build/b2b69efcc79a149e0bc765fb12ba0278d52fc260/libffi/msvcc.sh -m64
checking whether the C compiler works... no
libffi/3.2.1: 
configure: WARNING: unrecognized options: --enable-docs
configure: error: in `/c/J/w/prod/BuildSingleReference@2/.conan/data/libffi/3.2.1/_/_/build/b2b69efcc79a149e0bc765fb12ba0278d52fc260/build-debug':
configure: error: C compiler cannot create executables
See `config.log' for more details
libffi/3.2.1: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
libffi/3.2.1: ERROR: Package 'b2b69efcc79a149e0bc765fb12ba0278d52fc260' build failed
libffi/3.2.1: WARN: Build folder C:\J\w\prod\BuildSingleReference@2\.conan\data\libffi\3.2.1\_\_\build\b2b69efcc79a149e0bc765fb12ba0278d52fc260\build-debug
ERROR: libffi/3.2.1: Error in build() method, line 170
	autotools.configure()
	ConanException: Error 77 while executing "/c/j/w/prod/buildsinglereference@2/.conan/data/libffi/3.2.1/_/_/build/b2b69efcc79a149e0bc765fb12ba0278d52fc260/libffi/configure" --disable-shared --enable-static --prefix=/ --bindir=${prefix}/bin --sbindir=${prefix}/bin --libdir=${prefix}/lib --includedir=${prefix}/include --oldincludedir=${prefix}/include --enable-debug=yes --datarootdir=${prefix}/res --enable-builddir=no --enable-docs=no --build=x86_64-win64-mingw64 --host=x86_64-win64-mingw64 
```

Notice the: `bash.exe -c ^". \^"C:\J\w\prod\BuildSingleReference@2\.conan\data\libffi\3.2.1\_\_\build\b2b69efcc79a149e0bc765fb12ba0278d52fc260\build-debug\conan\conanbuild.sh\^" ^&^& ` Windows path after the bash command

**Pull request closed without merging**
