### PR TITLE
[libjpeg] Update sha256 for 9e

### LINKED ISSUE #13417: [package] libjpeg/9d: Can't build on windows (hash mismatch)
### Description

Whenever I try to build libjpeg on windows I get an error about a failed sha256 signature for 'jpehsrc.v9d.tar.gz' file.

### Package and Environment Details

* Package Name/Version: **libjpeg/9d**
* Operating System+version: **Windows 10**
* Compiler+version: **Visual Studio 16 2019**
* Conan version: **conan 1.53.0**
* Python version: **Python 3.9.5**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
[build_requires]
[env]

### Steps to reproduce

conan install libjpeg/9d@ -s build_type=Release -r conancenter --build libjpeg

### Logs

<details><summary>Click to expand log</summary>

```
> conan install libjpeg/9d@ -s build_type=Release -r conancenter --build libjpeg -pr release
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
[build_requires]
[env]

libjpeg/9d: Forced build from source
Installing package: libjpeg/9d
Requirements
    libjpeg/9d from 'artifactory' - Cache
Packages
    libjpeg/9d:3fb49604f9c2f729b85ba3115852006824e72cab - Build

Installing (downloading, building) binaries...
libjpeg/9d: WARN: Trying to remove corrupted source folder
libjpeg/9d: WARN: This can take a while for big packages
libjpeg/9d: Configuring sources in C:\Users\saphi\.conan\data\libjpeg\9d\_\_\source
Downloading jpegsrc.v9d.tar.gz completed [1006.75k]
ERROR: libjpeg/9d: Error in source() method, line 41
        tools.get(**self.conan_data["sources"][self.version])
        ConanException: sha256 signature failed for 'jpegsrc.v9d.tar.gz' file.
 Provided signature: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee
 Computed signature: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a
```

</details>

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **libjpeg**

This PR continues https://github.com/conan-io/conan-center-index/pull/15045 and it's related to #4151

closes #13417

/cc @arekmula @mejdys @Wuqiqi123

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — DISMISSED** [review]

**Comment by prince-chrismc** [comment]
Dont forget to label these pretty please

**Review by prince-chrismc — DISMISSED** [review]

**Comment by uilianries** [comment]
@prince-chrismc thank you for labeling, totally forgot it, sorry!

**Review by arekmula — APPROVED** [review]

**Review by arekmula — DISMISSED** [review]
Thank you very much!

**Review by SpaceIm — DISMISSED** [review]

**Review by MartinDelille — APPROVED** [review]

**Comment by prince-chrismc** [comment]
CCI master build is stuck :/

**Comment by prince-chrismc** [comment]
Just saw the `9e` failing myself :)

**Comment by prince-chrismc** [comment]
Going to let CI error out so we dont see this merge :)

**Comment by prince-chrismc** [comment]
Actually I just used my permissions, I forget I have those 🙃

**Review by jwillikers — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
c3i is currently working on build again 😕

**Comment by prince-chrismc** [comment]
still building.... 😠

**Comment by henryborchers** [comment]
I'm still getting...
```
Provided signature: 5d5349c3aacc978dfcbde11f7904d2965395261dd818ce21c15806f736b8911e  
Computed signature: 4077d6a6a75aeb01884f708919d25934c93305e49f7e3f36db9129320e6f4f3d
```
How long should this take before this is reflected in the https://center.conan.io remote?

**Comment by prince-chrismc** [comment]
You need to update your recipe, if you are not using revisions you can empty the cache and install it again

**Comment by henryborchers** [comment]
I tried with a fresh os inside a docker container with no existing cache and still the same effect.

**Comment by prince-chrismc** [comment]
It's not just you 🤔 

```
libjpeg/9e: Configuring sources in /Users/christopherm/.conan/data/libjpeg/9e/_/_/source/src
Downloading jpegsrc.v9e.tar.gz:   0%|          | 0.00/1.00M [00:00<?, ?B/s]libjpDownloading jpegsrc.v9e.tar.gz:  39%|###9      | 400k/1.00M [00:00<00:00, 2.59MB                                                                                Downloading jpegsrc.v9e.tar.gz completed [1022.40k]                                      libjpeg/9e:
ERROR: libjpeg/9e: Error in source() method, line 65
	get(self, **self.conan_data["sources"][self.version],
	ConanException: sha256 signature failed for 'jpegsrc.v9e.tar.gz' file.
 Provided signature: 5d5349c3aacc978dfcbde11f7904d2965395261dd818ce21c15806f736b8911e
 Computed signature: 4077d6a6a75aeb01884f708919d25934c93305e49f7e3f36db9129320e6f4f3d
```

Usually its faster then that maybe the backend got word it's a holiday and took today off

**Comment by henryborchers** [comment]
Ugh.. I got super excited to get this working again.

**Comment by henryborchers** [comment]
This was merged 8 hours ago. How long should this take before it's available on the backend?

**Pull request merged**
