### PR TITLE
cpp-httplib: use version range for openssl

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by Linux13524** [comment]
Hi @SpaceIm. Are those changes expected to still also work with Conan v1? The documentation says the following:

> There are some packages that do not follow semver. A popular one would be the OpenSSL package with versions as 1.0.2n. They cannot be used with version-ranges. To require such packages you always have to use explicit versions (without brackets).

We just noticed this as we got an error in our pipeline:

```
ERROR: Version range '>=1.1 <4' from requirement 'openssl/[>=1.1 <4]' required by 'cpp-httplib/0.11.1' could not be resolved in local cache
```

**Comment by Linux13524** [comment]
> https://github.com/conan-io/conan-center-index/blob/746eeba73375f0e1815c2c27328d22dd4f1ca49d/docs/adding_packages/dependencies.md#version-ranges does not say that

It actually links to the page that says that with "[documentation here](https://docs.conan.io/1/versioning/version_ranges.html)" 😉

**Comment by prince-chrismc** [comment]
It picks 3 from my remote 🤔 

```
(conan1)  christopherm@christopherm-mac  /tmp/1verra/conan1  ./bin/conan search openssl
Existing package recipes:

openssl/1.0.2u
openssl/1.1.0l
openssl/1.1.1n
openssl/1.1.1o
openssl/1.1.1q
openssl/1.1.1q@ts/test_no_md2
openssl/1.1.1s
openssl/1.1.1t
openssl/3.0.5
(conan1)  christopherm@christopherm-mac  /tmp/1verra/conan1  conan remove open
ssl/3.0.5@
(conan1)  christopherm@christopherm-mac  /tmp/1verra/conan1  ./bin/conan remove openssl/3.0.5@
Are you sure you want to delete from 'openssl/3.0.5' (yes/no): yes
(conan1)  christopherm@christopherm-mac  /tmp/1verra/conan1  ./bin/conan install cpp-httplib/0.12.1@ -o with_openssl=True -b missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=14
os=Macos
os_build=Macos
[options]
with_openssl=True
[build_requires]
[env]

openssl/3.1.0: Not found in local cache, looking in remotes...
openssl/3.1.0: Trying with 'conancenter'...
WARN: Hook 'conan-center.py' not found in /Users/christopherm/.conan/hooks folder. Please remove hook from conan.conf or include it inside the hooks folder.
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [29.05k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
openssl/3.1.0: Downloaded recipe revision 25925a18588e030e406a15da96c4d32b
Version ranges solved
    openssl/* versions found in 'conancenter' remote
    Version range '>=1.1 <4' required by 'cpp-httplib/0.12.1' resolved to 'openssl/3.1.0' in remote 'conancenter'

Installing package: cpp-httplib/0.12.1
Requirements
    cpp-httplib/0.12.1 from 'conancenter' - Cache
    openssl/3.1.0 from 'conancenter' - Downloaded
    zlib/1.2.13 from 'conancenter' - Cache
Packages
    cpp-httplib/0.12.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    openssl/3.1.0:cbc2b0e6ce2f761a978b5595914e39ab280ee8a5 - Build
    zlib/1.2.13:6841fe8f0f22f6fa260da36a43a94ab525c7ed8d - Cache

Installing (downloading, building) binaries...
zlib/1.2.13: Already installed!
openssl/3.1.0: Configuring sources in /Users/christopherm/.
```

**Comment by Linux13524** [comment]
I was able to reproduce it again:

This works fine:
```
> conan search openssl                                                  
There are no packages matching the 'openssl' pattern
> conan install cpp-httplib/0.12.1@ -o with_openssl=True --build missing
...
Version ranges solved
    openssl/* versions found in 'conancenter' remote
    Version range '>=1.1 <4' required by 'cpp-httplib/0.12.1' resolved to 'openssl/3.1.0' in remote 'conancenter'

Installing package: cpp-httplib/0.12.1
Requirements
    cpp-httplib/0.12.1 from 'conancenter' - Cache
    openssl/3.1.0 from 'conancenter' - Downloaded
    zlib/1.2.13 from 'conancenter' - Cache
Packages
    cpp-httplib/0.12.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    openssl/3.1.0:2c9e8b314c0851f3c4888c0d94e674a5d31056fe - Build
    zlib/1.2.13:19729b9559f3ae196cad45cb2b97468ccb75dcd1 - Cache

Installing (downloading, building) binaries...
zlib/1.2.13: Already installed!
openssl/3.1.0: Configuring sources in /home/lkloeckner/.conan/data/openssl/3.1.0/_/_/source/src
...
```

But if I have `openssl/1.1.1n` in a remote other than CCI I get the error:

```
> conan install openssl/1.1.1n@ --build openssl 
...
> conan upload -r artifactory openssl/1.1.1n@
> conan search -r artifactory openssl                                   
Existing package recipes:

openssl/1.1.1n
> conan install cpp-httplib/0.12.1@ -o with_openssl=True --build missing
...
ERROR: Version range '>=1.1 <4' from requirement 'openssl/[>=1.1 <4]' required by 'cpp-httplib/0.12.1' could not be resolved in remote 'artifactory'
```

So I guess the problem is that:
1. `artifactory` is set before CCI and
2. `1.1.1n` is not compatible to `[>=1.1 <4]` and
3.  `3.1.0` or any other compatible version is not existing in `artifactory`

**Comment by prince-chrismc** [comment]
Ahh, i only looked at 2.0 docs... I asked and the 1.x is more strict and wont resolve to 1.1.x -- but it should work for picking 3.x with Conan 1.59


Do you have conflicts that could be causing this?

**Comment by Linux13524** [comment]
No conflicts. Only `cpp-httplib` depends on it.

**Comment by prince-chrismc** [comment]
If should look in the remotes for a higher version, but this is normal that the 1.x client does not pick a 1.1 version, you can try using overrides to pick a lower one 

```sh
$ conan install cpp-httplib/0.12.1@ -o with_openssl=True -b missing --require-override openssl/1.1.1t@
WARN: cpp-httplib/0.12.1: requirement openssl/[>=1.1 <4] overridden by your conanfile to openssl/1.1.1t
Installing package: cpp-httplib/0.12.1
Requirements
    cpp-httplib/0.12.1 from 'conancenter' - Cache
    openssl/1.1.1t from 'conancenter' - Cache
Packages
    cpp-httplib/0.12.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    openssl/1.1.1t:6841fe8f0f22f6fa260da36a43a94ab525c7ed8d - Build

```

**Comment by prince-chrismc** [comment]
> But if I have openssl/1.1.1n in a remote other than CCI I get the error:

That makes sense... Conan will go back to the same remote and look for a version that is satisfactory for the requirements, if you dont have one, then it will fail.

**Comment by Linux13524** [comment]
The version override works as expected, yes, but is not very practical for us I think. So since we don't explicitly require OpenSSL 1.1.x I think the easiest workaround would be to just delete all 1.1.x references on Artifactory so the remote is not used for OpenSSL and instead 3.1.0 is picked from CCI, right?

**Comment by prince-chrismc** [comment]
Yes that is possible, assuming you do not need to reference openssl/1.1. in the future again.
Perhaps just upload a 3.x might be more viable?

It depends on your workflows, hard to say ❤️

**Comment by Linux13524** [comment]
> Perhaps just upload a 3.x might be more viable?

Yes, good point! We will do this.

Thanks a lot for your help! :slightly_smiling_face:

**Pull request merged**
