### PR TITLE
m4: use settings.os and setting.arch

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **m4/1.4.18**

Needed for cross building flex #1195 

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
@jgsogo re https://github.com/conan-io/conan-center-index/pull/1195#discussion_r426696258

Using the profile at the bottom, the following command works:
```sh
conan create . m4/1.4.18@ -pr:h default
```

But this command fails:
```sh
conan create . m4/1.4.18@ -pr:h default -pr:b default
```
The error is:
```
ERROR: m4/1.4.18: Error in build() method, line 75
	autotools = self._configure_autotools()
while calling '_configure_autotools', line 41
	self._autotools = AutoToolsBuildEnvironment(self, win_bash=tools.os_info.is_windows)
	AttributeError: 'NoneType' object has no attribute 'get_safe'
```
I've traced this to the following location:
https://github.com/conan-io/conan/blob/7f0390c69e48686b236f748d906f9a95b817069a/conans/client/tools/oss.py#L579


**profile**
```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by jgsogo** [comment]
The error is related to this issue: https://github.com/conan-io/conan/issues/7025 which will be fixed in `1.25.2` (PR already merged)

**Comment by madebr** [comment]
Thanks @jgsogo 
I'll continue the flex adventure after the next conan release.

**Comment by madebr** [comment]
@jgsogo 
Ok, I went ahead and checked out conans' `release/1.25` branch.
This indeed fixes the my earlier problem (thanks!!) but introduces another.
`test_package` fails because it cannot find the path of `m4`.

The following command fails:
```sh
conan test test_package/  m4/1.4.18@ -pr:h default -pr:b default
```

The output is:
```
ERROR: m4/1.4.18 (test package): Error in test() method, line 25
	m4_bin = self.deps_user_info["m4"].M4
	KeyError: 'M4'
```

So it appears `user_info` info is not passed along.

**Comment by jgsogo** [comment]
Hi, @madebr 

New xbuild model doesn't propagate `user_info` on purpose, we were looking for further evidence of this was needed and it is in this new and experimental features that are opt-in were we can introduce this breaking changes and wait for feedback about the community and use cases. If needed, we can introduce it again, it is just adding one line in the sources.

For this recipe, I would expect `m4` executable to be available in the PATH, [here](https://github.com/conan-io/conan/blob/7f0390c69e48686b236f748d906f9a95b817069a/conans/client/installer.py#L523) you can see the logic:

 * Before (without a `build` profile) the information was being propagated _in parallel_, for each dependency the information was added to the corresponding `deps_xxx_info` dictionary:

   ```
   conan_file.deps_user_info[n.ref.name] = n.conanfile.user_info
   conan_file.deps_cpp_info.update(n.conanfile._conan_dep_cpp_info, n.ref.name)
   conan_file.deps_env_info.update(n.conanfile.env_info, n.ref.name)
   ```

 * With the new model we are changing that:

   + packages in the `host` context (POV of the node we are computing) propagates only the `cpp_info`:

      ```
      conan_file.deps_cpp_info.update(n.conanfile._conan_dep_cpp_info, n.ref.name)
      ```

   + while packages in the `build` context propagates information only to the environment: the actual environment variables they define, but also the information from `cpp_info` will be propagated to the some special environment variables:

      ```
      env_info = EnvInfo()
      env_info._values_ = n.conanfile.env_info._values_.copy()
      # Add cpp_info.bin_paths/lib_paths to env_info (it is needed for runtime)
      env_info.DYLD_LIBRARY_PATH.extend(n.conanfile._conan_dep_cpp_info.lib_paths)
                    
      env_info.DYLD_LIBRARY_PATH.extend(n.conanfile._conan_dep_cpp_info.framework_paths)
      env_info.LD_LIBRARY_PATH.extend(n.conanfile._conan_dep_cpp_info.lib_paths)
      env_info.PATH.extend(n.conanfile._conan_dep_cpp_info.bin_paths)
      conan_file.deps_env_info.update(env_info, n.ref.name)
      ```

Hope it makes sense. In this recipe, using the new model, we could get rid of the `M4` variable defined in the `env_info` and into the `user_info` if we were going to use this recipe as a build_require from the `test_package`, but that is not the case, we are using this recipe as a requirement in the `host` context... and here it is the problem: **we need the environment as if we were using a `virtualenv` generator** for this `test()` function to work.

**Comment by madebr** [comment]
> New xbuild model doesn't propagate `user_info` on purpose, we were looking for further evidence of this was needed and it is in this new and experimental features that are opt-in were we can introduce this breaking changes and wait for feedback about the community and use cases. If needed, we can introduce it again, it is just adding one line in the sources.

So `user_info` becomes useless when using xbuild?
The `automake` recipe uses it for consumers that want to wrap the Visual Studio compiler (`ar_lib` and `compiler`). This is useful when automake is used as a build requirement.

> For this recipe, I would expect `m4` executable to be available in the PATH, [here](https://github.com/conan-io/conan/blob/7f0390c69e48686b236f748d906f9a95b817069a/conans/client/installer.py#L523) you can see the logic:

I added `M4` to `user_info` to find out why the `M4` environment variable was not passed. I have removed it.

> Hope it makes sense. In this recipe, using the new model, we could get rid of the `M4` variable defined in the `env_info` and into the `user_info` if we were going to use this recipe as a build_require from the `test_package`, but that is not the case, we are using this recipe as a requirement in the `host` context... and here it is the problem: **we need the environment as if we were using a `virtualenv` generator** for this `test()` function to work.

It makes sense. It's the details that surprise me :smile: 

The `M4` environment variable is used by a lot of scripts to override the m4 interpreter,
so it is really required. I have added a comment to avoid removing it.
e.g. autoconf/automake/libtool embed the path of the m4 interpreter in the generated sources

**Pull request merged**
