### PR TITLE
Fix Incorrect Include Directory Structure in harfbuzz Conan Recipe #20158

### PR DESCRIPTION
**Pull request by tuduongquyet**
Specify library name and version:  **harfbuzz/8.1.1**

Resolving #20158

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — CHANGES_REQUESTED** [review]
on my machine, (ubuntu), I have:
```
$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/harfbuzz.pc
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/x86_64-linux-gnu
includedir=/usr/include

Name: harfbuzz
Description: HarfBuzz text shaping library
Version: 2.7.4

Libs: -L${libdir} -lharfbuzz
Libs.private: -lm
Requires.private: glib-2.0 >= 2.19.1 freetype2 >= 12.0.6 graphite2 >= 1.2.0
Cflags: -I${includedir}/harfbuzz
```
so the include path which is passed is `/usr/include/harfbuzz`, which contains all the hb*.h files

Also, `/usr/lib/x86_64-linux-gnu/cmake/harfbuzz/harfbuzz-config.cmake` has:
```
set_target_properties(harfbuzz::harfbuzz PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_harfbuzz_prefix}/${_harfbuzz_includedir}/harfbuzz"
  ...)
```

Also also,  `https://github.com/harfbuzz/harfbuzz/blob/main/test/fuzzing/hb-draw-fuzzer.cc#L4` does not specify `harfbuzz/` when including.

also also also, https://harfbuzz.github.io/a-simple-shaping-example.html does not specify `harfbuzz.` when including either

Where does your assumption that it should be included as `#include "harfbuzz/hb*.h` comes from ?

**Comment by SpaceIm** [comment]
That's incorrect: I don't think so: https://github.com/harfbuzz/harfbuzz/blob/c8c97864e8c810068123ef62947be13675df54c2/CMakeLists.txt#L452-L454

These lines clearly say that CMake config files should expose headers under harfbuzz folder directly. You are breaking recipe actually here, while your incorrect include convention was also supported actually, I don't know how you consume this recipe.

**Comment by tuduongquyet** [comment]
I'm currently working on a project that involves using harfbuzz, and in the codebase, we have references to harfbuzz/hb.h. I also conducted a search on GitHub and found numerous instances where harfbuzz/hb.h is used in other projects as well. This seems to be a common convention when working with harfbuzz.

Furthermore, it's a widely followed practice to structure include paths with the format <folder>/<header> when dealing with packages. This helps maintain clarity and organization in larger codebases.

However, I should have also considered the specific structure of the harfbuzz Debian package, which utilizes Cflags: -I${includedir}/harfbuzz. In this case, the package itself defines the include path as /usr/include/harfbuzz, and it's acceptable to directly include headers without the harfbuzz/ prefix due to this packaging configuration.

So, while #include "harfbuzz/hb.h" is a common convention, the Debian package configuration you mentioned allows for a simplified #include "hb.h" when working within the context of an Ubuntu system with the harfbuzz package installed.

So I think we should keep the same.
I will close the issue and the PR.

Thank you for reviewing. @ericLemanissier

**Comment by tuduongquyet** [comment]
Thank you @SpaceIm

**Pull request closed without merging**
