### PR TITLE
Approvaltests.cpp.8.9.1, 8.9.2, 9.00 and 10.00

### PR DESCRIPTION
**Pull request by claremacrae**
Specify library name and version:  **approvaltests.cpp/8.9.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by claremacrae** [comment]
Hi, just to let you know we are about to add a few more quick releases to this PR, so I'll let you know when it's ready for review... Thanks.

**Comment by uilianries** [comment]
Hi @claremacrae ! I just converted this PR to a draft, so we can avoid any precipitated merge.

**Comment by claremacrae** [comment]
Thanks @uilianries - what do I need to do later to un-draft it?

**Comment by uilianries** [comment]
@claremacrae Yes, click on "Ready for Review":

**Comment by claremacrae** [comment]
Thanks Uilian - We've added our next release, and are now getting "This commit cannot be built".

Is that because it's a Draft now?

**Comment by uilianries** [comment]
@claremacrae that was an internal error. It's okay adding new versions at same PR, it's allowed.

Now your current error is:

> Scanning dependencies of target test_package_doctest
[ 62%] Building CXX object CMakeFiles/test_package_doctest.dir/test_doctest.cpp.o
/tmp/c3ipr/co_pr_1821_3_7_0/recipes/approvaltests.cpp/all/test_package/test_boosttest.cpp: In member function ‘void Suite::TestCase::test_method()’:
/tmp/c3ipr/co_pr_1821_3_7_0/recipes/approvaltests.cpp/all/test_package/test_boosttest.cpp:16:9: error: ‘Options’ is not a member of ‘ApprovalTests’
         ApprovalTests::Options(ApprovalTests::QuietReporter()));

It seems like ApprovalTests::Options doesn't exist for 8.6.0. Is that correct?

If yes, you could add #if condition to skip, based on ApprovalTests version, Or, create a separated .cpp test file for newer version.

**Comment by claremacrae** [comment]
Thanks @uilianries - much appreciated. 

I think I can see how to rework the test so a single set of code will work with all versions of our library. I’ll try that tomorrow.

**Comment by claremacrae** [comment]
And yes, you are correct that Options didn’t exist in older versions.

**Comment by uilianries** [comment]
Hi @claremacrae I've removed the draft, because I see 9.0.0 is the latest version available and this PR looks good. Tell if you want to add more versions.

**Comment by claremacrae** [comment]
Hi @uilianries thanks - we have one more release to add, and then we will be good to go...

(I can't see the UI to change this to back to "work in progress" at the moment...)

**Comment by claremacrae** [comment]
Hi @uilianries - we are now done... we improved the tests along the way....

**Comment by claremacrae** [comment]
The reason for the large number of releases was that this is a carefully planned series of small steps in making some major deprecations to our code - so users can upgrade in steps if they wish.

**Comment by uilianries** [comment]
Thanks a lot @claremacrae !

**Pull request merged**
