### PR TITLE
[boost] Fix #11988

### PR DESCRIPTION
**Pull request by garethsb**
I tried this fix for https://github.com/conan-io/conan-center-index/pull/11988#issuecomment-1218367469
Could the underlying cause be a confusing translation between `None` vs `"None"` in options?

### CODE REVIEW

**Comment by uilianries** [comment]
@garethsb Thank your for your hotfix! Please, update the import according to https://github.com/conan-io/conan-center-index/pull/12314/files#diff-cc14160728d1ad321c1444ffad82615139181e681f4acb7dfd045a005cc8bd66R8. So the linter will pass.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by Nekto89 — APPROVED** [review]
I should have checked locally after changing "default" to None. I "love" Python.

**Review by vasily-v-ryabov — APPROVED** [review]
We need it quickly merged today. Thanks!

**Review by SSE4 — APPROVED** [review]

**Review by pflynn-virtru — APPROVED** [review]

**Review by patmantru — APPROVED** [review]
Thank you!

**Review by DonOregano — APPROVED** [review]

**Pull request merged**
