### PR TITLE
nss/3.83

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **nss/3.83**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@jgsogo Why didn't the CI try to build nss/3.83 with gcc 11 cf https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/13106/1-linux-gcc/nss/3.83//summary.json ?
I think all nss's requirement have gcc11 binaries, so nss should be able to move to the new epoch. Is is a caching issue again ?

**Comment by jgsogo** [comment]
In the logs, I can see some requirements using epoch `0` (default one): `nspr`, `7zip`, `lzma_sdk`, `mozilla-build`

**Comment by ericLemanissier** [comment]
woopsie, I must have confused clang 11 for gcc11.  I'll migrate lzma_sdk, then 7zip, then mozilla-build, and finally I'll make a PR touching nspr.

**Comment by ericLemanissier** [comment]
blocked by:

- https://github.com/conan-io/conan-center-index/pull/13107

**Review by uilianries — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
