### PR TITLE
dbus: switch to autotools

### PR DESCRIPTION
**Pull request by ericLemanissier**
this is what is recommended upstream for non windows
it should fix FreeBSD

see comment on https://gitlab.freedesktop.org/dbus/dbus/-/issues/324#note_746339:
`The Autotools build system is the recommended one for Unixish operating systems`

Specify library name and version:  **dbus/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by dmn-star** [comment]
Why not just fix CMake build? Autotools should be deprecated anywhere. :-)

**Comment by ericLemanissier** [comment]
Don't hesitate to fix the cmake build if you want to. I'm following upstream recommendation in the meantime.
FreeBSD just passed on https://github.com/ericLemanissier/conan-center-index/runs/1656613048?check_suite_focus=true

**Review by uilianries — APPROVED** [review]
LGTM

**Review by prince-chrismc — APPROVED** [review]
🚀

**Comment by dmn-star** [comment]
> Don't hesitate to fix the cmake build if you want to. I'm following upstream recommendation in the meantime.
> FreeBSD just passed on https://github.com/ericLemanissier/conan-center-index/runs/1656613048?check_suite_focus=true

Any recipe that uses only CMake is a big advantage for all Windows Conan users regardless of any "recommendations". But OPP.

**Review by theirix — APPROVED** [review]
Hope nobody used removed `enable_assert` and `enable_checks` options.

**Pull request merged**
