### PR TITLE
import is used which is only available from conan >= 1.46.0

### LINKED ISSUE #11955: [package] boost/ALL: ImportError in conanfile.py
### Package and Environment Details

* Package Name/Version: **boost/all**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 9**
* Conan version: **conan 1.43.0**
* Python version: **Python 3.8**

### Conan profile

_No response_

### Steps to reproduce

Install any boost version with conan==1.43.0 and an `ImportError` is raised:
```
#14 2.116   File "/root/.conan/data/boost/1.71.0/_/_/export/conanfile.py", line 1, in <module>
#14 2.116     from conan.tools.build import cross_building
#14 2.116 ImportError: cannot import name 'cross_building' from 'conan.tools.build' (/usr/local/lib/python3.8/dist-packages/conan/tools/build/__init__.py)
```

seems like [a recent change](https://github.com/conan-io/conan-center-index/commit/abf40e34637400c5c3f625d230098bfaee39bc06#diff-cc14160728d1ad321c1444ffad82615139181e681f4acb7dfd045a005cc8bd66) to the `conanfile.py` introduced that. the conanfile.py says it's valid down until v1.43.0, however that import wasn't introduced until [1.43.4 or so](https://github.com/conan-io/conan/pull/10536/files#diff-74272a6f8877a3af1e97d287b5e9169050b4c836c436d7d3779cb6842dacef65).

### Logs

<details><summary>Click to expand log</summary>

</details>

### PR DESCRIPTION
**Pull request by nilsnolde**
Specify library name and version:  **boost/all**

fixes #11955 

in fact the import in question wasn't released until v1.46.x: https://github.com/conan-io/conan/blob/release/1.46/conan/tools/build/__init__.py

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
LGTM

**Review by jwillikers — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by nilsnolde** [comment]
more a philosophy question: in this simple case we could also have a conditional import e.g. 

```
try:  # >= 1.46.0
    from conan.tools.build import cross_building
except:
    from conans.tools import cross_building
```

is that smth you do generally, or you avoid version conditionals and just increase the min conan version?

**Review by SpaceIm — APPROVED** [review]

**Comment by uilianries** [comment]
> more a philosophy question: in this simple case we could also have a conditional import e.g.
> 
> ```python
> try:  # >= 1.46.0
>     from conan.tools.build import cross_building
> except:
>     from conans.tools import cross_building
> ```
> 
> is that smth you do generally, or you avoid version conditionals and just increase the min conan version?

@nilsnolde Conan client parses `required_conan_version` to validate which version is needed to execute a recipe. However, first we need to import Conan modules. So, the best approach is: 

People need to update their Conan client. 

Also, Conan Center Index expects it: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#submitting-a-package

**Comment by nilsnolde** [comment]
> However, first we need to import Conan modules.

right.. then bumping the min version won't prevent the recipe to fail with conan < 1.46.0 with the same `ImportError` (didn't try before). wouldn't a conditional import like the one above remove the need for bumping the min version at all and be generally a better fix?

btw, I [asked for access](https://github.com/conan-io/conan-center-index/issues/4#issuecomment-1199097495), should come soon I guess. does the ci job somehow schedule itself or I need to do smth after I got access?

**Comment by uilianries** [comment]
> right.. then bumping the min version won't prevent the recipe to fail with conan < 1.46.0 with the same `ImportError` (didn't try before). wouldn't a conditional import like the one above remove the need for bumping the min version at all and be generally a better fix?

No, because there are more features involved than only `cross_building`.

> btw, I https://github.com/conan-io/conan-center-index/issues/4#issuecomment-1199097495, should come soon I guess. does the ci job somehow schedule itself or I need to do smth after I got access?

The access request process is executed 3 times every week. A bot collects the new names, Conan team checks those new users, then approve (or not in case a suspicious profile). After that, the CI bot will re-run automatically all PRs which were waiting for the Access Request.

**Pull request merged**
