### PR TITLE
[docs] Apply python black formatter over recipe templates

### LINKED ISSUE #13289: [service] linter clean the cmake_package template
I started a new recipe from docs/package_templates/cmake_package

I noticed when the linters ran on my PR, that some autopep8 and pylint issues occurred.
The autopep8 issues were probably due to line wrapping at column 80.
the pylint issues were about bare-excepts

Ideally the package templates should be autopep8 and pylint clean from scratch.

### PR DESCRIPTION
**Pull request by uilianries**
closes #13289

- Using 120 chars as max line length

/cc @winterz

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
I personally don't think it looks/reads better... code is too long, and has too many lines instead of single, easy to read line

**Review by jwillikers — DISMISSED** [review]
Yes, thank you. Formatting consistency makes diffing that much easier and Black is nice and easy to use.

**Comment by uilianries** [comment]
I just updated to 120 chars.

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
we should write a pipeline for these and build them 🙈

**Pull request merged**
