### PR TITLE
quill: add version 4.3.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **quill/***

quill/4.3.0 becomes header only library.

https://github.com/odygrd/quill/compare/v3.9.0...v4.3.0

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
@RazielXYZ 
Thank you for your comment!
I missed it.
Fixed.

**Review by RazielXYZ — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
Hi @toge - I was going to ask you to split the recipe into two versions to simplify the logic, but I (correctly) guessed it would be quite tedious so I've done it myself to save you some time, let's see if this works :) Thanks a lot!

**Comment by toge** [comment]
@RubenRBS 
Thank you for the improvement!
I was wondering if I should create new recipes for 4.0.0 and you gave me a good direction.

For my recipes, you just need to direct me to the changes.
You are one of the key people in this project and your work time is obviously more valuable than mine.

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by odygrd** [comment]
Hello @toge,

Thank you so much for doing this! I was unsure how to update the recipe for the new version.

The main differences in version v4 are as follows:

- It is now a header-only library.
- The CMake option `QUILL_FMT_EXTERNAL` has been removed.
- The option `QUILL_DISABLE_POSITION_INDEPENDENT_CODE` is no longer relevant.

Thanks again!

**Review by jwillikers — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
