### PR TITLE
[boost] Add version 1.86.0

### PR DESCRIPTION
**Pull request by uilianries**
### Summary
Changes to recipe:  **boost/1.86.0**

#### Motivation

New Boost version 1.86.0 has been released and there is a related PR: #25030

#### Details

The version 1.86.0 brings updates related to required C++ standard. However, most of those components are not exposed as an option.

https://www.boost.org/users/history/version_1_86_0.html

- No new libraries.
- Boost CRC requires C++11
- Boost Format requires C++11
- Boost Graph requires C++14. This one has an option.
- Boost UUID requires C++11
- Boost Heap requires C++14
- Boost Lockfree requires C++14

closes #25030

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by Nekto89** [comment]
From release notes:
[Process](https://www.boost.org/libs/process/):
    Turned v2 into a compile library.

**Comment by uilianries** [comment]
@Nekto89 I'm not sure what you are saying. Could you please rephrase?

**Comment by Nekto89** [comment]
> @Nekto89 I'm not sure what you are saying. Could you please rephrase?

Boost.process can be compiled as library now and isn't header-only anymore so probably some adjustments should be made.

**Comment by uilianries** [comment]
> Boost.process can be compiled as library now and isn't header-only anymore so probably some adjustments should be made.

@Nekto89 Thank you for pointing it! I'll investigate it as well.

**Review by AbrilRBS — APPROVED** [review]

**Review by toge — APPROVED** [review]

**Pull request merged**
