### PR TITLE
gcc: model exported libraries, better mirrors, more specific license

### PR DESCRIPTION
**Pull request by valgur**
Continues the changes from #15128 to model the installed runtime libraries correctly. The compilers cannot be used reliably unless `self.requires("gcc/")` with `self.cpp_info.requires.append("gcc::gfortran")` is used in addition to `self.tool_requires("gcc/")`.

Set the `package_type` to `library` for the runtime libraries to be usable as `self.requires()`. See https://github.com/conan-io/conan/issues/15306 for more context.

The current URLs for the sources were extremely slow - 10 minutes to download 140 MB. Replaced the .tar.gz with tar.xz for 80 MB instead of 140 MB size and picked the fastest 2 mirrors out of 25 tested. Download takes less than 10 seconds now.

Made the license ID more specific by including the exception for runtimes:
https://spdx.org/licenses/GCC-exception-3.1.html
https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html

Requires #21153 for Conan 2.0 pipeline to pass.

### CODE REVIEW

**Comment by samuel-emrys** [comment]
The changes you've pulled in from my PR in https://github.com/conan-io/conan-center-index/pull/15128 exceed the scope of what you've defined for this PR. Given that there seems to be some reluctance to adopt the internal library model for the gcc recipe, my suggestion would be to remove these changes from this PR if you want it to be accepted.

**Comment by valgur** [comment]
> The changes you've pulled in from my PR in #15128 exceed the scope of what you've defined for this PR. Given that there seems to be some reluctance to adopt the internal library model for the gcc recipe, my suggestion would be to remove these changes from this PR if you want it to be accepted.

@samuel-emrys Yes, I actually care more about that change than the other minor ones, really.

`gfortran` is not really usable via a `self.tool_requires("gcc/")` unless `self.requires("gcc/")` with `self.cpp_info.requires.append("gcc::gfortran")` is also used. I've tried multiple approaches with `self.cpp_info.system_libs` and what not, and this is the only one that really works.

**Comment by jcar87** [comment]
Closing this, as per the reasons already expressed here: https://github.com/conan-io/conan-center-index/issues/15099#issuecomment-1782681777

Currently we don't have a package type that can correctly and comprehensively model libraries within a toolchain. In most circumstances, libraries within a toolchain like GCC don't need to be modelled: the compiler knows where to look for those libraries, and a "relocatable" gcc would know, as a fallback, where to look for libraries, or would already implicitly link them (e.g. like glibc, libstdc++, etc).

It is true that the `gcc` recipe in Conan center is unmaintained - at the moment we are not prioritising this because the vast majority of our users use a GCC provided by their system or SDK. If there are specific use cases that could be satisfied by an improved recipe, please open an issue where this can be discussed and other users can articulate their needs, and we will consider this in the future.

**Comment by valgur** [comment]
@jcar87 Thanks for looking into it. I agree with all of your points.

My real motivation in this PR was to get some kind of Fortran support going on CCI, which is required for quite a few numerical libraries. A full GCC toolchain with C/C++ support is more of a liability in that case anyway as it will interfere with the compiler configured in the profile. That's why I opened #23334. I invite you to take a closer look at it if you get a chance.

**Pull request closed without merging**
