### PR TITLE
xorg: fix centos

### PR DESCRIPTION
**Pull request by ericLemanissier**
add system packages to install

Specify library name and version:  **lib/1.0**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Maybe add a condition to install all those packages only when running centos ?

**Comment by SSE4** [comment]
should be more or less the same for other CentOS-like distros (Fedora, RHEL, Mandriva, SUSE, Orcale, etc.)

**Comment by ericLemanissier** [comment]
probably this one should not be merged before a decision on https://github.com/conan-io/conan-center-index/pull/2123 is taken

**Comment by daravi** [comment]
Just a reminder that `libdmx-devel` and `libFS-devel` are not available on CentOS 8 so in that case we probably should add `libdmx/1.1.4@bincrafters/stable` and `libfs/1.0.8@bincrafters/stable` as requirements.

**Comment by ericLemanissier** [comment]
libXi-devel is pulled by libXtst-devel and libXv-devel is pulled by libXvMC-devel so we should be good now

**Comment by uilianries** [comment]
I'm curious about that list, how could you be sure about those packages, like, are you checking the dependencies graph from a package, or is related to xorg when building something ?

**Comment by ericLemanissier** [comment]
These packages are the ones providing the .pc files used in https://github.com/conan-io/conan-center-index/blob/master/recipes/xorg/all/conanfile.py#L56-L62.
These .pc files are required in order to build qt with xcb support : https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/configure.json?h=5.15.0#n595
some are needed by [cairo](https://github.com/freedesktop/cairo/blob/master/configure.ac#L165) too or [pulseaudio](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/1fe37e6d4bd5b2d183244538b250dae82ea27d47/configure.ac#L631)

**Comment by ericLemanissier** [comment]
I merged this change in #2123

**Pull request closed without merging**
