### PR TITLE
libwebp: add version 1.3.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **libwebp/1.3.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Comment by SpaceIm** [comment]
libwebp 1.3.0 needs more love. shared libs are not relocatable anymore on macOS due to https://github.com/webmproject/libwebp/blob/v1.3.0/CMakeLists.txt#L104-L108

**Comment by paulharris** [comment]
@toge there is a problem with this PR,
1.3.0 split the SharpYuv* functions into a separate library: libsharpyuv.a
the webp libraries need the sharpyuv lib to link.

The new libwebp.pc file generated during the build (and then deleted by conan) looks like:
```
Name: libwebp
Description: Library for the WebP graphics format
Version: 1.3.0
Requires: libsharpyuv
Cflags: -I${includedir}
Libs: -L${libdir} -lwebp
Libs.private: -lm  -lpthread
```

**Comment by kwsp** [comment]
This patch breaks installing libwebp with conan 1.x

**Comment by prince-chrismc** [comment]
Could you provide more details? this was tested 2 months ago with Conan 1.x https://github.com/conan-io/conan-center-index/pull/15256#issuecomment-1382913155

**Pull request merged**
