### PR TITLE
Removing some unecessary settings

### PR DESCRIPTION
**Pull request by anagno**
Coming from question #3482 in the issues. Since Eigen is a header only library, the other settings are not necessary

Specify library name and version:  **Eigen/**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
I think these were added to make sure cmake detects the correct compiler toolchain.
On the other hand, `eigen` does not contain a `CMakeLists.txt` wrapper to check the compiler or uses the `cmake` generator, which is safer to do (imho).
Its cost is negligible.

**Comment by Croydon** [comment]
In the context of https://github.com/conan-io/conan-center-index/issues/3157 and what we decided to do for installer packages, it might be a lot easier to always have the full set of settings and remove on a per-recipe basis from the package ID, which is done here by `self.info.header_only()`

🤔

**Comment by SSE4** [comment]
I think it goes back to #1783

**Comment by anagno** [comment]
Because I got lost in the referenced issues, then we do nothing. ```self.info.header_only()``` is more than enough. The current suggestion for the header libraries is that we specify all the settings and then we use the self.info.header_only() to delete them. Right ? Should that be mentioned in the [documentation](https://docs.conan.io/en/latest/howtos/header_only.html)?

**Comment by SSE4** [comment]
@anagno I think yes, this is more or less common practice for CMake-based header-only projects: 
1. have all settings defined (os, arch, compiler, build_type)
2. clear settings in package_info

I believe we should add this to the FAQ, maybe also to the hooks (unsure).

why do we need them?
without specifying some settings, CMake may struggle to correctly generate the project or detect a compiler.
in the end, for consumer it's the same - you still get one package and on package id for all settings combinations, but it solves issues for many users.

**Pull request closed without merging**
