### PR TITLE
lzip: migrate to Conan v2

### PR DESCRIPTION
**Pull request by valgur**

### CODE REVIEW

**Comment by klausholstjacobsen** [comment]
Why modify cmake files in the recipe when building with autotools?

**Comment by valgur** [comment]
Closing temporarily to avoid unnecessary load on the CI. Will reopen when I'm actively working on the PR again.

**Comment by klausholstjacobsen** [comment]
I will try to ensure that my active PR (https://github.com/conan-io/conan-center-index/pull/18906) will contain whatever specific changes you have here. So hopefully after merging that one you will not have to reopen this one!

//Klaus

**Comment by valgur** [comment]
Closing in favor of #18906.

**Pull request closed without merging**
