### PR TITLE
actions: upgrade changed-files version

### PR DESCRIPTION
**Pull request by ericLemanissier**
set base_sha in consequence

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
As expected, several [commits](https://github.com/conan-io/conan-center-index/pull/13602/commits/20180700964495bb76efa997616eefff555ffca1) do not break the pipeline any more: https://github.com/conan-io/conan-center-index/actions/runs/3281588327/jobs/5403808099#step:6:19
`tj-actions/get-changed-files` properly identifies the yml change: https://github.com/conan-io/conan-center-index/actions/runs/3281588327/jobs/5403808099#step:5:105

Same after adding another [commit](https://github.com/conan-io/conan-center-index/pull/13602/commits/b6dac62b2ff7369cc4dcda06083642e9e7643797) with a conanfile.py error: https://github.com/conan-io/conan-center-index/actions/runs/3281628291/jobs/5403903404#step:8:19
`tj-actions/get-changed-files` properly identifies the conanfile change: https://github.com/conan-io/conan-center-index/actions/runs/3281628291/jobs/5403903404#step:4:87

**Comment by ericLemanissier** [comment]
ok, so a new problem appears: the diff is now computed vs the master at the time of the build, so we had some warnings for this PR `alac`, `aws-c-mqtt`, `emsdk` and `marisa` https://github.com/conan-io/conan-center-index/actions/runs/3287550320/jobs/5416844748
They disappeared when I merged upstream/master in this pr's branch, but it's pretty bad that solving a warning/error in the master creates the warning/error in all opened PR....

**Comment by ericLemanissier** [comment]
I reset the fetch depth to 2, but instead I defined the `base_sha` to `${{ github.event.pull_request.base.sha }}` (as in `Get all changed files using a different base SHA` in https://github.com/tj-actions/changed-files/blob/main/README.md), and all errors related to concurrent changed in master are now gone (see commit status of https://github.com/conan-io/conan-center-index/pull/13602/commits/267ccc08ca43382a220881f2558976528c879bf0)
I then added an error in a .yml file, which was properly detected, cf commit status of https://github.com/conan-io/conan-center-index/pull/13602/commits/79e8fb2c2d80fcc3250b94430c2ca0ead4d1eed4
Then an error in a conanfile, which was properly detected too, cf commit status of https://github.com/conan-io/conan-center-index/pull/13602/commits/908ed625c381b9dbe586749b53ea2f1204fde6d4
Finally, I fixed the two errors, and the status is green again, cf commit status of https://github.com/conan-io/conan-center-index/pull/13602/commits/3bf6dac3a7089bb6ef54380d7be200fdf0a9ba0d

I am confident that this is the proper fix

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Let's be slow since this got in very quickly last time and cause some distractions 😄 we often have PRs with more then 20 commits so that will probably need to be changed.

you should also be able to push 25 commits here to trigger it as well

**Comment by ericLemanissier** [comment]
The `20` fetch depth I'm talking about is `target_branch_fetch_depth`, so I think it applies to `master`, not to the branch being pulled.
It is used in https://github.com/tj-actions/changed-files/blob/27c18b1c64f5fe93f03c72b5a849c899089b9039/diff-sha.sh#L133, so it fetches `GITHUB_BASE_REF` wchich comes from [${{ github.base_ref }}](https://github.com/tj-actions/changed-files/blob/27c18b1c64f5fe93f03c72b5a849c899089b9039/action.yml#L161)

**Comment by prince-chrismc** [comment]
image

Should be good to test 👍

**Comment by ericLemanissier** [comment]
Sadly, I was not wrong. fetch-depth must be set to 0 to be sure to have the commit history up to the branch point between master and the PR.
Do you have other tests in mind @prince-chrismc @uilianries ?

**Comment by prince-chrismc** [comment]
I was worried about the time it would take given the size of the repo but it's reasonable

image

**Comment by prince-chrismc** [comment]
I am pretty content with this, great work

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
