### PR TITLE
Add libclang 13

### PR DESCRIPTION
**Pull request by intelligide**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericriff** [comment]
I know this is a draft, but I found it interesting since I was considering packaging the compilers we use to provide them as build requirements (now tool requirements).
Is there a reason why you're not building clang here?

**Comment by intelligide** [comment]
Clang is heavy to compile, it takes a lot of space and memory. My goal now is just to submit the libclang, and so I try to optimize as much as possible by avoiding unnecessary parts.

**Comment by ericriff** [comment]
I see. What's the use of `libclang` outside of `clang` itself? :thinking:

**Comment by intelligide** [comment]
The libclang parse and analyze C/C++ code. it can be useful to create tools like documentation generators or code generators.

**Comment by maksim-0** [comment]
That's exactly what I need. But I think this is not libclang. libclang is a C interface to clang (https://clang.llvm.org/doxygen/group__CINDEX.html, https://github.com/llvm/llvm-project/tree/main/clang/tools/libclang). And _this_ is just clang (https://github.com/llvm/llvm-project/tree/main/clang). 

@intelligide Do you plan to continue working on this?

**Comment by intelligide** [comment]
@maksim-0 tTis recipe builds the libclang (C and C++ library) and not the clang executables.

**Pull request closed without merging**
