### PR TITLE
xkbcommon: fix conflict with wayland

### PR DESCRIPTION
**Pull request by ericLemanissier**
since https://github.com/conan-io/conan-center-index/commit/3264e15a2117e10f4d286d033876d4bc800e47ff#diff-5c99ca1cb44d19a32c9f1373d8effc9125f8e1b094489ef02ee1cf755feb82f7R53

Specify library name and version:  **xkbcommon/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
blocks:
- https://github.com/conan-io/conan-center-index/pull/23597
- https://github.com/conan-io/conan-center-index/pull/23571

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8733193394/attempts/1)

**Review by RubenRBS — APPROVED** [review]

**Comment by mayeut** [comment]
depends on https://github.com/conan-io/conan-center-index/pull/23637

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8733193394/attempts/2)

**Review by jwillikers — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
