### PR TITLE
[hdf5] Bump dependencies and add missing versions

### PR DESCRIPTION
**Pull request by tbeu**
Specify library name and version:  **hdf5/1.12.1**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by tbeu** [comment]
@SpaceIm Why is it failing? Shall 1.10.5, 1.10.6 and 1.10.7 be removed?

**Comment by uilianries** [comment]
@tbeu Do you need those old versions? Otherwise, I suggest avoid them.

**Comment by SpaceIm** [comment]
@jgsogo 

hdf5 recipe raises if cross-built: https://github.com/conan-io/conan-center-index/blob/42be839cb3e3404b8f5e791960f6805102edb7c6/recipes/hdf5/all/conanfile.py#L81-L83

It has not been changed in this PR, but yet CI tries to build to macOS M1 (and fails): https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/10179/8-configs/macos-m1-clang/hdf5/1.12.1//summary.json

**Comment by jgsogo** [comment]
Triggering again after removing the cached packageIDs.... let's what happens now. Now it should compute INVALID_PACKAGE

**Comment by SSE4** [comment]
there are conflicts, please rebase

**Comment by paulharris** [comment]
I'm working on another HDF5 PR,
I see this PR introduces a lot of older HDF5 versions, and bumps some deps (which have since been bumped separately).

Is there a reason to support these older HDF5 versions?
If not then I humbly suggest that this PR can be closed.

**Comment by jgsogo** [comment]
Unless someone request it explicitly, there is no interest on our side in adding older versions. In fact, according to CCI policies only the latest versions should be available (of course, this is enforcer more strictly for bigger libraries that takes too much time to build)

**Comment by tbeu** [comment]
OK.

**Pull request closed without merging**
