### PR TITLE
libiconv: Fix building on mingw

### PR DESCRIPTION
**Pull request by Ahajha**
Specify library name and version:  **libiconv/all**

Resolves https://github.com/conan-io/conan-center-index/issues/20548  
Resolves https://github.com/conan-io/conan-center-index/issues/506  

The old [bincrafters recipe](https://github.com/bincrafters/conan-libiconv/blob/testing/1.16/conanfile.py) worked with mingw (in Conan 1.x), and I saw the main lines that made it work:
```python
        if self._is_mingw_windows or self._is_msvc:
            prefix = prefix.replace('\\', '/')
            build = False
            if self.settings.arch == "x86":
                host = "i686-w64-mingw32"
                rc = "windres --target=pe-i386"
            elif self.settings.arch == "x86_64":
                host = "x86_64-w64-mingw32"
                rc = "windres --target=pe-x86-64"
```
(plus some added context, but the idea is there)

This PR just migrates these lines to the new build helpers. Admittedly, I have no idea what the `RC` and `WINDRES` flags are for.

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Hello @Ahajha Did you try to build using mingw with this change? If yes, do you have a full build log to shared your results?

Locally, I can't build:

https://gist.github.com/uilianries/00567ffda78d3b96a63c5dfaaf314cb4

**Comment by Ahajha** [comment]
> Hello @Ahajha Did you try to build using mingw with this change? If yes, do you have a full build log to share your results?
> 
> Locally, I can't build:
> 
> https://gist.github.com/uilianries/00567ffda78d3b96a63c5dfaaf314cb4

I did and it worked, I will get the log shortly.

**Comment by Ahajha** [comment]
@uilianries Here is the log from my local build. I installed mingw separately using this tutorial: https://code.visualstudio.com/docs/cpp/config-mingw

[log.txt](https://github.com/conan-io/conan-center-index/files/14170734/log.txt)

**Comment by Ahajha** [comment]
@uilianries That also works for me.
[log2.txt](https://github.com/conan-io/conan-center-index/files/14170846/log2.txt)
Adding -o */*:shared also works.
[log3.txt](https://github.com/conan-io/conan-center-index/files/14170864/log3.txt)

**Review by uilianries — APPROVED** [review]
With the build log using mingw I'm comfortable with this change.

**Review by ericLemanissier — APPROVED** [review]

**Comment by amachado-pie** [comment]
This PR fails for cross-compiling wih gcc, when the profile:host is `Windows` but the  profile:build is `Linux` because mingw toolchain binaries in Linux has a name prefix `i686-w64-mingw32-`, ie., `i686-w64-mingw32-windres` , etc. 
So, then we try to do a cross-compilation for Windows from Linux it fails:
```
libtool: compile:  windres --target=pe-i386 --target=pe-i386 -DPACKAGE_VERSION_STRING=\\\"1.17\\\" -DPACKAGE_VERSION_MAJOR=1 -DPACKAGE_VERSION_MINOR=17 -DPACKAGE_VERSION_SUBMINOR=0 -i /home/amachado/.conan2/p/b/libic362ec7a18a879/b/src/lib/../windows/libiconv.rc --output-format=coff -o libiconv.res.o
../libtool: line 1932: windres: command not found
make[1]: *** [Makefile:99: libiconv.res.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by jcar87** [comment]
based on the report in https://github.com/conan-io/conan-center-index/issues/26445, I think this needs to be reverted.

Unfortunately, while the PR mentions  https://github.com/conan-io/conan-center-index/issues/20548 and  https://github.com/conan-io/conan-center-index/issues/506 - I can't find any evidence in the reported logs that those build failures had anything to do with windres? 

`windres` is autodetected by autotools - it tries `windres` and also `i686-w64-mingw32-windres` which it derives from the compiler target triple)  - this PR breaks the autodetection when the user is using a toolchain that only has the latter. 
* then it is invoked during the libtool phases - but the errors reported in t

The errors reported in those two issues, are compiler errors, reported for older versions of gcc and older versions of libiconv than the ones reported in the PR comments - so I'm not entirely sure we had enough information to approve this in the first place.

hi @Ahajha , @uilianries  - do we have build logs where building libiconv with mingw _fails_ without the changes in this PR? if I remove these lines, I can build with mingw on Windows (both with msys2 itself, and with the mingw-builds conan center package), as well as on Linux (with the toolchain provided by Ubuntu) - I'd hate to introduce a regression by removing these lines - but on the other hand I cant find any logs where the error is related to windres

**Pull request merged**
