### PR TITLE
libavif: add version 1.1.1

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **libavif/1.1.1**

#### Motivation
There are several improvements in 1.1.1.

#### Details
https://github.com/AOMediaCodec/libavif/compare/v1.1.0...v1.1.1#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by perseoGI — APPROVED** [review]
LGTM

**Review by AbrilRBS — COMMENTED** [review]
We should probably handle [AOMediaCodec/libavif@`v1.1.0...v1.1.1`#diff-1e7de1ae2d](https://github.com/AOMediaCodec/libavif/compare/v1.1.0...v1.1.1#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR137) `AVIF_ENABLE_GTEST` and friends

**Comment by toge** [comment]
@AbrilRBS 
The comment of `AVIF_ENABLE_GTEST` is following:
> Build avif C++ tests, which depend on GoogleTest. Requires GoogleTest. Has no effect unless AVIF_BUILD_TESTS is ON.

And the default value of `AVIF_BUILD_TESTS' is `OFF`.
```
option(AVIF_BUILD_TESTS "Build avif tests." OFF)
```

So these new options are no effect by default.

**Comment by AbrilRBS** [comment]
I didn't catch that extra option, thanks a lot for double checking @toge!

**Review by AbrilRBS — APPROVED** [review]

**Review by perseoGI — APPROVED** [review]

**Pull request merged**
