### PR TITLE
capnproto: add version 1.0.2

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **capnproto/1.0.2**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]

**Comment by RubenRBS** [comment]
Will retrigger this once the missing binary is available :)

**Comment by RubenRBS** [comment]
I think a second compilation should now fix it

**Review by valgur — APPROVED** [review]

**Review by valgur — APPROVED** [review]

**Comment by toge** [comment]
@RubenRBS 
Still missing dependencies.(itself)
```
ERROR: Missing prebuilt package for 'capnproto/1.0.2'. You can try:
    - List all available packages using 'conan list capnproto/1.0.2:* -r=remote'
    - Explain missing binaries: replace 'conan install ...' with 'conan graph explain ...'
    - This is a **test_package** missing binary. You can use --build (for all dependencies) or --build-test (exclusive for 'test_package' dependencies) to define what can be built from sources
```

Could you fix this?

**Comment by RubenRBS** [comment]
Checking, but this probably comes from the fact that the test recipe depends on the recipe in both contexts. It should have been fixed by the rerun you did, but seems like it still fails for some reason 🤔

**Pull request merged**
