### PR TITLE
netease-im: add new package NetEase IM C++ cross-platform SDK

### PR DESCRIPTION
**Pull request by nmgwddj**
Specify library name and version:  

 - **netease-im/9.10.0**
 - **netease-im/9.12.1**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by valgur** [comment]
Since `nim` is a fairly well-known language and a compiler, I would suggest renaming the paclage to `netease-im` instead.

**Comment by nmgwddj** [comment]
Hi @jcar87.

I would like to know why the inspectors `c3i/conan-v2/pr-merge` and `continuous integration/jenkins/pr-merge` fail.

I have already applied for permission https://github.com/conan-io/conan-center-index/issues/4, but I don't know what else is causing this problem? Please advise, thank you.

**Comment by nmgwddj** [comment]
> Since `nim` is a fairly well-known language and a compiler, I would suggest renaming the paclage to `netease-im` instead.

Okay, no problem. I will resubmit this PR.

**Comment by nmgwddj** [comment]
@prince-chrismc 
Could you please help me check why 'c3i/conan-v2/pr-merge' has been in progress for over 24 hours.

**Comment by prince-chrismc** [comment]
@nmgwddj you need to be more patient, there's over 325 PR+ so the build service can take some time.

Looking at this PR it's very complicated. Can you please  why there's an `"All"` key in the conandata.yml, there's no obvious reason what this is for 🧐

**Comment by nmgwddj** [comment]
> @nmgwddj you need to be more patient, there's over 325 PR+ so the build service can take some time.
> 
> Looking at this PR it's very complicated. Can you please why there's an `"All"` key in the conandata.yml, there's no obvious reason what this is for 🧐

Thank for your reply.

The binary package and source code are packaged in the same compressed file, with one copy for each architecture. Initially, I wanted to use the `source()` method to download the specified compressed package to the local machine for compilation based on the platform and architecture, but the checker reported an error, disallowing the use of the `self.settings` option in the `source()` method. So, I had to handle it temporarily, and we will consider separating the code and binary precompiled packages in the future. However, there is no good idea for now.

**Comment by nmgwddj** [comment]
> **c3i/conan-v2/pr-merge ** — This commit cannot be built

Finally waited until the end of `c3i/conan-v2/pr-merge`, but it prompts `This commit cannot be built` and there is no output, and there is no permission to view the details page.

**Pull request closed without merging**
