### PR TITLE
wil: add version 1.0.240803.1

### PR DESCRIPTION
**Pull request by slivermeteor**
### Summary
Changes to recipe:  **wil/1.0.240803.1**

#### Motivation
There are several new features in 1.0.240803.1

#### Details
https://github.com/microsoft/wil/compare/v1.0.240122.1...v1.0.240803.1

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by valgur — APPROVED** [review]

**Review by AbrilRBS — APPROVED** [review]
Thanks! We'll need the CLA signed for the PR to be merged, but otherwise looks good :)

**Comment by slivermeteor** [comment]
Ok, I've signed the CLA. Now this PR needs another reviewer's approval.

**Comment by slivermeteor** [comment]
@AbrilRBS Can any reviewer with write access help me review this PR?

**Review by uilianries — APPROVED** [review]
LGTM. No breaking changes: https://github.com/microsoft/wil/compare/v1.0.240122.1...v1.0.240803.1#files_bucket

**Pull request merged**
