### PR TITLE
sentry-native: add new versions

### PR DESCRIPTION
**Pull request by goranbrkic**
Specify library name and version:  **sentry-native/0.3.0**, **sentry-native/0.3.1**, **sentry-native/0.3.2**, **sentry-native/0.3.3**, **sentry-native/0.3.4**, **sentry-native/0.4.0**, **sentry-native/0.4.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jgsogo — COMMENTED** [review]
Are all these versions needed? Maybe it is ok to add only the latest one for each _series_: `0.2.6`and `0.3.4` and `0.4.1`.... or maybe just `0.4.1`

Are you using all these intermediate versions?

**Comment by goranbrkic** [comment]
> Are all these versions needed? Maybe it is ok to add only the latest one for each _series_: `0.2.6`and `0.3.4` and `0.4.1`.... or maybe just `0.4.1`
> 
> Are you using all these intermediate versions?

I'm using **sentry-native/0.4.1**, but thought to add rest of them for completeness.

I'm ok with providing only latest ones. 
@jgsogo is there any action I should take on my side?

**Comment by SpaceIm** [comment]
duplicate of https://github.com/conan-io/conan-center-index/pull/2696?

**Comment by goranbrkic** [comment]
Closing as it is duplicate of #2696

**Pull request closed without merging**
