### PR TITLE
add libcurl version 7.83.0

### PR DESCRIPTION
**Pull request by pbailey-hf**
Specify library name and version:  **libcurl/7.83.0**

Bumping to the latest upstream. I depend on this package, and this version corrects several security vulnerabilities.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
you probably want to close and reopen the PR, to retrigger CI. This PR should be marked as version bump after that, and be merged automatically if all jobs pass

**Comment by uilianries** [comment]
restarted it now.

**Comment by uilianries** [comment]
@pbailey-hf please, request access on the issue #4 as described above. https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#request-access

**Comment by pbailey-hf** [comment]
ok it appears I've been granted access.

**Pull request merged**
