### PR TITLE
Add missing requirement for libhal

### PR DESCRIPTION
**Pull request by kammce**
libhal 2.Y.Z requires tl-function-ref as well as boost-leaf.

Specify library name and version:  **libhal/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — DISMISSED** [review]

**Comment by RubenRBS** [comment]
Thanks! Any reason this was not caught by the test package originally?

**Comment by kammce** [comment]
> Thanks! Any reason this was not caught by the test package originally?

My test package just tests that you can bring in basic libraries, but doesn't check all of them. Where as my unit tests, which would catch this, were not brought over in the previous upgrade of libhal. So I missed this in the last review. 

Should I add the code to perform the unit tests in this recipe? I can also update the test package to ensure that this part of the library is checked.

**Comment by kammce** [comment]
Updated the test package to depend on a header file that depends on tl-reference

**Review by RubenRBS — APPROVED** [review]

**Comment by RubenRBS** [comment]
> Should I add the code to perform the unit tests in this recipe?

`test_package`s are not meant to run unittestings, only that the package itself was correctly created. It has its downsides as for example not catching this case earlier, but it's an approach that otherwise cleanly separates concerns and responsabilities for who tests what :)

> I can also update the test package to ensure that this part of the library is checked.

Thanks for doing it!

**Comment by kammce** [comment]
> > Should I add the code to perform the unit tests in this recipe?
> 
> `test_package`s are not meant to run unittestings, only that the package itself was correctly created. It has its downsides as for example not catching this case earlier, but it's an approach that otherwise cleanly separates concerns and responsabilities for who tests what :)
> 
> > I can also update the test package to ensure that this part of the library is checked.
> 
> Thanks for doing it!

Oh I meant to say, that, after we download the sources, we could build unit tests as part of the build. But I'm happy to just have test_package manage this.

**Review by toge — APPROVED** [review]

**Pull request merged**
