### PR TITLE
cmake: add 3.16.9, 3.17.5, 3.18.3 + update OpenSSL + exclude unsupported compilers

### PR DESCRIPTION
**Pull request by Croydon**
Specify library name and version:  **cmake/3.16.9**, **cmake/3.17.5** , **cmake/3.18.3**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
Ha. I fall for it too.

**Comment by prince-chrismc** [comment]
RIP - file too long

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "pseudo_emulator_custom_command.dir\Release\pseudo_e.F4792B4A.tlog\pseudo_emulator_custom_command.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\J\w\cci_PR-2941@3\2\11e15847-1e31-40d1-a9a9-014aa6f1b526\.conan\data\cmake\3.16.9\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\Tests\RunCMake\pseudo_emulator_custom_command.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "pseudo_emulator_custom_command_arg.dir\Release\pseudo_e.03E80CCC.tlog\pseudo_emulator_custom_command_arg.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\J\w\cci_PR-2941@3\2\11e15847-1e31-40d1-a9a9-014aa6f1b526\.conan\data\cmake\3.16.9\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\Tests\RunCMake\pseudo_emulator_custom_command_arg.vcxproj]
```

**Review by prince-chrismc — APPROVED** [review]

**Comment by danimtb** [comment]
please check again, I think the error is different

**Comment by uilianries** [comment]
> CMake Error at CMakeLists.txt:109 (message):
>  The C++ compiler does not support C++11 (e.g.  std::unique_ptr).

Now requires C++11

**Comment by Croydon** [comment]
This is odd. Why would they raise suddenly the c++ standard in a patch release?

**Comment by uilianries** [comment]
I don't know, I'll check tomorrow, sounds weird indeed.

**Comment by uilianries** [comment]
I don't think that's a new requirement, but a bug in cmake. unique_ptr is listed since 3 years ago, but there is a small change from 2 weeks ago in the cmake file which checks all requires features, including unique_ptr: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Source/Checks/cm_cxx_features.cmake#L26

**Comment by Croydon** [comment]
Indeed. CMake requires at least C++11, which brings me to the question: Which of the many ways to exclude compilers based on their language support is currently the approach we consider the best? Currently, our recipes use a wild mix of different ways. Also wouldn't this be something worth integrating in Conan itself?

**Comment by Croydon** [comment]
```
-- Checking if compiler supports C++ make_unique
-- Checking if compiler supports C++ make_unique - no
-- Checking if compiler supports C++ unique_ptr
-- Checking if compiler supports C++ unique_ptr - no
CMake Error at CMakeLists.txt:109 (message):
  The C++ compiler does not support C++11 (e.g.  std::unique_ptr).
```

I really don't understand what's going on here.

CMake is supporting VS2015+
And VS2015+ is supporting std::unique_ptr

I can also build locally without problems with VS2019

**Comment by uilianries** [comment]
@Croydon Maybe it's a specific version of MSVC 15

**Comment by Croydon** [comment]
It also failed with MSVC 15 and 16 on CI: https://github.com/conan-io/conan-center-index/pull/2941#issuecomment-701476654

**Comment by Croydon** [comment]
What now? 🙈

**Comment by jgsogo** [comment]
That unexpected error was because Jenkins restarted, we are not managing this scenario: the job tries to resume but there is some state not serialized, some dynamically created nodes not available after the restart and the job finally fails.

**Comment by Croydon** [comment]
Now I have to rebase, push and wait for another 12 hours or so.🙄

**Comment by jgsogo** [comment]
> Now I have to rebase, push and wait for another 12 hours or so.🙄

Yes. This is something we need to discuss. It is a problem which can only grow (unless we add more and more machines). Alternatives would be to remove versions or compile fewer profiles (or compile fewer profiles for older versions)... not sure if there are any other options 🤔  We need to talk about it.

**Comment by Croydon** [comment]
-> https://github.com/conan-io/conan-center-index/issues/2813 ? 

In this case I was (temporary) annoyed that pretty much a duplicate PR got merged causing this, but I guess it happens

By the way, do we still need to add all those settings for installer packages like CMake?

> settings = "os", "arch", "compiler", "build_type"

I kinda lost track of the related problems, but believe to recall that things got better there?

**Comment by Croydon** [comment]
I think the main concern was Windows and if dynamic runtimes are actually around on the host systems

https://github.com/conan-io/conan-center-index/pull/1783#issuecomment-637757038

@jgsogo IIRC we have now a guaranteed order for the compiler versions. Do we also have a guaranteed order for the runtimes and is Windows building with static runtimes first?

**Comment by jgsogo** [comment]
@solvingj  is trying to gather together the pros and cons of building all/some profiles of all/some versions. As with many other things, the implementation is not going to be the blocker, but we need to know the consequences.

About the order of profiles, it is in my TODO list. I need to double check it is working as expected. But there are so many conflicting priorities that I never find the time to run that check and open the PR and document the intention. Let's check it right now (https://github.com/conan-io/conan-center-index/pull/3153).

**Comment by Croydon** [comment]
@jgsogo Thank you so much for your work. I hope I didn't cause more stress ❤️

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
