### PR TITLE
pulseaudio: fix missing glibc symbols on newer systems

### PR DESCRIPTION
**Pull request by valgur**
Related to https://github.com/conan-io/hooks/pull/508
Applying the hook temporarily as a part of the package to validate that the fix for the glibc issue works.

A full list of packages affected by removed glibc symbols can be found here:
https://gist.github.com/valgur/4fec44c680d3df6401495dc8be4642d2

Depends on:
- #20266
- #20270

### CODE REVIEW

**Comment by valgur** [comment]
@uilianries @RubenRBS This build has been restarting over and over again for 8 times already today. You should probably look into it.

**Comment by RubenRBS** [comment]
Sorry for the spam @valgur, will check what's triggering the builds so often

**Comment by RubenRBS** [comment]
Ok I've discovered the root cause and we're working on fixing the issue, it's some combination of unlucky timing and maintenance mode checks for v2 builds. I've restarted the build, shouldn't happen again

**Comment by valgur** [comment]
The fix works. I created a separate PR to have something to actually merge: #20732

**Pull request closed without merging**
