### PR TITLE
flatbuffers: refactoring

### PR DESCRIPTION
**Pull request by SpaceIm**
- deprecate `flatc`, `flatbuffers` and `options_from_context` options (there was an attempt in https://github.com/conan-io/conan-center-index/pull/4863). All these options were part of a counterintuitive mechanism preventing to build the lib in build context and the executable in host context.
  Instead:
   - `flatc` is always built now, as well as flatbuffers lib (either static, shared or header only). 
   - we provide `flatbuffers::flatc` target (like upstream config file), and handle executable discovery from build context if cross-building with 2 profiles (it was managed by the weird `options_from_context` before), or host context if native build. It's a more elegant solution than https://github.com/conan-io/conan-center-index/pull/3345, and similar to the trick used in `protobuf` and `grpc` recipes.
- relocatable shared lib on macOS: see https://github.com/conan-io/hooks/issues/376
- CMakeDeps support
- fix Find module name (it's `FindFlatBuffers.cmake`, while config file is `FlatbuffersConfig.cmake`): see https://github.com/google/flatbuffers/tree/v2.0.0/CMake
- always rely on upstream CMakeLists to build and package flatbuffers (event for header-only) => less branching in the recipe.
- only provide functions of `BuildFlatBuffers.cmake` through `find_package()` (ie `cmake_find_package`/`cmake_find_package_multi`/`CMakeDeps`). At some point it doesn't make sense and it's not worth the effort to support consumers trying to call these functions without calling `find_package(Flatbuffers)` before.
  It's worth noting that this module file & its functions are not part of upstream config file, only Find module file. I've added this file to both, but I don't recommend to rely on these functions.

/cc @jgsogo @mjvankampen

closes https://github.com/conan-io/conan-center-index/issues/5616
closes https://github.com/conan-io/conan-center-index/issues/8374

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by mjvankampen** [comment]
By building flatc always I cannot use this recipe anymore for platforms where flatc cannot be build. I'm not sure if there are still platforms that do not support flatc but do support flatbuffers. This is not such a weird situation, there are multiple platforms where the compiler/code generator is more restrictive that the produced code. This was the original reason for the weird option_from_context as it was the only way I could find to include flatc in the build context but not in the host context.

**Comment by SpaceIm** [comment]
> By building flatc always I cannot use this recipe anymore for platforms where flatc cannot be build.

which platforms?

**Comment by SpaceIm** [comment]
> QNX for example. Not sure about others. I don't think you can set the flatc option one way for the build context and a different for the host context. Or is this possible now?

If I add flatc option again, it would be possible:

`conan install flatbuffers/2.0.0@ -pr:h flatbuffers:flatc=False -pr:b flatbuffers:flatc=True -b missing`

**Comment by SpaceIm** [comment]
```
ERROR: Missing binary: flatbuffers/2.0.0:17c6b956e973041a99732b9f33647b34bae851a9
flatbuffers/2.0.0: WARN: Can't find a 'flatbuffers/2.0.0' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.libcxx=libc++, compiler.version=12.0, os=Macos
- Options: flatbuffers=deprecated, flatc=deprecated, header_only=True, options_from_context=deprecated
- Dependencies: 
- Requirements: 
- Package ID: 17c6b956e973041a99732b9f33647b34bae851a9

ERROR: Missing prebuilt package for 'flatbuffers/2.0.0'
Use 'conan search flatbuffers/2.0.0 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=flatbuffers'
```

@jgsogo what is exactly the command executed in CI? This error should never happen with `conan create` when we add the same dependency in build requirements of test package.

**Comment by jgsogo** [comment]
Hi! The error comes from the `conan test` command. The `test_package/conanfile.py` is adding `flatbuffers` to build context (as a build-requires), and this is something we can't do although it might succeed under some circumstances (see 1️⃣  below).

When building for Apple M1, the command is `conan test ... --profile:host=<the-host-profile> --profile:build=default` (two profiles), the `profile:host` matches the one used to build the package, but the `profile:build` is different:

```
Configuration (profile_host):
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
[options]
flatbuffers:header_only=True
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
```

And the packageID computed for each context are different:

```
Requirements
    flatbuffers/2.0.0 from local cache - Cache
Packages
    flatbuffers/2.0.0:aa8bfbbddca8feb09a7119f3e659ee3aa3a1d452 - Download
Build requirements
    flatbuffers/2.0.0 from local cache - Cache
Build requirements packages
    flatbuffers/2.0.0:17c6b956e973041a99732b9f33647b34bae851a9 - Missing
```

Of course, the packageID for the _build_ context is missing because it hasn't been built. When creating the package in the previous step we build the one for the _host_ context.

**We cannot test in `test_package/conanfile.py` any other configuration than the one that has been built.** We cannot add the package as a build-requires, at least in Conan v1 that doesn't know how to rotate the profiles. 

---
1️⃣  It can succeed if the package for the _build_ context has already been built by another thread and uploaded to the remote... typically, it will succeed if we retrigger the build one more time for the same recipe revision.

This is probably the reason why other packages have succeeded. Having a look at the logs, they are using two different packageIDs:

```
Requirements
    flatbuffers/2.0.0 from local cache - Cache
Packages
    flatbuffers/2.0.0:c36572cdc38be7dbc966c1f9dd7cc86c518bcb6c - Download
Build requirements
    flatbuffers/2.0.0 from local cache - Cache
Build requirements packages
    flatbuffers/2.0.0:6a83d7f783e7ee89a83cf2fe72b5f5f67538e2a6 - Download
```
and if they work, it is just because that packageID has been generated before by a different job.

Of course we cannot rely on this behavior.

**Comment by jgsogo** [comment]
> * disable test if cross-build? (but I really want to test that we can call flatbuffers::flatc target from build context).

Indeed, we can only test the _build_ context if both profiles (_host_ and _build_) are the same (same packageID). So far this only happens (atm in CCI) in scenarios other than cross-building ones.

For the future, Conan should provide a way to indicate that the `test_package/conanfile.py` is testing the package as build_requires (there was a `test_type` for it) and then Conan should use the input `--profile:host` to feed the _build_ context (ensure we are testing the package we have just build)... and probably use the same one as the profile for the _target_ context (or just accept one more parameter). If rotating the profiles this way sound a bit weird, think about the `conan create --profile:host --profile:build` command where it is clear that the package built (_host_ context) should be used as a build-requires in the testing step, so Conan needs to _rotate_ the profiles.

**Comment by SpaceIm** [comment]
> btw, thanks a lot for taking care of this recipe, all those fixes were really needed 🎉
> 
> @mjvankampen , if `flatc` cannot be built for some configuration (and given the bug you are mentioning), we can use a different approach and remove the option or change its default value for that configuration. It's something we have done before in some recipes and helps us to deal with this kind of situation.

There is a serious issue in 2 profiles I think, so even with this trick, if someone has flatbuffers in requirements (for the library) and build requirement (for flatc), and flatc is False is requirements, it won't work because build requirement will inherit flatc=False: https://github.com/conan-io/conan/issues/10425#issuecomment-1031638847

**Comment by SpaceIm** [comment]
@mjvankampen would it be fine with https://github.com/conan-io/conan-center-index/pull/9292/commits/8b99a52187fa47a880d441baa244f22511425645?

**Comment by SpaceIm** [comment]
@jgsogo As you can see, it always works if not header_only.

**Comment by jgsogo** [comment]
> @jgsogo As you can see, it always works if cross-build and not header_only.

It works because we are building first the configuration for regular MacOS and then the ones for Apple M1, so the package for the _build_ environment is always available at that moment.

---

About the missing package when `header_only=True` we need to know how it is computed. (Using [these results](https://github.com/conan-io/conan-center-index/pull/9292#issuecomment-1031796832)) The packageID is `flatbuffers/1.12.0:17c6b956e973041a99732b9f33647b34bae851a9 - Missing` which is not listed anywhere.

```
ERROR: Missing binary: flatbuffers/1.12.0:17c6b956e973041a99732b9f33647b34bae851a9
flatbuffers/1.12.0: WARN: Can't find a 'flatbuffers/1.12.0' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.libcxx=libc++, compiler.version=12.0, os=Macos
- Options: flatbuffers=deprecated, flatc=deprecated, header_only=True, options_from_context=deprecated
- Dependencies: 
- Requirements: 
- Package ID: 17c6b956e973041a99732b9f33647b34bae851a9
```

According to the configuration provided, we should find that packageID in this table (https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/9292/6-configs/macos-clang/flatbuffers/1.12.0//summary.json), but there the one for `header_only=True` is `185696e08c21cba45ac28efd5468564a2bc85ed2`. How is this possible? Looks like it is taking into account value `compiler.version=12.0` (different from `compiler.version=11.0`). Checking the `package_id` I can see:

```python
    def package_id(self):
        if self.options.header_only and not self._has_flatc:
            self.info.header_only()
        # deprecated options
        del self.info.options.flatc
        del self.info.options.flatbuffers
        del self.info.options.options_from_context
```

And here we see another challenge for CCI: **option `header_only=True` doesn't [always] translate to a `header_only()` package in terms of packageID** 😓  In this case CCI shouldn't assume that for `header_only=True` there is only one packageID, but IMHO the CI cannot be that smart... 

...and I need to think about it.

**Comment by mjvankampen** [comment]
> @mjvankampen would it be fine with [8b99a52](https://github.com/conan-io/conan-center-index/commit/8b99a52187fa47a880d441baa244f22511425645)?

Sure, just change qnx to neutrino which is in settings.yml, I'm used to using the brand name, don't know why :-). Imho it would be nicer to fix the options from context (rename as misleiding, only use during crossbuilding, ...)? It does what you want right? Only build flatc in build context and not in host context. But I'm fine with this solution as well! Up to you and @jgsogo.

**Comment by SpaceIm** [comment]
> > @mjvankampen would it be fine with [8b99a52](https://github.com/conan-io/conan-center-index/commit/8b99a52187fa47a880d441baa244f22511425645)?
> 
> Sure, just change qnx to neutrino which is in settings.yml, I'm used to using the brand name, don't know why :-). Imho it would be nicer to fix the options from context (rename as misleiding, only use during crossbuilding, ...)? It does what you want right? Only build flatc in build context and not in host context. But I'm fine with this solution as well! Up to you and @jgsogo.

But basically CCI doesn't want to not build flatc in host context if cross-building. Otherwise the binary for macOS M1 doesn't contain flatc.

**Comment by SpaceIm** [comment]
There are compilation issues in flatbuffers 2.0.5, don't want to handle them in this PR.

**Review by uilianries — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]
let's move this one forward @SpaceIm . there are serious issues with 2 profiles in v1, but nothing we can do about it in CCI right now :( 
I don't think it should block your PR, as it's an improvement on its own.

**Comment by qiao-tw** [comment]
Hi @SpaceIm ,
I just updated my conan to 1.49.0 and suddenly the function ```build_flatbuffers()``` in my ```CMakeList.txt``` not working anymore. I think it's related to this patch.

After reading this discussion loop, I still got following 2 questions.
1. I can see the cmake function ```build_flatbuffers()``` is in ```BuildFlatBuffers.cmake``` which is provided in official conan ```flatbuffers``` package, but how should I use it in my ```CMakeList.txt```?
2. How to work with host executable with conan? I've tried to adopt the best practice (i.e. use the ```flatc``` executable of host machine, for me which is ubuntu 20.04, and use ```find_package(Flatbuffers)``` to import the cmake variables. However, cmake complains as following:
```
CMake Error at CMakeLists.txt:57 (find_package):
  By not providing "FindFlatbuffers.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Flatbuffers", but CMake did not find one.

  Could not find a package configuration file provided by "Flatbuffers" with
  any of the following names:

    FlatbuffersConfig.cmake
    flatbuffers-config.cmake
```

Thanks.

**Comment by elejke** [comment]
Have the same problem on linux as @qiao-tw when building onnxruntime/1.7.1 package with flatbuffers/1.12.0

what is the current solution for this?

**Pull request merged**
