### PR TITLE
univalue: modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
Warning: Neither 'python-version' nor 'python-version-file' inputs were supplied. Attempting to find '.python-version' file.
Warning: .python-version doesn't exist.
Warning: The `python-version` input is not set.  The version of Python currently in `PATH` will be used.
Run import json
Traceback (most recent call last):
  File "/home/runner/work/_temp/be673886-2e6a-[47](https://github.com/conan-io/conan-center-index/actions/runs/4205787070/jobs/7298369507#step:26:51)51-b8ee-7921effb4e70.py", line 9, in <module>
    res = subprocess.run(["gh", "api", "/repos/conan-io/conan-center-index/pulls/16103/files", "--paginate"], capture_output=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gh', 'api', '/repos/conan-io/conan-center-index/pulls/16103/files', '--paginate']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

I don't know what's wrong here, but it's quite problematic that such github action unrelated to recipe verification can prevent a successful check of recipe.

/cc @ericLemanissier @uilianries

**Comment by ericLemanissier** [comment]
@SpaceIm Do you have a link to the error ? does it actually prevent the merge ?

**Comment by uilianries** [comment]
@ericLemanissier @SpaceIm I opened the issue https://github.com/conan-io/conan-center-index/issues/16104 to report it.

So far we have https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error but also need to improve gh api call with some retries.

**Comment by ericLemanissier** [comment]
I don't think the merge bot looks at this workflow status, cf https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L26-L28

**Review by uilianries — APPROVED** [review]
LGTM

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
