### PR TITLE
fix poco process fork

### PR DESCRIPTION
**Pull request by paulo-coutinho**
Specify library name and version:  **poco/1.11.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by paulo-coutinho** [comment]
This solution come from poco guys:
https://github.com/pocoproject/poco/issues/3347

**Review by uilianries — APPROVED** [review]
It looks correct. There is no forward definition for POCO_NO_FORK_EXEC using CMake, however, I can find ifdef in 2 cpp files. According the upstream, it should be fixed on 1.11.1. We could adopt their fix (when available) as a patch.

**Comment by madebr** [comment]
I would prefer a patch that does this completely in cmake.
e.g.
```patch
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -3,1 +3,4
 project(poco)
+if(POCO_NO_FORK_EXEC)
+  add_definitions(-DPOCO_NO_FORK_EXEC=1)
+endif()
```

**Comment by uilianries** [comment]
@paulo-coutinho Consider https://github.com/paulo-coutinho/conan-center-index/pull/1 That suggestion follow @madebr approach.

**Comment by paulo-coutinho** [comment]
Hi,

I made all changes.

**Review by madebr — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
