### PR TITLE
bzip2 apply patch only for the version >= 1.0.6

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **bzip2/all**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — CHANGES_REQUESTED** [review]
Why do you need this ?
apply_conandata_patches works even if there is not patches listed for the version of the package.

**Review by uilianries — CHANGES_REQUESTED** [review]
@AndreyMlashkin Please, explain your case, what's breaking for you and what this change fixes.

Please, understand that `apply_conandata_patches`, applies a patch according to the `conandata.yml` data: https://docs.conan.io/2/reference/tools/files/patches.html#conan.tools.files.patches.apply_conandata_patches

**Comment by AndreyMlashkin** [comment]
I have a fail for windows build:

```bzip2/1.0.8: Configuring sources in C:\Users\khuddev.LGS-NET\.conan\data\bzip2\1.0.8\_\_\source\src
[18:12:07][Step 3/4] bzip2/1.0.8: 
[18:12:07][Step 3/4] bzip2/1.0.8: Copying sources to build folder
[18:12:07][Step 3/4] bzip2/1.0.8: Building your package in C:\Users\khuddev.LGS-NET\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201
[18:12:07][Step 3/4] bzip2/1.0.8: Generator txt created conanbuildinfo.txt
[18:12:07][Step 3/4] bzip2/1.0.8: Calling generate()
[18:12:07][Step 3/4] bzip2/1.0.8: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
[18:12:07][Step 3/4] bzip2/1.0.8: Preset 'default' added to CMakePresets.json. Invoke it manually using 'cmake --preset default'
[18:12:07][Step 3/4] bzip2/1.0.8: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:\Users\khuddev.LGS-NET\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
[18:12:07][Step 3/4] bzip2/1.0.8: Aggregating env generators
[18:12:07][Step 3/4] bzip2/1.0.8: Calling build()
[18:12:07][Step 3/4] bzip2/1.0.8: apply_conandata_patches(): No patches defined in conandata
[18:12:07][Step 3/4] bzip2/1.0.8: CMake command: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/khuddev.LGS-NET/.conan/data/bzip2/1.0.8/_/_/build/53b5fd22ba061620078deefdae9a437c5f693201/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/khuddev.LGS-NET/.conan/data/bzip2/1.0.8/_/_/package/53b5fd22ba061620078deefdae9a437c5f693201" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\khuddev.LGS-NET\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201\src\.."
[18:12:07][Step 3/4] CMake Warning:
[18:12:07][Step 3/4]   Ignoring extra path from command line:
[18:12:07][Step 3/4] 
[18:12:07][Step 3/4]    "C:\Users\khuddev.LGS-NET\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201\src\.."
[18:12:07][Step 3/4] 
[18:12:07][Step 3/4] 
[18:12:07][Step 3/4] CMake Error: The source directory "C:/Users/khuddev.LGS-NET/.conan/data/bzip2/1.0.8/_/_/build/53b5fd22ba061620078deefdae9a437c5f693201" does not appear to contain CMakeLists.txt.
[18:12:07][Step 3/4] Specify --help for usage, or press the help button on the CMake GUI.
[18:12:07][Step 3/4] bzip2/1.0.8: ERROR: Package '53b5fd22ba061620078deefdae9a437c5f693201' build failed
[18:12:07][Step 3/4] bzip2/1.0.8: 
[18:12:07][Step 3/4] bzip2/1.0.8: WARN: Build folder C:\Users\khuddev.LGS-NET\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201\build
[18:12:07][Step 3/4] ERROR: bzip2/1.0.8: Error in build() method, line 63
[18:12:07][Step 3/4] 	cmake.configure(build_script_folder=os.path.join(self.source_folder, os.pardir))
[18:12:07][Step 3/4] 	ConanException: Error 1 while executing cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/khuddev.LGS-NET/.conan/data/bzip2/1.0.8/_/_/build/53b5fd22ba061620078deefdae9a437c5f693201/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/khuddev.LGS-NET/.conan/data/bzip2/1.0.8/_/_/package/53b5fd22ba061620078deefdae9a437c5f693201" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\khuddev.LGS-NET\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201\src\.." ```

**Comment by valgur** [comment]
Probably can be closed.

**Pull request closed without merging**
