### PR TITLE
gdal: add 3.2.3 & 3.4.1 + keep last patch version of each minor version + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
LGTM

**Review by prince-chrismc — APPROVED** [review]

**Review by prince-chrismc — DISMISSED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by SpaceIm** [comment]
relocatable shared lib on macOS: https://github.com/conan-io/hooks/issues/376

I've also seen that all shared (ie `conan create . gdal/3.4.1@ -o "*":shared=True`) was broken on macOS due to autotools helper injecting libs of dependencies in `LIBS` (it breaks configure). So autotools.libs should be forced to empty array, but patches of configure.ac should be updated, they strongly rely on implicit injection of all deps in LIBS.

**Comment by SpaceIm** [comment]
> relocatable shared lib on macOS: [conan-io/hooks#376](https://github.com/conan-io/hooks/issues/376)
> 
> I've also seen that all shared (ie `conan create . gdal/3.4.1@ -o "*":shared=True`) was broken on macOS due to autotools helper injecting libs of dependencies in `LIBS`. Indeed it breaks on macOS for native build because configure mechanism is to run test executables produced during this step to check whether they work properly, and shared libs are not found because autotools doesn't seem to be smart enough to inject paths of shared dependencies to rpath of test executables:
> 
> ```
> configure:4804: checking whether we are cross compiling
> configure:4812: gcc -o conftest -m64 -O3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -arch x86_64 -I/Users/spaceim/.conan/data/json-c/0.15/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/include -I/Users/spaceim/.conan/data/libgeotiff/1.7.0/_/_/package/1045c995724910e9a632e3842c2b43b027ad0b9c/include -I/Users/spaceim/.conan/data/flatbuffers/2.0.0/_/_/package/1d613d6f0a839546e2dd1dc483368c53410c16a9/include -I/Users/spaceim/.conan/data/libiconv/1.16/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/include -I/Users/spaceim/.conan/data/libpng/1.6.37/_/_/package/1f28ef21536b01906a19c1c67bcaa87e4e65eee0/include -I/Users/spaceim/.conan/data/giflib/5.2.1/_/_/package/bdbbca4fa8cee5960988840eb64565a9176ffd19/include -I/Users/spaceim/.conan/data/geos/3.10.2/_/_/package/ed714b563840e2756b9341de05e8e97691c36131/include -I/Users/spaceim/.conan/data/qhull/8.0.1/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/include -I/Users/spaceim/.conan/data/proj/8.2.1/_/_/package/bae6006bd6719a0aa72c02b25f2bba067f36b5b8/include -I/Users/spaceim/.conan/data/libtiff/4.3.0/_/_/package/d3604617558e16293479fa2e12742f04d50430c0/include -I/Users/spaceim/.conan/data/nlohmann_json/3.10.5/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/Users/spaceim/.conan/data/sqlite3/3.37.2/_/_/package/b15b8772d94005922ec8a099e4464c2747b96506/include -I/Users/spaceim/.conan/data/libcurl/7.80.0/_/_/package/6b4c8314e132d9b68b5f48c40d4df883034ce8b3/include -I/Users/spaceim/.conan/data/zlib/1.2.11/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/include -I/Users/spaceim/.conan/data/libdeflate/1.9/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/include -I/Users/spaceim/.conan/data/xz_utils/5.2.5/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/include -I/Users/spaceim/.conan/data/libjpeg/9d/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/include -I/Users/spaceim/.conan/data/jbig/20160605/_/_/package/880bc78f4d08d85e4d29331704f4c28ea89ee364/include -I/Users/spaceim/.conan/data/zstd/1.5.2/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/include -I/Users/spaceim/.conan/data/libwebp/1.2.2/_/_/package/6e8cbe983405f952fb58e22087c41f4154ac3259/include -DUSE_UNSTABLE_GEOS_CPP_API -DGEOS_INLINE -DNDEBUG -framework SystemConfiguration -framework CoreFoundation -framework Security -m64 -L/Users/spaceim/.conan/data/json-c/0.15/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/lib -L/Users/spaceim/.conan/data/libgeotiff/1.7.0/_/_/package/1045c995724910e9a632e3842c2b43b027ad0b9c/lib -L/Users/spaceim/.conan/data/flatbuffers/2.0.0/_/_/package/1d613d6f0a839546e2dd1dc483368c53410c16a9/lib -L/Users/spaceim/.conan/data/libiconv/1.16/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib -L/Users/spaceim/.conan/data/libpng/1.6.37/_/_/package/1f28ef21536b01906a19c1c67bcaa87e4e65eee0/lib -L/Users/spaceim/.conan/data/giflib/5.2.1/_/_/package/bdbbca4fa8cee5960988840eb64565a9176ffd19/lib -L/Users/spaceim/.conan/data/geos/3.10.2/_/_/package/ed714b563840e2756b9341de05e8e97691c36131/lib -L/Users/spaceim/.conan/data/qhull/8.0.1/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib -L/Users/spaceim/.conan/data/proj/8.2.1/_/_/package/bae6006bd6719a0aa72c02b25f2bba067f36b5b8/lib -L/Users/spaceim/.conan/data/libtiff/4.3.0/_/_/package/d3604617558e16293479fa2e12742f04d50430c0/lib -L/Users/spaceim/.conan/data/sqlite3/3.37.2/_/_/package/b15b8772d94005922ec8a099e4464c2747b96506/lib -L/Users/spaceim/.conan/data/libcurl/7.80.0/_/_/package/6b4c8314e132d9b68b5f48c40d4df883034ce8b3/lib -L/Users/spaceim/.conan/data/zlib/1.2.11/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib -L/Users/spaceim/.conan/data/libdeflate/1.9/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib -L/Users/spaceim/.conan/data/xz_utils/5.2.5/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib -L/Users/spaceim/.conan/data/libjpeg/9d/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib -L/Users/spaceim/.conan/data/jbig/20160605/_/_/package/880bc78f4d08d85e4d29331704f4c28ea89ee364/lib -L/Users/spaceim/.conan/data/zstd/1.5.2/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib -L/Users/spaceim/.conan/data/libwebp/1.2.2/_/_/package/6e8cbe983405f952fb58e22087c41f4154ac3259/lib conftest.c -ljson-c -lgeotiff -lgeotiff.5 -lgeotiff.5.1.0 -lflatbuffers -lflatbuffers.2 -lflatbuffers.2.0.0 -liconv -lcharset -lpng16 -lgif -lgeos_c -lgeos -lqhull_r -lproj -lproj.22 -lproj.22.2.1 -ltiffxx -ltiff -lsqlite3 -lcurl -lz -ldeflate -llzma -llzma.5 -ljpeg -ljbig -lzstd -lzstd.1 -lzstd.1.5.2 -lwebpdecoder -lwebpdemux -lwebpmux -lwebp >&5
> configure:4816: $? = 0
> configure:4823: ./conftest
> dyld[84471]: Library not loaded: @rpath/libgeotiff.5.dylib
>   Referenced from: /Users/spaceim/.conan/data/gdal/3.4.1/_/_/build/9eadedb4d5863750443d4071c8f90e468c88634b/source_subfolder/conftest
>   Reason: tried: '/usr/local/lib/libgeotiff.5.dylib' (no such file), '/usr/lib/libgeotiff.5.dylib' (no such file)
> ./configure: line 4825: 84471 Abort trap: 6           ./conftest$ac_cv_exeext
> configure:4827: $? = 134
> configure:4834: error: in `/Users/spaceim/.conan/data/gdal/3.4.1/_/_/build/9eadedb4d5863750443d4071c8f90e468c88634b/source_subfolder':
> configure:4836: error: cannot run C compiled programs.
> If you meant to cross compile, use `--host'.
> See `config.log' for more details
> ```
> 
> So autotools.libs should be forced to empty array (I think that this auto injection should never have been implemented), but patches of configure.ac should be updated, they strongly rely on implicit injection of all deps in LIBS.

Even when I call add `include_rpath_flags=True` to autotools helper, it doesn't work, because paths are double quoted, and it's invalid:

```
dyld[86180]: Library not loaded: @rpath/libgeotiff.5.dylib
  Referenced from: /Users/spaceim/.conan/data/gdal/3.4.1/_/_/build/9eadedb4d5863750443d4071c8f90e468c88634b/source_subfolder/conftest
  Reason: tried: '"/Users/spaceim/.conan/data/json-c/0.15/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libgeotiff/1.7.0/_/_/package/1045c995724910e9a632e3842c2b43b027ad0b9c/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/flatbuffers/2.0.0/_/_/package/1d613d6f0a839546e2dd1dc483368c53410c16a9/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libiconv/1.16/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libpng/1.6.37/_/_/package/1f28ef21536b01906a19c1c67bcaa87e4e65eee0/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/giflib/5.2.1/_/_/package/bdbbca4fa8cee5960988840eb64565a9176ffd19/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/geos/3.10.2/_/_/package/ed714b563840e2756b9341de05e8e97691c36131/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/qhull/8.0.1/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/proj/8.2.1/_/_/package/bae6006bd6719a0aa72c02b25f2bba067f36b5b8/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libtiff/4.3.0/_/_/package/d3604617558e16293479fa2e12742f04d50430c0/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/sqlite3/3.37.2/_/_/package/b15b8772d94005922ec8a099e4464c2747b96506/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libcurl/7.80.0/_/_/package/6b4c8314e132d9b68b5f48c40d4df883034ce8b3/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/zlib/1.2.11/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libdeflate/1.9/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/xz_utils/5.2.5/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libjpeg/9d/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/jbig/20160605/_/_/package/880bc78f4d08d85e4d29331704f4c28ea89ee364/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/zstd/1.5.2/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libwebp/1.2.2/_/_/package/6e8cbe983405f952fb58e22087c41f4154ac3259/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/json-c/0.15/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libgeotiff/1.7.0/_/_/package/1045c995724910e9a632e3842c2b43b027ad0b9c/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/flatbuffers/2.0.0/_/_/package/1d613d6f0a839546e2dd1dc483368c53410c16a9/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libiconv/1.16/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/li
bgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libpng/1.6.37/_/_/package/1f28ef21536b01906a19c1c67bcaa87e4e65eee0/lib"/libgeotiff.5.dylib' (no such file), '"/Users/charpe
ntiera/.conan/data/giflib/5.2.1/_/_/package/bdbbca4fa8cee5960988840eb64565a9176ffd19/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/geos/3.10.2/_/_/package/ed714b5
63840e2756b9341de05e8e97691c36131/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/qhull/8.0.1/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5
.dylib' (no such file), '"/Users/spaceim/.conan/data/proj/8.2.1/_/_/package/bae6006bd6719a0aa72c02b25f2bba067f36b5b8/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan
/data/libtiff/4.3.0/_/_/package/d3604617558e16293479fa2e12742f04d50430c0/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/sqlite3/3.37.2/_/_/package/b15b8772d9400592
2ec8a099e4464c2747b96506/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libcurl/7.80.0/_/_/package/6b4c8314e132d9b68b5f48c40d4df883034ce8b3/lib"/libgeotiff.5.dylib
' (no such file), '"/Users/spaceim/.conan/data/zlib/1.2.11/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data
/libdeflate/1.9/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/xz_utils/5.2.5/_/_/package/bda713dd3b257827c8d1
1a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libjpeg/9d/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no su
ch file), '"/Users/spaceim/.conan/data/jbig/20160605/_/_/package/880bc78f4d08d85e4d29331704f4c28ea89ee364/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/zstd/1.5.2/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib"/libgeotiff.5.dylib' (no such file), '"/Users/spaceim/.conan/data/libwebp/1.2.2/_/_/package/6e8cbe983405f952fb58e22087c41f4154ac3259/lib"/libgeotiff.5.dylib' (no such file), '/usr/local/lib/libgeotiff.5.dylib' (no such file), '/usr/lib/libgeotiff.5.dylib' (no such file)
```

See `'"/Users/spaceim/.conan/data/libgeotiff/1.7.0/_/_/package/1045c995724910e9a632e3842c2b43b027ad0b9c/lib"/libgeotiff.5.dylib' (no such file)`. Interesting, isn't it?

**Review by prince-chrismc — DISMISSED** [review]

**Review by uilianries — DISMISSED** [review]

**Comment by SpaceIm** [comment]
@SSE4 @madebr @toge could you review this PR please?

**Comment by SSE4** [comment]
> @SSE4 @madebr @toge could you review this PR please?

I am not sure, there are many patches with lots of changes to makefiles and sources. it needs to be reviewed carefully, but I am not familar with gdal at all.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by prince-chrismc — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
