### PR TITLE
zxing-cpp: Revert #8373

### PR DESCRIPTION
**Pull request by SpaceIm**
This reverts commit b1fbb052b4d0552e0afd7a0e217ae7ce30ae416a.

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Plain revert is not possible on conan-center, the recipe must have a content different from all previous revisions, or it won't be exported after merge.

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@SSE4 Github review didn't that change was under `config_options`, wrong place.

**Comment by SSE4** [comment]
> @SSE4 Github review didn't that change was under `config_options`, wrong place.

so maybe move this code into `validate` then?

**Comment by ericLemanissier** [comment]
it is already there

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
