### PR TITLE
[sentry-crashpad/0.6.3] Bump version

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jcar87** [comment]
Hi @MartinDelille  - thanks for your contribution.
I've fixed a Conanfile syntax issue with the test package, but it looks like there's a problem with the logic that causes a compiler error:

```
sentry-crashpad/0.6.1 (test package): Running CMake.build()
sentry-crashpad/0.6.1 (test package): RUN: cmake --build "/home/conan/w/prod-v2/BuildSingleReference/cci-b185063e/recipes/sentry-crashpad/all/test_package/build/gcc-11-x86_64-17-release" -- -j3
Scanning dependencies of target test_package
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.o
/home/conan/w/prod-v2/BuildSingleReference/cci-b185063e/recipes/sentry-crashpad/all/test_package/test_package.cpp: In function 'bool startCrashpad(const base::FilePath&, const base::FilePath&)':
/home/conan/w/prod-v2/BuildSingleReference/cci-b185063e/recipes/sentry-crashpad/all/test_package/test_package.cpp:25:9: error: cannot convert 'const char [1]' to 'const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&'
   25 |         "",
      |         ^~
      |         |
      |         const char [1]
In file included from /home/conan/w/prod-v2/BuildSingleReference/cci-b185063e/recipes/sentry-crashpad/all/test_package/test_package.cpp:9:
/home/conan/w/prod-v2/BuildSingleReference/p/sentr2ee2483ca2d66/p/include/crashpad/client/crashpad_client.h:127:63: note:   initializing argument 5 of 'bool crashpad::CrashpadClient::StartHandler(const base::FilePath&, const base::FilePath&, const base::FilePath&, const string&, const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&, const std::vector<std::__cxx11::basic_string<char> >&, bool, bool, const std::vector<base::FilePath>&)'
  127 |                     const std::map<std::string, std::string>& annotations,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
CMakeFiles/test_package.dir/build.make:62: recipe for target 'CMakeFiles/test_package.dir/test_package.cpp.o' failed
make[2]: *** [CMakeFiles/test_package.dir/test_package.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/test_package.dir/all' failed
make[1]: *** [CMakeFiles/test_package.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by MartinDelille** [comment]
Hi @jcar87 ! Yes indeed. I replaced #if by #ifdef to fix the issue locally.

**Comment by jcar87** [comment]
awesome, thanks for looking into it

**Review by jcar87 — APPROVED** [review]
Thanks for your contribution!

**Review by RubenRBS — APPROVED** [review]
Thanks a lot! :)

**Pull request merged**
