### PR TITLE
yamllinter: raise if actual patch files are not coherent with conandata.yml

### PR DESCRIPTION
**Pull request by ericLemanissier**
It can happen if:
- conadata.yml patches section reference some files which do not exist
- or if some patches exist in patches subfolder, but not in conandata.yml

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
New detections:
- 1 patch listed in conandata.yml, but not present in patches folder: https://github.com/conan-io/conan-center-index/actions/runs/3766729317/jobs/6403536596#step:9:9907 => https://github.com/conan-io/conan-center-index/tree/8b3c7ac87fccd44d30ae18890823f386d3e12a02/recipes/rangesnext/all
- 21 patches which are not listed in conandata.yml (search for `is not referenced` in https://github.com/conan-io/conan-center-index/actions/runs/3766729317/jobs/6403536596)

**Comment by ericLemanissier** [comment]
This is still alive, back off !

**Comment by ericLemanissier** [comment]
blocked by:
- https://github.com/conan-io/conan-center-index/pull/15499

**Comment by prince-chrismc** [comment]
Because this inspect the contents of the recipe is more appropriate for the hooks https://github.com/conan-io/hooks/blob/2e7cac85494fd4ec5134aae5af504ed35174c0d7/hooks/conan-center.py#L465

Linters should focused on specific files and syntax correctness but the structure or files are the hooks. That being said it's unclear how these will evolve so I am not sure if this should be put on hold.

**Comment by ericLemanissier** [comment]
> Because this inspect the contents of the recipe is more appropriate for the hooks https://github.com/conan-io/hooks/blob/2e7cac85494fd4ec5134aae5af504ed35174c0d7/hooks/conan-center.py#L465

ok. I tend to go to linters by default, because the way errors show-up in github is way more convenient and efficient than hooks errors and (even worse) hooks warning. That said we could start using a fixed format reporting errors and warnings in hooks, add a github workflow which exports the recipes, and code a problem-matcher. Then hooks error would show-up on github UI too.

> Linters should focused on specific files and syntax correctness but the structure or files are the hooks. That being said it's unclear how these will evolve so I am not sure if this should be put on hold.

I had no idea about this "1 file" inspection rule. genuine question: what makes the number of files inspected relevant in choosing to implement a check as a hook as opposed to a linter ?

**Comment by ericLemanissier** [comment]
Still alive, you bot

**Pull request closed without merging**
