### PR TITLE
protobuf: improve discovery of protoc executable in build context

### PR DESCRIPTION
**Pull request by SpaceIm**
While building googleapis shared against protobuf shared, and protobuf static in build requirements, I've realized that the protoc flavor linked to shared protobuf was used, instead of the static flavor.

So this PR fixes this issue, by ensuring that even for native build, protoc from build requirements is used when available, instead of protoc from requirements.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
ERROR: Missing binary: protobuf/3.20.0:eb5173dacad2e669146d68b06c433f666807fac6

protobuf/3.20.0: WARN: Can't find a 'protobuf/3.20.0' package binary 'eb5173dacad2e669146d68b06c433f666807fac6' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[options]
debug_suffix=True
lite=False
shared=False
with_rtti=True
with_zlib=True
[requires]
zlib/1.3.Z

ERROR: Missing prebuilt package for 'protobuf/3.20.0'
Check the available packages using 'conan list protobuf/3.20.0:* -r=remote'
'conan test' tested packages must exist, and '--build' argument is used only for the 'test_package' dependencies, not for the tested dependencies

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```

@RubenRBS @danimtb Is c3i logic broken? There should be a "lock" delaying execution of test package for `shared=True` flavor of each settings, until `shared=False` package of the same settings is available (and if shared=True is the default value, it should be the opposite), otherwise when recipe is in build requirements of test package, we end up with these missing binaries.

**Comment by SpaceIm** [comment]
I guess that it should pass if I trigger c3i again, since package is available now...

**Comment by SpaceIm** [comment]
Well, it's super tedious. Any chance to fix c3i logic?

**Comment by SpaceIm** [comment]
It's a bug of v2 pipeline: https://github.com/conan-io/conan-center-index/pull/19501#issuecomment-1792269986

**Review by toge — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Comment by pgeler** [comment]
https://github.com/conan-io/conan-center-index/issues/21737

**Pull request merged**
