### PR TITLE
glu/system: Fix cpp_info.includedirs typo

### PR DESCRIPTION
**Pull request by Hopobcn**
Specify library name and version:  **glu/system**

Fixes https://github.com/conan-io/conan-center-index/issues/6575

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Review by FernandoVelcic — APPROVED** [review]

**Review by theirix — APPROVED** [review]
nice catch!

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
I wonder if it's even possible to make conan strict about it?
right now, python allows `cpp_info.whatever = whatever` and it might be a good thing for general cases, but for conan, not sure

**Comment by Hopobcn** [comment]
> I wonder if it's even possible to make conan strict about it?


Are "N config -> 1 package" (`self.cpp_info.debug`, `self.cpp_info.release`, etc..) type of packages allowed in CCI? 

If not, one possibility would be to use a hook. If a `self.cpp_info` references something not contemplated in https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info it could raise a warning/error.

**Comment by ericLemanissier** [comment]
I *think* this is what https://www.github.com/conan-io/hooks/tree/master/hooks%2Frecipe_linter.py does

**Pull request merged**
