### PR TITLE
openimageio: migrate to Conan v2

### PR DESCRIPTION
**Pull request by valgur**
Getting many `undefined reference to `__exp_finite'` and similar errors currently.

### CODE REVIEW

**Comment by valgur** [comment]
Closing temporarily to avoid unnecessary load on the CI. Will reopen when I'm actively working on the PR again.

**Comment by RubenRBS** [comment]
Triggering this again, it should now be fixed

**Comment by RobertRapidshape** [comment]
Hi there,
is there already a solution? We still observe a wrong package id for the latest supported OpenImageIO package (2.4.7.1) as initially issued here: [Issue 20365](https://github.com/conan-io/conan-center-index/issues/20365)

**Comment by valgur** [comment]
Requires #20703 for a fix to the version mismatches.

**Pull request closed without merging**
