### PR TITLE
CMake test_package: Use deps_cpp_info version

### PR DESCRIPTION
**Pull request by danimtb**
Specify library name and version:  **cmake/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by danimtb** [comment]
Apparently the ``deps_cpp_info["cmake"].version`` valu is empty, I have to check this.

**Comment by danimtb** [comment]
I am testing this locally with latest conan version and it is working. Not sure what is the issue in the CI

**Comment by SSE4** [comment]
@danimtb is CI running the latest version?

**Comment by danimtb** [comment]
@SSE4 yes, it is updated.

I found the issue. It was failing at parsing the output due to CONAN_PRINT_RUN_COMMANDS=1
```
----Running------
> cmake --version
-----------------
cmake version 3.16.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Pull request merged**
