### PR TITLE
adding releases.md file to conan center

### PR DESCRIPTION
**Pull request by Dattax**
Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @Dattax !

Could please sign the [CLA](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=372)

**Comment by Dattax** [comment]
Just signed the CLA!

**Comment by memsharded** [comment]
Hi @Dattax 

As the releases are so closely tied to the website, I suggest moving these release notes to the website repo in https://github.com/conan-io/website, and leave this repo for the recipes and the building service automation, not mix it with the frontend.

**Comment by Dattax** [comment]
Ok, that's a good plan. I will move it there.

**Pull request closed without merging**
