### PR TITLE
[boost] Add `nowide` lib

### PR DESCRIPTION
**Pull request by fpelliccioni**
Specify library name and version:  **boost/1.74.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Could you please add something to the test_packge too?

**Comment by madebr** [comment]
@fpelliccioni

You will also need to run the `rebuild-dependencies` script.

**Comment by fpelliccioni** [comment]
> d something to the

Sure, like... what?

**Comment by fpelliccioni** [comment]
> @fpelliccioni
> 
> You will also need to run the `rebuild-dependencies.py` script.
> The script runs on Linux.
> I'm not sure about windows, I have seen some strange behavior of `git/boostdep` and don't trust it.

I tried to run the script on macOS but it end up with an error

```
ERROR: Unable to find 'boostdep/1.74.0' in remotes
Traceback (most recent call last):
  File "/Users/fernando/dev/conan-center-index/recipes/boost/all/rebuild-dependencies.py", line 481, in <module>
    sys.exit(main())
  File "/Users/fernando/dev/conan-center-index/recipes/boost/all/rebuild-dependencies.py", line 472, in main
    boost_collector.do_install_boostdep()
  File "/Users/fernando/dev/conan-center-index/recipes/boost/all/rebuild-dependencies.py", line 156, in do_install_boostdep
    subprocess.check_call(["conan", "install", "boostdep/{}@".format(self.boostdep_version), "-g", "json"])
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conan', 'install', 'boostdep/1.74.0@', '-g', 'json']' returned non-zero exit status 1.
```

I do not have a Linux box at hand.

**Comment by madebr** [comment]
Macos might work, I didn't test it though. It will probably work on all unixes.
Boostdep is from #2096

**Comment by prince-chrismc** [comment]
You can take the stock example off the website

Something like this https://github.com/conan-io/conan-center-index/pull/3872/commits/ceb127865a25e204659828fa0faf79f34d5a9a4a (near the bottom of the diff)

**Comment by fpelliccioni** [comment]
> d boostdep in the mean time, but there is an arg

I ran ...

`./rebuild-dependencies.py -U -v 1.74.0`

... on Linux and I got the same error:

`ERROR: Unable to find 'boostdep/1.74.0' in remotes`

Do you have the exact command to run, please?
Thanks!

**Comment by madebr** [comment]
The script has a `-h` option:
```
$ ./rebuild-dependencies.py -h
usage: rebuild-dependencies.py [-h] [--verbose] [-t TMPPATH]
                               [-d BOOSTDEP_VERSION] [-u GIT_URL] [-U]
                               [-o OUTPUTDIR] [-x] (-v BOOST_VERSION | -A)

optional arguments:
  -h, --help           show this help message and exit
  --verbose            verbose output
  -t TMPPATH           temporary folder where to clone boost (default is
                       system temporary folder)
  -d BOOSTDEP_VERSION  boostdep version
  -u GIT_URL           boost git url
  -U                   update the git repo
  -o OUTPUTDIR         output dependency dir
  -x                   unsafe fast(er) operation
  -v BOOST_VERSION     boost version
  -A                   All boost versions
```

So:
```
./rebuild-dependencies -d 1.75.0 -U -A
```
If you run the script multiple times, then you don't need to add the `-U` option, as it will update the git boost repo.
The boost repo is cloned to a temporary folder, so it will be cleared on reboot.

The `-v` option is to only update the dependencies of one particular boost version.
Since we want to update all boost versions, add `-A`.
(`-A` and `-v` cannot be used together)

**Comment by fpelliccioni** [comment]
> The script has a `-h` option:
> 
> ```
> $ ./rebuild-dependencies.py -h

I know, but everything you explain below is not easy to deduce using the `-h`.

Thank you!

**Comment by madebr** [comment]
Depending on what pr gets merged first (yours or #3872), the scripts will have to be re-run because #3872 adds nowide and yours adds a nowide option.

**Comment by fpelliccioni** [comment]
> Depending on what pr gets merged first (yours or #3872), the scripts will have to be re-run because #3872 adds 1.75.0 and yours adds a nowide option.

I will look at the progress of #3872

**Comment by madebr** [comment]
@fpelliccioni 
Is it ok for you if I add nowide to #3872?

**Comment by fpelliccioni** [comment]
> ```
> ./rebuild-dependencies -d 1.75.0 -U -A
> ```
> 

I ran 

`python rebuild-dependencies.py -d 1.75.0 -U -A`

and I am still getting:

```
boostdep/1.75.0: Not found in local cache, looking in remotes...
boostdep/1.75.0: Trying with 'conan-center'...
ERROR: Unable to find 'boostdep/1.75.0' in remotes
Traceback (most recent call last):

```

**Comment by fpelliccioni** [comment]
> nd it's better for the enviro

Sure, please, do it.

**Comment by madebr** [comment]
@fpelliccioni 
Can you check #3872?

**Comment by prince-chrismc** [comment]
closed by https://github.com/conan-io/conan-center-index/pull/3872/files#diff-77170adeb770425c4dd279e9597262497d55f2c26bb169182cb1d9ddc71ff152R19

**Pull request closed without merging**
