### PR TITLE
libgettext 0.21

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **libgettext/***

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
So this file should be removed, because libgettext shouldn't be deprecated.

**Comment by ericLemanissier** [comment]
OK I will

**Comment by SpaceIm** [comment]
I think this file was added before implementation of deprecated attribute. The file by itself is useless for conan or conan-center logic.

**Comment by ericLemanissier** [comment]
Yes. It was a reminder for future contributors

**Review by SpaceIm — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
