### PR TITLE
Updated sqlcipher OpenSSL dependency to 1.1.1h

### PR DESCRIPTION
**Pull request by madduci**
Specify library name and version:  **sqlcipher/4.4.0**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Comment by uilianries** [comment]
Weird, I can't believe only that update can cause the error.

**Comment by ericLemanissier** [comment]
is the presence of `@` in paths really supported by msvc?

**Comment by uilianries** [comment]
@ericLemanissier Yes, it means the job number. Take a look here: https://c3i.jfrog.io/c3i/misc/logs/pr/3148/2/libqrencode/4.1.1/2d9bdce2f2abc84a245dbc72936bde3cc54040d7/create_stdout.txt

**Comment by Croydon** [comment]
I can build sqlcipher/4.3.0 both with OpenSSL 1.1.1h and 1.1.1g with VS2019 locally

**Comment by Croydon** [comment]
Let's see: https://github.com/conan-io/conan-center-index/pull/3161

**Comment by Croydon** [comment]
Current revision does not build. Updating OpenSSL has nothing to do with it

**Comment by jgsogo** [comment]
Found the issue, requires a [change in the infra](https://github.com/conan-io/conan-center-index/pull/3162#issuecomment-706247371). Just a little bit of patience. Thanks!

**Review by jgsogo — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
