### PR TITLE
xnnpack: add version cci.20230715, add package_type

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **xnnpack/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
I have to update cpuinfo recipe because xnnpack/cci.20230715 requires newer cpuinfo.

**Comment by SpaceIm** [comment]
> I have to update cpuinfo recipe because xnnpack/cci.20230715 requires newer cpuinfo.

You can't globally update I think. New version of cpuinfo doesn't seem to be compatible with old versions of xnnpack.

**Comment by toge** [comment]
@SpaceIm 
Thanks a lot!
I try to update this recipe.

**Comment by toge** [comment]
Oh no.
```
ERROR: Missing prebuilt package for 'cpuinfo/cci.20220228'
Use 'conan search cpuinfo/cci.20220228@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=cpuinfo'
```

**Review by RubenRBS — APPROVED** [review]

**Review by czoido — APPROVED** [review]

**Pull request merged**
