### PR TITLE
cctag: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
waiting for https://github.com/conan-io/conan-center-index/pull/13406 (which is also waiting for https://github.com/conan-io/conan-center-index/pull/13285).

**Comment by SpaceIm** [comment]
don't close, still waiting for fix of conflicts in opencv dependency graph

**Review by jwillikers — DISMISSED** [review]

**Comment by SpaceIm** [comment]
```
CMakeFiles/CCTag.dir/cctag/utils/FileDebug.cpp.o:(.bss+0x4): multiple definition of `boost::phoenix::placeholders::uarg8'
CMakeFiles/CCTag.dir/cctag/Bresenham.cpp.o:(.bss+0x4): first defined here
```

I'll revert to boost 1.80.0 due to a bug in 1.81.0: https://github.com/boostorg/phoenix/issues/111

**Comment by SpaceIm** [comment]
```
ERROR: Missing binary: onetbb/2020.3:f42ebec2d0ee7d5c41713cd8eee15cf988b0d202
onetbb/2020.3: WARN: Can't find a 'onetbb/2020.3' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MT, compiler.version=15, os=Windows
- Options: shared=True, tbbmalloc=False, tbbproxy=False
- Dependencies: 
- Requirements: 
- Package ID: f42ebec2d0ee7d5c41713cd8eee15cf988b0d202

ERROR: Missing prebuilt package for 'onetbb/2020.3'
Use 'conan search onetbb/2020.3@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=onetbb'
```

what?

**Review by jwillikers — DISMISSED** [review]

**Comment by uilianries** [comment]
@SpaceIm I would skip shared=True + MT with ConanInvalidConfiguration, as we can't skip it internally. We don't have black/white lists in C3I jenkins to skip packages. In case it's really needed, I could say people will open an issue asking for.

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
