### PR TITLE
eudev: Add recipe

### PR DESCRIPTION
**Pull request by jwillikers**
Specify library name and version:  **eudev/3.2.12**

[eudev](https://github.com/eudev-project/eudev) is an alternative implementation of systemd's libudev library.
This package indicates this with `provides = "libudev"`.
A `libblkid` Conan package is missing, but should be added and default enabled in this package. Here's an attempt at that:  #22426

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jwillikers** [comment]
@RubenRBS Would you have any insight into this CI failure?

**Comment by RubenRBS** [comment]
Rebuilding those missing binaries now, thanks for the ping :)

**Comment by RubenRBS** [comment]
We're going to implement a mechanism for PR's to be automatically retriggered when its corresponding builds are completed, sorry about the delay! :)

**Comment by uilianries** [comment]
Just started an internal build to generate kmod.

**Comment by uilianries** [comment]
Generated kmod/30 yesterday: https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/prod-v2/TapaholesRepo/319/summary.json

**Review by valgur — APPROVED** [review]

**Comment by jwillikers** [comment]
I've enabled blkid now that it's a separate component!

**Comment by jwillikers** [comment]
Alright, @RubenRBS I think this is ready now, but just needs that missing `kmod` binary for v2.

**Review by valgur — APPROVED** [review]

**Comment by RubenRBS** [comment]
This comes from kmod being a `shared-library`, but it requires opencv as static, and thus when this recipe is built as shared (Where we pass `*:shared=True`), it gets opencv as a missing dependency - Will check with the team about how to best handle these cases tomorrow, will let you know

**Comment by jwillikers** [comment]
@RubenRBS Any developments?

**Comment by uilianries** [comment]
hello @jwillikers Sorry the delay, we have a hotfix prepared and tested. We update the infra on Wednesdays https://github.com/conan-io/conan-center-index/discussions/20497, so it should be fixed by tomorrow, after the maintenance window.

**Comment by jwillikers** [comment]
> hello @jwillikers Sorry the delay, we have a hotfix prepared and tested. We update the infra on Wednesdays #20497, so it should be fixed by tomorrow, after the maintenance window.

@uilianries Awesome, thank you!

**Review by RubenRBS — APPROVED** [review]
Yay

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
