### PR TITLE
[7zip/19.00] Use msys2/20161025 for providing make for mingw builds

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **7zip/19.00**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Continuation of #154 
When building 7zip using mingw on Windows, we need `make`.
This is provided by `msys2/20161025`.

### CODE REVIEW

**Comment by madebr** [comment]
`conandata.yml` from `7zip` was already non-conforming to KB-H030, so this error is expected.

(Is there a legal way to add multiple sources?)

**Comment by Croydon** [comment]
Should we maybe make this depending on if `CONAN_BASH_PATH` is NOT set? 🤔 

https://docs.conan.io/en/latest/reference/env_vars.html#conan-bash-path-env

**Comment by madebr** [comment]
@Croydon 
so something like this?
```
if os.environ.get("CONAN_BASH_PATH", None) is None:
    if self.settings.compiler != "Visual Studio":
        self.build_requires("msys2/20161025")
```

**Comment by Croydon** [comment]
Yes, exactly

**Comment by danimtb** [comment]
@madebr could you please take a look at the comments of the bot? We recently introduced a new check validating the conandata.yml syntax and this PR triggered the new check. Sorry for the inconvenience

**Comment by madebr** [comment]
@danimtb See #251

**Comment by madebr** [comment]
Overruled by #396

**Pull request closed without merging**
