### PR TITLE
qt 5.x: lowercase system libs + bump dependencies

### PR DESCRIPTION
**Pull request by SpaceIm**
for https://github.com/conan-io/hooks/pull/480

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
```
There is not enough space on the disk.
Error copying C:\J\w\prod\BuildSingleReference\s\e8821a\1\qt5\qtbase\src\corelib\kernel\qobject_p.h to C:\J\w\prod\BuildSingleReference\s\892c22\1\include\QtCore\5.15.8\QtCore\private\qobject_p.h: Cannot create C:\J\w\prod\BuildSingleReference\s\892c22\1\include\QtCore\5.15.8\QtCore\private\qobject_p.h for output
```

:(

**Comment by SpaceIm** [comment]
```
rcc C:\J\w\prod\BuildSingleReference@8\s\e2a630\1\qt5\qttools\src\assistant\help\helpsystem.qrc 
..\..\..\include\QtHelp\QtHelpDepends(8): fatal error C1085: Cannot write precompiled header file: '.pch\debug\Qt5Helpd_pch.pch': There is not enough space on the disk.
```

@danimtb @uilianries is there something to prune in c3i?

**Comment by uilianries** [comment]
@SpaceIm yes, as we use a same machine to build more than one PR at same time, some build can be huge enough to eat all disk left and still need more. Qt is a known case. We will need to restart, but check the disk first. Thank you for pinging.

**Comment by SpaceIm** [comment]
Still this disk space issue, again & again :(

**Comment by ericLemanissier** [comment]
We may have to disable qttools and qttranslations by default. I don't know how much disk space they take on Visual studio debug.

**Comment by SpaceIm** [comment]
> We may have to disable qttools and qttranslations by default. I don't know how much disk space they take on Visual studio debug.

But they were build before without this disk space issue, correct?

**Comment by ericLemanissier** [comment]
Yes, they have been built since October 30th : https://github.com/conan-io/conan-center-index/commit/7e292bc025078633df6537fe50204423729c8672#diff-a8b177bc27deaf5165ec2e51c7e70bb42587ec0352c5bc2711524d5240e03737R139
Also, other package seem to have the same problem https://github.com/conan-io/conan-center-index/issues/15755
In any case, as we currently have no (public) plan for the resolution of the root cause in C3I, I think it's worth a try

**Comment by kambala-decapitator** [comment]
awaiting merge of #16404

**Comment by SpaceIm** [comment]
I'll fix casing of system libs in https://github.com/conan-io/conan-center-index/pull/17030

**Pull request closed without merging**
