### PR TITLE
quazip/1.3: Change minimum cpp version to 17

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **quazip/1.3**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Can you point an upstream issue which requires it or a log error?

**Comment by MartinDelille** [comment]
@uilianries Yes: https://github.com/stachenov/quazip/issues/145

**Comment by MartinDelille** [comment]
Fix https://github.com/conan-io/conan-center-index/issues/11313

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
@MartinDelille Thank you!

**Review by ericLemanissier — APPROVED** [review]

**Comment by MartinDelille** [comment]
Any idea what is going wrong here ?

**Comment by uilianries** [comment]
@MartinDelille I just restarted the CI build. Let's wait the result.

**Pull request merged**
