### PR TITLE
qt6: bump reqs

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **qt/6.***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
qt5 also needs a new build.

**Comment by ericLemanissier** [comment]
for qt5 => https://github.com/conan-io/conan-center-index/pull/9609 or https://github.com/conan-io/conan-center-index/pull/9558 or https://github.com/conan-io/conan-center-index/pull/9507

**Comment by SpaceIm** [comment]
ok, but I don't see bump of requirements in these PRs, and we have a new major version of harfbuzz (major version of dependencies contribute to package id).

**Comment by ericLemanissier** [comment]
done in https://github.com/conan-io/conan-center-index/pull/9609

**Comment by SSE4** [comment]
> ok, but I don't see bump of requirements in these PRs, and we have a new major version of harfbuzz (major version of dependencies contribute to package id).

qt was blocked due to the infrastructure error (missing `lzma` in python).
bump version label only applies to semver (I don't know if Qt follows it)

**Pull request merged**
