### PR TITLE
automake: modernize

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **automake/all**

This recipe suffers from the same problem as described in #6673 and #6674,
but now with running `autoconf`.

Adding `autoconf/2.71` as a build requirement does not fix the problem.

Running with `-pr:b default64 -pr:h default64` gives the following error:
```
checking whether autoconf is installed... no
configure: error: Autoconf 2.65 or better is required.
    Please make sure it is installed and in your PATH.
automake/1.16.3: 
```

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SSE4 — APPROVED** [review]

**Comment by jgsogo** [comment]
Is it ok to remove the `arch` in this package? Will `MacOS - armv8` run binaries for `MacOS - x64`?

**Comment by madebr** [comment]
It should. A test should confirm that though.

**Comment by madebr** [comment]
@jgsogo 
`automake` and `autoconf` are (in theory) header-only packages.
Is it ok to leave these packages like they are until c3i learns to test header packages on all platforms?

**Comment by jgsogo** [comment]
> @jgsogo
> `automake` and `autoconf` are (in theory) header-only packages.

😓 

> Is it ok to leave these packages like they are until c3i learns to test header packages on all platforms?

Yes, I think it is more useful to have a working recipe than something that could fail if we change the CI. I've been talking with @SSE4 and during this month we should have something ready to test header-only packages on all platforms, by that time I would ask you to remove the _workaround/patch_ and generate just one package.

**Review by jgsogo — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
