### PR TITLE
openssl: fix builddirs and add vars module file to cmake_find_package only

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@danimtb @uilianries @SSE4 CI is stuck in pending state.

**Comment by uilianries** [comment]
Yep, Jenkins finished that build and it passed, but didn't notify, or Github didn't receive. We can restart and see if receives a new notification.

**Comment by uilianries** [comment]
new build started, let's see now.

**Comment by uilianries** [comment]
Well, didn't work. @jgsogo @danimtb it seems like Jenkins didn't notify or github didn't receive the build result.

**Comment by danimtb** [comment]
@uilianries yeah, it didn't work but the latest build ended correctly. We have to merge it manually

**Review by danimtb — APPROVED** [review]

**Review by mathbunnyru — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
