### PR TITLE
date: support gcc14 on test_package

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **date/***

In gcc14 and msvc, there are compilation errors on building test_package.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi @toge thanks a lot! Posting the before and after logs for gcc would be great, as we're not yet building that configuration to test it ourselves, so it would help a ton for future traceability, thanks!

**Review by AbrilRBS — APPROVED** [review]

**Review by AbrilRBS — DISMISSED** [review]
Thanks!

**Review by jcar87 — CHANGES_REQUESTED** [review]
it shouldn't be necessary to publish a new recipe revision for this! 

note to team: the pipeline should be able to handle fixing a test package without requiring to publish recipe revisions (or rebuilding packages from new revisions)

**Comment by jcar87** [comment]
> note to team: the pipeline should be able to handle fixing a test package without requiring to publish recipe revisions (or rebuilding packages from new revisions)

note to self - fixing this asap ;)

**Review by AbrilRBS — APPROVED** [review]
The fix to support test_package only changes is now live, thanks!

**Review by jcar87 — APPROVED** [review]
Thanks!
I've modified the test package to minimise it as much as possible - ensuring that when there is a library to test, we check a symbol from that library, and nothing else. 
This helps with ongoing maintenance and hopefully will be more robust to compiler updates...
(I did test it with gcc-14 on Linux)

**Review by AbrilRBS — APPROVED** [review]

**Pull request merged**
