### PR TITLE
Remove add method for build_requires

### PR DESCRIPTION
**Pull request by uilianries**
Remove `build_requirements.add` from nasm

Specify library name and version:  **nasm/2.14**

related issue: https://github.com/conan-io/hooks/issues/175

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
@danimtb seems like we have a bug here
@uilianries maybe without rename?

**Comment by jgsogo** [comment]
@uilianries can you send a PR changing only the `build_requirements.add` call?  and we leave this PR to investigate the bug in the CI

**Comment by uilianries** [comment]
Yes, I gonna revert the folder name

**Comment by uilianries** [comment]
@jgsogo all good now.

**Comment by uilianries** [comment]
I've forgotten *RWindows from CI :facepalm: 

* RWindows is the brazilian expression for the words Ruin (bad) + Windows = RWindows.

**Comment by danimtb** [comment]
> @danimtb seems like we have a bug here
> @uilianries maybe without rename?

I don't think the error above is a bug as the config.yml file was still pointing to the "ALL" folder, not to the new "all" one. So I think the error is legit in this case.

**Pull request merged**
