### PR TITLE
Autoconf: Remove instances of embedded absolute paths in scripts

### PR DESCRIPTION
**Pull request by jcar87**
Specify library name and version:  **autoconf/all**

## Summary of changes
Refactor the way in which relocatability is handled such that the scripts will fallback to looking for resources relative to themselves inside the package folder.

* Perl scripts: remove instances of embedded path to install prefix passed at build time, and fall back to directory relative to script iself, an embedded path to m4 as well. 
* Bash script: same logic - reference the directory of the script itself
* Use canonical `autom4te_perllibdir` instead of forcing a Conan-specific upper case one - since the script can now fallback to finding the correct one in all cases. Consumers using new conan integrations will have files generated that contain the right environment variable
* Remove `AC_MACRODIR` and `AUTOM4TE_PERLLIBDIR` for downstream consumers using legacy integrations - these were used _only_ internally by autoconf/autoreconf, which now fallback to loading them relatively. The rest of the variables are kept for compatibility. 
* Remove version 2.69. All instances in Conan Center use version 2.71 already, and this is only used as tool/build-requires so there is little need to maintain older versions.

These changes paves the way to:
* avoiding unix_path conversions in `package_info()` 
* consuming `autoconf` without having to define environment variables on the consumer side (this was technically already possible), as long as the scripts in the `bin` folder can be found in `PATH`

## More details
Mainly, this changes things like this:
```
my $pkgdatadir = $ENV{'autom4te_perllibdir'} || '/absolute/path/to/install/prefix/passed/at/build/type';
```
to
```
my $pkgdatadir = $ENV{'autom4te_perllibdir'} || "$scriptpath/../res/autoconf";
```

where `$scriptpath` is the path to itself.  This enables the use by consumers finding `autoconf` and `autoreconf` in `PATH` with the names only, without having to rely on environment variables. On the other hand, environment variables still work correctly.

### CODE REVIEW

**Review by uilianries — DISMISSED** [review]
LGTM @jcar87 thank you for your detailed description!

**Comment by SpaceIm** [comment]
@jcar87 thanks for taking the time to improve autoconf, it's a major pain in windows build of conan-center recipes. I think that deep testing against existing v1 & v2 conan center recipes should be done before merging this one.

**Comment by jcar87** [comment]
> @jcar87 thanks for taking the time to improve autoconf, it's a major pain in windows build of conan-center recipes. I think that deep testing against existing v1 & v2 conan center recipes should be done before merging this one.

Absolutely! I'm keeping this in draft until I have time to validate this further. So far results are promising and have tested this downstream with v1/v2 without issues.

**Comment by jcar87** [comment]
> @jcar87 thanks for taking the time to improve autoconf, it's a major pain in windows build of conan-center recipes. I think that deep testing against existing v1 & v2 conan center recipes should be done before merging this one. Good candidates:
> 
> * for MinGW: libcurl, libsodium, libsmacker, libusb-compat, cityhash, gdal < 3.5.0, faac, hidapi, zimg, gsl, cunit, libxcrypt, opusfile, readosm, univalue, wolfssl, xmlsec, xqilla, gf-complete, glpk, gumbo-parser, libdisasm, libexif, librasterlite, librasterlite2, libsafec, cairo, asn1c, sassc, pupnp
> * for msvc: cityhash, gsl, cunit, libsmacker, libusb-compat, univalue, wolfssl, glpk, libdisasm, libexif

Have tested all of these with both msvc and mingw/gcc:
* cityhash, gsl, cunit, libsmacker, libusb-compat, univalue, wolfssl, glpk, libdisasm, libexif
And additionally these on mingw:
* pupnp, hidapi, faac, libsodium, zimg


With 3 variants of the `autoconf` package:
A) as it currently is on the master branch
B) as it currently is on this pull request
C) with a more reduced package_inf() as follows 



<details><summary>modified package_info() </summary>

```
    def package_info(self):
        self.cpp_info.libdirs = []
        self.cpp_info.includedirs = []
        self.cpp_info.resdirs = ["res"]

        # TODO: to remove in conan v2
        bin_path = os.path.join(self.package_folder, "bin")
        self.env_info.PATH.append(bin_path)
        self.env_info.AUTOCONF = "autoconf"
        self.env_info.AUTORECONF = "autoreconf"
        self.env_info.AUTOHEADER = "autoheader"
```

(only keeping these environment variables since they are referenced externally without performing the unix path conversion on the other side, otherwise they could be removed too). 

</details>


A few failed only on mingw for unrelated reasons: glpk, hidapi, cityhash (also fail with the unmodified autoconf) - everything else built fine with the configurations mentioned above.

The behaviour is as expected:
* the executable scripts are found on the path
* when the scripts reference each other, or they reference the resource directory, it's all done relative without the need of environment variables

Conan 2 is a little more involved as it involves updating more recipes (automake, libtool, etc) - I do have working versions of these with similar patches, and the limited testing I've done indicates that it all works as expected as well.

**Review by danimtb — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
