### PR TITLE
tl-expected: don't set CMAKE_CXX_STANDARD

### PR DESCRIPTION
**Pull request by ericLemanissier**
this must be handled by conan_basic_setup

Specify library name and version:  **tl-expected/***

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Ok but now you have to patch upstream CMakeLists with target_compile_features(tl-expected PUBLIC cxx_std_11)

**Comment by ericLemanissier** [comment]
My take on this, is that letting cmake decide the cppstd on its own is not ok, because it leads to mixing several cppstds in the same dependency tree, which is wrong https://github.com/conan-io/conan/issues/6157#issuecomment-570552095
We have to check for cppstd in the recipe, and raise if it's not ok.

**Comment by SpaceIm** [comment]
> My take on this, is that letting cmake decide the cppstd on its own is not ok, because it leads to mixing several cppstds in the same dependency tree, which is wrong [conan-io/conan#6157 (comment)](https://github.com/conan-io/conan/issues/6157#issuecomment-570552095)
> We have to check for cppstd in the recipe, and raise if it's not ok.

I disagree, a good CMakeLists must use target_compile_features(), and the recipe must check cppstd if set in profile.

**Comment by ericLemanissier** [comment]
what's the point of calling target_compile_features if the recipe already makes sure the std is ok ?
it's totally fine if the upstream project calls target_compile_features, and it's a no-op for conan consumers if the recipe already checks the cppstd).
I don't understand why we would add target_compile_features calls by patching the sources of the project, or in the cmake wrapper file(if the recipe already checks the cppstd, which we agree is needed)

**Comment by SpaceIm** [comment]
> what's the point of calling `target_compile_features()` if the recipe already makes sure the std is ok ?

Do you want to break all recipes based on C++11 or higher?

conan injects `CMAKE_CXX_STANDARD` when cppstd is set, which is a wish for the upper bound C++ standard. `target_compile_features()` is a hard requirement for the lower bound, and this is what you would expect from a library.
`target_compile_features()` will:
- use default compiler standard if it's higher than minimum required C++ standard
- use a C++ standard higher or equal than minimum required C++ standard (and supported by the compiler) if default compiler standard is lower. Very important for AppleClang because C++98 is still the default standard.

> it's totally fine if the upstream project calls `target_compile_features()`, and it's a no-op for conan consumers if the recipe already checks the cppstd.

Sure it's fine, it's exactly what I say. Does `tl-expected` call `target_compile_features()`? I guess not, otherwise you PR would pass CI.

> I don't understand why we would add `target_compile_features()` calls by patching the sources of the project, or in the cmake wrapper file(if the recipe already checks the cppstd, which we agree is needed)

cppstd is not needed, it's better to set it for consistency in final project.

> EDIT: I disagree with the "if set in profile" part of your message. cppstd consistency across all packages of a graph is a hard requirement, because it has an impact on ABI (conan-io/conan#6157 (comment) again)

It's a corner case. How many recipe in CCI have this issue, 2? 3?

**Comment by ericLemanissier** [comment]
> > what's the point of calling `target_compile_features()` if the recipe already makes sure the std is ok ?
> 
> Do you want to break all recipes based on C++11 or higher?

We don't have to break anything, my plan is to update recipes one by one using the following process:
-remove CMAKE_CXX_STANDARD from the CMakeLists.txt file (test recipe and cmake wrapper)
-fix eventual errors by raising exceptions in `validate(self)`.
no user should be broken by this. they may have to explicitly define the cppstd conan setting, but it's ok, because it happens only for users who are in a situation where the default cppstd conan uses(which is the compiler's default) does not match what compiled libraries actually use, so in an ABI incompatibility situation.

> conan injects `CMAKE_CXX_STANDARD` when cppstd is set, which is a wish for the upper bound C++ standard.

cppstd is not a wish for upper/lower bound, it is a precise specification of the standard you want to be used across the dependency graph. This is why conan translates it to CMAKE_CXX_STANDARD, which is also an exact specification. Basically like all conan settings. ref https://github.com/conan-io/conan-center-index/issues/54#issuecomment-586006591


> > EDIT: I disagree with the "if set in profile" part of your message. cppstd consistency across all packages of a graph is a hard requirement, because it has an impact on ABI ([conan-io/conan#6157](https://github.com/conan-io/conan/issues/6157) (comment) again)
> 
> It's a corner case. How many recipe in CCI have this issue, 2? 3?

to quote @SSE4 on https://github.com/conan-io/conan/issues/6157#issuecomment-570552095, there are at least 2: gtest and fmt. See also https://cullmann.io/posts/cpp-standard-version-mix-up/



Regarding AppleClang, is the default cppstd really C++98  ? I found https://apple.stackexchange.com/a/393700 which says it's c++14 (and I don't have access to a mac, so I cannot do a quick test).

AppleClang is a good example of the problem: All the users who did not explicitely define conan's setting for cppstd, and create projects using libraries requiring c++11 or later (I guess most of the libraries on CCI currently) get compilation errors like the one above. They probably will google the error message to understand the problem, which will tell them to use set CMAKE_CXX_STANDARD for cmake, or whatever equivalent for their build system. In addition to the ABI problem I already mentionned, this is a very bad user experience, which would be highly improved if conan told them their cppstd is not supported from the start.

**Comment by SpaceIm** [comment]
> We don't have to break anything, my plan is to update recipes one by one using the following process:
-remove CMAKE_CXX_STANDARD from the CMakeLists.txt file (test recipe and cmake wrapper)
-fix eventual errors by raising exceptions in validate(self).
no user should be broken by this. they may have to explicitly define the cppstd conan setting, but it's ok, because it happens only for users who are in a situation where the default cppstd conan uses(which is the compiler's default) does not match what compiled libraries actually use, so in an ABI incompatibility situation.

I'm completly against that, but I've already explained why.

> cppstd is not a wish for upper/lower bound, it is a precise specification of the standard you want to be used across the dependency graph. This is why conan translates it to CMAKE_CXX_STANDARD, which is also an exact specification. Basically like all conan settings. ref #54 (comment)

`CMAKE_CXX_STANDARD` is not an exact specification, it's a wish for a specific C++ standard. If the compiler doesn't support this C++ standard, CMake fallbacks to maximum C++ standard supported by the compiler, older than the one requested.

> AppleClang is a good example of the problem: All the users who did not explicitely define conan's setting for cppstd, and create projects using libraries requiring c++11 or later (I guess most of the libraries on CCI currently) get compilation errors like the one above. They probably will google the error message to understand the problem, which will tell them to use set CMAKE_CXX_STANDARD for cmake, or whatever equivalent for their build system. In addition to the ABI problem I already mentionned, this is a very bad user experience, which would be highly improved if conan told them their cppstd is not supported from the start.

The only pb I see, is that CMake like generators are not able to propagate `cxx_std_xx` compile features of targets. If they were doing that properly as they should, there would be no issue.

**Comment by dmn-star** [comment]
> AppleClang is a good example of the problem: All the users who did not explicitely define conan's setting for cppstd
:-)
https://github.com/conan-io/conan-center-index/issues/4097#issuecomment-764450188

**Pull request closed without merging**
