### PR TITLE
fix(libselinux): add patch to link with pcre2 from conan instead of o…

### PR DESCRIPTION
**Pull request by ledocc**
…ne from system

Specify library name and version:  **libselinux/3.3**

Problem:
On my centos 7.9 docker image, I have not libpcre2-8.so installed. 
When package libselinux build, utils executables failed to link with libselinux because libpcre2-8 is not found.

Explication:
In the libselinux Makefile, libselinux.so library link with libpcre2-8.so.
Then executables in utils sub-directory are compiled and linked with libselinux.so. But on link command line, no information were provide to find libselinux dependencies (ex: -L/path/to/pcre2/lib_directory), so linker look for libpcre2 on the system, and this work fine in many case ... excepted when libpcre2-8.so in not installed on the system

Solution:
Provided information to linker to find libselinux dependencies.

Info:
Executables in utils sub-directory are not installed in libselinux package, so we could : 
 - patch the Makefile to disable the build utils sub-directory
 - remove utils sub-directory before run the build
 - any other solution to not build utils sub-directory
 - do nothing
 - add them to package

thought ?
---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Tobulus** [comment]
Hi @ledocc 
This sounds like it could potentially also fix this issue here: https://github.com/conan-io/conan-center-index/issues/15798

I can check this tomorrow :)

**Comment by Tobulus** [comment]
> Hi @ledocc This sounds like it could potentially also fix this issue here: #15798
> 
> I can check this tomorrow :)

Yep, its fixing the problem. Thanks!

**Review by Tobulus — APPROVED** [review]

**Comment by Tobulus** [comment]
> ### Conan v1 pipeline ❌
> Failure in build 1 (`843b43a560a1d18f0851e70f8be92e68cd7a7079`):
> 
> An unexpected error happened and has been reported. Help is on its way! 🏇
> 
> ### Conan v2 pipeline ✔️
> > **Note**: Conan v2 builds may be required once they are on the [v2 ready](https://github.com/conan-io/conan-center-index/blob/master/.c3i/conan_v2_ready_references.yml) list
> 
> All green in build 1 (`843b43a560a1d18f0851e70f8be92e68cd7a7079`):
> 
> * **libselinux/3.3@:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/3.3//summary.json))
> * **libselinux/3.2@:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/3.2//summary.json))
> * **libselinux/3.1@:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/3.1//summary.json))
> * **libselinux/3.0@:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/3.0//summary.json))
> * **libselinux/2.9@:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/2.9//summary.json))

What about this failure? Is someone taking care?
@RubenRBS or someone else

**Review by jwillikers — APPROVED** [review]

**Comment by Tobulus** [comment]
> > ### Conan v1 pipeline ❌
> > Failure in build 1 (`843b43a560a1d18f0851e70f8be92e68cd7a7079`):
> > An unexpected error happened and has been reported. Help is on its way! 🏇
> > ### Conan v2 pipeline ✔️
> > > **Note**: Conan v2 builds may be required once they are on the [v2 ready](https://github.com/conan-io/conan-center-index/blob/master/.c3i/conan_v2_ready_references.yml) list
> > 
> > 
> > All green in build 1 (`843b43a560a1d18f0851e70f8be92e68cd7a7079`):
> > 
> > * **libselinux/3.3@:**
> >   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/3.3//summary.json))
> > * **libselinux/3.2@:**
> >   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/3.2//summary.json))
> > * **libselinux/3.1@:**
> >   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/3.1//summary.json))
> > * **libselinux/3.0@:**
> >   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/3.0//summary.json))
> > * **libselinux/2.9@:**
> >   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19123/1/libselinux/2.9//summary.json))
> 
> What about this failure? Is someone taking care? @RubenRBS or someone else

@RubenRBS

**Review by Tobulus — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Review by franramirez688 — APPROVED** [review]

**Pull request merged**
