### PR TITLE
[boost] Avoid some components when building 1.85.0

### LINKED ISSUE #24313: [package] boost/1.85.0: missing 'boost_stacktrace_from_exception', 'boost_stacktrace_backtrace', 'boost_locale'
### Description

Unable to install boost 1.85.0 due to missing packages:
```
boost/1.85.0: WARN: Boost component 'locale' is missing libraries. Try building boost with '-o boost:without_locale'. (Option is not guaranteed to exist)
boost/1.85.0: WARN: Boost component 'stacktrace_backtrace' is missing libraries. Try building boost with '-o boost:without_stacktrace_backtrace'. (Option is not guaranteed to exist)
boost/1.85.0: WARN: Boost component 'stacktrace_from_exception' is missing libraries. Try building boost with '-o boost:without_stacktrace_from_exception'. (Option is not guaranteed to exist)
ERROR: boost/1.85.0: Error in package_info() method, line 1970
	raise ConanException(f"These libraries were expected to be built, but were not built: {non_built}")
	ConanException: These libraries were expected to be built, but were not built: {'boost_stacktrace_from_exception', 'boost_stacktrace_backtrace', 'boost_locale'}
```

### Package and Environment Details

* Operating System+version: **macos latest**
* Compiler+version: **GCC 14**
* Conan version: **conan 2.4**
* Python version: **Python 3.12**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=14
os=Macos

[buildenv]
CC=/usr/bin/clang
CXX=/usr/bin/clang++

### Steps to reproduce

Create conanfile.txt with the following content:
```
[requires]
boost/1.85.0

[generators]
CMakeDeps
CMakeToolchain
```

run:
```
conan install . --output-folder=build --build=missing
```

more details available here: https://github.com/denismakogon/judy/actions/runs/9500317683/job/26183105246#step:7:2279

### Logs

logs can be found here https://github.com/denismakogon/judy/actions/runs/9500317683/job/26183105246#step:7:2279

### PR DESCRIPTION
**Pull request by uilianries**
### Summary
Changes to recipe:  **boost/1.85.0**

#### Motivation

The Boost 1.85.0 changed some requirements when build stacktrace.

For instance, when building on Mac Intel, it will require C++20, otherwise, some parts of
stacktrace and locale to work.

fixes #24313

/cc @denismakogon

#### Details

Disabled options values for failed components when building from Mac x86_64 and not using C++20.

@deniskovalchuk Could you please confirm this patch works? 

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by denismakogon** [comment]
I assume it will fix the problem for the rest of the versions, right?

**Comment by uilianries** [comment]
> I assume it will fix the problem for the rest of the versions, right?

@denismakogon  It's exclusive for 1.85.0. Have you seen the same error with older versions? 

As I commented before, in Boost 1.85.0 they changed more things related to C++20 and stacktrace, so I'm sure if 1.84.0 is affected too.

**Comment by denismakogon** [comment]
@uilianries
> Have you seen the same error with older versions?

I do, I mentioned it in the ticket. All versions from 1.81 are affected. You could've seen it in the Actions logs. The first version I saw it failing was 1.82.0, then I tried all of them up to 1.75.

**Comment by uilianries** [comment]
Fixed on issue #24313

**Pull request closed without merging**
