### PR TITLE
cli11 / Fix typo in license name: BDS -> BSD

### PR DESCRIPTION
**Pull request by bsergean**
Specify library name and version:  **cli11/1.9.1**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

This is a typo fix so all the above isn't applicable.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]
Nice catch!

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
#2259 Seems like someone cheated to get this merged 😱

**Comment by ericLemanissier** [comment]
by the way, it passed on FreeBSD: https://github.com/ericLemanissier/conan-center-index/runs/1784615834?check_suite_focus=true

**Review by theirix — APPROVED** [review]

**Comment by mathbunnyru** [comment]
@bsergean could you please ask to add you to the EAP here?
https://github.com/conan-io/conan-center-index/issues/4

**Review by mathbunnyru — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/issues/4#issuecomment-784401952

Shouldn't be long till you are added, it's a weekly job

**Comment by uilianries** [comment]
That's a good excuse for introducing https://github.com/conan-io/hooks/blob/master/hooks/spdx_checker.py in CCI.

**Pull request merged**
