### PR TITLE
librdkafka: add package_type + bump dependencies

### PR DESCRIPTION
**Pull request by SpaceIm**
- bump dependencies and use version range for openssl
- add package_type
- remove workarounds for 2  issues (includedirs/libdirs/bindirs of components, and PKG_CONFIG_PATH for CMake) fixed in conan 1.50.0 & 1.55.0 respectively. This is why required_conan_version is updated to 1.55.0

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@SpaceIm and others. Do not version ranges require square brackets, like specified in:
- https://docs.conan.io/2/tutorial/consuming_packages/intro_to_versioning.html
- https://docs.conan.io/2/tutorial/versioning/version_ranges.html
- https://docs.conan.io/2/reference/conanfile/attributes.html#version-ranges-reference
- https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges ?

**Comment by SpaceIm** [comment]
Yep, typo...

**Comment by ericLemanissier** [comment]
see https://github.com/conan-io/conan-center-index/pull/17519

**Comment by prince-chrismc** [comment]
Thats a tough one completely missed it too, and I clsoely looked at it RIP, thanks eric for following up 👍

**Pull request merged**
