### PR TITLE
 Bump version Flatbuffers 2.0.0

### PR DESCRIPTION
**Pull request by mtrzas**
Specify library name and version:  flatbuffers/2.0.0

Bump version of flatbuffers to 2.0.0

---

- [+] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [+] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [+] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [+] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by mjvankampen** [comment]
You need to patch this file https://github.com/google/flatbuffers/blob/master/CMake/Version.cmake as we are not using a git repo. I think you can just remove line 6 through 26.

**Comment by SpaceIm** [comment]
Yes, replace `if(GIT)` by `if(0)` in this file.

**Comment by SpaceIm** [comment]
To fix 2.0.0, please add in conanfile.py:

-  In `package()`, below `tools.rmdir(os.path.join(self.package_folder, "lib", "cmake"))`:

   ```python
   tools.rmdir(os.path.join(self.package_folder, "lib", "pkgconfig"))
   ```

- In `package_info()`, below `self.cpp_info.names["cmake_find_package_multi"] = "flatbuffers"`:

```python
self.cpp_info.names["pkg_config"] = "flatbuffers"
```

**Comment by SpaceIm** [comment]
And for errors in 1.11.0 and clang >= 10, you'll need to add a patch (which one, I don't know), this configuration was not tested the last time flatbuffers recipe was updated.

**Comment by mjvankampen** [comment]
@SpaceIm wouldn't it be better to raise a invalid configuration?

**Comment by SpaceIm** [comment]
Not if the error comes from -Werror or /WX.

**Comment by mjvankampen** [comment]
Maybe it's nicer to use the flatbuffers suggested method:

afbeelding

**Comment by mjvankampen** [comment]
@mtrzas I think if you run the CI again (close/open PR) it'll work due to #6023 going in!

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
> Maybe it's nicer to use the flatbuffers suggested method:
> 
> afbeelding

Good point, to keep in mind for another PR.

**Review by SpaceIm — APPROVED** [review]

**Pull request merged**
