### PR TITLE
libuv: add version 1.41.0

### PR DESCRIPTION
**Pull request by yipdw**
Specify library name and version:  **libuv/1.41.0**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.  **Tested with Conan 1.33.1.**
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated. **Tested on gcc 10; no hook errors reported using conan-center hooks @ https://github.com/conan-io/hooks/commit/20e51f130421d0ac60b70df2798ce82cffc773e9.

---

Some topics for discussion:

## v1.41.0 is pulled from dist.libuv.org

In this PR, I am using tarballs from dist.libuv.org.  This is a response to https://github.com/conan-io/conan-center-index/issues/4518; although that is a different project, I think it would be good to use tarballs from projects' official distribution sites.  The SHA-256 was run on a tarball that passed `gpg --verify` on https://dist.libuv.org/dist/v1.41.0/libuv-v1.41.0.tar.gz.sign.

The tarballs from dist.libuv.org expand to `libuv-v1.41.0`; the tarballs from Github expand to `libuv-1.41.0` (no `v`).  I think we should modify all previous versions to _also_ use dist.libuv.org, but until that PR comes we need to handle both directory schemes.  The `glob.glob` bit was added to handle this.

## Possibly adding `-fno-strict-aliasing` to CFLAGS/CXXFLAGS

libuv 1.41's build process adds `-fno-strict-aliasing` to its build options on compilers that support it (e.g. gcc, clang).  This was done as a response to https://github.com/libuv/libuv/issues/1230 and is [now recommended for using libuv 1.x](https://github.com/libuv/libuv#-fno-strict-aliasing).  (A future 2.x version may change this.)
 
This option should be propagated to code that uses libuv or exposes libuv objects, so I'm thinking that the `libuv` recipe should also add `-fno-strict-aliasing` into `cpp_info.{cflags, cxxflags}` for compilers that support the flag.  This PR does not add this flag, but I think we should do this -- if we don't, we're planting unpleasant surprises to be dug up by newer compilers or improvements in compilation techniques (i.e. more aggressive LTO analysis). 

What do you think?

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Please do not backwards apply patches, see #3903 and related PR

**Comment by yipdw** [comment]
> Please do not backwards apply patches, see #3903 and related PR

I think the libuv patch satisfies the proposed criteria in `docs/policy_patching.md`, specifically:

> **Build system patches.-** In order to add libraries into ConanCenter sometimes 
it is necessary to apply patches so they can consume existing packages 
for requirements and binaries can be generated. These patches are totally 
needed for the purpose of ConanCenter and Conan keeps adding features trying 
to minimize these changes.

The libuv build system unconditionally builds both static and shared variants of the library, which seems to be a behavior designed to mimic what libuv's autoconf-based system does.  If we want to build either the static or the shared library variant (but not both) then we need to patch the build system.

To be clear, I don't have any information on whether the libuv developers would reject such a change; I guess I just haven't had any reason to expect that they'd accept it.  We can try, though.

**Comment by prince-chrismc** [comment]
I am terribly sorry my comment was far to vague.

I was referring to your opening description (which thank you for writing it)

> libuv 1.41's build process adds -fno-strict-aliasing to its build options on compilers that support it (e.g. gcc, clang). This was done as a response to libuv/libuv#1230 and is now recommended for using libuv 1.x. (A future 2.x version may change this.)

That change shouldn't be back ported...

But the patch applied currently is very good

**Comment by SpaceIm** [comment]
> In this PR, I am using tarballs from dist.libuv.org. This is a response to #4518; although that is a different project, I think it would be good to use tarballs from projects' official distribution sites. The SHA-256 was run on a tarball that passed gpg --verify on https://dist.libuv.org/dist/v1.41.0/libuv-v1.41.0.tar.gz.sign.
> 
> The tarballs from dist.libuv.org expand to libuv-v1.41.0; the tarballs from Github expand to libuv-1.41.0 (no v). I think we should modify all previous versions to also use dist.libuv.org, but until that PR comes we need to handle both directory schemes. The glob.glob bit was added to handle this.

github is also an official distribution site of libuv: https://github.com/libuv/libuv#downloading

**Comment by yipdw** [comment]
> github is also an official distribution site of libuv: https://github.com/libuv/libuv#downloading

Oh, I missed that.  I'll switch to it back to github.com and remove the globbing bit, then.

**Comment by yipdw** [comment]
> > libuv 1.41's build process adds -fno-strict-aliasing to its build options on compilers that support it (e.g. gcc, clang). This was done as a response to [libuv/libuv#1230](https://github.com/libuv/libuv/issues/1230) and is now recommended for using libuv 1.x. (A future 2.x version may change this.)
> 
> That change shouldn't be back ported...
> 
> But the patch applied currently is very good

Sorry, I'm still confused.  Do you mean that we shouldn't backport the `-fno-strict-aliasing` change to libuv < 1.41? I agree that we should not do that, as those versions are indeed not necessarily built with `-fno-strict-aliasing`.

However, if building a version of libuv that is also built with `-fno-strict-aliasing` (which, for now, is libuv >= 1.41), it seems to me that it would be a good idea to add that to the package CFLAGS and CXXFLAGS.  Something like

```python
if self.version >= "1.41" and self._compiler_supports_no_strict_aliasing:  
   self.cpp_info.cflags += ["-fno-strict-aliasing"]
   self.cpp_info.cxxflags += ["-fno-strict-aliasing"]
```

where the definition of `_compiler_supports_no_strict_aliasing` is left as an exercise for later. :P

If my understanding of https://github.com/libuv/libuv/issues/1230 is correct, this only applies to TUs that directly link to libuv; TUs that use code from those TUs that link against libuv don't necessarily need this, though that depends on the API exposed by those libuv-linking TUs.

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
