### PR TITLE
reflect-cpp: add version 0.10.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **reflect-cpp/0.10.0**

reflect-cpp/0.7.0 supports bson and cbor, but this PR does not mention the two features.
Since reflect-cpp is a header-library and these features do not require extra definitions or configuration files, I do not see the need to add two options for them.

> For BSON support, you must also include the header <rfl/bson.hpp> and link to the libbson library (https://github.com/mongodb/libbson).
https://github.com/getml/reflect-cpp/blob/main/docs/bson.md

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
>  I do not see the need to add two options for them.

@toge wouldn't we need to at the very least add the requirements to the recipe?

**Comment by RazielXYZ** [comment]
Anyone who would want to use them could just require them to their own project that uses reflect-cpp and wants those backends. Core reflect-cpp won't have issues compiling without the serialization libraries as backends unless you try to include its specific header for that format/backend.

That said, I'm not sure what the best practice is for something like this. When I made the initial recipe I thought having them in would be helpful, but in that case we should probably keep being consistent with having them.

**Comment by RazielXYZ** [comment]
@RubenRBS any thoughts on this?

**Comment by RubenRBS** [comment]
Hi @RazielXYZ didn't realize you answered back, sorry for the delay, will have something for you tomorrow once I get back to reviewing PRs :)

**Comment by uilianries** [comment]
We have a similar recipe CCI with optional backend, so users need to include them as extra dependency. I would follow the same approach here, not installing these dependencies. Reading the headers and the cmake file, there is no mechanism like a ifdef or linkage that could break the project.

**Comment by RazielXYZ** [comment]
> We have a similar recipe CCI with optional backend, so users need to include them as extra dependency. I would follow the same approach here, not installing these dependencies. Reading the headers and the cmake file, there is no mechanism like a ifdef or linkage that could break the project.

So the suggestion is to remove the with_* options and requires from the recipe? Sounds fine to me

**Comment by uilianries** [comment]
> So the suggestion is to remove the with_* options and requires from the recipe? Sounds fine to me

Not exactly, let's keep with the current options to avoid breaking users.

**Review by RazielXYZ — APPROVED** [review]

**Comment by lkotsonis** [comment]
Should there be a separate PR for v0.8.0 that got out today?

**Review by valgur — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM. We can take an action over the options in another PR.

**Comment by uilianries** [comment]
> Should there be a separate PR for v0.8.0 that got out today?

@lkotsonis Yes, please. Could you open a new PR? Otherwise we would need to re-build this PR, but is actually good to be merged.

**Comment by lkotsonis** [comment]
> oh. In my local environment(17.7.2+d6990bcfa), it works fine. I try to find workaround.

Any update on this?

**Comment by toge** [comment]
@lkotsonis 
Sorry it took so long.

The reason why 0.8.0 does not pass CI is because 0.8.0 has a compile error in certain versions of msvc.
The latest msvc does not have this problem, so I am going to prepare an older msvc environment used by CI to investigate the cause.
I have not been able to take the time to do this. Please wait.

**Comment by lkotsonis** [comment]
> @lkotsonis 
> Sorry it took so long.
> 
> The reason why 0.8.0 does not pass CI is because 0.8.0 has a compile error in certain versions of msvc.
> The latest msvc does not have this problem, so I am going to prepare an older msvc environment used by CI to investigate the cause.
> I have not been able to take the time to do this. Please wait.

Just to be clear, I wasn't complaining. Thank you for taking care of this and for the useful information!

**Comment by toge** [comment]
@RubenRBS 
Colud you review it again?

If you think the options for dependand packages are mandatory(bson, toml, messagepack etc), I will add these options.

**Review by franramirez688 — CHANGES_REQUESTED** [review]
@toge Thanks a lot for the PR, it looks pretty well! Only one thing before moving this forward. We have to report that patch upstream and wait for the official solution to this bug. Otherwise, we could report it and add an extra step at validation time for that temporary invalid configuration while waiting for the official patch.

**Comment by toge** [comment]
@franramirez688 
Thank you for your review.
I create a PR for this.
Let's wait for reply.

**Comment by toge** [comment]
@franramirez688 
My patch has been merged.

**Review by franramirez688 — DISMISSED** [review]
@toge Great job! Thanks a lot for taking the time to report the patch upstream 👏 That's really appreciated.

**Review by RubenRBS — DISMISSED** [review]
Thanks for creating the upstream PR, it is supper appreciated! :)

**Comment by toge** [comment]
@RubenRBS 
Colud you review it again?
I forgot to remove dangling patch.

**Review by RubenRBS — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM https://github.com/getml/reflect-cpp/compare/v0.6.0...v0.10.0.patch

**Review by czoido — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
Sorry for the delay! Looks great now

**Review by franramirez688 — APPROVED** [review]

**Pull request merged**
