### PR TITLE
Add Nodejs

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **nodejs/13.6.0**

- NodeJS is a pre requirement for emsdk (https://github.com/conan-io/conan-center-index/issues/620)

Version 12.14.1 is LTS
Version 13.6.0 is the latest

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
BTW I tried to build from sources ... On Linux it took 2h to build only one profile :scream:

**Comment by czoido** [comment]
Hi @uilianries, just one question: shouldn't we take the 32-bit versions into account or maybe raise an invalid configuration if there are no installers available?

**Comment by uilianries** [comment]
@czoido there are installers for 32-bit, but not for all OS. As we dropped 32-bit support, I'm going to raise and error when trying to install such platform

**Comment by uilianries** [comment]
@czoido reading again, at line 13, only 64-bit is accepted: https://github.com/conan-io/conan-center-index/pull/632/files#diff-1fd4aa2024f47a355578a3c8d25620e7R13

**Pull request merged**
