### PR TITLE
json-c: add version 0.15

### PR DESCRIPTION
**Pull request by qchateau**
Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot)
Find more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)

Specify library name and version:  **json-c/0.15**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — DISMISSED** [review]

**Comment by qchateau** [comment]
I can't see where the error is in the logs

**Comment by uilianries** [comment]
I can't reproduce that error (I can't see it too), let's restart.

**Review by uilianries — DISMISSED** [review]

**Comment by SpaceIm** [comment]
Please take into account modifications in json-c build files to avoid building both shared and static (and maybe also properly manage PIC): https://github.com/json-c/json-c/compare/json-c-0.14-20200419...json-c-0.15-20200726#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a

**Comment by prince-chrismc** [comment]
https://github.com/json-c/json-c/compare/json-c-0.14-20200419...json-c-0.15-20200726#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR80

https://github.com/json-c/json-c/compare/json-c-0.14-20200419...json-c-0.15-20200726#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR115-R121

Good catch! These break functionality from the previous version

**Review by SSE4 — APPROVED** [review]

**Comment by qchateau** [comment]
I think this is what you expect ? Let me know

**Review by SpaceIm — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
