### PR TITLE
[sentry-native/0.6.0] + remove old versions

### PR DESCRIPTION
**Pull request by MartinDelille**
- [sentry-native/0.6.0] + remove old versions
- Remove performance option

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
wait for #16046 and #16047

**Comment by MartinDelille** [comment]
@Croydon Since you approved my last two depending PR and this one was left behind, may I ask you for review ?

**Review by Croydon — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@MartinDelille Please, avoid re-opening PRs for now. We have more +1000 builds to be processed and we don't want to crash the CI 🙏

**Comment by MartinDelille** [comment]
Ok sorry! 👍

**Pull request merged**
