### PR TITLE
add test for c_subscripts

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **newmat/all**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi! Thanks for your contribution. Can you explain the reasonale behind changing this default? It would be helpful in order to be able to validate the change

**Comment by AndreyMlashkin** [comment]
It is more or less a test if flag with_c_subscripts is relyably working. Because it does not on my end.

**Comment by RubenRBS** [comment]
I've pushed a change to fix the URL and get the option back to its default, as unless there's a good reason, we normally don't differ from upstream defaults :)

**Review by RubenRBS — APPROVED** [review]
Great job catching the defines bug! :)

**Pull request merged**
