### PR TITLE
Fix for Boost build failure on Windows when not able to find MSVC toolset

### PR DESCRIPTION
**Pull request by ivabrajer**
Specify library name and version:  **boost/1.74.0**

Closes https://github.com/conan-io/conan-center-index/issues/4338
Closes https://github.com/conan-io/conan-center-index/pull/4149

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Looks like my suggestion from https://github.com/conan-io/conan-center-index/pull/4149#issuecomment-756206216

Can you please add "closes #4149" in the opening comment 🙏 and please link the issue you already noted https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by prince-chrismc — APPROVED** [review]

**Comment by ivabrajer** [comment]
> Looks like my suggestion from [#4149 (comment)](https://github.com/conan-io/conan-center-index/pull/4149#issuecomment-756206216)
> 
> Can you please add "closes #4149" in the opening comment 🙏 and please link the issue you already noted https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Will do, no problem. Thanks for approving!

**Comment by prince-chrismc** [comment]
You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁

Boost is very massive and some days it's harder to get a build to pass

**Comment by ivabrajer** [comment]
Close/Re-open to trigger CI

**Comment by prince-chrismc** [comment]
> MSBUILD : error MSB4166: Child node "2" exited prematurely

Again...

One more restart is needed 🤞

**Comment by ivabrajer** [comment]
> Again...
> 
> One more restart is needed 🤞

Oh man, at least it's morning here so I can restart this thing the whole day.

**Comment by ivabrajer** [comment]
@prince-chrismc All passed, but since I'm not authorized to merge I have to wait for more reviewers or you can merge if you have permissions to do it.

**Comment by prince-chrismc** [comment]
Sadly no one has permission =) https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md#getting-your-pull-request-reviewed ... The the evil bots taking over the world 🤖

**Comment by prince-chrismc** [comment]
👋 This is a 4 line diff... please take a look 🙏 

@sse4
@uilianries
@madebr
@SpaceIm
@ericLemanissier
@Croydon
@intelligide
@theirix
@gocarlos
@mathbunnyru

**Review by madebr — APPROVED** [review]

**Review by mathbunnyru — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]
okay, I am really really tentative to approve that... it's just 4 lines diff, but situation isn't trivial, as I've said already, it might be fixing one thing, but breaking another thing (see https://github.com/conan-io/conan-center-index/pull/3362#issuecomment-719965620). it might be possible there is no way to make it working correctly for everyone, in the end. but as several people reported it improves workflows for them, let's merge it.

**Comment by prince-chrismc** [comment]
> but situation isn't trivial

:100: agreed

In your comment https://github.com/conan-io/conan-center-index/pull/3362#issuecomment-719968902, most people expecting it be multiple arguments are UNIX consumers... When using MSVC you typically expect it to be quoted (since it's picked up by default with spaces)

I hope this will keep both user bases happy 🤞

**Pull request merged**
