### PR TITLE
glib: Fix libdir for PkgConfigDeps

### PR DESCRIPTION
**Pull request by jwillikers**
Specify library name and version:  **glib/***

Required to update `gstreamer` to use PkgConfigDeps: #13400.

Related issue is here: conan-io/conan#12279.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Also fixed in https://github.com/conan-io/conan-center-index/pull/13440, but since I've also added a test_package for PkgConfigDeps and it's blocked by libffi recipe, it's fine to do a specific PR.

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by planetmarshall** [comment]
This does not appear to be fixed? `glib-2.0.pc` contains:

```
prefix=/home/andrew/.conan/data/glib/2.73.3/_/_/package/eb34e48f59e3766360e3256bde88ef47a36ecfe0
libdir1=${prefix}/lib
includedir1=${prefix}/include
includedir2=${prefix}/include/glib-2.0
includedir3=${prefix}/lib/glib-2.0/include
# Custom PC content
bindir=${prefix}/bin
glib_genmarshal=${bindir}/glib-genmarshal
gobject_query=${bindir}/gobject-query
glib_mkenums=${bindir}/glib-mkenums

Name: glib-2.0
Description: Conan component: glib-glib-2.0
Version: 2.73.3
Libs: -L"${libdir1}" -lglib-2.0 -lpthread 
Cflags: -I"${includedir1}" -I"${includedir2}" -I"${includedir3}" 
Requires: libpcre2
```

`libdir` and `includedir` are missing, which are required by downstream recipes.

**Comment by SpaceIm** [comment]
libdir & includedir are an internal detail of a pkgconfig file. What really matters is Libs, Cflags etc. If you really want libdir & includedir variables, it would require a PR on conan client side.

**Comment by jwillikers** [comment]
@planetmarshall @SpaceIm is right, fixes specific to the GLIB recipe would just be a temporary band-aid. Better to fix the issue in Conan for all such scenarios. I submitted conan-io/conan#12279 for this some time ago.

**Pull request merged**
