### PR TITLE
[libpq] Add support for dynamic builds with Visual Studio

### PR DESCRIPTION
**Pull request by SSE4**
* Fix source file lists to avoid link errors and to behave be as close as possible to the original MSVC projects.
* Generate more complete pg_config.h.
* Use .def file to make exported symbols work as expected.
* Add missing wldap32 library link in package_info().
* Enable dynamc build in conanfile.py

Specify library name and version:  **libpq/11.5**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Original related bug report: https://github.com/bincrafters/conan-libpq/pull/25
Original PR: https://github.com/conan-io/conan-center-index/pull/143

### CODE REVIEW

**Comment by SSE4** [comment]
@Talkless FYI I am going to implement an official way to build project for Visual Studio:
https://www.postgresql.org/docs/8.3/install-win32-libpq.html
https://github.com/postgres/postgres/blob/master/src/tools/msvc/README

**Comment by Talkless** [comment]
> @Talkless FYI I am going to implement an official way to build project for Visual Studio:

That would be best of course, good luck!

**Comment by Talkless** [comment]
@SSE4 I believe PostgreSQL requires ActivePerl, while Conan has Strawberry perl only? And for ActivePerl you need to register to download.. so I kinda doubt we can package that..?

**Comment by SSE4** [comment]
@Talkless I'll check it and let you know

**Comment by SSE4** [comment]
@Talkless I've checked locally, and it builds fine with `StrawberryPerl`

**Comment by SSE4** [comment]
@lasote is it possible some slave(s) use older (cached) version of packages?
e.g. strawberry perl still misses pc files:
```
Can't locate Win32API/File/cFile.pc in @INC (@INC contains: C:\J\c3ipr\pr_188_3_0_2\.conan\data\libpq\11.5\_\_\build\3a39ecdadc1d316422be7204374ad529b5fd8b77\source_subfolder\src\tools\msvc C:/J/c3ipr/pr_188_3_0_2/.short/574618/1/lib) at C:/J/c3ipr/pr_188_3_0_2/.short/574618/1/lib/Win32API/File.pm line 177.
```
but it was fixed at #189 (and works locally)

**Comment by SSE4** [comment]
@Talkless CI didn't relaunch build, and nothing helped (tried new commit, force push, open/close PR, open new PR, etc.). the only thing helped - creating another branch. there is an issue on CI side, but don't worry, there is new PR: https://github.com/conan-io/conan-center-index/pull/231

**Pull request closed without merging**
