### PR TITLE
glib/all: bump deps

### PR DESCRIPTION
**Pull request by ericLemanissier**
Generated and committed by [Conan Center Bump Deps](https://github.com/ericLemanissier/conan-center-index-bump-deps)
Find more updatable recipes in the [GitHub Pages](https://ericlemanissier.github.io/conan-center-index-bump-deps/)

Specify library name and version:  **glib/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@ericLemanissierBot build

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/5954404665)

**Comment by ericLemanissier** [comment]
@ericLemanissierBot build

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/5961626726)

**Comment by ericLemanissier** [comment]
@ericLemanissierBot build

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/5963373681)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/5963373681)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/5963373681)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/5963373681)

**Comment by ericLemanissier** [comment]
blocks:
- https://github.com/conan-io/conan-center-index/pull/19393

**Comment by uilianries** [comment]
Hi @ericLemanissier ! Did you close your PR by mistake?

**Comment by ericLemanissier** [comment]
@uilianries no, I reponned it as https://github.com/conan-io/conan-center-index/pull/19417. I wanted to see if it could generate msvc 193 binaries for glib/2.77.1 and glib/2.77.2, but it still does not :(

**Comment by uilianries** [comment]
@ericLemanissier okay, let's take a look! Thank you!

**Pull request closed without merging**
