### PR TITLE
qt 5.x: several fixes for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
- inject `VirtualRunEnv` in `build` scope (in case of native build) since path to shared libs of several requirements must be visible when executables built during qt build process are executed (because these executables link to some requirements).
- Also fix `DYLD_LIBRARY_PATH` workaround on macOS, it was broken (it's the same usage than previous point, but as usual SIP defeats everything, leading to this workaround).
- as a consequence, also remove some build requirements erroneously added by https://github.com/conan-io/conan-center-index/pull/16404 (see https://github.com/conan-io/conan-center-index/pull/16404#discussion_r1148160492). They are requirements actually, but their shared libs must be visible in PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH during build process as described in previous point.
- don't rely on `is_msvc()` in `package_id()` method, it's forbidden in conan v2.
- lowecase system libs if Windows (`uxtheme` instead of `UxTheme`)
- use modern generators & helpers in test package, and add test_v1_package
- use version range for openssl
- bump several dependencies
- prefer `openal-soft` in requirements over deprecated `openal` recipe

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — DISMISSED** [review]

**Comment by SpaceIm** [comment]
Converted to draft, v2 pipeline still fails, but I can't see the log yet.

**Comment by SpaceIm** [comment]
there was no test package for conan v2

**Comment by SpaceIm** [comment]
```
ERROR: Missing binary: jom/1.1.3:522dcea5982a3f8a5b624c16477e47195da2f84f

jom/1.1.3: WARN: Can't find a 'jom/1.1.3' package binary '522dcea5982a3f8a5b624c16477e47195da2f84f' for the configuration:
[settings]
arch=x86_64
os=Windows

ERROR: Missing prebuilt package for 'jom/1.1.3'
Check the available packages using 'conan list jom/1.1.3:* -r=remote'
or try to build locally from sources using the '--build=jom/1.1.3' argument
```

I've opened https://github.com/conan-io/conan-center-index/pull/17035

**Comment by SpaceIm** [comment]
> * inject `VirtualRunEnv` in `build` scope (in case of native build) since path to shared libs of several requirements must be visible when executables built during qt build process are executed (because these executables link to some requirements).

It's not sufficient on macOS when dependencies are shared (SIP my love...), and the workaround with `BASH_ENV` is broken (`DYLD_LIBRARY_PATH` is set to None in `bash_env` file). I'll provide a fix.

**Comment by SpaceIm** [comment]
Is their a c3i maintenance?

**Comment by SpaceIm** [comment]
v2 pipeline, msvc 192, shared:

```
C:\J\w\prod-v2\BuildSingleReference\p\qtebd2810f13ecd\s\qt5\qtbase\src\3rdparty\angle\src\libANGLE\renderer\d3d\d3d11\texture_format_table_autogen.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
jom: C:\J\w\prod-v2\BuildSingleReference\p\t\qt809d189331ab7\b\build_folder\qtbase\src\angle\src\libGLESv2\Makefile.Release [.obj\release\J\w\prod-v2\BuildSingleReference\p\qtebd2810f13ecd\s\qt5\qtbase\src\3rdparty\angle\src\libANGLE\renderer\d3d\d3d11\texture_format_table_autogen.obj] Error 1
DebugAnnotator9.cpp
jom: C:\J\w\prod-v2\BuildSingleReference\p\t\qt809d189331ab7\b\build_folder\qtbase\src\angle\src\libGLESv2\Makefile [release] Error 2
jom: C:\J\w\prod-v2\BuildSingleReference\p\t\qt809d189331ab7\b\build_folder\qtbase\src\angle\src\Makefile [sub-libGLESv2-make_first-ordered] Error 2
jom: C:\J\w\prod-v2\BuildSingleReference\p\t\qt809d189331ab7\b\build_folder\qtbase\src\angle\Makefile [sub-src-make_first] Error 2
jom: C:\J\w\prod-v2\BuildSingleReference\p\t\qt809d189331ab7\b\build_folder\qtbase\src\Makefile [sub-angle-make_first] Error 2
```

It works fine for me with Visual Studio 2022 :s

**Review by MartinDelille — DISMISSED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by prince-chrismc — COMMENTED** [review]
v2 test failed 😨 😩

**Comment by SpaceIm** [comment]
> v2 test failed 😨 😩

With Visual Studio only, and I can't reproduce this issue locally.

**Comment by ericLemanissier** [comment]
According to Google it's a "path too long" issue

**Pull request merged**
