### PR TITLE
libgit2: Rename 0.28.x recipe folder

### PR DESCRIPTION
**Pull request by intelligide**
Specify library name and version:  **libgit2/0.28.x**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

This PR moves the libgit2 0.28 recipe from `all` to `0.28.x` folder. This is a step for adding the 1.x.x recipe. Below 1.0.0, each minor version need its own recipe (because options changed). The next step will be to add the 1.x.x version recipe.

### CODE REVIEW

**Comment by SpaceIm** [comment]
1st commit is hard to review, `all` folder was not removed, therefore it's difficult to check differences.

**Comment by intelligide** [comment]
The system won't let me rename the folder. It gave me this error:
```
Only one library can be changed in the same PR: [libgit2/0.28.x, libgit2/all]
```
:sweat_smile:

**Comment by intelligide** [comment]
>     * `0.27.x` conanfile deserves the same Libssh2 fixes (in another PR I guess).

Fixed with #3029

**Comment by uilianries** [comment]
There is no information about why you are moving the folder, we need to search for libgit2 to understand the context. Please, update the PR description with more details.

**Comment by intelligide** [comment]
Done.

**Comment by uilianries** [comment]
Thank you!

**Review by uilianries — APPROVED** [review]

**Review by SpaceIm — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
