### PR TITLE
openjpeg: add missing CMake vars in CMakeDeps of openjpeg

### PR DESCRIPTION
**Pull request by SpaceIm**
fixes https://github.com/conan-io/conan-center-index/issues/19219

see https://github.com/uclouvain/openjpeg/blob/master/cmake/OpenJPEGConfig.cmake.in

OpenCV relies on these variables (instead of CMake target): https://github.com/opencv/opencv/blob/4.5.5/modules/imgcodecs/CMakeLists.txt#L44-L45

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@marxin it should fix your build issue of OpenCV with openjpeg as jpeg2000 backend

**Comment by marxin** [comment]
Great! What a quick fix. Yes, I can confirm it fixes my problem. Thank you!

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
@RubenRBS @uilianries could you review this one please?

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by RubenRBS** [comment]
Thanks for the ping and your patience :)

**Review by RubenRBS — APPROVED** [review]
Nice extra tests too :)

**Pull request merged**
