### PR TITLE
Mosquitto 2.x conan2

### PR DESCRIPTION
**Pull request by danicriss**
Specify library name and version:  **mosquitto/2.x**

Porting mosquitto/2.x to conan2

Note mosquitto/1.x was ported in https://github.com/conan-io/conan-center-index/pull/15714. Used its test_package, which is actually nicely done (comprehensive, at least compared to the existing 2.x conan v1 one)

Its libwebsockets dependency wasn't ported, and its current openssl dependency version also seems to have issues, so I disabled the respective flags in testing. Tested on Linux only, basically `conan create 2.x/conanfile.py --version=2.0.15 --user=dan --channel=local_run --profile:build=default --profile:host=default --options:host=ssl=False` and similarly for conan1. See the commit message(s) for details

Used hooks with conan1 as they haven't been ported to conan2

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by danicriss** [comment]
This PR fails the dynamic library build on Mac with

```
dyld: Symbol not found: _GENERAL_NAME_free
  Referenced from: [...]/.conan/data/mosquitto/2.0.15/[...]/lib/libmosquitto.1.dylib
  Expected in: flat namespace
 in /Users/jenkins/[...]/.conan/data/mosquitto/2.0.15/[...]/lib/libmosquitto.1.dylib
ERROR: mosquitto/2.0.15 (test package): Error in test() method, line 18
	self.run(bin_path, run_environment=True)
	ConanException: Error -6 while executing DYLD_LIBRARY_PATH="[...]/.conan/data/mosquitto/2.0.15/[...]/lib:[...]/.conan/data/openssl/1.1.1q/[...]/lib" DYLD_FRAMEWORK_PATH="" bin/test_package
```

That's when it tries to load the _test_package_ executable and fails to load the openssl dynamic lib required by the mosquitto lib in the conan package

Note it passes with the option `Shared == False` on Mac and also passes on Linux

Source:
- build https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/17007/5-configs/macos-clang/mosquitto/2.0.15//summary.json
- test log (failed) https://c3i.jfrog.io/c3i/misc/logs/pr/17007/5-configs/macos-clang/mosquitto/2.0.15//327ba68881e026e4f102a081f8376904399bd0da-test.txt

**Comment by danicriss** [comment]
I tried to reproduce this on a Mac of one of my colleagues and was not able to - the `conan test ...` command was successful

There was a slight difference in setup re. the versions

Failed build:
- SDK for MacOSX 11.3
- clang 13

My colleague's Mac:
- SDK for MacOSX 13.3
- clang 14

I'm not convinced it's the version which is the root cause of the failure though...

**Comment by danicriss** [comment]
The package recipe patches some Apple OS's regarding shared libaries - close enough. I thought I'd add "Macos" to the list of OSs where the patch is applied - but that didn't work

commit: https://github.com/conan-io/conan-center-index/pull/17007/commits/0f061ea6f3a37ca4dcfb0c4555318d8851e8229d

**Comment by danicriss** [comment]
I'm stuck on this port for mosquitto/2.x to conan2 - see above comments. Any help would be appreciated - ideally regarding fixing the problem itself, otherwise at least any pointers in how to replicate it, i.e. access to a virtual machine with the build environment that I can run?

@memsharded - tagging you just because your name stuck out when I was looking at conan issues in general ;)
@SpaceIm - tagging you because you're the top contributor here ;)

**Comment by danicriss** [comment]
Just to be clear - I'm referring to the conan1 builds

Conan2 builds are failing because the profiles used for the builds use an option which doesn't exist in mosquitto v2, only in mosquitto v1 - that's another discussion I want to defer until conan1 builds pass

**Comment by franramirez688** [comment]
Hi @danicriss 

First of all, thanks a lot for your contribution! I saw that you got stuck so I started working on another branch, but using your original one (keeping your commits for sure): https://github.com/conan-io/conan-center-index/pull/17507

I'm trying to make it pass for all the platforms 🤞 I'll tell you whenever I have the final version.

**Comment by danicriss** [comment]
@franramirez688 wow that's better than we expected, thanks so much for this! I looked at the new commits and realised I was a bit further from a clean build than I imagined - sorry for that

I have no attachment to the initial commits, so feel free to squash it all in the end if it's easier. Also if you get to green builds in your fork I'm happy to close this PR

I wanted to give you a heads-up that my original https://github.com/conan-io/conan-center-index/commit/0f061ea6f3a37ca4dcfb0c4555318d8851e8229d commit was only experimental, but I see you've nuked all that hard-coded patching in https://github.com/conan-io/conan-center-index/pull/17507/commits/a285beee3f0e9969be57c20eb84ca70acfdd6b2c so that's great

**Comment by franramirez688** [comment]
Hi @danicriss 

Thanks for your comments! 😁 
Now, it seems that it's properly working for a bunch of checks (https://github.com/conan-io/conan-center-index/pull/17507), so I think it's great for now 👏 
We could close this PR and wait for the other one to be approved by the reviewers.

**Pull request closed without merging**
