### PR TITLE
zserio: Add new Zserio release 2.14.1

### PR DESCRIPTION
**Pull request by Mi-La**
### Summary
Changes to recipe:  **zserio/2.14.1**

#### Motivation
New patch release 2.14.1

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by Mi-La** [comment]
@AbrilRBS, @uilianries Do you have any idea when it will work again? (Service Under Maintenance)

**Comment by Mi-La** [comment]
License is already signed, but the system cannot see it. Tried multiple times :-(.

**Comment by AbrilRBS** [comment]
@Mi-La this is because the commit was authored by @mikir https://api.github.com/repos/conan-io/conan-center-index/pulls/24667/commits, it's that account the one what should sign with the shown email there :)

**Comment by AbrilRBS** [comment]
The maintenance mode is expected to be over later today, but might roll over to the weekend if we find reasons to delay it, sorry for the delay!

**Review by AbrilRBS — APPROVED** [review]

**Review by valgur — APPROVED** [review]

**Review by toge — APPROVED** [review]

**Pull request merged**
