### PR TITLE
add ixwebsocket 11.2.4, which is compatible with mingw and allows sha…

### PR DESCRIPTION
**Pull request by bsergean**
…red libraries

Specify library name and version:  **ixwebsocket/11.2.3**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by bsergean** [comment]
We use the conanfile here -> https://github.com/machinezone/cobra/blob/master/sdk/cpp/conanfile.txt

**Comment by bsergean** [comment]
Previous work on it was done here -> 5428e873435a046a13d59404661e0ab7e9aee749

**Comment by jgsogo** [comment]
Hi! Our CI is not able to modify the status of this PR 🤷 ... but the failure is legit, you need to add an entry to the `conandata.yml` file with the URL to the sources of the new 11.2.3 version: https://github.com/conan-io/conan-center-index/blob/master/recipes/ixwebsocket/all/conandata.yml

**Comment by bsergean** [comment]
Just fixed it, thanks Javier !

**Review by danimtb — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Comment by jgsogo** [comment]
Easy fix! Just waiting for one more approval 😊

**Comment by czoido** [comment]
Hi @bsergean,
Looks like 11.2.4 is available: https://github.com/machinezone/IXWebSocket/tree/v11.2.4
Maybe we can update the PR?

**Review by czoido — CHANGES_REQUESTED** [review]
https://github.com/conan-io/conan-center-index/pull/5029#issuecomment-808115076

**Comment by bsergean** [comment]
Sure thing, I just updated the PR to use 11.2.4.

        if self.settings.compiler.cppstd:
            # After version 11.0.8, IXWebSocket is fully compatible with C++ 11. https://github.com/machinezone/IXWebSocket/commit/ee5a2eb46ee0e109415dc02b0db85a9c76256090
            tools.check_min_cppstd(self, 14 if tools.Version(self.version) < "11.0.8" else 11)


Is that blob of python the recommended way for conan-2 ?

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Please update the title 🙏

**Comment by bsergean** [comment]
done !

**Review by ericLemanissier — APPROVED** [review]

**Review by czoido — APPROVED** [review]

**Pull request merged**
