### PR TITLE
grpc: add version 1.67.1

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **grpc/1.67.1**

#### Motivation
There are several new components in 1.67.1.

#### Details
https://github.com/grpc/grpc/compare/v1.65.0...v1.67.1

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — COMMENTED** [review]
Thanks a lot @toge! In https://github.com/conan-io/conan-center-index/pull/25203 I identified missing dependencies that you have correctly identified, which is super great! I only have one minor question:

- Inhttps://github.com/conan-io/conan-center-index/pull/25203/files#r1760875461, I saw a plugin not listed here. Do you have any insight if this is needed? Thanks!

**Review by antonkesy — APPROVED** [review]

**Comment by toge** [comment]
@AbrilRBS 
Thank you for your review!
I updated `target_info` by checking the difference CMakeLists.txt between 1.65.0 and 1.67.0.
https://github.com/grpc/grpc/compare/v1.65.0...v1.67.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a

I'm going to check the list of #25203.

**Comment by toge** [comment]
@AbrilRBS 
Fixed.

I add `grpc_otel_plugin` entry in grpc_1.65.0.yml and grpc_1.67.0.yml.
And `otel_plugin` option has been added in conanfile.py.

But we can't build grpc recipe with `otel_plugin=True` due to opentelemetry-cpp having fixed version dependencies.
We have to wait for making `otel_plugin=True` until opentelemetry-cpp recipe has been improved.

**Comment by AbrilRBS** [comment]
Seems like this will work after all, the grpc requirement in opentelemetry-cpp should not be on by default, so I have turned it off in able to be able to use it here, but either way, we probably don't want it set to True by default here either, as in https://github.com/grpc/grpc/blob/74f245857247b4b3e28a753d85d06ae2d5a55434/CMakeLists.txt#L390C8-L390C37 it's marked as OFF by default

**Review by AbrilRBS — APPROVED** [review]
Thanks!

**Review by AbrilRBS — APPROVED** [review]

**Review by ErniGH — APPROVED** [review]
Thanks

**Pull request merged**
