### PR TITLE
Add OpenSSL to CMake

### LINKED ISSUE #1401: [cmake] cmake uses OpenSSL within its recipe but does not depend on it?
There are mentions of openssl within the conanfile, and cmake can be build with openssl dependency to allow download for https stuff. see: 
https://github.com/conan-io/conan-center-index/blob/master/recipes/cmake/all/conanfile.py#L52

However recipe present in this repository has no dependency even conditional one on openssl. 
This causes issues like this:
```
 Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
CMake Error at Utilities/cmcurl/CMakeLists.txt:454 (message):
```
When trying to build it on the systems that dont have libssl-devel installed by default.
Any particular reason why openssl was not added as a build requires even a conditional one?

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **cmake/any**

fixes #1401

cmake only requires openssl for linux and freebsd: https://gitlab.kitware.com/cmake/cmake/-/blob/master/CMakeLists.txt#L459

/cc @fulara

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by fulara** [comment]
@jgsogo cmake is statically depending on ssl - so its really only a build requires in that sense, 
Or you dont think that it should be treated as such in that case?

**Comment by jgsogo** [comment]
There are many things that we need to improve in the graph model, one of them is how to properly encode all the complexity of a C++ graph with private requirements, relations between shared-static libraries,... and this is something that will possibly break so we are delaying it to Conan 2.0.

Using a `build_requires` for a private requirement works here because `cmake` is a final tool and we are linking static, but if it were a regular library it would be needed to propagate some link information downstream. So this is not a general solution, but a hack that works for this use-case.

And it has one drawback. Using a `build_requires` it won't affect the CMake package ID, so it will be the same regardless of the `openssl` version. Again, this can work here for this recipe, but it is not "an example" of best practices.

**Comment by madebr** [comment]
Shouldn't the settings of the cmake recipe be changed to use `arch` and `os` instead of `arch_build` and `os_build`?

Doesn't this require a `ENABLE_OPENSSL` definition passed to `cmake.configure`? Or is this done automatically?
https://gitlab.kitware.com/cmake/cmake/-/blob/master/CMakeLists.txt#L564

**Comment by uilianries** [comment]
> Doesn't this require a ENABLE_OPENSSL definition passed to cmake.configure? Or is this done automatically?

It's automatic. Take a look on my last comment.

> Shouldn't the settings of the cmake recipe be changed to use arch and os instead of arch_build and os_build?

Good idea. WDYT @jgsogo

**Comment by madebr** [comment]
> It's automatic. Take a look on my last comment.

It is possible to disable openssl support. Would a `with_openssl` option make sense?
+ use `ENABLE_OPENSSL`

**Comment by uilianries** [comment]
It's possible, but does it make sense? Without openssl you can't download HTTS. It's kind of option for rare cases I think.

**Comment by madebr** [comment]
> It's possible, but does it make sense? Without openssl you can't download HTTS. It's kind of option for rare cases I think.

That makes sense.
My initial question was just that I think it is always better to explicitly pass `True`/`False` for an option to cmake.

**Comment by jgsogo** [comment]
> > Shouldn't the settings of the cmake recipe be changed to use arch and os instead of arch_build and os_build?
> 
> Good idea. WDYT @jgsogo

It is the way to go, but we need to think twice if it will break people that are using this recipe for their workflows and how badly it will be. Will it break the build just because they'll need a different package id? Will they need to change the profile? Will PR https://github.com/conan-io/conan/pull/6778 make the transition easier? I feel like it would be better to wait for that change after 1.25 (maybe mid May).

**Comment by uilianries** [comment]
Okay, let's wait so.

**Comment by madebr** [comment]
@uilianries 
This change has already been applied to current master as the option `with_openssl`.
I guess this pr can be closed.

**Pull request closed without merging**
