### PR TITLE
librasterlite2: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by samuel-emrys — APPROVED** [review]

**Review by uilianries — DISMISSED** [review]
LGTM

**Comment by SpaceIm** [comment]
```
dyld[15171]: Library not loaded: '@rpath/libgio-2.0.0.dylib'
  Referenced from: '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/librasterlite2/1.1.0-beta1/_/_/package/116df3d8153e7b7527cb1a50df6c9ab58cc7850b/lib/librasterlite2.1.dylib'
  Reason: tried: '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/librasterlite2/1.1.0-beta1/_/_/package/116df3d8153e7b7527cb1a50df6c9ab58cc7850b/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/cairo/1.17.6/_/_/package/4947144c63aec1938407a20e3470015ee4e7a2e6/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/giflib/5.2.1/_/_/package/93d7d400bcbae5c154cb7f4075f51d356c23b5d6/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libgeotiff/1.7.1/_/_/package/b450db07361802671717daa185f3e60a4f2dbd11/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libspatialite/5.0.1/_/_/package/749c92119985956e9fb74a9d05d600afd84bb008/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/openjpeg/2.5.0/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/lz4/1.9.4/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/pixman/0.40.0/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/lzo/2.10/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/fontconfig/2.14.2/_/_/package/dc65abfe99a711449f2a3c63f1cc57414799cb5d/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/glib/2.76.3/_/_/package/f7e06d8bb9b376a5458cccda75aacd93afa8c007/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/proj/9.1.1/_/_/package/b709a0e1e48a4f2bc936e62afdb0562e37b67b78/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/freexl/1.0.6/_/_/package/f2be05c09fe173a67f4b5253094adbf8501f0f55/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/librttopo/1.1.0/_/_/package/cd9365dca1ae82fa5724b13f22cbbce232166833/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libxml2/2.10.3/_/_/package/3e7fe1aad9fd36a14b0c19265f113b7ca4b09282/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/minizip/1.2.13/_/_/package/42480211ce3ff7dc12afbef4358043fecbdb5256/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/expat/2.5.0/_/_/package/a2fdc7f179bbe8c5db4c842ce67a3799914f233c/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/freetype/2.13.0/_/_/package/41f5f66f7d00992efb1870bcfaf56b01c679aed8/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libffi/3.4.4/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/pcre2/10.42/_/_/package/bfe27188ce1586f299c1a16f76982ce58c188ee2/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libelf/0.8.13/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libgettext/0.21/_/_/package/37b273fdb3cb050132a55c416d3ca02f66d01df5/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libcurl/7.88.1/_/_/package/f74ee7d7522b3efc86911c49a3fa0d6d3619706f/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libtiff/4.4.0/_/_/package/592da0c532c7112477dac01b9bb3405836657708/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/sqlite3/3.41.1/_/_/package/0b3c9306cf623f5cd015aa6a184678fd91711342/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/geos/3.11.1/_/_/package/07ef1df526a09ba13e697b1ee61d879cbad20ce0/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libpng/1.6.39/_/_/package/93d0d0ac1c261471eea08ce1f0d5d7aaf2b280ca/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/bzip2/1.0.8/_/_/package/a354ec84d9aa7012cfbeb01b59c5daa2780bb252/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/brotli/1.0.9/_/_/package/7b13aac265b6cd52c8312b07b2769a17e970b036/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libiconv/1.17/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libdeflate/1.18/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/xz_utils/5.4.0/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libjpeg/9e/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/jbig/20160605/_/_/package/c22e8c8a8163060fc60b4a898c859fee681732f5/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/zstd/1.5.4/_/_/package/316d1ccab6bad17521b1ccec39687f23bcf02e87/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libwebp/1.3.0/_/_/package/320b21beb576c60d3c4f320d038490736a2e6927/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/zlib/1.2.13/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib/libgio-2.0.0.dylib' (no such file), '/Users/jenkins/w/prod/BuildSingleReference@8/.conan/data/glib/2.76.1/_/_/package/0126e5fa3e526761ed90ff78e330c7e1a38a0bed/lib/libgio-2.0.0.dylib' (no such file), '/usr/local/lib/libgio-2.0.0.dylib' (no such file), '/usr/lib/libgio-2.0.0.dylib' (no such file)
WARN: libtiff/4.4.0: requirement xz_utils/5.4.2 overridden by libgeotiff/1.7.1 to xz_utils/5.4.0 
WARN: libtiff/4.4.0: requirement zstd/1.5.5 overridden by libgeotiff/1.7.1 to zstd/1.5.4 
ERROR: librasterlite2/1.1.0-beta1 (test package): Error in test() method, line 17
	self.run(bin_path, run_environment=True)
	ConanException: Error -6 while executing DYLD_LIBRARY_PATH="/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/librasterlite2/1.1.0-beta1/_/_/package/116df3d8153e7b7527cb1a50df6c9ab58cc7850b/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/cairo/1.17.6/_/_/package/4947144c63aec1938407a20e3470015ee4e7a2e6/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/giflib/5.2.1/_/_/package/93d7d400bcbae5c154cb7f4075f51d356c23b5d6/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libgeotiff/1.7.1/_/_/package/b450db07361802671717daa185f3e60a4f2dbd11/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libspatialite/5.0.1/_/_/package/749c92119985956e9fb74a9d05d600afd84bb008/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/openjpeg/2.5.0/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/lz4/1.9.4/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/pixman/0.40.0/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/lzo/2.10/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/fontconfig/2.14.2/_/_/package/dc65abfe99a711449f2a3c63f1cc57414799cb5d/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/glib/2.76.3/_/_/package/f7e06d8bb9b376a5458cccda75aacd93afa8c007/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/proj/9.1.1/_/_/package/b709a0e1e48a4f2bc936e62afdb0562e37b67b78/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/freexl/1.0.6/_/_/package/f2be05c09fe173a67f4b5253094adbf8501f0f55/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/librttopo/1.1.0/_/_/package/cd9365dca1ae82fa5724b13f22cbbce232166833/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libxml2/2.10.3/_/_/package/3e7fe1aad9fd36a14b0c19265f113b7ca4b09282/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/minizip/1.2.13/_/_/package/42480211ce3ff7dc12afbef4358043fecbdb5256/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/expat/2.5.0/_/_/package/a2fdc7f179bbe8c5db4c842ce67a3799914f233c/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/freetype/2.13.0/_/_/package/41f5f66f7d00992efb1870bcfaf56b01c679aed8/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libffi/3.4.4/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/pcre2/10.42/_/_/package/bfe27188ce1586f299c1a16f76982ce58c188ee2/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libelf/0.8.13/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libgettext/0.21/_/_/package/37b273fdb3cb050132a55c416d3ca02f66d01df5/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libcurl/7.88.1/_/_/package/f74ee7d7522b3efc86911c49a3fa0d6d3619706f/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libtiff/4.4.0/_/_/package/592da0c532c7112477dac01b9bb3405836657708/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/sqlite3/3.41.1/_/_/package/0b3c9306cf623f5cd015aa6a184678fd91711342/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/geos/3.11.1/_/_/package/07ef1df526a09ba13e697b1ee61d879cbad20ce0/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libpng/1.6.39/_/_/package/93d0d0ac1c261471eea08ce1f0d5d7aaf2b280ca/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/bzip2/1.0.8/_/_/package/a354ec84d9aa7012cfbeb01b59c5daa2780bb252/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/brotli/1.0.9/_/_/package/7b13aac265b6cd52c8312b07b2769a17e970b036/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libiconv/1.17/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libdeflate/1.18/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/xz_utils/5.4.0/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libjpeg/9e/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/jbig/20160605/_/_/package/c22e8c8a8163060fc60b4a898c859fee681732f5/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/zstd/1.5.4/_/_/package/316d1ccab6bad17521b1ccec39687f23bcf02e87/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/libwebp/1.3.0/_/_/package/320b21beb576c60d3c4f320d038490736a2e6927/lib:/Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/zlib/1.2.13/_/_/package/f0ce0f189afed95b41fb2faad2f2225a7eca0d22/lib" DYLD_FRAMEWORK_PATH="" bin/test_package
```

? It was working fine... 😩

**Comment by uilianries** [comment]
Failed due libcurl conflict version. I opened a new PR to bump its version for proj: https://github.com/conan-io/conan-center-index/pull/19093

**Comment by SpaceIm** [comment]
```
======== Installing packages ========
ERROR: Missing binary: cairo/1.17.6:f570917f5820877c84e648b8e48a88c31ec56838
ERROR: Missing binary: freexl/1.0.6:5328f91178ff203c85161e07e25e6fcef2eb4a17
ERROR: Missing binary: libgeotiff/1.7.1:c955f45feb058c30b2b557b67898e33eb27f2e4b
ERROR: Missing binary: libspatialite/5.0.1:4873a4e33d69f2fe885d5d0ad92204e992ef9259
ERROR: Missing binary: lzo/2.10:b647c43bfefae3f830561ca202b6cfd935b56205
ERROR: Missing binary: pixman/0.40.0:b647c43bfefae3f830561ca202b6cfd935b56205
ERROR: Missing binary: proj/9.1.1:7a1e8654fd5474fc501238a2ea788c8fc8233a27

lzo/2.10: WARN: Can't find a 'lzo/2.10' package binary 'b647c43bfefae3f830561ca202b6cfd935b56205' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=11
os=Linux
[options]
fPIC=True
shared=False

ERROR: Missing prebuilt package for 'cairo/1.17.6', 'freexl/1.0.6', 'libgeotiff/1.7.1', 'libspatialite/5.0.1', 'lzo/2.10', 'pixman/0.40.0', 'proj/9.1.1'
Check the available packages using 'conan list lzo/2.10:* -r=remote'
or try to build locally from sources using the '--build=missing' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```

Well, if it could be merged as is I would appreciate :sweat_smile:, because there are too many missing packages in dependencies.

**Comment by SpaceIm** [comment]
waiting for https://github.com/conan-io/conan-center-index/pull/19111

**Pull request closed without merging**
