### PR TITLE
[config] Remove old jenkinsfile and start using new configuration

### PR DESCRIPTION
**Pull request by danimtb**
We have recently started to use the new jenkinsfiles and configuration files under `.c3i/` folder. This means that jobs will be using the values declared there from now on.

Also, we will be updating those files whenever we have to do the following tasks:

- Add new authorized users.
- Add new reviewers.
- Add new profiles to build packages for.
- Change automatic merge review requirements.
- Add references that require larger resources to be built.

Beware that changes to `.c3i` folder are only allowed to Conan team members right now.

### CODE REVIEW

**Comment by danimtb** [comment]
> _config.yml_ syntax error in build 1:
> 
> ```
> No changes detected in this pull request
> ```

Well, yeah... that was embarrassing 🤣

**Comment by uilianries** [comment]
Go home Bot, it's Friday!

**Comment by jgsogo** [comment]
@danimtb , do we need to develop something on the library side to get a green here?

**Comment by danimtb** [comment]
> @danimtb , do we need to develop something on the library side to get a green here?

well, yes. Basically the CI only detects added or modified files, not removed ones

**Review by jgsogo — APPROVED** [review]
IMHO, it is not worth developing on the library side for this use case. It is one in a lifetime when we will remove files _configuration/ci files_.

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
Vamos mergear esto, cabrones!

**Pull request merged**
