### PR TITLE
sentry-native/0.4.13

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **sentry-native/0.4.13**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
Waiting for #8548 and #8549

**Review by uilianries — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
This PR is illformed, it has removed sources of 0.4.12 while keeping 0.4.12 in config.yml

**Comment by SSE4** [comment]
> This PR is illformed, it has removed sources of 0.4.12 while keeping 0.4.12 in config.yml Will be fixed in #9186

indeed
@jgsogo @uilianries probably, something we didn't consider in our CI and it could be improved

**Comment by jgsogo** [comment]
Yes, right now there is a mismatch. We should enforce `config.yml` file even if it is not strictly required, and we should also enforce that the same versions are listed in both files. Even if it requires a little bit more effort from contributors.

**Comment by SpaceIm** [comment]
It's detected most of the time, see in https://github.com/conan-io/conan-center-index/pull/9186:

```
ERROR: sentry-native/0.4.12: Error in source() method, line 137
	tools.get(**self.conan_data["sources"][self.version], destination=self._source_subfolder)
	KeyError: 'sources'
```

But if a "bump" PR is detected, it's missed.

**Comment by MartinDelille** [comment]
Ooops! My bad... 😓

**Comment by prince-chrismc** [comment]
> Yes, right now there is a mismatch. We should enforce `config.yml` file even if it is not strictly required, and we should also enforce that the same versions are listed in both files. Even if it requires a little bit more effort from contributors.

Safety First 🤷

**Pull request merged**
