### PR TITLE
wt: fix hooks

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **wt/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Comment by ericLemanissier** [comment]
the error is `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018: System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "wtdbopostgres.dir\Release\wtdbopostgres.tlog\ParallelCustomBuild.read.1.tlog". Path: wtdbopostgres.dir\Release\wtdbopostgres.tlog\ParallelCustomBuild.read.1.tlog exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\J\w\cci_PR-2895@3\2\f2454905-4a30-4215-aa67-85fd1a46269a\.conan\data\wt\4.3.1\_\_\build\23ebbad8f72ede86ddb72df4a916152946953d5c\build_subfolder\source_subfolder\src\Wt\Dbo\backend\wtdbopostgres.vcxproj]`
I believe C3I will use a shorter path for conan cache in a coming update right ?

**Comment by ericLemanissier** [comment]
> the error is `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018: System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "wtdbopostgres.dir\Release\wtdbopostgres.tlog\ParallelCustomBuild.read.1.tlog". Path: wtdbopostgres.dir\Release\wtdbopostgres.tlog\ParallelCustomBuild.read.1.tlog exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\J\w\cci_PR-2895@3\2\f2454905-4a30-4215-aa67-85fd1a46269a\.conan\data\wt\4.3.1\_\_\build\23ebbad8f72ede86ddb72df4a916152946953d5c\build_subfolder\source_subfolder\src\Wt\Dbo\backend\wtdbopostgres.vcxproj]`
> I believe C3I will use a shorter path for conan cache in a coming update right ?

friendly ping @jgsogo @danimtb

**Comment by danimtb** [comment]
@ericLemanissier we are checking this specific case in staging and will report about it soon

**Comment by ericLemanissier** [comment]
@danimtb there are also the following:
- https://github.com/conan-io/conan-center-index/pull/2771
- https://github.com/conan-io/conan-center-index/pull/2762
- https://github.com/conan-io/conan-center-index/pull/1759

**Review by jgsogo — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by SpaceIm** [comment]
Huu, I was already fixing this hook in https://github.com/conan-io/conan-center-index/pull/2559 xD

Not sure that generating a new revision just for fixing hooks in test_package is worth the effort. Why not waiting improvement in the recipe?

**Comment by SSE4** [comment]
this has pros and cons, e.g. for me personally it's easier to review smaller PRs, keeping changes isolated and atomic.
e.g. your PR has title `add components`, but it does other things as well which aren't relevant for components - e.g. you changed quotes in many places, resulting in many lines changed, and it's necessary to check if only quotes were changed or something else in these lines. 
P.S. for me types of quotes are not so relevant, as they are all functionally equivalent, but I see lots of PRs changing quotes from single to double and vice versa. I am okay with both of them and don't see advantages in either way.

**Comment by SpaceIm** [comment]
There is no advantage to use single or double quote, I just care to have a consistent recipe which doesn't mix both without good reason.
But I agree that I should have split those modifications in different commits. If CCI would not create a package revision for each PR (so potentially very big binaries for some recipes), I would have split these modifications in different PR.
Also when adding components, it might be important to have a good overview of dependencies and options, so I have to reorder methods, and specially group dependencies in requirements methods. So some modifications doesn't seem relevant for components but without them I may have introduced bugs.
Once these modifications are done, it's sometimes tedious to split them in different commits, most of the time I try, but for wt I forgot.

**Comment by ericLemanissier** [comment]
@SpaceIm sorry for that. I hope there won't be conflicts between branches. Regarding PR fixing hooks only, this is because it is tedious to change CONAN_HOOK_ERROR_LEVEL on a package by package basis, so the sooner hook errors are solved the better.
Maybe we could imagine a bot comparing all the PRs with each other, and warn when there is an overlap?

**Comment by SpaceIm** [comment]
Don't worry ;) no conflicts

**Pull request merged**
