### PR TITLE
ceres-solver: conan v2 support + deprecate use_gflags option + drop 1.13.0

### PR DESCRIPTION
**Pull request by SpaceIm**
gflags is not direct dependency of ceres-solver, and this option has no special meaning upstream except handling of transitive dependencies (which is useless with targets).

also remove use_TBB option after 2.0.0

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
Run echo "::add-matcher::linter/yamllint_matcher.json"
Error: Schema outlined in https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conandata_yml_format.md#patches-fields is not followed.

required key(s) 'patch_description', 'patch_type' not found in 
      - patch_file: patches/2.1.0-00 ... 
```

@prince-chrismc IMHO, it's excessive to fail for this kind of details like patch fields. It forces contributors to change stuff not related to their PR.

**Comment by SpaceIm** [comment]
```
C:\J\w\prod\BuildSingleReference@2\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\Eigen\src\Core\../plugins/BlockMethods.h(956,1): fatal error C1060: compiler is out of heap space (compiling source file C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\src\internal\ceres\generated\schur_eliminator_3_3_3.cc) [C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\build\internal\ceres\ceres_internal.vcxproj]
C:\J\w\prod\BuildSingleReference@2\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\Eigen\src\Core\../plugins/BlockMethods.h(580,1): fatal error C1060: compiler is out of heap space (compiling source file C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\src\internal\ceres\generated\schur_eliminator_4_4_2.cc) [C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\build\internal\ceres\ceres_internal.vcxproj]
C:\J\w\prod\BuildSingleReference@2\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\Eigen\src\Core\../plugins/BlockMethods.h(459,68): fatal error C1060: compiler is out of heap space (compiling source file C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\src\internal\ceres\generated\schur_eliminator_4_4_4.cc) [C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\build\internal\ceres\ceres_internal.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmmintrin.h(327,35): fatal error C1060: compiler is out of heap space (compiling source file C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\src\internal\ceres\block_jacobian_writer.cc) [C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\build\internal\ceres\ceres_internal.vcxproj]
C:\J\w\prod\BuildSingleReference@2\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\Eigen\src/Core/AssignEvaluator.h(856,1): fatal error C1060: compiler is out of heap space (compiling source file C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\src\internal\ceres\generated\schur_eliminator_4_4_3.cc) [C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\build\internal\ceres\ceres_internal.vcxproj]
C:\J\w\prod\BuildSingleReference@2\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\Eigen\src/Core/util/XprHelper.h(460,1): fatal error C1060: compiler is out of heap space (compiling source file C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\src\internal\ceres\generated\schur_eliminator_d_d_d.cc) [C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\build\internal\ceres\ceres_internal.vcxproj]
C:\J\w\prod\BuildSingleReference@2\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\Eigen\src/Core/DenseBase.h(198,1): fatal error C1060: compiler is out of heap space (compiling source file C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\src\internal\ceres\block_jacobi_preconditioner.cc) [C:\J\w\prod\BuildSingleReference@2\.conan\data\ceres-solver\2.1.0\_\_\build\c14ba4661ac4a96588c15ebfb8c235f27e8e885b\build\internal\ceres\ceres_internal.vcxproj]
  block_random_access_dense_matrix.cc
```

@danimtb @uilianries looks like an infra issue. I guess this configuration has built at least once in the past in c3i.

**Comment by prince-chrismc** [comment]
> @danimtb @uilianries looks like an infra issue. I guess this configuration has built at least once in the past in c3i, so why does it fail now with fatal error C1060: compiler is out of heap space?

Maybe the deployment config has changed since then and it now needs to be assigned to a bigger pod?
I am not sure how to investigate that 🙊

**Comment by SpaceIm** [comment]
What is the process to add ceres-solver to a bigger pod?

**Comment by prince-chrismc** [comment]
Both are off this week but hopefully they answer slack DMs when they get back 😬😅

**Comment by SpaceIm** [comment]
@jwillikers @prince-chrismc @uilianries @SSE4 could you review this one please? It's a quite old PR.

**Review by jwillikers — DISMISSED** [review]

**Review by SSE4 — DISMISSED** [review]

**Review by jwillikers — DISMISSED** [review]

**Comment by tylerjw** [comment]
I tested this locally with conan 2.0 and it worked for me.

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
By the way, to be sure that it builds in c3i without dozens of close/open PR, I think large pod is still relevant.

**Comment by prince-chrismc** [comment]
With recent config changes I am optimistic, if it fails ones we can change it

**Comment by SpaceIm** [comment]
```
[ 50%] Building C object CMakeFiles/test_package.dir/test_package.c.o
[100%] Linking C executable test_package
/opt/conan/binutils/bin/ld: CMakeFiles/test_package.dir/test_package.c.o: undefined reference to symbol 'exp@@GLIBC_2.2.5'
/opt/conan/binutils/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/test_package.dir/build.make:84: recipe for target 'test_package' failed
make[2]: *** [test_package] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/test_package.dir/all' failed
make[1]: *** [CMakeFiles/test_package.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

There was this error in test package of v2 pipeline for linux static build. Actually it works fine in v1 pipeline because libm is propagated through eigen, but in conan v2 libm is not propagated despite eigen being a public dependency .(transitive_headers=True).
Actually libm is also a direct & private dependency of ceres-solver, so I've explicitly added libm to its system_libs, but I've reported this issue to conan because libm should have been propagated through eigen since it's a public dependency of ceres-solver: https://github.com/conan-io/conan/issues/13361

**Comment by SpaceIm** [comment]
> With recent config changes I am optimistic, if it fails ones we can change it

Here we go, it fails again: https://c3i.jfrog.io/artifactory/misc-v2/logs/pr/14855/13-configs/windows-msvc/ceres-solver/2.0.0/85de4a71e45c9d04d47d3c466dfdcb35f11cd665-build.txt

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/pull/16425 😄

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
Let's see if it's better in large pods.

**Review by SSE4 — APPROVED** [review]

**Comment by fong7x7** [comment]
Fixes: https://github.com/conan-io/conan-center-index/issues/16622

**Comment by prince-chrismc** [comment]
Why is this not being merged 🤔 1 team + two community reviews v1 and v2 are green

**Comment by SpaceIm** [comment]
Due to https://cpplang.slack.com/archives/C41CWV9HA/p1679321483306049 + https://cpplang.slack.com/archives/C41CWV9HA/p1679415745116219

**Comment by fong7x7** [comment]
@SpaceIm Do we have an ETA for when this might be completed? I can't read the slack thread if it's explained there.

**Comment by SpaceIm** [comment]
I'm not a team member, so I can't answer. It will be merged once merge-bot of conancenter is fixed I guess (it seem to be stuck in an infinite loop currently, or has been disabled, I don't know).

**Comment by danimtb** [comment]
Sorry, we had some issues with automatic merge and I had to get this merged mannually

**Comment by fong7x7** [comment]
Is this a Conan deployment issue? It appears like the ceres-solver package export can't be found
```
*********************************************************
Recipe 'ceres-solver/2.1.0' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'ceres-solver/2.1.0' not resolved: ceres-solver/2.1.0: Cannot load recipe.
Error loading conanfile at '/home/fortem/.conan2/p/ceres5e4db3e731b58/e/conanfile.py': /home/fortem/.conan2/p/ceres5e4db3e731b58/e/conanfile.py not found!
```

**Comment by SpaceIm** [comment]
Works fine for me. But my recipe folder for ceres-solver/2.1.0 is ceres8242d8cabe728, not ceres5e4db3e731b58:

```
$ ls ~/.conan2/p/ceres8242d8cabe728/*
/Users/spaceim/.conan2/p/ceres8242d8cabe728/e:
conandata.yml		conanfile.py		conanmanifest.txt

/Users/spaceim/.conan2/p/ceres8242d8cabe728/es:
patches
```

**Comment by fong7x7** [comment]
Looks like I had something bad in my `.conan2` folder. Deleting it and resetting up fixed the issue.

**Pull request merged**
