### PR TITLE
linter: improve conandata.yml linter output

### PR DESCRIPTION
**Pull request by prince-chrismc**
resolves https://github.com/conan-io/conan-center-index/issues/13778

- looks better
- multiple errors per file https://github.com/conan-io/conan-center-index/pull/14015#issuecomment-1354119926
- exits 1 on error
- invalid yaml are annotations
- Calls out improvements when using layouts https://github.com/conan-io/conan-center-index/pull/14015#issuecomment-1354091107

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Doesnt actually get picked up 🤔

**Comment by prince-chrismc** [comment]
image

vs

image

**Comment by danimtb** [comment]
Let's move this forward @prince-chrismc, what else is needed?

**Review by danimtb — DISMISSED** [review]

**Comment by prince-chrismc** [comment]
This really only achieves removing the "unicode string" and it's just slightly more pretty

**Comment by prince-chrismc** [comment]
The annotations looks much better, you can see them in the files changed at the bottom

**Comment by prince-chrismc** [comment]
New stuff 
image

**Comment by prince-chrismc** [comment]
Reports failures multiple times on the same file with this too 

image

**Review by danimtb — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by SpaceIm** [comment]
Does it prevent CI to succeed now when these optional fields are missing?

**Comment by prince-chrismc** [comment]
Of course not! It's only enforcing the ones marked as required, like https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conandata_yml_format.md#patch_type, and there rest are warnings.

**Comment by SpaceIm** [comment]
When I mean optional, I was talking about patch_type & patch_description which are optional for conan client, but are not for this linter.
Try to update conandata.yml of boost (for example to add a patch for a specific boost version in a PR) to experiment how pleasant it can be to have to find a description and a patch type for the existing 40 patches which don't have these fields ;)
I had to analyse patches of bison when I've migrated this recipe to conan v2 yesterday, it took me more time than migrating the recipe.

**Pull request merged**
