### PR TITLE
zstd: build command line tools too

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **lib/1.0**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
I would say to add it as option, also, binaries need to be included in PATH

**Comment by ericLemanissier** [comment]
` You need to build static library to build zstd CLI` that means we should always build the static lib regardless of the shared option, and remove the static lib in the package method if shared option is true. Do you agree ?

**Comment by madebr** [comment]
@ericLemanissier 
A patch can fix this.
Remove that test with `if(0)` or `if(1)`,
and link the cli eecutable target to `$<IF:$<BOOL:${ZSTD_BUILD_STATIC}>,zstd_static,zstd_shared>`
That way, the patch is short.

**Comment by madebr** [comment]
@ericLemanissier Did you close this or intentionally?

**Comment by ericLemanissier** [comment]
Yes, I have no interest in this change.

**Pull request closed without merging**
