### PR TITLE
Bump versions of various packages

### PR DESCRIPTION
**Pull request by alejandro-colomar**
Specify library name and version:  **libavrocpp/1.10.2**, **librdkafka/1.6.1**, **librdkafka/1.7.0**, **prometheus-cpp/0.12.3**

I have a task which is to start using conan in a project that is already consuming those libraries by other means.  I need those versions, which aren't in conan-center, so I had a look at how you bump versions normally, and followed that.

I haven't done any tests, apart from checking the checksums with `sha256sum` (for both the version that I uploaded, and the latest version that you already had, to make sure that I was doing it correctly).  I specifically haven't tested that these commits build correctly the new versions and that they are usable because I got an error message when trying to do so:

```
.../conan-center-index$ conan config install https://github.com/conan-io/hooks.git -sf hooks -tf hooks
Trying to clone repo: https://github.com/conan-io/hooks.git
Repo cloned!
Copying file conan-center.py to /home/alx/.conan/hooks/.
Copying file export_metadata.py to /home/alx/.conan/hooks/.
Copying file spdx_checker.py to /home/alx/.conan/hooks/.
Copying file members_typo_checker.py to /home/alx/.conan/hooks/.
Copying file recipe_linter.py to /home/alx/.conan/hooks/.
Copying file attribute_checker.py to /home/alx/.conan/hooks/.
Copying file binary_linter.py to /home/alx/.conan/hooks/.
Copying file github_updater.py to /home/alx/.conan/hooks/.
.../conan-center-index$ conan config set hooks.conan-center
.../conan-center-index$ cd recipes/libavrocpp/all/
.../conan-center-index/recipes/libavrocpp/all$ conan create . 1.10.2@
ERROR: [HOOK - conan-center.py] pre_export(): could not get source code
.../conan-center-index/recipes/libavrocpp/all$ conan create . 1.10.3@
ERROR: [HOOK - conan-center.py] pre_export(): could not get source code
.../conan-center-index/recipes/libavrocpp/all$ conan create . 1.10.1@
ERROR: [HOOK - conan-center.py] pre_export(): could not get source code
```

I saw that some packages have some patches, and I didn't touch anything of that, because I didn't know if I should.  Please tell me if there's anything I should have done about that, for next time.  Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [-] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [?] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated. `see error above :/`

### CODE REVIEW

**Comment by SpaceIm** [comment]
@alejandro-colomar 

Few comments:
- commits must be done with email of your github account
- it is allowed to modify only on recipe per PR
- please test the build before submitting a PR. For example, there are patches for previous versions librdkakfa & libavrocpp, so there are good chances that these new versions need patches also. If not, explain why.

**Comment by alejandro-colomar** [comment]
> 
> 
> @alejandro-colomar
> 
> Few comments:
> 
>     * commits must be done with email of your github account

I just added it :)

> 
>     * it is allowed to modify only one recipe per PR

Okay, I'll break it.

> 
>     * please test the build before submitting a PR. For example, there are patches for previous versions of librdkakfa & libavrocpp, so there are good chances that these new versions need patches also (for librdkafka, I'm pretty sure that patches are still required). If not, explain why.

Hmm, I got the error above.  Should I open an issue, or could you help me knowing why I got the error.  Also, about the patches, do you have anything I should follow?  Or should I just copy the lines with the patches from the latest version you have and see if it passes?

Thanks,

Alex

**Comment by SpaceIm** [comment]
> Also, about the patches, do you have anything I should follow? Or should I just copy the lines with the patches from the latest version you have and see if it passes?

It's a solution, but it's better to undestand what you are doing:

1. Compare source code of new and previous version.
2. If files modified by a patch have been modified, you'll probably need to create a new patch (but not always). Be sure to understand purpose of the patch and consequences.
3. If build files have been modified, try to understand the consequences for the recipe.

**Comment by alejandro-colomar** [comment]
> 
> 
> I've edited previous message:
> 
> > build command is not `conan create . <version>@` but `conan create . <recipename>/<version>@`, for example `conan create . libavrocpp/1.10.2@`

I'm still getting an error:

```
alx@lvl01026:~/src/conan/conan-center-index/recipes/libavrocpp/all$ conan create . 'libavrocpp/1.10.2@'
ERROR: [HOOK - conan-center.py] pre_export(): could not get source code
```

**Comment by SpaceIm** [comment]
https://github.com/conan-io/hooks/issues/157 ?

**Comment by alejandro-colomar** [comment]
> 
> 
> [conan-io/hooks#157](https://github.com/conan-io/hooks/issues/157) ?

Yup, it's probably that, although I used the Debian installer, not the Windows one.  I commented there with my case.  Maybe you could reopen the issue?  Or should I open a Debian specific one?

**Comment by alejandro-colomar** [comment]
> 
> 
> > Also, about the patches, do you have anything I should follow? Or should I just copy the lines with the patches from the latest version you have and see if it passes?
> 
> It's a solution, but it's better to undestand what you are doing:
> 
>     1. Compare source code of new and previous version.
> 
>     2. If a patch has been ported upstream, it's likely not required anymore.
> 
>     3. If files modified by a patch have been modified, you'll probably need to create a new patch (but not always). Be sure to understand purpose of the patch and consequences.
> 
>     4. If build files have been modified, try to understand the consequences for the recipe.

Sure.

But, I meant if you have some scripts to apply the patches or how do you do it?

I can more or less understand the contents of the patches, and if necessary could write the code manually from the newer version, but those patches are not in a format that I can apply using `git am`.

**Pull request closed without merging**
