### PR TITLE
krb5: add library version 1.19.2

### PR DESCRIPTION
**Pull request by Jihadist**
Specify library name and version:  **krb5/1.19.2**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Closes https://github.com/conan-io/conan-center-index/issues/4102

### CODE REVIEW

**Comment by Jihadist** [comment]
How to find appropriate prebuild libevent?

**Comment by Jihadist** [comment]
@memsharded sorry for pin, can you help me? I don't understand where the problem is and how can I solve it for cci

**Comment by Jihadist** [comment]
Maybe someone can help to fix shared build
I can reproduce error with conanio/gcc11-ubuntu16.04 docker container https://pastebin.com/N5XbCWdE
Looks like we could not run ```conftest``` due to problems with environment
```
configure:3376: checking whether we are cross compiling
configure:3384: gcc -o conftest  -m64 -O3  -DNDEBUG -I/home/conan/.conan2/p/libvec1b1a4b556868/p/include -I/home/conan/.conan2/p/libev32ce1de9f2776/p/include -I/home/conan/.conan2/p/opens58f99806979ee/p/include -I/home/conan/.conan2/p/zlibf0503f1ff2450/p/include  -m64 -L/home/conan/.conan2/p/libvec1b1a4b556868/p/lib -L/home/conan/.conan2/p/libev32ce1de9f2776/p/lib -L/home/conan/.conan2/p/opens58f99806979ee/p/lib -L/home/conan/.conan2/p/zlibf0503f1ff2450/p/lib conftest.c  -lverto -levent_pthreads -levent_openssl -levent_extra -levent_core -lssl -lcrypto -lz -ldl -lpthread -lrt >&5
configure:3388: $? = 0
configure:3395: ./conftest
./conftest: error while loading shared libraries: libverto.so.1: cannot open shared object file: No such file or directory
configure:3399: $? = 127
configure:3406: error: in `/home/conan/.conan2/p/b/krb56b930557904cb/b/build-release':
configure:3408: error: cannot run C compiled programs.
```
But I don't have ideas how to set env correctly here

**Review by valgur — APPROVED** [review]

**Comment by Jihadist** [comment]
@madebr, sorry for ping. Can you please sign cla?

**Comment by Jihadist** [comment]
@franramirez688 are there any chances for review?

**Comment by Jihadist** [comment]
@RubenRBS sorry for ping. Can someone review it?

**Review by uilianries — COMMENTED** [review]
@Jihadist Thank you for your PR! I submitted my suggestions to a PR, otherwise this PR would be very polluted: https://github.com/Jihadist/conan-center-index/pull/5

**Comment by uilianries** [comment]
@Jihadist I'll take a look soon. I tested the current state of the recipe in Linux, locally and it's working. Let's see with official docker images to avoid any context from my machine.

**Review by RubenRBS — APPROVED** [review]

**Comment by Jihadist** [comment]
@uilianries ok, I see, thank you! openssl need to fixed

**Review by uilianries — APPROVED** [review]
It looks for first version. So far we only build on Linux and as shared. There are several errors to build using other configurations, but could be checked with the upstream first.

**Pull request merged**
