### PR TITLE
gtest: add 1.15.2

### PR DESCRIPTION
**Pull request by gjasny**
### Summary
Changes to recipe:  **gtest/1.15.2**

#### Motivation
I wanted to update to Google Test 1.15 but noticed that a newer patch version is available.

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by perseoGI — APPROVED** [review]
LGTM https://github.com/google/googletest/compare/v1.15.0...v1.15.2
Really minor changes

**Comment by gsantner** [comment]
Humble said, is it even worth it then to add 1.15.1 & 1.15.2 changes by 1.15.2 release here?  
Looks not like  it brings any actual improvement for C++ usage (and thats we users do with Conan after all).

Unnecessary versions adds unnecessary strain to the Conan CI systems isn't it?

**Comment by gsantner** [comment]
Humble said, is it even worth it then to add >1.15.0 - 1.15.2 changes by 1.15.2 release here?  
Looks not like  it brings any actual improvement/fix for C++ usage (and thats users do with Conan after all).

Unnecessary versions adds unnecessary strain to the Conan CI systems isn't it?

**Comment by gjasny** [comment]
I did not notice that the changes are only for Bazel.

**Comment by perseoGI** [comment]
> Humble said, is it even worth it then to add >1.15.0 - 1.15.2 changes by 1.15.2 release here? Looks not like it brings any actual improvement/fix for C++ usage (and thats what users do with Conan after all).
> 
> Unnecessary versions adds unnecessary strain to the Conan CI systems isn't it?

Yes, that is totally true...
I've accepted because some developers want to be always on the edge line but in this case, between 1.15.0 and 1.15.2 there is no apparent C++ change or significant improvement.

**Pull request closed without merging**
