### PR TITLE
libjpeg-turbo: add 2.1.5 + download official tarballs + no manual injection of CMAKE_SYSTEM_PROCESSOR

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
As per https://www.libjpeg-turbo.org/, official tarballs are available under https://sourceforge.net/projects/libjpeg-turbo/files

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by sykhro** [comment]
Would an additional PR for adding `clang-cl` support be welcome?
Currently this fails because `clang-cl` isn't recognised as `is_msvc`. We have been working around it locally like this, like other recipes con conan center do:
```python
    @property
    def _is_clang_cl(self):
        return self.settings.os == "Windows" and self.settings.compiler == "clang"
 ```

**Comment by SpaceIm** [comment]
> Would an additional PR for adding `clang-cl` support be welcome? Currently this fails because `clang-cl` isn't recognised as `is_msvc`. We have been working around it locally like this, like other recipes con conan center do:
> 
> ```python
>     @property
>     def _is_clang_cl(self):
>         return self.settings.os == "Windows" and self.settings.compiler == "clang"
> ```

As you wish, but it may break other flavors of clang on Windows. This issue must be addressed at conan client scope.

**Comment by sykhro** [comment]
> > Would an additional PR for adding `clang-cl` support be welcome? Currently this fails because `clang-cl` isn't recognised as `is_msvc`. We have been working around it locally like this, like other recipes con conan center do:
> > ```python
> >     @property
> >     def _is_clang_cl(self):
> >         return self.settings.os == "Windows" and self.settings.compiler == "clang"
> > ```
> 
> As you wish (but not in this PR), but it may break other flavors of clang on Windows (MinGW clang, LLVM clang). This issue must be addressed at conan client scope. See [conan-io/conan#12336](https://github.com/conan-io/conan/issues/12336) and specifically [conan-io/conan#12336 (comment)](https://github.com/conan-io/conan/issues/12336#issuecomment-1342464853)

I'm aware, I brought it up because it's already in use for [other recipes](https://github.com/conan-io/conan-center-index/search?q=_is_clang_cl) (we noticed when switching from `libjpeg`).

**Comment by SpaceIm** [comment]
It's in used in few recipes, and it breaks other windows clang flavors. I would advise pushing the effort on conan client, convincing conan maintainers to properly address this problem, instead of introducing workaround in all conan-center recipes.

**Review by uilianries — APPROVED** [review]

**Pull request merged**
