### PR TITLE
add a new fcl version (0.7.0)

### PR DESCRIPTION
**Pull request by JurajX**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Comment by JurajX** [comment]
Hey guys, can you please review and either approve or reject?
Thanks!

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
> Hey guys, can you please review and either approve or reject? Thanks!

yes, we can. we review whenever we have time. there are many PRs opened, so it may take some time.

**Comment by SpaceIm** [comment]
I've also opened https://github.com/conan-io/conan-center-index/pull/8873, 0.7.0 still need patch to be really robust, and bigobj for mingw.

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
> there are many PRs opened, so it may take some time.

We have had some record setting numbers of PRs in the last two weeks, currently it takes 8 days to merge... You can see more here https://github.com/prince-chrismc/conan-center-index-pending-review/issues/1

**Comment by prince-chrismc** [comment]
The bot will automatically merge your PR shortly 🚀

**Pull request merged**
