### PR TITLE
date : add an option to install all headers

### LINKED ISSUE #24997: date/*: add option for installing all headers
### Description

Currently, there is a header_only option. An option should be added to support the case where both header and binaries are needed from the package. 

### Package and Environment Details

All

### Conan profile

All

### Steps to reproduce

conan install date/3.0.1@ -pr:all gcc12

### Logs

ls -la conan-data/b/dateae5e329277a92/p/include/date/
date.h  tz.h

expecting:
date.h
islamic.h
iso_week.h
julian.h
ptz.h
tz.h

### PR DESCRIPTION
**Pull request by sophieeihpos**
### Summary
Changes to recipe:  **date/all**

#### Motivation
Fix #24997

#### Details
Add an option to install all headers

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

© 2024 Morgan Stanley.
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE Conan-io project Contributor License Agreement.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Review by perseoGI — APPROVED** [review]
LGTM

**Review by perseoGI — DISMISSED** [review]
LGTM

**Comment by uilianries** [comment]
@sophieeihpos Thank you for your PR, I just opened a PR to yours as review. Please, consider it: https://github.com/sophieeihpos/conan-center-index/pull/2

**Review by perseoGI — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
