### PR TITLE
opencascade: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/20226

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Version conflict with the version of fontconfig in tk recipe. https://github.com/conan-io/conan-center-index/pull/19897 should solve this conflict.

**Comment by SpaceIm** [comment]
v2 pipeline:

```
======== Installing packages ========
ERROR: Missing binary: fontconfig/2.13.93:be99654e60049e3c9c81374f129beeb1bf5469ab
ERROR: Missing binary: tk/8.6.10:58334a10067056e3c216a16f9f1c94b7841730df

fontconfig/2.13.93: WARN: Can't find a 'fontconfig/2.13.93' package binary 'be99654e60049e3c9c81374f129beeb1bf5469ab' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=11
os=Linux
[options]
fPIC=True
shared=False
[requires]
brotli/1.1.Z
bzip2/1.0.Z
expat/2.5.Z
freetype/2.13.Z
libpng/1.6.Z
util-linux-libuuid/2.39.Z
zlib/1.3.Z

ERROR: Missing prebuilt package for 'fontconfig/2.13.93', 'tk/8.6.10'
Check the available packages using 'conan list fontconfig/2.13.93:* -r=remote'
or try to build locally from sources using the '--build=fontconfig/2.13.93 --build=tk/8.6.10' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```

:grimacing:

**Comment by SpaceIm** [comment]
```
TKDraw.lib(Draw_Window.obj) : error LNK2001: unresolved external symbol __imp_Tcl_CreateExitHandler [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_AppendElement referenced in function "public: void __cdecl Draw_Interpretor::AppendElement(char const * const)" (?AppendElement@Draw_Interpretor@@QEAAXQEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_AppendResult referenced in function "public: class Draw_Interpretor & __cdecl Draw_Interpretor::Append(char const * const)" (?Append@Draw_Interpretor@@QEAAAEAV1@QEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_CommandComplete referenced in function "public: static bool __cdecl Draw_Interpretor::Complete(char const * const)" (?Complete@Draw_Interpretor@@SA_NQEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_CreateCommand referenced in function "protected: void __cdecl Draw_Interpretor::add(char const *,char const *,char const *,struct Draw_Interpretor::CallBackData *,char const *)" (?add@Draw_Interpretor@@IEAAXPEBD00PEAUCallBackData@1@0@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_CreateInterp referenced in function "public: void __cdecl Draw_Interpretor::Init(void)" (?Init@Draw_Interpretor@@QEAAXXZ) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_DeleteCommand referenced in function "public: bool __cdecl Draw_Interpretor::Remove(char const * const)" (?Remove@Draw_Interpretor@@QEAA_NQEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_DeleteInterp referenced in function "public: void __cdecl Draw_Interpretor::Init(void)" (?Init@Draw_Interpretor@@QEAAXXZ) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_Eval referenced in function "public: int __cdecl Draw_Interpretor::Eval(char const * const)" (?Eval@Draw_Interpretor@@QEAAHQEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2001: unresolved external symbol __imp_Tcl_Eval [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_EvalFile referenced in function "public: int __cdecl Draw_Interpretor::EvalFile(char const * const)" (?EvalFile@Draw_Interpretor@@QEAAHQEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_Exit referenced in function "public: __cdecl Draw_Interpretor::~Draw_Interpretor(void)" (??1Draw_Interpretor@@QEAA@XZ) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2001: unresolved external symbol __imp_Tcl_Exit [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_GetStringResult referenced in function "public: char const * __cdecl Draw_Interpretor::Result(void)const " (?Result@Draw_Interpretor@@QEBAPEBDXZ) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2001: unresolved external symbol __imp_Tcl_GetStringResult [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_GetVar2 referenced in function __catch$?CommandCmd@@YAHPEAXPEAUTcl_Interp@@HQEAPEBD@Z$0 [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2001: unresolved external symbol __imp_Tcl_GetVar2 [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_RecordAndEval referenced in function "public: int __cdecl Draw_Interpretor::RecordAndEval(char const * const,int)" (?RecordAndEval@Draw_Interpretor@@QEAAHQEBDH@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_ResetResult referenced in function "public: void __cdecl Draw_Interpretor::Reset(void)" (?Reset@Draw_Interpretor@@QEAAXXZ) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_SetResult referenced in function __catch$?CommandCmd@@YAHPEAXPEAUTcl_Interp@@HQEAPEBD@Z$0 [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Interpretor.obj) : error LNK2019: unresolved external symbol __imp_Tcl_SetVar2 referenced in function "protected: void __cdecl Draw_Interpretor::add(char const *,char const *,char const *,struct Draw_Interpretor::CallBackData *,char const *)" (?add@Draw_Interpretor@@IEAAXPEBD00PEAUCallBackData@1@0@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_VariableCommands.obj) : error LNK2001: unresolved external symbol __imp_Tcl_SetVar2 [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Main.obj) : error LNK2019: unresolved external symbol __imp_Tcl_FindExecutable referenced in function "int __cdecl Draw_Main(int,char * * const,void (__cdecl*const)(class Draw_Interpretor &))" (?Draw_Main@@YAHHQEAPEADQ6AXAEAVDraw_Interpretor@@@Z@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw.obj) : error LNK2019: unresolved external symbol __imp_Tcl_DStringAppend referenced in function "bool __cdecl Draw_Interprete(char const *)" (?Draw_Interprete@@YA_NPEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw.obj) : error LNK2019: unresolved external symbol __imp_Tcl_DStringFree referenced in function "bool __cdecl Draw_Interprete(char const *)" (?Draw_Interprete@@YA_NPEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw.obj) : error LNK2019: unresolved external symbol __imp_Tcl_DStringInit referenced in function "bool __cdecl Draw_Interprete(char const *)" (?Draw_Interprete@@YA_NPEBD@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw.obj) : error LNK2019: unresolved external symbol __imp_Tcl_Init referenced in function "void __cdecl Draw_Appli(struct HINSTANCE__ *,struct HINSTANCE__ *,int,int,wchar_t * *,void (__cdecl*const)(class Draw_Interpretor &))" (?Draw_Appli@@YAXPEAUHINSTANCE__@@0HHPEAPEA_WQ6AXAEAVDraw_Interpretor@@@Z@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2001: unresolved external symbol __imp_Tcl_Init [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw.obj) : error LNK2019: unresolved external symbol __imp_Tcl_PutEnv referenced in function "void __cdecl setOcctTclEnv(class TCollection_AsciiString const &,class TCollection_AsciiString &)" (?setOcctTclEnv@@YAXAEBVTCollection_AsciiString@@AEAV1@@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_VariableCommands.obj) : error LNK2019: unresolved external symbol __imp_Tcl_TraceVar2 referenced in function "public: static void __cdecl Draw::Set(char const * const,class opencascade::handle<class Draw_Drawable3D> const &,bool)" (?Set@Draw@@SAXQEBDAEBV?$handle@VDraw_Drawable3D@@@opencascade@@_N@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_VariableCommands.obj) : error LNK2019: unresolved external symbol __imp_Tcl_UnsetVar2 referenced in function "public: static void __cdecl Draw::Set(char const * const,class opencascade::handle<class Draw_Drawable3D> const &,bool)" (?Set@Draw@@SAXQEBDAEBV?$handle@VDraw_Drawable3D@@@opencascade@@_N@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_VariableCommands.obj) : error LNK2019: unresolved external symbol __imp_Tcl_UntraceVar2 referenced in function "char * __cdecl tracevar(void *,struct Tcl_Interp *,char const *,char const *,int)" (?tracevar@@YAPEADPEAXPEAUTcl_Interp@@PEBD2H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_VariableCommands.obj) : error LNK2019: unresolved external symbol __imp_Tcl_VarTraceInfo2 referenced in function "public: static void __cdecl Draw::Set(char const * const,class opencascade::handle<class Draw_Drawable3D> const &,bool)" (?Set@Draw@@SAXQEBDAEBV?$handle@VDraw_Drawable3D@@@opencascade@@_N@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_Panic referenced in function "struct Tcl_Channel_ * __cdecl TclpGetDefaultStdChannel(int)" (?TclpGetDefaultStdChannel@@YAPEAUTcl_Channel_@@H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_AddErrorInfo referenced in function "void __cdecl Prompt(struct Tcl_Interp *,int)" (?Prompt@@YAXPEAUTcl_Interp@@H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_Close referenced in function "struct Tcl_Channel_ * __cdecl TclpGetDefaultStdChannel(int)" (?TclpGetDefaultStdChannel@@YAPEAUTcl_Channel_@@H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_DoOneEvent referenced in function "unsigned long __cdecl tkLoop(void *)" (?tkLoop@@YAKPEAX@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_Flush referenced in function "void __cdecl Prompt(struct Tcl_Interp *,int)" (?Prompt@@YAXPEAUTcl_Interp@@H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_GetStdChannel referenced in function "void __cdecl Prompt(struct Tcl_Interp *,int)" (?Prompt@@YAXPEAUTcl_Interp@@H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_MakeFileChannel referenced in function "struct Tcl_Channel_ * __cdecl TclpGetDefaultStdChannel(int)" (?TclpGetDefaultStdChannel@@YAPEAUTcl_Channel_@@H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_RegisterChannel referenced in function "unsigned long __cdecl tkLoop(void *)" (?tkLoop@@YAKPEAX@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_SetChannelOption referenced in function "struct Tcl_Channel_ * __cdecl TclpGetDefaultStdChannel(int)" (?TclpGetDefaultStdChannel@@YAPEAUTcl_Channel_@@H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_SetStdChannel referenced in function "void __cdecl ResetStdChannel(int)" (?ResetStdChannel@@YAXH@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_StaticPackage referenced in function "bool __cdecl Init_Appli(struct HINSTANCE__ *,struct HINSTANCE__ *,int,struct HWND__ * &)" (?Init_Appli@@YA_NPEAUHINSTANCE__@@0HAEAPEAUHWND__@@@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tcl_Write referenced in function "void __cdecl Prompt(struct Tcl_Interp *,int)" (?Prompt@@YAXPEAUTcl_Interp@@H@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tk_GetNumMainWindows referenced in function "unsigned long __cdecl tkLoop(void *)" (?tkLoop@@YAKPEAX@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tk_GetUid referenced in function "unsigned long __cdecl tkLoop(void *)" (?tkLoop@@YAKPEAX@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tk_Init referenced in function "bool __cdecl Init_Appli(struct HINSTANCE__ *,struct HINSTANCE__ *,int,struct HWND__ * &)" (?Init_Appli@@YA_NPEAUHINSTANCE__@@0HAEAPEAUHWND__@@@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tk_MainWindow referenced in function "unsigned long __cdecl tkLoop(void *)" (?tkLoop@@YAKPEAX@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
TKDraw.lib(Draw_Window.obj) : error LNK2019: unresolved external symbol __imp_Tk_SetAppName referenced in function "unsigned long __cdecl tkLoop(void *)" (?tkLoop@@YAKPEAX@Z) [C:\J2\w\prod-v1\bsr@2\18102\cfcda\s\a03754\1\build\src\DRAWEXE\DRAWEXE.vcxproj]
```

Ok, now I remember why it was necessary to inject interface definitions of dependencies globally through `conan_global_flags()`. I just need to find an elegant conan v2 equivalent.

**Comment by RubenRBS** [comment]
Yep, rebulding now, thanks for the ping - we'll run a big tapaholes for all the missing binaries that the zlib migration caused, for now it's patchwork when we detect them :)

**Comment by RubenRBS** [comment]
Will do so (And qt's one) first thing monday, thanks for the ping :)

**Comment by SpaceIm** [comment]
No problem. It's a complex recipe, so v2 migration leads to a big PR, not easy to review.

**Review by jwillikers — APPROVED** [review]

**Comment by rainman110** [comment]
> onday, thanks for

Great work! Can't wait for it to be merged 😄

**Review by danimtb — APPROVED** [review]

**Review by EstebanDugueperoux2 — APPROVED** [review]

**Pull request merged**
