### PR TITLE
Use validate in gn

### PR DESCRIPTION
**Pull request by petamas**
Specify library name and version:  **gn/cci.20210429**

Trying to resolve an issue I ran into while trying to make https://github.com/conan-io/conan-center-index/pull/12189 build.

For the other PR, I got this error: `Do not raise ConanInvalidConfiguration from build() method. Please, move that same check to validate() method.`

Checking the log, I saw this message: `ERROR: gn/cci.20210429: Invalid configuration: gn requires a compiler supporting c++17`

My assumption is that the root cause is that `gn` validates its configuration in `configure()` instead of `validate()`.

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — DISMISSED** [review]
LGTM

**Comment by uilianries** [comment]
@petamas please, update `required_conan_version = ">=1.41.0"` because `tools.files.get` is only available since that version.

**Comment by petamas** [comment]
> @petamas please, update `required_conan_version = ">=1.41.0"` because `tools.files.get` is only available since that version.

Fixed, thanks!

**Comment by petamas** [comment]
Ooops, modified the wrong recipe. Will fix in a few hours when I have access to my regular git client.

**Comment by petamas** [comment]
CI has completed successfully, @uilianries, please re-review when you get the chance. :)

**Review by uilianries — APPROVED** [review]
LGTM

**Review by toge — APPROVED** [review]

**Pull request merged**
