### PR TITLE
libbacktrace: do not call autoreconf

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

closes https://github.com/conan-io/conan-center-index/issues/5608

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by alex-176 — APPROVED** [review]

**Review by pmakaragc — APPROVED** [review]

**Review by ShmuelFine — APPROVED** [review]

**Review by yossavi — APPROVED** [review]

**Review by ctc-santanaa — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by SpaceIm** [comment]
there a file `override.m4` in `config` folder of libbacktrace archive:

```m4
dnl Test for the exact version when AC_INIT is expanded.
dnl This allows to update the tree in steps (for testing)
dnl by putting
dnl   m4_define([_GCC_AUTOCONF_VERSION], [X.Y])
dnl in configure.ac before AC_INIT,
dnl without rewriting this file.
dnl Or for updating the whole tree at once with the definition above.
AC_DEFUN([_GCC_AUTOCONF_VERSION_CHECK],
[m4_if(m4_defn([_GCC_AUTOCONF_VERSION]),
  m4_defn([m4_PACKAGE_VERSION]), [],
  [m4_fatal([Please use exactly Autoconf ]_GCC_AUTOCONF_VERSION[ instead of ]m4_defn([m4_PACKAGE_VERSION])[.])])
])
m4_define([AC_INIT], m4_defn([AC_INIT])[
_GCC_AUTOCONF_VERSION_CHECK
])
```

**Review by madebr — APPROVED** [review]
I would have liked a comment in `build_requirements` on why adding autoconf as a build requirement might cause problems.
But I guess a future contributor will see the reason soon enough.

**Comment by SpaceIm** [comment]
Why is it not merged by the bot?

**Comment by SSE4** [comment]
> Why is it not merged by the bot?

there is a bug in CI, automatic merge job iterates all the PRs trying to find candidate to merge.
unfortunately, right now it aborts if it finds a merge conflict, instead of continuing the iteration.

**Pull request merged**
