### PR TITLE
doctest: Update url's to new doctest organization

### PR DESCRIPTION
**Pull request by ItsBasi**
The maintainer onqtam moved the doctest project to a dedicated organization. (https://github.com/doctest/doctest/issues/554)
This change makes it so that downloads do not have to rely on redirects.

Specify library name and version:  **doctest/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Review by ericLemanissier — DISMISSED** [review]

**Comment by Croydon** [comment]
Can someone restart the CI for this PR?

@ItsBasi you could do it be closing the PR for ~10 seconds and then re-open it

**Comment by Croydon** [comment]
Seems like Apple M1 is not supported. I'm not sure if this is upstream's fault or the recipe's

**Comment by ItsBasi** [comment]
Should i create a separate issue for 36aaea1eefac56c2522e92018f418a893b2ae764?

**Review by Croydon — APPROVED** [review]

**Comment by Croydon** [comment]
> Should i create a separate issue for [36aaea1](https://github.com/conan-io/conan-center-index/commit/36aaea1eefac56c2522e92018f418a893b2ae764)?

No, let's keep it in one PR

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
