### PR TITLE
boost/1.78.0: Add Boost 1.78

### LINKED ISSUE #8424: [request] boost/1.78.0
### Package Details
  * Package Name/Version: **boost/1.78.0**
  * Changelog: **https://www.boost.org/users/history/version_1_78_0.html**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

### PR DESCRIPTION
**Pull request by jwillikers**
Specify library name and version:  **boost/1.78.0**

Adds the latest version of Boost, version 1.78.0.
Fixes #8424.

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SSE4 — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by RamilGauss** [comment]
I use Visual Studio 2019 (toolset v142 ) with conan extension. I tried install boost 1.78. Conan version 1.43.2.

[requires]
	boost/1.78.0

23.12.2021 15:50:48: ERROR: boost/1.78.0: Error in package_info() method, line 1455
23.12.2021 15:50:48: 	"toolset": "-{}".format(self._toolset_tag),
23.12.2021 15:50:48: while calling '_toolset_tag', line 1294
23.12.2021 15:50:48: 	if self.settings.compiler in ("msvc", "Visual Studio"):
23.12.2021 15:50:48: 	ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value.
23.12.2021 15:50:48: Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc']
23.12.2021 15:50:48: Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
23.12.2021 15:50:48: Conan has returned exit code '1' while processing configuration 'Architecture: x86_64, build type: Debug, compiler toolset: v142, compiler version: 16;, runtime library: MDd'. Please check file 'C:\Trash\Test\\Exe\.conan\conan_b747d9ab-6e07-4fb6-805b-b2d8b3f6de6c.log' for details.

**Comment by jwillikers** [comment]
> I use Visual Studio 2019 (toolset v142 ) with conan extension. I tried install boost 1.78. Conan version 1.43.2.
> 
> [requires] boost/1.78.0
> 
> 23.12.2021 15:50:48: ERROR: boost/1.78.0: Error in package_info() method, line 1455 23.12.2021 15:50:48: "toolset": "-{}".format(self._toolset_tag), 23.12.2021 15:50:48: while calling '_toolset_tag', line 1294 23.12.2021 15:50:48: if self.settings.compiler in ("msvc", "Visual Studio"): 23.12.2021 15:50:48: ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value. 23.12.2021 15:50:48: Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc'] 23.12.2021 15:50:48: Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting" 23.12.2021 15:50:48: Conan has returned exit code '1' while processing configuration 'Architecture: x86_64, build type: Debug, compiler toolset: v142, compiler version: 16;, runtime library: MDd'. Please check file 'C:\Trash\Test\Exe.conan\conan_b747d9ab-6e07-4fb6-805b-b2d8b3f6de6c.log' for details.

Does your `~/.conan/settings.yml` include the `msvc` compiler? It looks like you might be missing it.

**Comment by madebr** [comment]
As @jwillikers said.
Compare `~/.conan/settings.yml` with `~/.conan/settings.yml.new`.

When upgrading your conan version, `settings.yml` might become outdated.
Imho, conan should make this easier.

**Comment by RamilGauss** [comment]
Thanks. It's works! :)

**Pull request merged**
