### PR TITLE
libiconv: .lib extension for msvc import lib instead of .dll.lib

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **libiconv/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
When we have an import lib with .dll.lib for msvc, we have to explicitly add the full name with extension to cpp_info.libs, because for a reason I don't undestand, CMake builds fail to consume those import libs. But other build systems will fail if this extension is added to cpp_info.libs.

I guess that `.dll.lib` should never be allowed for msvc import libs.

**Comment by madebr** [comment]
> When we have an import lib with `.dll.lib` extension for msvc, we have to explicitly add the full name with extension to `cpp_info.libs`, because otherwise -for a reason I don't understand- CMake builds fail to consume those import libs (see this attempt to change `libgettext` cpp_info if msvc for example #2914). But other build systems will fail if this extension is added to `cpp_info.libs` (in `qt` recipe for example).
> 
> I guess that `.dll.lib` extension should never be allowed for msvc import libs.

Can you name a consumer that is causing problems? Or a small reproducer?
Maybe it's `find_library(ICONV_LIBRARY iconv)` that is failing?
Does it only happen if the consumer uses a private `FindIconv.cmake` module instead of the conan-generated?

Anyway, good fix!

**Comment by SpaceIm** [comment]
It's `qt` bincrafters recipe. It tries to find `libiconv.dll.lib.lib`

**Comment by madebr** [comment]
@SpaceIm 
Ah thanks, so cmake is automatically adding an extra `.lib` at the linker stage.
We will need to remember this.
I think this should be a good candidate for a hook: `the .lib extensions of msvc libraries should not be added`

**Comment by SpaceIm** [comment]
Wait, not CMake I think, it's the underlying build system of qt.

Three cases:
- First:
  - generated import lib file is `libname.dll.lib`
  - self.cpp_info.libs = ["libname.dll.lib"]
  
  => seems to work with CMake (at least in test_package), but fails with qt build system on Windows.

- Second:
  - generated import lib file is `libname.dll.lib`
  - self.cpp_info.libs = ["libname.dll"]

  => CMake complains with `LINK : fatal error LNK1104: cannot open file 'libname.lib'`. Don't know for qt.

- Third:
  - generated import lib file is `libname.lib`
  - self.cpp_info.libs = ["libname"]

  => happy build systems

**Review by SSE4 — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
