### PR TITLE
libmysqlclient: requires stdc++

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **libmysqlclient/8.0.17**

this is a port of @madebr 's work on https://github.com/conan-io/conan-center-index/pull/1445

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
Thanks @ericLemanissier for picking up the pieces after me :smile:

**Comment by ericLemanissier** [comment]
now that the default is static, I noticed that it failed to link on clang because of `undefined reference to std::allocator<char>::allocator()` et al.
I did not check the two patches you added in #1445 (and `self._cmake.definitions["REQUIRE_STDCPP"] = self._stdcpp_library`). Do you think it can be needed here too ? mysql_config seems to be broken too for this package, because `mysql_config --libs_r` returns `... -lLIBMYSQL_OS_OUTPUT_NAME-NOTFOUND ...`

**Comment by madebr** [comment]
@ericLemanissier 

The `REQUIRE_STDCPP` option is my method to add `-lstdc++` or `-lc++` to the `mysql_config` util.
I thought it was ok for Linux, but I tested only using gcc9. It probably should be added to the libs list.
I don't think they removed the c++ code while going from `mysql-conector-c` to `libmysqlclient`.

I also thought that `LIBMYSQL_OS_OUTPUT_NAME` was fixed between `mysql-connector-c` and `libmysqlclient` because I did not see any errors while switching from `mysql-connector-c` to `libmysqlclient`. But if you're saying the contrary, then that patch is also needed here.

(For apr-util, I first used `mysql-connector-c` before noticing that newer versions are developed under `libmysqlclient`. Because all problems I was having with `mysql-connector-c` disappeared when moving to `libmysqlclient`, I didn't port all patches.)

**Comment by SpaceIm** [comment]
Should we consider this modification as the recommended way to package C++ libraries with C API in conan (adding stdc++ etc in system_libs if static)?

**Comment by SSE4** [comment]
@SpaceIm yes, I think it should be a common practice for C++ packages with C API. we already have some similar cases (e.g. openh264). and I believe we may need some kind of helper tool to avoid code duplication across recipes.

**Comment by madebr** [comment]
@SpaceIm @SSE4 Yes, I hope it becomes a common practice that we annotate whether a library needs to link to a c++ library, but I hope that it won't have to be done like here.

In exported cmake scripts, I spotted that it sets the [LINKER_LANGUAGE property](https://cmake.org/cmake/help/v3.0/prop_tgt/LINKER_LANGUAGE.html).

Maybe adding a attribute to `self.cpp_info` would help. e.g. `self.cpp_info.link_languages = ["c++"]`.

**Comment by SpaceIm** [comment]
It's not completly equivalent I think. In CMake, LINKER_LANGUAGE CXX requires to not force C language only.

**Comment by madebr** [comment]
> It's not completly equivalent I think. In CMake, LINKER_LANGUAGE CXX requires to not force C language only.

Indeed, how about `self.cpp_info.system_libs.append(tools.libcxx_library(self.settings))`?

**Comment by SpaceIm** [comment]
Yes, it would be nice to have such utility function.

**Comment by ericLemanissier** [comment]
@uilianries wdyt ? (sorry for pushing, it's blocking qt builds since libmysqlclient has been made static by default 8 days ago)

**Comment by jgsogo** [comment]
@SSE4 did you open the issue in Conan about that tool? If possible, it can be developed and merged into `1.26` 🎉

**Comment by SSE4** [comment]
@jgsogo yes, it's here https://github.com/conan-io/conan/issues/6990

**Comment by Enjection** [comment]
Seems like this patch breaks -static-libstdc++ in builds because libs in cpp_info.system_libs are always being linked dynamically.

**Comment by ericLemanissier** [comment]
@Enjection indeed. please see https://github.com/conan-io/conan-center-index/pull/5037

**Comment by Enjection** [comment]
@ericLemanissier is there any way to link this both this recipe and libstdc++ statically?

**Comment by ericLemanissier** [comment]
you can use this recipe as a static lib with option `libmysqlclient:shared=False`, but I'm not sure conan has a setting to use libstdc++ as a static library.

**Comment by Enjection** [comment]
I dug a little in guts of conan and looked through docs. Making such build seems impossible for now. Probably I will make an issue in main conan repo later.

**Comment by sunnycase** [comment]
+1 this breaks -static-libstdc++

**Comment by ericLemanissier** [comment]
can you please report an issue with the full information for this break, and explain how you use static libstdc++ with conan ?

**Pull request merged**
