### PR TITLE
[openssl] fix handling of CROSS_COMPILE variable beeing set in profile

### PR DESCRIPTION
**Pull request by KristianJerpetjon**
Specify library name and version:  **openssl/ALL**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
hi @KristianJerpetjon 
as I understand, the fix is for **1.0.2**, right?
have you checked, do 1.1.0 and 1.1.1 work with `CROSS_COMPILER` or need one more fix?

**Comment by KristianJerpetjon** [comment]
> hi @KristianJerpetjon
> as I understand, the fix is for **1.0.2**, right?
> have you checked, do 1.1.0 and 1.1.1 work with `CROSS_COMPILER` or need one more fix?
It seems that is still an issue. i dont want to go for the simple del os.environ['CROSS_COMPILE'] either

**Comment by SSE4** [comment]
@KristianJerpetjon I don't think it's fair to do `del os.environ["CROSS_COMPILE"]`  - if user have set this in his profile/environment, then it should be respected, as he set it with purpose - in order to get the right compiler to be used. so ignoring it is not an option for me.

**Comment by KristianJerpetjon** [comment]
Agreed.

**Comment by SSE4** [comment]
@KristianJerpetjon could you possibly rebase on master?

**Comment by KristianJerpetjon** [comment]
done.. i have tried quite a lot here and it seems to me that if both CC and CROSS_COMPILE is defined.. well the Configure is broken for versions > 1.10.0+
Any ideas ?

**Comment by SSE4** [comment]
@KristianJerpetjon I'd suggest to create an issue in OpenSSL project then. maybe then they will recommend something.
for now, fixing for 1.0.x is still an improvement, so let's merge the existing fix at least.

**Comment by SSE4** [comment]
ping @uilianries

**Comment by SSE4** [comment]
@KristianJerpetjon there are some conflicts, pls resolve

**Comment by uilianries** [comment]
@KristianJerpetjon you will need to remove https://github.com/conan-io/conan-center-index/blob/aa4b28435649ea4d9d937577636486cd315e267c/recipes/openssl/ALL/conanfile.py#L66

**Comment by KristianJerpetjon** [comment]
Needs some new approvals after i updated the content

**Comment by jheaff1** [comment]
Hi,

I believe this pull request has caused OpenSSL versions < 1.1.0 to fail when cross compiling in certain situations.

If I try to build OpenSSL version 1.0.2s using the conanio/gcc49-armv7 docker image, I get the following errro:

```bash
make[1]: arm-linux-gnueabihf-gcc-ar-4.9m-linux-gnueabihf-gcc-ar-4.9: Command not found
```

If I comment out line 374 of the conanfile.py, the build is successful. This code is only exercised if CROSS_COMPILE is not set.

Furthermore the logs given below for versions < 1.1.0 seem like they contain an error. Perhaps there were false positives in the build infrastructure

> All green! 
> 
> * `openssl/1.0.2s`: Generated 78 packages. [All logs here](https://c3i.jfrog.io/c3i/misc/logs/pr/149/9/openssl/1.0.2s/)
> * `openssl/1.0.2t`: Generated 78 packages. [All logs here](https://c3i.jfrog.io/c3i/misc/logs/pr/149/9/openssl/1.0.2t/)
> * `openssl/1.1.0k`: Generated 78 packages. [All logs here](https://c3i.jfrog.io/c3i/misc/logs/pr/149/9/openssl/1.1.0k/)
> * `openssl/1.1.0l`: Generated 78 packages. [All logs here](https://c3i.jfrog.io/c3i/misc/logs/pr/149/9/openssl/1.1.0l/)
> * `openssl/1.1.1c`: Generated 78 packages. [All logs here](https://c3i.jfrog.io/c3i/misc/logs/pr/149/9/openssl/1.1.1c/)
> * `openssl/1.1.1d`: Generated 78 packages. [All logs here](https://c3i.jfrog.io/c3i/misc/logs/pr/149/9/openssl/1.1.1d/)

**Pull request merged**
