### PR TITLE
qt6: use absolute paths for CMAKE_TOOLCHAIN_FILE path

### PR DESCRIPTION
**Pull request by enzo-pellegrini**
Specify library name and version:  **qt/6.x.x**

Fixes https://github.com/conan-io/conan/issues/16217 on 2.3.1, by setting `tc.absolute_path` to True (option introduced in https://github.com/conan-io/conan/pull/16244)

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — APPROVED** [review]
thanks !

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9125490685/attempts/1)

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@enzo-pellegrini I guess you did not see the message. in order to make your PR mergeable, you need to request access on https://github.com/conan-io/conan-center-index/issues/4

**Review by RubenRBS — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@enzo-pellegrini you are now registered (https://github.com/conan-io/conan-center-index/commit/fefb24eb626b8aac4549b51c9d089f44f0394058). Can you please restart the CI, by doing a merge or by adding an empty line to the PR description ?

**Comment by RubenRBS** [comment]
The recipe wouldn't build until 2.3.1 was added - we just did so so I've commited a new change to trigger the CI, thanks!

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
