### PR TITLE
qarchive: use maintained version of libarchive

### PR DESCRIPTION
**Pull request by ericLemanissier**
since https://github.com/conan-io/conan-center-index/commit/c4495e47cf56cdc97b0815bdd40dcec56dd11a6a

Specify library name and version:  **qarchive/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by RubenRBS — DISMISSED** [review]

**Comment by ericLemanissier** [comment]
I don't understand, `conan list libarchive/3.7.3:* -r=conancenter` has 
```
            2fa6e52eebfba2a83ddca29a07e5ce9eb87b49b1
              info
                settings
                  arch: armv8
                  build_type: Release
                  compiler: apple-clang
                  compiler.version: 13
                  os: Macos
                options
                  fPIC: True
                  shared: False
                  with_acl: True
                  with_bzip2: False
                  with_cng: False
                  with_expat: False
                  with_iconv: True
                  with_libb2: False
                  with_libxml2: False
                  with_lz4: False
                  with_lzma: False
                  with_lzo: False
                  with_mbedtls: False
                  with_nettle: False
                  with_openssl: False
                  with_pcre2: False
                  with_pcreposix: False
                  with_xattr: False
                  with_zlib: True
                  with_zstd: False
                requires
                  libiconv/1.17.Z
                  zlib/1.3.Z
```

**Review by uilianries — DISMISSED** [review]

**Comment by uilianries** [comment]
I just triggered a new build, but for some reason, didn't update the state here in GH to yellow (running).

**Comment by ericLemanissier** [comment]
network error during system package install. Can you retrigger a build @uilianries please ? thanks !

**Comment by uilianries** [comment]
> network error during system package install. Can you retrigger a build @uilianries please ? thanks !

Done, thank you for pinging

**Comment by ericLemanissier** [comment]
same error :(

**Comment by ericLemanissier** [comment]
@RubenRBS @uilianries I'm sorry to ask you again: is it possible to have a new build ? thanks

**Comment by ericLemanissier** [comment]
@jcar87 Can we get a new build for this PR ?

**Comment by RubenRBS** [comment]
Sorry about the delay!

**Comment by ericLemanissier** [comment]
@RubenRBS thank you. This time I also have the missing binary. Is there somthing you can do to regenerate missing binaries for libarchive/3.7.3 ? Currently there are only 4 when the last PR had 10 https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/23623/2/libarchive/3.7.3//summary.json
```
$ pipx run conan list libarchive/3.7.3:* -r=conancenter
conancenter
  libarchive
    libarchive/3.7.3
      revisions
        2456d159710a717790bfec6e38fa6e10 (2024-04-18 06:29:21 UTC)
          packages
            eaf00762d40ea6784d1d0d34d5e8883043a53923
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: msvc
                  compiler.runtime: dynamic
                  compiler.runtime_type: Release
                  compiler.version: 193
                  os: Windows
                options
                  shared: False
                  with_acl: True
                  with_bzip2: False
                  with_cng: False
                  with_expat: False
                  with_iconv: True
                  with_libb2: False
                  with_libxml2: False
                  with_lz4: False
                  with_lzma: False
                  with_lzo: False
                  with_mbedtls: False
                  with_nettle: False
                  with_openssl: False
                  with_pcre2: False
                  with_pcreposix: False
                  with_xattr: False
                  with_zlib: True
                  with_zstd: False
                requires
                  libiconv/1.17.Z
                  zlib/1.3.Z
            d40aeb38b6cf7a4cd7d611616534c78c7c654d2b
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: gcc
                  compiler.version: 11
                  os: Linux
                options
                  shared: True
                  with_acl: True
                  with_bzip2: False
                  with_cng: False
                  with_expat: False
                  with_iconv: True
                  with_libb2: False
                  with_libxml2: False
                  with_lz4: False
                  with_lzma: False
                  with_lzo: False
                  with_mbedtls: False
                  with_nettle: False
                  with_openssl: False
                  with_pcre2: False
                  with_pcreposix: False
                  with_xattr: False
                  with_zlib: True
                  with_zstd: False
                requires
                  libiconv/1.17.Z
                  zlib/1.3.Z
            a7c5a21646dde4c0183ae181ed62cfeb42365a92
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: apple-clang
                  compiler.version: 13
                  os: Macos
                options
                  fPIC: True
                  shared: False
                  with_acl: True
                  with_bzip2: False
                  with_cng: False
                  with_expat: False
                  with_iconv: True
                  with_libb2: False
                  with_libxml2: False
                  with_lz4: False
                  with_lzma: False
                  with_lzo: False
                  with_mbedtls: False
                  with_nettle: False
                  with_openssl: False
                  with_pcre2: False
                  with_pcreposix: False
                  with_xattr: False
                  with_zlib: True
                  with_zstd: False
                requires
                  libiconv/1.17.Z
                  zlib/1.3.Z
            5518335b7fd841a90ef004d6d7659a015b225973
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: gcc
                  compiler.version: 11
                  os: Linux
                options
                  fPIC: True
                  shared: False
                  with_acl: True
                  with_bzip2: False
                  with_cng: False
                  with_expat: False
                  with_iconv: True
                  with_libb2: False
                  with_libxml2: False
                  with_lz4: False
                  with_lzma: False
                  with_lzo: False
                  with_mbedtls: False
                  with_nettle: False
                  with_openssl: False
                  with_pcre2: False
                  with_pcreposix: False
                  with_xattr: False
                  with_zlib: True
                  with_zstd: False
                requires
                  libiconv/1.17.Z
                  zlib/1.3.Z
```

**Comment by ericLemanissier** [comment]
@uilianries is it possible to regenerate libarchive binaries (more details in my message directly above)

**Comment by ericLemanissier** [comment]
@jcar87 is it possible to regenerate libarchive binaries (more details in my message above)

**Review by RubenRBS — APPROVED** [review]

**Comment by ericLemanissier** [comment]
Thank you !

**Pull request merged**
