### PR TITLE
readosm: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
@prince-chrismc do you know why this PR is not displayed in https://github.com/prince-chrismc/conan-center-index-pending-review/issues/1?

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
No I do not :( It's there now so I dont get to investigate 



#16187 | SpaceIm | Feb 20 | 📝 readosm | L | 2 | Apr 6 |   | jwillikers
-- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/conan-io/conan-center-index/pull/16187	[SpaceIm](https://github.com/SpaceIm)	Feb 20	📝 readosm	L	2	Apr 6		jwillikers

there's nothing obvious that should have excluded it.

**Comment by prince-chrismc** [comment]
https://github.com/prince-chrismc/conan-center-index-pending-review/actions/runs/4627327085/jobs/8185113423#step:6:86

Confused I actually can check 😱

**Comment by prince-chrismc** [comment]
Ohh derp... The Assumption is that if there was a review (i.e comments or request changes) that person would follow up quickly enough and approve.

Because jordans first review was dismissed it was a non-zero (it will post no reviews) but there was no approvals so it was disgarded


***

https://api.github.com/repos/conan-io/conan-center-index/pulls/16187/reviews

```
[
  {
    "id": 1323937342,
    "node_id": "PRR_kwDODDMJAM5O6a4-",
    "user": {
      "login": "jwillikers",
      "id": 19399197,
      "node_id": "MDQ6VXNlcjE5Mzk5MTk3",
      "avatar_url": "https://avatars.githubusercontent.com/u/19399197?u=dac900db43788310516c636d63cd9245b37b51a9&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jwillikers",
      "html_url": "https://github.com/jwillikers",
      "followers_url": "https://api.github.com/users/jwillikers/followers",
      "following_url": "https://api.github.com/users/jwillikers/following{/other_user}",
      "gists_url": "https://api.github.com/users/jwillikers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jwillikers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jwillikers/subscriptions",
      "organizations_url": "https://api.github.com/users/jwillikers/orgs",
      "repos_url": "https://api.github.com/users/jwillikers/repos",
      "events_url": "https://api.github.com/users/jwillikers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jwillikers/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "",
    "state": "DISMISSED",
    "html_url": "https://github.com/conan-io/conan-center-index/pull/16187#pullrequestreview-1323937342",
    "pull_request_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/16187",
    "author_association": "CONTRIBUTOR",
    "_links": {
      "html": {
        "href": "https://github.com/conan-io/conan-center-index/pull/16187#pullrequestreview-1323937342"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/16187"
      }
    },
    "submitted_at": "2023-03-03T14:36:58Z",
    "commit_id": "d242bc7a59e64a83e45f9cf84b520de97c48619f"
  },
  {
    "id": 1374813738,
    "node_id": "PRR_kwDODDMJAM5R8f4q",
    "user": {
      "login": "jwillikers",
      "id": 19399197,
      "node_id": "MDQ6VXNlcjE5Mzk5MTk3",
      "avatar_url": "https://avatars.githubusercontent.com/u/19399197?u=dac900db43788310516c636d63cd9245b37b51a9&v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jwillikers",
      "html_url": "https://github.com/jwillikers",
      "followers_url": "https://api.github.com/users/jwillikers/followers",
      "following_url": "https://api.github.com/users/jwillikers/following{/other_user}",
      "gists_url": "https://api.github.com/users/jwillikers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jwillikers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jwillikers/subscriptions",
      "organizations_url": "https://api.github.com/users/jwillikers/orgs",
      "repos_url": "https://api.github.com/users/jwillikers/repos",
      "events_url": "https://api.github.com/users/jwillikers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jwillikers/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "",
    "state": "APPROVED",
    "html_url": "https://github.com/conan-io/conan-center-index/pull/16187#pullrequestreview-1374813738",
    "pull_request_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/16187",
    "author_association": "CONTRIBUTOR",
    "_links": {
      "html": {
        "href": "https://github.com/conan-io/conan-center-index/pull/16187#pullrequestreview-1374813738"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/16187"
      }
    },
    "submitted_at": "2023-04-06T12:57:34Z",
    "commit_id": "47efa240d39a5e74b7b02cbe15702ea85215145d"
  }
]
```

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
