### PR TITLE
[actions] Revert tj-actions/changed-file to version v20

### PR DESCRIPTION
**Pull request by uilianries**
Try to fix current linter errors:

For instance: https://github.com/conan-io/conan-center-index/pull/13526

/cc @toge 

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
@uilianries Thanks a lot! What a quick response!

**Review by jwillikers — DISMISSED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by uilianries** [comment]
CI linter told me that my linter has a bad indentation in the linter file.

**Review by jwillikers — DISMISSED** [review]

**Review by ericLemanissier — DISMISSED** [review]

**Review by toge — APPROVED** [review]

**Comment by ericLemanissier** [comment]
I don't think this will fix the error, because it happens for another job. Maybe the depth need to be infinite (PRs can have unbounded number of commits)

**Comment by uilianries** [comment]
@ericLemanissier I'm thinking the same ... Or, one error is propagated to all other linters 🤔

**Comment by ericLemanissier** [comment]
I think we should use fetch-depth 0 on all jobs which use changed-files action, so that all the history is fetched

**Comment by uilianries** [comment]
I did 2 changes now:

- Reverted to version v20, which was working 
- Changed to depth 0

**Comment by prince-chrismc** [comment]
Actions are now passing https://github.com/conan-io/conan-center-index/actions/runs/3275051354/jobs/5389394892

This leaves us with the original problem but we can take our time to fix it properly

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
> I don't think this will fix the error, because it happens for another job. Maybe the depth need to be infinite (PRs can have unbounded number of commits)

2 in github land means the merge commit and the base commit (which have all the diff between them) then one extra from the head branch that we dont care about 😄

**Review by prince-chrismc — APPROVED** [review]

**Comment by uilianries** [comment]
ping @toge @ericLemanissier for a new review.

**Review by toge — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
Have we been bitten by https://github.com/tj-actions/changed-files/releases/tag/v30.0.0 `Stop pulling partial branch history and rely on the user-specific configuration of the checkout action.`
or https://github.com/tj-actions/changed-files/releases/tag/v24 `Raise error for invalid commit sha comparison as opposed to pulling the remote for other commits.`

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
