### PR TITLE
[DO NOT MERGE][test] see if current CMake revision still builds on CI

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Comment by jgsogo** [comment]
Why is it failing now? 😕  What has changed in the CI?

**Comment by Croydon** [comment]
See also https://github.com/conan-io/conan-center-index/pull/2941

I'm not sure yet

Since we build CMake with CMake, maybe it is a bug in a newer CMake version

Which CMake version is used on Windows and macOS currently?

According to the CCI changelog the version is still 1.16.4 and wasn't changed since June 

https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md#02-june-2020---0002-cest

**Comment by madebr** [comment]
Can you instrument the build to print `CMakeFiles/CMakeOutput.log` and `CMakeFiles/CMakeError.log` on failure?

something like the following:
```python
try:
    cmake.build()
except:
    self.output.info("CMakeOutput.log")
    print(tools.load("CMakeFiles/CMakeOutput.log"))
    self.output.info("CMakeError.log")
    print(tools.load("CMakeFiles/CMakeError.log"))
    raise
```

**Comment by madebr** [comment]
The error was in the configure step.
That one should be included in the try body as well. oops.

**Comment by madebr** [comment]
I think the following is going on:
When testing the unique_ptr feature, it compiles a trivial `unique_ptr` source and checks the stdout of the compiler.
First, it filters some false warnings. If there are still warnings left, it will treat them as errors.
(see `source_subfolder/Source/Checks/cm_cxx_features.cmake`)
```
    string(REGEX REPLACE " +0 Warning\\(s\\)" "" check_output "${check_output}")
    # Filter out warnings caused by user flags.
    string(REGEX REPLACE "[^\n]*warning:[^\n]*-Winvalid-command-line-argument[^\n]*" "" check_output "${check_output}")
    # Filter out warnings caused by local configuration.
    string(REGEX REPLACE "[^\n]*warning:[^\n]*directory not found for option[^\n]*" "" check_output "${check_output}")
    string(REGEX REPLACE "[^\n]*warning:[^\n]*object file compiled with -mlong-branch which is no longer needed[^\n]*" "" check_output "${check_output}")
    # Filter out other warnings unrelated to feature checks.
    string(REGEX REPLACE "[^\n]*warning:[^\n]*sprintf\\(\\) is often misused, please use snprintf[^\n]*" "" check_output "${check_output}")
    # Filter out xcodebuild warnings.
    string(REGEX REPLACE "[^\n]* xcodebuild\\[[0-9]*:[0-9]*\\] warning: [^\n]*" "" check_output "${check_output}")
    # If using the feature causes warnings, treat it as broken/unavailable.
    if(check_output MATCHES "(^|[ :])[Ww][Aa][Rr][Nn][Ii][Nn][Gg]")
      set(CMake_HAVE_CXX_${FEATURE} OFF CACHE INTERNAL "TRY_COMPILE" FORCE)
    endif()
```

When checking `CMakeError.log`, the following warning is spewed:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(467,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\J\w\cci_PR-3053@2\.conan\data\cmake\3.16.2\_\_\build\a79a557254fabcb77849dd623fed97c9c5ab7651\CMakeFiles\CMakeTmp\cmTC_3d17c.vcxproj]
```

So I think on cci CI, the builds happen in a temporary directory.
Or the environment variables for temporary directories are not set correctly.

Googling around for `MSB8029` gave me the following tips on how to fix this:
- [Modifying the user props file](https://pniedzielski.wordpress.com/2014/02/12/fixing-warning-msb8029-with-cmake-and-msvc12/). I don't think this is a complete fix, as it will have to be done for each CI machine over and over again + also for arm (in the future).
- [Wrong environment variables](https://issue.life/questions/34744098): I don't think this is the case because this warning should have shown before. But maybe worth checking? Is the `Temp` environment variable set? [second source](https://stackoverflow.com/questions/34744098/how-to-fix-msb8029-intermediate-directory-or-output-directory-cannot-reside-und) [third source](http://showcode12.blogspot.com/2013/07/visual-studio-2013-how-to-fix-msb8029.html)

cmake has a way to add a property file to a target. But that does not apply here because the warnings is thrown during a test compile (not during compilation of a target).

**Comment by jgsogo** [comment]
Thanks a lot for noticing about this issue and the investigation. We are, indeed, assigning TMP environment variables to folders inside the workspace of each Jenkins job (the aim was to ensure that we were removing everything ASAP to avoid the disk full errors). All these environment variables are assigned to the same folder, something like:

```
tmpDir = "${env.WORKSPACE}/${env.BUILD_NUMBER}/${uid}"
env.add("TMP=${tmpDir}")
env.add("TEMP=${tmpDir}")
env.add("TMPDIR=${tmpDir}")
```

No idea why these variables could be _wrong_.

---

Good news: I'm able to reproduce it a testing environment.

**Comment by jgsogo** [comment]
The approach with the `IgnoreWarnIntDirInTempDetected` works and I think it is preferred given the CI nature of C3i (we always build from scratch, no incremental builds here).

**Microsoft.Cpp.x64.user**
```xml
<?xml version="1.0" encoding="utf-8"?> 
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
  </ImportGroup>
  <PropertyGroup Label="UserMacros">
    <IgnoreWarnIntDirInTempDetected>true</IgnoreWarnIntDirInTempDetected> 
  </PropertyGroup> 
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup />
</Project>
```

I owe you two a beer 🍻 , as soon as we can travel again!

---

If there are no objection I will ask infra-team to update machines in production with this changes... I'm afraid we will need to wait until next week :/

**Comment by madebr** [comment]
Adding a patch to ignore the MSB8029 is another solution.
This patch should be applied to all cmake versions and is a candidate for upstream.

**Comment by jgsogo** [comment]
We will ignore MSB8029 in the user props files, no need to patch anything in the recipe itself. That warning is meaningless in the C3i context.

**Comment by madebr** [comment]
> We will ignore MSB8029 in the user props files, no need to patch anything in the recipe itself. That warning is meaningless in the C3i context.

This warning is always harmless. It is currently emitted by all cmake runs on c3i.
But the cmake recipe is the only one complaining. So maybe there is a point in fixing it.
Cmake is too sensitive here, imho.

The place where it is failing (see https://github.com/conan-io/conan-center-index/pull/3053#issuecomment-702295510) does already some filtering. So maybe it requires some extra filtering.

**Comment by Croydon** [comment]
Closing as we figured out the problem

For further references, see
https://github.com/conan-io/conan-center-index/pull/3109
https://gitlab.kitware.com/cmake/cmake/-/issues/21270

**Pull request closed without merging**
