### PR TITLE
Test for conan bug: module-config problems

### PR DESCRIPTION
**Pull request by paulharris**
This PR is for testing bug conan-io/conan#11201
I have a fix to consider in conan-io/conan#11217

Note that this should be tested with the latest release-1.48.0 branch
AND with this added to the profile:
```
[conf]
tools.cmake.cmaketoolchain:find_package_prefer_config=False
```

Error message is:
```
-- Detecting CXX compile features - done
-- Found Fontconfig: 2.13.93 (found version "2.13.93") 
-- Conan: Target declared 'Fontconfig::Fontconfig'
CMake Error at /build/msrap2/devenv/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  No "Findfreetype.cmake" found in CMAKE_MODULE_PATH.
Call Stack (most recent call first):
  build/generators/FindFontconfig.cmake:25 (find_dependency)
  CMakeLists.txt:4 (find_package)
```

The problem is conan wants to import "freetype" as a MODULE, but the python code to compute the filename is assuming the caller wants the CONFIG version of the filename.

My solution is to ensure the filename-calculation is told whether the caller wants to force the MODULE or CONFIG variant.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Not sure that opening a PR in conan-center-index to test conan client bug is the good approach.

**Comment by paulharris** [comment]
I'm opening a PR here and an issue on conan, referencing it.
I'm not sure how else I should submit test cases to demonstrate the problem?
I thought it was pretty neat because then I could check CCI did the same as what I was seeing locally.

How else should I report bugs like this?

**Comment by paulharris** [comment]
I might've done a pull instead of a draft-pull by mistake, would draft-PRs be ok?

**Comment by paulharris** [comment]
Not an actual PR, should've been a draft-PR, just for pushing up a test case.  Sorry for the confusion @MartinDelille

**Pull request closed without merging**
