### PR TITLE
libarchive: bump dependencies

### PR DESCRIPTION
**Pull request by robomics**
Specify library name and version:  **libarchive/all**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by robomics** [comment]
Ping in case this fell through the cracks :) @RubenRBS

**Comment by AbrilRBS** [comment]
Hi @robomics thanks a lot for the PR and sorry about the radio silence, we should have communicated a bit better!

The current approach for CCI is to not prioritize PRs that exclusively bump dependencies without a good reasoning behind them (it removes conflicts, a bugfix is needed etc) - Even though this PR falls in this category, not communicating it was a mistake on my end, I know it feels bad when a PR goes unattended for so long for seemingly no reason :/

I'll check if these bumps make sense later today and will come back to you, thanks a lot for your patience

**Comment by AbrilRBS** [comment]
Closing as wont-merge, but does not mean we won't tackle this in the future, we'll tidy this up when the new pipeline is ready to go :)

**Comment by robomics** [comment]
No worries, I understand it is difficult to find the right balance with accepting PRs only bumping dependencies.

On my side, I've switched all my projects from using `conanfile.txt` to `conanfile.py` and override dependency's versions as needed. So it is not an issue that this PR was not merged.

**Pull request closed without merging**
