### PR TITLE
pkgconf: download archive from official url + bump meson

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **pkgconf/1.7.3**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

closes https://github.com/conan-io/conan-center-index/issues/4518

### CODE REVIEW

**Comment by Croydon** [comment]
Is someone able to compare the sources before and after? Stuff like this is really not cool and projects need to stop changing published versions 😞

**Review by intelligide — DISMISSED** [review]

**Comment by SpaceIm** [comment]
> Is someone able to compare the sources before and after? Stuff like this is really not cool and projects need to stop changing published versions 😞

I can't check, I've removed my previous versions of this source code.

**Comment by Croydon** [comment]
I'm not feeling comfortable approving this when we don't know what is changed

**Comment by rdeterre** [comment]
Would the `~/.conan/data/pkgconf` directory of a machine where version 1.7.3 of pkgconf was previously installed be helpful? I can't find the right .tar.gz in there but there is a `conan_sources.tgz` file.

**Comment by prince-chrismc** [comment]
> I'm not feeling comfortable approving this when we don't know what is changed

Pulled the repo, I do not see any lost/unattached refs... https://git.sr.ht/~kaniini/pkgconf/log#log-aca0674837cb6df1b29faddb8afe6b2f39733f6b Seems legit but we may never know.

If the author moved the tag it was also re-indexed and there's no trace.

**Review by prince-chrismc — DISMISSED** [review]

**Comment by Croydon** [comment]
Hi @kaniini, 

you seem to be the main maintainer of pkgconf. Conan is a C/C++ package manager and we have here a package for pkgconf.

We secure downloads with sha256 checksums. The checksum of `https://git.sr.ht/~kaniini/pkgconf/archive/pkgconf-1.7.3.tar.gz` just changed.

Do you know why this happened? Should we rather use the downloads of https://github.com/pkgconf/pkgconf? 

Thank you very much in advance!

**Comment by kaniini** [comment]
You’re not using the correct distfiles URL.

Use https://distfiles.dereferenced.org/pkgconf for the tarballs I generate at release time.

**Comment by kaniini** [comment]
> Is someone able to compare the sources before and after? Stuff like this is really not cool and projects need to stop changing published versions 😞

> I'm not feeling comfortable approving this when we don't know what is changed

You are literally downloading a random tarball from a git hosting service.

For stable tarballs which never change, you should be using distfiles.dereferenced.org as the readme has said to use since the beginning of the project.  I can’t control the output of git hosting service generated tarballs.

What’s “not cool” is packaging a software without reading the instructions for packagers, which amongst other things, mentions where to acquire a stable tarball for every release version.

**Comment by kaniini** [comment]
As for “what happened”, clearly the git hosting service updated either their git version or their compression utilities.  When you download a tarball from a git hosting service they generate it on demand, using whatever tools are presently installed.  This means that checksums cannot be depended upon to be stable for tarballs from git hosting services, as there’s several variables which would cause the tarball to change.

**Comment by Croydon** [comment]
Thank you for the information and apologies, my words above were more a general note, as we encountered several projects in the past, which actually did re-use published version numbers. In this case it is clearly our fault for using the wrong downloads

**Comment by kaniini** [comment]
Hopefully this encourages you to look at other download URIs and change them to the actual sources of truth.  Hopefully this encourages projects to stop treating automatically generated tarballs as a source of truth for their end users to consume.

**Comment by ericLemanissier** [comment]
@kaniini a quick suggestion here, because I don't have an account on https://todo.sr.ht/~kaniini/pkgconf. You probably want to mark https://github.com/kaniini/pkgconf as archived and indicate to use https://git.sr.ht/~kaniini/pkgconf instead, because it is outdated

**Review by ericLemanissier — DISMISSED** [review]

**Comment by dmn-star** [comment]
Are there any strong reasons not to use https://github.com/pkgconf/pkgconf here?

**Comment by SpaceIm** [comment]
in README:
> Release tarballs are available at https://distfiles.dereferenced.org/pkgconf/. Please only use the tarballs from distfiles.dereferenced.org.

**Review by intelligide — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by dmn-star** [comment]
> in README:
> 
> > Release tarballs are available at https://distfiles.dereferenced.org/pkgconf/. Please only use the tarballs from distfiles.dereferenced.org.

Yes I have already seen, the good intention was only enough for one Github release. :-)

**Review by dmn-star — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by Croydon — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
