### PR TITLE
sdbus-cpp: fix expat discovery

### PR DESCRIPTION
**Pull request by SpaceIm**
### Summary
Changes to recipe:  **sdbus-cpp/all**

#### Motivation
- move expat from build requirements to requirements. Indeed, executable created when code gen is enabled depends on it.
- remove patches related to expat discovery, changing casing of generated expat config file is sufficient
- some minor cleanups: not use of self.info in validate(), remove useless patch related to CMAKE_SOURCE_DIR (not needed with CMakeToolchain), version range for pkgconf

closes https://github.com/conan-io/conan-center-index/issues/25371

#### Details

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — COMMENTED** [review]
Great work @SpaceIm thanks a lot :)

Before being able to approve, could I get compilation logs with `-o="&:with_code_gen=True"` for future traceability? Thanks!

**Comment by SpaceIm** [comment]
> Great work @SpaceIm thanks a lot :)
> 
> Before being able to approve, could I get compilation logs with `-o="&:with_code_gen=True"` for future traceability? Thanks!

@kiozen can share its log I think.

**Comment by kiozen** [comment]
Here you are:

[conan.log](https://github.com/user-attachments/files/17144124/conan.log)

Thanks for the fix

**Review by AbrilRBS — APPROVED** [review]
Thanks!

**Review by uilianries — APPROVED** [review]
LGTM. Good catch by filtering expat, the strategy looks good:

- https://github.com/Kistler-Group/sdbus-cpp/blob/v2.0.0/CMakeLists.txt#L240
- https://github.com/Kistler-Group/sdbus-cpp/blob/v2.0.0/tools/CMakeLists.txt#L45

No other part of code is consuming expat.

**Pull request merged**
