### PR TITLE
grpc: add v1.60.0

### PR DESCRIPTION
**Pull request by valgur**
Requires
- #21592

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
@valgur , could you reopen this one, please?

**Comment by valgur** [comment]
@AndreyMlashkin It requires
* #21622

The current protobuf version is not compatible.

**Comment by grmcdorman** [comment]
There is now a security issue in the current Conan package version, CVS-2023-44487 (a DoS attack, CVSS score 7.5). This is fixed by 1.59.2 or later. This means this issue should be increased in priority.

**Comment by Nazardo** [comment]
@Ahajha @valgur I have tested this with protobuf built with the recipe in PR #21622 (4.25.3), but as @NoneOfUrBusiness12 reported there are linking errors related to missing upb_* calls. It is not clear to me whether it is a gRPC issue or not.

**Comment by Ahajha** [comment]
Currently I believe the link error is a gRPC issue. My working theory is that either it or upb (micro protobuf implementation, vendored since I don't see any other package using it, though maybe that could be changed) switched from one large "upb" library to some smaller ones.

I'm not entirely sure why it's using that package though if we supply protobuf.

**Comment by amerry** [comment]
i fixed the upb link issues with this diff (NB: this diff is based on merging this recipe with the latest grpc recipe on master):

```
diff --git a/recipes/grpc/all/conanfile.py b/recipes/grpc/all/conanfile.py
index 58c8b0e1e..9ddc69844 100644
--- a/recipes/grpc/all/conanfile.py
+++ b/recipes/grpc/all/conanfile.py
@@ -405,6 +405,26 @@ class GrpcConan(ConanFile):
                 },
             })

+        if Version(self.version) >= "1.60":
+            components.update({
+                "upb_json_lib": {
+                    "lib": "upb_json_lib",
+                    "system_libs": libm() + pthread() + crypt32() + ws2_32() + wsock32(),
+                },
+                "upb_textformat_lib": {
+                    "lib": "upb_textformat_lib",
+                    "system_libs": libm() + pthread() + crypt32() + ws2_32() + wsock32(),
+                },
+                "utf8_range_lib": {
+                    "lib": "utf8_range_lib",
+                    "system_libs": libm() + pthread() + crypt32() + ws2_32() + wsock32(),
+                },
+            })
+            extra_libs = ["upb_textformat_lib", "upb_textformat_lib", "utf8_range_lib"]
+            components["_grpc"]["requires"] += extra_libs
+            if not self.options.secure:
+                components["grpc_unsecure"]["requires"] += extra_libs
+
         return components

     def package_info(self):
```

**Comment by Ahajha** [comment]
Thanks @amerry! I can fix the merge conflicts and add the patch :)

**Comment by amerry** [comment]
Just to highlight that I updated the original diff - the version I originally posted allowed the test to link, but might cause issues for code that uses more of the grpc library (eg: JSON exports).

**Comment by grmcdorman** [comment]
Blocked by #21622 which is currently blocked by an error building the recipe with Conan 2, it appears.

**Comment by valgur** [comment]
#24165

**Pull request closed without merging**
