### PR TITLE
m4: add download mirror

### LINKED ISSUE #13769: [package] m4/1.4.19: Connection to ftp.gnu.org timed out
### Description

Sometimes building gnu packages fail due ftp.gnu.org unstability.

From here https://www.gnu.org/prep/ftp.en.html they mention https://ftpmirror.gnu.org/ to automatically choose a nearby and up-to-date mirror. Should recipes be updated to use that URL?

Similar issue in the past https://github.com/conan-io/conan-center-index/issues/9215

### Package and Environment Details

* Package Name/Version: **m4/1.4.19**
* Operating System+version: **macos 12.6**
* Compiler+version: **Apple clang 14**
* Docker image: no applicable
* Conan version: **conan 1.53.0**
* Python version: **Python 3.9.6**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter m4/1.4.19@ -pr:b default -pr:h default --build m4/1.4.19

### Logs

<details><summary>Click to expand log</summary>

```
% conan install -r conancenter m4/1.4.19@ -pr:b default -pr:h default --build m4/1.4.19
Configuration (profile_host):
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=14
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=14
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

m4/1.4.19: Retrieving from server 'conancenter' 
m4/1.4.19: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.47k]                                          
Downloading conanfile.py completed [5.07k]                                               
Downloading conan_export.tgz completed [0.33k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
m4/1.4.19: Downloaded recipe revision 94367bfc4bd2bdc63a07aaccbd69abda
m4/1.4.19: Forced build from source
Installing package: m4/1.4.19
Requirements
    m4/1.4.19 from 'conancenter' - Downloaded
Packages
    m4/1.4.19:3eb32b976fb0626f3c40a8b87ace72156aa44204 - Build

Installing (downloading, building) binaries...
Downloading conan_sources.tgz completed [3.50k]                                          
Decompressing conan_sources.tgz completed [0.00k]                                        
m4/1.4.19: Configuring sources in /Users/pfarre/.conan/data/m4/1.4.19/_/_/source/src
m4/1.4.19: ERROR: Error downloading file https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.gz: 'HTTPSConnectionPool(host='ftp.gnu.org', port=443): Max retries exceeded with url: /gnu/m4/m4-1.4.19.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x104a89c40>, 'Connection to ftp.gnu.org timed out. (connect timeout=60.0)'))'
m4/1.4.19: Waiting 5 seconds to retry...
Downloading m4-1.4.19.tar.gz completed [2884.64k] 
```
(sometimes it may completely fail after few retries)

</details>

### PR DESCRIPTION
**Pull request by Croydon**
Fixes #13769

We can specify download mirrors, so let's add both // @Hopobcn 

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
We are using this in several recipes and it is fine, but the YAML linter has a problem with that. Why and how to change it?

https://github.com/conan-io/conan-center-index/actions/runs/3328424453/jobs/5504401564

**Review by Hopobcn — DISMISSED** [review]

**Comment by Croydon** [comment]
> An example of the expected format can be found in https://github.com/conan-io/conan-center-index/blob/master/docs/package_templates/autotools_package/all/conandata.yml#L5

That is new. E.g. https://github.com/conan-io/conan-center-index/blob/720a0a9d41a8a7aef23512990c0e84f6aabb48ec/recipes/openssl/1.x.x/conandata.yml#L4 as an example

**Comment by ericLemanissier** [comment]
Yes, https://github.com/conan-io/conan-center-index/commit/70d9c6b69e67d33fa5cb04b3e9936c76a1f75e33

**Review by ericLemanissier — APPROVED** [review]

**Comment by Croydon** [comment]
> Yes, [70d9c6b](https://github.com/conan-io/conan-center-index/commit/70d9c6b69e67d33fa5cb04b3e9936c76a1f75e33)

Thanks for the link! This completely drowned in my ocean of unread notifications

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
