### PR TITLE
zstd: cache cmake + delete fPIC option if shared + fix cmake imported target

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **zstd/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

imported target is `zstd::libzstd_static` if static else `zstd::libzstd_shared` :(

https://github.com/facebook/zstd/blob/bd21e4b26460a707955e29572cd1110a550a6c5a/build/cmake/lib/CMakeLists.txt#L83
https://github.com/facebook/zstd/blob/bd21e4b26460a707955e29572cd1110a550a6c5a/build/cmake/lib/CMakeLists.txt#L93
https://github.com/facebook/zstd/blob/bd21e4b26460a707955e29572cd1110a550a6c5a/build/cmake/lib/CMakeLists.txt#L159
https://github.com/facebook/zstd/blob/bd21e4b26460a707955e29572cd1110a550a6c5a/build/cmake/CMakeLists.txt#L194

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "libzstd_static.dir\Debug\libzstd_static.tlog\libzstd_static.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\J\workspace\onan-center-pull-request_PR-2214\2\pr_2214_2_0_2\.conan\data\zstd\1.3.5\_\_\build\f27dcd2d5e453cb01f9324a959461903ce8116a0\build_subfolder\source_subfolder\build\cmake\lib\libzstd_static.vcxproj]
```
https://github.com/conan-io/conan-center-index/pull/2182#issuecomment-657541926

**Comment by uilianries** [comment]
@danimtb Seems like we still have the max path problem:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018: System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "libzstd_static.dir\Release\libzstd_static.tlog\ParallelCustomBuild.command.1.tlog". Path: libzstd_static.dir\Release\libzstd_static.tlog\ParallelCustomBuild.command.1.tlog exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\J\workspace\onan-center-pull-request_PR-2214@2\6\0_1\.conan\data\zstd\1.3.5\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\build_subfolder\source_subfolder\build\cmake\lib\libzstd_static.vcxproj]

**Comment by danimtb** [comment]
If this error is coming from MSBuild, then the only solution is to add `short_paths = True` to the recipe, as MSBuild is not able to manage long paths even if the opt-in setting is enabled in Windows.

If the error is coming from the Windows filesystem then we will have to look into this again as we already opt-in long paths config in all our Windows agents 🤔

**Comment by uilianries** [comment]
@danimtb I'm curious, CCI is using CONAN_USE_ALWAYS_SHORT_PATHS for every Windows build? 

Anyhow, this situation is weird, because we are keeping the same version, the changes in this PR should affect the path length. It seems like some internal change affected the package path length.

**Comment by danimtb** [comment]
This is what we changed:

- Enabled the long paths in all our windows agents.
- Changed CONAN_USER_HOME and CONAN_USER_HOME_SHORT to subdirectories in the `workspace` Jenkins folder so they are removed automatically by Jenkins.
- Realized the path limitation is also present in MSBuild (nothing to do with the OS opt-in).
- Changed `CONAN_USER_HOME_SHORT` to a shorter path.

So end the end, these recipes might be failing due to the `CONAN_USER_HOME` set to `C:\J\workspace\onan-center-pull-request_PR-2214@2\6\`. We could make the home path shorter in the Jenkins configuration but my point is that if this is an MSBuild error, then this issue is likely to happen to users as the `CONAN_USER_HOME` we are using has an acceptable length

**Comment by uilianries** [comment]
@danimtb Right, probably Windows users are using CONAN_USE_ALWAYS_SHORT_PATHS. I don't use, but because my user name in Windows is short: `C:/Users/uilia/...`

@SpaceIm Can you reproduce this error locally?

**Comment by SpaceIm** [comment]
No, I don't reproduce this error locally, because my user name leads to shorter base path than `C:\J\workspace\onan-center-pull-request_PR-2214@2\6\`
This one is equivalent to a 47 characters user name with default `CONAN_USER_HOME`:
`C:/J/workspace/onan-center-pull-request_PR-2214@3/5/0_2/.conan/data/zstd/1.3.5/_/_/build`
`C:/Users/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/.conan/data/zstd/1.3.5/_/_/build`

**Comment by danimtb** [comment]
I was not able to reproduce this error locally setting the CONAN_USER_HOME to the same path above but I was able to do it in our development environment. Turns out the error is related to MSBuild as pointed out earlier and it happens (I think) with the patches introduced in this PR.

I am going to test if reducing the path makes the build succeed. Otherwise, we will have to set short_paths in this case

**Comment by SpaceIm** [comment]
> Turns out the error is related to MSBuild as pointed out earlier and it happens (I think) with the patches introduced in this PR.

Mmmhh, you're right `self._cmake.configure(build_folder=self._build_subfolder)` has increased build folder path length.

**Comment by danimtb** [comment]
@SpaceIm we are going to try to reduce the workspace path in Jenkins as much as possible to improve this issue (it is happening in other PRs as well). If that doesn't solve the issue we will have to inevitably resort to `short_paths = True` in the recipe

**Comment by danimtb** [comment]
Done https://github.com/conan-io/conan-center-index/wiki/Deployment-Changelog#24-july-2020---1252-cest. CI relaunched!

**Comment by danimtb** [comment]
It worked!! 😀

**Comment by uilianries** [comment]
Thanks a lot @danimtb !

**Pull request merged**
