### PR TITLE
add automake_build_aux/1.16.1

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **automake_build_aux/1.16.1**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Should I make a PR to whitelist this package for these two checks ?

**Comment by Croydon** [comment]
From my understanding we only pick two scripts out from automake right now. Maybe we should package it completely instead?

**Comment by ericLemanissier** [comment]
I'm not sure it's worth spending some time if we have no use for the rest. These two scripts are blocking bison, libgpgerror and gettext. If other parts other parts are needed in the future, it'll always be possible to add them

**Comment by Croydon** [comment]
My concern is that we might end up packaging it anyway and then we have two similar packages which can cause confusion 🤔

**Comment by ericLemanissier** [comment]
this is useless, now that https://github.com/conan-io/conan-center-index/pull/658 is merged. thanks @madebr !

**Pull request closed without merging**
