### PR TITLE
add cpr/1.4.0

### PR DESCRIPTION
**Pull request by KingKili**
Specify library name and version:  **cpr/1.4.0**

closes: #1522

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by KingKili** [comment]
> _config.yml_ syntax error in build 1:
> 
> ```
> Only one library can be changed in the same PR: [cpr/1.3.0, cpr/1.4.0]|
> ```

I just moved 1.3.0 from all to 1.3.0 how should I handle this instead?

**Comment by uilianries** [comment]
Hi @KingKili ! Why do you need a specific folder only for 1.4.0? I didn't find any major change which requires a separated folder. Perhaps, you could use the folder `all` for any version and update the file conandata.yml and config.yml. If 1.4.0 a new patch, you can include it in all/patches and update them in conandata.yml

**Comment by KingKili** [comment]
Okay, thanks, should I move the 1.4.0 patches in another folder, since they are pretty similar just matching the new format of the files?

**Comment by uilianries** [comment]
> Okay, thanks, should I move the 1.4.0 patches in another folder, since they are pretty similar just matching the new format of the files?

Move them to the same folder. You can rename them adding a prefix or suffix with the version.

**Pull request merged**
