### PR TITLE
arrow: add version 11.0.0

### PR DESCRIPTION
**Pull request by raulcd**
Specify library name and version:  **arrow/11.0.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Thanks for your contribution :)
Please remember to request access [here](https://github.com/conan-io/conan-center-index/issues/4) for the PR to be mergeable!

**Comment by raulcd** [comment]
> Thanks for your contribution :) Please remember to request access [here](https://github.com/conan-io/conan-center-index/issues/4) for the PR to be mergeable!

Thanks @RubenRBS ! I did it a couple of days ago but nothing has happened: https://github.com/conan-io/conan-center-index/issues/4#issuecomment-1538478278

**Comment by RubenRBS** [comment]
Ouch, you missed the bot processing the messages by a few hours, the next one will be later tomorrow :)

**Comment by raulcd** [comment]
Currently waiting for the authorized PR to be merged: https://github.com/conan-io/conan-center-index/pull/17522

**Comment by RubenRBS** [comment]
Thanks a lot @raulcd :)

**Pull request merged**
