### PR TITLE
usockets: add version 0.8.3

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **usockets/0.8.3**

- add version 0.8.3
- Since 0.8.3, usockets don't provide `uSockets.vcxproj`, upstream provides makefile for cl.exe

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
Ummm.
License has expired again.

```
The license for Visual Studio has expired.
```

**Comment by toge** [comment]
@uilianries 
Please help me.
There is Visual Studio license issue.

**Comment by toge** [comment]
@uilianries 
Could you help me?

**Comment by uilianries** [comment]
@toge sorry my delay. I'll check it, thanks for reporting!

**Comment by toge** [comment]
@uilianries 
Thank you for your help!

**Comment by toge** [comment]
@uilianries 
Thanks a lot!
Now it works fine.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
