### PR TITLE
libcurl: disable unix sockets in MSVC and mingw

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **libcur/all**

In mingw, libcurl recipe is failed by "--enable-unix-sockets=True" which is default value.
I think it should be deleted in mingw because mingw has never supported unix sockets.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — COMMENTED** [review]
How is subsystem setting related to mingw? 🤯

**Comment by toge** [comment]
@prince-chrismc 
Because I think cygwin and msys2 provide a layer of support for unix sockets, I would make using `subsystem`.

**Review by prince-chrismc — APPROVED** [review]

**Comment by SSE4** [comment]
these seem to be [UNIX domain sockets](https://man7.org/linux/man-pages/man7/unix.7.html) (`AF_UNIX`). as I understand, they are supported on Windows nowadays: https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
so it's shouldn't be needed to disable them on these platforms.

**Review by SSE4 — CHANGES_REQUESTED** [review]
Windows 10 supports AF_UNIX, please change the code to support UNIX domain sockets for Windows (no subsystem)

**Comment by toge** [comment]
@SSE4 
I did not know about that.
Thank you for the information.

It seems that there is another reason for the unix domain related error in mingw, so I will look into it a bit.

**Comment by SSE4** [comment]
> It seems that there is another reason for the unix domain related error in mingw, so I will look into it a bit.

what's the error message, by the way?
P.S. you don't need to handle MinGW in the first iteration, it could be always added later, on-demand. as I can see, MinGW users aren't blocked and may use `-o libcurl:with_unix_sockets=False`

**Comment by toge** [comment]
@SSE4 
Thank you for the information.
Now I think my PR is in-adequate to solve error on MinGW.
So I will close this PR.

While I will find the way to solve compilation error, I will use libcurl with `with_unix_sockets=False`.

Here is error message.
```
checking whether to enable Unix domain sockets... yes
checking for struct sockaddr_un.sun_path... no
configure: error: --enable-unix-sockets is not available on this platform!
libcurl/7.80.0:
libcurl/7.80.0: ERROR: Package '726735111b86f9c53cbf4bb53c8c1c2adc9b7854' build failed
libcurl/7.80.0: WARN: Build folder C:\Users\toge\.conan\data\libcurl\7.80.0\_\_\build\726735111b86f9c53cbf4bb53c8c1c2adc9b7854
ERROR: libcurl/7.80.0: Error in build() method, line 218
        self._build_with_autotools()
while calling '_build_with_autotools', line 424
        autotools, autotools_vars = self._configure_autotools()
while calling '_configure_autotools', line 462
```

**Comment by ericLemanissier** [comment]
so, this fails: https://github.com/curl/curl/blob/master/configure.ac#L3678
```
  AC_CHECK_MEMBER([struct sockaddr_un.sun_path], [
    AC_DEFINE(USE_UNIX_SOCKETS, 1, [Use Unix domain sockets])
    AC_SUBST(USE_UNIX_SOCKETS, [1])
```
On my machine, mingw's afunix.h has 
```
#define UNIX_PATH_MAX 108

typedef struct sockaddr_un {
  ADDRESS_FAMILY sun_family;
  char sun_path[UNIX_PATH_MAX];
} SOCKADDR_UN, *PSOCKADDR_UN;
```
I'm using [MinGW-W64-builds-5.0.0 (gcc 11.2.0)](https://github.com/cristianadam/mingw-builds/releases/tag/v11.2.0-rev1)

maybe you are using an older mingw ? or somehow the include file is not the good one ?

**Comment by SSE4** [comment]
that's might be your MinGW picking up the wrong headers (e.g. from an outdated Windows SDK).
you can bypass the configure check by passing `ac_cv_member_struct_sockaddr_un_sun_path=yes`, but it may not compile with incorrect headers anyway

**Comment by toge** [comment]
@ericLemanissier  @SSE4 
Thank a lot!
I will check my MinGW SDK which was installed by scoop.

I will close this PR.

**Comment by SSE4** [comment]
well, up to you, you may add MinGW changes in another (follow up) PR, but leave this PR only with MSVC-relevant changes.

**Comment by toge** [comment]
@SSE4 
Does "MSVC-relevant changes" point out modification about moving ConanInvalidConfiguration from config() to validate()?

**Comment by SSE4** [comment]
> @SSE4 Does "MSVC-relevant changes" point out modification about moving ConanInvalidConfiguration from config() to validate()?

yes, include that moving code in validate. in other words, all the other changes, besides ones related to MinGW and subsystem.

**Comment by SSE4** [comment]
@toge any reason why is it still a draft?

**Comment by toge** [comment]
@SSE4 
No reason. I forget to close it.

**Pull request closed without merging**
