### PR TITLE
libheif: add version 1.19.5

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **libheif/1.19.5**

#### Motivation
There are several bugfixes since 1.19.0.

#### Details
https://github.com/strukturag/libheif/releases/tag/v1.19.5
https://github.com/strukturag/libheif/compare/v1.19.0...v1.19.5

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]
Thanks!

**Comment by ErniGH** [comment]
New patch has been released https://github.com/strukturag/libheif/releases/tag/v1.19.4

**Comment by toge** [comment]
@EmilienBINET 
Thanks a lot!
I will wait 12 hours before updating the PR for stability.

**Comment by toge** [comment]
updated

**Comment by AbrilRBS** [comment]
Welp, good thing we waited again, because .5 is already out!

**Review by AbrilRBS — APPROVED** [review]

**Review by perseoGI — APPROVED** [review]

**Pull request merged**
