### PR TITLE
xz_utils: fix build failure in Visual Studio Build Tools 2017 environment

### PR DESCRIPTION
**Pull request by db4**
Specify library name and version:  **xz_utils/5.2.5**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Closes https://github.com/conan-io/conan-center-index/issues/4318

### CODE REVIEW

**Comment by db4** [comment]
@madebr Can you explain what is failing? It's not obvious from CI logs

**Comment by prince-chrismc** [comment]
Most likely a runtime failure crashing the program... 

it dates from one of the first recipes =o https://github.com/conan-io/conan-center-index/pull/13 Wow! 

***

I am not sure this is related to the issue,

> use_env (Optional, Defaulted to True: Sets /p:UseEnv=true flag. Note that this setting does not guarantee that environment variables from Conan will not be used by the compiler or linker. This is an MSBuild setting which simply specifies the behavior when environment variables conflict with equivalent properties from the project (via .vcxproj, .props or .targets files). Conan will still apply the relevant compiler and linker environment variables when spawning the MSBuild process. For example, if use_env=False is specified and if there is no AdditionalDependencies variable defined in the project, the LINK environment variable passed by Conan will still be used by the linker because it technically doesn’t conflict with the project variable.

ref https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html#methods

**Comment by db4** [comment]
@prince-chrismc  
 
> Most likely a runtime failure crashing the program...

I don't see that in the logs above. Can you point me to the exact failure?

> it dates from one of the first recipes =o #13 Wow!
> 
> I am not sure this is related to the issue,
> 
> > use_env (Optional, Defaulted to True: Sets /p:UseEnv=true flag. Note that this setting does not guarantee that environment variables from Conan will not be used by the compiler or linker. This is an MSBuild setting which simply specifies the behavior when environment variables conflict with equivalent properties from the project (via .vcxproj, .props or .targets files). Conan will still apply the relevant compiler and linker environment variables when spawning the MSBuild process. For example, if use_env=False is specified and if there is no AdditionalDependencies variable defined in the project, the LINK environment variable passed by Conan will still be used by the linker because it technically doesn’t conflict with the project variable.
> 
> ref https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html#methods

Well, if no other CCI recipe contains `use_env=False`, why this one should use it? My experiments with MSBuild show that project file should contain 
```
  <PropertyGroup Label="Globals">
    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
```
to succeed with /p:useEnv=false and Visual Studio Build Tools 2017, but that doesn't seem to be an option as it introduces a specific Windows SDK dependency.

**Comment by dmn-star** [comment]
I think that is rather once again #4214

**Comment by prince-chrismc** [comment]
This might be the problem for your local setup...

https://github.com/conan-io/conan-center-index/blob/c2fd19ecf0874fefdc34abf7f96fc3b5789021da/recipes/xz_utils/all/conanfile.py#L51-L61

It's easier to remove it completely and let the build instance inject it's own... which is what the other recipes are doing

https://github.com/conan-io/conan-center-index/search?l=Python&q=WindowsTargetPlatformVersion

**Comment by db4** [comment]
@prince-chrismc 
> This might be the problem for your local setup...

Why CCI build is failing for this PR? It has nothing to do with my local setup at all.

> https://github.com/conan-io/conan-center-index/blob/c2fd19ecf0874fefdc34abf7f96fc3b5789021da/recipes/xz_utils/all/conanfile.py#L51-L61
> 
> It's easier to remove it completely and let the build instance inject it's own... which is what the other recipes are doing
> 
> https://github.com/conan-io/conan-center-index/search?l=Python&q=WindowsTargetPlatformVersion

This only applies to version 5.2.4 but I could not rebuild locally version 5.2.5. My Visual Studio build tools 2017 setup is quite straight-forward:
```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

ARG VS_VER=2017

SHELL ["cmd", "/S", "/C"]

RUN powershell Set-ExecutionPolicy Bypass -Scope Process -Force; \
  iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

#
# Visual Studio
#

RUN choco install visualstudio%VS_VER%buildtools -y
# MSVC with ATL/MFC
RUN choco install visualstudio%VS_VER%-workload-vctools --params " \
  --add Microsoft.VisualStudio.Component.Windows81SDK \
  --add Microsoft.VisualStudio.Component.VC.ATLMFC \
  " -y
```

**Comment by dmn-star** [comment]
> Why CCI build is failing for this PR? It has nothing to do with my local setup at all.

We also fight against random  Windows CCI failure .
https://github.com/conan-io/conan-center-index/pull/4205

**Comment by db4** [comment]
@dmn-star Thanks for the info. What should I do under the circumstances?  Just wait until CCI admins (or someone who has access to CCI internals) fix those Windows CI issues?

**Comment by dmn-star** [comment]
I think so. We can't get any further without Conan team help.

**Comment by SpaceIm** [comment]
Try to close/open this PR, it migh pass.

**Review by SSE4 — APPROVED** [review]

**Comment by db4** [comment]
> Try to close/open this PR, it might pass.

@SpaceIm It really helped, thank you!

**Review by madebr — APPROVED** [review]

**Review by SpaceIm — APPROVED** [review]

**Pull request merged**
