### PR TITLE
- add gsl

### PR DESCRIPTION
**Pull request by SSE4**
Specify library name and version:  **gsl/2.0.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
for this one we need to have conan center hook relaxed:
```
[HOOK - conan-center.py] post_package(): ERROR: [MATCHING CONFIGURATION (KB-H014)] Package for Header Only does not contain artifacts with these extensions: ['h', 'h++', 'hh', 'hxx', 'hpp'] (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H014)
```
as header files do not necessarily have an extension (and it's pretty legal, C++ standard doesn't enforce it)

**Comment by lasote** [comment]
Hi @SSE4, I don't know how frequently is that but I think I prefer to whitelist packages in the hook rather than stop checking if a header is correctly packaged. Could you submit a PR to the hooks repository (https://github.com/conan-io/hooks) adding a list of packages to ignore that check and adding `gsl`? Thanks

**Comment by SSE4** [comment]
@lasote  yes. sure

**Comment by uilianries** [comment]
should we use the name `gsl` or `ms-gsl` ? 

https://github.com/conan-io/conan-center-index/issues/21#issuecomment-527941643

**Comment by lasote** [comment]
> @lasote yes. sure

Please do not forget.

**Comment by Croydon** [comment]
> should we use the name gsl or ms-gsl ?

I'm voting for ms-gsl. Even in vcpkg it's named ms-gsl https://github.com/microsoft/vcpkg/tree/master/ports/ms-gsl

**Comment by SSE4** [comment]
renamed to `ms-gsl`

**Comment by SSE4** [comment]
@lasote hook whitelist: https://github.com/conan-io/hooks/pull/73

**Comment by lasote** [comment]
Merged hook relaxed and relaunched build

**Pull request merged**
