### PR TITLE
[qt] Fixes for Qt5::Multimedia

### PR DESCRIPTION
**Pull request by Renari**
Specify library name and version:  **qt/5.15.2**

Building Qt5 with the multimedia submodule is currently broken.

#5931 

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Renari** [comment]
For some reason this is trying to include shared objects while built statically:
```
g++: error: /home/arimil/.conan/data/qt/5.15.2/arimil/testing/package/38a8d9f70209e63b20c2432c9824b51fd1659bca/lib/libQt5MultimediaWidgets.so: No such file or directory
```
I haven't been able to find the cause of this yet.

**Comment by Renari** [comment]
So this issue appears to have been implemented in #5730

**Comment by ericLemanissier** [comment]
Could you please send the full lof of your failing build?

**Review by ericLemanissier — APPROVED** [review]

**Comment by Renari** [comment]
[output.txt](https://github.com/conan-io/conan-center-index/files/6677509/output.txt)

**Comment by ericLemanissier** [comment]
mm, could you try with this change https://github.com/bincrafters/conan-center-index/commit/e353695d9c4a152545fdc9c01bd21e7e617103cf ?

**Comment by Renari** [comment]
The issue persists with that change:
[output.txt](https://github.com/conan-io/conan-center-index/files/6678554/output.txt)

**Comment by ericLemanissier** [comment]
Interesting. Can you please also send the file named `/home/arimil/Documents/conan-center-index/recipes/qt/5.x.x/test_package/build/b0042734b09e12191f96d5794be36eb1522b0f13/conanbuildinfo.pri` ? What version of conan are you running ?

**Comment by Renari** [comment]
[conanbuildinfo.pri.txt](https://github.com/conan-io/conan-center-index/files/6679051/conanbuildinfo.pri.txt)

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
