### PR TITLE
Try to improve README visibility

### PR DESCRIPTION
**Pull request by uilianries**
After reading [Awesome README](https://github.com/matiassingers/awesome-readme), I think our README is not bad, all main information there. Maybe just need something to get more attention.

I added emojis because I think they are good for visual memorization and make CCI README more flashy.

You can check the preview directly on my fork: https://github.com/uilianries/conan-center-index/blob/feature/awesome-readme/README.md

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by danimtb — APPROVED** [review]
I like it!

**Review by jgsogo — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by mathbunnyru — APPROVED** [review]
Looks super-modern and nice 👍

**Comment by prince-chrismc** [comment]
Thank for removing my typo! ❤️ 
I absolutely enjoy the improvements

**Comment by uilianries** [comment]
@prince-chrismc It was the spell checker! haha I didn't see that typo too :sweat_smile:

**Pull request merged**
