### PR TITLE
(#14820) prevent xorg require when using qtwayland opt

### PR DESCRIPTION
**Pull request by EstebanDugueperoux2**
Specify library name and version:  **qt**

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by EstebanDugueperoux2** [comment]
Hi @ericLemanissier,

Do you have an idea of why "continuous-integration/jenkins/pr-merge" job is failing?

Regards.

**Comment by ericLemanissier** [comment]
I have no idea. What's happening @uilianries @danimtb ?

**Comment by ericLemanissier** [comment]
@EstebanDugueperoux2 this error will be fixed by https://github.com/EstebanDugueperoux2/conan-center-index/pull/2

**Comment by EstebanDugueperoux2** [comment]
Hi @uilianries @danimtb,

I get "check for insufficient disk space, invalid path, or insufficient privilege" from CI.
Can I close/reopen again to retrigger the CI or wait a CI fix?

Regards.

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
