### PR TITLE
add powershell/7.1.2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **powershell/7.1.2**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

closes https://github.com/conan-io/conan-center-index/issues/4555

I've tested with https://github.com/conan-io/conan-center-index/pull/4557 on Macos, and it seems to work.

### CODE REVIEW

**Comment by SpaceIm** [comment]
It will be hard to provide a robust package on Linux without building from source.

**Comment by uilianries** [comment]
I'm not opposed to building from the source, but do you think it is worth it? I see you have a package which requires Powershell, but I've never needed PS on Linux.

**Comment by SpaceIm** [comment]
> I see you have a package which requires Powershell, but I've never needed PS on Linux.

Can you run a powershell script in Linux shell?

**Comment by uilianries** [comment]
> Can you run a powershell script in Linux shell?

No, only with PowerShell interpreter. I just that version in this PR, is cover partial commands present on Windows. 

> Here is the command invoked in the library in which I need powershell: https://github.com/microsoft/glTF-SDK/blob/master/GLTFSDK/CMakeLists.txt#L15-L22

I invoked manually here, and it works on Linux:

```
$ wget https://github.com/PowerShell/PowerShell/releases/download/v7.1.2/powershell-7.1.2-linux-x64.tar.gz
$ git clone https://github.com/microsoft/glTF-SDK.git
$ cd glTF-SDK/GLTFSDK
$ ../../pwsh -ExecutionPolicy Bypass GenerateSchemaJsonHeader.ps1 -outPath GeneratedFiles/
$ file GeneratedFiles/SchemaJson.h 
GeneratedFiles/SchemaJson.h: C++ source, ASCII text, with very long lines, with CRLF, LF line terminators
```

**Comment by uilianries** [comment]
It could be related to Ubuntu version used for gcc-4.9. Let me try to reproduce same behavior there.

**Comment by SpaceIm** [comment]
Seems to be fragile.

At least, it doesn't work out of the box on Macos, powershell is not installed by default.

**Comment by uilianries** [comment]
Indeed! Running it on Ubuntu 14.04 (GCC 4.9) it doesn't work. It requires ICU too.

The package icu/68.2@ is not enough, I needed to install `libicu-dev` system package to run pwsh. 

Indeed is a bit fragile.

**Pull request closed without merging**
