### PR TITLE
lzip: bump + no `tools.os_info` in `build_requirements`

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **lzip/all**

- bump
- for https://github.com/conan-io/hooks/pull/320

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Review by SpaceIm — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by SpaceIm** [comment]
One configuration is stuck.

**Comment by SSE4** [comment]
> One configuration is stuck in CI for 2 days.

yeah, notification didn't arrive.

**Comment by prince-chrismc** [comment]
Seems to be a bug in the new GitHub status integration.

One job is in progress while the rest are green (including master job)

**Comment by ericLemanissier** [comment]
@madebr you may want to close and reopen this pr, CI seems stuck hard

**Pull request merged**
