### PR TITLE
duckdb: add recipe

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **duckdb/0.3.1**

duckdb is an embedded database engine for olap.
It is required by apache arrow >= 6.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jgsogo** [comment]
We have triggered this build manually a couple of times and it is always crashing.  It might be because it requires too much memory while building, do you know if that's the case? I'll try to monitor this PR closer and see if I can add more info.

**Comment by SSE4** [comment]
I think it should be added into the large pool:
https://github.com/duckdb/duckdb/issues/1474
https://stackoverflow.com/questions/66529271/duckdb-wont-compile-on-free-aws-ec2-instance-are-precompiled-packages-the-solu

**Comment by jgsogo** [comment]
Can someone try locally and report (aprox) the minimum required memory? Just for logging purposes, it is useful to know the limits.

**Comment by toge** [comment]
@jgsogo 

duckdb recipe requires 6.7GB memory.

here is `time -v conan create`:
```
User time (seconds): 344.12
System time (seconds): 4.45
Percent of CPU this job got: 97%
Elapsed (wall clock) time (h:mm:ss or m:ss): 5:57.59
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 6705372
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 2
Minor (reclaiming a frame) page faults: 2440644
Voluntary context switches: 9639
Involuntary context switches: 6123
Swaps: 0
File system inputs: 58984
File system outputs: 1076840
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 0
```

**Comment by jgsogo** [comment]
We are now building this reference in a larger cluster. Looks like the build succeeds (from a CI point of view), now these are regular build errors 🚀

**Comment by toge** [comment]
@jgsogo Thanks a lot!
I'm going to solve build errors.

**Comment by jgsogo** [comment]
> @jgsogo Thanks a lot! I'm going to solve build errors.

kudos to @SSE4 , he is the one pushing these changes and monitoring these PRs 🙌

**Comment by toge** [comment]
@SSE4 
Thanks a lot!
I'm always grateful for your help.

**Comment by jgsogo** [comment]
It's the second time I see this same error:

```
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I cannot remember which one was the other package, but I remember that triggering the build again, fixes the issue.

I'm afraid there is something here that we are missing... (🏓  @uilianries if it has something to do with docker images, 🏓  @danimtb to be aware of it, 🏓  @SSE4 as he is having a look to some memory issues and this PR was close to the limit before). Hopefully someone has seen this error before and can provide some insights.

**Comment by toge** [comment]
```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```
OMG!
still lack of resources.

**Comment by toge** [comment]
```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```
Still unsolved

**Comment by uilianries** [comment]
This project is a RAM vampire! I tried to build on my laptop (8GB) and it get frozen, I needed to use my PC (32GB) to finish the build. I'll try some Docker flags to limit and check if we can do it in a "limited" environment.

**Comment by uilianries** [comment]
@toge is it possible to build it without amalgamation? It kills the build.

**Comment by toge** [comment]
@uilianries 
I agree with you. I close this PR. 

duckdb without amalgamation exports a modified third party library (e.g. fmt with the original namespace).
It does not seem to be suitable for conan-center-index.

I will try to solve the problem of the third party libraries and
create a duckdb recipe without amalgamation.

**Pull request closed without merging**
