### PR TITLE
#921 Update fmt version for spdlog

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **spdlog/1.5.0**

fixes https://github.com/conan-io/conan-center-index/issues/921

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Is it possible to test the newly generated packages before the PR is merged?

**Comment by uilianries** [comment]
> Is it possible to test the newly generated packages before the PR is merged?

What do you mean by testing? The test_package already checks all generated versions.

**Comment by prince-chrismc** [comment]
I would like to download the package so I can use it locally =)
Trying to fix my CI pipeline but this is blocking me.

**Comment by uilianries** [comment]
Well, you can download this recipe and build in your local environment.

https://raw.githubusercontent.com/uilianries/conan-center-index/hotfix/fmt-spdlog-dep/recipes/spdlog/all/conanfile.py

**Comment by prince-chrismc** [comment]
I had to modify [this line](https://github.com/conan-io/conan-center-index/blob/13f1bd8aea6c96d54b549cc326b5ceea2d4a544f/recipes/spdlog/all/conanfile.py#L72) to 
`cmake.configure(source_folder=self._source_subfolder)`  which is the case for many other recipes from what I can tell. Before my modifications I got the error...

```
$ conan create .
// ...
spdlog/1.5.0: Calling build()
CMake Error: The source directory "C:/Users/cmcarthu/.conan/data/spdlog/1.5.0/_/_/build/435af6b9f903d76e9d2591bd53b1c2c4c92597b5" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
spdlog/1.5.0:
spdlog/1.5.0: ERROR: Package '435af6b9f903d76e9d2591bd53b1c2c4c92597b5' build failed
spdlog/1.5.0: WARN: Build folder C:\Users\cmcarthu\.conan\data\spdlog\1.5.0\_\_\build\435af6b9f903d76e9d2591bd53b1c2c4c92597b5
ERROR: spdlog/1.5.0: Error in build() method, line 83
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 73
        cmake.configure()
        ConanException: Error 1 while executing cd C:\Users\cmcarthu\.conan\data\spdlog\1.5.0\_\_\build\435af6b9f903d76e9d2591bd53b1c2c4c92597b5 && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\cmcarthu\.conan\data\spdlog\1.5.0\_\_\package\435af6b9f903d76e9d2591bd53b1c2c4c92597b5" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_MODULE_PATH="C:/Users/cmcarthu/.conan/data/spdlog/1.5.0/_/_/build/435af6b9f903d76e9d2591bd53b1c2c4c92597b5" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DSPDLOG_BUILD_EXAMPLE="False" -DSPDLOG_BUILD_EXAMPLE_HO="False" -DSPDLOG_BUILD_TESTS="False" -DSPDLOG_BUILD_TESTS_HO="False" -DSPDLOG_BUILD_BENCH="False" -DSPDLOG_FMT_EXTERNAL="True" -DSPDLOG_BUILD_SHARED="False" -DSPDLOG_WCHAR_SUPPORT="False" -DSPDLOG_WCHAR_FILENAMES="False" -DSPDLOG_INSTALL="True" -DSPDLOG_NO_EXCEPTIONS="False" -Wno-dev C:\Users\cmcarthu\.conan\data\spdlog\1.5.0\_\_\build\435af6b9f903d76e9d2591bd53b1c2c4c92597b5
```

I am not 100% sure how to set myself up for this infrastructure with the `conandata.yml`. I just copied the values into my `conanfile.py` 

Regardless thank you for your suggestion I now have a local copy I can test =)
This PR is greatly appreciated.

**Comment by uilianries** [comment]
> CMake Error: The source directory "C:/Users/cmcarthu/.conan/data/spdlog/1.5.0/_/_/build/435af6b9f903d76e9d2591bd53b1c2c4c92597b5" does not appear to contain CMakeLists.txt.

Are you sure that your spdlog folder is up-to-date? Did you copy the entire recipe? CMake is accusing that build_folder doesn't contain a CMakeLists.txt there. Or there is no such file in your conan-center-index/recipes/spdlog/all, Or exports_sources is not there in the recipe (not exporting the cmake file).

**Comment by prince-chrismc** [comment]
They are there just in a sub-directory from `def _source_subfolder(self):` in the recipe.

[this package](https://github.com/conan-io/conan-center-index/blob/1477c083de3800cec628d3f3efa8302d2cf74ed1/recipes/amqp-cpp/all/conanfile.py#L49) is similar and passes the source_dir to cmake.

**Comment by madebr** [comment]
@prince-chrismc the amqp-cpp recipe looks wrong.
When executing `conan create . spdlog/X.X@` for the spdlog recipe, you need to have both the conanfile.py and CMakeLists.txt (of the spdlog recipe) in your working directory.

**Comment by danimtb** [comment]
The CLA is not working? Can you check it @uilianries?

**Comment by uilianries** [comment]
I gonna check it!

**Comment by uilianries** [comment]
@danimtb restarting the PR worked!

**Comment by danimtb** [comment]
🤦‍♂

**Comment by uilianries** [comment]
Wait, Cla is not listed as mandatory check anymore!

**Comment by uilianries** [comment]
I've signed manually at https://cla-assistant.io/conan-io/conan-center-index?pullRequest=927 so it's CLA approved now.

Anyway, it sounds be a bug, CLA disappeared from this PR.

**Comment by danimtb** [comment]
I still see the check here:
image

**Pull request merged**
