### PR TITLE
Add docopt.cpp v0.6.3

### PR DESCRIPTION
**Pull request by rdeterre**
Specify library name and version:  **docopt.cpp/0.6.3**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by rdeterre** [comment]
I just added a newline at the end of "example.cpp" after reading the review of the bot.

**Comment by uilianries** [comment]
@rdeterre You need to remove pkgconfig too:

```python
def package(self):
    tools.rmdir(os.path.join(self.package_folder, "lib", "cmake"))
    tools.rmdir(os.path.join(self.package_folder, "lib", "pkgconfig"))
```

**Comment by rdeterre** [comment]
Thanks, I just pushed this change.

**Comment by danimtb** [comment]
this version has been already contributed https://github.com/conan-io/conan-center-index/blob/832df1c77dbabaefb0316854910c94316d454a13/recipes/docopt.cpp/config.yml#L4, closing the PR

**Pull request closed without merging**
