### PR TITLE
Add inih/51 recipe

### LINKED ISSUE #1150: [request] inih/48
### Package Details
  * Package Name/Version: **inih/48**
  * Website: **https://github.com/benhoyt/inih**
  * Source code: **https://github.com/benhoyt/inih**

### Description Of The Library / Tool

Simple .INI file parser in C, good for embedded systems

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **inih/51**

Fixes #1150

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
@uilianries 
These errors are coming from `meson`.
I think it needs an exception in the hooks.

**Comment by uilianries** [comment]
@madebr I see:

./bin/mesonbuild/cmake/data/preload.cmake (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H019)

But is it required? It seems be a file only for building stage.

**Comment by madebr** [comment]
@uilianries 
meson is a 100% python project. So it normally does not have any build artifacts.

**Comment by ericLemanissier** [comment]
this should pass, now that #2062 is merged

**Pull request merged**
