### PR TITLE
libassert: Bump cpptrace dependency

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
### Summary
Changes to recipe:  **libassert/v2.x.x**

#### Motivation
This PR bumps libassert's cpptrace dependency so it can benefit from new fixes

#### Details
Just bumps a dep, but depends on #24398

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]
Thanks!

**Review by RubenRBS — APPROVED** [review]

**Review by ErniGH — DISMISSED** [review]

**Comment by RubenRBS** [comment]
Sorry for the noise @jeremy-rifkin, the CI got a bit confused there :)

**Comment by jeremy-rifkin** [comment]
Thanks for the help as always! :)

**Review by franramirez688 — DISMISSED** [review]

**Review by uilianries — DISMISSED** [review]

**Comment by AbrilRBS** [comment]
Seems like our CI had an issue while uploading one of the packages, I'll retrigger this, sorry for the delay Jeremy!

**Comment by jeremy-rifkin** [comment]
Thanks so much for the help getting this squared away, please let me know if there's anything I can do on my end!

**Comment by AbrilRBS** [comment]
The Conan 1 issue is a bit weird, will check with @uilianries tomorrow, see if we can get to the bottom of it :)

**Comment by jeremy-rifkin** [comment]
It looks like another PR took care of this

**Pull request closed without merging**
