### PR TITLE
[linter] reduce pylint to just one command

### PR DESCRIPTION
**Pull request by technic**
We can make linter rules for conanfiles simpler by checking folder where conanfile.py is located from the pylint checker.
Then same rule can be applied both to test_package and regular recipe.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Is the intention here to remove https://github.com/conan-io/conan-center-index/blob/aeb068be6e7643da00c82dd259e57c0fc755bc79/linter/pylintrc_testpackage#L20?

It seems odd right now the PR in duplicating some of the other code 😳  but this is very very interesting

**Comment by technic** [comment]
> Is the intention here to remove
> 
> https://github.com/conan-io/conan-center-index/blob/aeb068be6e7643da00c82dd259e57c0fc755bc79/linter/pylintrc_testpackage#L20

I didn't notice difference between test_package and regular recipe pylintrc except ` conan-missing-name` and `conan-test-no-name`. The intention is to have one pylintrc file and don't use that enable/disable lines which you have mentioned.

If you like this change then pylintrc rules and ci scripts can be adjusted.

**Comment by prince-chrismc** [comment]
I think it's really good,  there's discussion internally about the linter being a pain point for contributing so I think this will be well received 

Make sure to comment in #4 :)

**Comment by RubenRBS** [comment]
This looks great (Sorry about the delay in getting this reviewed, we're hard at work for the 2.0 launch)

Just leaving myself a reminder that as #15177 aims to implement pre-commit hooks, it would need to be updated to support this new syntax

**Comment by ericLemanissier** [comment]
@technic can you please merge current master into your master, in order to get the fix to pylint workflow https://github.com/conan-io/conan-center-index/commit/448983ce167eab0d2057516860b3eef6346b6f1b ?

**Comment by technic** [comment]
reabsed

**Comment by RubenRBS** [comment]
Thanks, we'll look into this as soon as we can!
We are currently super busy with the imminent 2.0 release so expect this PR to be delayed a bit :)

**Comment by RubenRBS** [comment]
NOT stale, just in the backlog (Sorry @technic to keep you waiting! We really appreciate your patience)

**Comment by prince-chrismc** [comment]
@technic, we finally agreed to move forward with this change but we need to update the GitHub Actions and delete the dedicated test_package linter since those will be obsolete.

I will push some commit to help ensure this gets moving again :)

**Comment by prince-chrismc** [comment]
🤔 Not sure if these are supposed to be reported 

image

**Comment by prince-chrismc** [comment]
That matches better to https://github.com/conan-io/conan-center-index/actions/runs/4165393769 with was the last PR

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Comment by SpaceIm** [comment]
Is this PR responsible of this error https://github.com/conan-io/conan-center-index/actions/runs/4736184559/jobs/8407382514?pr=17062? Seems to be a regression.

**Comment by prince-chrismc** [comment]
Yes... Someone added checks but only in 1 of the two spots 😵‍💫 alrighty then!

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/pull/17103 :)

**Pull request merged**
