### PR TITLE
[rapidxml] Patch compilation issue with clang/gcc

### PR DESCRIPTION
**Pull request by kielby**
Fix a forward declaration issue with rapidxml which results in many compilation errors along the lines of:
```
/rapidxml_print.hpp:115:17: error: 'print_children' was not declared in this scope, and
no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
```

Issue was also reported here:
https://stackoverflow.com/questions/14113923/rapidxml-print-header-has-undefined-methods

Solution is to forward declare the various `print_` functions.

Also added use of `rapidxml_print.hpp` to verify that patch was applied correctly (will fail to compile otherwise).

Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
I'm fine accepting this patch, even it's something related to the project code, not to the building process.

The RapidXML project seems abandoned and there are several bugs reported, including this one, here: https://sourceforge.net/p/rapidxml/bugs/16/ (BTW, Stackoverflow is not a good reference as it does not host any project).

The patch offered is very similar to another in Sourceforge page.

I found many forks on Github, but nothing adopted as official.

**Comment by kielby** [comment]
I can update the PR to include that URL (https://sourceforge.net/p/rapidxml/bugs/16/) in the patch info in conandata, would you like me to do that?

I can also use the patch from that bug report if that is preferred, it looks only different by one line (which might not matter).

**Review by jwillikers — CHANGES_REQUESTED** [review]
Looks good, you just need to update `required_conan_version` to be `">=1.52.0"` for [export_conandata_patches](https://docs.conan.io/1/reference/conanfile/tools/files/patches.html?highlight=export_conandata_patches#conan-tools-files-export-conandata-patches).

**Comment by prince-chrismc** [comment]
> I can update the PR to include that URL (https://sourceforge.net/p/rapidxml/bugs/16/) in the patch info in conandata, would you like me to do that?

Please 🙏 its important to keep track of these for maintenance

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
