### PR TITLE
nlohmann_json/3.2.0

### PR DESCRIPTION
**Pull request by blackliner**
Specify library name and version:  **nlohmann_json/3.2.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Make sure to follow https://github.com/conan-io/conan-center-index/pull/3958#issuecomment-748518144

Is there a particular reason to be adding such an old version?

**Comment by blackliner** [comment]
> Make sure to follow [#3958 (comment)](https://github.com/conan-io/conan-center-index/pull/3958#issuecomment-748518144)

Already applied a few days ago, waiting to be unlocked 👍 

> Is there a particular reason to be adding such an old version?

We are using this version in our company as a checked in headerfile and we are transitioning to conan at the moment. Never versions have a compatibility issue with CUDA 10.0's nvcc

**Comment by blackliner** [comment]
wake up CI

**Comment by prince-chrismc** [comment]
Perfect let's get this merged!

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
As a new enterprise consumer, you might be interested in this https://github.com/conan-io/conan-center-index/issues/3890#issuecomment-744593510 discussion around using CCI

**Review by intelligide — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
