### PR TITLE
Fontconfig: fix FreeBSD

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **fontconfig/***

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Feel free to mark ready for review

**Comment by ericLemanissier** [comment]
I cannot test this one until libpng PR is merged. I'll mark this ready for review after testing

**Comment by ericLemanissier** [comment]
Build just passed on https://github.com/ericLemanissier/conan-center-index/runs/1602655977?check_suite_focus=true

**Comment by ericLemanissier** [comment]
@SSE4 are you ok with this one ?

**Review by SSE4 — APPROVED** [review]
I am okay. happy to see FreeBSD-related contributions.

**Pull request merged**
