### PR TITLE
civetweb: bump openssl

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **civetweb/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — DISMISSED** [review]

**Comment by ericLemanissier** [comment]
`libcivetweb-cpp.a: error adding symbols: Archive has no index; run ranlib to add one` wat ?

**Review by mathbunnyru — APPROVED** [review]
Let's take advantage of this change to also remove OPENSSL_INCLUDE_DIR variables patching.
It will make recipe easier and more future-proof.

**Comment by mathbunnyru** [comment]
@ericLemanissier I also don't know what the issue is with the linkage :(

**Review by mathbunnyru — DISMISSED** [review]

**Review by mathbunnyru — APPROVED** [review]
I'm OK with disabling LTO, but I don't know CCI policy about it.

**Comment by ericLemanissier** [comment]
My ideas are not very clear regarding LTO interaction with conan, but I think that when linking a program with LTO (as a consumer), all the object files (conan requirements) need to be compiled with LTO. So it does not seem to me that it can work, except if conan treats `LTO` option of recipes as a "special" option, and automatically checks that the full dependency graph uses LTO during validate step.

**Review by prince-chrismc — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@SSE4 @uilianries What do you think about this one ?

**Comment by SSE4** [comment]
IMO LTO and few other flags (e.g. RTTI, exceptions, etc.) fall into the category that should be enabled for all libraries, but we're not modelling them right now. I'd assume LTO=off by default for now.

**Review by theirix — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
