### PR TITLE
add dbus requirement for building qt webengine on linux

### LINKED ISSUE #14603: [package] qt/6.4.1: qwebengine requires dbus on linux
### Description

When building qt 6.4.1 on linux with qwebengine, qwebengine requires dbus.
An extra validation is needed that qt is built with the `with_dbus` option enabled when compiling for linux.

I'm not sure how to handle the cross compilation case, so I did not open a PR.

### Package and Environment Details

* Operating System+version: **Alma linux 8.6**
* Compiler+version: **GCC 10**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
[conf]
tools.system.package_manager:mode=install
tools.cmake.cmaketoolchain:generator=Ninja

### Steps to reproduce

conan install -r conancenter qt/6.4.1@ -pr:b=default -pr:h=default -o shared=True -o qtwebengine=True -o qtwebchannel=True -o qtwebsockets=True

### Logs

<details><summary>Click to expand log</summary>

```
Configuring submodule 'qtwebchannel'
Configuring submodule 'qtwebengine'
-- Checking 'ulimit -n'
 -- Open files limit 1048576
-- Support check for QtWebEngine failed: Build requires dbus.
Configuring submodule 'qtwebview'
```

</details>

### PR DESCRIPTION
**Pull request by EricAtORS**
Specify library name and version:  **qt/\***

This PR closes #14603 

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — DISMISSED** [review]
why `self.settings.get_safe("os")` as opposed to `self.settings.os`?

**Review by ericLemanissier — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@EricAtORS you are [now authorized](https://github.com/conan-io/conan-center-index/commit/dca9ab64ad98edb5dd8dcf70a2397731eb9ee5fb). Can you close this PR and re-open it, to trigger CI ?

**Comment by uilianries** [comment]
I just triggered it now.

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
> I wasn't sure when to call get_safe vs just direct access to the os attribute.

https://docs.conan.io/en/latest/reference/conanfile/attributes.html#settings

Basically, it's used when an setting can be or not available.

**Pull request merged**
