### PR TITLE
(#15330) hiredis: use self.settings instead of self.info.settings

### LINKED ISSUE #15330: [package] hiredis/1.1.0: referencing self.info.settings instead of self.settings
### Description

I am trying to build the Hiredis package for conan2, but it fails with the error:

```
ERROR: hiredis/1.1.0: Error in package_info() method, line 95
        if self.info.settings.build_type == "Debug":
        ConanException: 'self.info' access in 'package_info()' method is forbidden
```

I pulled the code locally and I think the fix should be:

```
diff --git a/recipes/hiredis/all/conanfile.py b/recipes/hiredis/all/conanfile.py
index 40c8d8d1f..f2c851704 100644
--- a/recipes/hiredis/all/conanfile.py
+++ b/recipes/hiredis/all/conanfile.py
@@ -92,7 +92,7 @@ class HiredisConan(ConanFile):
         if Version(self.version) >= "1.1.0":
             if is_msvc(self) and not self.options.shared:
                 suffix += "_static"
-            if self.info.settings.build_type == "Debug":
+            if self.settings.build_type == "Debug":
                 suffix += "d"

         # hiredis
```

### Package and Environment Details

* Package Name/Version: **hiredis/1.1.0**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 9**
* Conan version: **conan 2.0.0beta8**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

### Steps to reproduce

 conan install -r conancenter hiredis/1.1.0@ -pr:b=default -pr:h=default

### Logs

<details><summary>Click to expand log</summary>

```
-------- Installing (downloading, building) binaries... --------
hiredis/1.1.0: Already installed!
ERROR: hiredis/1.1.0: Error in package_info() method, line 95
        if self.info.settings.build_type == "Debug":
        ConanException: 'self.info' access in 'package_info()' method is forbidden
```

</details>

### PR DESCRIPTION
**Pull request by hpe-ykoehler**
Specify library name and version:  **hiredis/1.1.0**

Trying to make it works for conan2.

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

fixes #15330

### CODE REVIEW

**Comment by hpe-ykoehler** [comment]
I would definitely be interesting in knowing exactly how I can test this change locally and with the conan-center hook activated.  It was not clear to me as a newbie what were the exact steps to achieve that.

**Review by SpaceIm — APPROVED** [review]

**Comment by SpaceIm** [comment]
@hpe-ykoehler It's explained in https://github.com/conan-io/conan-center-index/blob/master/docs/developing_recipes_locally.md

**Comment by hpe-ykoehler** [comment]
@spacelm will go have a look and try it out, appreciated.

**Comment by hpe-ykoehler** [comment]
Testing was a breeze, good work to whoever wrote that doc.

Test 1.56 and 2.0.0.b8

**Comment by hpe-ykoehler** [comment]
Related to this issue https://github.com/conan-io/conan-center-index/issues/15330

**Comment by hpe-ykoehler** [comment]
The PR and the issue seem to have the same number id, and in my commit, I put that ID, would not that be enough to link them and make their status similar? newbie to contributing via GitHub, last time I did, PR was using a different number than Issue.

What "message" do you mean when you say "in first message"? Do you mean a comment? a commit message?  I looked at other commit message in that repo to write mine, copying the style, of previous one.

**Comment by SpaceIm** [comment]
I've copied pasted the one of your message actually. Correct issue this PR fixes is https://github.com/conan-io/conan-center-index/issues/15330. And title doesn't matter, it must be put in first message, not title, with keywords `closes` or `fixes``  before, see github documentation.

**Comment by hpe-ykoehler** [comment]
ok so I added "fixed #15330" in the PR's first message at the top.

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Make sure to comment in #4 to get acces

**Comment by prince-chrismc** [comment]
> Testing was a breeze, good work to whoever wrote that doc.

I am glad you found it helpful 😊

**Review by prince-chrismc — APPROVED** [review]
There's some linters comments too but not required

**Review by franramirez688 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
