### PR TITLE
override sentry default backend and not the backend itself

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **sentry-native/0.4.17**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
Unfortunatelly this does not work as expected.
Logic in config_options does not override default_options.
@memsharded should I open a linked ticket in conan client?

**Comment by AndreyMlashkin** [comment]
Do someone know, why a warning is showed, even if there is such line in a recipe:

```
        elif self.settings.os == "Windows":
            self.cpp_info.system_libs = ["shlwapi", "dbghelp"]
            if tools.Version(self.version) >= "0.4.7":
                self.cpp_info.system_libs.append("Version")
```

**Comment by prince-chrismc** [comment]
> Do someone know, why a warning is showed, even if there is such line in a recipe

@ericLemanissier might be able to help 🤞

**Review by prince-chrismc — APPROVED** [review]

**Comment by ericLemanissier** [comment]
Most probably because of the capital V on the lib name, which should be lower case

**Comment by AndreyMlashkin** [comment]
@prince-chrismc @ericLemanissier @uilianries @SSE4, please review

**Comment by ericLemanissier** [comment]
As you realized. This does not work. What you can do is to add an `auto` value to this option, and sit is a default. Then in the configure(self) method, if the option value is still `auto`, you can set the actual backend depending on the settings (directly self.option.backend=... to override the `auto` value)

**Pull request closed without merging**
