### PR TITLE
[fix] entt/all: Add all base settings for build helpers to work

### PR DESCRIPTION
**Pull request by Minimonium**
Specify library name and version:  **entt/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Minimonium** [comment]
@SpaceIm Please create separate PRs for style changes from fixes/new versions. Otherwise, it can create breaking changes like this one. Thank you!

**Comment by SpaceIm** [comment]
Ok. What removing os, build_type and arch break exactly, since entt is header-only? I didn't see any difference.

**Comment by Minimonium** [comment]
It breaks the `CMake` build helper. While the result itself is header-only - CMake is still required to generate projects relying on settings:
https://github.com/conan-io/conan/blob/develop/conans/client/build/cmake_flags.py#L39
https://github.com/conan-io/conan/blob/develop/conans/client/build/cmake_flags.py#L72

**Comment by Minimonium** [comment]
Specifically, it breaks CMake generator deduction for Visual Studio toolsets.

**Pull request merged**
