### PR TITLE
Add mfast CMake wrapper

### PR DESCRIPTION
**Pull request by mathbunnyru**
Specify library name and version:  **mfast/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
You'll need to merge master into your branch or make an empty commit to trigger CI it was having a bad day

**Comment by mathbunnyru** [comment]
Reopening the PR doesn't help

**Comment by uilianries** [comment]
Try again

**Comment by mathbunnyru** [comment]
When you did it, pr-merge restarted. Why did it work for you and not for me?

**Comment by prince-chrismc** [comment]
> When you did it, pr-merge restarted. Why did it work for you and not for me?

I presume that there is an internal list in the CI that only enables that features for certain contributors 🙊

**Comment by mathbunnyru** [comment]
I would love to be in this list as well 😂

**Comment by uilianries** [comment]
Nope, you have to wait like 10 secs before re-opening the PR ;)

**Comment by mathbunnyru** [comment]
Thanks :)
That's non-intuitive, and funny at the same time :)

**Comment by prince-chrismc** [comment]
> Nope, you have to wait like 10 secs before re-opening the PR ;)

🤯 Now we know the secret https://github.com/conan-io/conan-center-index/pull/3484 Thank you!

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Review by Croydon — APPROVED** [review]

**Pull request merged**
