### PR TITLE
Update to all the vulkan packages

### PR DESCRIPTION
**Pull request by espositofulvio**
Vulkan packages/SDK 1.2.176.1

vulkan-headers
vulkan-loader
vulkan-validationlayers
spirv-headers
spirv-tools
spiirv-cross
glslang
shaderc

This is an update to all the Vulkan packages to match the latest LunarG SDK: 1.2.176.1

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
ping @SpaceIm I dont know the connection between these but it seems odd, can you take a peak please

**Comment by SpaceIm** [comment]
I would prefer to create a dedicated version of `spirv-headers` with our `cci.<version>` convention, the lack of new tag in this library prevents `spirv-tools`, `glslang`, `shaderc`, `vulkan-validationlayers` and `moltenvk` to be updated.
`spirv-headers`, `spirv-tools`, `glslang` and `shaderc` don't follow Vulkan SDK version convention, it will be confusing to change version convention for those recipes, others package manager don't.

**Comment by espositofulvio** [comment]
OK I did't know about the history of those packages, just started using conan 15 days ago :)

So I'll make the necessary changes to follow @SpaceIm description and will update the pull request soon.

**Comment by SpaceIm** [comment]
Important: CCI allows tu update only one recipe per PR.

So basically you may want to update spirv-headers or vulkan-headers first, then work on others recipes.

**Comment by espositofulvio** [comment]
> Important: CCI allows tu update only one recipe per PR.
> 
> So basically you may want to update spirv-headers or vulkan-headers first, then work on others recipes.

Thanks for the heads up! So I'll guess I'll update spirv-headers first, vulkan-headers is already updated at the latest.

**Comment by prince-chrismc** [comment]
Thanks for the awesome contribution @espositofulvio. You picked a really hard on to start but I am glad you understood what space described because I am still lost!

Hope to review your next PR ;-)

**Pull request closed without merging**
