### PR TITLE
Propagate channel to boost dependencies

### PR DESCRIPTION
**Pull request by klimkin**
Use same channel for dependencies

Specify library name and version:  **boost/1.73.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
Wouldn't this be better added as a conan feature?

**Comment by Croydon** [comment]
Did you try to work with overwrites of dependencies?

I agree with @madebr. This is something we certainly should not start to support on a recipe-per-recipe case.

**Comment by danimtb** [comment]
I agree with the comments above. This is something we are not willing to support in ConanCenter recipes. If you would like to discuss something like this as a feature, feel free to open an issue in https://github.com/conan-io/conan

**Comment by klimkin** [comment]
It's ok. Is it an expectation for conan-center-index packages to have blank user/channel? I mean if boost depends on xz with xz without channel, and some other package depends on boost, then boost wont' have channel as well...

**Comment by madebr** [comment]
@klimkin 
Your pr was technologically completely fine. It just doesn't scale for all recipes on CCI.

**Comment by Croydon** [comment]
> Is it an expectation for conan-center-index packages to have blank user/channel?


All packages in CCI are without user/channel

**Pull request closed without merging**
