### PR TITLE
Added DataFrame version 1.15.0

### PR DESCRIPTION
**Pull request by hosseinmoein**
Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — CHANGES_REQUESTED** [review]
Don't delete old versions

**Comment by hosseinmoein** [comment]
> Don't delete old versions

Done

**Comment by prince-chrismc** [comment]
This is a duplicate FYI

**Comment by hosseinmoein** [comment]
> This is a duplicate FYI

I was not aware something else was doing this. As long as one of them goes through, I am fine. 
What should we do now?

**Comment by prince-chrismc** [comment]
#4051 was opened minutes before this one xD

Please close this, the other one has more reviews... which feel free to approve if you like =)

**Comment by hosseinmoein** [comment]
Conflict

**Pull request closed without merging**
