### PR TITLE
onetbb: moved check for shared hwloc to validate method

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
Specify library name and version:  **onetbb/2021.10.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by valgur — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@SpaceIm @jcar87 @uilianries 
Could you please review and merge?
The change is quite simple

**Review by jwillikers — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@SpaceIm @jcar87 @uilianries
Could you please review and merge?
The change is quite simple

**Review by SpaceIm — APPROVED** [review]
Could you please keep methods by order of execution please? All this PRs introducing hwloc have made the recipe harder to understand since methods have been injected a little bit randomly.

Moreover in another PR you have added pkgconf to build requirements with a build_requires. It's tool_requires.

**Comment by ilya-lavrenov** [comment]
> Could you please keep ConanFile methods by order of execution please (not specific to this PR but other ones you have made in this recipe for hwloc)? Recipe is harder to understand since methods have been injected a little bit randomly.
> 
> Moreover in another PR for onetbb you have added pkgconf to build requirements with a build_requires. It's tool_requires.

I don't know the order of execution. 
Conan maintainers should implement such checks as conanfile linter.

**Comment by SpaceIm** [comment]
There is no linter, but it's documented as part of package templates in conancenter doc.

Still build_requirements is broken for conan v2 client.

**Comment by ilya-lavrenov** [comment]
> There is no linter, but it's documented as part of package templates in conancenter doc.
> 
> Still build_requirements is broken for conan v2 client.

updated. Please, check.

**Comment by ilya-lavrenov** [comment]
@RubenRBS 
Please, have a look. The change is quite small and simple.

**Review by uilianries — CHANGES_REQUESTED** [review]
Blocking this PR internal discussion first. It will fix the current problem in CCI, but it's a workaround. There is an internal PR to fix the situation with Jenkins. We could approve it, but let's discuss the impact first.

**Review by uilianries — APPROVED** [review]
After talking to Conan team, your PR looks the best solution so far. It will have the impact of no longer building OneTBB as static library ( not recommended by the author anyway).

In the future we should provide a better solution, providing support with mixed shared and static configuration with Conan 2.x.

LGTM

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
