### PR TITLE
Add protobuf v3.15.8

### PR DESCRIPTION
**Pull request by apogza**
Specify library name and version:  **protobuf/3.15.8**

There are some applications that require this version.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@apogza Thank you for your contribution, please, don't forget to sign the CLA listed above. The access request should be approved and authorized by the bot automatically. Regards.

**Comment by apogza** [comment]
> 

Thank you. I have accepted the CLA. I'm having trouble with the continuous-integration/jenkins/pr-merge process. I am not able to visualize any details.

**Comment by apogza** [comment]
@uilianries, 
Thank you. I have accepted the CLA. I'm having trouble with the continuous-integration/jenkins/pr-merge process. I am not able to visualize any details. Any ideas what might be going wrong?

**Comment by uilianries** [comment]
@apogza the Access Request is a separated step which we have periodic reviews every week (3 times), then we approve (or not if it's suspicious/malicious) and the CI bot put you in the allowed list. Then, the CI bot will run your PR. So far, your recipe is waiting. Maybe this process is a bit boring for you, but it's useful, as in the past we had few incidents. I believe by tomorrow it should be approved.

Please, read to obtain more information: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#request-access

**Comment by apogza** [comment]
> @uilianries ,
I do not find the process boring at all. I am sure that there are good reasons for it to be the way it is. Since it is new to me I was just wondering if this step fails because I have done something wrong or I haven't done something like you kindly reminded me for the CLA.
Thank you for your time and clarifications.

**Pull request merged**
