### PR TITLE
Update upstream for fmt/6.1.1

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **fmt/6.1.1**

This version should be working with Visual Studio

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
they do releases every 3 days?

**Comment by Morwenn** [comment]
Is it even worth providing the 6.1.0 when it's been alive for 3 days before 6.1.1 and the recipe requires a dedicated fix that is solved by 6.1.1?

**Comment by SSE4** [comment]
I don't think we need to support so many minor versions. I guess latest 6.x and latest 5.x would be enough. or latest 5.3.x, latest 6.0.x and latest 6.1.x.

**Comment by Morwenn** [comment]
It would probably be easier to not break things if version ranges were consistently used I guess.

**Comment by madebr** [comment]
```python
if self.options.header_only:
    self.info.header_only()
```
in `package_info(self)` should be moved to the `package_id(self)` member function.

**Comment by uilianries** [comment]
Remember that 6.1.0 has a bug which does not work with Visual Studio 15

**Comment by uilianries** [comment]
> ```python
> if self.options.header_only:
>     self.info.header_only()
> ```
> 
> in `package_info(self)` should be moved to the `package_id(self)` member function.

done

**Pull request merged**
