### PR TITLE
docs: spelling and formatting

### PR DESCRIPTION
**Pull request by prince-chrismc**
Docs!

- 85% is just formatting was inconsistent in some files
- code fences, trailing white space
- heading levels

The biggest thing is there were small typos (dont git blame they are probably my fault) that I discovered while working on docs

### CODE REVIEW

**Review by jgsogo — APPROVED** [review]
Thanks for taking care of these details. Greatly appreciated.

---

We need to agree on something _standard_ across the documentation when importing and using tools. I would say `from conan import tools` and then `tools.xxxx.yyyy`, which is aligned with what people started to use with `conans` namespace. If we prefer to use `from conan.tools.xxxx import yyyy` I'm fine with it, but whatever is our choice we should try to adhere to it. cc/ @uilianries @danimtb

**Comment by danimtb** [comment]
@jgsogo be careful with the imports. I learnt recently that there is a certain way of doing that: https://github.com/conan-io/docs/issues/2706

**Review by danimtb — APPROVED** [review]
Awesome! thank you for doing this 🙏

**Comment by jgsogo** [comment]
I see. Given https://github.com/conan-io/docs/pull/2708, then we should prefer `from conan.tools.xxxx import yyyy` 👍

**Review by uilianries — COMMENTED** [review]
Thank you a lot!

**Comment by prince-chrismc** [comment]
My brain hurts from the xxxyyyyzzzz 🙈 

So practically we should have `import files from conan.tools` and do `files.get(self, )` and `files.copy(self,)` ??
or so we go one level down?

**Comment by prince-chrismc** [comment]
> Thanks for taking care of these details. Greatly appreciated.

Wait till I open https://github.com/prince-chrismc/conan-center-index/tree/docs-overhaul 😈

**Pull request merged**
