### PR TITLE
Rename cpp-taskflow to taskflow

### PR DESCRIPTION
**Pull request by intelligide**
Specify library name and version:  **taskflow**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
I don't think we can rename it that way, as it would be breaking for some consumers.
did project perform sort of re-branding?
/cc @danimtb @uilianries

**Comment by intelligide** [comment]
Yes. Starting from v2.5.0, cpp-taskflow been renamed to **_taskflow_**, as you can see in [the official project repository](https://github.com/taskflow/taskflow) and in the [release notes](https://taskflow.github.io/taskflow/release-2-5-0.html).

**Comment by Croydon** [comment]
I believe that the census was that we do not delete recipe directory from the git directory, but instead deprecate it and then create a new directory with the new name and the new files

We don't have yet an established standard of HOW to deprecate recipes, this was briefly discussed in https://github.com/conan-io/conan-center-index/issues/1304

But I think we should, add the very minimum, adding a Conan Warning to the existing recipe recommending the new one

**Comment by uilianries** [comment]
I totally agree with @Croydon

**Comment by uilianries** [comment]
I'll wait for https://github.com/conan-io/conan-center-index/pull/2013/ first.

**Comment by prince-chrismc** [comment]
Would it be worth wild adding taskflow/2.5.0 in this PR?

**Comment by intelligide** [comment]
I plan to add 2.5.0 after this pr is merged.

**Pull request merged**
