### PR TITLE
fruit: add version 3.7.0

### PR DESCRIPTION
**Pull request by tt4g**
Specify library name and version:  **fruit/3.7.0**

A new minor version has been released.

Note the patch file ``fix-cmakelists-problems.patch, which had been divided into several files, is now combined into a single file.
This is because patch compatibility was often lost with version upgrades.

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by tt4g** [comment]
It appears that CI failed to include the dependent library boost.
However, I could not reproduce this problem on my machine.

Are there problems inherent in CI?

**Comment by tiolan** [comment]
@tt4g seems we did almost the same work in parallel.
In the PR linked above I kept the original patch structure of 3.6.0 and just updated it for 3.7.0.
This PR here introduces a slightly different approach by creating another patchfile, though the outcome should be somehow equivalent.
Which PR do you think we should continue with?

**Comment by tt4g** [comment]
@tiolan I have not been actively developing C/C++ recently, and have no knowledge of migration to conan v2.

I believe your PR should be a priority.
Please reply if you have time to do fruit recipe update. I will close this PR.

**Comment by tiolan** [comment]
Oh on the Conan V2 migration I also need to check. Just wanted to avoid double work. I'll investigate and come back.

**Comment by tt4g** [comment]
@tiolan Note I do not plan to include migration to v2 in this PR either, as it would be burdensome for reviewers to include multiple tasks in one PR.

**Comment by tiolan** [comment]
No progress on my end, as I am still awaiting access to the build pipeline.

**Comment by tt4g** [comment]
No progress on my end either. I am thinking that I will have to ask the maintainer to check CI as [the problem](https://github.com/conan-io/conan-center-index/pull/14569#issuecomment-1336331992) cannot be reproduced on the local machine.

**Comment by tt4g** [comment]
Close as work is in progress on #14574.

**Pull request closed without merging**
