### PR TITLE
bump poco 1.11.0

### PR DESCRIPTION
**Pull request by paulo-coutinho**
Specify library name and version:  **poco/1.11.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

---

Release:
https://raw.githubusercontent.com/pocoproject/poco/poco-1.11.0-release/CHANGELOG
and
https://github.com/pocoproject/poco/releases/tag/poco-1.11.0-release

### CODE REVIEW

**Review by uilianries — DISMISSED** [review]
A parada é sinistra (LGTM)

**Comment by paulo-coutinho** [comment]
Something related to:
https://github.com/libexpat/libexpat/blob/a28238bdeebc087071777001245df1876a11f5ee/expat/lib/xmlparse.c#L2526

**Comment by Nekto89** [comment]
There are some changes in dependencies between Poco components - https://github.com/pocoproject/poco/pull/2929/files

**Comment by Nekto89** [comment]
There are new components in 1.11.0: ActiveRecord and ActiveRecord Compiler - they are enabled by default. ActiveRecord also forces Data to be enabled.

**Comment by uilianries** [comment]
> There are new components in 1.11.0: ActiveRecord and ActiveRecord Compiler - they are enabled by default. ActiveRecord also forces Data to be enabled.

This part is easy, I can send you a PR. The main problem is libexpat

**Comment by Nekto89** [comment]
> 
> 
> > There are new components in 1.11.0: ActiveRecord and ActiveRecord Compiler - they are enabled by default. ActiveRecord also forces Data to be enabled.
> 
> This part is easy, I can send you a PR. The main problem is libexpat

I don't know whether conan should provide XML_DTD definition or Poco should include expat_config.h before expat.h

**Comment by uilianries** [comment]
@paulo-coutinho Consider https://github.com/paulo-coutinho/conan-center-index/pull/1

**Comment by paulo-coutinho** [comment]
Hi @uilianries,

There is an error message:

```
MSBUILD : error MSB4166: Child node "7" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\J\w\BuildSingleReference\20966\9176df34-7c91-4799-9ed4-2052e05ec9c9\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
```

This is a CI error or recipe error?

Thanks.

**Comment by paulo-coutinho** [comment]
Finally!

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
