### PR TITLE
ceres-solver/1.13.0

### PR DESCRIPTION
**Pull request by blackliner**
Specify library name and version:  **ceres-solver/1.13.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by prince-chrismc — CHANGES_REQUESTED** [review]
Wait why are you adding an older version?

**Comment by blackliner** [comment]
> Wait why are you adding an older version?

yes we are using 1.13.0 from apt currently, and our guys do not want to upgrade right now because they are concerned about possible performance degradation. They do not have time to investigate right now

**Review by prince-chrismc — APPROVED** [review]
LGTM 🚀

**Comment by blackliner** [comment]
@SSE4 or @uilianries would you be so kind 😁

**Review by madebr — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
