### PR TITLE
Bump opencv's zlib requirement to [>=1.2.11 <2] range

### PR DESCRIPTION
**Pull request by RubenRBS**

### CODE REVIEW

**Review by uilianries — DISMISSED** [review]

**Comment by hexablob** [comment]
> ### Conan v1 pipeline ✔️
> All green in build 2 (`fe1db8286c864d80131bbc35539283e6afb4118e`):
> 
> * **opencv/3.4.17:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/20128/2/opencv/3.4.17//summary.json))
> * **opencv/4.5.5:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/20128/2/opencv/4.5.5//summary.json))
> * **opencv/3.4.12:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/20128/2/opencv/3.4.12//summary.json))
> * **opencv/4.1.2:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/20128/2/opencv/4.1.2//summary.json))
> * **opencv/4.5.3:**
>   All packages built successfully! ([All logs](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/20128/2/opencv/4.5.3//summary.json))

Can we run the v2 pipeline too @RubenRBS please? would be much appreciated 🙏

**Comment by RubenRBS** [comment]
Hi @hexablob thanks for your ping!

The v2 pipeline was also run for this PR, but the bot did not include it in its message because the job was manually triggered from our side :)

**Comment by hexablob** [comment]
from 

`[requires]
opencv/4.5.5@#7d07b377070251361a21f3e380985aeb`

I'm encountering some build errors @RubenRBS 

```
opencv/4.5.5: ERROR: 
Package '429a613cba00ea8cfa0aa8825bf8f19a994e5a1d' build failed
opencv/4.5.5: WARN: Build folder /Users/jvq/.conan2/p/b/openc7bccf80a20fc2/b/build/Release
*********************************************************
Recipe 'opencv/4.5.5' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: opencv/4.5.5: Error in build() method, line 1386
        cmake.build()
        ConanException: Error 2 while executing
``` 

here's my conan profile:

```
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos
```

**Comment by RubenRBS** [comment]
Hm, that's weird, I'm checking on my side with a similar configuration, will let you know once I know more, thanks for bringing this to my attention! :)

**Comment by RubenRBS** [comment]
Weirdly enough, on my end I get a good compilation:
`conan install --requires="opencv/4.5.5#7d07b377070251361a21f3e380985aeb" -r=conancenter --build=missing`
with
```
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos
```
seems to work

**Comment by hexablob** [comment]
@RubenRBS seems like something is wrong with the clang command:

`../src/meson.build:1:0: ERROR: Unable to detect linker for compiler `clang -Wl,--version -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch arm64`
stdout: 
stderr: ld: unknown options: --version` missing a space between `-Wl,` and `--version`

**Comment by RubenRBS** [comment]
This seems to be a meson issue - Is the error coming from meson < 1.2.0?

**Comment by hexablob** [comment]
@RubenRBS seems like related to the Meson 1.0.0 build system version :
```
The Meson build system
Version: 1.0.0
Source dir: /Users/jvq/.conan2/p/b/pkgco9bfb144fde998/b/src
Build dir: /Users/jvq/.conan2/p/b/pkgco9bfb144fde998/b/build-debug
Build type: native build
../src/meson.build:1: WARNING: Keyword argument "default_options" defined multiple times.
WARNING: This will be an error in future Meson releases.
Project name: pkgconf
Project version: 1.9.3

../src/meson.build:1:0: ERROR: Unable to detect linker for compiler `clang -Wl,--version -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch arm64`
stdout: 
stderr: ld: unknown options: --version 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by RubenRBS** [comment]
pkgconf should get its meson dependency bumped to fix this issue

**Pull request merged**
