### PR TITLE
abseil: Add 20240116.1, remove old versions

### PR DESCRIPTION
**Pull request by Ahajha**
Specify library name and version:  **abseil/20240116.1**

I've removed some of the older versions, mainly out of date "patch" versions (for example, keeping 20230125.3 but removing .2/.1/.0).

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Ahajha** [comment]
Note to self: I don't like the way the edge case is handled, I think it should either be an invalid configuration, or just patch the problem.

**Comment by RubenRBS** [comment]
Just a heads up that `tensorflow-lite` uses one of the removed options

**Comment by RubenRBS** [comment]
I've asked the current tensorflow PR to do that for you :)

**Comment by Ahajha** [comment]
I've reported the GCC7/C++17 issue upstream here: https://github.com/abseil/abseil-cpp/issues/1635. I'm hoping it's a simple fix that could be backported, as that would be the simplest solution rather than the hack I have in place.

**Comment by Ahajha** [comment]
There was a std::result_of workaround (it was removed in C++20) added in #6383, it was fixed as of https://github.com/abseil/abseil-cpp/commit/e19260fd7dbef881492fd73891e0be5bd4a09b95, which was late 2020. None of the versions at this point need these extra defines to work. I also tested locally with an MSVC/C++20 build.

**Comment by Ahajha** [comment]
This should be good to go now, we now have the proper upstream fix backported so no need for any hacky workarounds.

**Review by RubenRBS — APPROVED** [review]
Approving to ghet the new version out asap, will bump tensorflow in a bit :) Thanks a lot

**Review by franramirez688 — APPROVED** [review]

**Pull request merged**
