### PR TITLE
qt 6.2.4

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **qt/6.2.4**

fixes conan-io/conan-center-index#9207

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Why is this not recognized as a bump version change ?
It would be much more efficient to not rebuild passed qt versions.

**Comment by SSE4** [comment]
> Why is this not recognized as a bump version change ? It would be much more efficient to not rebuild passed qt versions.

I think because of qtmodules.conf, wdyt @uilianries ?

**Comment by ericLemanissier** [comment]
@SSE4 @jgsogo this pr seems to be stuck on the last 11 checks for 4 days :/ is there something I can do ?

**Review by AndreyMlashkin — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]
wow, so many linter messages, this time it was hard to see actual changes among linter messages 😆

**Pull request merged**
