### PR TITLE
github config: allow forks to manually run TOC generation

### PR DESCRIPTION
**Pull request by prince-chrismc**
Config!

Small quality of life to see what changes are bing made locally and how the impact the final product

### CODE REVIEW

**Comment by jgsogo** [comment]
With this change, I guess you can trigger the job manually for the default branch in a fork?

**Comment by uilianries** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

**Comment by prince-chrismc** [comment]
You can trigger it for any branch! And the actions are smart enough to open the PR against the correct branch 🚀 

https://github.com/prince-chrismc/conan-center-index/actions/runs/2952113029
https://github.com/prince-chrismc/conan-center-index/pull/34

**Comment by jgsogo** [comment]
I didn't remember that the branch selector goes after the "Run workflow"... 🙌 

image

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by prince-chrismc** [comment]
I love GitHub Actions 🙊

**Pull request merged**
