### PR TITLE
adding up-cpp receipe

### PR DESCRIPTION
**Pull request by MelamudMichael**
Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MelamudMichael** [comment]
Hi @ericLemanissier  How can i check why the builds failed ?

@conan-center-bot
c3i/conan-v2/pr-merge — This commit cannot be built
Required
[Details](https://ci-conan-prod.jfrog.team/job/prod-v2/job/cci/job/PR-22684/9/display/redirect)
@conan-center-bot
continuous-integration/jenkins/pr-merge — This commit cannot be built
Required
[Details](https://ci-conan-prod.jfrog.team/job/prod-v1/job/cci/job/PR-22684/9/display/redirect)

**Comment by MelamudMichael** [comment]
> it's written in the comments above:
> 
> > Sorry, the build is only launched for Access Request users. You can request access [writing in this issue](https://github.com/conan-io/conan-center-index/issues/4).

Thanks @ericLemanissier
and is it mandatory? or the pr can be pushed and reviewed without it?

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/README.md

**Comment by MelamudMichael** [comment]
@conan-center-bot
c3i/conan-v2/pr-merge — This commit cannot be built
Required
[Details](https://ci-conan-prod.jfrog.team/job/prod-v2/job/cci/job/PR-22684/9/display/redirect)
@conan-center-bot
continuous-integration/jenkins/pr-merge — This commit cannot be built
Required
[Details](https://ci-conan-prod.jfrog.team/job/prod-v1/job/cci/job/PR-22684/9/display/redirect)

**Comment by uilianries** [comment]
Hello @MelamudMichael ! Thank you for your first contribution! I'll send you a PR with some suggestions, it reflects my code review.

**Comment by uilianries** [comment]
@MelamudMichael Please, consider the PR https://github.com/MelamudMichael/conan-center-index/pull/1 as review and improvement. Some important notes:

- Please, read carefully the documentation as this is your first PR. I strongly recommend reading https://github.com/conan-io/conan-center-index/tree/master/docs/adding_packages#two-creating-a-package
- You need to use only the upstream project, not your fork. For those cases when the upstream does not offer a release, you may follow: https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases

**Comment by MelamudMichael** [comment]
> * cases when the upstream does not offer a release, you may follow: https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases

Hi @uilianries 

I am making the necessary changes on my fork , and then once working , we will push the change to main branch and create the package from there 

Can you please elaborate a little bit more about - **The up-cpp requires up-core-api first. I would ask to create a separated PR only for that dependency. We really avoid downloading more than 1 project per package**

is it not allowed to clone a dependency inside the conanfile.py?

**Comment by uilianries** [comment]
> is it not allowed to clone a dependency inside the conanfile.py?

@MelamudMichael No. We use separated packages for each project. The thing is, both project can change, and be used separated, I mean, you can use up-core-api without up-cpp, so it can use a specific revision, but if you keep a download keep directly in up-cpp, you can't manage it.

**Comment by MelamudMichael** [comment]
Hi @uilianries 
 is compiling to msvc is mandatory or can it be bypassed?

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
[options]
*/*:shared=False

**Comment by uilianries** [comment]
> Hi @uilianries is compiling to msvc is mandatory or can it be bypassed?
> 
> [settings] arch=x86_64 build_type=Release compiler=msvc compiler.cppstd=14 compiler.runtime=dynamic compiler.runtime_type=Release compiler.version=193 os=Windows [options] _/_:shared=False

Hello @MelamudMichael Well, in can you are having trouble to build on Windows, but the project is supported there, you can skip it. It's required that you add a clear comment about what is happening, so some contributor has a hint how to fix it. Example:

```
def validate(self):
    # FIXME: Found an error when trying to build on Windows, need help to fix it:
    # <link to the build log in CCI>
    # <part of the compilation error>
    if is_msvc(self):
        raise ConanInvalidConfiguration(f"{self.ref} recipe is not prepared to be built by Visual Studio. Contributions are welcome.")
```

**Comment by uilianries** [comment]
@MelamudMichael Could you please try the patch that I sent you in the PR https://github.com/MelamudMichael/conan-center-index/pull/1. It should be stable enough and minimally work. 

Please, try building the recipe locally first, and in case having a blocker, please, try to clarify, so we can help you.

**Comment by PLeVasseur** [comment]
@MelamudMichael -- could you close this in favor of #23733?

**Pull request closed without merging**
