### PR TITLE
span-lite: fix cmake names

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **span-lite/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by danimtb** [comment]
I think the changes in this PR will produce the issue described in https://github.com/conan-io/conan/issues/7574, so maybe we have to wait for the fix in Conan 1.29 before merging this

**Comment by prince-chrismc** [comment]
Space opened a few more of these in the same situation, I don't think it should prevent merging them

**Review by danimtb — CHANGES_REQUESTED** [review]
let's wait for conan-io/conan#7574 to be fixed

**Review by madebr — APPROVED** [review]

**Comment by prince-chrismc** [comment]
This PR is unblocked

**Review by danimtb — APPROVED** [review]

**Pull request merged**
