### PR TITLE
[cppcheck/2.12.0] Add version

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Transient network error on GitHub's side, relaunching v1 pipeline :)

**Comment by MartinDelille** [comment]
Let me know how it works so we can have this patch removed for the next versions!

**Comment by RubenRBS** [comment]
For v2, only linux-gcc has completed for now, which seems to work

https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19724/1-linux-gcc/cppcheck/2.12.0//summary.json

**Comment by ericLemanissier** [comment]
C3I tries only release build for Conan V2, but this patch fixes the debug build, so this won't be testable on C3I

**Comment by ericLemanissier** [comment]
@MartinDelille I think this can be closed, with https://github.com/conan-io/conan-center-index/pull/19729 merged and the need for the patch clarified, right ?

**Comment by MartinDelille** [comment]
yes

**Pull request closed without merging**
