### PR TITLE
Add Intel parallelstl package

### PR DESCRIPTION
**Pull request by planetmarshall**
Specify library name and version:  **parallelstl/20200330**

- [ x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by planetmarshall** [comment]
> Some configurations of 'parallelstl/20200330' failed in build 2 (`c106e4770feec50765df4bf5795bc417bec20639`):
> 
> * **Windows x86_64, Debug, Visual Studio 14,  MTd**
>   
>   * [Log download](https://c3i.jfrog.io/c3i/misc/logs/pr/2072/2/parallelstl/20200330/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/create_stdout.txt)
>   * [Log error Download](https://c3i.jfrog.io/c3i/misc/logs/pr/2072/2/parallelstl/20200330/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/create_stderr.txt)
>   * [Profile](https://c3i.jfrog.io/c3i/misc/logs/pr/2072/2/parallelstl/20200330/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/profile.txt)
> * [Access to all the logs](https://c3i.jfrog.io/c3i/misc/logs/pr/2072/2/parallelstl/20200330/)

Not seeing an error here other than tbb being missing (should it not be built automatically by CI?)

**Comment by uilianries** [comment]
@danimtb @jgsogo @SSE4 I'm not sure using the parallelstl for this recipe. Intel ParallelSTL was moved to oneapi-src/oneDPL. I vote for using the new name, to keep the new project identity. If the name has been changed, in the future people will look for oneDPL and not parallelstl.

**Comment by planetmarshall** [comment]
> @danimtb @jgsogo @SSE4 I'm not sure using the parallelstl for this recipe. Intel ParallelSTL was moved to oneapi-src/oneDPL. I vote for using the new name, to keep the new project identity. If the name has been changed, in the future people will look for oneDPL and not parallelstl.

Yeah wasn't quite sure what to make of that. There's no oneDPL release as of yet (still in beta) - my main reason for including this recipe was to have a Parallel STL implementation I could use with libc++ - I'm not sure what the status of the "official" LLVM implementation is - it doesn't seem to be included with any of the standard libc++ packages. I noted that there was a PR for llvm but it hasn't been updated in a while.

I guess changing the name is "principle of least surprise".

**Comment by planetmarshall** [comment]
> @danimtb @jgsogo @SSE4 I'm not sure using the parallelstl for this recipe. Intel ParallelSTL was moved to oneapi-src/oneDPL. I vote for using the new name, to keep the new project identity. If the name has been changed, in the future people will look for oneDPL and not parallelstl.

OK done, I've added a note in the description. I've retained the cmake find package name as `ParallelSTL` as that matches the release version. I haven't looked into the beta release yet but will keep track and update the package when it's released.

**Pull request merged**
