### PR TITLE
nss: Add support for building NSS for aarch64

### PR DESCRIPTION
**Pull request by jwillikers**
One false-positive compiler warning had to be silenced for GCC.
I used XCFLAGS as done Fedora's NSS RPM spec file.

Specify library name and version:  **nss/3.xx**

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@jwillikers please, remove the line 38 from your recipe. It's forcing the shared option to true, which is failing for your case. As validate() already discards static library, that line does not make sense.

**Comment by jwillikers** [comment]
> @jwillikers please, remove the line 38 from your recipe. It's forcing the shared option to true, which is failing for your case. As validate() already discards static library, that line does not make sense.

Thanks! I've done that.

**Comment by ericLemanissier** [comment]
forcing shared option is necessary, otherwise no conan-center package can require nss

**Comment by uilianries** [comment]
@ericLemanissier I see, because static won't be available ... 🤦

**Comment by jwillikers** [comment]
> @ericLemanissier I see, because static won't be available ... facepalm

I've reverted that so that nss configures as a shared library.

**Comment by uilianries** [comment]
@ericLemanissier What about default_option shared=True instead, then remove that option?

**Comment by uilianries** [comment]
@jwillikers could you please remove that line again and replace the default option shared=True? I gonna open a PR to hooks and link here.

**Comment by ericLemanissier** [comment]
note that this would solve the problem that sqlite3 will always be shared, because nss does not support static, and it won't have an MT binary available.

**Review by uilianries — APPROVED** [review]

**Review by ericLemanissier — CHANGES_REQUESTED** [review]
@uilianries please remove you approval, the default value for shared must be set to True before merge

**Review by uilianries — CHANGES_REQUESTED** [review]
default option for shared must be True

**Comment by jwillikers** [comment]
> default option for shared must be True

Done.

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
