### PR TITLE
Feature/openssl apple flags

### PR DESCRIPTION
**Pull request by prsolucoes**
Specify library name and version:  **openssl/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Added a flag name "add_apple_flags" that is "True" by default to don't change current behaviour. But we can disable to use other toolchains like "https://github.com/ezored/conan-darwin-toolchain".

Tested here with ezored toolchain for ios and mac (also android).

### CODE REVIEW

**Comment by uilianries** [comment]
Saudações @prsolucoes! Thanks for your contribution!

**Comment by prsolucoes** [comment]
@uilianries Agora só falta revisarem, já está tudo verde.

**Comment by SSE4** [comment]
I am tentative about adding an option being an optimal solution. probably, we just shouldn't add these flags if they are already in place.

**Comment by prsolucoes** [comment]
> I am tentative about adding an option being an optimal solution. probably, we just shouldn't add these flags if they are already in place.

I can make another PR removing it if you want.

**Comment by prsolucoes** [comment]
Hi, any decision about it?

**Comment by danimtb** [comment]
@prsolucoes I think adding an option like this is not the solution to the issue. If the library can build without setting those flags then it is okay to change that and, IIUIC, that will make it possible to build the lib with different toolchains

**Comment by prsolucoes** [comment]
@danimtb ok, but what is the solution? i think that add this flags is wrong and cannot be override, so the best option is remove or accept this PR to make it optional.

**Comment by SSE4** [comment]
@prsolucoes I am going to open another PR checking this flags are already specified by other means (toolchain, environment variables, etc). in other words, recipe will add these flags only if they aren't specified already.

**Pull request closed without merging**
