### PR TITLE
Bump miniaudio

### PR DESCRIPTION
**Pull request by ruilvo**
Specify library name and version:  **miniaudio/0.10.34**

I maintain this recipe, not the author of the library.
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by prince-chrismc** [comment]
@ruilvo can we block this one?

A development oversight caused the release of another version in this short span. For 0.10.34 the C++ build was broken, which was fixed on this version.

**Comment by ruilvo** [comment]
@prince-chrismc Well, I leave that up to you. Indeed I don't see any reason why 0.10.34 would be used, since it's a bugged version with a fix in under 24h. But if you want it for the sake of completeness, here it is. If you don't care, we can block this one and only deal with #5343 only.

**Review by prince-chrismc — CHANGES_REQUESTED** [review]
No need to merge something that's broken

**Comment by Croydon** [comment]
@ruilvo Since you are the author of the PR and you don't see any reason for it anymore, I would say let's close it 

We only add versions that are actively wanted

**Comment by ruilvo** [comment]
Okay, let's ignore this then.

Closed.

**Pull request closed without merging**
