### PR TITLE
add glslang/11.5.0

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **glslang/11.5.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
implements
https://github.com/conan-io/conan-center-index/issues/6090

**Comment by espositofulvio** [comment]
glslang 11.5.0 requires a recent version of spirv-tools and spirv-headers. I've got a pull request for spirv-headers under approval https://github.com/conan-io/conan-center-index/pull/6078, and will later push spirv-tools, glslang, vulkan-validationlayers and shaderc as well. I've got all of them built locally, I just have to follow the dependency graph in pushing the changes.

**Comment by AndreyMlashkin** [comment]
Oh, it will take time. CI builds take very long in the last time.

**Comment by AndreyMlashkin** [comment]
@espositofulvio, could you please try my branch? I am getting some strange linkage errors

**Comment by AndreyMlashkin** [comment]
Or do you already have glslang/11.5.0 in your branch somewhere? Could you please shared it?
I will then close this PR

**Comment by espositofulvio** [comment]
> Or do you already have glslang/11.5.0 in your branch somewhere? Could you please shared it?
> I will then close this PR

Hi @AndreyMlashkin,
I've already got glslang 11.5.0 build in a local branch, I was waiting for spirv-tools to get merge before pushing it. The link errors are probably due spirv-tools 2021.2 not merged yet in the master branch. If you tried my pull request than it's probably because glslang added a couple more targets to their build and it needs adjustments in conanbuild.py. I'll push glslang next as soon as spirv-tools is merged, so I guess you can close this one.

**Pull request closed without merging**
