### PR TITLE
openvino: added OpenVINO 1.0 API headers for older releases

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
Specify library name and version:  **lib/1.0**

Required for OpenCV https://github.com/conan-io/conan-center-index/pull/21204 since it still uses old API in some places

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Blocked by https://github.com/conan-io/conan-center-index/pull/22281

**Comment by ilya-lavrenov** [comment]
@RubenRBS could you please help? What is wrong with Conan v2 CI? I cannot access the link and the status is red.

**Comment by ilya-lavrenov** [comment]
CC @SpaceIm

**Comment by ilya-lavrenov** [comment]
@uilianries @RubenRBS 
Could you please approve and merge?

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by ilya-lavrenov** [comment]
> license/cla

@uilianries do I need to care about this handing check? 
I've contributed to conan-center-index numerous times and I suppose CLA checks should be Ok with me :)

**Comment by uilianries** [comment]
> > license/cla
> 
> @uilianries do I need to care about this handing check? I've contributed to conan-center-index numerous times and I suppose CLA checks should be Ok with me :)

@ilya-lavrenov sometimes the CLA bot gets stuck, so just need to push it again. Fortunately, anyone can do it. In this case just need a HTTP GET to https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=22289

**Pull request merged**
