### PR TITLE
libavrocpp: Bump to 1.10.2

### PR DESCRIPTION
**Pull request by alejandro-colomar**
**libavrocpp/1.10.2**

Bump version

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — APPROVED** [review]

**Comment by SpaceIm** [comment]
Same comment than https://github.com/conan-io/conan-center-index/pull/5672#issuecomment-850300949

**Comment by alejandro-colomar** [comment]
I've always worked with git and don't know how to fix these patches in a large scale.  And git fails to apply 0001.  How do you normally do it?

**Comment by alejandro-colomar** [comment]
I'm not sure how I should handle patch 0002.  Could you please have a look at it?

Thanks,

Alex

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Please do not force push

**Comment by alejandro-colomar** [comment]
Hi @prince-chrismc ,

I'm sorry for the inconvenience caused by my push forces.

I can't test locally for the reasons here: https://github.com/conan-io/hooks/issues/157, so the first CI runs when I open a PR are actually a replacement for my local testing, and I would normally test that locally and do commit amends before ever pushing.

If you would like to help me fix that problem, I'd send you much more mature PRs where I don't need to amend any commits, and may only add commits at the tip of the branch.

Nevertheless, I'll try to avoid them a bit more.

Cheers,

Alex

**Comment by prince-chrismc** [comment]
Yes I am familiar with that problem....

> I would normally test that locally and do commit amends before ever pushing.

You do not need to amend! You can just push as many commits as you like... CCI automatically squashes on merge.
It does not matter if a commit fails, just push new commits.

**Comment by alejandro-colomar** [comment]
> 
> 
> Yes I am familiar with that problem....
> 
> > I would normally test that locally and do commit amends before ever pushing.
> 
> You do not need to amend! You can just push as many commits as you like... CCI automatically squashes on merge.
> It does not matter if a commit fails, just push new commits.

Yup... except for a bit of garbage in the ending commit msg such as:

* add x

* revert "add x"

* fix typo
...

But yes, I'll do that for now (mostly)

**Comment by uilianries** [comment]
Do not force your commits! Like Chris said, we use merge squash, and we don't read commit messages as a change log, because the PR page works better because there are more discussion involved, so doesn't message if you have garbage in commit message. Also, forced push breaks the review, which is very important part of PR. So, again, don't use forced commit, we just don't banished it because there is no such feature in Github.

**Review by uilianries — APPROVED** [review]
LGTM, Thank you for your contribution!

**Comment by alejandro-colomar** [comment]
> LGTM, Thank you for your contribution!

You're welcome :-)

BTW, ...
```
$ wtf is LGTM
Gee...  I don't know what LGTM means...
```

https://www.mankier.com/6/wtf

https://salsa.debian.org/games-team/bsdgames/-/tree/master/wtf

Maybe you could add that one :P

**Comment by prince-chrismc** [comment]
Looks good to me xD LOL

**Comment by alejandro-colomar** [comment]
Yup, DuckDuckGo helped what wtf(1) didn't :)

BTW, I found out that the BSD version (sourceforge) has LGTM.

It's Debian that has a very very old version.

I'll report them a bug.

**Comment by uilianries** [comment]
@alejandro-colomar Try https://www.urbandictionary.com/ for web language. It has been worked for me.

**Comment by alejandro-colomar** [comment]
Yes, I know it.  It's just that I discovered `wtf(1)` recently and I liked it sooo much that I tend to use it now all the time, hehe.

And working with a terminal, it;s much easier than having to open the browser... :-)

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
