### PR TITLE
libtool: allow to link static libs into shared libs for cygwin & mingw

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

It should fix shared builds with MinGW for several recipes (gdal, maybe also libgettext)

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
For Windows platforms, will this fix linking static libraries into shared libraries once and for all?
MSVC has the same problem..

**Comment by SpaceIm** [comment]
I don't know. You can test:
- install libtool package for msvc and patch libtool.m4 in generated package
- build a recipe where libtool is a build requirement if Visual Studio.

Anyway, there are several issues for the moment:
- very weird issue: if msys2 is updated in test_package (without the modification in libtool.m4), the build fails on github action for msvc (undefined reference when shared ltdl is built), but it doesn't fail on AppVeyor.
  github action: https://github.com/SpaceIm/conan-libtool/actions/runs/800802146
  Appveyor: https://ci.appveyor.com/project/SpaceIm/conan-libtool/builds/38959512/job/9hxk4b9slj1f1q44
- modification of libtool.m4 in source code seems to trigger the build of documentation, which fails.

**Comment by madebr** [comment]
The only thing I can suggest to triage this problem is to compare the `config.log` of both builds.

**Comment by SpaceIm** [comment]
I've opened https://github.com/conan-io/conan-center-index/issues/5391 for specific issues on some Windows machines (mine & github action), but it can be addressed in another PR since CI of CCI seems to be happy.

**Comment by madebr** [comment]
It would be nice to have this tested in the test_package (to avoid regressions).
Will you do this? Or should I take an attempt tomorrow?

**Review by prince-chrismc — DISMISSED** [review]

**Comment by SpaceIm** [comment]
> It would be nice to have this tested in the test_package (to avoid regressions).
> Will you do this? Or should I take an attempt tomorrow?

You mean a test building a static & a shared lib, the static lib linked into shared lib? If you have time, please do 😃

**Comment by madebr** [comment]
> > It would be nice to have this tested in the test_package (to avoid regressions).
> > Will you do this? Or should I take an attempt tomorrow?
> 
> You mean a test building a static & a shared lib, the static lib linked into shared lib? If you have time, please do smiley

See https://github.com/SpaceIm/conan-center-index/pull/9

**Comment by SpaceIm** [comment]
Seems to work on Macos

**Comment by SpaceIm** [comment]
off-topic: why is there an extension added to this PATH https://github.com/conan-io/conan-center-index/blob/a10f21fe90cb2406f71773d01d81e8a699d41232/recipes/libtool/all/conanfile.py#L199-L201
And why this environement variable is added in libtool, but not in pkgconf recipe?

**Comment by madebr** [comment]
The extension is added to circumvent some hook.
The hook complained that no executable files were present.
See https://github.com/conan-io/conan-center-index/pull/657#issuecomment-574749395 and below.

I think `ACLOCAL_PATH` can be used instead of `AUTOMAKE_CONAN_INCLUDES`, but I'm not sure.
If it could, the patches of `automake` can be dropped.

**Comment by SpaceIm** [comment]
I understand for executables, but libtool_aclocal is a folder, not an executable.

**Comment by madebr** [comment]
You're correct.
Seehttps://www.gnu.org/software/automake/manual/html_node/Macro-Search-Path.html

`ACLOCAL_PATH` is supposed to be a search path.

**Comment by madebr** [comment]
See https://github.com/SpaceIm/conan-center-index/pull/10

**Review by madebr — APPROVED** [review]
Super addition!
Now we can (maybe) fix recipes that disallow shared Windows builds because of libtool.

**Review by prince-chrismc — DISMISSED** [review]

**Review by madebr — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
