### PR TITLE
log4cxx/0.12.1 patch re-connect for socket appender.

### PR DESCRIPTION
**Pull request by bowb**
Specify library name and version:  **log4cxx/0.12.1**

The socket appender will throw a mutex exception and not start the monitor thread back up. This is a patch to fix those issues until an official release with fixes is made.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
is the patch submitted upstream ? was it accepted ? when is the version with the fix expected to be released ?

**Comment by bowb** [comment]
> is the patch submitted upstream ? was it accepted ? when is the version with the fix expected to be released ?

An issue has been submitted to log4cxx see https://issues.apache.org/jira/projects/LOGCXX/issues/LOGCXX-537. It looks like the fix has changed since last time I looked at it.  I don't know when a new version of log4cxx will come out.

**Comment by ericLemanissier** [comment]
it seems to be too soon to include this patch, if the fix is not yet settled.

**Comment by bowb** [comment]
> it seems to be too soon to include this patch, if the fix is not yet settled.

I'll convert the pr to draft and keep an eye on the accepted fix.

**Comment by uilianries** [comment]
We usually prefer to wait for a next release. If it will take a long time, you could create a virtual version based on a new commit with those changes. The version 0.12.1 doesn't have that patch, so we can't create a misbehavior on that library.

**Pull request closed without merging**
