### PR TITLE
[boost] allow to specify mutliple extra b2 flags

### PR DESCRIPTION
**Pull request by SSE4**
closes: #1415 

Specify library name and version:  **boost/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
You can also use `shlex.split`

**Comment by SSE4** [comment]
@madebr I am reading the doc on `shlex.split` and couldn't understand what exactly does it do:
```
Split the string s using shell-like syntax
```
first off, what kind of shell - PowerShell, cmd.exe, bash, zsh, czsh, dash or something else?
second, I am not sure what does it refer to - does it refer to built-in [split](https://ss64.com/ps/split.html) command? in such case I don't see any significant difference from the python's split method...
some examples could help I guess

**Comment by madebr** [comment]
@SSE4 
What it does is split a string as you expect it to when passing arguments to programs.

Simple example:
```python
>>> s = "echo \"hello world\""
# str.split splits on whitespace
>>> s.split()
['echo', '"hello', 'world"']
# shlex.split splits with knowledge of how shells work (which is what we want here)
>>> import shlex
>>> shlex.split(s)
['echo', 'hello world']
```

In this particular case:
```python
>>> shlex.split("define=BOOST_BEAST_USE_STD_STRING_VIEW define=BOOST_ASIO_DISABLE_CONCEPTS")
['define=BOOST_BEAST_USE_STD_STRING_VIEW', 'define=BOOST_ASIO_DISABLE_CONCEPTS']
````

**Comment by SSE4** [comment]
@danimtb need help here!

**Review by danimtb — APPROVED** [review]

**Review by czoido — APPROVED** [review]

**Pull request merged**
