### PR TITLE
sqlcipher: Add 4.5.6

### PR DESCRIPTION
**Pull request by Alex-PLACET**
Specify library name and version:  **sqlcipher/4.5.6**

Add new version and add SQLITE_ENABLE_COLUMN_METADATA option feature flag. The add of this flag made the use of sqlcipher usable by sqlitecpp.

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Alex-PLACET** [comment]
> > Add new version and add SQLITE_ENABLE_COLUMN_METADATA option feature flag. The add of this flag made the use of sqlcipher usable by sqlitecpp.
> 
> @Alex-PLACET what error do you have when not using that define? Is `tools.build:cflags` not enough for your case?
> 
> https://docs.conan.io/2/reference/config_files/global_conf.html

I got this error when trying to compile SqliteCpp with sqlcipher as sqlite lib:
```
SQLiteCpp.lib(Statement.obj) : error LNK2019: unresolved external symbol sqlite3_column_origin_name referenced in fun
ction "public: char const * __cdecl SQLite::Statement::getColumnOriginName(int)const " (?getColumnOriginName@Statemen 
t@SQLite@@QEBAPEBDH@Z) [\conan-center-index\recipes\sqlitecpp\all\test_package\build\msvc 
-193-x86_64-20-release\test_package.vcxproj]
SQLiteCpp.lib(Column.obj) : error LNK2001: unresolved external symbol sqlite3_column_origin_name [\conan-center-index\recipes\sqlitecpp\all\test_package\build\msvc-193-x86_64-20-release\test_package.vcxproj 
]
```
This is a build with a SqliteCPP recipe that I modified to be able to use encryption which will come in another PR.
Do you prefer that I activate it through an option ?

**Comment by uilianries** [comment]
> This is a build with a SqliteCPP recipe that I modified to be able to use encryption which will come in another PR.
Do you prefer that I activate it through an option ?

@Alex-PLACET Yes, please. I'm not sure how this could affect the package behavior, like breaking users.

**Comment by Alex-PLACET** [comment]
@uilianries Ok done

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
@Alex-PLACET Thank you for your contribution, we just need another review now: https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md#getting-your-pull-request-reviewed

**Pull request merged**
