### PR TITLE
concurrencpp: Update to 0.1.5

### PR DESCRIPTION
**Pull request by chausner**
Specify library name and version:  **concurrencpp/0.1.5**

This updates the recipe for the latest version of the library.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Comment by ohanar** [comment]
@chausner FYI, it seems that 0.1.5 no longer requires the use of libc++ with clang.

**Comment by chausner** [comment]
> @chausner FYI, it seems that 0.1.5 no longer requires the use of libc++ with clang.

Are you sure? The upstream build scripts still have `-stdlib=libc++` hardcoded for Clang: https://github.com/David-Haim/concurrencpp/blob/master/cmake/coroutineOptions.cmake#L8

**Comment by ohanar** [comment]
> Are you sure? The upstream build scripts still have `-stdlib=libc++` hardcoded for Clang: https://github.com/David-Haim/concurrencpp/blob/master/cmake/coroutineOptions.cmake#L8

I'm quite sure that the entire test suite passed for me on Ubuntu 22.04 with clang 15 and without those flags. E.g.
```bash
$ ldd ./timer_tests
        linux-vdso.so.1 (0x00007ffe255b6000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb57603e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb575f57000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb575f37000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb575d0f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb57629c000)
```

**Comment by chausner** [comment]
> I'm quite sure that the entire test suite passed for me on Ubuntu 22.04 with clang 15 and without those flags. E.g.

Interesting. I suggest you open an issue about this in the upstream repo, then we can discuss there further. I am also surprised you got it running with clang 15 given that the library has [some issues](https://github.com/David-Haim/concurrencpp/pull/74) with clang 14 the last time I checked.

**Review by jgsogo — APPROVED** [review]

**Pull request merged**
