### PR TITLE
aaf: Add martindelille to maintainers

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **aaf**

Hi,

The idea of this PR is to add a new array field to a recipe to implement an automatic ping of the maintainers of this recipe.
I don't have any competences in writing bot for now (except one throwing random gif on the mattermost of my company), but I would be happy to have some help !!!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
@qchateau @ericLemanissier What do you think about it ?

**Comment by MartinDelille** [comment]
@uilianries I spoke to you about having a more configurable way to get notification on CCI. This would help contributors like me that want to be able to follow only their dependencies for example. I unfortunately don't have more time to do more review and it would avoid me to spent 5 minutes each morning to unsubscribe to other recipe PR.

**Comment by SpaceIm** [comment]
Well basically it's the `author` field and conan-center doesn't allow to define it. Not sure it's a good idea to define a custom fiedl not documented in https://docs.conan.io/en/latest/reference/conanfile/attributes.html#attributes

**Comment by MartinDelille** [comment]
@SpaceIm Can author contains multiple contributors?

**Review by uilianries — CHANGES_REQUESTED** [review]
The author attribute is reserved only to conan-center-index, because all recipes are owned by the community, not to a specific author/champion/specialist.

However, this feature was discussed with Conan team and indeed is useful as people can not digest all CCI emails. As it is more related to Conan Center Index and not Conan client itself, we can not add new attribute in the recipe. Instead, we will need to list those subscribers in config.yml and process with the CI service, like pinging on Github PR in a comment.

As it's not implemented now and will take some time, you can use https://app.github-file-watcher.com/ or similar service to watch only what you want, meanwhile.

**Comment by MartinDelille** [comment]
@uilianries I pushed a proposition although I'm totally open with the naming. Maintainers could be a little bit restrictive so I switch to watchers.

**Pull request closed without merging**
