### PR TITLE
add libkmod/system

### PR DESCRIPTION
**Pull request by daravi**
Specify library name and version:  **libkmod/system**

I followed libudev/system as a reference to create this recipe. It is needed for https://github.com/conan-io/conan-center-index/pull/8555.

---

- [✓] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [✓] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [✓] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [✓] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by eirikb** [comment]
Hi. I never got around to publishing this, but I think this conanfile for kmod might work: https://gist.github.com/eirikb/edd00c32f0a1d3481e27d5f1b4ce568e#file-libkmod_conanfile-py .
I had to clean it up according to the recommendations I got for i2c, but it kind of stopped there.

**Comment by daravi** [comment]
@eirikb Thank you.

Reviewers please let me know if it is necessary to make this a non-system package as I would prefer to avoid doing that.

**Comment by eirikb** [comment]
I'm not very familiar with the library to be honest, but in the end I would like to build ddcutil in cleanish environments, such as docker conanio/gcc

**Comment by uilianries** [comment]
Hi! Thank you for your contribution!

I'm able to build kmod library from sources, I would like to know did you prefer as system package?

How to build:

https://www.linuxfromscratch.org/lfs/view/development/chapter08/kmod.html

**Comment by SSE4** [comment]
> https://www.linuxfromscratch.org/lfs/view/development/chapter08/kmod.html

let's add the actual library, then. I can take a look.

**Review by SSE4 — CHANGES_REQUESTED** [review]
see #9488

**Pull request closed without merging**
