### PR TITLE
add imgui/1.79

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **imgui/1.79**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — APPROVED** [review]
Should `imgui` set `self.cpp_info.srcdirs`?

See https://docs.conan.io/en/latest/reference/conanfile/methods.html#cpp-info

**Comment by SpaceIm** [comment]
Yes maybe adding `os.path.join(self.package_folder, "res", "bindings")`.

**Review by uilianries — APPROVED** [review]

**Comment by madebr** [comment]
@SpaceIm 
> Yes maybe adding `os.path.join(self.package_folder, "res", "bindings")`.

I think it should be:
```python
self.cpp_info.srcdirs = [os.path.join("src", "bindings")]
```

**Comment by SpaceIm** [comment]
So moving source files in a src folder instead of res folder?

**Comment by madebr** [comment]
You can keep the filesystem names.
Just add them to `scrdirs` in `package_info`.
That's no breaking change, I think.

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Pull request merged**
