### PR TITLE
Libgpiod update source url

### PR DESCRIPTION
**Pull request by ashley-b**
Specify library name and version:  **libgpiod**

- Source URLs are broken. This PR updates URLs to point to authors recommend location 
https://github.com/brgl/libgpiod/issues/71

- Also added new version 2.1.1

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — COMMENTED** [review]
@ashley-b Thank you for checking with the upstream first! 👏 

As a mirror, it should have the very same checksum, so we could use as a list in conandata.yml. I would ask to investigate a bit more to understand why they don't match. 

Plus, I checked locally and the original url is working. It could be a temporary error, could you please check it again.

**Comment by ashley-b** [comment]
>
> As a mirror, it should have the very same checksum, so we could use as a list in conandata.yml. I would ask to investigate a bit more to understand why they don't match. 

From the authors comments 
"
You'll be better off downloading tarballs from https://mirrors.edge.kernel.org/pub/software/libs/libgpiod/ too - they're signed with my GPG key and generated using make dist as opposed to just the repo snapshot.
"
So make dist has created some changes 

I have done a diff and can see there are generated Makefile.in in the new link

> 
> Plus, I checked locally and the original url is working. It could be a temporary error, could you please check it again. 

I've check it today and the URL is still broken for me and check with some one and they have the same issue

**Comment by uilianries** [comment]
@ashley-b You informed to the author the mirror is down for you too, but it's working. Not only the mirror, but also the snapshot:

- https://www.isitdownrightnow.com/mirrors.edge.kernel.org.html
- https://www.isitdownrightnow.com/git.kernel.org.html

I would suggest checking your network first. What exactly command and output do you have when trying to download? I guess you are having some limitation in your organization only.

**Comment by ashley-b** [comment]
I've tested the snapshot today, and it seems to be back. It's a strange fault.
I did find someone else with the same issue https://github.com/microsoft/vcpkg/issues/37948

**Comment by ashley-b** [comment]
The source URL still seems to be working. I will close this PR

**Pull request closed without merging**
