### PR TITLE
- [libdeflate] fix clang-cl

### PR DESCRIPTION
**Pull request by SSE4**
closes: #9809
Specify library name and version:  **libdeflate/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SpaceIm — APPROVED** [review]
I don't know whether it's robust, but I guess it's better. Does clang on Windows always link to msvc runtime? Or could it use libc++ & libc of MinGW?

**Comment by SSE4** [comment]
> I don't know whether it's robust, but I guess it's better. Does clang on Windows always link to msvc runtime? Or could it use libstdc++ & libc of MinGW?

clang from MSYS doesn't know these things:
```
$ clang++ -x c++ -stdlib=libc++ 1.c
x86_64-pc-msys-g++: error: unrecognized command-line option ‘-stdlib=libc++’
clang++: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
```
```
$ clang++ -x c++ -stdlib=libstdc++ 1.c
x86_64-pc-msys-g++: error: unrecognized command-line option ‘-stdlib=libstdc++’
clang++: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
```

one from MS also doesn't like them:
```
clang: warning: argument unused during compilation: '-stdlib=libstdc++' [-Wunused-command-line-argument]    
```
```
clang: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]
```
it doesn't seem possible to use them

**Comment by AndreyMlashkin** [comment]
just for info: this issue was fixed in the most recent version
https://github.com/ebiggers/libdeflate/commit/478abccb812c0baabfc12528bf2272e3e081df96

We can add v1.10

**Review by AndreyMlashkin — APPROVED** [review]

**Comment by AndreyMlashkin** [comment]
@jgsogo
retrigger the build?

**Review by uilianries — APPROVED** [review]

**Comment by SSE4** [comment]
> @jgsogo retrigger the build?

I was able to re-trigger just CLA visiting URL `https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=<pr-number>`

**Pull request merged**
