### PR TITLE
bazel-6.1.0

### PR DESCRIPTION
**Pull request by Daparrag**
Adding support for bazel vesion  6.1.0
Signed-off-by: guzman <diego-alejandro.parra-guzman@tttech.com>

Specify library name and version:  **bazel/6.1.0**

Reasons to upgrade:
Current version of bazel is quite old  4.0.0. 
Bazel is highly used for building TensorFlow   

---
- [X ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Please sign the CLA :)

**Comment by memsharded** [comment]
Hi @Daparrag 

It would be good to move this recipe forward, could you please check the CLA that needs to be signed to be able to accept the contribution? Otherwise the PR will go stale and will be automatically closed.

**Review by jcar87 — COMMENTED** [review]
Hi @Daparrag - thanks so much for your contribution.

I've pushed some minimal fixes to get this to pass properly on both Conan 1.x and Conan 2.0.

From what I can see, however, the recipes for both versions of Bazel (4.x and 6.x) are almost identical, with minimal differences in the logic to download and the conandata.yml file. It would be greatly appreciated if you found the way to merge this into a single recipe, I believe we will benefit from this and be able to push newer versions quicker.

Thanks a lot!

**Comment by valgur** [comment]
Can probably be closed now that #17698 has been merged.

**Comment by jcar87** [comment]
Hi @Daparrag  - indeed as @valgur  kindly points out, https://github.com/conan-io/conan-center-index/pull/17698 has been merged which makes the bazel recipe compatible with Conan 2.0, as well as adding version 6.2.0. I'll proceed to close this PR since I believe the other PR already satisfied the requirements - but if there's anything missing please let me know and we'll address it.

Thanks for your contribution!

**Pull request closed without merging**
