### PR TITLE
opencv/4.x: fix disabling dnn

### PR DESCRIPTION
**Pull request by mologie**
Specify library name and version:  **opencv/4.x**

Cases existed where dnn_cuda would be deleted twice, which would crash the recipe in configure().

For example, when I build for macOS arm64 with `-o dnn=False`, I would get the following error:

```
ERROR: opencv/4.5.5: Error in configure() method, line 164
	del self.options.dnn_cuda
	ConanException: option 'dnn_cuda' doesn't exist
Possible options are ['shared', 'contrib', 'parallel', 'with_ipp', 'with_ade', 'with_jpeg', 'with_png', 'with_tiff', 'with_jpeg2000', 'with_openexr', 'with_eigen', 'with_webp', 'with_quirc', 'with_cuda', 'with_ffmpeg', 'with_imgcodec_hdr', 'with_imgcodec_pfm', 'with_imgcodec_pxm', 'with_imgcodec_sunraster', 'neon', 'dnn', 'cuda_arch_bin', 'cpu_baseline', 'cpu_dispatch', 'nonfree']
```

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by mologie** [comment]
The CI pipeline fails due to conflicting libwebp versions in opencv and ffmpeg. Failure is unrelated to this MR:

```
Graph error
    Version conflict: ffmpeg/4.4->libwebp/1.3.0, None->libwebp/1.3.1.
ERROR: Version conflict: ffmpeg/4.4->libwebp/1.3.0, None->libwebp/1.3.1.
```

**Review by uilianries — APPROVED** [review]
LGTM

You could replace `rm` by `self.options.rm_safe("with_cuda")` that's not affected by double removing.

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
@conan-center-bot you're drunk :beer:

**Comment by mologie** [comment]
Seems like this is no longer needed: #15193 landed in master and completely replaces how OpenCV modules are selected. The bug where a dnn option was deleted twice is gone too.

Closing, hopefully that stops the bot spam too...

**Pull request closed without merging**
