### PR TITLE
Add approvaltests.cpp 10.10.0

### PR DESCRIPTION
**Pull request by isidore**
Specify library name and version:  **approvaltests.cpp/10.10.0**

We are the authors of the library releasing a new version

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Hello @isidore ! Thank your for your first contribution. Please, ask for Early-Access-Program inclusion on issue #4. The CI bot only builds PRs which are from approved users.

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by claremacrae** [comment]
> Hello @isidore ! Thank your for your first contribution. Please, ask for Early-Access-Program inclusion on issue #4. The CI bot only builds PRs which are from approved users.

This is now done….

**Comment by claremacrae** [comment]
Could someone please investigate why the pr-merge bot above cannot be built?

Also, re the conflicting PR #6903 I see that that has been closed, with no comment… It differed from this in that it also updated the version of Catch2 dependency…

**Comment by uilianries** [comment]
@claremacrae The issue #4 which @isidore asked permission, is updated every Monday. However, @isidore only asked for access yesterday, after the bot enabling new people. We would need to include manually, or wait until next week (not good). Also, this PR requires 3 approvals, so far we have 2.

**Comment by claremacrae** [comment]
Thanks @uilianries - I see, we were unlucky with our timing then... No problem.

Did you have any thoughts about PR #6903 - I'm just curious as to why you created it, and updated its Catch2 dependency...

**Comment by uilianries** [comment]
@claremacrae It was a duplication. I saw on Twitter about new Approval Test release, but I didn't this PR here. This PR is older than mine, and I prefer giving priority to community PRs.

**Comment by uilianries** [comment]
@SSE4 could please review this one? It's waiting for 2 weeks

**Review by ericLemanissier — APPROVED** [review]

**Comment by uilianries** [comment]
@ericLemanissier Thank you!

**Pull request merged**
