### PR TITLE
add diligent-glslang

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **diligent-glslang/cci.20211008**

relates to https://github.com/conan-io/conan-center-index/pull/7804
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Show the diff with upstream master please.

**Comment by AndreyMlashkin** [comment]
There are no additional changes to the original repository.

What do you propose? this recipe still should depend on diligentgraphics-spirv-tools/cci.20211008, there are some local changes there

**Comment by SpaceIm** [comment]
As I said in the PR submitting spirv-tools fork, I don't think it was required, changes in spirv-tools are minimal.

**Comment by AndreyMlashkin** [comment]
@SpaceIm  For now, I can only use official spirv-cross and vulkan-headers/1.2.195 and spirv-cross/cci.20210930

I have opened PRs for them:
https://github.com/conan-io/conan-center-index/pull/8032
https://github.com/conan-io/conan-center-index/pull/8049

For other libs, I need a forked recipe

**Comment by AndreyMlashkin** [comment]
@SpaceIm, how do you want to apply that minimal changes in spirv-tools?

**Comment by AndreyMlashkin** [comment]
@SpaceIm , I have tried to use diligent-core just with the latest glslang and spirv-tools and it worked. Thank you for being picky.

I will close this MR and remove diligent* recipes for  spirv-headers and spirv-tools.

I still need a specific version for vulkan-headers - there are many local changes and also volk (it does not have local changes, but there is no way to let it pointing to diligent- vulkan-headers)

**Pull request closed without merging**
