### PR TITLE
libmp3lame: fix msvc & mingw build regressions

### PR DESCRIPTION
**Pull request by SpaceIm**
Regarding msvc, see https://github.com/conan-io/conan-center-index/pull/13791#discussion_r1008586781 & https://github.com/conan-io/conan/issues/12188

MinGW cross-build from linux to Windows was likely broken due to another regression coming from https://github.com/conan-io/conan-center-index/pull/13791 where target os was tested instead of build machien os.

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
```
--=* .\output\libmp3lame-static.lib ready *=--

LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'
libmp3lame/3.100: 

Microsoft (R) Program Maintenance Utility Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.EXE"' : return code '0x450'
Stop.
libmp3lame/3.100: ERROR: Package '970e773c5651dc2560f86200a4ea56c23f568ff9' build failed
libmp3lame/3.100: WARN: Build folder C:\J\w\prod\BuildSingleReference@2\.conan\data\libmp3lame\3.100\_\_\build\970e773c5651dc2560f86200a4ea56c23f568ff9\build-release
ERROR: libmp3lame/3.100: Error in build() method, line 150
	self._build_vs()
while calling '_build_vs', line 134
	self.run(command)
	ConanException: Error 2 while executing nmake -f Makefile.MSVC comp=msvc MSVCVER=Win64 asm=yes libmp3lame.dll
```

? All I can say is that I can't reproduce this error locally with the same profile (except that I have Visual Studio 2022 instead of Visual Studio 2017)

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Please do not force push 🙏 GitHub forces us to restart the review which is not fun!

**Comment by SpaceIm** [comment]
Yes sorry for that. Actually I've forced pushed on a commit done after your review, I've not changed previous commits.

**Comment by SpaceIm** [comment]
runtime looks good now, no more warnings in test_package for Visual Studio.

Debug MDd static:

```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/libmp3lame/all/test_package/CMakeLists.txt
  test_package.c
  test_package.vcxproj -> C:\J\w\prod\BuildSingleReference\conan-center-index\recipes\libmp3lame\all\test_package\build\Debug\test_package.exe
  Building Custom Rule C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/libmp3lame/all/test_package/CMakeLists.txt
```

Debug MTd static:

```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/libmp3lame/all/test_package/CMakeLists.txt
  test_package.c
  test_package.vcxproj -> C:\J\w\prod\BuildSingleReference\conan-center-index\recipes\libmp3lame\all\test_package\build\Debug\test_package.exe
  Building Custom Rule C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/libmp3lame/all/test_package/CMakeLists.txt
```

Release MD static:

```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/libmp3lame/all/test_package/CMakeLists.txt
  test_package.c
  test_package.vcxproj -> C:\J\w\prod\BuildSingleReference\conan-center-index\recipes\libmp3lame\all\test_package\build\Release\test_package.exe
  Building Custom Rule C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/libmp3lame/all/test_package/CMakeLists.txt
```

Release MT static:

```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/libmp3lame/all/test_package/CMakeLists.txt
  test_package.c
  test_package.vcxproj -> C:\J\w\prod\BuildSingleReference\conan-center-index\recipes\libmp3lame\all\test_package\build\Release\test_package.exe
  Building Custom Rule C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/libmp3lame/all/test_package/CMakeLists.txt
```

**Comment by prince-chrismc** [comment]
> Actually I've forced pushed on a commit done after your review, I've not changed previous commits.

Sadly the review reposition gets whipped out in most cases of a force push. it's the biggest limitation with
GitHub 

If the history is changed at all it reset 😞

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
thanks, it's important to fix this one before contamination of ffmpeg shared pre build binary.

**Comment by AndreyMlashkin** [comment]
> MinGW cross-build from linux to Windows was likely broken due to another regression coming from #13791 where target os was tested instead of build machien os.

I am curious now, what are the build and host profiles for such cross-compilation? I haven't found them in the related tickets

**Pull request merged**
