### PR TITLE
etl: modernize & fix CMake imported target

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/8074

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jputcu** [comment]
Watch out, the path change in the example doesn't work on msys2.

**Comment by SpaceIm** [comment]
It's the same path we are using in all test package of conan-center recipes, so it's quite surprising.

**Review by jgsogo — APPROVED** [review]
yes, the path should work... @jputcu, can you provide command and log output?

**Comment by jputcu** [comment]
I'll try tomorrow

**Review by uilianries — APPROVED** [review]

**Comment by jputcu** [comment]
On Msys2 I get the following error:
~~~~
[2/2] Linking CXX executable bin\test_package.exe
etl/20.24.1 (test package): Running test()
'bin' is not recognized as an internal or external command,
operable program or batch file.
ERROR: etl/20.24.1 (test package): Error in test() method, line 17
        self.run(bin_path, run_environment=True)
        ConanException: Error 1 while executing bin/test_package
~~~~~

**Comment by SpaceIm** [comment]
Looks like a conan issue eventually rather than test package issue. Does it work for any other recipes in CCI?

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
