### PR TITLE
dataframe: add version 2.2.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **dataframe/2.2.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Seems like apple-clang 13 might not be enough for the new version?

**Comment by toge** [comment]
@RubenRBS 
You give me a good advise!
It works fine on apple-clang 15.
Thanks!

**Comment by RubenRBS** [comment]
Nice! I'm going to look into updating CCI to start building with newer apple-clang versions

**Review by RubenRBS — APPROVED** [review]
🫶

**Pull request merged**
