### PR TITLE
vulkan-headers: add all sdk versions up to 1.2.141.0

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **vulkan-headers/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
This seems excessive. Are you actually using all of those older versions?

**Comment by SSE4** [comment]
@Croydon +1, I guess it should be enough to just have latest 1.1.x and latest 1.2.x. are these minors ABI incompatible or something?

**Comment by SpaceIm** [comment]
AFAIK, there is no backward compatibility, even between patch versions of the same minor version. Is it really an issue to submit all those versions for a header-only library? It will be also easier to package vulkan validation layers because it sometimes hard to package the latest with available glslang and shaderc releases.
Last time I tried, I was only able to package 1.2.131.0, not 12.135.0 for example.

**Comment by uilianries** [comment]
I see packages ... Where? ... Everywhere!

**Comment by uilianries** [comment]
@SpaceIm The only problem is maintaining multiple versions, when few or only one is used. But in this case I see no big problem, it's header-only, so we can't complain about storage, and as you said, it's not backward compatible, thus, I see the value of multiple versions available.

**Pull request merged**
