### PR TITLE
magic_enum: add version 0.9.7

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **magic_enum/0.9.7**

#### Motivation
There are several minor improvements in 0.9.7.

`magic_enum.hpp` include header has been replaced. 
We have to include `magic_enum/magic_enum.hpp`.

#### Details
https://github.com/Neargye/magic_enum/releases/tag/v0.9.7
https://github.com/Neargye/magic_enum/compare/v0.9.6...v0.9.7

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by ErniGH — APPROVED** [review]
LGTM

**Review by jcar87 — CHANGES_REQUESTED** [review]
Marking this to give us some time to investigate the back and forth as to what the location of the public header should be.

**Review by jcar87 — APPROVED** [review]
Well, indeed it has changed again 

https://github.com/Neargye/magic_enum/pull/374#issuecomment-2411541373

Thanks @toge! And thanks for waiting until a few days have passed since the releases are out :)

**Comment by gsantner** [comment]
Hello,
wanted to ask if something went wrong with this package? Usually when PR is merged it's basically instant installable via conanfile. But this time only can install 0.9.6 and not found error on 0.9.7. However 0.9.7 is also listed at conan center as latest version. Not sure whats wrong?

**Comment by jcar87** [comment]
HI @gsantner  - please be aware that since 4-nov-2024 we are uploading to a new Conan remote.
* If you are using Conan 1.x - the repository  at `https://center.conan.io` is no longer updated and is effectively in a frozen state
* If you are using Conan 1.x - please update the remote to point to `https://center2.conan.io` - you can do this with
```
conan remote update conancenter --url https://center2.conan.io
```

More details:
https://github.com/conan-io/conan-center-index/discussions/25461

**Comment by gsantner** [comment]
Oh, thank you!

**Comment by gsantner** [comment]
Oh, thank you for the reply. It is not really visible that there was this server change

**Comment by jcar87** [comment]
> Oh, thank you for the reply! It is not really visible that there was this server change

Oh! Thanks for the feedback, we really tried to communicate it via all the channels possible.
On the Conan Center package browser at https://conan.io/center/recipes/magic_enum?version=0.9.7 there's also a banner at the top - perhaps we need to make it more noticeable

**Pull request merged**
