### PR TITLE
[zstd] upgrade to 1.4.5


### PR DESCRIPTION
**Pull request by SSE4**
[zstd] upgrade to 1.4.5
NOTE: this is automated commit created by conan-bump32!
command line: conan-bump32.py -p zstd -v 1.4.5

### CODE REVIEW

**Comment by ericLemanissier** [comment]
what is this marvelous conan-bump32 tool ?

**Comment by SSE4** [comment]
@ericLemanissier I am just testing it, it's not yet available

**Comment by SSE4** [comment]
didn't see there is already https://github.com/conan-io/conan-center-index/pull/1707
anyway, this was just a test

**Comment by uilianries** [comment]
Oh no! @Croydon washed your brain! Now you are creating bots too! :joy_cat:

**Comment by uilianries** [comment]
@SSE4 You could use Github API to apply the reviewers too. 

https://developer.github.com/v3/pulls/review_requests/

**Comment by SSE4** [comment]
@uilianries I know, that's on the list, but I want to get it work reliably first

**Comment by Croydon** [comment]
> Oh no! @Croydon washed your brain!

4311h3

**Pull request closed without merging**
