### PR TITLE
glew: add option for glu

### PR DESCRIPTION
**Pull request by xyz1001**
Specify library name and version:  **glew/2.2.0**

glew with mesa-glu cause crash on my device. `glu/system` works well. 
Environment:
OS: Kubuntu 22.04
Hardware: Lenovo ThinkBook 14p G2 ACH with AMD 5800H

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by valgur** [comment]
@jwillikers

**Comment by jwillikers** [comment]
@xyz1001 Thanks for submitting the PR regarding this issue! I'm more curious to understand exactly why it would crash at runtime. Are you running your application with the `conanrun.sh` shell script? That's important as it will put the runtime-loaded `libGLU` from the standard Conan package in `LD_LIBRARY_PATH` path.

**Comment by xyz1001** [comment]
I am not running my application with `conanrun.sh`. I collect all so file from dependencies and copy them to the directory of executable file. And then I run my application with `LD_LIBRARY_PATH` set to the directory of executable file. 
image

It crash when call `glDrawArrays`. 
image

**Comment by jwillikers** [comment]
@xyz1001 Thanks! That helps me understand the situation. I'm certain GLU is the issue yet. What happens if you delete `libglvnd` from the `.so` files you've copied and try re-running?

**Comment by xyz1001** [comment]
@jwillikers It works well after I delete all so copy from `libglvnd`. It turn to load those so from system packages.

**Comment by jwillikers** [comment]
> @jwillikers It works well after I delete all so copy from `libglvnd`. It turn to load those so from system packages.

@xyz1001 Thanks for checking. I think making `opengl/system` an alternative for `libglvnd` in `mesa/glu` would solve your problem. I'm not sure the issue is related to the `libglvnd` Conan package or just the fact that a lot of the dependencies like `glew` depend on `opengl/system` still instead of the `libglvnd` Conan package. To figure out what's really going would require a bigger deep dive into running with some different environment variables to debug the `libglvnd` loading and the Mesa drivers. I don't think that's really necessary at this point though.

**Comment by xyz1001** [comment]
@jwillikers Yes, I am using the latest revision of the `libglvnd` recipe. The `conanfile.py` in my local conan cache is same as that in conan-center-index repo.

**Pull request merged**
