### PR TITLE
Fix SFML runtime error on macOS

### PR DESCRIPTION
**Pull request by ssrobins**
Specify library name and version:  **sfml/2.5.1+**

If you build SFML statically on macOS, it hits an error at runtime when using `sfml-window`.

This was fixed in SFML 2.5.1 with this [CMake code](https://github.com/SFML/SFML/blob/af5edaab912c6f5254052a4976221d89f0950064/src/SFML/Window/CMakeLists.txt#L297):
```
if ((NOT BUILD_SHARED_LIBS) AND SFML_OS_MACOSX)
    target_link_libraries(sfml-window PRIVATE -ObjC)
endif()
```

This work simply ports that change to the Conan package. In addition to running `conan create`, I used it in a macOS app to verify that the runtime error is gone and the app runs normally.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jcar87** [comment]
Hi @ssrobins  - thank you for your contribution. For completeness and traceability, would you be able to paste or provide more details on the exact error that occurs if this patch is not applied?

**Comment by ssrobins** [comment]
> Hi @ssrobins - thank you for your contribution. For completeness and traceability, would you be able to paste or provide more details on the exact error that occurs if this patch is not applied?

Sure, here are the repro steps:
 
1. Replace the code in `test_package/test_package.cpp` with this:
   ```
   #include <SFML/System.hpp>
   #include <SFML/Window.hpp>
   #include <SFML/Graphics.hpp>

   int main()
   {
       sf::RenderWindow window(sf::VideoMode(720, 480), "");
       return 0;
   }
   ```
1. Run `conan create . --version 2.5.1` on `master` branch. You get this error:

```
2023-07-06 20:49:56.858 test_package[10383:125695] -[SFOpenGLView enableKeyRepeat]: unrecognized selector sent to instance 0x7fc79695fcd0
2023-07-06 20:49:56.858 test_package[10383:125695] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SFOpenGLView enableKeyRepeat]: unrecognized selector sent to instance 0x7fc79695fcd0'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007ff81f89c773 __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff81f5fcbc3 objc_exception_throw + 48
        2   CoreFoundation                      0x00007ff81f92135b -[NSObject(NSObject) __retain_OA] + 0
        3   CoreFoundation                      0x00007ff81f803535 ___forwarding___ + 1356
        4   CoreFoundation                      0x00007ff81f802f58 _CF_forwarding_prep_0 + 120
        5   test_package                        0x00000001024bd6b6 -[SFOpenGLView initWithFrame:fullscreen:] + 118
        6   test_package                        0x00000001024beb54 -[SFWindowController setupWindowWithMode:andStyle:] + 372
        7   test_package                        0x00000001024be504 -[SFWindowController initWithMode:andStyle:] + 356
        8   test_package                        0x00000001024c0afe _ZN2sf4priv15WindowImplCocoaC2ENS_9VideoModeERKNS_6StringEmRKNS_15ContextSettingsE + 222
        9   test_package                        0x00000001024b4de3 _ZN2sf4priv10WindowImpl6createENS_9VideoModeERKNS_6StringEjRKNS_15ContextSettingsE + 67
        10  test_package                        0x00000001024b4307 _ZN2sf6Window6createENS_9VideoModeERKNS_6StringEjRKNS_15ContextSettingsE + 471
        11  test_package                        0x00000001024a1923 _ZN2sf12RenderWindowC1ENS_9VideoModeERKNS_6StringEjRKNS_15ContextSettingsE + 99
        12  test_package                        0x0000000102462bbb main + 123
        13  dyld                                0x000000010e84652e start + 462
)
libc++abi: terminating with uncaught exception of type NSException
/bin/sh: line 1: 10383 Abort trap: 6           ./test_package
```

If you repeat those steps with the code from this branch, it runs fine. Unfortunately, I can't run `sf::RenderWindow window(sf::VideoMode(720, 480), "");` in GitHub CI because of this error:
```
Failed to open X11 display; make sure the DISPLAY environment variable is set correctly
Aborted
```

**Review by jcar87 — APPROVED** [review]
Hi @ssrobins  - thank you so much for your contribution and for the details steps to reproduce this issue.

I have tested this locally before and after the patch and have been able to replicate the issue and verify that it is resolved. Thank you so much for taking the time to fix this and detail it.

**Review by RubenRBS — APPROVED** [review]

**Comment by ssrobins** [comment]
> Hi @ssrobins - thank you so much for your contribution and for the details steps to reproduce this issue.
> 
> I have tested this locally before and after the patch and have been able to replicate the issue and verify that it is resolved. Thank you so much for taking the time to fix this and detail it.

Happy to help, the repo is a joy to work in and the docs are top-notch!

Curious how long it takes for updates to reach Conan Center? I noticed the SFML 2.6.0 upgrade was merged two weeks ago and I don't see that update either. I recall a previous update I made to a different library took just a couple days. Is there a way to check progress?

**Comment by ChrisThrasher** [comment]
SFML maintainer here. This was fixed in the 2.6.0 release that shipped about a month ago.

**Comment by jcar87** [comment]
Hi @ChrisThrasher  - thanks for letting us know!

**Pull request merged**
