### PR TITLE
aws-c-cal/0.5.11

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **aws-c-cal/0.5.11**

ref https://github.com/conan-io/conan-center-index/pull/6346

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
The logs contain:
```
-- Using automatic libcrypto: /usr/lib/x86_64-linux-gnu/libcrypto.a
```
So it uses the openssl library.
This message looks custom. It seems they use a custom cmake module to find openssl.
See https://github.com/awslabs/aws-c-cal/blob/main/cmake/modules/FindLibCrypto.cmake

**Comment by madebr** [comment]
Not unsurprisingly, their `FindLibCrypto.cmake` is a poor re-implementation of `FindOpenSSL.cmake`.
I would patch `FindLibCrypto.cmake` to call `find_package(OpenSSL REQUIRED)`, and create a `crypto` interface target that has `OpenSSL::Crypto` in its `INTERFACE_LINK_LIBRARIES` property.

**Comment by MartinDelille** [comment]
@madebr I'm struggling with implementing your advice because of my insufficient cmake knowledge. I'm wondering the patch should occurs here when enabling the `USE_OPENSSL` option: https://github.com/awslabs/aws-c-cal/blob/main/CMakeLists.txt#L86-L106

**Comment by madebr** [comment]
See https://github.com/MartinDelille/conan-center-index/pull/3

**Review by madebr — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
