### PR TITLE
onetbb: support versions of deprecated tbb recipe

### PR DESCRIPTION
**Pull request by SpaceIm**
As suggested in https://github.com/conan-io/conan-center-index/issues/8308, and implemented in https://github.com/conan-io/conan-center-index/pull/9162, this PR assumes that we agree to deprecate tbb recipe.

All versions which were supported in tbb recipe are backported to onetbb recipe.

closes https://github.com/conan-io/conan-center-index/issues/8308

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
/tmp/ccKvTYBp.s: Assembler messages:
/tmp/ccKvTYBp.s:8734: Error: no such instruction: `tpause %ecx'
/tmp/ccKvTYBp.s:9859: Error: no such instruction: `tpause %ecx'
make[2]: *** [src/tbb/CMakeFiles/tbb.dir/arena.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/tbb/CMakeFiles/tbb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
``` 

? I builds fine for me on Ubuntu with gcc11, same profile.

**Comment by SpaceIm** [comment]
@jgsojo What's wrong in this agent? Can't reproduce this error on Ubuntu with gcc11.

**Comment by SSE4** [comment]
> tpause

maybe `as` (assembler) is too old and it doesn't recognize [tpause](https://github.com/Mic92/x86_64-linux-cheatsheats/blob/master/pages/TPAUSE) instruction (which seems to be relatively new and part of Intel TSX-NI)? @uilianries could you re-check?

**Comment by jgsogo** [comment]
Hi. I'm far from being an expert in Kubernetes, but as it happened with some other library some month ago, it looks like not everything depends on the docker image, but also on the underlying machine running docker. Those Linux machines are not under our control, so probably this is something that we cannot change and, if it is relatively new instruction, probably it's still not available (I assume the vendor is continuously upgrading its machines, but cannot confirm this point)

**Comment by SSE4** [comment]
I don't think it's about actual CPU in k8s cluster supporting execution of TSX-NI and tpause instruction, it's about binutils (GNU assembler) doesn't know the opcode (binary representation) of tpause instruction and cannot produce binary.
on the other hand, it's normal that compilation may generate some instructions that build machine cannot execute, as long as they are behind cpuid dispatcher branch and not mandatory (like these, onetbb could provide several implementation of the function with and without tpause behind the dispatcher).
in Linux world, the compiler doesn't generate a binary, but produces assembler listing and then invokes the assembler.
we installed GCC 11, which definitely supports tpause, but it appears GCC 11 may have some requirements of binutils version, which are separately installed and separately versioned. might be something we have completely missed in our docker images, as that's not very typical use-case (99% of recipes don't care about TSX-NI).

**Comment by jgsogo** [comment]
Thanks a lot for that master class! 🤟

**Comment by SpaceIm** [comment]
ok, let's just add old versions and see if it works

**Review by SSE4 — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
@prince-chrismc @ericLemanissier @toge @madebr one last review please? So that we can start to update recipes depending on `tbb` to `onetbb` recipe.

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Sorry for being slow! new job == busy 😭 trying to make more time to review PRs I promise ❤️

**Pull request merged**
