### PR TITLE
libyuv: conan v2 support + package version 1768 instead of cci.20201106 + add 1841

### PR DESCRIPTION
**Pull request by SpaceIm**
It addresses this comment: https://github.com/conan-io/conan-center-index/pull/13007#discussion_r973937129

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — DISMISSED** [review]
LGTM

**Review by jgsogo — COMMENTED** [review]
Can you share (maybe comment in `conandata.yml`) where does these package-version come from? It would be useful when checking/adding new releases. 

Thanks!

**Review by jgsogo — APPROVED** [review]
Thanks!

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
