### PR TITLE
serf: Fix url for serf-1.3.9.tar.bz2 

### PR DESCRIPTION
**Pull request by puetzk**
Specify library name and version:  **serf/1.3.9**

Fix build failure of serf package (due to download linkrot) similar to apr (e.g. #15737)

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by puetzk** [comment]
> Note: Conan v2 builds are now mandatory

If that's the case, this should probably be rejected in favor of #18889. I was just trying to fix the obvious and non-invasive problem so the recipe worked at all (and so that #20655 could then work too), to start un-clogging these conflicts since the conanv2 changes there seemed to have wrong results on windows

**Comment by RubenRBS** [comment]
> If that's the case, this should probably be rejected in favor of https://github.com/conan-io/conan-center-index/pull/18889.

@puetzk for cases like this we can manually override the limitation, I'll check with @czoido how far away the merge of the linked PR is and decide from there if we should push this one or wait for the other, thanks a lot for your contribution nevertheless :)

**Comment by czoido** [comment]
> > If that's the case, this should probably be rejected in favor of #18889.
> 
> @puetzk for cases like this we can manually override the limitation, I'll check with @czoido how far away the merge of the linked PR is and decide from there if we should push this one or wait for the other, thanks a lot for your contribution nevertheless :)

https://github.com/conan-io/conan-center-index/pull/18889 already passed the ci and it should be merged soon if nothing strange arises

**Comment by czoido** [comment]
Closing this as https://github.com/conan-io/conan-center-index/pull/18889 has already been merged. Thanks a lot @puetzk for the contribution

**Pull request closed without merging**
