### PR TITLE
qt 5.15.3

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **qt/5.15.3**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
retry

**Comment by ericLemanissier** [comment]
What happens on CCI here ? I don't have a mac, but it passes on github actions: https://github.com/eirikb/proof-of-conan/runs/5429103682?check_suite_focus=true#step:8:7843

**Comment by SSE4** [comment]
tried locally on macOS, it works normally. I was able to extract the archive as with conan, as well as with command line `xz`.
CI uses `python 3.6.13` and `conan 1.44.1` right now, and I've tried exactly the same combo.
archives itself appears to be regular, nothing suspicious.
I'll add `CONAN_VERBOSE_TRACEBACK` to see what exactly happens on CI...
as archive is quite a big, maybe it's a memory issue.

**Comment by SSE4** [comment]
not much info: it happens on https://github.com/python/cpython/blob/v3.6.13/Lib/tarfile.py#L1578

**Comment by ericLemanissier** [comment]
could it be a path length issue ? CCI uses /Users/jenkins/w/BuildSingleReference@2/.conan/data/qt/5.15.3/_/_/source

**Comment by SSE4** [comment]
> could it be a path length issue ? CCI uses /Users/jenkins/w/BuildSingleReference@2/.conan/data/qt/5.15.3/_/_/source

I highly doubt, one macOS we never had these things in the past. and it fails before the `extractall` call.

**Comment by ericLemanissier** [comment]
mm, so 5.15.2 probably does not work either ?
according to https://github.com/pandas-dev/pandas/issues/27532#issuecomment-517259553 and https://github.com/pandas-dev/pandas/issues/27532#issuecomment-808137030 maybe C3I missed `brew install xz` when doing `pyenv install ...`

**Comment by SSE4** [comment]
> mm, so 5.15.2 probably does not work either ? according to [pandas-dev/pandas#27532 (comment)](https://github.com/pandas-dev/pandas/issues/27532#issuecomment-517259553) and [pandas-dev/pandas#27532 (comment)](https://github.com/pandas-dev/pandas/issues/27532#issuecomment-808137030) maybe C3I missed `brew install xz` when doing `pyenv install ...`

yes, it appears like our python installation on mac machines is broken, and doesn't include xz/lzma module.

**Comment by jgsogo** [comment]
We've reinstalled most of the macOS servers in the last few days, clearly, this was something not on our radar.

**Review by uilianries — APPROVED** [review]

**Review by AndreyMlashkin — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
oh, there are conflicts now 🤦 it means rebuild Qt one more time... @ericLemanissier

**Review by SSE4 — APPROVED** [review]

**Review by AndreyMlashkin — APPROVED** [review]

**Review by Croydon — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by hanusek** [comment]
I have a problem:
```
qt/5.15.3: Configuring sources in /root/.conan/data/qt/5.15.3/_/_/source
Downloading qt-everywhere-opensource-src-5.15.3.tar.xz completed [608578.83k]                              

ERROR: qt/5.15.3: Error in source() method, line 420
	tools.get(**self.conan_data["sources"][self.version],
	ReadError: file could not be opened successfully
```

**Comment by ericLemanissier** [comment]
please upgrade your python and retry

**Pull request merged**
