### PR TITLE
pdal: back to shared by default + bump dependencies + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

~I want to regenerate binaries, package ids are not coherent anymore.~

cross-build is broken for the moment:
- it's broken by design in pdal CMakeLists (due to https://github.com/PDAL/PDAL/blob/2.2.0/cmake/dimension.cmake), I'll see if can fix it.
- ~gdal packages (and flatbuffers packages, dependency of gdal) for Macos M1 are not available in conan-center~

closes https://github.com/conan-io/conan-center-index/issues/8104

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@jgsogo @uilianries @danimtb Could you generate macos M1 packages for `flatbuffers` & `gdal` please (in this order, since `gdal` depends on `flatbuffers`). They are missing in conan-center.
Otherwise I can open a PR, but it's overkill (and I don't want to open a PR for flatbuffers right now, because I know that I'll spend time to fix several issues).

**Comment by jgsogo** [comment]
Done for `flatbuffers`: https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/TapaholesList/248/summary.json

Now, let's go for `gdal`, it will be a bit harder 😓

**Comment by jgsogo** [comment]
`gdal` ready: https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/TapaholesList/249/summary.json

**Comment by SpaceIm** [comment]
Didn't have time to work on this. Soon.

**Comment by SpaceIm** [comment]
I'll work on it later.

**Review by prince-chrismc — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
