### PR TITLE
vulkan-headers: add version 1.3.224.1

### PR DESCRIPTION
**Pull request by KingKili**
Specify library name and version:  **vulkan-headers 1.3.224.1**
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
ok but vulkan-headers 1.3.224.0 & 1.3.224.1 are identical (exactly the same commit).

**Comment by KingKili** [comment]
Weird that they tagged a release. Do you still want this version in conan, or should I close the pulls? Sorry for any inconvenience.

**Comment by uilianries** [comment]
@KingKili It can be added yes, as people may look for that new version. Thank you!

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
> Weird that they tagged a release. Do you still want this version in conan, or should I close the pulls? Sorry for any inconvenience.

These tags are the one of lunarg sdk. When they fix at least one component of Vulkan SDK for a new release, they add a tag to all components (vulkan-headers, vulkan-loader, vulkan-validationlayers, spirv-headers, spirv-cross, spirv-tools, glslang).

**Pull request merged**
