### PR TITLE
add volk/1.2.198

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **volk/1.2.198**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
There is https://github.com/conan-io/conan-center-index/pull/8159 already, why not editing this one.

**Comment by AndreyMlashkin** [comment]
That are two separate versions. If one got approved, I will close another one.
For me it does not matter, if there is a trailing zero or not.

**Comment by SpaceIm** [comment]
It doesn't make sense, it's the same source url, you just have to fix the version in the other PR. No need to open another PR.

**Comment by AndreyMlashkin** [comment]
PR is not a limited resource ;)

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by ericLemanissier** [comment]
> PR is not a limited resource ;)

Review time and CI time definitely are limited

**Review by ericLemanissier — APPROVED** [review]

**Comment by prince-chrismc** [comment]
> Review time

We use to trend at ~120 PRs open we are not at ~155... it's a huge restriction!

**Pull request merged**
