### PR TITLE
taocpp-pegtl: add version 3.2.2

### PR DESCRIPTION
**Pull request by prince-chrismc**
Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot)
Find more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Nothing obvious stand out why the file system hear is missing C++ is set to 17 🤔 any suggestions?

**Comment by uilianries** [comment]
@prince-chrismc I'm trying to understand too. So far, I can't reproduce that error here, and I can run the same docker image (conanio/clang11-ubuntu16.04:1.43.3), it works fine here.

**Comment by prince-chrismc** [comment]
Ahh yes, the infamous clang11 wrong stdlib

I'll modernize the recipe too since it requires a change

**Review by SSE4 — APPROVED** [review]

**Comment by prince-chrismc** [comment]
newer versions have been added 👏

**Pull request closed without merging**
