### PR TITLE
glaze: add version 2.1.4

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **glaze/***

- glaze/2.1.4 uses `decltype(auto)` which is not supported by gcc < 11.3 due to gcc bug. [ref](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102229)

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — COMMENTED** [review]
Hi! Thanks a lot as always :)

It's weird that gcc does not seem to work here, as their actions seem to be testing for gcc 11 too, and they would have caught a failing build there https://github.com/stephenberry/glaze/compare/v2.1.3...v2.1.4#diff-2ceee9940e7b1f3b7b4cea77c164a4417544c1495fdda80678bcac0313fb1589L23, I won'der whats going on in there?

**Comment by toge** [comment]
@RubenRBS 
Thank you for your comment!
It seems to be gcc bug. [ref](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102229)
It has been fixed since gcc 11.3.

While cci's gcc11 is 11.1, glaze/2.1.4(uses `decltype(auto)`) met a compilation error.

I will try to relax compilation version check.

**Comment by RubenRBS** [comment]
> While cci's gcc11 is 11.1

Maybe I can do something about it, let me double check, but yeah, checking for 11.3 would be great

**Review by RubenRBS — APPROVED** [review]
Approving, will circle bak to this once we update to 11.3 if possible :)

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
