### PR TITLE
libxft: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/17818

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/conan/w/prod-v2/BuildSingleReference/p/t/libxfa520101bafe08/b/build-release':
configure: error: C compiler cannot create executables
See `config.log' for more details

libxft/2.3.4: ERROR: 
Package '24839a77c7fe0258fd2778813f88fa1914ece8ce' build failed
libxft/2.3.4: WARN: Build folder /home/conan/w/prod-v2/BuildSingleReference/p/t/libxfa520101bafe08/b/build-release
```

Works fine for me on Linux, I can't know what's wrong here without the content of config.log

**Review by jwillikers — APPROVED** [review]

**Comment by jasuramme** [comment]
@SpaceIm here you go, pal!
[config.log](https://github.com/conan-io/conan-center-index/files/11659576/config.log)

**Comment by jasuramme** [comment]
@SpaceIm 
I think it links across system xorg libraries, but takes libuuid from conan repo.
And Xorg libraries need libuuid1.0, but in conan we have 1.03

**Comment by ericLemanissier** [comment]
See https://github.com/conan-io/conan-center-index/pull/17664

**Comment by jasuramme** [comment]
> See #17664

@ericLemanissier should we wait until util-linux-libuuid is released and add it to the requirements after that? Is it correct?

**Comment by ericLemanissier** [comment]
If we have no reason to think that libxft uses libuuid directly, then we should not add it to its requirements. Instead, we should wait for util-linux-libuuid to be merged, then upgrade the fontconfig recipe to require util-linux-libuuid instead of libuuid. Then libxft should pass

**Comment by ericLemanissier** [comment]
blocked by:
- https://github.com/conan-io/conan-center-index/pull/17664
- https://github.com/conan-io/conan-center-index/pull/17995

**Review by SSE4 — APPROVED** [review]

**Comment by ericLemanissier** [comment]
this one can be re-triggered now that https://github.com/conan-io/conan-center-index/pull/17995 is merged

**Comment by jwillikers** [comment]
Can this be triggered again?

**Review by valgur — APPROVED** [review]

**Comment by jcar87** [comment]
Closing in favour of https://github.com/conan-io/conan-center-index/pull/18789.

Please feel free to reopen and update if something was missing.

**Pull request closed without merging**
