### PR TITLE
sentry-crashpad/0.4.11

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **sentry-crashpad/0.4.11**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
Waiting for https://github.com/conan-io/conan-center-index/pull/6280

**Comment by ericriff** [comment]
Can you do sentry-breakpad as well? It will be the default backend on some platforms after my pr goes in
https://github.com/conan-io/conan-center-index/pull/6294

**Review by ericriff — APPROVED** [review]

**Comment by jgsogo** [comment]
> Waiting for #6280

Is it required for this PR? (I've trigger #6280 again and I'll try to shepherd it through the CI)

**Review by uilianries — APPROVED** [review]

**Comment by MartinDelille** [comment]
> Is it required for this PR? (I've trigger #6280 again and I'll try to shepherd it through the CI)

No.

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
