### PR TITLE
fmt: add version 11.0.0

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **fmt/11.0.0**

#### Motivation
There are lots of update since 10.2.1.

#### Details
https://github.com/fmtlib/fmt/compare/10.2.1...11.0.0

I deleted one line in test_package.cpp because it failed in gcc14 with c++20.
I already created [PR](https://github.com/fmtlib/fmt/pull/4042) about this issue. 
Since this seems to be a rare case, I decided to delete this line without waiting for the merge.

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by uilianries — COMMENTED** [review]
Thank you for updating this project! 

The version 11.x introduced the option `FMT_UNICODE` that I think could added to the recipe too. 

https://github.com/fmtlib/fmt/compare/10.2.1...11.0.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR170

**Review by AbrilRBS — COMMENTED** [review]
@toge thanks a lot for taking the time to submit the fix upstream, I'm sure they really appreciate it! ❤️

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by AbrilRBS — APPROVED** [review]
Thanks :)

**Review by uilianries — APPROVED** [review]
LGTM. Thank you for updating fmt, good catch by exposing /utf-8 for msvc.

**Pull request merged**
