### PR TITLE
[ginkgo] prefix components names with package

### PR DESCRIPTION
**Pull request by upsj**
Following up on a review suggestion by @SpaceIm in #4916 that unfortunately came after the PR was already merged

This PR adds a `ginkgo_` prefix to all components in the package to avoid issues with non-namespaced generators (I think?)

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — CHANGES_REQUESTED** [review]
Judging by this line this more problems https://github.com/ginkgo-project/ginkgo/blob/3ab51dbfd29d246053bed7fd06c47aabe504bb3d/core/CMakeLists.txt#L64

Currently the does does not match https://github.com/conan-io/conan-center-index/blob/5068b420b7f6e1d1c0c5c7171cab79d44bdb32a2/recipes/ginkgo/all/test_package/CMakeLists.txt#L10

You are probable missing names for the components themselves

**Comment by upsj** [comment]
@prince-chrismc I would really like to do make these uses match, unfortunately Conan won't let me:
From CMake's perspective, our package is named `Ginkgo` everywhere. From a package manager's perspective, its name is `ginkgo` everywhere. Its primary library is named `ginkgo`, which has dependencies to four other libraries `ginkgo_*`, which themselves have interdependencies. So I need to specify components to force a fixed linking order.
```diff
diff --git a/recipes/ginkgo/all/conanfile.py b/recipes/ginkgo/all/conanfile.py
diff --git a/recipes/ginkgo/all/conanfile.py b/recipes/ginkgo/all/conanfile.py
index 674320c7..ebb28085 100644
--- a/recipes/ginkgo/all/conanfile.py
+++ b/recipes/ginkgo/all/conanfile.py
@@ -109,9 +109,9 @@ class GinkgoConan(ConanFile):
         self.cpp_info.components["ginkgo_omp"].requires = [
             "ginkgo_cuda", "ginkgo_hip"]
 
-        self.cpp_info.components["ginkgo_core"].libs = [
+        self.cpp_info.components["ginkgo"].libs = [
             "ginkgo" + debug_suffix]
-        self.cpp_info.components["ginkgo_core"].requires = [
+        self.cpp_info.components["ginkgo"].requires = [
             "ginkgo_reference", "ginkgo_omp", "ginkgo_cuda", "ginkgo_hip"]
 
         self.cpp_info.names["cmake_find_package"] = "Ginkgo"
diff --git a/recipes/ginkgo/all/test_package/CMakeLists.txt b/recipes/ginkgo/all/test_package/CMakeLists.txt
index 3a3f92d6..3762d9b6 100644
--- a/recipes/ginkgo/all/test_package/CMakeLists.txt
+++ b/recipes/ginkgo/all/test_package/CMakeLists.txt
@@ -7,5 +7,5 @@ conan_basic_setup()
 find_package(Ginkgo REQUIRED)
 
 add_executable(test_install test_install.cpp)
-target_link_libraries(test_install Ginkgo::Ginkgo)
+target_link_libraries(test_install Ginkgo::ginkgo)
 set_target_properties(test_install PROPERTIES CXX_STANDARD 14)
```
`Component name cannot be the same as the package name: 'ginkgo'`

**Comment by SpaceIm** [comment]
Please consider https://github.com/upsj/conan-center-index/pull/1

**Comment by SpaceIm** [comment]
> 
> 
> Judging by this line this more problems https://github.com/ginkgo-project/ginkgo/blob/3ab51dbfd29d246053bed7fd06c47aabe504bb3d/core/CMakeLists.txt#L64
> 
> Currently the does does not match
> 
> https://github.com/conan-io/conan-center-index/blob/5068b420b7f6e1d1c0c5c7171cab79d44bdb32a2/recipes/ginkgo/all/test_package/CMakeLists.txt#L10
> 
> You are probable missing names for the components themselves

@prince-chrismc ALIAS target **is not** IMPORTED target. It's good practice to have consistent ALIAS targets and IMPORTED targerts, that's all (which is the case here).

**Review by SpaceIm — APPROVED** [review]

**Comment by prince-chrismc** [comment]
I apologize... I should have linked the 2 lines above which stated it was the `IMPORTED` target which is why I presumed there was need for more work.

Which @SpaceIm great work once again 

Hopefully this make it easy for your consumer via Conan

**Review by prince-chrismc — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
