### PR TITLE
glib: modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
- no `self.info` in `validate()`
- remove `with_pcre` option since it doesn't make sense after 2.69.0 (can't be disabled)
- add `package_type`
- remove PKG_CONFIG_PATH workaround in test package (fixed in conan 1.55.0)

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — DISMISSED** [review]

**Comment by SpaceIm** [comment]
```
clang: error: no such file or directory: 'CoreServices'
clang: error: no such file or directory: 'CoreFoundation'
clang: error: no such file or directory: 'AppKit'
make[2]: *** [bin/test_package] Error 1
make[1]: *** [test_package/CMakeFiles/test_package.dir/all] Error 2
```

WTF? A weird error In test v1 package only for a very specific apple-clang configuration of a very specific glib version?

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
```
ERROR: HTTPSConnectionPool(host='c3i.jfrog.io', port=443): Max retries exceeded with url: /c3i/api/conan/conan-center/v2/conans/ninja/1.11.1/_/_/revisions/a2f0b832705907016f336839f96963f8/packages/723257509aee8a72faf021920c2874abc738e029/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025F7F596588>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```

v2 pipeline seems quite fragile for the moment :s

**Comment by SpaceIm** [comment]
```
libffi/3.4.3: Retrieving package ae9eaf478e918e6470fe64a4d8d4d9552b0b3606 from remote 'conan-center' 
libffi/3.4.3: ERROR: Exception while getting package: ae9eaf478e918e6470fe64a4d8d4d9552b0b3606
libffi/3.4.3: ERROR: Exception: <class 'conans.errors.ConanConnectionError'> HTTPSConnectionPool(host='c3i.jfrog.io', port=443): Max retries exceeded with url: /c3i/api/conan/conan-center/v2/conans/libffi/3.4.3/_/_/revisions/ab23056d668dc13482a811f215f7be3e/packages/ae9eaf478e918e6470fe64a4d8d4d9552b0b3606/revisions/988b05c80f6aa89be687fca86351dad2/files (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C1498E2708>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

Unable to connect to conan-center=https://c3i.jfrog.io/c3i/api/conan/conan-center
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
ERROR: HTTPSConnectionPool(host='c3i.jfrog.io', port=443): Max retries exceeded with url: /c3i/api/conan/conan-center/v2/conans/libffi/3.4.3/_/_/revisions/ab23056d668dc13482a811f215f7be3e/packages/ae9eaf478e918e6470fe64a4d8d4d9552b0b3606/revisions/988b05c80f6aa89be687fca86351dad2/files (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C1498E2708>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```

again & again 😞

**Comment by SpaceIm** [comment]
@danimtb @uilianries needs help here, there is something wrong in v2 pipeline. It randomly fails to access packages.

**Pull request merged**
