### PR TITLE
Add JsonCPP v1.9.4

### PR DESCRIPTION
**Pull request by TheStormN**
Specify library name and version:  **jsoncpp/1.9.4**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by intelligide — APPROVED** [review]

**Comment by SpaceIm** [comment]
Since 1.9.4:
- jsoncpp builds again both static and shared by default, but also objects files which are installed...
- replacing PIC part is not required in 1.9.4 since it's not forced anymore for static target

I've preparated a PR for jsoncpp, but I'll just submit few parts into yours.

**Comment by TheStormN** [comment]
> Since 1.9.4:
> 
> * jsoncpp builds again both static and shared by default, but also an OBJECT target which is installed...
> * replacing PIC part is not required in 1.9.4 since it's not forced anymore for static target
> 
> I've preparated a PR for jsoncpp, but I'll just submit few parts into yours.

Well, I've just bumped the version. If you want to make changes to the build configurations, perhaps it would be better to do it in separate PR?

**Comment by SpaceIm** [comment]
The build of 1.9.4 create packages with both shared and static, so it's not a proper packaging, that's the point.

**Comment by TheStormN** [comment]
> The build of 1.9.4 create packages with both shared and static, so it's not a proper packaging, that's the point. You can't just bump the version in conandata as is in this case.

Weird changes for minor version... Anyway, feel free to add the needed changes.

**Comment by SpaceIm** [comment]
Please consider https://github.com/TheStormN/conan-center-index/pull/1

**Comment by SpaceIm** [comment]
> Weird changes for minor version... Anyway, feel free to add the needed changes.

They also broke CMake imported target if static, so yes it's weird.

**Review by SpaceIm — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
