### PR TITLE
update sqlite3 to 3.34.1

### PR DESCRIPTION
**Pull request by paulo-coutinho**
Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Comment by SpaceIm** [comment]
Why CI result is marked failed?

**Comment by prince-chrismc** [comment]
CCI bot posted a fail

https://api.github.com/repos/conan-io/conan-center-index/statuses/53c98be3c899a1dd056f907c5bd1dc7ea965e91a
```json
  {
    "url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/53c98be3c899a1dd056f907c5bd1dc7ea965e91a",
    "avatar_url": "https://avatars.githubusercontent.com/u/54393557?v=4",
    "id": 11948339664,
    "node_id": "MDEzOlN0YXR1c0NvbnRleHQxMTk0ODMzOTY2NA==",
    "state": "error",
    "description": "This commit cannot be built",
    "target_url": "https://ci-conan-prod.jfrog.team/job/cci/job/PR-4350/2/display/redirect",
    "context": "continuous-integration/jenkins/pr-merge",
    "created_at": "2021-01-24T08:53:01Z",
    "updated_at": "2021-01-24T08:53:01Z",
    "creator": {
      "login": "conan-center-bot",
```

**Comment by paulo-coutinho** [comment]
What is wrong?

**Comment by prince-chrismc** [comment]
There's a bug in the CCI bot that's been causing a few failures

**Comment by paulo-coutinho** [comment]
What i need do?

**Comment by uilianries** [comment]
It's something related to CI bot and Github event. We will check it soon.

**Review by uilianries — APPROVED** [review]

**Pull request merged**
