### PR TITLE
add onnx/1.8.1

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **onnx/1.8.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

closes https://github.com/conan-io/conan-center-index/issues/4728

### CODE REVIEW

**Comment by SpaceIm** [comment]
I was surprised to not be able to reproduce those errors, until I tried to disable Ninja and fall back to Makefiles. Just have to figure out what happen with Makefiles.

**Comment by SpaceIm** [comment]
There is something wrong in Visual Studio 16 agent, it shouldn't fail.

**Comment by SpaceIm** [comment]
patch submitted to upstream https://github.com/onnx/onnx/pull/3317

**Comment by SpaceIm** [comment]
This issue with undefined reference is not reproducible.
Visual Studio 16 / MTd/ Debug / Static is OK in build 3 but not in build 4...

**Comment by SpaceIm** [comment]
So now Visual Studio 16 / MD / Release / Static is OK in build 5, but I didn't change anything to fix this issue.

**Comment by SpaceIm** [comment]
And now it builds, well pretty sure there is something wrong in Visual Studio 16 agent.

**Review by prince-chrismc — DISMISSED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by jgsogo** [comment]
Hi! Sorry for the delay. There are more than one Windows machines, all of them with VS 16. It looks like it fails for one of them, but not for the others, so it has to be something related to _our_ installation.

I would say it is this same issue: https://developercommunity.visualstudio.com/t/-dyn-tls-on-demand-init-and-tls-guard-related-weir/1010557

Q:
> [regression] [worked-in:16.4.5]
> There exists a strange issue with newer versions of Visual Studio.
>
> When I compile the library google/protobuf with Visual Studio v16.5.4, the compilation is fine, however when trying to link against the library I get linker errors about ___dyn_tls_on_demand_init and ___tls_guard as unresolved external symbols.
>
> If protobuf is compiled with VS v16.4.5, this issue does not happen, even if the project that tried to link against the library was compiled using v16.5.4. This leads me to believe this is a Visual Studio related issue, rather than a protobuf one.
> 
>I believe the issue should be fairly simple to reproduce.
>
>I am not sure at which version Visual Studio broke exactly, as I have not tested every single version in-between, but I can confirm v16.5.4 is problematic and v16.4.5 does not suffer from such an issue.

Answer:
> These symbols, __dyn_tls_on_demand and __tls_guard, were added in Visual Studio 2019 16.5 in the static startup library (msvcrt.lib for /MD and libcmt.lib for /MT) in order to properly support dynamic TLS initialization. The compiler will refer to these symbols and assume they will be present in the final link via msvcrt.lib or libcmt.lib.
> 
> Looking at your repro project, it appears that the repro binary you are linking with the v141 toolset shipped with Visual Studio 2017. Updating to use the v142 toolset in Visual Studio 2019 16.5 or later will resolve the issue.
> 
> Note that the compatibility policy is that the version of libraries must be newer than the compiler used to produce all the objs and libs. In this case, the compiler used is newer than the libraries linked against, so there is a linker failure.

Now, I need to have a look at how it translates to our infrastructure.

**Comment by jgsogo** [comment]
Found it! Some machines are running `cl.exe` 19.28.29333 and one is not updated, it runs 19.24.28316. Reporting the bug...

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
