### PR TITLE
geos: add components

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **geos/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

`GEOS` creates `geos-targets.cmake` and `geos-config.cmake`.
Targets are `GEOS::geos`, `GEOS::geos_cxx_flags` (only for compile definitions and compile features) and `GEOS::geos_c`.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Mmmhh, find_package in config mode looks for target exact name, then lowercase, but not uppercase. It can't work on case sensitive filesystem without https://github.com/conan-io/conan/issues/7254

**Comment by uilianries** [comment]
@SpaceIm I'm waiting for that feature too, I need for protobuf.

**Comment by SpaceIm** [comment]
`cmake_find_package_multi` is know fixed for geos (this PR requires conan 1.28.0 since `filenames` attribute is used).

**Comment by uilianries** [comment]
Not too fast, Conan 1.28 is not available in CCI yet ...

**Pull request merged**
