### PR TITLE
Package/implot add implot demo.cpp

### PR DESCRIPTION
**Pull request by FranzPoize**
Specify library name and version:  **implot/0.15**

Adds implot_demo.cpp into the recipe so that user can use the main documentation of implot

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by FranzPoize** [comment]
Not sure what I should do from here on out. I think I have access so I guess the build have been launched, but I can't check what the errors are (I get a 403 when I click on details).

**Comment by RubenRBS** [comment]
Hi @FranzPoize thanks a lot for your contribution, sorry we didn't look into this earlier

> Not sure what I should do from here on out. I think I have access so I guess the build have been launched, but I can't check what the errors are (I get a 403 when I click on details).

The CI is not accesible to contributors to limit exposure of its internal workings, and the bot then posts the relevant bits once the compilations are done - Your case was different because it was waiting on you being greanted access to the system, sorry that we did not comunicate it further, we totally should have

Any way, thanks a lot for your patience, it seems like the build did work as expected now, so we'll be sure to review this next Monday :)

**Comment by FranzPoize** [comment]
Hi @RubenRBS, no worries at all it went super well. It just took more time than i thought to acknowledge my access request after its merge

**Comment by uilianries** [comment]
Weird error. Restarting that build right now.

**Review by RubenRBS — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
