### PR TITLE
add cityhash/cci.20130801

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

It fails with Visual Studio, there is some weird issue with source file path.

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
cityhash/cci.20130801@bincrafters/testing: run_in_windows_bash: C:\.conan\b0665d\1\bin\msys64\usr\bin\bash.exe --login -c ^"cd \^"/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651\^" ^&^& PATH=\^"/c/users/runneradmin/.conan/data/libtool/2.4.6/_/_/package/b65aafefa4036f1abc12efbf25e90cc02193effb/bin:/c/.conan/b0665d/1/bin/msys64/usr/bin:/c/users/runneradmin/.conan/data/automake/1.16.3/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin:/c/users/runneradmin/.conan/data/autoconf/2.71/_/_/package/3475bd55b91ae904ac96fde0f106a136ab951a5e/bin:/c/users/runneradmin/.conan/data/m4/1.4.18/_/_/package/0a420ff5c47119e668867cdb51baff0eca1fdb68/bin:$PATH\^" ^&^& make -j2 ^"
make  all-recursive
make[1]: Entering directory '/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651'
Making all in src
make[2]: Entering directory '/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/src'
source='/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src/city-test.cc' object='city-test.obj' libtool=no \
DEPDIR=.deps depmode=msvc7 /bin/sh /c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/depcomp \
/c/users/runneradmin/.conan/data/automake/1.16.3/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -DHAVE_CONFIG_H -I. -I/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src -I..   -I/c/users/runneradmin/.conan/data/libtool/2.4.6/_/_/package/b65aafefa4036f1abc12efbf25e90cc02193effb/include -DNDEBUG  -O2 -Ob2 -MT -FS -EHsc -c -o city-test.obj `cygpath -w '/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src/city-test.cc'`
source='/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src/city.cc' object='city.lo' libtool=yes \
DEPDIR=.deps depmode=msvc7 /bin/sh /c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/depcomp \
/bin/sh ../libtool  --tag=CXX   --mode=compile /c/users/runneradmin/.conan/data/automake/1.16.3/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -DHAVE_CONFIG_H -I. -I/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src -I..   -I/c/users/runneradmin/.conan/data/libtool/2.4.6/_/_/package/b65aafefa4036f1abc12efbf25e90cc02193effb/include -DNDEBUG  -O2 -Ob2 -MT -FS -EHsc -c -o city.lo /c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src/city.cc
libtool: compile:  /c/users/runneradmin/.conan/data/automake/1.16.3/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -DHAVE_CONFIG_H -I. -I/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src -I.. -I/c/users/runneradmin/.conan/data/libtool/2.4.6/_/_/package/b65aafefa4036f1abc12efbf25e90cc02193effb/include -DNDEBUG -O2 -Ob2 -MT -FS -EHsc -c -showIncludes /c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src/city.cc -o city.obj
city.cc
c1xx: fatal error C1083: Cannot open source file: 'C:C:/.conan/b0665d/1/bin/msys64/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/source_subfolder/src/city.cc': No such file or directory
make[2]: *** [Makefile:641: city.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
city-test.cc
make[2]: Leaving directory '/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651/src'
make[1]: *** [Makefile:453: all-recursive] Error 1
make[1]: Leaving directory '/c/users/runneradmin/.conan/data/cityhash/cci.20130801/bincrafters/testing/build/a79a557254fabcb77849dd623fed97c9c5ab7651'
make: *** [Makefile:364: all] Error 2
```

**Comment by SpaceIm** [comment]
```
make[2]: Entering directory '/c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/src'
source='/c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src/city-test.cc' object='city-test.obj' libtool=no \
DEPDIR=.deps depmode=msvc7 /bin/sh /c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/depcomp \
/c/j/w/buildsinglereference@2/.conan/data/automake/1.16.3/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -DHAVE_CONFIG_H -I. -I/c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src -I..   -I/c/j/w/buildsinglereference@2/.conan/data/libtool/2.4.6/_/_/package/df56c2b4f8e488bbd25eedb52fba643c7d59c97f/include -DNDEBUG  -O2 -Ob2 -MT -FS -EHsc -c -o city-test.obj `cygpath -w '/c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src/city-test.cc'`
source='/c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src/city.cc' object='city.lo' libtool=yes \
DEPDIR=.deps depmode=msvc7 /bin/sh /c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/depcomp \
/bin/sh ../libtool  --tag=CXX   --mode=compile /c/j/w/buildsinglereference@2/.conan/data/automake/1.16.3/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -DHAVE_CONFIG_H -I. -I/c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src -I..   -I/c/j/w/buildsinglereference@2/.conan/data/libtool/2.4.6/_/_/package/df56c2b4f8e488bbd25eedb52fba643c7d59c97f/include -DNDEBUG  -O2 -Ob2 -MT -FS -EHsc -c -o city.lo /c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src/city.cc
libtool: compile:  /c/j/w/buildsinglereference@2/.conan/data/automake/1.16.3/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -DHAVE_CONFIG_H -I. -I/c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src -I.. -I/c/j/w/buildsinglereference@2/.conan/data/libtool/2.4.6/_/_/package/df56c2b4f8e488bbd25eedb52fba643c7d59c97f/include -DNDEBUG -O2 -Ob2 -MT -FS -EHsc -c -showIncludes /c/j/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src/city.cc -o city.obj
city.cc
c1xx: fatal error C1083: Cannot open source file: 'C:J:/w/buildsinglereference@2/.conan/data/cityhash/cci.20130801/_/_/build/7bd6f2c3d5c4e48a75805376b58cde753392f711/source_subfolder/src/city.cc': No such file or directory
make[2]: *** [Makefile:641: city.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
city-test.cc
```

@madebr Any idea on this issue? Compilation of city.cc is wrapped in libtool and fails (it seems to do something wrong with file path), while city-test.cc succeeds without libtool.

**Comment by madebr** [comment]
> @madebr Any idea on this issue? Compilation of `city.cc` is wrapped in libtool and fails (it seems to do something wrong with file path), while compilation of `city-test.cc` succeeds without libtool.

Weird, `configure.ac` and the `Makefile.am` files don't use any fancy features.

```
 /c/users/maarten/.conan/data/automake/1.16.3/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -DHAVE_CONFIG_H -I. -I/c/users/maarten/.conan/data/cityhash/cci.20130801/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/source_subfolder/src -I.. -DNDEBUG -O2 -Ob2 -MD -FS -EHsc -c /c/users/maarten/.conan/data/cityhash/cci.20130801/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/source_subfolder/src/city.cc
```
fails, but 
```
cl -nologo -DHAVE_CONFIG_H -I. -I/c/users/maarten/.conan/data/cityhash/cci.20130801/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/source_subfolder/src -I.. -DNDEBUG -O2 -Ob2 -MD -FS -EHsc -c /c/users/maarten/.conan/data/cityhash/cci.20130801/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/source_subfolder/src/city.cc
```
succeeds.
So wrapping `cl` with automake's `compile` script makes it fail (unix path is incorrectly converted to a windows path).

I think the problem is due to stacking the `compile` script twice:
`libtool` will use the `compile` script (or something similar) themself.
When changing the environment variables to
```python

                env = {
                    "CC": "cl -nologo",
                    "CXX": "cl -nologo",
                    "LD": "link -nologo",
                    "AR": "{} lib".format(tools.unix_path(self.deps_user_info["automake"].ar_lib)),
                }
```
I got it building.

**Comment by SpaceIm** [comment]
Great, thanks !

**Review by madebr — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
