### PR TITLE
Bump doctest to 2.4.6

### PR DESCRIPTION
**Pull request by ruilvo**
Specify library name and version:  **doctest/2.4.6**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ruilvo** [comment]
We probably need to add C++17 as a public requirement for usage. I'm going to check what versions require what.

**Comment by ruilvo** [comment]
It's C++11, my bad!

**Comment by ruilvo** [comment]
The CI complains about:
```
CMake Error at /home/conan/w/BuildSingleReference/.conan/data/doctest/2.4.6/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/doctestAddTests.cmake:60 (if):
  if given arguments:

    "EQUAL" "1"

  Unknown arguments specified
```

That line on that file reads:
```
  if(${add_labels} EQUAL 1)
```
So seems the variable is boiling down to nothing?

**Comment by ruilvo** [comment]
I officially have no idea what's going on...

**Comment by ruilvo** [comment]
I found the problem to have to do with onqtam/doctest/issues/489. Let's see if it doesn't mind building with the flag on the test. If it does, I might put this version on a separate folder.

**Comment by ruilvo** [comment]
Yay! The needed variable is backward compatible :D CMake's janky arg parsing working in our behalf on this one.

Sorry for the CI usage!

Ready now :)

**Review by ericLemanissier — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
