### PR TITLE
opentelemetry-cpp: add version 1.8.2, update dependencies

### PR DESCRIPTION
**Pull request by MrSparc**
Specify library name and version: opentelemetry-cpp/*

- add version 1.8.2
- add add_subdirectory in test_v1_package

This PR was based on [toge](https://github.com/toge) PR: https://github.com/conan-io/conan-center-index/pull/15687 that was closed as outdated  to be merged by this new one. 

---
 

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Make sure to comment in #4

**Comment by prince-chrismc** [comment]
You need to wait #15980 has not merged

**Comment by prince-chrismc** [comment]
Please do not force push 🙏 GitHub forces us to restart the review which is not fun!

**Review by prince-chrismc — APPROVED** [review]

**Comment by MrSparc** [comment]
> Please do not force push 🙏 GitHub forces us to restart the review which is not fun!

Ohh, sorry I didn't know that.

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
There's merge conflicts FYI

**Comment by MrSparc** [comment]
Hi @prince-chrismc I had to rebase to merge the changes that were added into this recipe in the meantime since my PR was created.
Please check if that's ok.

**Comment by MrSparc** [comment]
Sorry but it looks  I made a mess of updating my fork with master and doing the rebase which is referring to other issues in this PR. I don't know how to fix it if necessary.

**Comment by MrSparc** [comment]
@prince-chrismc 
Conan v1 pipeline v1 is reporting what I think was a transient error when it was run as it is giving an error on package grpc-proto/cci.20220627 which cannot be downloaded but was used in other builds earlier.
This PR wouldn't change anything about this dependency:
```
ERROR: Missing binary: grpc-proto/cci.20220627:1ebc5c26f9d4e062ad1c3ac414832acfc06d22a5
grpc-proto/cci.20220627: WARN: Can't find a 'grpc-proto/cci.20220627' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.libcxx=libc++, compiler.version=11.0, os=Macos
```
Please can you take a look to see if we can unblock the merge of this PR?
Thanks!

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
It's all the version conflicts that need to resolved upstream, it's only the first missing I suspect

**Comment by MrSparc** [comment]
Pinging @prince-chrismc about if there is any news about  version conflict on upstream to unlock this PR.
OpenTelemetry already release v1.8.3 and I would like to create a new PR to update the recipe to include this new version  but we need first merge all these previous PR for this same recipe.

**Comment by prince-chrismc** [comment]
Please open PRs to bump dependencies :)

**Comment by MrSparc** [comment]
> Please open PRs to bump dependencies :)

It would gladly help if I understood what are the problems of dependency versions of other packages that are failing, but I think without help it goes beyond me in my limited knowledge of Conan :/

**Comment by prince-chrismc** [comment]
These requires need to be update to be consistent with the downstream requirements.
https://github.com/conan-io/conan-center-index/blob/c37a2f18f60b8087ddc0948e7234be47e8c4f100/recipes/opentelemetry-cpp/all/conanfile.py#L89 

Drilling down

- this error is from `ERROR: Missing binary: grpc-proto/cci.20220627:1ebc5c26f9d4e062ad1c3ac414832acfc06d22a5`
- https://github.com/conan-io/conan-center-index/blob/c37a2f18f60b8087ddc0948e7234be47e8c4f100/recipes/opentelemetry-cpp/all/conanfile.py#L104
- https://github.com/conan-io/conan-center-index/blob/c37a2f18f60b8087ddc0948e7234be47e8c4f100/recipes/grpc/all/conanfile.py#L100

Holy crap okay that's actually complicated AF lol 😱

**Comment by prince-chrismc** [comment]
I will trigger it again 🤞 maybe those configs now exists

**Comment by prince-chrismc** [comment]
v2 should fail because `opentelemetry-proto` is missing

**Comment by prince-chrismc** [comment]
Locally with v1 I get these conflicts 🤔 

```
WARN: grpc/1.50.1: requirement openssl/1.1.1s overridden by opentelemetry-cpp/1.8.1 to openssl/1.1.1t
WARN: thrift/0.17.0: requirement openssl/1.1.1s overridden by opentelemetry-cpp/1.8.1 to openssl/1.1.1t
WARN: libevent/2.1.12: requirement openssl/1.1.1m overridden by thrift/0.17.0 to openssl/1.1.1t
```

**Comment by rbharvs** [comment]
Hi all,

I opened a Github [issue](https://github.com/conan-io/conan-center-index/issues/16296) recently related to an issue I discovered that was introduced to the package recipe recently. Namely, a change was made that to the recipe that caused Conan to build the example files in the OpenTelemetry repo. Unfortunately, there is a mistkae in one of their example files that prevents it from building in C++ 20.

Would the authors of this PR would consider updating it to turn off the building of the example files? cc @MrSparc @prince-chrismc @jwillikers 

Thank you!

**Comment by prince-chrismc** [comment]
Seems like adding `        tc.variables["WITH_EXAMPLES"] = False` is an easy fix, have you tested this locally?

**Comment by MrSparc** [comment]
> Seems like adding ` tc.variables["WITH_EXAMPLES"] = False` is an easy fix, have you tested this locally?

A PR about this topic was already raised:
https://github.com/conan-io/conan-center-index/pull/16220

**Comment by rbharvs** [comment]
> Seems like adding ` tc.variables["WITH_EXAMPLES"] = False` is an easy fix, have you tested this locally?

Yes, agreed, would be an easy fix. I have not tested it locally yet.

> A PR about this topic was already raised: #16220

Ah, I missed that, thank you.

**Comment by MrSparc** [comment]
@prince-chrismc can you trigger it again as some package dependencies were updated in the meantime? This PR was marked as stale.

**Comment by malcolmdavey** [comment]
Any progress?

**Comment by prince-chrismc** [comment]
You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁 

Service is currently under maintenance so you should wait a day

**Comment by ArielGMachado** [comment]
All I wanted was to update a recipe to include 1.8.2 but not rewrite the entire cookbook...

Now the old opentelemetry-cpp/1.4.1 failed because:
```
ERROR: Missing binary: grpc/1.50.1:4e914df54182e8cc93e64fce8cf43f88c7c56ab2
ERROR: Missing binary: libcurl/7.87.0:31bccab54732bcb63b59ced4b6daa7c81021754f
ERROR: Missing binary: libevent/2.1.12:c378a47a0c2d7b4c80c55a6ef608ec40d4eb303a

ERROR: Missing prebuilt package for 'grpc/1.50.1', 'libcurl/7.87.0', 'libevent/2.1.12'
```
this is a never ending history :(

**Review by memsharded — COMMENTED** [review]
Maybe this version is no longer important once 1.9.1 is out?

**Comment by MrSparc** [comment]
> Maybe this version is no longer important once 1.9.1 is out?
 I agree, with a more recent version there is no reason to continue this PR.
We even had to use v1.8.3 and ended up creating a local recipe since this PR could not be merged to propose a new PR.
Already in version 1.9.1 they had to change the versions of the dependencies and the paths with LD_PATH probably because they were having the same errors as in this PR.

**Pull request closed without merging**
