### PR TITLE
Upgrade MaterialX to 1.39.1 release

### PR DESCRIPTION
**Pull request by EstebanDugueperoux2**
### Summary
Add materialx/1.39.1

### CODE REVIEW

**Review by ErniGH — APPROVED** [review]
Thanks ❤️

**Comment by EstebanDugueperoux2** [comment]
Hi @uilianries, I permit to ping you to have your review :)
Thanks in advance.

Thanks @ErniGH .

**Review by AbrilRBS — DISMISSED** [review]
Thanks for adding the new version, I have fixed a few things, otherwise looks good :)

**Review by AbrilRBS — COMMENTED** [review]
We should also disable `MATERIALX_BUILD_USE_CCACHE` to be on the safe side for now

**Review by AbrilRBS — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
Not easy to review this update:

https://github.com/AcademySoftwareFoundation/MaterialX/compare/v1.38.10...v1.39.1

Screenshot 2024-09-12 at 16-40-14 Comparing v1 38 10 v1 39 1 · AcademySoftwareFoundation_MaterialX

From main CMakeLists.txt, it looks correct, all new features are deactivated.

**Review by ErniGH — APPROVED** [review]

**Pull request merged**
