### PR TITLE
add option libuuid

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **libuuid/all**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
relates to https://github.com/conan-io/conan-center-index/pull/19547

**Review by ericLemanissier — CHANGES_REQUESTED** [review]
libuuid is deprecated because it is incompatible with uuid implementation shipped by most (all?) distros. The solution to your problem is to stop requiring libuuid in cpython and require libutil-uuid instead.

**Review by danimtb — APPROVED** [review]

**Review by danimtb — CHANGES_REQUESTED** [review]
Sorry, I approved by error. Please check Eric's comment https://github.com/conan-io/conan-center-index/pull/19552#pullrequestreview-1607953938

**Comment by AndreyMlashkin** [comment]
I am closing this one as a duplicate

**Pull request closed without merging**
