### PR TITLE
add folly/2020.01.13

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **folly/2020.01.13**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
this is blocked by #630

**Comment by danimtb** [comment]
Blocked by #630

**Comment by danimtb** [comment]
@ericLemanissier please do not open a close PR to relaunch the CI. Packages take some time to upload to the central repo, especially if those are big ones or there are a lot of them. Be patient and check availability of packages first with `conan search`. Thanks!

**Comment by ericLemanissier** [comment]
Instead of deleting the option, maybe we should raise an exception if the value is incorrect?

**Comment by ericLemanissier** [comment]
I'm not sure to understand why does this fail:
```
ERROR: folly/2019.09.02: Error in source() method, line 78
	tools.get(**self.conan_data["sources"][self.version])
	KeyError: 'sources'
```

**Comment by Croydon** [comment]
conandata.yml only contains `2020.01.06`, while config.yml only contains `2019.09.02`

**Comment by ericLemanissier** [comment]
I reported this error upstream: https://github.com/facebook/folly/issues/1311

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan-center-index/pull/920

**Pull request closed without merging**
