### PR TITLE
cairo: Add package_type and bump dependencies

### PR DESCRIPTION
**Pull request by jwillikers**
Specify library name and version:  **cairo/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by samuel-emrys — APPROVED** [review]

**Review by memsharded — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
Thanks!

**Review by RubenRBS — CHANGES_REQUESTED** [review]
Blocking until gtk-doc is merged so no extra PR/binary regeneration needs to be done for v2

**Comment by SSE4** [comment]
@RubenRBS can you unblock? thanks
I think we shouldn't block PRs to wait for other PRs merged. all PRs should be atomic. binary regeneration will happen from time to time, and it's normal.

**Comment by SSE4** [comment]
@RubenRBS can you unblock? it's blocked for 3 weeks already. please don't block PRs if you don't plan to unblock them with a reasonable deadline.

**Review by RubenRBS — APPROVED** [review]
@SSE4 thanks for the heads up, this fell thru the cracks as the related PR has not been able to progress

**Pull request merged**
