### PR TITLE
Adding package cpptoml 

### PR DESCRIPTION
**Pull request by dotChris90**
Specify library name and version:  "cpptoml/0.1.*"

The reason for the PR is the following : 
- i would like to soon or later bring https://github.com/eclipse-iceoryx/iceoryx into the conan-center 
- for that reason first i want to add one of their dependencies 
- cpptoml/0.1 

The header only library "cpptoml" is not made by me but present on https://github.com/skystrife/cpptoml - the conanfile mostly was copied from https://github.com/jgsogo/conan-cpptoml (with several changes to match pep8 ) i just didnt find it in conan center index. 
Even it is not a 1.X.Y version but i still think it's worth to bring it to the index. 

- [x ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes. (validated it via pycodestyle) 
- [x ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version (fresh today pip3 install conan) 
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Hello @dotChris90 ! 

Thank you for your contribution, I know tomlplusplus, but cpptoml is new ...

Please, consider my PR, which provide some improvements: https://github.com/dotChris90/conan-center-index/pull/1

**Comment by uilianries** [comment]
@dotChris90 Please, sign the CLA, commented on this PR, here: https://github.com/conan-io/conan-center-index/pull/5428#issuecomment-832189476

Without your sign, this PR can not be merged.

**Comment by dotChris90** [comment]
@uilianries  - thanks for the changes you made. I was using the cmake to be honest just because their Readme used it and because i thought it's the only way how to get the cmake files and package them. But i just found that the "consuming package" (so the project using the package) can use a generator (the cmake_find_package)  https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_multi_generator.html and then also can find it's package. Then absolute right - it's just this single header to export with some meta-information.

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by dotChris90** [comment]
hello @jgsogo  - hope it's ok if nudge you. I would you like to have a small review here? it's basically taken from your public repo https://github.com/jgsogo/conan-cpptoml with some changes ;) a very interesting project i want to bring to the conan center is using it ;) and i hope you dont mind i bring cpptoml to CCI :D

**Review by mathbunnyru — APPROVED** [review]

**Comment by jgsogo** [comment]
Thanks @dotChris90 for moving that recipe to ConanCenter. I will archive/remove my repository now 🚀

**Pull request merged**
