### PR TITLE
Set boost required version to 1.85.0 to be inline with thrift/0.17.0 …

### PR DESCRIPTION
**Pull request by maximiliank**
Adjust boost version dependency for arrow/all

### Summary
Changes to recipe:  **arrow/all**

#### Motivation
In the latest commit to the `thrift` recipe (https://github.com/conan-io/conan-center-index/commit/f8a8a29cdc062aa3c21ac73669a02e224010dbd5) the `boost` version requirement was set to 1.85.0. This results in a version conflict when `arrow` is requested with any option requiring `with_thrift` (e.q. `parquet` requires this)

#### Details
Solution is to increase the `boost` version to 1.85.0. Solves https://github.com/conan-io/conan-center-index/issues/24455

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]
Thanks! With the new pipeline we'll be able to handle cases like this in a simpler way by being able to modify more than once recipe per PR, sorry that this was an issue meanwhile :)

**Comment by maximiliank** [comment]
Unfortunately, I cannot view the details about the failing required checks c3i/conan-v2/pr-merge and continuous-integration/jenkins/pr-merge. How should I proceed here?

**Comment by RubenRBS** [comment]
Hi @maximiliank sorry for the bot noise - our CI got a bit confused, that's also the reason you couldn't see the logs. I've restarted the build now, let's see if it's happier about it this time around :)

**Comment by RubenRBS** [comment]
Should be fixed now 🤞 , sorry for the noise @maximiliank - if this gives more problems, I'll have to dig deeper on monday

**Comment by maximiliank** [comment]
Now 60 more fail and I still get a 403 Forbidden on the 3ci/conan-v2/pr-merge and continuous-integration/jenkins/pr-merge checks

**Comment by abba-kovner** [comment]
Hello @AbrilRBS, do you have an idea why the checks failed? Thank you

**Comment by maximiliank** [comment]
@AbrilRBS any news on this issue?

**Pull request merged**
