### PR TITLE
Grpc/cross build fix

### PR DESCRIPTION
**Pull request by roalter**
Specify library name and version:  **grpc/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jcar87** [comment]
Hi @roalter - thanks for opening this PR.

I'm very happy to look into this, as I've been working recently with the grpc recipe. Could you provide more details as to which scenarios are currently broken with the recipe? We did test the cross-compilation workflow. The `conan_toolchain.cmake` file should already allow the call to `find_program` to work properly, without the need of an additional environment variable. If this is not working as intended I'm happy to look into it and provide a robust fix

**Comment by roalter** [comment]
Still on investigating. I'm struggling on with including both contexts in the right way. But remember, still a legacy issue as we and many other still work on Conan < 2.0

Interessting is this part:
```cmake
self._cmake.definitions["CMAKE_PROGRAM_PATH"] = ";".join(list(set(self.deps_env_info["grpc"].PATH)))
```

This - in the context of the build - enables the lookup of the right plugins.

**Comment by jcar87** [comment]
> Still on investigating. I'm struggling on with including both contexts in the right way. But remember, still a legacy issue as we and many other still work on Conan < 2.0
> 
> Interessting is this part:
> 
> ```cmake
> self._cmake.definitions["CMAKE_PROGRAM_PATH"] = ";".join(list(set(self.deps_env_info["grpc"].PATH)))
> ```
> 
> This - in the context of the build - enables the lookup of the right plugins.

Yup, the intention is that (save for some very legacy workflows), this still works as intended for users on Conan 1.X.

Out of curiosity, which Conan generator(s) are you using in your workflow, and are you using one or two profiles when cross-building?
Cheers!

**Comment by roalter** [comment]
Will close this PR, doesn't work in the use case as expected.

**Pull request closed without merging**
