### PR TITLE
libevent: add libevent pkg_config (only requires core and extra)

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **libevent/all**

cc'ing @SpaceIm since you're *specialized* in this (or at least did the latest changes to package_info)

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
It generates:

```
$ cat libevent.pc 
prefix=/home/conan/.conan/data/libevent/2.1.11/_/_/package/6b0981c427aa0eb8bea05add2094df29ed639799
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libevent-libevent
Description: Conan package: libevent-libevent
Version: None
Libs: -L${libdir} -Wl,-rpath="${libdir}"
Cflags: -I${includedir}
Requires: libevent_core libevent_extra

```

**Review by uilianries — APPROVED** [review]

**Comment by madebr** [comment]
> It generates:
> 
> ```
> $ cat libevent.pc 
> prefix=/home/conan/.conan/data/libevent/2.1.11/_/_/package/6b0981c427aa0eb8bea05add2094df29ed639799
> libdir=${prefix}/lib
> includedir=${prefix}/include
> 
> Name: libevent-libevent
> Description: Conan package: libevent-libevent
> Version: None
> Libs: -L${libdir} -Wl,-rpath="${libdir}"
> Cflags: -I${includedir}
> Requires: libevent_core libevent_extra
> ```

Yup, see https://github.com/libevent/libevent/blob/master/libevent.pc.in for the reference.

Btw @uilianries , you should update conan because `Version: None` is fixed in the latest release.

**Comment by uilianries** [comment]
@madebr I need to update my Docker image for Conan!!!

**Comment by SpaceIm** [comment]
To fully mimic upstream pkg-config files, `openssl` and `pthreads` components should require this component `liblibevent` instead of `core` (even though I'm pretty sure that their lib only depends on `core` and not on `extra`):
https://github.com/libevent/libevent/blob/9b270c5e02e47d372ad53e773f98668890b33e9f/libevent_openssl.pc.in#L11
https://github.com/libevent/libevent/blob/9b270c5e02e47d372ad53e773f98668890b33e9f/libevent_pthreads.pc.in#L11

**Review by danimtb — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
