### PR TITLE
Enable gtk 3 on windows

### PR DESCRIPTION
**Pull request by hesham-essam**
Specify library name and version:  **gtk/3.24.24**

The major blocker for building gtk 3 on windows was [LNK1170 error ](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1170?view=msvc-170); that is the linking command for gtk 3 was so big the msvc linker can't handle it even with `short_paths` on.

This patch fixes this by editing the `ninja.build` file and removing duplicates in the link arguments.

I also forced some libraries to be shared, since I couldn't get the gtk demo to work without warnings/errors unless that was the case.

Also, gtk 3 requires external icons pack. I copy pasted Adwaita icons theme from my gtk 3 build on linux to make things work. Same problem on vcpkg here https://github.com/microsoft/vcpkg/issues/4417
How do we handle this? Do we include adawita icon pack in the recipe?

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
Update to `libxml2/2.9.14` to solve the conflict

**Comment by hesham-essam** [comment]
@Croydon Any idea how to fix this "MISSING_DEPENDENCIES" CI error?

**Comment by Croydon** [comment]
The binary packages are missing because you overwrote dependencies versions.

Unfortunately, the only way is to work through the dependency graph and update dependencies that appear multiple times to the same version

**Comment by hesham-essam** [comment]
I also think it's because I made `glib` a shared library, and atk/pango use static glib by default whether they're shared or static. Any way to get these packages built with this configuration?

I really think that glib should be shared by default on windows.

**Comment by Croydon** [comment]
> I also think it's because I made glib a shared library, and atk/pango use static glib by default whether they're shared or static. Any way to get these packages built with this configuration?

Unfortunately, no. It isn't possible to build additional configurations

**Comment by hesham-essam** [comment]
I will close this and create another PR

**Pull request closed without merging**
