### PR TITLE
[sentry-native] Stop depending other sentry-breakpad/sentry-crashpad recipes

### LINKED ISSUE #19675: [question] Use only one recipe for sentry-native/crashpad/breakpad
### What is your question?

After talking to the sentry-native developer [here](https://github.com/getsentry/sentry-native/pull/872#issuecomment-1693542784) he advised me that we should have only one recipe instead of three:
- sentry-native
- sentry-crashpad
- sentry-breakpad

I wondered what was the thought of the community and why the recipe had been splited originally.

I ping @madebr who originaly created the sentry-breakpad/crashpad recipe and @paulharris who recently pushed a fix the sentry-crashpad.

### PR DESCRIPTION
**Pull request by MartinDelille**
This PR aims to fix #19675 by removing the need for sentry-breakpad and sentry-crashpad

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
Hi @uilianries ! I wondered if someone from the team could help me on this PR ? I would make sentry-native maintenance so much simpler!

**Comment by MartinDelille** [comment]
@madebr @paulharris I'd like to have your input/advice on this draft!

**Comment by RubenRBS** [comment]
@uilianries is currently on vacation for a few more days, I'll try to check with the team about this PR until he returns, thanks a lot for your patience @MartinDelille :)

**Comment by MartinDelille** [comment]
@madebr @RubenRBS I'll be happy to have your feedback on this PR!

**Comment by MartinDelille** [comment]
Hi @RubenRBS ! May we have a chance to get this merged soon ?

**Comment by MartinDelille** [comment]
Hi @uilianries ! I have this PR I started working months ago that I would love to see merged in order to easier `sentry-native` maintenance (I talk about it with the upstream repo maintainer [here](https://github.com/getsentry/sentry-native/pull/872)).

Would you have a look ?

**Comment by uilianries** [comment]
Hello @MartinDelille I read #19675, #https://github.com/getsentry/sentry-native/pull/872 and https://github.com/conan-io/conan-center-index/pull/5536, but do you really have a blocker over this package? Is it breaking?

Usually in ConanCenterIndex we keep all submodules as external packages, and it fits the current state of that recipe. You are very expert in Conan, so you should noted it already.

Of course, as you pointed, we need a "patch" for sentry-breakpad, otherwise it does not work. Plus, the author recommended to use only submodules. So, I checked some linux distros and they don't split or use breakpad as a separated dependency, they keep all in the sentry-native package as well.

So, general speaking, I'm fine with your changes.

**Comment by MartinDelille** [comment]
Hi @uilianries !

Thanks for reviewing my PR. It is not breaking but it is a pain to update each new sentry-native version since I need to update sentry-breakpad and sentry-crashpad first (and regenerate the patches each times sentry is updating its submodule).

**Review by uilianries — COMMENTED** [review]
LGTM. I'll wait for @RubenRBS having a final review, then a I mark as approved. 

Thank you @MartinDelille for checking it with the upstream first!

**Review by uilianries — APPROVED** [review]
Approved.

**Comment by MartinDelille** [comment]
Hi @uilianries and @RubenRBS ! Is there anything blocking this PR to get merged ? Three releases have been published since I started this work: https://github.com/getsentry/sentry-native/releases

Having an up to date sentry-native SDK is recommended to work fine with https://sentry.io service.

**Review by RubenRBS — APPROVED** [review]

**Comment by MartinDelille** [comment]
Thank you so much! 🎉

**Comment by X1aomu** [comment]
Hi @MartinDelille 

I found a bug when using crashpad as backend on GNU/Linux, I don't think i know the root cause you added those line, would you take a look?

BTW, Sentry has officially maded crashpad the default backend on Linux according to the release note. What should CCI do in the future?

Anyway, i love those changes you made in this PR, thanks for your great work,

**Comment by MartinDelille** [comment]
Hi @X1aomu ! I indeed missed that! I configured crashpad as a default backend here: https://github.com/conan-io/conan-center-index/pull/22422/files#diff-95df6adf18543155d3f51239ff9678848b33c8922e0e652daa20175d2d2fc816R92-R93

Let's continue the conversation there.

**Pull request merged**
