### PR TITLE
mongo-c-driver: remove useless patch

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **mongo-c-driver/***

Revealed by https://github.com/conan-io/conan-center-index/commit/eee7db8caa8417b7e3dedf8137b5f1f70765baa0#diff-b7fdbf57431472eea5bb0ee25ca6a509090b211cb95114e1eb82ce6fa003c9d3R12 : the patch was not added to 1.26.2 by mistake

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8970013430/attempts/1)

**Comment by RubenRBS** [comment]
Quick clarification: With the Pr message body, do you mean that the patch should have never been applied?

**Comment by ericLemanissier** [comment]
@RubenRBS the patch was introduced in https://github.com/conan-io/conan-center-index/pull/11311#issuecomment-1162537455 on `mongo-c-driver/1.21.2` and actually fixed the error
Current versions of mongo-c-driver pass without this patch, showing that the problem has been fixed upstream between 1.21.2 and 1.23.5

**Comment by RubenRBS** [comment]
Oh I see, now I understand, thanks for the clarification! :)

**Review by toge — APPROVED** [review]

**Pull request merged**
