### PR TITLE
[hazelcast-cpp-client new version] hazelcast-cpp-client 4.1.0 release

### PR DESCRIPTION
**Pull request by ihsandemir**
Specify library name and version:  **hazelcast-cpp-client/4.1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

We just released new Hazelcast C++ client version 4.1.0, and i updated the existing recipe to include this new release.
---

- [ x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ihsandemir** [comment]
> Looks like you need c++11 features by default. Since only gcc 4.9 and 5 failed [ref](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/5468/1/hazelcast-cpp-client/4.1.0//summary.json) you could raise the minimum compiler for this new version
> 
> ~or maybe set the C++ standard in your project~ Which you are 🤔
> https://github.com/hazelcast/hazelcast-cpp-client/blob/c1f96b8549f4a989ff98e35ac486b6b2cb51465a/CMakeLists.txt#L25
> Seems you are only testing gcc 9.3 https://github.com/hazelcast/hazelcast-cpp-client/runs/2478772292?check_suite_focus=true#step:6:22
> 
> Is the failure expected?

The project should work with any compiler that has C++11 features. see [C++11 library features](https://en.cppreference.com/w/cpp/compiler_support). The standart library is only actually complete beginning with gcc5. Hence, that may be the reason. 

Out github actions test is only for newer gcc versions, it is NOT an indicator of minimum supported version for the project.

**Review by yuce — APPROVED** [review]

**Review by yuce — APPROVED** [review]

**Review by srknzl — APPROVED** [review]

**Comment by prince-chrismc** [comment]
This new version does not compile on C++11 compilers. Seems you need to improve your CI 🙃

**Comment by ihsandemir** [comment]
> This new version does not compile on C++11 compilers. Seems you need to improve your CI 🙃

We probably need to add more configurations, yes.

By the way, I just pushed a fix patch. Lets see how it works.

**Review by prince-chrismc — APPROVED** [review]
LGTM!

**Comment by ihsandemir** [comment]
> @ihsandemir Did you sent this new patch to the upstream? If not, please do.

Yes, i did  send the pr for upstream. Please see https://github.com/hazelcast/hazelcast-cpp-client/pull/872

**Comment by ihsandemir** [comment]
> > @ihsandemir Did you sent this new patch to the upstream? If not, please do.
> 
> Yes, i did send the pr for upstream. Please see [hazelcast/hazelcast-cpp-client#872](https://github.com/hazelcast/hazelcast-cpp-client/pull/872)

I merged this upstream PR, hence the change is in the master repository now.

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
