### PR TITLE
libgeotiff/1.7.1: Ensure conan proj is used

### PR DESCRIPTION
**Pull request by Chrismarsh**
Specify library name and version:  **libgeotiff/1.7.1**

libgeotiff as patched fails to find conan proj.h

```
-- Library proj not found in package, might be system one
-- Library proj.25 not found in package, might be system one
-- Library proj.25.9.0.1 not found in package, might be system one
-- Library proj not found in package, might be system one
-- Library proj.25 not found in package, might be system one
-- Library proj.25.9.0.1 not found in package, might be system one

[...]

.conan/data/libgeotiff/1.7.1/_/_/build/8c4e784c8e523cadba0c054914b8d76687863587/source_subfolder/libgeotiff/geo_keyp.h:18:10: fatal error: 'proj.h' file not found
#include "proj.h"
         ^~~~~~~~
```

because NO_MODULE is being used in the `find_package` cmake call. 

- [ x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Comment by Chrismarsh** [comment]
@uilianries Thank you for approving this. Is there anything else I need to do to have this merged in? I ask because it is currently blocking me and I'm uncertain if I should just have my own copy of this in my conan repo or should I wait for this to be approved?

**Comment by uilianries** [comment]
@Chrismarsh please, read https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md

**Comment by SpaceIm** [comment]
It works fine without this PR since there is cmake_find_package_multi in generators of this recipe. Could you open an issue please?

**Review by SSE4 — APPROVED** [review]

**Comment by SpaceIm** [comment]
Why is it accepted while this PR does the opposite of its title by removing `NO_MODULE`?

**Comment by Chrismarsh** [comment]
Hi @SpaceIm, Thanks for the input. I've opened this in #11368

**Comment by Chrismarsh** [comment]
Closing as it appears I had a corrupted conan proj build. Unclear how this occurred, but a clean rebuild w.o the PR resolved it.

**Pull request closed without merging**
