### PR TITLE
boost-ext-ut: Add version 2.0.0

### PR DESCRIPTION
**Pull request by jwillikers**
Specify library name and version:  **boost-ext-ut/2.0.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]

**Comment by jwillikers** [comment]
@RubenRBS I don't think there were any changes in there for the `m4` recipe...

**Comment by RubenRBS** [comment]
Those errors are due to a race condition in our CI with the Github api, most of the times re-triggering the build fixes it - I've done so now

**Comment by RubenRBS** [comment]
Seems like Cmake 3.21 or higher is needed in the new version

**Comment by RubenRBS** [comment]
You might need to add a VirtualBuildEnv now that the recipe has build requirements

**Review by RubenRBS — APPROVED** [review]

**Review by toge — APPROVED** [review]

**Pull request merged**
