### PR TITLE
Update to vulkan-loader

### PR DESCRIPTION
**Pull request by espositofulvio**
Specify library name and version:  **vulkan-loader/1.2.182**

This pull request updates vulkan-loader with versions 1.2.182
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-is-the-policy-for-adding-older-versions-of-a-package

Do you need both the versions added? Or need the oldest and included the newest?
I assume this follows up from https://github.com/conan-io/conan-center-index/pull/6002#issuecomment-865059463?

**Comment by espositofulvio** [comment]
Hi @prince-chrismc,
I just wanted to align the versions for this package with those in vulkan-headers (which I recently updated to 1.2.182 as well). I guess people might still want to use 1.2.176 as that is the version in the latest available vulkan SDK (as I understand, 1.2.182 should become the new SDK version, but am not sure yet).
I must admit I oversaw the old version policy, so this might be a good moment to ask: as I have a few other packages in the pipeline (spirv-tools, glslang, vulkan-validationlayers, and in a few days shaderc as well), should I go just for the latest?

**Comment by prince-chrismc** [comment]
> should I go just for the latest?

Yes, adding older versions takes more resources than it provides benefit. if someone needs an older version they can add it later

**Review by prince-chrismc — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
