### PR TITLE
Add numa support to libx265

### PR DESCRIPTION
**Pull request by theirix**
Specify library name and version:  **libx265/3.4**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jgsogo** [comment]
Sorry, I needed to restart a worker where your job was running (Windows one). Maybe you get an unexpected error message.

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by theirix** [comment]
Some thoughts about linking versioned symbols.

I have experienced a bug when running a test against static libnuma library:
```
conan create . libx265/3.4@ -o libx265:with_numa=True
...
[ 50%] Linking C shared library lib/libtest_library.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/test_library.dir/link.txt --verbose=1
/usr/bin/gcc -fPIC   -m64 -O3 -DNDEBUG   -Wl,-Bsymbolic,-znoexecstack -m64 -shared -Wl,-soname,libtest_library.so -o lib/libtest_library.so CMakeFiles/test_library.dir/test_library.c.o   -L/home/conan/.conan/data/libx265/3.4/_/_/package/29aa233fa6f0aca6bc2c2d245cb48f71eac1fb8b/lib  -L/home/conan/.conan/data/libnuma/2.0.14/_/_/package/76f87539fc90ff313e0b3182641a9bb558a717d2/lib  -Wl,-rpath,/home/conan/.conan/data/libx265/3.4/_/_/package/29aa233fa6f0aca6bc2c2d245cb48f71eac1fb8b/lib:/home/conan/.conan/data/libnuma/2.0.14/_/_/package/76f87539fc90ff313e0b3182641a9bb558a717d2/lib -lx265 -lnuma -lm -lstdc++ -ldl -lpthread
/usr/bin/ld: lib/libtest_library.so: version node not found for symbol numa_alloc_interleaved_subset@libnuma_1.1
/usr/bin/ld: failed to set dynamic section sizes: Bad value
collect2: error: ld returned 1 exit status
```

Library symbols:
```
conan@0faee3890bca:/tmp$ readelf -aW /home/conan/.conan/data/libnuma/2.0.14/_/_/package/76f87539fc90ff313e0b3182641a9bb558a717d2/lib/libnuma.a  | grep numa_alloc_interleaved_subset
    79: 0000000000000c50   140 FUNC    GLOBAL DEFAULT    1 numa_alloc_interleaved_subset_v1
    80: 0000000000000ce0   148 FUNC    GLOBAL DEFAULT    1 numa_alloc_interleaved_subset_v2
   184: 0000000000000c50   140 FUNC    GLOBAL HIDDEN     1 numa_alloc_interleaved_subset_v1_int
   185: 0000000000000ce0   148 FUNC    GLOBAL HIDDEN     1 numa_alloc_interleaved_subset_v2_int
   236: 0000000000000c50   140 FUNC    GLOBAL DEFAULT    1 numa_alloc_interleaved_subset@libnuma_1.1
   237: 0000000000000ce0   148 FUNC    GLOBAL DEFAULT    1 numa_alloc_interleaved_subset@@libnuma_1.2
```

This bug appears only if a dependency with versioned symbols (libnuma) is used as a static library linked into dynamic library. It is the case of the test_package in x265 that produces a shared library. Static linking into executable works fine (no dynamic linker involved). Using libnuma as a shared library linked to shared library works too - ld chose symbols correctly and versioning works well.

I suppose there is a catch in how the linker works with versioned symbols in a static library.
Linker should choose a symbol with version `libnuma_1.2` (It is default and marked with @@) but according to the bug it wants a previous version.



Check matrix:
x265 shared + numa shared = ok
x265 static + numa shared = ok
x265 shared + numa static = fail
x265 static + numa static = fail

So I blacklisted a shared library test for static libnuma.

**Review by jgsogo — APPROVED** [review]
Thanks for the extra documentation

**Comment by SpaceIm** [comment]
I also see this issue with libnuma static in libtorch on Linux. Maybe libnuma default shared value should be True.

**Pull request merged**
