### PR TITLE
log4cxx: add version 1.1.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **log4cxx/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — DISMISSED** [review]
Thanks!

**Comment by RubenRBS** [comment]
Oh I see that there's an old PR adding v2 support, maybe we need to prioritize that before we cab merge this?

**Comment by toge** [comment]
@RubenRBS 
I want to update version fist. 
Then I will add several options as previous PR.

**Review by RubenRBS — APPROVED** [review]
Thanks a lot for going ahead with the v2 support for the new version too, really appreciated :)

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
