### PR TITLE
arrow: add version 18.1.0

### PR DESCRIPTION
**Pull request by amoeba**
### Summary

Changes to recipe:  **arrow/18.1.0**

#### Motivation

This is a minor release which doesn't contain any critical changes but it does include new APIs.

#### Details

Arrow keeps a very clean git history so this compare view is a good overview: https://github.com/apache/arrow/compare/apache-arrow-18.0.0...apache-arrow-18.1.0

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by amoeba** [comment]
CLA signed.

**Comment by wgtmac** [comment]
@AbrilRBS Could you help run the CI? Thanks!

**Comment by toge** [comment]
@amoeba 
Could you add following lines on `patches` section in conandata.yml?
```yaml
  "18.1.0":
    - patch_file: "patches/18.0.0-0001-fix-cmake.patch"
      patch_description: "use cci package"
      patch_type: "conan"
```

**Comment by amoeba** [comment]
Done in https://github.com/conan-io/conan-center-index/pull/26035/commits/7bc5c8526b654328dde091d24bebf9ad71e03742 @toge.

**Review by ErniGH — APPROVED** [review]
LGTM thanks for your effort

**Review by AbrilRBS — APPROVED** [review]

**Comment by amoeba** [comment]
Thanks for the review and quick merge.

**Pull request merged**
