### PR TITLE
krb5: new recipe

### PR DESCRIPTION
**Pull request by valgur**
Adds a recipe for Kerberos 5: https://web.mit.edu/kerberos

Required by `libhdfs3`.

[Packaging status](https://repology.org/project/krb5/versions)

### CODE REVIEW

**Comment by Jihadist** [comment]
@valgur did you see previous attempt #16074 ? Maybe you have ideas how to fix that pr because it can be built with windows but not with linux and I don't see any problem that can cause ownership error

**Comment by valgur** [comment]
@Jihadist I did, but only after creating this PR. Your version looked much more thorough and I should probably merge my version into yours. Unfortunately, I'm on a break from CCI-related development for an indefinite period and currently don't have any plans to continue work on this PR.

**Comment by Jihadist** [comment]
oh, you are the third who wanna add krb5 recipe but left cci development :) maybe the next try will be successful

**Comment by valgur** [comment]
Closing in favor of #16074.

**Pull request closed without merging**
