### PR TITLE
bump azure dependencies

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **azure-storage-cpp**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
What's wrong with cpprestsdk/2.10.18 ? It exists in conancenter

**Comment by jgsogo** [comment]
I've run a job to check if any package was missing, and all of them were available: https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/TapaholesList/272/summary.json, but the computed package-id for that configuration yields a different one `58717fe4a9631e6074c275eb5a7d127e8e0a1a33`.

**Comment by AndreyMlashkin** [comment]
Can I do something on my side?

**Comment by jgsogo** [comment]
Issue comes from here: https://github.com/conan-io/conan-center-index/blob/6a9df2e8a21a1a8466c37645d75cf02a78578f15/recipes/cpprestsdk/all/conanfile.py#L65 

```python
    def package_id(self):
        self.info.requires["boost"].minor_mode()
```

**Comment by uilianries** [comment]
There was a long discussion about that minor version, you can follow here: https://github.com/conan-io/conan-center-index/pull/8856#issuecomment-1011146300

If there is a side effect, we still can revert and try to find another solution.

**Pull request closed without merging**
