### PR TITLE
enable cross compile for foonathan-memory

### PR DESCRIPTION
**Pull request by KristianJerpetjon**
Specify library name and version:  foonathan-memory/7**

Fixing a fixme by removing it ?

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Which recipe?

**Comment by KristianJerpetjon** [comment]
> Which recipe?

this just removed the fixme in an old package that didnt crosscompile

**Comment by SpaceIm** [comment]
> > Which recipe?
> 
> this just removed the fixme in an old package that didnt crosscompile

I mean that looking at the title, it's not obvious which recipe we are going to review ;)
If I see boost, I first need some mental preparation.

**Comment by KristianJerpetjon** [comment]
> > > Which recipe?
> > 
> > 
> > this just removed the fixme in an old package that didnt crosscompile
> 
> I mean that looking at the title, it's not obvious which recipe we are going to review ;) If I see boost, I first need some mental preparation.

Yea sorry .. i was mangling things in the fast-dds pr whilst fixing this. although i have no idea what the unexpected error was.

**Pull request closed without merging**
