### PR TITLE
llvm-openmp: add versions v13, v14, v15, v16 and v17-rc4

### PR DESCRIPTION
**Pull request by valgur**

### CODE REVIEW

**Review by uilianries — COMMENTED** [review]
All those version? 🤔  What about adding only latest for now, then adding other in case someone asks in an issue? Remember that anything from LLVM consumes tons of resources to be built. E.g. I need 1h30 to build llvm-clang a single configuration in my machine and is not a bad a hardware at all.

**Comment by valgur** [comment]
> All those version? 🤔  What about adding only latest for now, then adding other in case someone asks in an issue? Remember that anything from LLVM consumes tons of resources to be built. E.g. I need 1h30 to build llvm-clang a single configuration in my machine and is not a bad a hardware at all. 

It fortunately does not depend on the core llvm components and builds in seconds due to being pure C.

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
I checked locally and they are really small packages.

**Comment by marxin** [comment]
@valgur : About `# All versions except for v11 crash with a segfault for the simple test_package.cpp test`: Have you filled an upstream issue about it? Is it something known by upstream?

**Comment by valgur** [comment]
@marxin No, I have not. Feel free to investigate the issue and report it upstream.

**Comment by marxin** [comment]
I bet it's caused by the following hairy issue: https://github.com/llvm/llvm-project/issues/49923. Apparently, the Apple interest for OpenMP on aarch64 is pretty low :/

**Pull request merged**
