### PR TITLE
wavelet_buffer: add version 0.7.1

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **wavelet_buffer/***

Since 0.7.1, wavelet_buffer requires streamvbyte and fpzip instead of sf_compressor.
These dependent libraries are downloaded and built at build time.
In the future I will make a recipe for each of them and require them.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
@RubenRBS 
I agree with you.
I will make this issue draft until streamvbyte is merged.

**Comment by RubenRBS** [comment]
I've now approved the last one, will make sure both of these PRs are merged before the end of tomorrow, thanks a lot as always @toge :)

**Comment by RubenRBS** [comment]
The related PRs are now merged :)

**Review by RubenRBS — APPROVED** [review]
Thanks! Accepting because the old patch was already present, it just has new code to also remove Catch2 witch seems to be only a test requirement looking at the upstream cmakelist :)

**Review by czoido — APPROVED** [review]

**Pull request merged**
