### PR TITLE
qt/6.x.x: Added missing imageformats plugins

### PR DESCRIPTION
**Pull request by FaerHack**
Specify library name and version:  **qt/6.x.x**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — CHANGES_REQUESTED** [review]
thanks for the contribution. It looks like these 3 plugins are actually part of qtbase and not qtimageformats : qtbase
Can you please move their declaration outside of this `if self.options.get_safe("qtimageformats")` ? Also, please add the jpeg package to `QJpegPlugin`'s `requires`

**Review by ericLemanissier — APPROVED** [review]
Great ! thank you very much

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
CI seems stuck....

You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁

**Comment by prince-chrismc** [comment]
>ERROR: Conflict in libxml2/2.9.14:
    'libxml2/2.9.14' requires 'libiconv/1.17' while 'odbc/2.3.9' requires 'libiconv/1.16'.
    To fix this conflict you need to override the package 'libiconv' in your root package.

https://github.com/conan-io/conan-center-index/pull/11828 was merged

should be good to try again

**Pull request merged**
