### PR TITLE
sole: add package_type

### PR DESCRIPTION
**Pull request by valgur**
### Summary
Changes to recipe:  **lib/[version]**

#### Details

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — COMMENTED** [review]
@valgur just a heads-up. We stopped adding the `package_type` to `header-only` libraries until the new pipeline comes online (Super soon!), as we'll probably need to modify their package_id_mode to avoid missing binaries for them, and we want to do it all at once instead of PR by PR. 

I'll keep yu updated on thatm, but for now the new PRs that _just_ add a header-only package_type we can close (if I close anything that has something else that I miss, please do let me know/reopen!), but either way thanks a lot for taking the time to improve the recipes, we appreciate it!

**Comment by valgur** [comment]
@AbrilRBS Ok, sounds reasonable. I would have liked to see whether this specific one passes or fails in the CI, though, since it's one of the few remaining ones (https://github.com/conan-io/conan-center-index/issues/20992#issuecomment-2370677372) that has been nominally migrated, but has not been successfully built with the v2 pipeline. Mybe you can reopen?

**Comment by AbrilRBS** [comment]
The bot might take a bit to post the results as we're under maintenance currently, but seems to be failing with https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/25395/4-linux-gcc/sole/1.0.2//summary.json

**Comment by AbrilRBS** [comment]
Ping me once it gets fixed so we can try again :)

**Comment by valgur** [comment]
@AbrilRBS I fixed the test_package issues.

**Review by AbrilRBS — APPROVED** [review]

**Review by perseoGI — APPROVED** [review]
LGTM

**Pull request merged**
