### PR TITLE
qt 6.x: fix recipe when gui disabled + bump some dependencies

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

closes https://github.com/conan-io/conan-center-index/issues/5295

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — DISMISSED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by Manu343726** [comment]
The last patch does not solve the issue, there are more options that are deleted when gui is disabled that are later unsafely used by the `requires()` function.

**Comment by ericLemanissier** [comment]
The only one I could find is https://github.com/conan-io/conan-center-index/blob/3385a06cf3854771f6e3a5f22221f496f2fdd6a9/recipes/qt/6.x.x/conanfile.py#L408

**Comment by SpaceIm** [comment]
Correct. I didn't dig into CMake build files of Qt but I think that `self._cmake.definitions["INPUT_opengl"] = self.options.get_safe("opengl", "no")` should be fine.

**Comment by ericLemanissier** [comment]
it works on my machine (the build actually starts, I'm not sure yet about the test recipe...)

**Review by ericLemanissier — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
