### PR TITLE
Bump libdeflate/1.15

### PR DESCRIPTION
**Pull request by SpaceIm**
libdeflate has moved to CMake in 1.15 (instead of raw Makefiles), so I had to move old versions to a dedicated folder.

It will be easier for reviewers to check each commit, because the overall diff doesn't allow to understand whether I've changed stuff in versions before 1.15 (I didn't).

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — DISMISSED** [review]
That's much simpler. Do you think there should be a v1 test package for 1.15 recipe?

**Comment by SpaceIm** [comment]
> Do you think there should be a v1 test package for 1.15 recipe?
Yes, and there is a test v1 package.

**Comment by prince-chrismc** [comment]
image
 

🤔

**Comment by SpaceIm** [comment]
> It will be easier for reviewers to check each commit, because the overall diff doesn't allow to understand whether I've changed stuff in versions before 1.15 (I didn't).

**Review by uilianries — APPROVED** [review]
LGTM

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
