### PR TITLE
mongo-c-driver: add 1.17.6 + bump dependencies

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
ERROR: Binary package not found: 'mongo-c-driver/1.17.3:c2b3cd8e92086b7f3d256639e8271c18abd0788d'
```

Funny

**Comment by SpaceIm** [comment]
@jgsogo why CI tries to download a mongo-c-driver package for 1.17.3?

**Comment by jgsogo** [comment]
> @jgsogo why CI tries to download a mongo-c-driver package for 1.17.3?

The package is already available, so when running `test_package` it needs to download the binary. If you have a closer look at the log output, you will realize the error comes from the `test_package`, not from the build.

Why the error, why it fails to download? I'll have a look at it.

**Comment by jgsogo** [comment]
For some reason, that package in Artifactory is missing the `conanmanifest.txt` file... it thinks that the package is there, but it fails to download.

image

This is something reported upstream, we are working on a way to check package integrity and return `true` only if everything is available.

**Comment by SpaceIm** [comment]
But this PR builds `mongo-c-driver`

**Comment by jgsogo** [comment]
Yes, but we store packages generated during the PR in one temporal Artifactory repository. If you close/open the PR the recipe-revision is the same and the package is found in that Artifactory repository (not in ConanCenter). That's the difference between:

 * CONAN-CENTER: The package is already available in ConanCenter.
 * UPSTREAM: The package is already available in a previous build of this same job (available in the intermediate repository, not in ConanCenter).
 
In both cases, the package won't be built, but the `test_package` will run.

**Review by madebr — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Pull request merged**
