### PR TITLE
gtk 4.1.2

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **gtk/4.1.2**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
blocked by:

- https://github.com/conan-io/conan-center-index/pull/4906
- https://github.com/conan-io/conan-center-index/pull/4905
- https://github.com/conan-io/conan-center-index/pull/4904
- https://github.com/conan-io/conan-center-index/pull/4903

**Review by mathbunnyru — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by ericLemanissier** [comment]
it is not blocked any more!

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
no idea why was it blocked, but I have no objections

**Comment by ericLemanissier** [comment]
it was blocked because of missing binaries for requirements, but it's not the case any more

**Pull request merged**
