### PR TITLE
octo-logger-cpp: update checksum for 1.12.0

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **octo-logger-cpp/1.12.0**

#### Motivation
tar ball of 1.12.0 is updated.

#### Details

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by jcar87 — CHANGES_REQUESTED** [review]
Thanks @toge! 

Leaving this pending internal verification - hopefully we are able to compare the changes against a backed up copy of the original file contents.

Please note that we will not accept checksum changes without verifying what changed - if we did, we may as well not use checksums at all!

**Review by RubenRBS — COMMENTED** [review]
Changed code

```diff
diff -bur old new
diff --color=auto -bur old/src/aws/cloudwatch-sink.cpp new/src/aws/cloudwatch-sink.cpp
--- old/src/aws/cloudwatch-sink.cpp	2024-06-13 08:08:09
+++ new/src/aws/cloudwatch-sink.cpp	2024-06-16 08:04:14
@@ -83,6 +83,22 @@
     if (std::find(existing_log_streams_.begin(), existing_log_streams_.end(), log_stream_name) ==
         existing_log_streams_.end())
     {
+        Aws::CloudWatchLogs::Model::DescribeLogStreamsRequest describe_log_streams;
+        describe_log_streams.SetLogGroupName(log_group_name_.c_str());
+        describe_log_streams.SetLogStreamNamePrefix(log_stream_name.c_str());
+        auto const describe_outcome = aws_cloudwatch_client_->DescribeLogStreams(describe_log_streams);
+        if (describe_outcome.IsSuccess())
+        {
+            const auto& log_streams = describe_outcome.GetResult().GetLogStreams();
+            for (const auto& log_stream : log_streams)
+            {
+                if (log_stream.GetLogStreamName() == log_stream_name)
+                {
+                    existing_log_streams_.insert(log_stream_name);
+                    return;
+                }
+            }
+        }
         Aws::CloudWatchLogs::Model::CreateLogStreamRequest create_log_stream;
         create_log_stream.WithLogGroupName(log_group_name_.c_str()).WithLogStreamName(log_stream_name.c_str());
         auto const outcome = aws_cloudwatch_client_->CreateLogStream(create_log_stream);
```

**Comment by jcar87** [comment]
Please note that it 1.12.0 does *not* appear to be a release _yet_: https://github.com/ofiriluz/octo-logger-cpp/releases

so maybe the maintainers are updating the tag until it is. 

furthermore, this is the second time we have a checksum issue: https://github.com/conan-io/conan-center-index/pull/24308

I can see that this will continue being a problem until 1.12.0 is actually released. Under what conditions was 1.12.0 considered a release? The presence of the tag?

**Comment by toge** [comment]
@jcar87 @RubenRBS 
Thank you for your deep dive.

I have updated this recipe as the 1.12.0 tag has been added.
I understand that this is an inconvenient situation for cci.
I will keep the use of 1.12.0 in my private environment.
Is there any way to make this clear to users that it will be difficult to use 1.12.0 on cci until an official release is made?

**Comment by jcar87** [comment]
> Is there any way to make this clear to users that it will be difficult to use 1.12.0 on cci until an official release is made?

Thanks @toge ! We can probably invalidate all packages in the `validate()` method and point users to use an older version? Until a new recipe revision is published that has the actual release.
Or we can publish these as `1.12.0-pre1` etc - but point to the actual commit rather than the 1.12.0 tag - but the `1.12.0` will still remain published

Any ideas @RubenRBS ??

**Comment by perseoGI** [comment]
I suggest removing support for this version as v2.0.0 https://github.com/conan-io/conan-center-index/pull/24743 has been released and it is getting merged soon.

**Comment by toge** [comment]
Oh, I forget my old work.
Let's close it.

**Pull request closed without merging**
