### PR TITLE
openal: deprecate in favor of openal-soft + download official tarballs + modernize more

### PR DESCRIPTION
**Pull request by SpaceIm**
see https://github.com/conan-io/conan-center-index/pull/15716

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — DISMISSED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — DISMISSED** [review]

**Comment by SpaceIm** [comment]
😩

**Comment by SpaceIm** [comment]
16 hours to build & run test package, seriously?

**Comment by SpaceIm** [comment]
I've added an extra modification: deprecation of this recipe in favor of `openal-soft` recipe (https://github.com/conan-io/conan-center-index/pull/15716)

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
image

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
