### PR TITLE
open62541: add version 1.4.6

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **open62541/1.4.6**

#### Motivation
Try to close https://github.com/conan-io/conan-center-index/issues/25585.

#### Details
https://github.com/open62541/open62541/compare/v1.3.9...v1.4.6

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by AbrilRBS** [comment]
@toge you might be missing bcrypt system_lib for the new version under Windows for the current compilation issue?

**Comment by toge** [comment]
@AbrilRBS 
Thank you for your advice.
I solved this issue to include "iphlpapi.h".
I will try to create PR for upstream.

**Review by AbrilRBS — APPROVED** [review]

**Comment by ErikTempelaarVO** [comment]
Hey, @toge, thanks for updating this recipe.
Unfortunately, it doesn't work for me on MinGW Windows.

I believe the new patch is the culprit, because locally I can compile open62541 v1.4.6 just fine.

```
#if defined(_WIN32)
#  include <winsock2.h>
#  include <iphlpapi.h>
#endif
```

When I apply the patch the build breaks. Maybe this patch is too generic?
I guess it should only apply to builds with MSVC, and not any other _WIN32?

Any thoughts, @toge @AbrilRBS ?

**Comment by ErikTempelaarVO** [comment]
According to this [issue](https://github.com/open62541/open62541/issues/6423)
one should #include windows.h (that will #include winbase.h and that contains the declaration)

I manually changed the existing 0004-include-iphlpapi.patch to:
```
diff --git a/src/ua_util.c b/src/ua_util.c
index 13eb0fb..d832f0a 100644
--- a/src/ua_util.c
+++ b/src/ua_util.c
@@ -11,6 +11,10 @@
  * unit for the generated code from UA_INLINABLE definitions. */
 #define UA_INLINABLE_IMPL 1
 
+#if defined(_WIN32)
+//#  include <winsock2.h>
+#  include <windows.h>
+#endif
 #include <open62541/types_generated_handling.h>
 #include <open62541/util.h>
 

```

Exported the library into my local cache and was able to successfully build in MinGW via conan

**Pull request merged**
