### PR TITLE
mbedtls: add version 3.3.0, remove unused CMakeLists.txt

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **mbedtls/3.3.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — DISMISSED** [review]

**Comment by toge** [comment]
```
  File "/home/conan/w/prod/BuildSingleReference/.conan/data/mbedtls/3.3.0/_/_/build/be27726f9885116da1158027505be62e913cd585/src/library/../scripts/generate_driver_wrappers.py", line 29, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

mbedtls/3.3.0 requires jsonschema python module.
I'm going to use cpython package.

**Comment by robiwano** [comment]
What is the status of this PR?

**Comment by prince-chrismc** [comment]
> What is the status of this PR?

You are more then welcomed to fork this PR and open a new one if you'd like to continue it :)

**Comment by toge** [comment]
I can't find the way to install extra python modules to generate driver codes on MacOS.
I temporary disable MacOS support.

**Pull request closed without merging**
