### PR TITLE
- [automake] bump autoconf to 2.71

### PR DESCRIPTION
**Pull request by SSE4**
Specify library name and version:  **automake/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Comment by SpaceIm** [comment]
@SSE4 Could you take advantage of this PR to bump msys2 and use strip_root in tools.get?

**Review by Croydon — APPROVED** [review]

**Review by mathbunnyru — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
I've read that 20% of projects based on autotools in Debian are not compatible with autoconf 2.71. Since build requirements can't be overriden, how to deal with issues like https://github.com/conan-io/conan-center-index/issues/5707?

**Comment by madebr** [comment]
I"m trying to reproduce your problem.
What needs to be changed to the recipes below to make your problem appear?
```
cat >conanfile_autoconf.py <<EOF
from conans import ConanFile
class FakeAutoconfConan(ConanFile):
  name = "fake-autoconf"
EOF
cat >conanfile_dep1.py <<EOF
from conans import ConanFile
class FakeDep1Conan(ConanFile):
  name = "fake-dep1"
  build_requires = "fake-autoconf/2.69"
  def build(self):
    if self.deps_cpp_info["fake-autoconf"].version != "2.69":
      raise ConanInvalidConfiguration("fake-autoconf MUST be of version 2.69")
EOF
cat >conanfile_dep2.py <<EOF
from conans import ConanFile
class FakeDep2Conan(ConanFile):
  name = "fake-dep2"
  build_requires = "fake-autoconf/2.71"
  def build(self):
    if self.deps_cpp_info["fake-autoconf"].version != "2.71":
      raise ConanInvalidConfiguration("fake-autoconf MUST be of version 2.71")
EOF
cat >conanfile_master.py <<EOF
from conans import ConanFile
class FakemasterConan(ConanFile):
  name = "fake-master"
  requires = "fake-dep1/0.1", "fake-dep2/0.1"
EOF
conan remove fake-autoconf -f
conan remove fake-dep1 -f
conan remove fake-dep2 -f
conan remove fake-master -f
conan export conanfile_autoconf.py fake-autoconf/2.69@
conan export conanfile_autoconf.py fake-autoconf/2.71@
conan export conanfile_dep1.py fake-dep1/0.1@
conan export conanfile_dep2.py fake-dep2/0.1@
conan create conanfile_master.py fake-master/0.1@ --build=*
```

**Comment by SSE4** [comment]
> I've read that 20% of projects based on autotools in Debian are not compatible with autoconf 2.71. Since build requirements can't be overriden, how to deal with issues like #5707 where we need to call autoreconf, libtool is in build requirement (which drags automake, autoconf & m4) but we can't override autoconf version?

this is a fundamental and hard question in general. should we update everything to the bleeding edge, especially, if old software wasn't ever tested against these newly released tools/libraries

**Comment by SpaceIm** [comment]
> I"m trying to reproduce your problem.
> What needs to be changed to the recipes below to make your problem appear?
> 
> ```
> cat >conanfile_autoconf.py <<EOF
> from conans import ConanFile
> class FakeAutoconfConan(ConanFile):
>   name = "fake-autoconf"
> EOF
> cat >conanfile_dep1.py <<EOF
> from conans import ConanFile
> class FakeDep1Conan(ConanFile):
>   name = "fake-dep1"
>   build_requires = "fake-autoconf/2.69"
>   def build(self):
>     if self.deps_cpp_info["fake-autoconf"].version != "2.69":
>       raise ConanInvalidConfiguration("fake-autoconf MUST be of version 2.69")
> EOF
> cat >conanfile_dep2.py <<EOF
> from conans import ConanFile
> class FakeDep2Conan(ConanFile):
>   name = "fake-dep2"
>   build_requires = "fake-autoconf/2.71"
>   def build(self):
>     if self.deps_cpp_info["fake-autoconf"].version != "2.71":
>       raise ConanInvalidConfiguration("fake-autoconf MUST be of version 2.71")
> EOF
> cat >conanfile_master.py <<EOF
> from conans import ConanFile
> class FakemasterConan(ConanFile):
>   name = "fake-master"
>   requires = "fake-dep1/0.1", "fake-dep2/0.1"
> EOF
> conan remove fake-autoconf -f
> conan remove fake-dep1 -f
> conan remove fake-dep2 -f
> conan remove fake-master -f
> conan export conanfile_autoconf.py fake-autoconf/2.69@
> conan export conanfile_autoconf.py fake-autoconf/2.71@
> conan export conanfile_dep1.py fake-dep1/0.1@
> conan export conanfile_dep2.py fake-dep2/0.1@
> conan create conanfile_master.py fake-master/0.1@ --build=*
> ```

Do you try to reproduce build requirement versions conflict issue?

Here is the issue:

- automake is a requirement of libtool
- autoconf 2.71 is a requirement of automake
- a recipe has libtool in build requirement. autoconf 2.69 can't be a build requirement of this recipe, otherwise conan complains about autoconf version conflict between 2.69 and 2.71. It seems that top level recipe can't override versions of build requirement graph.

**Comment by madebr** [comment]
@SpaceIm 
> Do you try to reproduce build requirement versions conflict issue?

Yes. This is an issue with conan so let's create a small reproducer to fix the issue.
If this gets fixed, we can keep using older autoconf releases where needed.

**Pull request merged**
