### PR TITLE
[cpptrace] Add v0.3.0

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Specify library name and version:  **cpptrace/0.3.0**

I'm the author, this is the next release.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]
Looks nice, thanks a lot :)

**Review by ericLemanissier — APPROVED** [review]

**Comment by jeremy-rifkin** [comment]
Apologies, I had to alter the tag upstream. Should be good to go now :)

**Review by uilianries — APPROVED** [review]
LGTM

**Review by RubenRBS — APPROVED** [review]
Thanks for keeping it up to date Jeremy :)

**Pull request merged**
