### PR TITLE
[new revision] NDK r22

### PR DESCRIPTION
**Pull request by dmn-star**
Specify library name and version: android-ndk/r22

@a4z

https://github.com/android/ndk/wiki/Changelog-r22

  I've read the guidelines for contributing.
  I've followed the PEP8 style guides for Python code in the recipes.
  I've used the latest Conan client version.
  I've tried at least one configuration locally with the
conan-center hook activated.

### CODE REVIEW

**Review by mathbunnyru — DISMISSED** [review]

**Comment by a4z** [comment]
Thanks for the ping, happy to have clang11 now!

**Review by a4z — APPROVED** [review]

**Review by uilianries — DISMISSED** [review]

**Comment by a4z** [comment]
@dmn-star could you please add this

```
        self.output.info('Creating ANDROID_NDK_HOME environment variable: %s' % self.package_folder)
        self.env_info.ANDROID_NDK_HOME = self.package_folder
```

into the recipe, package info ? Around Line 158 
Those lines got lost in the history of changes in the 1  PR, and I just noticed I added them back on my local version because there are situations where you need to know the package root

**Comment by dmn-star** [comment]
@a4z done.

**Review by a4z — APPROVED** [review]
Thanks!

**Review by mathbunnyru — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by SpaceIm — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
