### PR TITLE
sdl_mixer/all: migrate to Conan v2

### PR DESCRIPTION
**Pull request by valgur**
Linking in test_package currently fails for GCC due to #12826.

### CODE REVIEW

**Comment by valgur** [comment]
Closing temporarily to avoid unnecessary load on the CI. Will reopen when I'm actively working on the PR again.

**Review by RubenRBS — APPROVED** [review]

**Comment by RubenRBS** [comment]
Regenerating binaries now

**Comment by RubenRBS** [comment]
Some missing symbols in v2 seem to point to a (few?) missing requirement traits @valgur :)

**Comment by RubenRBS** [comment]
Any idea why v1 has those missing symbols?

**Comment by valgur** [comment]
Don't close.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by AbrilRBS — APPROVED** [review]

**Pull request merged**
