### PR TITLE
libdeflate: improve mingw support

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **libdeflate/1.7**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

`mingw32-make` fails if no shell is available since libdeflate's Makefike calls several commands in a shell.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by dmn-star** [comment]
I know this is a special case of special cases but these changes will make the Android build on windows no longer possible.

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
> 
> 
> I know this is a special case of special cases but these changes will make the Android build on windows no longer possible.

Which part would break android build? `tools.unix_path` on make program?

**Comment by dmn-star** [comment]
> self.build_requires("msys2/20200517")

libdeflate/1.7: Not found in local cache, looking in remotes...
libdeflate/1.7: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [3.95k]
Downloading conan_export.tgz completed [0.25k]
Decompressing conan_export.tgz completed [0.00k]
libdeflate/1.7: Downloaded recipe revision 0
libdeflate/1.7: Forced build from source
msys2/20200517: Not found in local cache, looking in remotes...
msys2/20200517: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [3.87k]
Downloading conan_export.tgz completed [0.34k]
Decompressing conan_export.tgz completed [0.00k]
**msys2/20200517: Downloaded recipe revision 0
ERROR: msys2/20200517: Invalid configuration: Only Windows supported**

**Comment by dmn-star** [comment]
But not so important Conan and windows generally don't get along. :-)

**Comment by SpaceIm** [comment]
Because you don't use 2 profiles I guess.

**Comment by dmn-star** [comment]
Because is windows :-) if tools.os_info.is_windows

Configuration (profile_host):
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=9
os=Android
os.api_level=21
[options]
[build_requires]
*: android-ndk/r21d, cmake/3.19.0, ninja/1.10.1
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]

**Comment by SpaceIm** [comment]
`msys2` shouldn't raise in this case, because it's part of build machine requirements.

**Comment by dmn-star** [comment]
1) libdeflate/1.7: Forced build from source
msys2/20200517: Not found in local cache, looking in remotes...
msys2/20200517: Trying with 'conan-center'...

All below is true
>def build_requirements(self):
    if tools.os_info.is_windows and self.settings.compiler != "Visual Studio" and \
       not tools.get_env("CONAN_BASH_PATH"):
        self.build_requires("msys2/20200517")

2) msys2 raise because Android os is detected

**Comment by dmn-star** [comment]
>but maybe there is something wrong in msys2 recipe

or cross compiling is broken for the build requirements.

**Comment by SpaceIm** [comment]
Could you open an issue with exact conan command and profiles please? Someone more familiar with cross compilation in conan could answer.
This pattern is very common in recipes based on Autotools.

**Comment by dmn-star** [comment]
I can do. 

> self.settings.compiler != "Visual Studio"

If I use clang (Windows), then I don't need msys2 either. Right?

**Pull request merged**
