### PR TITLE
libjxl: disable linking static libgcc and libstdc++

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **libjxl/***

#### Motivation
In some environments, there are compilation errors in static build.
It seems to be caused by linking static libgcc and libcstdc++.
This PR tries to fix it.

#### Details
Compilation error message are following:
```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
CMake Error at cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake-3.28/Modules/FindThreads.cmake:226 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:170 (find_package)
```

After applying this PR.
```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Using -lpthread as --whole-archive
```

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by valgur — APPROVED** [review]
Thanks!

**Comment by jcar87** [comment]
Hi @toge - thanks for your contribution.

> In some environments, there are compilation errors in static build.

When this recipe was last built on CI (Linux, gcc11, shared=False), [build log here](https://c3i.jfrog.io/c3i/misc-v2/logs/pr/18812/4-linux-gcc/libjxl/0.10.2//4ce43b2cd05eb16eaa16c4e1031d383741ed92f2-build.txt)  there were no failures related to this. Could you provide more details as to which environments are problematic?


I suspect the problem with this recipe is actually this line:
https://github.com/conan-io/conan-center-index/blob/d8515e82deeb27522b67549ba3237e99c6f55287/recipes/libjxl/all/conanfile.py#L95

which should always be set to off. That variable applies to the tools (the executables), rather than the libraries: https://github.com/libjxl/libjxl/blob/main/CMakeLists.txt#L151-L152

Setting this to off would prevent this:
```
-- Using -lpthread as --whole-archive
```

The variable that controls static/shared libraries in CMake's conventional `BUILD_SHARED_LIBS`, as per https://github.com/libjxl/libjxl/blob/main/CMakeLists.txt#L97

**Review by jcar87 — CHANGES_REQUESTED** [review]
Please set `JPEGXL_STATIC` to `OFF` instead, which applies to the executables and only refers to the runtime. The upstream project sets this to off by default, and it is taken to mean something like "use static runtime in tool executables", and is unrelated to whether the libraries are being built shared or statically.

**Comment by toge** [comment]
@jcar87 
Thank you for your detail investigation!
I don't understand the meaning of JPEGXL_STATIC.
Thank you very much.

**Review by jcar87 — DISMISSED** [review]

**Review by AbrilRBS — DISMISSED** [review]

**Review by AbrilRBS — APPROVED** [review]
I've removed the old 0.6.1 instead of removing the extra libraries it was creating so that we could remove some noise in the recipe :) Thanks a lot @toge for addressing this one quickly :)

**Review by jcar87 — APPROVED** [review]

**Pull request merged**
