### PR TITLE
[pybind11/2.9.2] Add pybind11 2.9.2

### PR DESCRIPTION
**Pull request by vectorsli**
Specify library name and version:  **pybind11/2.9.2**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
> The Eric's already listed some related issues, but according to pybind11, it's a bug: [pybind/pybind11#3081](https://github.com/pybind/pybind11/issues/3081)
> 
> Very interesting, not first time we have it: #9492

so, is there anything we can do about it? can we at least just raise `ConanInvalidConfiguration` for these broken/buggy combinations?

**Comment by uilianries** [comment]
@SSE4 Yes, I think we can restrict those failed combinations and point the issue link

**Comment by SSE4** [comment]
> @SSE4 Yes, I think we can restrict those failed combinations and point the issue link

nice, can you make such a PR?

**Comment by uilianries** [comment]
@SSE4 Yes, I'll do

**Comment by cqc-alec** [comment]
Are we sure that the issue is in fact a bug in pybind11 and not https://github.com/conan-io/conan-center-index/issues/6605 (which is a possible cause of https://github.com/pybind/pybind11/issues/3081 )?

**Review by uilianries — APPROVED** [review]

**Pull request merged**
