### PR TITLE
qt 6.3.0

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **qt/6.3.0**

closes conan-io/conan-center-index#10050
fixes conan-io/conan-center-index#10174

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
so, it errors with `qtbase/src/corelib/text/qlocale_tools.cpp:57:10: fatal error: 'charconv' file not found` on linux clang with libstdc++.
According to https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017, charconv was implemented in libstdc++ 8.1
I think there is no way to put a restriction on libstdc++'s version right ?

**Comment by ericLemanissier** [comment]
blocked by:

- https://github.com/conan-io/conan-center-index/pull/10279

**Comment by PatSche** [comment]
> I think there is no way to put a restriction on libstdc++'s version right ?

Unfortunately, I don't know how to check the `libstdc++` version directly in a Conan recipe - which would certainly be the most elegant way. 

However, the CI system uses an Ubuntu 18.04 container for the tests and for this Ubuntu version there is a [`libstdc++-8-dev`](https://packages.ubuntu.com/bionic/amd64/libstdc++-8-dev/filelist) package, which should solve the problem. 

I.e. with the following added code, you could make the recipe compatible with Ubuntu 18.04:

```py
    def system_requirements(self):
        packages = None
        self.output.info("distro: " + os_info.linux_distro + "; version: " + os_info.os_version)
        if tools.os_info.is_linux and self.settings.os == "Linux":
            # Install libstdc++ > 8.1.0 or (for standard library header <charconv>)")
            if os_info.linux_distro == "ubuntu" and os_info.os_version == "18.04":
                packages = ["libstdc++-8-dev"]
        if packages:
            package_tool = tools.SystemPackageTool(conanfile=self, default_mode='verify')
            for p in packages:
                package_tool.install(update=True, packages=p)
```

**Comment by ericLemanissier** [comment]
It's not possible, because SystemPackageTool is allowed only in system package (`foo/system`). This fix would have to be applied at the source directrly during creation of the docker images used by CCI.

**Comment by PatSche** [comment]
> It's not possible, because SystemPackageTool is allowed only in system package (`foo/system`). This fix would have to be applied at the source directrly during creation of the docker images used by CCI.

Ah, too bad. It looked so simple at first glance.

**Review by uilianries — APPROVED** [review]

**Review by PatSche — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@madebr @SpaceIm @jgsogo @intelligide @toge May I ask you for a final review ? The CI status is pending, but all builds have been reported as successful 3 days ago.

**Review by madebr — APPROVED** [review]

**Pull request merged**
