### PR TITLE
glfw: fix regressions introduced by #20913

### PR DESCRIPTION
**Pull request by SpaceIm**
- do not required xorg if not Linux or FreeBSD (regression of https://github.com/conan-io/conan-center-index/pull/20913)
- update required_conan_version due to host_version in build requirements
- fix version comparison in CMake variables logic
- do not add wayland in build requirements if 1 profile

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
I think there is place for improvement in this new wayland branch (it's suspicious to see wayland-protocols in requirements instead of build requirements, and I suspect that patches could be simplified) but it can be done in another PR.

**Comment by jwillikers** [comment]
> I think there is place for improvement in this new wayland branch (it's suspicious to see wayland-protocols in requirements instead of build requirements, and I suspect that patches could be simplified) but it can be done in another PR.

The wayland-protocols can be made a `tool_requires` by adding `pkg_config_deps.build_context_activated = ["wayland-protocols"]`, but single profile builds still need to be taken into account.

**Comment by SpaceIm** [comment]
Yes, build_context_activated can't work with 1 profile. I have a workaround for this in opencv/4.8.1 recipe (hopefully merged soon): https://github.com/conan-io/conan-center-index/blob/50b5d9d83384dac02cc7597a4b6b4a6078cc7875/recipes/opencv/4.x/conanfile.py#L1275-L1290

**Comment by jwillikers** [comment]
> Yes, build_context_activated can't work with 1 profile. I have a workaround for this in opencv/4.8.1 recipe (hopefully merged soon) so that you don't have to put wayland-protocols in requirements even for 1 profile:
> 
> https://github.com/conan-io/conan-center-index/blob/50b5d9d83384dac02cc7597a4b6b4a6078cc7875/recipes/opencv/4.x/conanfile.py#L1105-L1107
> 
> https://github.com/conan-io/conan-center-index/blob/50b5d9d83384dac02cc7597a4b6b4a6078cc7875/recipes/opencv/4.x/conanfile.py#L1212-L1217
> 
> https://github.com/conan-io/conan-center-index/blob/50b5d9d83384dac02cc7597a4b6b4a6078cc7875/recipes/opencv/4.x/conanfile.py#L1551-L1555
> 
> https://github.com/conan-io/conan-center-index/blob/50b5d9d83384dac02cc7597a4b6b4a6078cc7875/recipes/opencv/4.x/conanfile.py#L1275-L1290

Thanks. It'll be nice to finally have a consistent way of handling that, even if it isn't the prettiest.

Thanks for submitting this PR to fix my mess!

**Review by jwillikers — APPROVED** [review]

**Comment by jwillikers** [comment]
> No problem, I've pushed another commit in order to move wayland-protocols to build requirements. I don't have access to a Linux machine currently, so if someone could test, I would appreciate.

I've tested building 3.3.8 and 3.3.2 with Wayland enabled it works.

**Review by jwillikers — APPROVED** [review]

**Comment by RubenRBS** [comment]
Thanks a lot @SpaceIm and @jwillikers for your work on this one. Some of the more glaring regressions should have been caught the first time around, sorry about that

**Review by uilianries — APPROVED** [review]

**Pull request merged**
