### PR TITLE
Flatbuffers flatc integration

### PR DESCRIPTION
**Pull request by mjvankampen**
Specify library name and version:  **flatbuffers/1.12.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Not fully up to pep8 as long lines and not sure if fully idiomatic Python. I don't program Python that often, please leave your comments.

This PR adds flatc to flatbuffers. It should not impact existing users of the package I believe. You would use it by including flatbuffers as a require and build_require. Ref. https://github.com/conan-io/conan/issues/7414 (which is not a bug :-))

### CODE REVIEW

**Comment by mjvankampen** [comment]
I think the options_from_context doesn't work if you are not using --profile:build and --profile:host as it does not detect the third case (build==host) and does not enable flatc and flatbuffers.

**Review by uilianries — CHANGES_REQUESTED** [review]
There is a specific package for flatc: https://conan.io/center/flatc

Please, try use both flatbuffers and flatc. If it does not solve your problem, please open an issue reporting the package: https://github.com/conan-io/conan-center-index/issues

**Comment by mjvankampen** [comment]
#3361

**Comment by Croydon** [comment]
I think @mjvankampen is right.

We did separate binaries and libraries and in the past for cross-compiling reasons, but that shouldn't be necessary anymore, hence I believe that flatc should be merged into flatbuffers and then the flatc package should be deprecated in favour of the flatbuffers one.

**Review by madebr — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
