### PR TITLE
restinio: add 0.6.19

### PR DESCRIPTION
**Pull request by gegles**
Specify library name and version:  **restinio/0.6.19**

Just a regular version update to add the latest.
---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by gegles** [comment]
> @gegles Cloud you update fmt and pcre2?

@toge Done, see [24c5a8c](https://github.com/conan-io/conan-center-index/pull/19259/commits/24c5a8c46db707f2fa8b1001353351c278eebc2c). I've also switched these deps to using version ranges so there is no need to override upstream in the future.

**Comment by toge** [comment]
@gegles 
Thanks a lot!
But conan center index don't allow using version ranges except openssl and cmake.
Please refer: https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges

**Comment by gegles** [comment]
> @gegles Thanks a lot! But conan center index don't allow using version ranges except openssl and cmake. Please refer: https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges

Thanks for the info, I had missed that!

I've now updated the versions explicitly and removed the ranges.

**Comment by toge** [comment]
@gegles 
Thank you for your quick response!

**Review by toge — APPROVED** [review]

**Comment by gegles** [comment]
@prince-chrismc @czoido this is one is now ready to be merged. It's just a bit more than a version bump so it did not get picked up for auto merge... Thanks in advance! 🙏🏻 😉 !

**Review by toge — APPROVED** [review]

**Review by czoido — APPROVED** [review]

**Comment by czoido** [comment]
> @prince-chrismc @czoido this is one is now ready to be merged. It's just a bit more than a version bump so it did not get picked up for auto merge... Thanks in advance! 🙏🏻 😉 !

Thanks for the contribution @gegles !

**Review by RubenRBS — APPROVED** [review]

**Comment by gegles** [comment]
Thanks @czoido  and @RubenRBS!

@prince-chrismc, we just need one more 😉

**Pull request merged**
