### PR TITLE
libiconv: apply x86 resource patch

### PR DESCRIPTION
**Pull request by cyberflashguru**
**libiconv/1.17**

Create a patch to resolve this x86 libiconv build error:

`libiconv.res.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'`

Close https://github.com/conan-io/conan-center-index/issues/20689

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi @Subash-Lamichhane thanks a lot for your contribution! Make sure to submit access [in the request access issue](https://github.com/conan-io/conan-center-index/issues/4) for the PR to be able to get merged, thanks!

**Comment by docbrown1955** [comment]
Hello, any news on this PR ? I encountered the same issue with libiconv.

**Comment by uilianries** [comment]
Friendly ping @cyberflashguru ! We want to accept your PR, but first you need to be listed in the allowed users list. Could please ask for access in the issue #4

More information about CCI process: https://github.com/conan-io/conan-center-index/tree/master/docs/adding_packages#one-request-access

**Comment by uilianries** [comment]
@docbrown1955 Currently, this PR is blocked due authorization. In case the author does not want to continue, you could open a second PR with same changes.

**Comment by cyberflashguru** [comment]
> @docbrown1955 Currently, this PR is blocked due authorization. In case the author does not want to continue, you could open a second PR with same changes.



> @docbrown1955 Currently, this PR is blocked due authorization. In case the author does not want to continue, you could open a second PR with same changes.

https://github.com/conan-io/conan-center-index/issues/4#issuecomment-1814350068

**Comment by cyberflashguru** [comment]
> Hi @Subash-Lamichhane thanks a lot for your contribution! Make sure to submit access [in the request access issue](https://github.com/conan-io/conan-center-index/issues/4) for the PR to be able to get merged, thanks!

Who is @Subash-Lamichhane? Did you mean [cyberflashguru](https://github.com/cyberflashguru)? Thanks.

**Comment by docbrown1955** [comment]
> @docbrown1955 Currently, this PR is blocked due authorization. In case the author does not want to continue, you could open a second PR with same changes.

@uilianries Thanks, although it seems good now ?

**Comment by uilianries** [comment]
@cyberflashguru Thank you for your fix! Have you communicated the upstream about that bug? Please, inform the upstream about the case, so we don't need to patch future versions too.

In https://www.gnu.org/software/libiconv/ you can find:

```
Bug reports
Bug reports should be sent to bug-gnu-libiconv@gnu.org.
```

**Comment by cyberflashguru** [comment]
Added a bug report to bug-gnu-libiconv@gnu.org. Thanks.
https://lists.gnu.org/archive/html/bug-gnu-libiconv/2023-11/msg00005.html

**Comment by uilianries** [comment]
@cyberflashguru Thank you for reporting the upstream!

**Review by uilianries — APPROVED** [review]
LGTM

**Review by toge — APPROVED** [review]

**Pull request merged**
