### PR TITLE
libgpiod: Update to conan v2

### PR DESCRIPTION
**Pull request by ashley-b**
Specify library name and version:  **libgpiod/1.6.3**

Conan v2 update of libgpiod recipe

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi @ashley-b thanks a lot for your contribution! The changes look good, I've pushed some minor things.

For future maintenance: I've tested that the two recipe options seem to work ok as far as I can tell :)

**Review by RubenRBS — APPROVED** [review]

**Comment by Tobulus** [comment]
https://github.com/conan-io/conan-center-index/pull/18171

This was already open for half a month. I don't get the order the team is reviewing pull requests. The bot above also mentions that there is existing work on this lib ...

**Comment by ashley-b** [comment]
@Tobulus Apologies, I missed this work had been started

**Comment by Tobulus** [comment]
@ashley-b I don't blame you. :) Can you check whether the PRs are basically the same? Then I would close mine, as this one is already reviewed once.

**Comment by ashley-b** [comment]
@Tobulus Am also happy to close mine.
They basically look the the same. I did rename the pc file to match linux distro naming

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
