### PR TITLE
libmysqlclient: Fix FreeBSD

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **libmysqlclient/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/9350 also fixes FreeBSD

**Comment by ericLemanissier** [comment]
yes, but FreBSD is broken even with your PR. it requires libunwind.

**Comment by ericLemanissier** [comment]
This PR solves this error: https://github.com/ericLemanissier/conan-center-index/runs/5462356927?check_suite_focus=true#step:3:18002
```
/root/.conan/data/libmysqlclient/8.0.25/_/_/build/8a8358db748f21fb263fbe9fd5d357ca61d3e9c0/source_subfolder/mysys/stacktrace.cc:72:10: fatal error: 'libunwind.h' file not found
#include <libunwind.h>
```

cf:

- https://github.com/mysql/mysql-server/blob/8.0/configure.cmake#L84
- https://github.com/mysql/mysql-server/blob/8.0/mysys/stacktrace.cc#L73

**Comment by ericLemanissier** [comment]
this PR passes on FreeBSD : https://github.com/ericLemanissier/conan-center-index/runs/5462555278?check_suite_focus=true#step:3:20107

**Pull request closed without merging**
