### PR TITLE
make it possible to delete diligent-tools patches

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **diligent-tools/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
@jgsogo @prince-chrismc I have a challange here.

diligent-tools tries to install some python package via pip:
https://github.com/DiligentGraphics/DiligentTools/blob/e604522a83d2186f9df823515751c8034b7fb7e8/RenderStateNotation/CMakeLists.txt#L26

As I understand, it it forbidden in conan CI. At least, previous builds failed because of it.
As I see, they are required in some other python build scripts.

Is it possible to get/import these packages via conanfile?

**Comment by uilianries** [comment]
@AndreyMlashkin No way. If libclang need to be installed as mandatory dependency, I would say to take a look on llvm-core package, otherwise, it will need a new package.

Pip will install other packages, but Conan will not but able to manage it, it will affect the package it, but we have no hint about it.

In the very very past, I did a workaround involving Conan + pip, using `pip.main()`. But still, is not something to be used here. Sorry.

**Comment by AndreyMlashkin** [comment]
I will remove adding of a new version for now

**Comment by AndreyMlashkin** [comment]
@uilianries @SSE4 @ericLemanissier @prince-chrismc 
please approve

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
