### PR TITLE
libcurl: Add 8.7.1

### LINKED ISSUE #23295: [request] libcurl 8.7.1
### What is your problem/feature request?

https://curl.se/download/curl-8.7.1.tar.gz

### PR DESCRIPTION
**Pull request by Ahajha**
Specify library name and version:  **libcurl/8.7.1**

Resolves #23295 

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — COMMENTED** [review]
I see that from our latest version, there's the new Cmake `USE_OPENSSL_QUIC`, and that `ENABLE_CURL_MANUAL` has changed default to true.
I think it'd be nice to ensure that `ENABLE_CURL_MANUAL` is set to false if we're remocing the docs (Not that I think they could get built if they seem to require Perl).

Does it make sense to have the new option also available? wdyt? Thanks!

**Comment by jcar87** [comment]
> USE_OPENSSL_QUIC

I'd leave it as default to off outside of this PR - it requires an additional dependency which we don't currently have (`nghttp3`), and requires handling the same logic when invoking both the `./configure` and CMake. Orthogonal to this recipe unless these capabilities were introduced in the newest version.


> ENABLE_CURL_MANUAL

Setting this to OFF unconditionally - matches what we do for makefiles which is disable the manual/docs altogether

**Review by RubenRBS — APPROVED** [review]
Sorry for the delay on this one, it fell thru the cracks :)

**Review by jcar87 — APPROVED** [review]

**Comment by perseoGI** [comment]
I'm closing this PR in favor of https://github.com/conan-io/conan-center-index/pull/24068 which adds `libcurl 8.8.0`.
Thanks for your contribution @Ahajha!

**Pull request closed without merging**
