### PR TITLE
libcurl: add version 7.84.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **libcurl/7.84.0**

- add version 7.84.0
- use `is_msvc()`
- add topics
- use `lru_cache` in `_configure_cmake`, `_configure_autotools`
- update wolfssl, ninja

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by allen-zhou-dev** [comment]
Closing my PR https://github.com/conan-io/conan-center-index/pull/11571 as this covers it. Thanks!

**Comment by allen-zhou-dev** [comment]
Any progress on this?

**Comment by allen-zhou-dev** [comment]
@SSE4 Just needs approval it looks like?

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]
🤞 this will trigger the markdown generator so I an see it run

**Comment by prince-chrismc** [comment]
> Hoping to push this through a bit quicker, my organization is waiting on this.

You can take a look at https://github.com/prince-chrismc/conan-center-index-pending-review/issues/1 which shows how long PRs take this way you know what to expect

it's at about 8 days right now and there a super long list (twice as long) that are pending. 

The bot will auto merge this shortly 🤞

**Pull request merged**
