### PR TITLE
opencv/2.x: Update dependencies

### PR DESCRIPTION
**Pull request by prince-chrismc**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

Trying to see how bad #13988 is 

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/README.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
The error message is super misleading 

https://c3i.jfrog.io/c3i/misc/logs/pr/14281/3-configs/windows-visual_studio/opencv/2.4.13.7//18d96ff8fbeed0cc785be3719208fdd5a06bbe96-build.txt

image

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/issues/14754

**Comment by RubenRBS** [comment]
This looks to be a subset from the changes in #13406 that @SpaceIm seems to have almost ready for 2.0 compatibility, right?

**Comment by prince-chrismc** [comment]
Most certainly does look that way, this is mostly to unblock the conflicts with zlib but I am surprised that PR is passing 🤔 of maybe #13285 was merged?

**Comment by prince-chrismc** [comment]
closing in favor of https://github.com/conan-io/conan-center-index/pull/13406 since I dont want to update the imports :)

**Pull request closed without merging**
