### PR TITLE
[google-cloud-cpp] add v2.23.0 version

### PR DESCRIPTION
**Pull request by dbolduc**
**google-cloud-cpp/2.23.0**

- Add version 2.23.0 of `google-cloud-cpp`.
- Remove version 2.12.0, and clean up code only relevant to 2.12.0.
- Simplify handling of some legacy proto libraries from https://github.com/googleapis/google-cloud-cpp/issues/8022
- Drop the MSVC patch from previous versions which was fixed upstream in https://github.com/googleapis/google-cloud-cpp/pull/13777
- Individual compute_${foo}_protos libraries were removed in https://github.com/googleapis/google-cloud-cpp/pull/13836 so mirror that here.

Tested with the following on linux:
```
for v in "2.23.0" "2.19.0" "2.15.1"; do
  env CC=gcc-11 CXX=g++-11 conan create --build missing  --build-require  --version ${v} recipes/google-cloud-cpp/2.x
done
```

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by dbolduc** [comment]
ping?

**Comment by dbolduc** [comment]
@jcar87 PTAL

**Comment by dbolduc** [comment]
@jcar87 - is there anything I need to do to get this PR merged?

**Comment by jcar87** [comment]
Hi @dbolduc  - currently reviewing this, aiming to have a review today, thanks!

**Comment by dbolduc** [comment]
ping?

**Comment by saschasc** [comment]
@jcar87 I remember that you've mentioned that based on the recent grpc update also google-cloud-cpp should be updated.  Does it make sense that @dbolduc updates this to a newer version of google-cloud-cpp? Thanks for your effort @jcar87 and @dbolduc! Much appreciated. It would be great to have an updated google-cloud-cpp package.

**Comment by dbolduc** [comment]
> Does it make sense that @dbolduc updates this to a newer version of google-cloud-cpp?

@saschasc - I think you are right.

We are releasing `v2.28.0` of `google-cloud-cpp` today-ish. When that drops, I will work on a PR to add `v2.28.0` to Conan. I will abandon this PR in favor of the `v2.28.0` PR.

**Comment by dbolduc** [comment]
> So then this PR should be closed?

Yes, thanks.

> Are there any plans to create a google-cloud-cpp package which builds upon the newest grpc/1.65.0 and dependencies?

Not immediately. If it as simple as updating the `requirements` strings maybe you could send a PR?

**Pull request closed without merging**
