### PR TITLE
[google-cloud-cpp] update to v2.15.1

### PR DESCRIPTION
**Pull request by coryan**
Specify library name and version:  **google-cloud-cpp/2.15.1**

Updating to the latest version (v2.15.1).

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by coryan** [comment]
Seems like something is not right between the libcurl, openssl, protobuf and gRPC dependencies. Any advice?

**Comment by bemehiser** [comment]
> Seems like something is not right between the libcurl, openssl, protobuf and gRPC dependencies. Any advice?

It looks like grpc is downgrading the zlib version. I'm going to try upgrading the version of zlib for grpc, which should remove the conflict.

**Comment by coryan** [comment]
> > Seems like something is not right between the libcurl, openssl, protobuf and gRPC dependencies. Any advice?
> 
> It looks like grpc is downgrading the zlib version. I'm going to try upgrading the version of zlib for grpc, which should remove the conflict.

Thanks, your PR seems like a more robust fix than just bumping gRPC to the latest version.

**Comment by coryan** [comment]
Looks like the `grpc` recipe still needs updates.  Will continue to wait.

**Comment by coryan** [comment]
This is going to need more work to get v2.5.0 compiling again.  At the very least I need to backport:

https://github.com/googleapis/google-cloud-cpp/pull/10612

At least on my macOS laptop I need to disable `-Werror` and/or backport:

https://github.com/googleapis/google-cloud-cpp/pull/12563

**Comment by coryan** [comment]
Looks like `openssl/3.1.4` was not prebuilt, rebasing and starting over.

**Comment by coryan** [comment]
@RubenRBS should I rebase or test this PR in some new way?

**Review by RubenRBS — APPROVED** [review]
Hi @coryan thanks a lot for your patience - I mislabeled this PR a few weeks ago and it's not until now that I've realized, sorry about that - the changes look good, will ensure this gets merged asap :)

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by coryan** [comment]
Thanks!

**Pull request merged**
