### PR TITLE
re2: add 2020-10-01 + fix hooks

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **re2/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
CI pending...

**Comment by SpaceIm** [comment]
still in pending state

**Comment by uilianries** [comment]
The bot is drunk, there are 2 finished builds in CI status only. Probably, it didn't catch the related event.

**Comment by jgsogo** [comment]
> The bot is drunk, there are 2 finished builds in CI status only. Probably, it didn't catch the related event.
> 
> @danimtb @jgsogo Could you please take a look?

Last week we had hard times here: we had an issue in the C3i backend, and Github API was in maintenance mode for some hours... you know, if something can go wrong, it will go wrong 😞 

But now everything should be working again

**Comment by madebr** [comment]
> Should I add an empty commit? Still in pending state.

Do it.
It's harmless. This pr will be squashed before merging, so no extra commits will be merged to master.

**Comment by jgsogo** [comment]
build successful... about the green check I can see this in the logs:

```
Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected


GitHub has been notified of this commit’s build result

Finished: SUCCESS
```

It makes no sense, it is using the same credentials as other jobs that are updating the commit status 😖

**Comment by jgsogo** [comment]
We really don't know why the CI is not able to update the commit status... but it has 3 approvals, it is ready to be merged 👍

**Pull request merged**
