### PR TITLE
quazip/1.3.0: Add qt6 support

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **quazip/1.2.0**

I currently put qt6 as default for CI testing but we might revert it to qt5 if needed
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by MartinDelille** [comment]
Wait for https://github.com/conan-io/conan-center-index/pull/10261

**Comment by MartinDelille** [comment]
Latest quazip version seems to handle automatically qt6: https://github.com/stachenov/quazip/releases/tag/v1.3

**Comment by jgsogo** [comment]
Conflicts here

**Comment by MartinDelille** [comment]
Yes I guess part of the work has been done [here](https://github.com/conan-io/conan-center-index/pull/10569) but I still have an issue: https://github.com/conan-io/conan-center-index/issues/10640

**Pull request closed without merging**
