### PR TITLE
onetbb/2021.6.0 version bump

### PR DESCRIPTION
**Pull request by cguentherTUChemnitz**
Specify library name and version:  **onetbb/2021.6.0**

just a version bump of existing reciepe

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by cguentherTUChemnitz** [comment]
@AndreyMlashkin @TheClonerx I have seen you both added also PR for updating the tbb package. I have seen that you both added the "m" library like here:
https://github.com/conan-io/conan-center-index/pull/12082/files#diff-b3f311c029a7f65413cc611ba0802a17a7f16811df0ae6ee0310cf5fa342bd61R136

Is that necessary, should i add it also accordingly?

Does someone maybe have an idea how to cope with those problems? https://github.com/conan-io/conan-center-index/pull/13116#issuecomment-1257927798

**Comment by cguentherTUChemnitz** [comment]
> @AndreyMlashkin @TheClonerx I have seen you both added also PR for updating the tbb package. I have seen that you both added the "m" library like here: https://github.com/conan-io/conan-center-index/pull/12082/files#diff-b3f311c029a7f65413cc611ba0802a17a7f16811df0ae6ee0310cf5fa342bd61R136
> 
> Is that necessary, should i add it also accordingly?
> 
> Does someone maybe have an idea how to cope with those problems? [#13116 (comment)](https://github.com/conan-io/conan-center-index/pull/13116#issuecomment-1257927798)

<details>
  <summary>A local shared build test showed me the following:</summary>

ldd on all the shared libs:
```
./libtbbbind_2_5.so:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007fffd2987000)
        libhwloc.so.15 => /usr/lib/libhwloc.so.15 (0x00007f5405e6c000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f5405c00000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f5405b18000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5405e4c000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f5405931000)
        libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f5405904000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f5405efe000)
./libtbbbind_2_5.so.3:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffc509f8000)
        libhwloc.so.15 => /usr/lib/libhwloc.so.15 (0x00007f39b6cc7000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f39b6a00000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f39b6918000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f39b6ca7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f39b6731000)
        libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f39b6c7a000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f39b6d59000)
./libtbbbind_2_5.so.3.6:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffc26deb000)
        libhwloc.so.15 => /usr/lib/libhwloc.so.15 (0x00007f489cf61000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f489cc00000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f489ce79000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f489ce59000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f489ca19000)
        libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f489c9ec000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f489cff3000)
./libtbbmalloc_proxy.so:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffd14ded000)
        libtbbmalloc.so.2 => /usr/lib/libtbbmalloc.so.2 (0x00007f5d3c96a000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f5d3c600000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f5d3c882000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5d3c862000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f5d3c419000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f5d3c9dd000)
./libtbbmalloc_proxy.so.2:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffc633f3000)
        libtbbmalloc.so.2 => /usr/lib/libtbbmalloc.so.2 (0x00007f9d2dbaa000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f9d2d800000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f9d2dac2000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f9d2daa2000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f9d2d619000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f9d2dc1d000)
./libtbbmalloc_proxy.so.2.6:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffcf8310000)
        libtbbmalloc.so.2 => /usr/lib/libtbbmalloc.so.2 (0x00007f417a49c000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f417a200000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f417a118000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f417a47c000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f4179f31000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f417a50f000)
./libtbbmalloc.so:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007fff48b7d000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f2f8568d000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f2f858e6000)
./libtbbmalloc.so.2:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffd3b374000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f18c498c000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f18c4be5000)
./libtbbmalloc.so.2.6:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffea2df6000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f3544f01000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f354515a000)
./libtbb.so:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffe6f4d7000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f1cbca00000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f1cbcd03000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f1cbcce3000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f1cbc819000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f1cbce6b000)
./libtbb.so.12:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffe59bc9000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f7515000000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f751530d000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f75152ed000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f7514e19000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f7515475000)
./libtbb.so.12.6:
        linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffd97d2a000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f4c1ea00000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f4c1e918000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f4c1ec62000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f4c1e731000)
        /usr/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f4c1ed02000)
```
</details>

i would go to add libm for libtbb libtbbmalloc_proxy but not for libtbbmalloc itself. I hope this is the right way to go here.

**Comment by cguentherTUChemnitz** [comment]
> Failure in build 3 (`3bb64a034ca2aca82acd3ca7f7896f496b94d6b9`):
> 
> * **onetbb/2021.3.0@:**
>   Didn't run or was cancelled before finishing
> * **onetbb/2021.6.0@:**
>   CI failed to create some packages ([All logs](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/13116/3-linux-gcc/onetbb/2021.6.0//summary.json))
>   Logs for packageID `053ea29eb0edc6b1695c893b738a971110c756fd`:
>   ```
>   [settings]
>   arch=x86_64
>   build_type=Debug
>   compiler=gcc
>   compiler.libcxx=libstdc++
>   compiler.version=7
>   os=Linux
>   [options]
>   onetbb:shared=False
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   ```
>   [...]
>   -- Detecting CXX compile features - done
>   -- Conan: called by CMake conan helper
>   -- Conan: Adjusting output directories
>   -- Conan: Using cmake targets configuration
>   -- Library tbb_debug found /home/conan/w/prod/BuildSingleReference/.conan/data/onetbb/2021.6.0/_/_/package/053ea29eb0edc6b1695c893b738a971110c756fd/lib/libtbb_debug.a
>   -- Conan: Adjusting default RPATHs Conan policies
>   -- Conan: Adjusting language standard
>   -- Conan: Compiler GCC>=5, checking major version 7
>   -- Conan: Checking correct version: 7
>   -- Conan: C++ stdlib: libstdc++
>   -- Library tbb_debug found /home/conan/w/prod/BuildSingleReference/.conan/data/onetbb/2021.6.0/_/_/package/053ea29eb0edc6b1695c893b738a971110c756fd/lib/libtbb_debug.a
>   -- Found: /home/conan/w/prod/BuildSingleReference/.conan/data/onetbb/2021.6.0/_/_/package/053ea29eb0edc6b1695c893b738a971110c756fd/lib/libtbb_debug.a
>   -- Library tbb_debug found /home/conan/w/prod/BuildSingleReference/.conan/data/onetbb/2021.6.0/_/_/package/053ea29eb0edc6b1695c893b738a971110c756fd/lib/libtbb_debug.a
>   -- Found: /home/conan/w/prod/BuildSingleReference/.conan/data/onetbb/2021.6.0/_/_/package/053ea29eb0edc6b1695c893b738a971110c756fd/lib/libtbb_debug.a
>   -- Configuring done
>   -- Generating done
>   -- Build files have been written to: /home/conan/w/prod/BuildSingleReference/conan-center-index/recipes/onetbb/all/test_v1_package/build/bead7fe95daefab26b9f1d211663559f5e9fefb1
>   
>   ----Running------
>   > cmake --build '/home/conan/w/prod/BuildSingleReference/conan-center-index/recipes/onetbb/all/test_v1_package/build/bead7fe95daefab26b9f1d211663559f5e9fefb1' '--' '-j3'
>   -----------------
>   Scanning dependencies of target test_package
>   [ 50%] Building CXX object CMakeFiles/test_package.dir/home/conan/w/prod/BuildSingleReference/conan-center-index/recipes/onetbb/all/test_package/test_package.cpp.o
>   [100%] Linking CXX executable bin/test_package
>   [100%] Built target test_package
>   onetbb/2021.6.0 (test package): Running test()
>   
>   ----Running------
>   > bin/test_package
>   -----------------
>   Fib 6=CMake Warning:
>     Manually-specified variables were not used by the project:
>   
>       CMAKE_EXPORT_NO_PACKAGE_REGISTRY
>       CMAKE_INSTALL_BINDIR
>       CMAKE_INSTALL_DATAROOTDIR
>       CMAKE_INSTALL_INCLUDEDIR
>       CMAKE_INSTALL_LIBDIR
>       CMAKE_INSTALL_LIBEXECDIR
>       CMAKE_INSTALL_OLDINCLUDEDIR
>       CMAKE_INSTALL_SBINDIR
>   
>   
>   Assertion node(val).my_prev_node == &node(val) && node(val).my_next_node == &node(val) failed (located in the push_front function, line in file: 135)
>   Detailed description: Object with intrusive list node can be part of only one intrusive list simultaneously
>   Aborted
>   onetbb/2021.6.0: WARN: oneTBB strongly discourages usage of static linkage
>   ERROR: onetbb/2021.6.0 (test package): Error in test() method, line 17
>   	self.run(bin_path, run_environment=True)
>   	ConanException: Error 134 while executing bin/test_package
>   ```
> 
> **Note:** To save resources, CI tries to finish as soon as an error is found. For this reason you might find that not all the references have been launched or not all the configurations for a given reference. Also, take into account that we cannot guarantee the order of execution as it depends on CI workload and workers availability.

I can confirm that those problems are showing up only for onetbb 2021.6.0 in combination of Debug build with shared=False. When one of the three parts are configured in another way, the problems does not occur anymore.

**Comment by kambala-decapitator** [comment]
@cguentherTUChemnitz could you incorporate additional changes from #13386 into this PR?

**Comment by cguentherTUChemnitz** [comment]
> @cguentherTUChemnitz could you incorporate additional changes from #13386 into this PR?

It seems you already incorporated my changes in your PR. It also seems that you superseded my work in progress here. So i will just close this ticket here. Great work and thanks for pushing on on the topic here.

**Comment by uilianries** [comment]
Thank you both @kambala-decapitator @cguentherTUChemnitz for pushing it!

**Pull request closed without merging**
