### PR TITLE
geographiclib: fix check for minimum cpp standard

### PR DESCRIPTION
**Pull request by riebl**
Specify library name and version:  **geographiclib/1.51**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SpaceIm — APPROVED** [review]

**Comment by mathbunnyru** [comment]
Grepped `tools.min_cppstd` - this is the only place with these lines.

**Comment by mathbunnyru** [comment]
@riebl  could you please ask to add you to the EAP here?
#4

**Review by mathbunnyru — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by riebl** [comment]
Now that I have been added to the EAP, shall I rebase this PR to trigger the CI?

**Comment by mathbunnyru** [comment]
You can close the PR, wait for at least 10 secs and then open it again.

**Comment by riebl** [comment]
Closing temporarily to trigger CI later.

**Comment by riebl** [comment]
Hopefully triggering CI now :-)

**Pull request merged**
