### PR TITLE
Update to h5pp/1.9.0

### PR DESCRIPTION
**Pull request by DavidAce**
Update to newest version **[h5pp/1.9.0](https://github.com/DavidAce/h5pp/releases/tag/v1.9.0)**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Is it not excessive https://github.com/DavidAce/h5pp/commit/93169a598ccdb10bdf549a997f824481e141acf5#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a?

**Comment by DavidAce** [comment]
> Is it not excessive [DavidAce/h5pp@93169a5](https://github.com/DavidAce/h5pp/commit/93169a598ccdb10bdf549a997f824481e141acf5)?
I reduced the cmake version requirement to 3.18 now since that seems to be the version on the build server. I'd rather keep the version as new as possible.

Version 3.19 had some nice updates, in particular to FindHDF5.cmake and the support for querying the LOCATION property of IMPORTED INTERFACE libraries without giving errors. But I managed to get 3.18 working on my system after a version check.

**Comment by jgsogo** [comment]
Our baseline for the CI is the same that Conan 2.x will use, CMake 3.15 (https://github.com/conan-io/tribe/blob/main/design/004-tools-cmake.md), although most of the machines are using 3.16. If this library really needs a newer version, maybe it needs a build-requires to CMake.

**Review by prince-chrismc — DISMISSED** [review]

**Comment by DavidAce** [comment]
> Our baseline for the CI is the same that Conan 2.x will use, CMake 3.15 (https://github.com/conan-io/tribe/blob/main/design/004-tools-cmake.md), although most of the machines are using 3.16. If this library really needs a newer version, maybe it needs a build-requires to CMake.

Thanks! I've updated h5pp/1.9.0 to require CMake 3.15. 
Fortunately other than the features I mentioned previously, it turns out that the rest of what h5pp needs was introduced precisely in CMake 3.15, such as [`MSVC_RUNTIME_LIBRARY`](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html#prop_tgt:MSVC_RUNTIME_LIBRARY) and related flags. Also I suppose it makes sense for a header-only library to be more relaxed about the CMake version.

**Review by jgsogo — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
