### PR TITLE
[freetype] Bump requirements for libpng and zlib

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@uilianries @jcar87 @prince-chrismc @RubenRBS I've missed something. Does conancenter now allow to use version range besides openssl & cmake?

**Comment by uilianries** [comment]
@SpaceIm not yet, but we have been discussing about a new list. I remember you posted about a possible new list and started from there.

**Comment by SpaceIm** [comment]
Ok, but this PR has added version range for several dependencies not part of current list and bot didn't complain, shouldn't there be a hook preventing this?

**Comment by MartinDelille** [comment]
I wasn't aware of this list. Thank you for your vigilance!

**Pull request merged**
