### PR TITLE
daw_json_link: add version 3.28.3

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **daw_json_link/***

#### Motivation
There are several improvements since 3.24.1.

#### Details
https://github.com/beached/daw_json_link/compare/v3.24.1...v3.28.3

Because daw_json_link and daw_utf_range requires daw_utf_header, we have to update daw_utf_range and daw_utf_header at same time.

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by toge** [comment]
@AbrilRBS 
Could you help me?

The extra attributes for dependencies have been introduced by https://github.com/conan-io/conan-center-index/pull/24499.
It worked fine on CI at that moment.

Are there any white list to check attributes of conandata.yml?

**Comment by AbrilRBS** [comment]
@toge sorry for the dealy, I didn't see your notification. This is quite weird because that same pattern is working elsewhere 🤔

**Comment by AbrilRBS** [comment]
Will need to double check with the team as to what might be going on here! Locally this works!

**Review by AbrilRBS — APPROVED** [review]

**Review by jcar87 — APPROVED** [review]

**Comment by AbrilRBS** [comment]
Thanks @toge, this now works with the new pipeline, so merging as-is :)

**Pull request merged**
