### PR TITLE
patch for fixing boost::proto #20

### PR DESCRIPTION
**Pull request by dvirtz**
Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by dvirtz** [comment]
Backports a fix to https://github.com/boostorg/proto/issues/20

**Comment by danimtb** [comment]
Reading the issue linked, it seems the fix for this is going to be released in Boost 1.72.0

So I am wondering if we should patch this here or just wait for next release.

**Comment by dvirtz** [comment]
The current release is unusable with latest msvc. I'd rather not wait for
next release.

**Comment by danimtb** [comment]
Yes, I understand that. But it is not an issue of the Conan package but of the library itself. Are they planning to release a patch (1.70.1 and 1.71.1) fixing this?

**Comment by dvirtz** [comment]
I assumed from the presence of https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/patches/0001-beast-fix-moved-from-executor.patch that it's allowed to have patches for bug fixes.

**Comment by uilianries** [comment]
Usually we don't patch upstream bugs. We prefer accepting patches which allow multi-platform building. This is case affects a feature, not a platform, we prefer waiting for 1.72

**Comment by dvirtz** [comment]
Understandable

**Pull request closed without merging**
