### PR TITLE
paho-mqtt-cpp: update paho-mqtt-c/1.3.13

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **paho-mqtt-cpp/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
I just started an internal build to generate the missing `paho-mqtt-c/1.3.13`

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
Generating the missing `paho-mqtt-c/1.3.1` right now! 🏗️

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
Only paho-mqtt-cpp uses paho-mqtt-c, this change is safe.

**Comment by uilianries** [comment]
Just started an internal build to generate the missing paho-mqtt-c/1.3.1

**Comment by uilianries** [comment]
Started another build to generate paho-mqtt-c/1.3.1.

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — DISMISSED** [review]
LGTM, no other projects are consuming paho-mqtt-c, no possible conflicts.

**Comment by toge** [comment]
@pwqbot 
Sorry I missed this PR.
Now CI is invoked. Please wait to finish.

**Comment by uilianries** [comment]
@toge I did some few changes in your pull request:

- Dropped version 1.1 and 1.0. Not only because the current error, but there is a new paho mqtt c++ version available already and old versions need a specif logic and patches. Plus, no other recipes in CCI are using paho.
- Removed the deprecated option ssl. It was marked to be removed in few months.
- Simplified the test package to use a minimal part of the library. So we don't need to open a server as before.

**Review by RubenRBS — APPROVED** [review]

**Comment by uilianries** [comment]
@pwqbot The paho-mqtt-cpp PR is merged now 🎉

**Pull request merged**
