### PR TITLE
tidy-html5: add 5.8.0 + fix packaging on Windows + do not suggest unofficial CMake names

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

- version 5.7.28 was not a stable release, and upstream removed this tag: https://github.com/htacg/tidy-html5/issues/834#issuecomment-886941863
- packaging on Windows:
  - static lib was not removed if Visual Studio and shared
  - both static and import lib were removed if MinGW and shared 😅 
- tidy-html5 doesn't export CMake names, so no need for all these components (and anyway I strongly discourage to write conditional conan components names).

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
the conditional component goes from: https://github.com/htacg/tidy-html5/blob/c42ec040c96e28494704c171fadf799365aa8e98/CMakeLists.txt#L430
they have different target names for static vs shared, which complicates packaging a lot...

> both static and import lib were removed if MinGW and shared 
is this even correct thing to do?

**Comment by SpaceIm** [comment]
> the conditional component goes from: https://github.com/htacg/tidy-html5/blob/c42ec040c96e28494704c171fadf799365aa8e98/CMakeLists.txt#L430
> they have different target names for static vs shared, which complicates packaging a lot...

Components don't make sense for tidy-html5. It doesn't export CMake targets, and only one pkgconf file. How target names are handled internally in their CMakeLists is orthogonal.

> > both static and import lib were removed if MinGW and shared
> 
> is this even correct thing to do?

I describe the issue in previous revision, now it's fixed.

**Comment by SpaceIm** [comment]
There is an issue with pdb files, it requires a patch for Visual Studio.

**Comment by SSE4** [comment]
> version 5.7.28 was not a stable release, and upstream removed this tag

really horrible move, always sad to read things like that...

**Comment by SSE4** [comment]
> There is an issue with pdb files, it requires a patch for Visual Studio.

what kind of issue?

**Comment by SpaceIm** [comment]
installation of pdb files hard fails

**Comment by SSE4** [comment]
that wasn't an issue in previous (removed) tag... they likely have broken something

**Comment by SpaceIm** [comment]
I think it was already broken with ninja generator and Visual Studio.

**Comment by SSE4** [comment]
> I think it was already broken with ninja generator and Visual Studio (CCI uses MSBuild).

yes, that's very possible - we don't test all the CMake generators, only default (Visual Studio) one. no nmake, ninja, etc.

**Comment by SpaceIm** [comment]
https://github.com/htacg/tidy-html5/pull/980

**Comment by SpaceIm** [comment]
@SSE4 Actually, 5.7.28 shouldn't have been packaged, it's explained here: https://github.com/htacg/tidy-html5/blob/next/README/VERSION.md#minor

**Review by uilianries — APPROVED** [review]
Much simpler without 5.7

**Comment by SSE4** [comment]
> @SSE4 Actually, 5.7.28 shouldn't have been packaged, it's explained here: https://github.com/htacg/tidy-html5/blob/next/README/VERSION.md#minor

of course, every projects likes to invent its own unique versioning scheme making it complicated for users - you can't just grab latest release, you need to check if it's odd number, prime number, Fibonacci number or whatever, because it has special meaning...

**Review by SSE4 — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Pull request merged**
