### PR TITLE
[boost] fix soname

### PR DESCRIPTION
**Pull request by SSE4**
closes: #294 

Specify library name and version:  **boost/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
@danimtb any idea why packages might be missing?
```
ERROR: Missing prebuilt package for 'bzip2/1.0.8'
Try to build it from sources with "--build bzip2"
```

**Comment by uilianries** [comment]
Weird error, we need to check if some package was removed

**Comment by SSE4** [comment]
@uilianries the error disappeared after relaunch. still we have no clue what happened and why...

**Comment by uilianries** [comment]
@SSE4 server maintenance maybe ? Let's remember about this case, if we have similar problem in the future

**Pull request merged**
