### PR TITLE
Rework openCV test_packages to remove controversial Lena test image [2/2]

### PR DESCRIPTION
**Pull request by ericriff**
See https://github.com/conan-io/conan-center-index/issues/4609 and https://github.com/conan-io/conan-center-index/pull/4619
 
The test_package used here is **_almost_** the same as the one on 2.x. The only difference is that it needs the `opencv2/imgproc.hpp` header and therefore also links against `opencv::opencv_imgproc`.

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericriff** [comment]
```
ERROR: Missing binary: libpng/1.6.37:d8b88b49d6e7691941997f64ad700b4308d0ed8c
libpng/1.6.37: WARN: Can't find a 'libpng/1.6.37' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=10, os=Linux
- Options: api_prefix=None, fPIC=True, shared=False, zlib:fPIC=True, zlib:minizip=False, zlib:shared=False
- Dependencies: zlib/1.2.11
- Requirements: zlib/1.Y.Z
- Package ID: d8b88b49d6e7691941997f64ad700b4308d0ed8c
```
This is the same problem I'm getting on the QuaZip PR. `libpng` is not available on the new compilers.

**Comment by uilianries** [comment]
@ericriff Yes, some package are still missing for new compiler version, but it's a temporary error, they should available in few days.

**Review by mathbunnyru — APPROVED** [review]

**Comment by mathbunnyru** [comment]
And, if you want to speed up this process, you can create a PR with some small change in conanfile.py for libpng.
After getting merged, it will generate all the needed configurations.
But it might get messy if libpng has dependencies, which are also not yet present in CCI for new compiler version...

**Comment by uilianries** [comment]
> And, if you want to speed up this process, you can create a PR with some small change in conanfile.py for libpng.
> After getting merged, it will generate all the needed configurations.
> But it might get messy if libpng has dependencies, which are also not yet present in CCI for new compiler version...

CCI can generate it internally too, just need to list the package reference. I'm collecting broken packages to start a new build asap.

**Comment by ericriff** [comment]
> > And, if you want to speed up this process, you can create a PR with some small change in conanfile.py for libpng.
> > After getting merged, it will generate all the needed configurations.
> > But it might get messy if libpng has dependencies, which are also not yet present in CCI for new compiler version...
> 
> CCI can generate it internally too, just need to list the package reference. I'm collecting broken packages to start a new build asap.

Check my QuaZip PR, it has a couple of packages missing besides this one (libpng)

**Comment by jgsogo** [comment]
Hi! I've triggered it and it succeeded for `libpng/1.6.37`: https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/TapaholesList/70/libpng/1.6.37//summary.json

We are not monitoring these errors (we should, but we forgot to add a label to PRs with these failures), so please, mention us and we will trigger the build. It is possible that some other versions of `libpng` are failing and then the _batch_ build did fail... for other references it would be the recipe that requires a patch/fix to compile for the new configurations.

We tried to generate them all, but we haven't inspected one by one all the failures.

**Comment by ericriff** [comment]
@jgsogo is this an infrastructure error?

**Comment by jgsogo** [comment]
I don't think so. Linux builds are running inside docker containers (the ones from `conan-docker-tools`). Maybe some URLs were not available at that moment. cc/ @uilianries

**Comment by uilianries** [comment]
Really interesting ... I'll take a look

**Comment by ericriff** [comment]
I'm not sure what is going on now, it builds on my PC. To double check I pulled the docker container `conanio/gcc5` and it also builds there (after installing libgtk2.0-dev) :thinking:

**Comment by uilianries** [comment]
http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-minimal_2.7.12-1ubuntu0~16.04.14_amd64.deb has been removed, but patch 13 is still there.

**Comment by uilianries** [comment]
It's an error from APT. OpenCV requires libgtk2.0-dev, which requires python2.7. For some reason, patch 14 is not there. Or it has been removed, or it will be available soon.

**Comment by uilianries** [comment]
Let's retry, patch 16 is available now, maybe the index is fixed.

**Comment by ericriff** [comment]
On my PC and in this docker container, with the problematic profile, the build passes. I'm not sure what is going on.
Can someone confirm that the gcc5 build failing is using the conanio/gcc5 container?

**Comment by uilianries** [comment]
I can see patch 16 listed with my browser, but APT is not able to solve it.

**Comment by ericriff** [comment]
> > On my PC and in this docker container, with the problematic profile, the build passes. I'm not sure what is going on.
> > Can someone confirm that the gcc5 build failing is using the conanio/gcc5 container?
> 
> I think is related to Ubuntu mirrors. As there are many of them, probably that one used by CCI is not updated yet.

But it is a linking issue on the test_package :thinking:

**Comment by jgsogo** [comment]
We are using the docker images from `conan-docker-tools` to build... and AFAIK there is only one version of `gcc` (or `clang`) in each container, so if it is building using `gcc5` it should be the `conanio/gcc5` docker image.

I've tried it locally (using VPN, most likely the same that our CI is using) and it has succeeded `sudo apt-get update` and `sudo apt-get install libgtk2.0-dev`. If the error persists, I'll ask people in charge of the infrastructure, maybe there is some intermediate cache/CDN in front of our cluster.

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
