### PR TITLE
add proj/7.1.0 + use components to define PROJ::proj target

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **proj/7.1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
  Checking Build System

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "x64\Debug\generate_all_sql_in\generate.3BD4BA4C.tlog\generate_all_sql_in.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\J\workspace\onan-center-pull-request_PR-2143\1\pr_2143_1_0_2\.conan\data\proj\7.1.0\_\_\build\9a7d571ebac47686db198060f28764a1602a8ddb\build_subfolder\source_subfolder\data\generate_all_sql_in.vcxproj]

proj/7.1.0: 

JSON file created at 'C:\J\workspace\onan-center-pull-request_PR-2143/1/co_pr_2143_1_0_2/_create.json'
```

Was working without `short_paths=True` in previous proj's PR, why does it fail now?

**Comment by uilianries** [comment]
@SpaceIm probably something changed internally

**Comment by danimtb** [comment]
@SpaceIm I think it is related to msbuild not managing long paths well. We are preparing a fix for this

**Comment by uilianries** [comment]
Thanks @danimtb !!!

**Pull request merged**
