### PR TITLE
libdisplay-info: move hwdata to build requirements unconditionally + bump hwdata

### PR DESCRIPTION
**Pull request by SpaceIm**
---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]
Thanks!

**Review by jwillikers — APPROVED** [review]
Thanks!

**Comment by SpaceIm** [comment]
@uilianries @AbrilRBS @jcar87 @danimtb Could you review this one please? It's waiting for a final reviewer for 9 months 🥲

**Review by AbrilRBS — APPROVED** [review]

**Review by perseoGI — APPROVED** [review]
LGTM

**Review by jcar87 — APPROVED** [review]

**Pull request merged**
