### PR TITLE
[qt/6.5.1] Add version

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **qt/6.5.1**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by ericLemanissier — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by MartinDelille** [comment]
@danimtb ?

**Comment by ericLemanissier** [comment]
see https://status.conan.io/

**Comment by nrbnlulu** [comment]
Why are you merging stuff if it is not working for conan v2?

**Pull request merged**
