### PR TITLE
dbus: fix build of 1.15.8 with Visual Studio 2022

### LINKED ISSUE #19421: [package] dbus/1.15.8: compilation fails with Visual Studio 2022 (and C++20?)
### Description

Compilation fails with Visual Studio 2022 (and C++20?).

There are errors like `error C2061: syntax error: identifier 'atomic_bool'` or `error C2079: 'refcount' uses undefined struct 'DBusAtomic'`

### Package and Environment Details

* Package Name/Version: **dbus/1.15.8**
* Operating System+version: **Windows 11**
* Compiler+version: **Visual Studio 2022 (17.7.2)**
* Conan version: **conan 2.0.9**
* Python version: **Python 3.11.1**

### Conan profile

```ini
[settings]
os=Windows
arch=x86_64
compiler=msvc
compiler.version=193
compiler.runtime=dynamic
compiler.cppstd=20
build_type=Release
```

### Steps to reproduce

```
conan install --requires dbus/1.15.8 -b missing
```

### Logs

[build.log](https://github.com/conan-io/conan-center-index/files/12442485/build.log)

### PR DESCRIPTION
**Pull request by tsondergaard**
Instead of using has_header use check_header to confirm the header works. This is necessary to get the meson build to work with Visual Studio 2022. It has <stdatomic.h> but it does not actually work when compiling a C program.

Fixes #19421

See also associated upstream issue and merge request:
* https://gitlab.freedesktop.org/dbus/dbus/-/issues/494
* https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/454

Specify library name and version:  **dbus/1.15.8**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]
LGTM. Thanks for working on a fix upstream.

**Review by RubenRBS — CHANGES_REQUESTED** [review]
Thanks! Let's wait for upstream decision on merging their PR before merging this one, please ping me when the PR is updated, thanks! :)

**Comment by tsondergaard** [comment]
> Thanks! Let's wait for upstream decision on merging their PR before merging this one, please ping me when the PR is updated, thanks! :)

@RubenRBS, the upstream [PR](https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/454) has been merged. Will you approve this PR now?

Once approved do I need to update the branch? The CI comment says "This branch is out-of-date with the base branch" next to a warning icon, but it is not clear to me if this is just a warning or an issue that needs to be addressed before the PR can be merged automatically.

**Review by RubenRBS — APPROVED** [review]
Thanks!

> but it is not clear to me if this is just a warning or an issue that needs to be addressed before the PR can be merged automatically.

It's just GitHub's way to notify contributors that changes arrived in the main branch not present in this PR, but nothing to worry about unless it also shows that there are conflcits!

Approved, thanks a lot! :)

**Pull request merged**
