### PR TITLE
libiconv: fix MinGW clang & modernize more

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/15475

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by rilian-la-te** [comment]
@SpaceIm it requests msys2 for me, which it should not do.

**Comment by rilian-la-te** [comment]
@SpaceIm error during cross-compilation on Linux:

```
libiconv/1.17 (test package): CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/home/rilian/Projects/conan-center-index/recipes/libiconv/all/test_package/build/Release/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/rilian/Projects/conan-center-index/recipes/libiconv/all/test_package/."
-- Using Conan toolchain: /home/rilian/Projects/conan-center-index/recipes/libiconv/all/test_package/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 11 with extensions OFF
-- The C compiler identification is Clang 15.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang - works
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: Target declared 'Iconv::Iconv'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rilian/Projects/conan-center-index/recipes/libiconv/all/test_package/build/Release
libiconv/1.17 (test package): CMake command: cmake --build "/home/rilian/Projects/conan-center-index/recipes/libiconv/all/test_package/build/Release" '--' '-j12'
[1/2] Building C object CMakeFiles/test_package.dir/test_package.c.o
clang-15: warning: argument unused during compilation: '-L/usr/lib/gcc/x86_64-w64-mingw32/12.2.0/' [-Wunused-command-line-argument]
[2/2] Linking C executable test_package
clang-15: warning: argument unused during compilation: '-rdynamic' [-Wunused-command-line-argument]
libiconv/1.17 (test package): Running test()
/bin/sh: строка 1: /home/rilian/Projects/conan-center-index/recipes/libiconv/all/test_package/build/Release/generators/conanrun.bat: Отказано в доступе
ERROR: libiconv/1.17 (test package): Error in test() method, line 27
        self.run(bin_path, env="conanrun")
        ConanException: Error 126 while executing ./test_package

```

**Comment by SpaceIm** [comment]
Your logs make little sense, are you trying to cross-build without 2 profiles?

**Comment by rilian-la-te** [comment]
@SpaceIm I use default profile for build. Am I wrong?

**Comment by uilianries** [comment]
> I use default profile for build. Am I wrong?

@rilian-la-te Please, always use two profiles when cross-building, otherwise the build behavior is not ensured. It's well documented here: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer

**Review by uilianries — APPROVED** [review]
LGTM

**Review by franramirez688 — APPROVED** [review]

**Pull request merged**
