### PR TITLE
add mesongen/0.1

### PR DESCRIPTION
**Pull request by Sahnvour**
Specify library name and version:  **mesongen/0.1**

This a _generator_ I wrote for integration into the meson build system.
It outputs a `meson.build` to find installed dependencies.

This is isn't a source package, so I could not follow precisely every step in making this PR.
However I've used this package for some time now installed in my local cache and it works.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated. ==> this fails checks

### CODE REVIEW

**Comment by intelligide** [comment]
I don't think it's possible to include code under GPL in this repository which is under MIT license.

Moreover, I think it is better to include this generator in the [main conan repository](https://github.com/conan-io/conan).

**Comment by danimtb** [comment]
Hi @Sahnvour,

AFAIK meson build system is compatible with pkg-config file format and this is what we have used so far to integrate it with Conan. I this is a new format or way to use meson we will be happy to adopt it.

 As @intelligide suggests, we are open to any improvement regarding generators in the Conan client, so the right place to contribute this generator will be https://github.com/conan-io/conan. Hope that makes sense.

Thanks!

**Comment by Sahnvour** [comment]
@intelligide @danimtb Thanks for you answers.

Initially I went with the pkg-config generator that is indeed usable with meson. However meson does not really allow a configuration where the build is fully self-contained and installing packages locally.

For example it's not possible to instruct conan to install .pc files inside the build directory and consume them automatically, you have to either install to a machine-wide directory, or manually pass a specific directory to meson while configuring your build. cf https://github.com/mesonbuild/meson/issues/6711
This meson generator helps me avoid this, and everything comes from the initial `meson <builddir>`.

**Comment by danimtb** [comment]
Thanks a lot for the info @Sahnvour. I think we should definitely add this information to an issue in the conan-io/conan repository so we can improve the integration with meson and have a built-in generator in the conan client. WDYT?

**Comment by Sahnvour** [comment]
@danimtb Fine by me, I'll try to come up with a PR when I find some time.

**Comment by Croydon** [comment]
Did someone create a new issue for this? Please link it then :)

**Comment by Sahnvour** [comment]
@Croydon Sorry I don't have time to contribute this to conan at the moment.
But anyone feel free to take it from there and make conan more usable inside a meson project!

**Pull request closed without merging**
