### PR TITLE
[OpenSSL] set asm_arch and perlasm_scheme, if needed

### PR DESCRIPTION
**Pull request by SSE4**
Specify library name and version:  **openssl/all**

closes: #514 

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
don't merge for a while, I need reporters to test the fix first.

**Comment by SSE4** [comment]
per @dmn-star the issue is fixed by the patch

**Comment by spaque** [comment]
Looks like this has broken iOS cross builds for the x86_64 arch. Can work around it though by setting the `no_asm` option to True.

**Comment by SSE4** [comment]
@spaque pls open an issue (with build log, if possible). I can take a look tomorrow.

**Comment by spaque** [comment]
@SSE4 Thanks! Created issue https://github.com/conan-io/conan-center-index/issues/778

**Pull request merged**
