### PR TITLE
Update conanfile.py with additional option

### PR DESCRIPTION
**Pull request by afedechko**
cbor library has an option to be compiled with custom allocators by adding CBOR_CUSTOM_ALLOC to the cmake command.
extend the conanfile.py with ability to specify the option above.

Specify library name and version:  **libcbor/0.7.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@afedechko Please, assign the CLA too: https://github.com/conan-io/conan-center-index/pull/2418#issuecomment-669063745

**Comment by afedechko** [comment]
> Some configurations of 'libcbor/0.7.0' failed in build 3 (`17b160b62217e408bb17585895d07fdda8aca9b8`):
> 
> * **Linux x86_64, Release, gcc 5, libstdc++ . Options:  libcbor:shared-True**
>   
>   * Hooks errors detected:
>     
>     * `[HOOK - conan-center.py] pre_export(): ERROR: [CMAKE VERSION REQUIRED (KB-H048)] The test_packages/CMakeLists.txt requires CMake 3.1 at least. Update to 'cmake_minimum_required(VERSION 3.1)'. (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H048) `
>   * [Log download](https://c3i.jfrog.io/c3i/misc/logs/pr/2418/3/libcbor/0.7.0/e30939caa2339df448fcf9917da7b5ebc54646b6/create_stdout.txt)
>   * [Log error Download](https://c3i.jfrog.io/c3i/misc/logs/pr/2418/3/libcbor/0.7.0/e30939caa2339df448fcf9917da7b5ebc54646b6/create_stderr.txt)
>   * [Profile](https://c3i.jfrog.io/c3i/misc/logs/pr/2418/3/libcbor/0.7.0/e30939caa2339df448fcf9917da7b5ebc54646b6/profile.txt)
> * [Access to all the logs](https://c3i.jfrog.io/c3i/misc/logs/pr/2418/3/libcbor/0.7.0/)

I'm not sure I should do any changes in the CMake file it self, should I ? My changes are only about the recipe and I'm not touching the package itself.

**Comment by jgsogo** [comment]
> I'm not sure I should do any changes in the CMake file it self, should I ? My changes are only about the recipe and I'm not touching the package itself.

Yes, please. I understand your concerns, but these changes will be needed in order to pass the CI... Alternative would be to create a different PR to fix that, wait until merge and update afterward this PR, maybe too much wait for very little changes.

**Comment by uilianries** [comment]
@afedechko Please, accept https://github.com/afedechko/conan-center-index/pull/1

**Comment by afedechko** [comment]
Thanks a lot for the help and support. 

I have tried compiling libcbor with specifying the newly added option and it works as expected. 

However, I noticed additional problem. The `shared` option seems to not work as expected. And seems to be inconsistent on different operating systems. 

Here is the problem I see: 
On Linux (Ubuntu 18.04):
It doesn't matter if _shared_ is True or False after compiling only .so files are created in the lib folder

On Windows:
It also doesn't matter if _shared_ is True or False - after compiling it creates .dll and .lib, but looks the lib is a static library vs import library that makes it not very convenient to use dll.

**Comment by jgsogo** [comment]
Hi! Can you open a new issue (put the name of the library in the title) and the profiles you are using? 

Thanks!

**Comment by afedechko** [comment]
Sure, thank you. 
Just would like to double check what do you mean under "profiles" ?

**Comment by afedechko** [comment]
never mind, looks like I figured that out :) 
Thank you !

**Pull request merged**
