### PR TITLE
coin-osi: modernize

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **coin-osi/all**

For https://github.com/conan-io/hooks/pull/320

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
>Problem getting list of reviews GET https://api.github.com/repos/conan-io/conan-center-index/pulls/7024/reviews?per_page=100: 403 API rate limit of 1000 still exceeded until 2021-08-25 01:35:23 +0000 UTC, not making remote request. [rate reset in 44m15s]

https://github.com/prince-chrismc/conan-center-index-pending-review/runs/3417043709?check_suite_focus=true#step:7:50

We've have never had this many PRs at once you busted my api limit

**Review by prince-chrismc — APPROVED** [review]

**Comment by madebr** [comment]
Oops sorry.
I guess the problem is not self-healing (unless we close/merge some prs) and requires intervention/refactoring?

**Comment by prince-chrismc** [comment]
Honestly, I am happy you broke it. Amazing work!
I just put a PAT so I can find all your PRs to review more quickly 😸 but yeah we need to wait for the CCI bot to pass but it only does 1 every 30 min unless something gets stuck and blocks master

**Comment by madebr** [comment]
Let's hope @conan-center-bot does not break :rofl:

**Review by ericLemanissier — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Review by SpaceIm — APPROVED** [review]

**Pull request merged**
