### PR TITLE
libpciaccess: fix unexpected keyword argument

### PR DESCRIPTION
**Pull request by ericLemanissier**
fixes conan-io/conan-center-index#10909

Specify library name and version:  **libpciaccess/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by uilianries** [comment]
@ericLemanissier It will take a while to run 1.48 here in CCI. Maybe you could downgrade to 1.47

**Comment by SSE4** [comment]
@uilianries is it possible to make it work for any version (1.47/1.48), e.g. with `getattr`/`hasattr` or something? 👁️

**Review by jwillikers — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by uilianries** [comment]
> @uilianries is it possible to make it work for any version (1.47/1.48), e.g. with `getattr`/`hasattr` or something? 👁️

@SSE4 the problem is that we are importing from `conan.tools.gnu` which every helper/tool there consumes `self` as first argument. We could understand it as a bug, but actually is a hotfix. Our options are few, as it implies a change in Conan client. If we do it in CCI, we could create a wrapper, or even use a try/except section to avoid version validation.

Anyway, I also don't like this approach, we will need to pollute all recipes with the check version.

**Comment by ericLemanissier** [comment]
@uilianries I'm not sure to understand (well, actually, I'm sure I don't understand 😄)
This PR is exactly the same change as https://github.com/conan-io/conan-center-index/pull/10911/ and https://github.com/conan-io/conan-center-index/pull/10912/. Why is there a problem with this one ?

**Comment by uilianries** [comment]
@SSE4 Now, I don't understand 😅  Do you mean update Conan client, or do some workaround in CCI recipes? 

@ericLemanissier It's not a problem with this one, but if we start to use it for every cmake usage in recipes. It should be straightforward, no if's, versions, etc ...

**Comment by SSE4** [comment]
> @SSE4 Now, I don't understand 😅 Do you mean update Conan client, or do some workaround in CCI recipes?

a workaround in recipe, but something relilable, that doesn't hard-code conan versions into conditions

**Comment by ericLemanissier** [comment]
> @ericLemanissier It's not a problem with this one, but if we start to use it for every cmake usage in recipes. It should be straightforward, no if's, versions, etc ...

conan.tools.gnu.Autotools is used in only [3 recipes](https://github.com/conan-io/conan-center-index/search?q=conan.tools.gnu), and the other two fixes are already merged. This is the last PR.
Hopefully conan 1.48.0 will be deployed on CCI before we port existing recipes to conan.tools.gnu.Autotools or merge new recipes using conan.tools.gnu.Autotools



> a workaround in recipe, but something relilable, that doesn't hard-code conan versions into conditions

I think hardcoding the recipe is more maintainable, because it's trivial to check with `required_conan_version` at the top of the recipe, and remove the checks when they are redundant.

**Comment by uilianries** [comment]
@ericLemanissier Agreed. Indeed our best option is wait for 1.48.0, then update those recipes.

**Comment by ericLemanissier** [comment]
so our answer to https://github.com/conan-io/conan-center-index/issues/10909 is "do not use conan 1.48.0" ?

**Comment by ericLemanissier** [comment]
let me complete my message: `our answer to https://github.com/conan-io/conan-center-index/issues/10909 is "do not use conan 1.48.0 until it is deployed on C3I" ?`

because I understood that this PR won't be merged as is (with the version checks), but maybe I did not understand correctly ?

**Comment by ericLemanissier** [comment]
ow, sorry. I guess we can just revert these 3 PRs, and consumers will have to stay away from 1.48.* for these 3 packages

- https://github.com/conan-io/conan-center-index/pull/10910
- https://github.com/conan-io/conan-center-index/pull/10911
- https://github.com/conan-io/conan-center-index/pull/10912

**Comment by uilianries** [comment]
@ericLemanissier maybe we will have patch on 1.48. As we are still running 1.47 in Conan Center, we will wait a little just in case, so we can update and avoid more workarounds. Sorry for the inconvenient.

**Comment by jgsogo** [comment]
I've asked for a `1.48.x` release reverting these changes (to match `1.49` and `1.47`), that way we can avoid the check (if someone uses exact version `1.48.0` it will fail, yes, but upgrading to newer patch version shouldn't be a big problem).

We have also been told that there are many improvements for AutoTools in `1.49` and we should probably mark these recipes as `required_conan_version >= 1.49.0`. Of course, that would need to wait at least one month, until we move to `1.49` in CCI (now we will move to `1.48.x` once and if it is available)

**Pull request merged**
