### PR TITLE
[Help Wanted] aws-c-mqtt: add version 0.7.9

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **aws-c-mqtt/0.7.9**

Concerning #7763,
The versions of aws-c-common and aws-c-io are roughly tighted.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
I checked recipes with dependant, but I cloudn't find the reason the error messages.
I always success to create recipe in local environment. 
I'm glad to tell me advise.

```
CMake Error at build/1588f53520db167fd3f81f567135cd61cb8cc3d3/conanbuildinfo.cmake:1153 (add_library):
  add_library cannot create imported target "CONAN_LIB::AWS_aws-c-http"
  because another target with the same name already exists.
```

```
CMake Error at build/1588f53520db167fd3f81f567135cd61cb8cc3d3/conanbuildinfo.cmake:517 (add_library):
  add_library cannot create imported target "CONAN_PKG::AWS" because another
  target with the same name already exists.
```

**Comment by XuhuiSun95** [comment]
> I checked recipes with dependant, but I cloudn't find the reason the error messages. I always success to create recipe in local environment. I'm glad to tell me advise.
> 
> ```
> CMake Error at build/1588f53520db167fd3f81f567135cd61cb8cc3d3/conanbuildinfo.cmake:1153 (add_library):
>   add_library cannot create imported target "CONAN_LIB::AWS_aws-c-http"
>   because another target with the same name already exists.
> ```
> 
> ```
> CMake Error at build/1588f53520db167fd3f81f567135cd61cb8cc3d3/conanbuildinfo.cmake:517 (add_library):
>   add_library cannot create imported target "CONAN_PKG::AWS" because another
>   target with the same name already exists.
> ```

`aws-sdk-cpp/1.9.100` currently have the same issue on `CONAN_LIB::AWS_aws-c-http` and `CONAN_PKG::AWS` when building.

I am not exactly sure why this happened, but I am suspicious about the changes made in this PR #8068 at [section](https://github.com/conan-io/conan-center-index/pull/8068/files#diff-febd61e1038887efed57a4c9211bf8d8732e457ca7a211eb3790dc85aa4b252fL69-R71). 

Can you explain why you made that changes or maybe revert that section and have a try to see if that will fix it?

**Comment by toge** [comment]
@XuhuiSun95 
Thank you for your information.
I agree with you.

I am going to follow "New properties model for the cpp_info" https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info
But it has been too early.  https://github.com/conan-io/conan/pull/10077#issuecomment-980051717

I am going to revert my PRs which include set_property modification.

**Comment by toge** [comment]
Oh...
It has been closed by referenced PR.
I am going to create new PR.

**Pull request closed without merging**
