### PR TITLE
xtr: bump to 2.1.1

### PR DESCRIPTION
**Pull request by choll**
Specify library name and version: xtr/2.1.1

Bump xtr to 2.1.1, I am the library author.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by choll** [comment]
Requires [xtr: migrate to Conan v2 #21111](https://github.com/conan-io/conan-center-index/pull/21111)

**Review by valgur — APPROVED** [review]

**Comment by choll** [comment]
Is another maintainer able to approve this please?

**Review by RubenRBS — APPROVED** [review]
Hi! Sorry about the delay, the PR got stuck waiting for recipe support in Conan 2 and then it took us too long to circle back to it, sorry about that. I've now approved the PR and this should get merged in a few minutes :)

**Comment by choll** [comment]
> Hi! Sorry about the delay, the PR got stuck waiting for recipe support in Conan 2 and then it took us too long to circle back to it, sorry about that. I've now approved the PR and this should get merged in a few minutes :)

No worries, thanks for approving

**Pull request merged**
