### PR TITLE
wasmtime: add version 1.0.1 and support conan V2

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **wasmtime/***

- add version 1.0.0
- remove old versions
- support conan v2

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
There are a release problem on MacOSX.
It was fixed in 1.0.1, but 1.0.1 provides limited binaries.
I'm waiting for next release.

**Comment by uilianries** [comment]
@toge Thank you for the information. I'll mark this PR as blocked, so the CI will not try to rebuild or even mark as stale.

**Comment by toge** [comment]
@uilianries 
Now wasmtime provides all binaries for supported architectures on 1.0.1.
https://github.com/bytecodealliance/wasmtime/issues/4968

Could you remove blocked label?

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
