### PR TITLE
autoconf: remove requires from the package id calculation

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **autoconf/2.69**

- [x] Depends on #2198

- Fixes problem at https://github.com/conan-io/conan-center-index/pull/1986#issuecomment-657462799
- Fixes problem at https://github.com/conan-io/conan-center-index/pull/2103#issuecomment-653607752 (after #2198)

@ericLemanissier 

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
this PR fixes https://github.com/conan-io/conan-center-index/issues/2196

**Comment by madebr** [comment]
@jgsogo 
I guess that syntax is not available yet.
Should I add a comment like:
```
# FIXME: The m4 requirement is actually a build requirement and should be added using self.build_requires("m4/1.4.18", force_host_context=True)
```
?

**Comment by jgsogo** [comment]
Yes, it is, `force_host_context` is available from the very beginning, since `1.23` (https://github.com/conan-io/conan/pull/5592).

**Comment by madebr** [comment]
@jgsogo 
`m4` is also required for `autoconf` itself.
So it should be:
```
def build_requirements(self):
    self.build_requires("m4/1.4.18")
    self.build_requires("m4/1.4.18", force_host_context=True)
```
Will this work?

**Comment by madebr** [comment]
Adding
```
        self.build_requires("m4/1.4.18", force_host_context=True)
```
does not work.

We want `m4` to be visible to the consumers of `autoconf`.

**Comment by jgsogo** [comment]
🤦  Yes, you are totally right, with the `build_requires` it won't be available to consumers.

**Comment by madebr** [comment]
What we want is the following:
```
def build_requirements(self):
    self.build_requires("m4/1.4.18")  # private=True, interface=False

def requirements(self):
    self.requires("m4/1.4.18", private=False, interface=True)
```

Use the same attribute (INTERFACE, PRIVATE, PUBLIC) as cmake uses.

**Comment by madebr** [comment]
@jgsogo 
Can you review this, so other reviewers know whether this pr is ok (or not)?

**Pull request merged**
