### PR TITLE
cppserver: Bump to 1.0.1.0

### PR DESCRIPTION
**Pull request by alejandro-colomar**
**cppserver/1.0.1.0**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Is this blocked and need to be bump the lower lever project? 

https://github.com/conan-io/conan-center-index/blob/bd799cf249f1bef26f07b231f56659fe2679120b/recipes/cppserver/all/conanfile.py#L21

**Comment by alejandro-colomar** [comment]
Yes, I would wait for cppcommon to be built before this one.

**Comment by alejandro-colomar** [comment]
Rebased against master, because it was quite old.  Just to be sure everythings fine.

It will probably break, as cppcommon/1.0.1.0 doesn't yet exist.

**Comment by alejandro-colomar** [comment]
Reopening, as the dependency was merged a few minutes ago.

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
