### PR TITLE
tabulate/1.5

### LINKED ISSUE #16191: [request] tabulate/1.5
### Package Name/Version

tabulate/1.5

### Changelog

https://github.com/p-ranav/tabulate/releases/tag/v1.5

### Context about the new update

The above-mentioned version is newly released by the upstream project and is not yet available as a recipe.
Please add this version.

### PR DESCRIPTION
**Pull request by edisonhello**
Specify library name and version:  **tabulate/1.5**

Recently I help tabulate to add some easy features and improved some efficiency. As the 1.4 version is already been there for a  pretty long time, I also help it to release a new version 1.5. Thus, I think we can also update it in Conan so that we can use the newer version.

Closes #16191.

I plan to try upgrading its recipe to Conan v2 later in a separate PR if v2 is still not necessary for a PR to be merged for now.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by edisonhello** [comment]
I plan to try upgrading its recipe to Conan v2 later in a separate PR if v2 is still not necessary for a PR to be merged for now.

**Comment by prince-chrismc** [comment]
> I plan to try upgrading its recipe to Conan v2 later in a separate PR if v2 is still not necessary for a PR to be merged for now.

V2 does not need to pass but you do need to update the imports for the latest 1.x tooling

**Comment by edisonhello** [comment]
> update the imports for the latest 1.x tooling

Not sure if you mean [this](https://docs.conan.io/1/migrating_to_2.0/recipes.html) - I can't deal with the generator problems after using the new imports.

**Comment by prince-chrismc** [comment]
I found https://github.com/conan-io/conan-center-index/pull/16250 which was 95% there so I will working on getting that PR through.

**Comment by prince-chrismc** [comment]
it was added it #16250 :)

**Pull request closed without merging**
