### PR TITLE
ouster_sdk: add version 0.12.0

### PR DESCRIPTION
**Pull request by jmdaly**
### Summary
Adding new version of `ouster_sdk`:  **ouster_sdk/0.12.0**

#### Motivation
Ouster has released a new version of their C++ SDK for their lidars. I would like to have it in `conan-center`.

#### Details
This is just a version bump, no recipe changes.

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — APPROVED** [review]
Thanks for keeping the available version up-to-date, we appreciate it! :)

**Review by AbrilRBS — COMMENTED** [review]
Woops, one minor thing! Do you have any insight into why the old patch is no longer needed? I suppose it's been fixed upstream in some way or another and our linked PR has stayed open?

**Comment by jmdaly** [comment]
> Woops, one minor thing! Do you have any insight into why the old patch is no longer needed? I suppose it's been fixed upstream in some way or another and our linked PR has stayed open?

Good question about the old patch! Ouster SDK officially only builds on up to C++17, and it looks like the SDK team have made enough source changes in this release that the old patch doesn't apply cleanly anymore. The old patch made it possible to build the Ouster SDK using the C++20 standard.

My thought was that, since it's often ok to link libraries built using one version of the C++ standard with other code built with another version of the standard, leaving this to be limited to C++17 might be ok for users. What do you think? If you'd rather have the functionality to build this package with C++20, I could work on a new patch. Just let me know 😄

**Comment by valgur** [comment]
The fix from that patch has been applied upstream and is no longer necessary: https://github.com/ouster-lidar/ouster_example/blob/20240703/ouster_client/src/curl_client.h#L147-L148
I also tested with `-s compiler.cppstd=20` with Clang and it built without issues for me.

**Review by AbrilRBS — APPROVED** [review]

**Pull request merged**
