### PR TITLE
sfml: bump dependencies and depend on openal-soft instead of deprecated openal

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
ERROR: Missing prebuilt package for 'openal-soft/1.22.2'
```

@danimtb @uilianries another missing prebuilt package here for conan v2.

**Comment by SpaceIm** [comment]
> ```
> ERROR: Missing prebuilt package for 'openal-soft/1.22.2'
> ```
> 
> @danimtb @uilianries another missing prebuilt package here for conan v2.

I've opened https://github.com/conan-io/conan-center-index/pull/16520

**Comment by SpaceIm** [comment]
draft until https://github.com/conan-io/conan-center-index/pull/16520 is merged

**Comment by SpaceIm** [comment]
```
sfml/2.5.1 (test package): Running test()
sfml/2.5.1 (test package): RUN: ./test_package
dyld: Symbol not found: __cg_png_create_info_struct
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/jenkins/w/prod-v2/BuildSingleReference@2/p/libpnfca29890dde11/p/lib/libPng.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
/bin/sh: line 1: 93732 Abort trap: 6           ./test_package
```

@jcar87 it seems to be a very similar issue than the one seen in v2 pipeline for boost in test package.

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
