### PR TITLE
range-v3: add versions 0.3.7, 0.4.0, and 0.5.0

### PR DESCRIPTION
**Pull request by romariorios**
**range-v3/0.3.7**, **range-v3/0.4.0**, and **range-v3/0.5.0**

Some projects might have an extensive codebase that still depends on older range-v3 versions. These projects might want to migrate to Conan, but migrating all the existing codebase from version 0.3.7 to 0.9.1 might be too much work and delay the Conan migration. To make the migration easier, I decided to make these older versions available on cci, so that these projects can have the opportunity to migrate to Conan without speding time on a very time-consuming migration first.

This change adds no new dependencies and doesn't affect the existing range-v3 versions in any way. It doesn't even touch the recipe really. The only real code change was to the test case so it could work with both the older and newer range-v3 versions.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] ~I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.~ (N/A, the recipe wasn't changed)
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by Bernhard-L** [comment]
@romariorios 

 "/experimental:preprocessor" is deprecated since VS2019 (16.5) and gives a lot of warnings, when compiling
 so checking  `if self.settings.compiler == "Visual Studio": `
 isn't enough.
 
 https://docs.microsoft.com/en-us/cpp/build/reference/experimental-preprocessor?view=msvc-170

**Comment by elqueffo** [comment]
@[romariorios](https://github.com/romariorios)

This MR causes build issues with other non-related packages such as capnproto because of the `/experimental:preprocessor` flag, especially on newer MSVC builds. Also, the flag is deprecated as Bernhard-L notes.

This is a clear regression and should be reverted/fixed.

**Comment by romariorios** [comment]
> @[romariorios](https://github.com/romariorios)
> 
> This MR causes build issues with other non-related packages such as capnproto because of the `/experimental:preprocessor` flag, especially on newer MSVC builds. Also, the flag is deprecated as Bernhard-L notes.
> 
> This is a clear regression and should be reverted/fixed.

Unfortunately, I have no access to an installation of MSVC. Do you think checking MSVC's version and choosing between `/experimental:preprocessor` and `/Zc:preprocessor` would solve the issue?

**Comment by SSE4** [comment]
`/experimentl:preprocessor` is explicitly mentioned in their [README](https://github.com/ericniebler/range-v3/tree/0.9.0):
```
Visual Studio 2019 Preview 4 (or later) on Windows, with some caveats due to range-v3's strict conformance requirements:
range-v3 needs /std:c++17 /permissive-
range-v3 needs a fully conforming preprocessor, so /experimental:preprocessor is necessary. Note that the conforming preprocessor diagnoses C5105 "macro expansion producing 'defined' has undefined behavior" in some of the Windows SDK headers, so you'll probably want to suppress that warning with /wd5105.
```

**Comment by elqueffo** [comment]
They have removed that requirement in 2020: https://github.com/ericniebler/range-v3/commit/cce62b1bdf5b004628fa5ecf34d50d44637cd317

Having it here means other packages break if used at the same time because the preprocessor syntax changes. A number of other packages expect the default MSVC behavior (non-conformant) and then do not build at all if range-v3 package is in the mix.

If it is needed for older versions, at least exclude it from newer range-v3 versions.

**Comment by SSE4** [comment]
yes, it definetely makes sense to only apply `/experimentl:preprocessor` for versions need it

**Pull request merged**
