### PR TITLE
Add OpenEXR to 3.1.9

### PR DESCRIPTION
**Pull request by EstebanDugueperoux2**
Specify library name and version:  **openexr/3.1.9**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by EstebanDugueperoux2** [comment]
Hi @madebr , @SpaceIm , @ericLemanissier ,

could you review this PR?

Regards.

**Review by ericLemanissier — APPROVED** [review]
FYI the changes would have been merge automatically if you had made a PR to bump the requirement, then another to add new version and remove the old version

**Comment by EstebanDugueperoux2** [comment]
Hi @ericLemanissier,

I have tried to create a PR through https://qchateau.github.io/conan-center-bot/#/updatable but I'm not authorized.
And as I have added a second commit here to remove an old release making a msvc build fails, I'm afraid that the automatically created Bump PR would have also its pipeline fails because of msvc build.

Regards.

**Comment by ericLemanissier** [comment]
I'm pretty sure you can create a PR from qchateau's conan-center-bot. Just make sure you modify the PR description or github refuses.
But what I said in my last message has nothing to do with qchateau's bot: conan center will automatically merge successful PRs (even without approval) if they only add and/or remove versions to/from config.yml and conandata.yml.
Likewise, it will automatically merge PRs if they only bump requirements versions in conanfile.py

**Comment by EstebanDugueperoux2** [comment]
> I'm pretty sure you can create a PR from qchateau's conan-center-bot. Just make sure you modify the PR description or github refuses. But what I said in my last message has nothing to do with qchateau's bot: conan center will automatically merge successful PRs (even without approval) if they only add and/or remove versions to/from config.yml and conandata.yml. Likewise, it will automatically merge PRs if they only bump requirements versions in conanfile.py

I have tried again on "coin-clp" recipe example, and even with some description changes, when clicking on "Create pull request" I get a "Pull request creation failed. Validation failed: must be a collaborator" message.

**Comment by ericLemanissier** [comment]
Indeed. I have the same error as you. Please report it to https://github.com/qchateau/conan-center-bot/issues. It's probably because @qchateau needs not sign the new CLA. In the mean-time, you can try with https://ericlemanissier.github.io/conan-center-bot/#/updatable

**Comment by qchateau** [comment]
Did it change recently ? I approved it in the past

**Comment by ericLemanissier** [comment]
I don't think it changed since https://github.com/qchateau/conan-center-bot/issues/109. The error must come from something else

**Comment by EstebanDugueperoux2** [comment]
Waiting bot fix, @qchateau could you review/approve my PR?

**Comment by qchateau** [comment]
You overestimate my powers here :D

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
GitHub recently made changes https://github.blog/changelog/2023-06-06-security-enhancements-to-required-approvals-on-pull-requests/ and it does impact how it looks at the base of a branch when creating PRs

https://github.com/orgs/community/discussions/55772
https://github.com/cli/cli/issues/4801

It might be some internal undocumented spam protecting... AFAIK there is no repo setting to limit this 🤔

**Pull request merged**
