### PR TITLE
Add mozjpeg/3.3.1

### PR DESCRIPTION
**Pull request by theirix**
Specify library name and version:  **mozjpeg/3.3.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by theirix** [comment]
Seems like `libtool` is missing on a build macine (possibly undefined macro: AC_PROG_LIBTOOL)

**Comment by SSE4** [comment]
@theirix yeah, it's already known infrastructure issue

**Comment by danimtb** [comment]
`libtool` is now installed

**Comment by theirix** [comment]
Yes, thanks. It seems the system `/usr/bin/nasm` does not work too (even on my local mac), homebrew nasm is required. But it is enough just to add nasm as a Conan build_requirements as it had been done for libjpeg-turbo recipe.

**Comment by uilianries** [comment]
@theirix https://github.com/theirix/conan-center-index/pull/1

**Comment by theirix** [comment]
> @theirix [theirix#1](https://github.com/theirix/conan-center-index/pull/1)

Thanks, looks great! Using CCI patches simplify the recipe, especially the need for the explicit use of `_source_subfolder`.

**Pull request merged**
