### PR TITLE
[google-cloud-cpp] update to v2.15.1

### PR DESCRIPTION
**Pull request by coryan**
Specify library name and version:  **google-cloud-cpp/2.15.1**

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by coryan** [comment]
I cannot see the build errors reported in jenkins/pr-merge.  Can somebody help me troubleshoot these?

**Comment by RubenRBS** [comment]
It has not yet finished processing, I'll double check inf a few hours and post the links for you if the bot does not :)

**Comment by coryan** [comment]
Seems like I need to rebase again to pick #19743: 

```
ERROR: Conflict in openssl/3.1.2:
    'openssl/3.1.2' requires 'zlib/1.2.13' while 'protobuf/3.21.12' requires 'zlib/1.3'.
    To fix this conflict you need to override the package 'zlib' in your root package.
 ```

But there is a separate error that seems more confusing:

```
ERROR: Missing prebuilt package for 'libcurl/8.2.1'
Check the available packages using 'conan list libcurl/8.2.1:* -r=remote'
or try to build locally from sources using the '--build=libcurl/8.2.1' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```
https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19717/11-macos-clang/google-cloud-cpp/2.5.0//summary.json

**Comment by coryan** [comment]
This is too confusing, I am going to start over.

**Pull request closed without merging**
