### PR TITLE
glib: enable cross-compilation

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **glib/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
I've already tried to enable cross-build in a Meson based recipe, `inih`: https://github.com/conan-io/conan-center-index/pull/6678

It doesn't work yet (unless there was improvement in Meson toochain and new Meson helper by that time). Moreover, this new combo doesn't automatically set stuff like libdir, bindir etc.

**Comment by ericLemanissier** [comment]
ok, so we just got to the same point as @SpaceIm in https://github.com/conan-io/conan-center-index/pull/6678#issuecomment-892751626 : `ERROR: 'c' compiler binary not defined in cross or native file`
AFAIU, it should be solved with https://github.com/conan-io/conan/pull/8353. Does it fail only because CCI profiles does not set CC, CXX etc ? @SSE4 what do you think ?

**Comment by ericLemanissier** [comment]
Friendly ping @SSE4
> ok, so we just got to the same point as @SpaceIm in [#6678 (comment)](https://github.com/conan-io/conan-center-index/pull/6678#issuecomment-892751626) : `ERROR: 'c' compiler binary not defined in cross or native file` AFAIU, it should be solved with [conan-io/conan#8353](https://github.com/conan-io/conan/pull/8353). Does it fail only because CCI profiles does not set CC, CXX etc ? @SSE4 what do you think ?

**Comment by SSE4** [comment]
in CCI, we don't set CC or CXX in profiles.

CMake is very smart, it detects the default Xcode (apple-clang) compiler automatically, even for cross-compiling.
Meson is on opposite side, it's extremely dumb (and that's good - no hidden magic), but it won't find any compiler if you don't set it explicitly, in case of cross-compiling.

that's their fundamental difference. I don't know if conan's `MesonToolchain` should have this missing auto-detection logic.
maybe it's worth providing it, at least for some popular platforms (iOS, Android, etc).

for instance, meson has these recommended configs for iOS/tvOS:
https://github.com/mesonbuild/meson/blob/master/cross/iphone.txt
https://github.com/mesonbuild/meson/blob/master/cross/tvos.txt

maybe it's worth generating something like that by default, if no explicit CC/CXX are provided in the profile.

**Pull request closed without merging**
