### PR TITLE
cnats: New package

### LINKED ISSUE #23001: [request] nats.c/v3.8.0
### Package Name/Version

nats.c/v3.8.0

### Webpage

https://nats.io/

### Source code

https://github.com/nats-io/nats.c

### Description of the library/tool

NATS is an open source messaging system (sometimes called message-oriented middleware). The core design principles of NATS are performance, scalability, and ease of use. 'JetStream' is the (optionally enabled) built-in persistence layer that adds streaming, queues, at-least-once and exactly-once delivery guarantees, historical data replay, decoupled flow-control and key/value store functionalities to Core NATS.

nats.c is the client interface library for the C language.

(Taken from https://en.wikipedia.org/wiki/NATS_Messaging for the lack of being able write a better description myself)

### PR DESCRIPTION
**Pull request by Ahajha**
Specify library name and version:  **cnats/3.8.0**

Resolves #23001 

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Ahajha** [comment]
@robinchrist Feel free to add feedback, mainly what kinds of options you would see useful in the package :)

**Comment by Ahajha** [comment]
@uilianries Should have checked prior to making a branch, but your PR looks a lot closer to working than mine. Would you mind if I branched from yours instead?

**Comment by uilianries** [comment]
@Ahajha Thank for pinging. Let me check it today, I guess it worth another try.

**Comment by Ahajha** [comment]
Closing in favor of #18444

**Pull request closed without merging**
