### PR TITLE
(#22506) arrow: fix config_options

### PR DESCRIPTION
**Pull request by wgtmac**
Specify library name and version:  **arrow/15.0.0**

Fix https://github.com/conan-io/conan-center-index/issues/22506

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by wgtmac** [comment]
@kou @raulcd

**Comment by valgur** [comment]
See #21669.

Thank you for the PR, but this approach approach would break most of the handling of dependent option values.

**Comment by raulcd** [comment]
We can try to apply: https://github.com/conan-io/conan-center-index/pull/21669 to our sync PR: https://github.com/apache/arrow/pull/39729

**Comment by wgtmac** [comment]
@valgur I have applied https://github.com/conan-io/conan-center-index/pull/21669 to https://github.com/apache/arrow/pull/39729 and it works. Could you help moving forward https://github.com/conan-io/conan-center-index/pull/21669? Then I can sync it to the arrow repo. Thanks!

**Comment by wgtmac** [comment]
@valgur Do you mind taking a look at my proposed fix?

**Comment by wgtmac** [comment]
Also ping @toge @RubenRBS @uilianries for help.

To provide the context, this PR is based on https://github.com/conan-io/conan-center-index/pull/21669 (by @valgur) with a few lines to fix the `simd_level` option.

**Review by valgur — APPROVED** [review]

**Comment by wgtmac** [comment]
Thanks for the review! @valgur

**Comment by wgtmac** [comment]
@toge Could you help review this? It would be good to get this in before the Arrow community releasing 15.0.1. Thanks!

**Comment by raulcd** [comment]
@RubenRBS @toge @uilianries could we get a review and a merge, I am about to release 15.0.1 and it would be good for us to get this merged before. Thank you very much!

**Comment by wgtmac** [comment]
Thanks @RubenRBS for the assignment!

Hi @danimtb, would you mind taking a look?

**Comment by raulcd** [comment]
Hi, we have just released 15.0.1 but I am not going to create a PR on conan until this is merged as we should merge this first.

**Comment by wgtmac** [comment]
@RubenRBS Gentle ping. Could you help review this?

**Comment by danimtb** [comment]
Hi @wgtmac and sorry for the delayed response.

This recipe has given us some trouble in the past with several PRs trying to improve the management of options. There are too many of them and some of them affect others or give them a spcific value. 

We have discussed this internally in the conan team and we think that we don't want to introduce more code in this recipe con manage options. Instead, we would like to simplify the recipe and remove any kind of automatic management of options (as it has proved to be problematic) and just restrict the combinations in the ``validate()`` method and direct the user to input the correct value for each option.

We believe this would be the less problematic approach that hopefully would solve the issues of this recipe regarding options and its management.

Hope that it make sense. Thank you!

**Comment by danimtb** [comment]
> IMHO, the remaining challenge is to figure out the third-party dependency requirement based on the user options. Will someone from the Conan community work on this?

Yes, we will try to work on that!

**Comment by wgtmac** [comment]
That's awesome! Looking forward to the fix. @danimtb

**Comment by valgur** [comment]
Can be closed after #23163 was merged.

**Pull request closed without merging**
