### PR TITLE
[protobuf] Revert "improve discovery of protoc executable in build context"

### LINKED ISSUE #21737: protobuf recent update broke protoc integration
### Description

new implementation as https://github.com/conan-io/conan-center-index/pull/20089 of searching protoc actually finds system protoc instead the one build by conan, as a result usage of the protoc leads to `error: incompatible with your Protocol Buffer headers. Please                     #error incompatible with your Protocol Buffer headers. ....` linux ubuntu 22.04 with default protoc installed from apt-get

### Package and Environment Details

* Package Name/Version: **protobuf/3.21.12**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **Clang 14**
* Docker image: **conanio/gcc8**
* Conan version: **conan 1.18.0**
* Python version: **Python 3.10.12**

### Conan profile
default

### Steps to reproduce

cmake build with dependencies

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

### PR DESCRIPTION
**Pull request by uilianries**
The PR #20089 is causing side-effects listed in the issue #21737 and is blocking #22244

fixes #21737

### CODE REVIEW

**Comment by SpaceIm** [comment]
Please no, openvino is likely broken since it's missing protobuf in build requirements. Issues reported in https://github.com/conan-io/conan-center-index/issues/21737 are unclear and missing logs to investigate.

**Comment by ilya-lavrenov** [comment]
> Please no, openvino recipe is likely broken since it's missing protobuf in build requirements in case of native build. It was working by luck. Issues reported in #21737 are unclear and missing proper issue template informations to investigate.

Thanks, let's check https://github.com/conan-io/conan-center-index/pull/22289

**Comment by SpaceIm** [comment]
Could you try exactly what is suggested in https://github.com/conan-io/conan-center-index/pull/22244#issuecomment-1910770387 please?

- VirtualBuildEnv since there are build requirements
- Do not add protobuf & flatbuffers to build requirements if 1 profile (due to potential issues in conan v1 in case of dependencies of these libs overridden by users).
- Add VirtualRunEnv in build scope if 1 profile

**Comment by ilya-lavrenov** [comment]
Looks like it can be closed

**Comment by uilianries** [comment]
Closing this issue as the PR https://github.com/conan-io/conan-center-index/pull/22244 is no longer blocked after updating protobuf usage.

**Pull request closed without merging**
