### PR TITLE
paho-mqtt-c: remove anl library from system libs

### PR DESCRIPTION
**Pull request by mtudan**
Remove `anl` library from default system libraries if on Linux because it is not available on non-glibc distros like Alpine. This will fix building your apps on e.g. Alpine that link with `paho-mqtt-c` library. We might use some logic to determine if `anl` is available like the upstream project does.

Specify library name and version:  **paho-mqtt-c/1.3.12**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
@SpaceIm  You added anl in https://github.com/conan-io/conan-center-index/pull/17088/files#diff-cefdb38dd5cec800413f548cb236f4f8cb7fd28165ef036164d59b456553cbd4R121 do you happen to recall why?

**Comment by SpaceIm** [comment]
> @SpaceIm You added anl in https://github.com/conan-io/conan-center-index/pull/17088/files#diff-cefdb38dd5cec800413f548cb236f4f8cb7fd28165ef036164d59b456553cbd4R121 do you happen to recall why?

Because it was reported by hooks: https://github.com/conan-io/conan-center-index/pull/17088#issuecomment-1513505200

See also https://github.com/eclipse/paho.mqtt.c/blob/7db21329301b1f527c925dff789442db3ca3c1e7/src/CMakeLists.txt#L67-L70, but yes it's optional. There is not enough granularity in conan profiles to predict if anl is required as a system libs or not.

**Comment by prince-chrismc** [comment]
Cheers! Thanks for helping :)

**Comment by mtudan** [comment]
@prince-chrismc @franramirez688 @jcar87

Any news with this PR? That's quite old right now.

**Comment by uilianries** [comment]
It's possible to customize the settings, adding distro: https://docs.conan.io/2/reference/config_files/settings.html#adding-new-settings

It could be used for this case, having a condition to not add `anl` in case distro Alpine, for instance.

**Pull request closed without merging**
