### PR TITLE
[qt] fix: conanfile.py RuntimeError: OrderedDict mutated during iteration

### PR DESCRIPTION
**Pull request by kaipenglu**
Specify library name and version:  qt/all

I meet this error when run `conan install .. -s build_type=Release --build missing` with python 3.10.8: 

> ERROR: qt/5.15.7: Error in package_info() method, line 1450
        for c in self.cpp_info.components:
        RuntimeError: OrderedDict mutated during iteration

My project conanfile.txt:
```
[requires]
qt/5.15.7

[generators]
cmake_multi
qt
cmake_find_package_multi
cmake_paths

[options]
qt:shared=True
qt:qttools=True
qt:qtserialbus=True
```

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@kaipenglu thanks ! Can you please consider https://github.com/kaipenglu/conan-center-index/pull/1, which should fix the qtserialbus issue, and raise an exception if the situation happens for other modules

**Comment by kaipenglu** [comment]
@ericLemanissier thanks! I didn't know qtserialbus depends on qtserialport. Adding `qt:qtserialport=True` in conanfile.txt will pass.  I think changing function _get_corrected_reqs in qt5 same as in qt6 is enough.

**Comment by ericLemanissier** [comment]
@kaipenglu actually, the change in `_get_corrected_reqs` is just here to produce a clearer error message in the already bugged situation. setting option `qt:qtserialport=True` works around the problem. The actual fix of your original situation is [this line](https://github.com/kaipenglu/conan-center-index/pull/1/files#diff-a8b177bc27deaf5165ec2e51c7e70bb42587ec0352c5bc2711524d5240e03737R1239). `qtserialport` is not required for `qtserialbus`, it is an optional dependency. This condition must be reflected in the component's requirements declaration.

**Comment by kaipenglu** [comment]
@ericLemanissier Sorry, I'm new to QT. 😅 I have merged your PR https://github.com/kaipenglu/conan-center-index/pull/1.

**Comment by ericLemanissier** [comment]
Thanks ! did you see the bot's message ?
> ### Conan v1 pipeline
> Sorry, the build is only launched for Access Request users. You can request access [writing in this issue](https://github.com/conan-io/conan-center-index/issues/4).

**Review by ericLemanissier — APPROVED** [review]

**Review by jwillikers — DISMISSED** [review]

**Comment by ericLemanissier** [comment]
@kaipenglu can you please close/reopen this PR to trigger CI ? It should start now that you are an an authorized user.

**Review by uilianries — DISMISSED** [review]

**Comment by ericLemanissier** [comment]
@kaipenglu https://github.com/kaipenglu/conan-center-index/pull/2 should solve this error

**Review by ericLemanissier — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by ericLemanissier** [comment]
this error will be fixed by https://github.com/conan-io/conan-center-index/pull/14821 when this will be merged. I just made a PR of your branch into @EstebanDugueperoux2 's branch, so that both changes are merged at once, cf https://github.com/EstebanDugueperoux2/conan-center-index/pull/3

**Comment by kaipenglu** [comment]
@ericLemanissier Should I close this PR?

**Comment by ericLemanissier** [comment]
@kaipenglu https://github.com/conan-io/conan-center-index/pull/14821 has just been merged, so you now have to merge master branch into your branch to get the fix.

**Comment by ericLemanissier** [comment]
@kaipenglu the hook error will be fixed if you merge https://github.com/kaipenglu/conan-center-index/pull/3

**Review by jwillikers — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@prince-chrismc @uilianries @jcar87 this PR has `Failed` label, but it can be merged. It just misses an approval from the team. Thanks !

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
#15130 :)

**Comment by ericLemanissier** [comment]
`fatal error LNK1180: insufficient disk space to complete link`
Can this build be restarted ?

**Comment by prince-chrismc** [comment]
@danimtb @uilianries looks like qt needs a bigger pod instance 😱

**Comment by ericLemanissier** [comment]
Well it has been happening for several weeks now, for all PRs on qt, but it always ends up going away by restarting.

**Comment by uilianries** [comment]
We have a configuration for larger builds, which includes Qt already, it seems like we need to update it and increase more resources.

**Pull request closed without merging**
