### PR TITLE
Add new recipe - bitserializer

### PR DESCRIPTION
**Pull request by PavelKisliak**
Specify library name and version: bitserializer/0.9

Description: Core part of C++ 17 library for serialization to JSON, XML, YAML
Home page: https://bitbucket.org/Pavel_Kisliak/bitserializer

Target formats for serialization are implemented in separate modules, they are pushed in the separate PRs.

- [ √ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ √  ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ √  ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ √  ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by PavelKisliak** [comment]
I see the error in the build log:
> object_traits.h:8:20: fatal error: optional: No such file or directory

it's related to include std::optional, which came with c++ 17 standard, in the recipe already exists check:
```
    def configure(self):
        if self.settings.get_safe("compiler.cppstd"):
            tools.check_min_cppstd(self, "17")
```

The build failed on GCC-5, but the library requires minimum GCC-8, CLang-7, VS-2017.
Should I add some additional configuration or there are needed some changes on CI?

**Comment by uilianries** [comment]
> The build failed on GCC-5, but the library requires minimum GCC-8, CLang-7, VS-2017.

Where did you obtain such information? If it's documented by the upstream, please, add a condition to check it.

**Comment by PavelKisliak** [comment]
> 
> 
> > The build failed on GCC-5, but the library requires minimum GCC-8, CLang-7, VS-2017.
> 
> Where did you obtain such information? If it's documented by the upstream, please, add a condition to check it.

Yes, it is documented requirements: https://bitbucket.org/Pavel_Kisliak/bitserializer
Thank you @uilianries, I've added checks and now build is green.

**Comment by uilianries** [comment]
@PavelKisliak Thanks for the clarification!

**Comment by PavelKisliak** [comment]
@jgsogo, Thank you very much for suggested help and for point to issue with link "stdc++fs", I did it in my Cmake and really forget to make the same in the recipe for Conan (will commit a fix).

About new components feature in the Conan - it is very cool feature and sound interesting for me, but need a bit more clarification and discussion.

A brief excurse to history - about one year ago, when I decided to publish previous version to VCPKG, I was think a lot which model is more suitable for my library,  VCPKG was already supported components at this time (features in VCPKG's terminology). As I also planned to publish to Conan and may be some other package managers, I was think about consistency - for able to have the same set of libraries in different managers. This also should help consumers easily switch between package managers. As you can see, I've already made PRs to Conan for other modules of BitSerializer.
If make decision to make BitSerializer with components in the Conan, will be logical to do the same in the VCPKG (may be it will not pain as library is young and there are no projects which use it, as I know).

And now let's go to questions about technical requirements to package manager.
At first, each component should be able to have its own dependencies for avoid install redundant libraries (as I understand the components in the Conan will can do it).
The second - each component should be able to have its own available platforms list, because in my case not all of base libraries (third-party dependencies) supported all platforms, for example <ryaml> currently does not support MacOS.

Please check, if all of described requirements aren't problem and you still think that new components feature is good fit to BitSerializer, we can pause the PR and wait new Conan release.

**Comment by jgsogo** [comment]
Hi!

Components are defined in the `package_info()` function where you have access to `settings` and `options`, so you can implement any logic you want based to declare the same or different components based on the `host` OS or to modify the flags and dependencies they are propagating to consumers.

Each component can declare as dependencies/`requires` other components in the same package and other packages (that were added to the `requires` in the `conanfile.py`). So you could do something like

```python
requires = "cpprestsdk/....", "rapidjson/....", "ryml/...."

def package_info(self):
    ...
    self.cpp_info.components["core"]....
    ....
    if self.settings.os != "Windows":
        # Component 'cpprestjson' is available for any system but Windows
        self.cpp_info.components["cpprestjson"].requires("core", "cpprestsdk::cpprestsdk")
```

and in the near future we will try to let components depend on components of another packages, so instead of using full `cpprestsdk` you could use just the component `cpprestsdk::cpprest` and have more granularity.

**With or without components your package will always provide a `bitserializer::bitserializer` target** that includes all the components defined in the conanfile. So you can start with a recipe without components, your consumers can use `bitserializer::bitserializer` and for the next iteration we can improve the recipe adding the _components feature_ to let consumers more fine-grained control about the libraries they are linking to.

**Comment by PavelKisliak** [comment]
Hi @jgsogo !

Sounds good for me, just for final confirmation:
Are you suggest for now make just one recipe "bitserializer" which will include all supported formats? And cancel PR's with separate modules #1597,  #1601 and #1602?

At this time I can start with **JSON** support (with implementation based on **RapidJson**), as **PugiXml** isn't available now in the **Conan-center** (need to port from Bincrafters) and **Ryaml** also doesn't exist in Conan (but author of the module for BitSerializer will try to submit PR with that recipe).

**Comment by jgsogo** [comment]
Hi! I think it makes sense to have one single recipe for `bitserializer` and use components for the different modules, as there is only one repository with the sources for all of this modules. I think it is a better approach, but you are the author of the library itself, so your opinion is really important. 

Will those modules live together with the _core_ of the library? Are they going to have _always_ the same version of the core library? Having it all in a single recipe would then be easier to maintain.

**Comment by PavelKisliak** [comment]
My main reason why I splitted library to several modules were dependent libraries.
Ability to have different versions of modules isn't important benefit in comparison with difficulties in maintain multiply packages, particularly when need to publish not in one package manager.

Thanks so much, that you are stopped me from publish multi packages, let's release `BitSerializer` with only one enabled module (based on `RapidJson`) and wait the new release of `Conan`.
The components is really needed feature!

I will update the recipe, please check and let me know if you will see any other issues.

**Comment by PavelKisliak** [comment]
Hi @jgsogo ,
Now, I have new version of BitSerializer (0.10), please don't merge this recipe before I update it to latest.

**Pull request merged**
