### PR TITLE
DCMTK: Add `dcmect` submodule

### PR DESCRIPTION
**Pull request by nagayev**
Specify library name and version:  **dcmtk/3.6.7**

I've got link error while tring to compile this code:
```cpp
EctEnhancedCT* concat = NULL;
EctEnhancedCT::loadDataset(*dataset, concat);
size_t numFrames;
numFrames = concat->getNumberOfFrames();
EctEnhancedCT::FramesType frames = concat->getFrames();
Uint16* frame                    = OFget<EctEnhancedCT::Frames<Uint16> >(&frames)->getFrame(0);
assert(frame != nullptr);
```

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by nagayev** [comment]
@SpaceIm Can you help please?
What is wrong with my code?

**Comment by uilianries** [comment]
@nagayev Thank you for your contribution! Please, read the bot message about requesting access to Conan Center Index, it's a standard step to contribute. For more information, please, read https://github.com/conan-io/conan-center-index/tree/master/docs/adding_packages

**Comment by uilianries** [comment]
@nagayev Did you open an issue reporting your error? At least, could you please detail a bit more your error, with a full build log, for instance. It's hard to check your PR without a full context of the problem.

**Comment by valgur** [comment]
This was fixed by https://github.com/conan-io/conan-center-index/pull/22187/files#diff-e99ec7de8d874cffccfd2d1c2e02ab45586b4d2443ab73ca71f2fb9907bfc66bR319

Can be closed.

**Pull request closed without merging**
