### PR TITLE
update cmake , add version 3.18.1

### PR DESCRIPTION
**Pull request by a4z**
Specify library name and version:  **cmake/3.18.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
welp RIP #2348

**Comment by Croydon** [comment]
Duplicate of #2222

**Comment by a4z** [comment]
You can not add 2 new version s in one  pr, or can you?
I remember running into some troubles by having more than one change in a OR

**Comment by jgsogo** [comment]
You can modify several references at the same time if all of them use the same conanfile.py file (90% sure 😄 )

**Pull request merged**
