### PR TITLE
Boost/1.72.0/mpi

### PR DESCRIPTION
**Pull request by oleurodecision**
Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

(note that this PR replaces the #2842 for branch name change)

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Are you have a problem in particular that requires this?

From https://www.boost.org/doc/libs/1_72_0/doc/html/mpi/getting_started.html#mpi.getting_started.config.bootstrap

> Alternatively, you can explicitly provide the list of Boost libraries you want to build. Please refer to the --help option of the bootstrap script.

Which I am pretty sure the recipe does here

https://github.com/conan-io/conan-center-index/blob/b247eb984bf114e05a53d2768b85ac25768bb31b/recipes/boost/all/conanfile.py#L533-L538

**Comment by prince-chrismc** [comment]
@SSE4 I think this PR can be closed, it was fixed in the numerous Boost PRs

**Comment by prince-chrismc** [comment]
>  I think this PR can be closed, it was fixed in the numerous Boost PRs

**Comment by prince-chrismc** [comment]
CI status did not update correctly

**Comment by prince-chrismc** [comment]
Can you confirm the recipe revision you are using?

OP only modified one version... I assume this needs to be applied to all of them

**Comment by oleurodecision** [comment]
Happy to this one alive again.
Well, could only test the patch on 1.72 at the time of writing. I have time to spend on the subject these comnig days, so if required I can update the PR on current master, and check for the other handled versions (1.69 to 1.76).

Please let me know if anything is required or desired from me.

**Review by SSE4 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
