### PR TITLE
glib/all: bump libgettext

### PR DESCRIPTION
**Pull request by ericLemanissier**
Generated and committed by [Conan Center Bump Deps](https://github.com/ericLemanissier/conan-center-index-bump-deps)
Find more updatable recipes in the [GitHub Pages](https://ericlemanissier.github.io/conan-center-index-bump-deps/)

Specify library name and version:  **glib/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
AFAIK we want old glib versions to stick around longer than for usual libraries, will check with the team

**Comment by ericLemanissier** [comment]
Ok, I don't mind reintroducing some old versions. I just wanted to make the recipe simpler and CI faster.
The full picture:
- [glib/2.72.4](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index%20glib%2F2.72.4&type=code) is not used
- [glib/2.73.3](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.73.3&type=code) is used by:
  - pango which is being bumped by https://github.com/conan-io/conan-center-index/pull/18874
- [glib/2.74.1](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.74.1&type=code) is not used
- [glib/2.75.0](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.75.0&type=code) is not used
- [glib/2.75.1](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.75.1&type=code) is not used
- [glib/2.75.2](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.75.2&type=code) is used by:
  - libnice which is being bumped by https://github.com/conan-io/conan-center-index/pull/19037
  - avahi which is being bumped by https://github.com/conan-io/conan-center-index/pull/18196
  - aravis which is being bumped by https://github.com/conan-io/conan-center-index/pull/18180
- [glib/2.76.0](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.76.0&type=code) is used by:
  -  gdk-pixbuf whic is being bumped by https://github.com/conan-io/conan-center-index/pull/19491
- [glib/2.76.1](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.76.1&type=code) is used by:
  -  libvips which is being bumped by https://github.com/conan-io/conan-center-index/pull/18453
- [glib/2.76.2](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+glib%2F2.76.2&type=code) is used by:
  - graphene which is being bumped by https://github.com/conan-io/conan-center-index/pull/19393 (cannot be merged before this PR, because there is a conflict in dependencies versions)

**Comment by ericLemanissier** [comment]
So the only dependants non straightforward to update are livips and pango, but the problem they have do not come from glib. All other PR just miss reviews.
Do you think we should keep glib/2.73.3 and glib/2.76.1?

**Comment by ericLemanissier** [comment]
blocks:
- https://github.com/conan-io/conan-center-index/pull/19644

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6121382020)

**Comment by RubenRBS** [comment]
After checking, I think we're good to remove old versions and keep only the latest patch for each minor, so let's focus on bumping pango and libvips so we can delete those :)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6129955252)

**Comment by ericLemanissier** [comment]
So we are good to go like this?

**Comment by RubenRBS** [comment]
Yes, but we first need to merge the other PRs you linked beforehand, let me prioritize those

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6259074597)

**Review by jwillikers — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Comment by RubenRBS** [comment]
Will re-trigger after https://github.com/conan-io/conan-center-index/pull/20218 is merged

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
