### PR TITLE
libkml: add components (partial) + bump dependencies + delete fPIC if shared

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **libkml/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

`libkml` doesn't export a namespace. Therefore this PR doesn't properly model imported targets names.

### CODE REVIEW

**Comment by SpaceIm** [comment]
path length issue probably coming from CI modifications: https://github.com/conan-io/conan-center-index/pull/2182#issuecomment-657541926

**Comment by uilianries** [comment]
@danimtb Here we have the same problem related to Windows max path length:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018: System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "kmlconvenience.dir\Release\kmlconvenience.tlog\ParallelCustomBuild.read.1.tlog". Path: kmlconvenience.dir\Release\kmlconvenience.tlog\ParallelCustomBuild.read.1.tlog exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\J\workspace\onan-center-pull-request_PR-2203\4\0_4\.conan\data\libkml\1.3.0\_\_\build\6f2abf8140002a3da320bdd0d05b6ffd269dd750\build_subfolder\source_subfolder\src\kml\convenience\kmlconvenience.vcxproj]

**Comment by uilianries** [comment]
@danimtb Here we have the same problem related to Windows max path length:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018: System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "kmlconvenience.dir\Release\kmlconvenience.tlog\ParallelCustomBuild.read.1.tlog". Path: kmlconvenience.dir\Release\kmlconvenience.tlog\ParallelCustomBuild.read.1.tlog exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\J\workspace\onan-center-pull-request_PR-2203\4\0_4\.conan\data\libkml\1.3.0\_\_\build\6f2abf8140002a3da320bdd0d05b6ffd269dd750\build_subfolder\source_subfolder\src\kml\convenience\kmlconvenience.vcxproj]

The path `C:\J\workspace\onan-center-pull-request_PR-2203\4\0_4\.conan\data\libkml\1.3.0\_\_\build\6f2abf8140002a3da320bdd0d05b6ffd269dd750\build_subfolder\source_subfolder\src\kml\convenience\kmlconvenience.vcxproj` is okay, it's 206 chars. But `kmlconvenience.dir\Release\kmlconvenience.tlog` is part of `FullPath` and probably passed to 260 chars.

**Comment by danimtb** [comment]
Relaunching the build after https://github.com/conan-io/conan-center-index/wiki/Deployment-Changelog#24-july-2020---1252-cest

**Comment by uilianries** [comment]
@danimtb Thanks a lot! All working good now!

**Pull request merged**
