### PR TITLE
boost: fix i18n_backend=icu support for version 1.7{1,2,3}.0

### PR DESCRIPTION
**Pull request by ledocc**
Specify library name and version:  **boost/1.7{1,2,3}.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ledocc** [comment]
@jgsogo : for the build tools b2, I add a  [PR 582](https://github.com/boostorg/build/pull/582),
for locale and regex, I will propose them when the boostbuild PR was accepted

**Comment by jgsogo** [comment]
Maybe we should wait a little bit for some feedback from the `boost` side, just in case they think that the patch need to be modified.

**Review by prince-chrismc — CHANGES_REQUESTED** [review]
blocked

possibly fixed by #3872

**Comment by SSE4** [comment]
@prince-chrismc as #3872 is already merged, do we still need this one?

**Comment by prince-chrismc** [comment]
@SSE4 I think it's safe to close.

The i18n option works for all platforms even android and apple watches based on the other prs that have been merged

**Pull request closed without merging**
