### PR TITLE
libcurl: add 7.88.1

### PR DESCRIPTION
**Pull request by Cogitri**
Specify library name and version:  **libcurl/7.88.0**

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by StellaSmith — APPROVED** [review]

**Comment by Cogitri** [comment]
I've updated this to 7.88.1 which has been released in the meantime.

**Review by alexb2539 — APPROVED** [review]

**Review by zallenz — APPROVED** [review]

**Comment by prince-chrismc** [comment]
@Cogitri Please let repo owners have permission to push to your branch please so we can fix things if required :)

**Review by prince-chrismc — COMMENTED** [review]
Can you please remove these patches? (the linter is flagging an error)

**Comment by Cogitri** [comment]
> Can you please remove these patches? (the linter is flagging an error)

Sure, I can do that tomorrow - although I have to admit I’m not sure if we should really make security updates wait for unrelated linter nits that could be solved in a separate PR

**Comment by prince-chrismc** [comment]
The patches are for packing it for Conan and its a version which is not even available :)

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Please do not force push 🙏 GitHub forces us to restart the review which is not fun!

**Review by ericLemanissier — APPROVED** [review]

**Pull request merged**
