### PR TITLE
boost: support RelWIthDebInfo

### LINKED ISSUE #1584: [package] <boost>/<1.72.0>: boost build with RelWithDebInfo mode has stripped symbols.
When loading my package into gdb I am seeing this output:
```
Reading symbols from /.conan/data/boost/1.72.0/_/_/package/907e2c094bdf4b6d1c9dc9fed80f48a536ca4d1b/lib/libboost_contract.so.1.72.0...(no debugging symbols found)...done.
```
For boost libraries, other libraries build fine.

I am using `RelWithDebInfo` mode, my boost recipe is about 5 months old.
I will be testing new conan recipe when we are ready to migrate to 1.73.0.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.72.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Conan version: **conan 1.24.0**
  * Python version: **Python 3.6.10**

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **boost/all**

Fixes #1584
Closes #1630

@fulara Can you check?

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by fulara** [comment]
THanks @madebr 
Binaries are definitely heavies, 994K  against 12M.
Unfortunatelly I wonthave any better way in next few days to test whether the symbols would load.

I cant get my gdb to print me that error message on my local setup atm.

**Comment by uilianries** [comment]
> Some configurations of 'boost/1.69.0' failed in build 1 (`431d649ddd6dbbc28da3cf11e90120f6a1f7a4ba`):
> 
>     * **Linux x86_64, Release, gcc 5, libstdc++ . Options:  boost:shared-True**
>       
>       * Hooks errors detected:
>         
>         * `[HOOK - conan-center.py] pre_export(): ERROR: [NO FINAL ENDLINE (KB-H041)] File '/tmp/c3ipr/co_pr_1612_1_0_0/recipes/boost/all/test_package/python.cpp' does not end with an endline (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H041) `
>         * `[HOOK - conan-center.py] pre_export(): ERROR: [NO FINAL ENDLINE (KB-H041)] File '/tmp/c3ipr/co_pr_1612_1_0_0/recipes/boost/all/test_package/lambda.cpp' does not end with an endline (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H041) `
>         * `[HOOK - conan-center.py] pre_export(): ERROR: [NO FINAL ENDLINE (KB-H041)] File '/tmp/c3ipr/co_pr_1612_1_0_0/recipes/boost/all/test_package/data.txt' does not end with an endline (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H041) `


@madebr You created a monster! :joy:

**Comment by SSE4** [comment]
@danimtb we have a problem - 403

**Comment by madebr** [comment]
@uilianries @danimtb Please merge.

**Comment by SSE4** [comment]
@madebr there are conflicts, we can't merge

**Comment by madebr** [comment]
@danimtb  @SSE4 @uilianries 
Conflict was because `data.txt` was modified to fix HB041 where this pr removed that file because it was unused.

**Comment by danimtb** [comment]
Let's get this one merged!

**Pull request merged**
