### PR TITLE
glm: add version 1.0.0

### PR DESCRIPTION
**Pull request by StellaSmith**
https://github.com/g-truc/glm/issues/1226

The released archive has a bit of a different structure than previous releases, so i had to add some conditionals for v1.0.0.
I'm wondering if I should also delete the cci.yyyymmdd versions and/or create a different subfolder for this release.

### CODE REVIEW

**Comment by StellaSmith** [comment]
I decided in the end to remove the older versions to simplify the conanfile, as i also believe that the cci versions are not necessary anymore that there's an official release.

**Comment by uilianries** [comment]
@StellaSmith Please, don't forget to update the `config.yml` as well.

**Comment by StellaSmith** [comment]
> @StellaSmith Please, don't forget to update the `config.yml` as well.

😅 i did this at like 2 am so i forgot

**Review by jwillikers — APPROVED** [review]

**Review by valgur — APPROVED** [review]

**Comment by valgur** [comment]
@StellaSmith Could you replace the v1.0.0 in this PR with v1.0.1, please.

@RubenRBS a review would be welcome. It's a pretty small PR.

**Comment by TheHugeManatee** [comment]
Hi @valgur,
Since there's no activity from the original PR author, is it reasonable that I create a new PR with the requested changes (v1.0.1)? If so, could I fork @StellaSmith 's  cci fork and create a PR to here, or would that somehow violate the CLA? Or is there simpler way that I can take over the required updates?

**Comment by valgur** [comment]
@TheHugeManatee Yes, that should be perfectly fine since they have signed the CLA. Feel free to open a new PR based off these commits.

**Comment by TheHugeManatee** [comment]
Thanks for the quick feedback! I created a new PR here: https://github.com/conan-io/conan-center-index/pull/23742 . I guess this one can be closed then.

**Comment by perseoGI** [comment]
I'm closing this PR in favor of this one already merged https://github.com/conan-io/conan-center-index/pull/23742
which adds a newer version (v1.0.1)

Thanks!

**Pull request closed without merging**
