### PR TITLE
Fix 7zip when compiling in C++17/20

### LINKED ISSUE #20600: [package] 7zip/22.01: Fails to build with C++17
### Description

I added 7zip/22.01 as a build_requires for one of my recipes. My profile uses C++17. The build fails.

I think options are:

1. Patch to build with C++17
2. Validate the std is c++14 or lower (or whatever the actual min requirement is)...hopefully reporting how to fix (override std of package in profile)

### Package and Environment Details

* Package Name/Version: 7zip/22.01
* Operating System+version: Windows
* Compiler+version: Visual Studio 2022
* Conan version: conan 2.0.13
* Python version: Python 3.11.5

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

### Steps to reproduce

conanfile.txt
```
[requires]
7zip/22.01
```

`conan install . -pr:b my_profile -pr:h my_profile --build=*`

### Logs

[build.txt](https://github.com/conan-io/conan-center-index/files/12917419/build.txt)

### PR DESCRIPTION
**Pull request by Ahajha**
Specify library name and version:  **7zip/22.01**

Closes #20600 

3 changes:
1. Add 23.01
2. Disable warnings as errors for versions <23.01 (unsure if this is generally a good idea or accepted practice in conan center).
3. Fix a single actual error in versions <23.01.
---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi @Ahajha thanks a lot for the patch, we appreciate it :)

It's a bit suprising to me that a library like 7zip has this issue - Has it been reported upstream/is it already in there and could this then be considered a backport?

**Comment by Ahajha** [comment]
Hi @RubenRBS, I just checked and it seems this hasn't been reported (https://sourceforge.net/p/sevenzip/discussion/search/?q=C%2B%2B17). I'm unfamiliar with how 7zip does its releases so I have no idea how long it would take them to accept a patch, or backport one to 22.01. I can check to see if the latest version has this problem.

**Comment by Ahajha** [comment]
@RubenRBS The latest (23.01) does not need any patching, nor disabling warnings as errors. For now I have the changes conditioned on the version, or perhaps we could just error on C++17 mode for 22.01. @rconde01 do you have a preference one way or the other? Do you need 7zip 22.01 specifically or will the latest work for you?

**Comment by rconde01** [comment]
> @RubenRBS The latest (23.01) does not need any patching, nor disabling warnings as errors. For now I have the changes conditioned on the version, or perhaps we could just error on C++17 mode for 22.01. @rconde01 do you have a preference one way or the other? Do you need 7zip 22.01 specifically or will the latest work for you?

I don't need 22.01 specifically. I know how to workaround the issue even with 22.01 so this is really to improve the experience for the community. In that regard I think "just working" is the best, but I can't say it's worth the investment per se so I think erroring, with a clear message on how to fix the issue (e.g. change your whole standard, or change the std for this package in your profile), would be a good second option. Not sure about the policy of such things. It might be a good idea to have a page in the docs re: semi-common issues like this and then you can keep the recipe light and just link to the page.

**Comment by Ahajha** [comment]
@RubenRBS I think then this is ready for review. Essentially, this is (1) an addition of 23.01 and (2) a backport/workaround of some small fixes that were included in that version.

**Review by RubenRBS — APPROVED** [review]
Thanks a lot @Ahajha for your contribution and @rconde01 for the extra insight, we really appreciate it :)

> with a clear message on how to fix the issue (e.g. change your whole standard, or change the std for this package in your profile), would be a good second option. Not sure about the policy of such things

This is totally aceptable behaviour in recipes when no upstream patch is avaialble, I'll make sure to note it down somewhere in the docs for the future, thanks a lot for the comment!

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
