### PR TITLE
md4qt: bump version

### PR DESCRIPTION
**Pull request by igormironchik**
Specify library name and version:  **md4qt/2.0.17**

I'm the author of this library.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by igormironchik** [comment]
@prince-chrismc Should I do something, or this build fail is a problem on your CI side?

**Comment by igormironchik** [comment]
@prince-chrismc Should I care about something?

**Comment by igormironchik** [comment]
@prince-chrismc Hello. I'm ready to publish a next release already, but I'm in stuck with this PR. Guys, could you solve this issue? Thank you.

**Comment by prince-chrismc** [comment]
@RubenRBS or @jcar87 will be able to help you :) (I am not longer on the team)

**Comment by igormironchik** [comment]
Guys, ping!

**Pull request closed without merging**
