### PR TITLE
glslang: add 1.3.239.0 + modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
draft until https://github.com/conan-io/conan-center-index/pull/16261 is merged

**Comment by IceflowRE** [comment]
Will be the executable `glslangValidator` available again?

**Comment by SpaceIm** [comment]
It has always been available by default in this recipe.

**Comment by IceflowRE** [comment]
> It has always been available by default in this recipe.

How can i access it?

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
