### PR TITLE
cmake: ignore MSB warnings

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **cmake/all**

I will push the patch upstream but want to test it first on CI.

update:
- [x] https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5348

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
This will fail

The offending CMake is NOT the one we are building but rather the one we are using to build it (we build CMake with CMake)

Hence, you would need to patch the install CMake on the Windows CI machines

**Comment by madebr** [comment]
The sources contain:
```cmake
# Make sure we can find internal find_package modules only used for
# building CMake and not for shipping externally
list(INSERT CMAKE_MODULE_PATH 0 ${CMake_SOURCE_DIR}/Source/Modules)
```
So there is hope :crossed_fingers:

**Comment by madebr** [comment]
@Croydon 
The patch is working!
The MSVC logs still contain the MSB warning so c3i's props file was not patched yet.

**Comment by Croydon** [comment]
Wohoo. Nevermind, don't listen to me. You are doing amazing work 🎉 🥳 🎉 

So, we are going to merge this and push it upstream? 🤔

**Review by Croydon — APPROVED** [review]

**Comment by a4z** [comment]
just out of interest, what is the actually problem solved here ? 
is this patching cmake to satisfy conan hooks?

**Comment by Croydon** [comment]
No, there was a change in the Windows CI which causes MSVC to produce a warning which is treated by CMake effectively as an error

See here https://github.com/conan-io/conan-center-index/pull/3053#issuecomment-702295510

**Review by a4z — APPROVED** [review]
looks good, not sure if an approval from me helps to merge that faster, but for the case it helps, here it is :-)

**Review by jgsogo — CHANGES_REQUESTED** [review]
We will fix it in the infra, no need to make the recipe more complex just because we are not doing things right in the backend.

@danimtb , what about releasing a new version of C3i? I think it is ready.

**Comment by Croydon** [comment]
@jgsogo Upstream already agreed to welcome a PR fixing this, so I don't see a reason why we shouldn't patch existing versions on CCI.

The patch is rather small and can be dropped as soon as it is upstreamed

https://gitlab.kitware.com/cmake/cmake/-/issues/21270

**Comment by danimtb** [comment]
@jgsogo done https://github.com/conan-io/conan-center-index/pull/3138

**Comment by jgsogo** [comment]
I prefer not to add complexity (maintenance, `ifs`,...) to the recipe if it is not needed. This is a PR we'd never have done if the CI hadn't failed. After https://github.com/conan-io/conan-center-index/pull/3138 this is no longer a problem.

**Comment by madebr** [comment]
This patch just got merged at https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5348

**Comment by Croydon** [comment]
Thank you for pushing this forward @madebr 

> I prefer not to add complexity (maintenance, ifs,...) to the recipe if it is not needed. This is a PR we'd never have done if the CI hadn't failed. After #3138 this is no longer a problem.

It is an upstream problem and may also affect other environments similar to C3I, but since it is now upstreamed, it at least won't be a problem for future CMake versions. So I guess it is fine with me if we don't patch the older versions.


That said, we got a new "unexpected error" here: 🙈 
https://github.com/conan-io/conan-center-index/pull/2941#issuecomment-705517540

**Comment by madebr** [comment]
I'll close it. I see the other pr will apply the openssl version bump.

**Pull request closed without merging**
