### PR TITLE
CI: Add Croydon for docs/ alerts

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Review by SSE4 — APPROVED** [review]
maybe we need to change format to multi-line, to avoid conflicts for people editing the same line in different PRs?

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
SSE4, the bot does not count your approval FYI (it does not match github)

**Comment by Croydon** [comment]
> SSE4, the bot does not count your approval FYI (it does not match github)

How so? His name here: https://github.com/conan-io/conan-center-index/blob/1953dfb32bdfae660c8078ab427b6eacbc6cdf8b/.c3i/reviewers.yml#L21 seems to be exactly the one on GitHub

**Comment by prince-chrismc** [comment]
Ohhh I meant the "reviewers" section on this PR it shows a check but it's on an old commit which is not how the bot likes it

**Comment by SSE4** [comment]
what should I do?

**Comment by prince-chrismc** [comment]
You just need to approve again :)

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
