### PR TITLE
onetbb 2021.x: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by saschasc** [comment]
@SpaceIm It would be nice to update/combine this for the onetbb/2021.5.0 version as well.

**Comment by SpaceIm** [comment]
In another PR.

**Review by uilianries — APPROVED** [review]

**Review by saschasc — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by saschasc** [comment]
> In another PR.

Any progress on this? It would be great to have onetbb/2021.5.0 supported as well. Thanks!

**Comment by uilianries** [comment]
@saschasc You could open a PR as well 😉

**Pull request merged**
