### PR TITLE
xorg: remove some packages

### PR DESCRIPTION
**Pull request by ericLemanissier**
these packages are not available on alpine or centos
also, fix zypper package name

Specify library name and version:  **xorg/system**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
Do some (known) libraries require those?

If so we should add rather a switch based on distro name instead of removing it for all

**Comment by ericLemanissier** [comment]
a dumb search on github did not show any usage:
https://github.com/search?q=libfs+filename%3Aconanfile.py&type=Code
https://github.com/search?q=libdmx+filename%3Aconanfile.py&type=Code
https://github.com/search?q=dmx+filename%3Aconanfile.py&type=Code&ref=advsearch&l=&l=

on debian, libfs seems to be required only by [x11-xfs-utils](https://debian.pkgs.org/11/debian-main-amd64/x11-xfs-utils_7.7+2+b1_amd64.deb.html) and libdmx seems to be required only by [xdmx-tools](https://debian.pkgs.org/11/debian-main-amd64/xdmx-tools_1.20.8-2_amd64.deb.html)

**Comment by ericLemanissier** [comment]
@SSE4 how did you choose to include dmx in the virtual package, and [to use it in the test ](https://github.com/conan-io/conan-center-index/commit/68b5407c959a5fd517ff3ef2f0b746093bf06564#diff-1f06919aff17f7723cb05e6e15f45979) ?

**Comment by SSE4** [comment]
@ericLemanissier I think `libdmx` was one of the first in the list alphabetically sorted, as others start with `libX` and tend to be in the end. also, very few libraries provide functions which could be called without creating an actual display or client/server instance. most of libraries require to have X11 connection to be already established, as they are extensions for the protocol.

**Comment by SSE4** [comment]
for the record, CentOS provides this package as
```
libdmx-devel-1.1.3-3.el7.aarch64.rpm | X.Org X11 DMX development files
```

**Comment by SSE4** [comment]
also, LFS for the reference on how to install X11 development libraries: http://www.linuxfromscratch.org/blfs/view/svn/x/x7lib.html

**Comment by ericLemanissier** [comment]
Centos 6 and 7 have libdmx-devel, but centos 8 does not have developement packages: https://pkgs.org/search/?q=dmx.pc

**Comment by SSE4** [comment]
@ericLemanissier hm, this is unfortunate. I am not sure if something has changed in X11 so libdmx is no longer needed?

**Comment by daravi** [comment]
> Centos 6 and 7 have libdmx-devel, but centos 8 does not have developement packages: https://pkgs.org/search/?q=dmx.pc

Yes seems like it was removed:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#removed-packages_changes-to-packages

**Comment by SSE4** [comment]
okay did some research, there are some projects using libFS APIs, but we're not packaging them yet. also, as CentOS doesn't ship them any longer, I think it's in general impossible to build them anyway.
my suggestion - review libFS from the list of packages to install and from test_package for now.
if/once someone complains - we will take a look and reconsider how to deal with that.
but right now I don't think it should be blocker for us (at least until we have real conan packages requiring libFS).

**Comment by ericLemanissier** [comment]
So where are we on this one ?
Currently:
1. opensuse installation fails because of wrong zypper package name: https://github.com/bincrafters/conan-qt/runs/868938393#step:11:8481
2. centos installation fails because of the absence of dmx: https://github.com/bincrafters/conan-qt/runs/868938482#step:11:844
3. archilinux installation fails because of the absence of dmx: https://github.com/bincrafters/conan-qt/runs/868938498#step:11:8469
4. fedora installation fails because of the absence of dmx: https://github.com/bincrafters/conan-qt/runs/868938512#step:11:8664

**Comment by ericLemanissier** [comment]
This PR allows to consume `xorg/system` on (at least) opensuse, debian, centos, archilinux and fedora : https://github.com/bincrafters/conan-center-index/actions/runs/169831610
I also did some tests on alpine, but it seems conan is not yet able to install system packages on this one, so I installed the system packages manually before invoking conan. It passed too.

**Comment by SSE4** [comment]
@ericLemanissier to clarify, for alpine, is there a conan bug in `SystemPackageTool` that prevents correct installation? have you opened an issue if so?

**Comment by ericLemanissier** [comment]
@SSE4 I did not report the lack of support of alpine distribution. It's more of a missing feature than a bug, because apk is not listed in https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool

**Pull request merged**
