### PR TITLE
abseil: cross-compatibility conan v1/v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
ERROR: abseil/20200923.3 (test package): Error in build() method, line 12
	cmake.definitions["CXX20_SUPPORTED"] = tools.Version(self.deps_cpp_info["abseil"].version) > "20210324.2"
	ConanException: Invalid version 'None'
```

Why is not valid in test_v1_package? I've kept the same conanfile 😲

**Comment by jgsogo** [comment]
We have just upgraded to Conan 1.50.1 this afternoon. Maybe a regression?

**Comment by SpaceIm** [comment]
I guess, I can reproduce this issue locally with `conan create . abseil/20211102.0@ -tf test_v1_package`. Maybe a breaking change where self.deps_cpp_info values are unkown in build() but not in generate()?

**Comment by SpaceIm** [comment]
> I guess, I can reproduce this issue locally with `conan create . abseil/20211102.0@ -tf test_v1_package`. Maybe a breaking change where self.deps_cpp_info values are unkown in build() but not in generate()?

Fixed in conan 1.51.1 with https://github.com/conan-io/conan/pull/11790. So waiting an update of conan version in CCI.

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Pull request merged**
