### PR TITLE
grpc: fix cross-build + provide all CMake executable imported targets + add shared option + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
This is a big PR fixing several issues:
- add CMakeDeps support
- provide all `gRPC::<plugin>` executable targets, not only `gRPC::grpc_cpp_plugin`. I've turned the custom module file to a template file reused at package time to generate one file per executable.
- fix cross-build:
  - we can trust our `protobuf::protoc` target coming from conan generators. When this recipe will use `CMakeToolchain`, the patch could be removed thanks to https://github.com/conan-io/conan/pull/10186, because find_program() will always find executables from build context first.
  - CMAKE_MACOSX_BUNDLE forced to OFF to avoid CMake configuration error if target is iOS.
- test package was more or less broken (issue was hidden by not calling `conan_basic_setup(TARGETS)`, it would have never passed CI with `CMakeToolchain`) and using custom logic, not standard module file from protobuf => now the CMakeLists of test package shows a proper usage of protobuf + grpc.
- add shared option

closes https://github.com/conan-io/conan-center-index/issues/6382
closes #8560

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
My gosh, I've realized something while trying to support shared in grpc recipe: `conan_basic_setup()` calls `conan_set_rpath()`, which force `CMAKE_SKIP_RPATH`. It's completly wrong in most properly written CMakeLists.
Indeed `CMAKE_SKIP_RPATH` is for the build tree only, and for a library like grpc you want rpath inside the build tree ! When you call the install target, CMake doesn't only copy files, it removes rpath by default in installed libraries, so `CMAKE_SKIP_RPATH` should not be the default in conan recipes (only in recipes where we manually copy binaries in `package()`).
What we want in conan-center recipes is `CMAKE_SKIP_INSTALL_RPATH ON` and `CMAKE_SKIP_RPATH OFF`.

Hoping it's not the default in conan v2.

/cc @memsharded @lasote

**Comment by SpaceIm** [comment]
Basically here is neat behavior for conan-center:

`otool -l grpc_cpp_plugin` (an executable built & called during grpc project build) in build & install tree:

<details><summary>grpc_cpp_plugin in the build tree</summary>

```
grpc_cpp_plugin:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x000000000001c000
  fileoff 0
 filesize 114688
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000100002c10
      size 0x00000000000168aa
    offset 11280
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x00000001000194ba
      size 0x00000000000003ae
    offset 103610
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000100019868
      size 0x0000000000000538
    offset 104552
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x0000000100019da0
      size 0x0000000000000cd4
    offset 105888
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x000000010001aa80
      size 0x00000000000007d7
    offset 109184
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x000000010001b257
      size 0x0000000000000409
    offset 111191
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x000000010001b660
      size 0x0000000000000998
    offset 112224
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 312
  segname __DATA_CONST
   vmaddr 0x000000010001c000
   vmsize 0x0000000000004000
  fileoff 114688
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 3
    flags 0x10
Section
  sectname __got
   segname __DATA_CONST
      addr 0x000000010001c000
      size 0x0000000000000110
    offset 114688
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 157 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA_CONST
      addr 0x000000010001c110
      size 0x0000000000000010
    offset 114960
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x000000010001c120
      size 0x0000000000000930
    offset 114976
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 312
  segname __DATA
   vmaddr 0x0000000100020000
   vmsize 0x0000000000004000
  fileoff 131072
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 3
    flags 0x0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x0000000100020000
      size 0x00000000000004e8
    offset 131072
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 191 (index into indirect symbol table)
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x00000001000204e8
      size 0x0000000000000168
    offset 132328
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x0000000100020650
      size 0x0000000000000059
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 4
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000100024000
   vmsize 0x0000000000028000
  fileoff 147456
 filesize 151760
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 5
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 147456
    rebase_size 152
       bind_off 147608
      bind_size 2920
  weak_bind_off 150528
 weak_bind_size 32904
  lazy_bind_off 183432
 lazy_bind_size 9432
     export_off 192864
    export_size 17312
Load command 6
     cmd LC_SYMTAB
 cmdsize 24
  symoff 211144
   nsyms 1129
  stroff 230600
 strsize 68616
Load command 7
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 280
     iextdefsym 280
     nextdefsym 670
      iundefsym 950
      nundefsym 179
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 229208
  nindirectsyms 348
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 8
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 9
     cmd LC_UUID
 cmdsize 24
    uuid 0E082481-3384-3517-8C41-891CDB931542
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 12.0
      sdk 12.1
   ntools 1
     tool 3
  version 711.0
Load command 11
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 12
       cmd LC_MAIN
   cmdsize 24
  entryoff 11280
 stacksize 0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1311.0.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name @rpath/libgrpc_plugin_support.1.43.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.43.0
compatibility version 1.43.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1200.3.0
compatibility version 1.0.0
Load command 16
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/openssl/1.1.1m/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/lib (offset 12)
Load command 17
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/protobuf/3.17.1/_/_/package/80f87b689c44329240fa96fdf4da01af5da79798/lib (offset 12)
Load command 18
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/c-ares/1.17.2/_/_/package/c30efb974509ebc40ac2eb16ba24cb589392f384/lib (offset 12)
Load command 19
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/abseil/20211102.0/_/_/package/1aff124b71f6d938138ecd7179ff075f4304a85d/lib (offset 12)
Load command 20
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/re2/20211101/_/_/package/1aff124b71f6d938138ecd7179ff075f4304a85d/lib (offset 12)
Load command 21
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/zlib/1.2.11/_/_/package/e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc/lib (offset 12)
Load command 22
          cmd LC_RPATH
      cmdsize 128
         path /Users/spaceim/.conan/data/grpc/1.43.0/_/_/build/70ebd75293805a009e60408c6088380b38dd5795/build_subfolder/lib (offset 12)
Load command 23
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 210176
 datasize 944
Load command 24
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 211120
 datasize 24
```

</details>

<details><summary>grpc_cpp_plugin in the install tree</summary>

```
grpc_cpp_plugin:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x000000000001c000
  fileoff 0
 filesize 114688
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000100002c10
      size 0x00000000000168aa
    offset 11280
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x00000001000194ba
      size 0x00000000000003ae
    offset 103610
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000100019868
      size 0x0000000000000538
    offset 104552
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x0000000100019da0
      size 0x0000000000000cd4
    offset 105888
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x000000010001aa80
      size 0x00000000000007d7
    offset 109184
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x000000010001b257
      size 0x0000000000000409
    offset 111191
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x000000010001b660
      size 0x0000000000000998
    offset 112224
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 312
  segname __DATA_CONST
   vmaddr 0x000000010001c000
   vmsize 0x0000000000004000
  fileoff 114688
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 3
    flags 0x10
Section
  sectname __got
   segname __DATA_CONST
      addr 0x000000010001c000
      size 0x0000000000000110
    offset 114688
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 157 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA_CONST
      addr 0x000000010001c110
      size 0x0000000000000010
    offset 114960
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x000000010001c120
      size 0x0000000000000930
    offset 114976
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 312
  segname __DATA
   vmaddr 0x0000000100020000
   vmsize 0x0000000000004000
  fileoff 131072
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 3
    flags 0x0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x0000000100020000
      size 0x00000000000004e8
    offset 131072
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 191 (index into indirect symbol table)
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x00000001000204e8
      size 0x0000000000000168
    offset 132328
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x0000000100020650
      size 0x0000000000000059
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 4
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000100024000
   vmsize 0x0000000000028000
  fileoff 147456
 filesize 151760
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 5
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 147456
    rebase_size 152
       bind_off 147608
      bind_size 2920
  weak_bind_off 150528
 weak_bind_size 32904
  lazy_bind_off 183432
 lazy_bind_size 9432
     export_off 192864
    export_size 17312
Load command 6
     cmd LC_SYMTAB
 cmdsize 24
  symoff 211144
   nsyms 1129
  stroff 230600
 strsize 68616
Load command 7
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 280
     iextdefsym 280
     nextdefsym 670
      iundefsym 950
      nundefsym 179
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 229208
  nindirectsyms 348
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 8
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 9
     cmd LC_UUID
 cmdsize 24
    uuid 0E082481-3384-3517-8C41-891CDB931542
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 12.0
      sdk 12.1
   ntools 1
     tool 3
  version 711.0
Load command 11
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 12
       cmd LC_MAIN
   cmdsize 24
  entryoff 11280
 stacksize 0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1311.0.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name @rpath/libgrpc_plugin_support.1.43.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.43.0
compatibility version 1.43.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1200.3.0
compatibility version 1.0.0
Load command 16
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 210176
 datasize 944
Load command 17
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 211120
 datasize 24
```

</details>

You see that in the build tree, `grpc_cpp_plugin` can resolve all its shared depenencies even of there was shared libs outside the build tree. But `grpc_cpp_plugin` in install tree, rpath is empty, no more specific paths from build machine.

**Comment by SpaceIm** [comment]
> /usr/bin/ld: /home/conan/w/BuildSingleReference/.conan/data/abseil/20211102.0/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib/libabsl_strings.a(charconv.cc.o): undefined reference to symbol 'nan@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line

seriously?

**Comment by lasote** [comment]
@SpaceIm In develop2 there is no `CMAKE_SKIP_RPATH` by default. You can set it to True adjusting the context of the `rpath` block. https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#extending-and-customizing-cmaketoolchain

**Comment by SpaceIm** [comment]
Let's see if it's better after https://github.com/conan-io/conan-center-index/pull/6383

@lasote, ok thanks, I think it will be fine with CMakeToolchain (except if upstream CMakeLists uses old policy). I think anyway that we should add a hook in conan-center to check the expected content of installed shared libs on macOS and Linux.

**Comment by SpaceIm** [comment]
```
********************************************************************************
conan install grpc/1.41.0@ --build=grpc --profile:host=/Users/jenkins/w/BuildSingleReference@2/77617/6258b6ce-dc71-4428-8e73-c6508a327260/profile_host.txt --profile:build=default
********************************************************************************
Auto detecting your dev setup to initialize the default profile (/Users/jenkins/w/BuildSingleReference@2/.conan/profiles/default)
Found apple-clang 12.0
Default settings
	os=Macos
	os_build=Macos
	arch=x86_64
	arch_build=x86_64
	compiler=apple-clang
	compiler.version=12.0
	compiler.libcxx=libc++
	build_type=Release
*** You can change them in /Users/jenkins/w/BuildSingleReference@2/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


ERROR: Profile not found: /Users/jenkins/w/BuildSingleReference@2/77617/6258b6ce-dc71-4428-8e73-c6508a327260/profile_host.txt
```

🙄

**Comment by SpaceIm** [comment]
regarding KEEP_RPATHS: see https://github.com/conan-io/hooks/issues/376. It's very important for grpc at build time also.

**Comment by SpaceIm** [comment]
:v:

**Review by prince-chrismc — DISMISSED** [review]

**Review by uilianries — APPROVED** [review]
Really nice!

**Comment by SpaceIm** [comment]
?

**Comment by SpaceIm** [comment]
Not really sure to understand why CI tried to build again.

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
