### PR TITLE
directx-headers: Add version 1.614.0

### PR DESCRIPTION
**Pull request by jwillikers**
### Summary
Changes to recipe:  **directx-headers/1.614.0**

#### Motivation

Add the latest version 1.614.0 of directx-headers. The current version of `directx-headers` is too old for the latest release of Mesa.

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — COMMENTED** [review]
Hi @jwillikers thanks a lot for taking the time to add the new version :) I have a minor question befor merging

The only thing that it's not 100% clear to me is this change [microsoft/DirectX-Headers@`v1.610.2...v1.614.0`#diff-30d8f6be63](https://github.com/microsoft/DirectX-Headers/compare/v1.610.2...v1.614.0#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4R15) in the meson.build file
```
if host_machine.system() == 'windows'
    test_compile_opts = ['-DUNICODE', '-D_WIN32_WINNT=0x0A00']
endif
```

If those are opts that their tests ineed under Windows, are those flags something that the recipe should also be propagating downstream?

**Comment by jwillikers** [comment]
> Hi @jwillikers thanks a lot for taking the time to add the new version :) I have a minor question befor merging
> 
> The only thing that it's not 100% clear to me is this change [microsoft/DirectX-Headers@`v1.610.2...v1.614.0`#diff-30d8f6be63](https://github.com/microsoft/DirectX-Headers/compare/v1.610.2...v1.614.0#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4R15) in the meson.build file
> 
> ```
> if host_machine.system() == 'windows'
>     test_compile_opts = ['-DUNICODE', '-D_WIN32_WINNT=0x0A00']
> endif
> ```
> 
> If those are opts that their tests ineed under Windows, are those flags something that the recipe should also be propagating downstream?

Those defines appear to have just been moved from the `test/meson.build` file to the top `meson.build` file in [this commit], so they were already in use. I'd be very wary of setting those defines through a recipe since they are specific to the `windows.h` configuration. Also, checking the (vcpkg)[https://github.com/microsoft/vcpkg/tree/master/ports/directx-headers) port, these definitions aren't added.

**Review by AbrilRBS — APPROVED** [review]
Thanks for the extra insight, seems like they are only used for the testing then :)

**Review by perseoGI — APPROVED** [review]
LGTM thanks

**Review by ErniGH — APPROVED** [review]

**Pull request merged**
