### PR TITLE
add frugally-deep/v0.15.1-p0, closes #3956

### LINKED ISSUE #3956: [request] frugally-deep/v0.15.1-p0
### Package Details
  * Package Name/Version: **frugally-deep/v0.15.1-p0**
  * Website: none
  * Source code: **https://github.com/Dobiasd/frugally-deep/**

### Description Of The Library / Tool
Use Keras models in C++ with ease

---

Pull request: https://github.com/conan-io/conan-center-index/pull/3993

### PR DESCRIPTION
**Pull request by Dobiasd**
Specify library name and version:  **frugally-deep/v0.15.1-p0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

---

Used [this](https://github.com/conan-io/conan-center-index/tree/master/recipes/functionalplus) to copy-paste from. I hope I did everything right. :slightly_smiling_face:

### CODE REVIEW

**Comment by Dobiasd** [comment]
I see the following:

U5b0ZTo

But when I click "details", I only get to:

pcb73yQ

So it would be cool if somebody could help me out, because I don't know what I have to do.

**Comment by uilianries** [comment]
@Dobiasd Please, consider https://github.com/Dobiasd/conan-center-index/pull/1

**Comment by Dobiasd** [comment]
@uilianries Nice! Thanks a lot! :slightly_smiling_face:

**Comment by Dobiasd** [comment]
The build is still failing. I'm not yet allowed to see why, but I've [requested EAP access](https://github.com/conan-io/conan-center-index/issues/4#issuecomment-768274240).

**Comment by uilianries** [comment]
@Dobiasd please, add your name on issue #4. The CI bot only runs PR from people which are included in EAP. There is more information [here](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md).

We usually approve EAP in waves, once a week.

Regards and thanks for your contribution.

**Review by intelligide — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
