### PR TITLE
dbus: Add dbus_user option to allow specifying a different run user

### PR DESCRIPTION
**Pull request by jwillikers**
Specify library name and version:  **dbus/***

Building dbus requires that the user specified for `dbus_user` exists.
To allow projects to build dbus in various situations, it makes sense to allow this option to be modified.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jwillikers** [comment]
Requires #22156

**Comment by jwillikers** [comment]
@RubenRBS @uilianries Can I get a review for this? Without it, local dbus builds are failing due to the `messagebus` group not being in the image.

```
Traceback (most recent call last):
  File "/root/.conan/data/dbus/1.15.8/_/_/build/f90ea84e722ce1012f8fe615de9d901f8ff1b350/src/meson_post_install.py", line 106, in <module>
    post_install_exe()
  File "/root/.conan/data/dbus/1.15.8/_/_/build/f90ea84e722ce1012f8fe615de9d901f8ff1b350/src/meson_post_install.py", line 95, in post_install_exe
    os.chown(exe_path, 0, grp.getgrnam(dbus_user).gr_gid)
KeyError: "getgrnam(): name not found: 'messagebus'"
```

It is also probably be worth opening an issue upstream to verify the group exists.

**Comment by RubenRBS** [comment]
My main concern here is if this option changing the package id is desirable or not. Do you have any extra insight?

**Comment by jwillikers** [comment]
> My main concern here is if this option changing the package id is desirable or not. Do you have any extra insight?

I'll check and see if the default user is compiled into the binary, in which case, it should effect the id.

**Comment by jwillikers** [comment]
Looks like it's only present in the system.conf file. The library itself doesn't contain any references: `strings /home/jordan/.conan2/p/b/dbusbed52a0433957/p/lib/libdbus-1.a | grep -i messagebus` was empty. No headers include it either. I'll remove the option in the package_id method.

**Comment by jwillikers** [comment]
Someone beat me to opening an issue upstream: https://gitlab.freedesktop.org/dbus/dbus/-/issues/492

**Comment by RubenRBS** [comment]
In the linked issue, you mention:

 > I'm continuing to try and communicate to the team to only depend on stable versions of DBus in other recipes

Happy to hear more about this and your insight on it either here or in Slack :)

**Comment by jwillikers** [comment]
> In the linked issue, you mention:
> 
> > I'm continuing to try and communicate to the team to only depend on stable versions of DBus in other recipes
> 
> Happy to hear more about this and your insight on it either here or in Slack :)

@RubenRBS  I've opened issue #23003 and previously had made a comment [here](https://github.com/conan-io/conan-center-index/pull/19003#issuecomment-1895904120), but I probably should have mentioned some team members there.

**Review by valgur — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
sorry for the delay, i've finally got the time to follow up on this, and now that I've understood it, this looks like the best way to go, thanks a lot for following up on it :)

As for dbus beind dependend upon with snapshot versions, I'm super open to approve bump PR for those to the latest "LTS" ones if you want, else just let me know which ones and I can do that myself!

**Comment by franramirez688** [comment]
@jwillikers the PR has some conflicts.

**Comment by jwillikers** [comment]
@franramirez688 Done.

**Review by RubenRBS — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Review by franramirez688 — APPROVED** [review]

**Pull request merged**
