### PR TITLE
Add libeb/4.4.3 recipe

### PR DESCRIPTION
**Pull request by tuduongquyet**
Name: libeb
About: Library for managing EB/EB-G/EB-XA ebooks
Repo: https://github.com/mistydemeo/eb
Version 4.4.3

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@tuduongquyet it seems be libeb is not prepared for Mac M1.

**Comment by tuduongquyet** [comment]
> configure: error: /bin/sh source_subfolder/config.sub aarch64-apple-darwin failed

Yes, let me check ^^

**Comment by tuduongquyet** [comment]
> @tuduongquyet it seems be libeb is not prepared for Mac M1.

This issue occurs because `config.sub` and `config.guess` were generated along ago. Regenerate these files fixes the issue. What should be better approach between following ones:
- Regenerate these files and add patch or
- Rerun automake

**Comment by uilianries** [comment]
> Rerun automake

It seems be a good idea.

**Pull request closed without merging**
