### PR TITLE
pistache: add version 0.0.5, support connan v2

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **pistache/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by jiankyu — APPROVED** [review]
LGTM

**Comment by tmustafa** [comment]
LGTM!

**Review by tmustafa — APPROVED** [review]
LGTM!

**Comment by jiankyu** [comment]
Hi, We're waiting for this version, so I and one of my colleague approved it to make 3 approvals. But the merging is still blocked. Wondering if it requires 3 approvals from the core developers?
Can we accelerate that? Appreciate.

**Comment by jwillikers** [comment]
@jiankyu It needs a review from one core developer still. I'd expect that to happen soon, given that the build has been passing for a couple of days.

**Comment by prince-chrismc** [comment]
Please refer to the docs for the review process https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md#rule-of-2-reviews The GitHub UI sadly does not reflect the bots implementation :/

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
