### PR TITLE
qt5: reorder dbus component generation

### PR DESCRIPTION
**Pull request by ericLemanissier**
fixes conan-io/conan-center-index#16084
fixes conan-io/conan-center-index#16113

Specify library name and version:  **qt/5.***

this is already corrected on qt6 : https://github.com/conan-io/conan-center-index/commit/da20142b41fa27281f4f7ae5fb740e8e43ab0591#diff-c548829da9d38ae15a8cb4447140bc50ac3f38250d1f348decd9569dc3298b24R1044

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — DISMISSED** [review]

**Comment by ericLemanissier** [comment]
blocked by:
- https://github.com/conan-io/conan-center-index/pull/16100

**Review by MartinDelille — DISMISSED** [review]

**Review by tsondergaard — DISMISSED** [review]

**Review by MartinDelille — APPROVED** [review]

**Review by tsondergaard — DISMISSED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
I love our new alerts remind you that you just opened a PR lol

**Review by MartinDelille — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by tsondergaard — APPROVED** [review]

**Comment by ericLemanissier** [comment]
`No space left on device` 😠

**Comment by ericLemanissier** [comment]
integrated in conan-io/conan-center-index#16404

**Pull request closed without merging**
