### PR TITLE
add opensslextra configure option

### LINKED ISSUE #2154: [request] wolfssl/4.4.0 : support more configuration options like openssl-extra
### Package Details
  * Package Name/Version: **wolfssl/4.4.0**
  * Existing Configuration: **https://github.com/conan-io/conan-center-index/blob/master/recipes/wolfssl/all/conanfile.py**

The existing recipe for wolfssl supports only "shared" and "fPIC" options. Need support for option to enable openssl extra compatibility layer. The default value can be set to false.

Something like the following:-

options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "openssl-extra": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
        "openssl-extra": False,
    }

### PR DESCRIPTION
**Pull request by kirandivekar**
Add support for opensslextra configuration option for openssl compatibility layer
default value is false.
This is based on the work from theirix PR 2027

closes #2154 

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by kirandivekar** [comment]
I checked the failing CI logs. It shows 

```
ERROR: Missing binary: automake/1.16.2:8f0570538ddd703bfc5400385a2fca9aa4a2b671
ERROR: Missing binary: libtool/2.4.6:1c19d2cb2281d70e5828ac1b9d3a4ed44671d717
automake/1.16.2: WARN: Can't find a 'automake/1.16.2' package for the specified settings, options and dependencies:
- Settings: os=Linux
- Options: 
- Dependencies: autoconf/2.69
- Requirements: autoconf/2.Y.Z
- Package ID: 8f0570538ddd703bfc5400385a2fca9aa4a2b671

ERROR: Missing prebuilt package for 'automake/1.16.2', 'libtool/2.4.6'
Try to build from sources with "--build=automake --build=libtool"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

Does the CI run with "--build=missing" flag?

**Comment by kirandivekar** [comment]
Any suggestion how this CI error can be resolved? Does not look like related to my change.

**Comment by danimtb** [comment]
This was affected by https://github.com/conan-io/conan-center-index/issues/2196, I'll rerun the CI nos as it should be already fixed

**Comment by kirandivekar** [comment]
I re-checked the CI logs. They are related to autoconf 2.69 package. Looks like same issue related to CI build in PR #2220 . which is a problem from issue #2196

**Comment by uilianries** [comment]
Need to pass run_environment to self.run

**Comment by madebr** [comment]
> Need to pass run_environment to self.run

This does not fix this problem.

Removing the dependency of `autoconf` on `m4` fixes it for me.
So it looks like `m4` and `autoconf` is still causing some problems on msys2.

**Comment by kirandivekar** [comment]
The CI logs again show a failure with autoconf. Looks like the same problem related to m4 dependancy.

**Comment by kirandivekar** [comment]
Moving changes to new PR # 2276

**Pull request closed without merging**
