### PR TITLE
libcurl: fix test package when crossbuilding from x86_64 to x86 on Windows

### LINKED ISSUE #7903: [package] libcurl: test package fails when crossbuilding from x86_64 to x86 on Windows
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl**
  * Operating System+version: **Windows 21H1**
  * Compiler+version: **VS 16.11**
  * Conan version: **conan 1.40.3**
  * Python version: **Python 3.9.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration (profile_host):
[settings]
arch=x86
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

``conan install libcurl/7.77.0@ --profile:host=windows-msvc-debug-x86 --profile:build=windows-msvc-release-x86_64 --build=libcurl``

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
build	24-Oct-2021 22:11:33	  test_package.vcxproj -> C:\bamboo-agent-home\xml-data\build-dir\THIRDPARTY-LIBCURL-JOB4\recipes\libcurl\all\test_package\build\9383702b7fc20bd2f2bd49777f62475c1274bd29\bin\test_package.exe
build	24-Oct-2021 22:11:33	  Building Custom Rule C:/bamboo-agent-home/xml-data/build-dir/THIRDPARTY-LIBCURL-JOB4/recipes/libcurl/all/test_package/CMakeLists.txt
build	24-Oct-2021 22:11:33	libcurl/7.77.0 (test package): Running test()
error	24-Oct-2021 22:11:33	ERROR: libcurl/7.77.0 (test package): Error in test() method, line 32
error	24-Oct-2021 22:11:33		output = subprocess.check_output(["file", self._test_executable]).decode()
error	24-Oct-2021 22:11:33		FileNotFoundError: [WinError 2] The system cannot find the file specified```

</details>

### PR DESCRIPTION
**Pull request by maksim-0**
Specify library name and version:  **libcurl**

Closes #7903

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by maksim-0** [comment]
> I would replace this line with something as follows:

But then it won't test anything...

**Comment by madebr** [comment]
> > I would replace this line with something as follows:
> 
> But then it won't test anything...

True.
But most other recipes test even less. Those only run the binary when not cross building, and that's it.

**Comment by SSE4** [comment]
> The actual reason for the test failing on Windows is the non-existance of the `file` utility.

AFAIK, it's not available out of the box, it needs to be installed (even on Linux)

**Review by SSE4 — APPROVED** [review]

**Comment by maksim-0** [comment]
As @SSE4 noted in https://github.com/conan-io/conan-center-index/issues/7902#issuecomment-955302864

> x64 systems may run x86 binaries, but x86 systems can't run x64 binaries.
also, it's not even true for all systems. you can run on Windows for sure (it has WOW64) and on some Linux systems (with multilib),  but macOS already dropped support for 32-bit binaries, you won't be able to run them. probably, next years situation will be getting even worse.

So my changes are valid only for Windows. I think it would be better to adopt @madebr suggestions. I'll do this soon, please do not approve current state

**Comment by uilianries** [comment]
@maksim-0 I converted your PR to draft state, so we can't merge. Remember as PR's author, you can do it too, including reverting to review state.

**Comment by madebr** [comment]
I have created a file recipe in the past, but if I remember correctly, I could not get it to compile with MSVC.
See https://github.com/madebr/conan-center-index/tree/file_recipe

**Pull request closed without merging**
