### PR TITLE
poco: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — DISMISSED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Review by jwillikers — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Comment by db4** [comment]
This PR breaks compatibility with opessl/1.1.1n. Is this expected?

**Comment by SpaceIm** [comment]
You can open an issue, but I don't understand what you mean by breaking compatibility with openssl/1.1.1n

**Comment by db4** [comment]
>  I don't understand what you mean by breaking compatibility with openssl/1.1.1n

Trying to use `poco/1.12.2` with `openssl/1.1.1n`. Poco build fails:

```
...
-- Building: Encodings
-- Building: XML
-- Building: JSON
-- Building: Util
-- Building: Net
-- Building: MongoDB
-- Building: Redis
-- Building: JWT
-- Building: Data
-- Building: ActiveRecord
-- Building: Zip
-- Configuring done
CMake Error at JWT/CMakeLists.txt:24 (target_link_libraries):
  Target "JWT" links to:

    Poco::Crypto

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
`poco/1.12.2@#a9ba7f0cfd6d672139d7f0f50f64bce4` works as expected

**Comment by SpaceIm** [comment]
That's because for some reason openssl/1.1.1n recipe is not maintained anymore. This PR of poco needs this fix in openssl recipe https://github.com/conan-io/conan-center-index/pull/12838, and openssl/1.1.1n is stuck to an older RREV.

**Comment by db4** [comment]
@SpaceIm thanks for looking into this. No, I don't need a specific version of openssl, upgrading to the latest version is OK

**Pull request merged**
