### PR TITLE
[ensmallen] Add ensmallen recipe

### LINKED ISSUE #6797: [request] ensmallen/2.17.0
### Package Details
  * Package Name/Version: **ensmallen/2.17.0**
  * Website: **https://ensmallen.org/**
  * Source code: 
      * **https://ensmallen.org/files/ensmallen-2.17.0.tar.gz**
      * **https://github.com/mlpack/ensmallen**

### Description Of The Library / Tool
ensmallen provides a simple set of abstractions for writing an objective function to optimize. It also provides a large set of standard and cutting-edge optimizers that can be used for virtually any numerical optimization task. These include full-batch gradient descent techniques, small-batch techniques, gradient-free optimizers, and constrained optimization

### PR DESCRIPTION
**Pull request by samuel-emrys**
Specify library name and version:  **ensmallen/2.19.1**

Closes #6797

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by samuel-emrys** [comment]
@RubenRBS just want to confirm that the failing pipeline here isn't a blocker to merge? I haven't developed this for conan 1.x compatibility, but it looks like it's passing the conan 2 pipeline.

**Comment by RubenRBS** [comment]
So the recipe is only v2 compatible due to some differences between the v1 and v2 integrations? Would like to understand how it's failing in v1 but no v2, as that's something a bit unexpected for me

**Comment by samuel-emrys** [comment]
@RubenRBS nevermind - I was confusing the [announcement here](https://github.com/conan-io/conan-center-index/discussions/17406) for saying that it wasn't necessary for a 1.x pipeline to pass for new recipes, where in fact it was saying that it wasn't necessary to have a `test_v1_package` with legacy generators. On a second read through, it's still important for the 1.x pipeline to pass, but it can do so with `CMakeDeps`/`CMakeToolchain`. I think the difference is being caused by a lack of a cppstd definition in CMakeLists.txt of the test_package at the moment, which conan introduces to the settings model in 2.x but was missing from 1.x (or, at least the pipelines in 1.x)

I was just saying that I haven't made any attempt to make sure this works in 1.x and was querying whether that was ok - I now understand that I do still need to test this.

**Review by RubenRBS — APPROVED** [review]
Thanks a lot for being understanding of the need to keep Conan v1 support _for now_ :)

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
