### PR TITLE
glog: delete unneeded CMakeLists.txt

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **glog/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — DISMISSED** [review]

**Comment by uilianries** [comment]
It seems this PR found an exceptional case. I gonna report it.

**Comment by danimtb** [comment]
It is not allowed to open a PR only removing files. You should add something else to those recipe files so the CI does not complain

**Comment by uilianries** [comment]
@AndreyMlashkin Please, consider https://github.com/AndreyMlashkin/conan-center-index/pull/9 It will update the test_package, which is enough to pass this PR.

**Comment by SpaceIm** [comment]
you can also replace `build_requires` by `tool_requires`

**Review by danimtb — DISMISSED** [review]

**Comment by uilianries** [comment]
@AndreyMlashkin Please, add at line 99:


```
# INFO: avoid "CONAN_LIB::gflags_gflags_nothreads_RELEASE" but the target was not found.
replace_in_file(self, os.path.join(self.source_folder, "CMakeLists.txt"),
                "determine_gflags_namespace",
                "# determine_gflags_namespace")
```

It should be applied to any version.

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
