### PR TITLE
abseil: add shared option + fix link to libm + drop few patch versions + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Ok, two issues to fix:
- shared was not supported before `20200225`. And `20200205` is a CCI version actually.
- On Windows, there is only one import library produced.

**Comment by SSE4** [comment]
are we missing `status` component?
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/third_party/abseil-cpp/absl/status/CMakeLists.txt

also there are conflicts, please rebase

**Comment by FMeinicke** [comment]
I'd like to see this PR getting merged. I assume the failing builds prevent it from getting merged. Does someone have an idea why this is?

**Comment by SpaceIm** [comment]
> I'd like to see this PR getting merged. I assume the failing builds prevent it from getting merged. Does someone have an idea why this is?


Nop, maybe shared + MT is not supported, I'll try to work on this PR later.

**Comment by SpaceIm** [comment]
The complete fix instead of https://github.com/conan-io/conan-center-index/pull/6383/commits/f336e83cdf870bf1563cd5cd4c14afa10878e2c0 is explained in https://github.com/conan-io/conan-center-index/pull/7443#issuecomment-1019947633

**Comment by SpaceIm** [comment]
@madebr @SSE4 @uilianries @ericLemanissier @prince-chrismc @toge could you review this PR please? The fix for libm is required to enable shared in grpc (https://github.com/conan-io/conan-center-index/pull/9044).

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Review by toge — APPROVED** [review]

**Comment by SpaceIm** [comment]
Thanks, I'll try to submit a PR to improve API & ABI compatibility between abseil and downstream recipes. Basically it should be freezed at CMake configuration time of abseil, but we must rely on its internal mechanism.

**Pull request merged**
