### PR TITLE
Add cppcheck 2.14

### PR DESCRIPTION
**Pull request by Sneder89**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Oh right, now it breaks with Conan 1 :/

**Comment by Sneder89** [comment]
@RubenRBS, I try to find out your intention to change the recipe. Would you explain your approach? The Line ro removed from source code `set (CMAKE_CXX_STANDARD 11 CACHE STRING "C++ standard to use")` just gets sure that C++11 features are enabled. Why did you remove that?

**Comment by RubenRBS** [comment]
Hi @Sneder89 - I misread the recipe in the begining and wanted to ensure the Cppstd values were being honored, but alas, after double checking, it seems I was wrong, sorry about the noise!

**Review by RubenRBS — APPROVED** [review]
Thanks for your patience, sorry about the noise

**Review by ericLemanissier — APPROVED** [review]

**Pull request merged**
