### PR TITLE
add rotor v0.24 release

### PR DESCRIPTION
**Pull request by basiliscos**
Specify library name and version:  **rotor/0.24**

Bump new release, I'm the library author..

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
@basiliscos 
Could you upgrade boost, If possible?

```python
    def requirements(self):
        self.requires("boost/1.69.0")
```

**Comment by basiliscos** [comment]
@toge sure, I've bumped to the latest boost version. Rotor works with all of them )

**Review by toge — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by basiliscos** [comment]
@SSE4  Seems it does not help... :(

**Comment by uilianries** [comment]
@basiliscos I just restarted it now. Let's see ...

**Comment by basiliscos** [comment]
Helped, thanks )

**Pull request merged**
