### PR TITLE
Add MartinDelille watched recipes

### PR DESCRIPTION
**Pull request by MartinDelille**
I added all the recipes I want to watch on CCI. I disabled the notification of the repository so feel free to ping me on slack if you see one of these recipes modified, I'll tell you if it works!

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
See https://github.com/conan-io/conan-center-index/pull/15554 for the fix to the failure

**Comment by prince-chrismc** [comment]
you have merge conflicts :)

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
This only works after it's merged and you will get a mention on the pull request

**Comment by MartinDelille** [comment]
My unread notification is in fact not related to this specific repositioy: https://github.com/community/community/discussions/46348

**Review by SSE4 — APPROVED** [review]

**Comment by MartinDelille** [comment]
I had my first notification so I confirm it works on my side! 👍

**Comment by prince-chrismc** [comment]
Yay!!!!!

**Pull request merged**
