### PR TITLE
config: add ceres-solver to large pod

### PR DESCRIPTION
**Pull request by prince-chrismc**
Specify library name and version:  **lib/1.0**

@SpaceIm 😀

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
I am not sure why the validate infra job is failing

**Comment by uilianries** [comment]
@prince-chrismc it fails to find msvc licenses (check if it's close to be expired).

**Review by uilianries — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by uilianries** [comment]
We will need to do a manual merge here. I guess @danimtb has power enough to execute a manual merge. Unfortunately, I don't.

**Comment by prince-chrismc** [comment]
#14855  was merged

**Pull request closed without merging**
