### PR TITLE
draco: fix MinGW + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/10106

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
mmhh, another issue of recent versions in shared builds, if shared=True, shared & static are packaged together:

```
draco/1.5.2 package(): Packaged 233 '.h' files
draco/1.5.2 package(): Packaged 1 '.4' file: libdraco.so.4
draco/1.5.2 package(): Packaged 1 '.a' file: libdraco.a
draco/1.5.2 package(): Packaged 1 '.0' file: libdraco.so.4.0.0
draco/1.5.2 package(): Packaged 1 '.so' file: libdraco.so
draco/1.5.2 package(): Packaged 1 file: LICENSE
```

due to https://github.com/google/draco/blob/1.5.2/CMakeLists.txt#L988

**Comment by AndreyMlashkin** [comment]
I am able to build it fails in test recipe
```

PS E:\sources\conan-center-index\recipes\draco\all> conan create . draco/1.5.2@ --build missing -pr gcc
Exporting package recipe
draco/1.5.2 exports: File 'conandata.yml' found. Exporting it...
draco/1.5.2 exports: Copied 1 '.yml' file: conandata.yml
draco/1.5.2 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
draco/1.5.2 exports_sources: Copied 3 '.patch' files: non-copy-ellision-workaround.patch, v1.3.5-gcc-11.patch, v1.3.6-gcc-11.patch
draco/1.5.2: The stored package has not changed
draco/1.5.2: Using the exported files summary hash as the recipe revision: bd93502e8294d74f0be9169cebfb8c25
draco/1.5.2: Exported revision: bd93502e8294d74f0be9169cebfb8c25
Configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=11.2
cppstd=17
os=Windows
[options]
*:with_embree=False
[build_requires]
[env]
CC=C:\ProgramData\chocolatey\bin\gcc.exe
CXX=C:\ProgramData\chocolatey\bin\g++.exe
[conf]
tools.cmake.cmaketoolchain:generator=Ninja

draco/1.5.2 (test package): Installing package
Requirements
    draco/1.5.2 from local cache - Cache
Packages
    draco/1.5.2:eb2df28141791403f303fa3e4bd4af0f1d327f54 - Build

Installing (downloading, building) binaries...
draco/1.5.2: Copying sources to build folder
draco/1.5.2: Building your package in E:\.conan\c36064\1
draco/1.5.2: Generator cmake created conanbuildinfo.cmake
draco/1.5.2: Aggregating env generators
draco/1.5.2: Calling build()

----Running------
> cd E:\.conan\c36064\1\build_subfolder && cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="11.2" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++11" -DBUILD_SHARED_LIBS="False" -DCMAKE_INSTALL_PREFIX="E:\.conan\4b01fc\1" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DDRACO_POINT_CLOUD_COMPRESSION="True" -DDRACO_MESH_COMPRESSION="True" -DDRACO_STANDARD_EDGEBREAKER="True" -DDRACO_PREDICTIVE_EDGEBREAKER="True" -DDRACO_ANIMATION_ENCODING="False" -DDRACO_BACKWARDS_COMPATIBILITY="True" -DDRACO_DECODER_ATTRIBUTE_DEDUPLICATION="False" -DDRACO_FAST="False" -DDRACO_GLTF="False" -DDRACO_JS_GLUE="False" -DDRACO_MAYA_PLUGIN="False" -DDRACO_TESTS="False" -DDRACO_UNITY_PLUGIN="False" -DDRACO_WASM="False" -Wno-dev E:\.conan\c36064\1
-----------------
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/ProgramData/chocolatey/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Compiler GCC>=5, checking major version 11.2
-- Conan: Checking correct version: 11.2
-- Conan: C++ stdlib: libstdc++11
-- Found PythonInterp: C:/Python310/python.exe (found version "3.10.4")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY


-- Build files have been written to: E:/.conan/c36064/1/build_subfolder

----Running------
> cmake --build E:\.conan\c36064\1\build_subfolder --target draco -- -j4
-----------------
draco/1.5.2: Package 'eb2df28141791403f303fa3e4bd4af0f1d327f54' built
draco/1.5.2: Build folder E:\.conan\c36064\1
draco/1.5.2: Generated conaninfo.txt
draco/1.5.2: Generated conanbuildinfo.txt
draco/1.5.2: Generating the package
draco/1.5.2: Package folder E:\.conan\4b01fc\1
draco/1.5.2: Calling package()
draco/1.5.2 package(): Packaged 1 file: LICENSE
draco/1.5.2 package(): Packaged 233 '.h' files
draco/1.5.2: Package 'eb2df28141791403f303fa3e4bd4af0f1d327f54' created
draco/1.5.2: Created package revision da90cd5d34a6dfad13ff4ddd7fbd280d
draco/1.5.2: WARN: Lib folder doesn't exist, can't collect libraries: E:\.conan\4b01fc\1\lib
draco/1.5.2 (test package): Generator txt created conanbuildinfo.txt
draco/1.5.2 (test package): Generator cmake created conanbuildinfo.cmake
draco/1.5.2 (test package): Aggregating env generators
draco/1.5.2 (test package): Generated conaninfo.txt
draco/1.5.2 (test package): Generated graphinfo
Using lockfile: 'E:\sources\conan-center-index\recipes\draco\all\test_package\build\b721dfa53433e49162d5b624578eadc4c7d29fa1/conan.lock'
Using cached profile from lockfile
draco/1.5.2 (test package): Calling build()

----Running------
> cd E:\sources\conan-center-index\recipes\draco\all\test_package\build\b721dfa53433e49162d5b624578eadc4c7d29fa1 && cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="11.2" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++11" -DCMAKE_INSTALL_PREFIX="E:\sources\conan-center-index\recipes\draco\all\test_package\build\b721dfa53433e49162d5b624578eadc4c7d29fa1\package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -Wno-dev E:\sources\conan-center-index\recipes\draco\all\test_package
-----------------
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/ProgramData/chocolatey/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Compiler GCC>=5, checking major version 11.2
-- Conan: Checking correct version: 11.2
-- Conan: C++ stdlib: libstdc++11
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR


-- Build files have been written to: E:/sources/conan-center-index/recipes/draco/all/test_package/build/b721dfa53433e49162d5b624578eadc4c7d29fa1

----Running------
> cmake --build E:\sources\conan-center-index\recipes\draco\all\test_package\build\b721dfa53433e49162d5b624578eadc4c7d29fa1 -- -j4
-----------------
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.obj
[100%] Linking CXX executable bin\test_package.exe
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0xa6): undefined reference to `draco::Mesh::Mesh()'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0xd3): undefined reference to `draco::GeometryAttribute::GeometryAttribute()'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0x108): undefined reference to `draco::GeometryAttribute::Init(draco::GeometryAttribute::Type, draco::DataBuffer*, signed char, draco::DataType, bool, long long, long long)'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0x11c): undefined reference to `draco::PointCloud::AddAttribute(draco::GeometryAttribute const&, bool, unsigned int)'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0x288): undefined reference to `draco::Encoder::Encoder()'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0x298): undefined reference to `draco::Encoder::SetAttributeQuantization(draco::GeometryAttribute::Type, int)'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0x2a5): undefined reference to `draco::Encoder::SetEncodingMethod(int)'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0x2b5): undefined reference to `draco::EncoderBuffer::EncoderBuffer()'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\test_package.dir/objects.a(test_package.cpp.obj):test_package.c:(.text.startup+0x2cb): undefined reference to `draco::Encoder::EncodeMeshToBuffer(draco::Mesh const&, draco::EncoderBuffer*)'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\test_package.dir\build.make:99: bin/test_package.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:82: CMakeFiles/test_package.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2
ERROR: draco/1.5.2 (test package): Error in build() method, line 12
        cmake.build()
        ConanException: Error 2 while executing cmake --build E:\sources\conan-center-index\recipes\draco\all\test_package\build\b721dfa53433e49162d5b624578eadc4c7d29fa1 -- -j4
```

**Comment by SpaceIm** [comment]
Works fine on my computer with MinGW. I've forced pushed more than once in this PR, try again.

**Comment by AndreyMlashkin** [comment]
Yes, now it works

**Review by AndreyMlashkin — DISMISSED** [review]

**Review by uilianries — DISMISSED** [review]

**Review by SSE4 — DISMISSED** [review]
is MinGW ever supported (e.g. upstream)?

**Comment by SpaceIm** [comment]
> is MinGW ever supported (e.g. upstream)?

Yes, it's even tested: https://github.com/google/draco/runs/5860496165?check_suite_focus=true

**Comment by SpaceIm** [comment]
I've fixed install destination in https://github.com/google/draco/pull/838, but upstream author doesn't want to add an option to avoid to install static if `BUILD_SHARED_LIBS ON`, so we'll have to remove static lib if shared in conanfile.py to avoid patching this library forever.

**Comment by SpaceIm** [comment]
I've fixed install destination in https://github.com/google/draco/pull/838, but upstream author doesn't want to add an option to avoid to install static if `BUILD_SHARED_LIBS ON`, so we'll have to remove static lib if shared in conanfile.py to avoid patching this library forever.

**Review by AndreyMlashkin — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by SpaceIm** [comment]
I'll submit another PR to change CMake names. draco has changed its CMake config file name (which was broken before 1.4.0 anyway), and I've submitted a PR to provide `draco::draco` imported target: https://github.com/google/draco/pull/840

**Comment by SpaceIm** [comment]
?

**Pull request merged**
