### PR TITLE
Add cppzmq/4.5.0 recipe

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **cppzmq/4.5.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@madebr please take a look: https://github.com/madebr/conan-center-index/pull/7

**Comment by SSE4** [comment]
rerun as zmq in conan center now

**Comment by Croydon** [comment]
@madebr Any specific reason why you choose this version?

Our version in Bincrafters is newer https://github.com/bincrafters/conan-cppzmq

**Comment by uilianries** [comment]
We can update it easily, but that is a good observation.

**Comment by madebr** [comment]
@Croydon The reason is quite easy.
When I opened this pr in december, the most recent version was 4.5.0.

**Pull request merged**
