### PR TITLE
add depot_tools/20200407

### PR DESCRIPTION
**Pull request by intelligide**
Specify library name and version:  **depot_tools/20200407**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Based on https://github.com/bincrafters/conan-depot_tools_installer

### CODE REVIEW

**Comment by Croydon** [comment]
Please provide at least some short link when you copy MIT licensed code

This is based on https://github.com/bincrafters/conan-depot_tools_installer

**Comment by Croydon** [comment]
This is probably of interest for @reneme 😄

**Comment by intelligide** [comment]
it's not a pre-built package, just a set of scripts (Python, bash, batch, pwsh).  There is no binaries, except the ninja one. depot_tools is used by some projects like crashpad.

**Comment by reneme** [comment]
Looks good to me, thanks for the effort!

I was wondering on what criteria you selected the depot-tools version to be [48c5c9c](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/48c5c9c50455c625c58dab2fbb0904cac467168c) (2020-04-07).
On bincrafters we are on a more recent version ([5e0a4a6](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/5e0a4a6b8088fc55794b51d1919c13ac4ae6ef0c)  - 2020-05-15) that unfortunately [required to remove `DEPOT_TOOLS_UPDATE=0` to work on Windows](https://github.com/bincrafters/community/issues/1198). However, it contains a commit ([c621315](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/c621315d173a9832fc7dcbf3854fe53cdfc5ee6c)) that claims to switch depot_tools to Python 3 on Windows by default. Your revision of depot_tools does not include that commit.

Admittedly, I didn't take the time to look deeper into the commit history of depot_tools to find a more suitable version (i.e. that works with Python3 and does not have the mentioned bootstrapping problem on windows).

**Comment by intelligide** [comment]
[48c5c9c](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/48c5c9c50455c625c58dab2fbb0904cac467168c) is just the last version that support DEPOT_TOOLS_UPDATE=0 on Windows.

**Comment by reneme** [comment]
In case you have insights on what broke the bootstrapping on Windows, I'd be glad if you could share them with the developers here: https://bugs.chromium.org/p/chromium/issues/detail?id=1067590#c7. It seems they didn't fix that upstream yet.

**Pull request merged**
