### PR TITLE
add recipe protobuf/3.5.2@

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **protobuf/3.5.2@**

add recipe protobuf/3.5.2@ needed by opencv dnn module

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Pretty sure you want to add protobuf 3.5.2 for OpenCV, but it's not required, vcpkg is able to build dnn feature with latest protobuf, try first to properly rebuild .proto files in OpenCV recipe please.

**Comment by AndreyMlashkin** [comment]
> Pretty sure you want to add protobuf 3.5.2 for OpenCV, but it's not required, vcpkg is able to build dnn feature with latest protobuf, try first to properly rebuild .proto files in OpenCV recipe please.

yes, exactly, I have written it in the ticket description. I don't know how to trigger a rebuild of proto files. The ways, that I have tried didn't work for me.
I think it would be easier first add dnn support with version 3.5.2 and then bump the version as an improvement.

**Comment by SpaceIm** [comment]
I don't think it's a good idea, I've explained how to trigger a rebuild of proto files, it's easy.

**Review by uilianries — CHANGES_REQUESTED** [review]
Please, follow @SpaceIm comments. Protobuf is a complex project, we don't need 3.5.2 now.

**Pull request closed without merging**
