### PR TITLE
update recipe for itk/5.3.0 - issue 15104 

### LINKED ISSUE #15104: [request] itk/5.3.0
### Package Name/Version

itk/5.3.0

### Changelog

https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.3.0

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

### PR DESCRIPTION
**Pull request by Ruwei**
itk/5.3.0 

This is a dependency of other libraries I want to package. I'm not the author of itk and have limited knowledge with it. 

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).

- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

   The instructions[ here](https://github.com/conan-io/conan-center-index/blob/master/docs/developing_recipes_locally.md) seem to be wrong and the command "conan config set hooks.conan-center" doesn't work. 
   I have tried with one configuration locally without the hook activated.

### CODE REVIEW

**Review by valgur — APPROVED** [review]

**Comment by AbrilRBS** [comment]
Hi @Ruwei thanks a lot for taking the time to add the new version of itk, we appreciate your effort and patience while we got this thru the backlog of PRs.

As per https://github.com/conan-io/conan-center-index/pull/23039#issuecomment-1986799628, it seems like at least 1 of the commits is authored by `ray-amcax` which means a CLA sign from that account is also needed, or if you prefer, force-pushing the branch to only have 1 commit comming from you would also be ok. Note that I've updated the branch to allow this to properly build after #23135 was merged :)

**Review by AbrilRBS — DISMISSED** [review]

**Comment by uilianries** [comment]
I just checked itk cmake files and are looking good, versions 5.2.0 and 5.3.0 differ their macros and included files.

I'll investigate Conan 1.x errors.

**Comment by uilianries** [comment]
I could not reproduce the test package error locally, it's working for this recipe revision and package ID.

[itk-5.3.0-linux-static.log](https://github.com/user-attachments/files/16978145/itk-5.3.0-linux-static.log)

I just re-triggered the build again.

**Comment by AbrilRBS** [comment]
Closing in favour of https://github.com/conan-io/conan-center-index/pull/25246, where I've kept proper authoring of commits, thanks a lot for your contribution :)=

**Pull request closed without merging**
