### PR TITLE
libsndfile: moving forlder all => pkg_config

### PR DESCRIPTION
**Pull request by MartinDelille**
Specify library name and version:  **libsndfile/1.0.28**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

I just moved the libsndfile folder for the 1.0.28 version after the discussion [here](https://github.com/conan-io/conan-center-index/issues/2491)

### CODE REVIEW

**Comment by madebr** [comment]
`pkg_config` is a weird name and not correct because it has nothing to do with the `pkg_config` generator (=.pc files).
Let's just rename it to `1.0.28`?

**Comment by MartinDelille** [comment]
@madebr Ok fixed. I used `pkg_config` because it was the recipe generator name and I named the other folder `cmake`. Should I use `all` for the next to come versions?

**Comment by madebr** [comment]
I think `all` will be fine. With that name, we send the message that new versions should use that recipe.

**Comment by MartinDelille** [comment]
I checked everything so this PR look compliant to me.

**Comment by uilianries** [comment]
@MartinDelille Could you please update the cmake version in test_package/CMakeLists ? There is a new hook which affects this recipe. Regards!

**Comment by MartinDelille** [comment]
Indeed! That makes build green! 😸

**Comment by MartinDelille** [comment]
@uilianries It looks like this PR only need approvals now.

**Review by uilianries — DISMISSED** [review]
Thanks!

**Review by SSE4 — APPROVED** [review]

**Review by danimtb — DISMISSED** [review]

**Comment by danimtb** [comment]
@MartinDelille sorry for the delay in the review. There are some conflicts, could you please take a look?

**Comment by MartinDelille** [comment]
Conflict solved.

**Review by uilianries — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
