### PR TITLE
mongo-c-driver: force package rebuild

### PR DESCRIPTION
**Pull request by mathbunnyru**
Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Shouldn't it be fixed by conan team in charge of conan-center?

**Comment by mathbunnyru** [comment]
Yep, it should be.

**Comment by Croydon** [comment]
@danimtb @jgsogo shouldn't this Tapaholes tool fix missing packages?

**Comment by uilianries** [comment]
Yes, but the number of packages is huge + new compilers.

**Comment by Croydon** [comment]
Ah, forgot that it already produces packages for new compilers :partying_face: 

So basically, let's be patient?

**Comment by uilianries** [comment]
Yes!

**Comment by mathbunnyru** [comment]
@uilianries is everything ok here and we should wait longer?

**Comment by mathbunnyru** [comment]
🎉 let's go for a merge while it works and generated right number of packages.

**Comment by Croydon** [comment]
Since the problem seems to be with merges, doing another merge might not solve anything 🤔

**Comment by mathbunnyru** [comment]
> Since the problem seems to be with merges, doing another merge might not solve anything 🤔

I do agree, that the problem is bigger and needs some infrastructural changes.

In the meantime, while the problem is not solved, I think only a part of merges do not work well and we can merge PRs like this.

**Review by SSE4 — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Comment by jgsogo** [comment]
> @danimtb @jgsogo shouldn't this Tapaholes tool fix missing packages?

Hi. There are two different types of errors and two different types of Tapaholes jobs:
 * One of them is easy. There is a Tapaholes job that checks that every reference (latest revision computed from sources) in the source repository is available in ConanCenter. It is fast, this job only needs to compute ~1500 recipe revisions and check they are available.
 * The other job is the hard one. It tries to check that all the binaries for a given recipe-revision are available in ConanCenter. This job iterates the latest revision of every reference in ConanCenter and computes all the packageIDs for each one of them... this is ~1500*150 packages. If any of them is missing, it will compile the package.

The first one is working flawlessly, but we are facing different problems with the second one. Not only the time it takes but the memory... and if we run out of memory in the K8s cluster everything crashes. 😓  We are exploring alternatives, for example we are thinking about adding a cache to avoid computing all the packageIDs again and again (key: recipe revision + profiles-file, value: computed packageIds).

**Review by jgsogo — APPROVED** [review]
This could have been fixed by us internally, but this new revision will do the work too.

**Comment by mathbunnyru** [comment]
> This could have been fixed by us internally, but this new revision will do the work too.

I don't think so. The latest version I see it still 1.17.2, while it should be 1.17.3.

**Comment by jgsogo** [comment]
The frontend (https://conan.io/center) ATM doesn't use the same database as the Artifactory you hit when running Conan in the terminal (`conan search`). This is due to the way information from different sources is gathered together: packages from this repository, existing packages from the old `conan-community` and packages provided via inclusion-request from bintray.

I agree that information should be synced, but for us (now) it is much more important to improve and add consistency to the CI, the Artifactory server and the actual packages than to the frontend information. Of course it deserves attention, and we will get there.

Thanks!

**Comment by jgsogo** [comment]
One more bit of information, maybe I didn't explained myself 🧑‍🏫 . A missing package in the frontend won;t be detected by any of the Tapaholes I mentioned previously. All those jobs are looking only at the Artifactory, not at the frontend.

**Comment by mathbunnyru** [comment]
> One more bit of information, maybe I didn't explained myself 🧑‍🏫 . A missing package in the frontend won;t be detected by any of the Tapaholes I mentioned previously. All those jobs are looking only at the Artifactory, not at the frontend.

Thanks.
Just a note: `conan search mongo-c-driver/1.17.3@ --table=file.html -r conan-center` still gives only 87 packages, not 88, so I think the issue wasn't resolved by tapaholes in this case.

**Comment by jgsogo** [comment]
After the merge, new revisions are uploaded and there are 88 packages 👍 

 * `conan search mongo-c-driver/1.17.3@ --table=file.html -r conan-center`
 * `conan search mongo-c-driver/1.17.2@ --table=file.html -r conan-center`

Just for completeness, packages for new configurations have failed due to missing dependencies. These are the extra packages we are (trying) to generate on every PR but they don't make the build to fail: [mongo-c-driver/1.17.3](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/4087/3/mongo-c-driver/1.17.3//summary.json) and [mongo-c-driver/1.17.2](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/4087/3/mongo-c-driver/1.17.2//summary.json)

**Pull request merged**
