### PR TITLE
bzip3: add version 1.1.8

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **bzip3/1.1.8**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by kspalaiologos** [comment]
Hello! I'm afraid that the license marker for bzip3 being changed to

```
license = "LGPL-3.0", "Apache-2.0"
```

does not reflect the actual licensing situation. The Apache-2.0 license applies only to libsais, not bzip3 as a whole.

**Comment by toge** [comment]
@kspalaiologos 
Sorry. I misunderstood.
I revert it.

**Comment by kspalaiologos** [comment]
No. Please add the **license text** for Apache 2.0 back, because it's required by `libsais`, but don't change the license field of bzip3 as a whole.

**Comment by toge** [comment]
@kspalaiologos 
I understand. Thanks!

**Comment by kspalaiologos** [comment]
Thanks :).

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@kspalaiologos Thank you for reviewing!

**Pull request merged**
