### PR TITLE
Add frugally-deep version 0.15.24-p0

### PR DESCRIPTION
**Pull request by Dobiasd**

### CODE REVIEW

**Comment by Dobiasd** [comment]
Are the failing CI jobs real errors, or do the jobs just need to be re-run?

**Comment by RubenRBS** [comment]
It seems to be real error when running tests for visual studio with the new version in both cases yes
Maybe the new version needs a newer visual studio or something?

**Comment by Dobiasd** [comment]
Is there a way for me to view the error log from the Visual Studio tests?

**Comment by Dobiasd** [comment]
Ah, I found [this](https://c3i.jfrog.io/c3i/misc/logs/pr/19953/2-windows-visual_studio/frugally-deep/0.15.22-p0//5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9-test.txt).

That looks weird. The [tests in the frugally-deep CI succeed](https://github.com/Dobiasd/frugally-deep/actions). :monocle_face:

**Comment by Dobiasd** [comment]
Oh, yes, that was a real issue in my code. I just [fixed it](https://github.com/Dobiasd/frugally-deep/commit/2c280db0a670929147cb8922aad6ce5896817708), released [a new version](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.15.23-p0), and [updated this pull request accordingly](https://github.com/conan-io/conan-center-index/pull/19953/commits/55fbff52df475364505d83ee4a029aace7b9274a).

**Review by RubenRBS — APPROVED** [review]

**Comment by Dobiasd** [comment]
@RubenRBS The PR logs say that I dismissed your review. Sorry, this was not my intention, and I don't remember doing this.

Is something blocking this PR?

**Comment by RubenRBS** [comment]
No worries, Github auto dismisses reviews when new commits are pushed, so that no unreviewed changes get thru - I see that the new runs are failing, will investigate the reason

**Review by RubenRBS — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Pull request merged**
