### PR TITLE
implot: Include source code to support customized imgui builds

### PR DESCRIPTION
**Pull request by technoyes**
Update the `implot` package to also include the source code. This allows building in projects where customized versions of the `imgui` library is needed. This is in line with recently merged PR #19877 for `imgui`. Tagging  @RubenRBS and @czoido who were involved in that PR.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated. _[Conan Center hook is [not supported](https://github.com/conan-io/hooks#conan-2x-support) for 2.x yet it seems?]_

### CODE REVIEW

**Comment by technoyes** [comment]
Just a note: This PR does not conflict with #20374 as the the `implot` source code is included as passive files in a separate directory.

**Comment by technoyes** [comment]
Updated PR moving the included source from `src/` to `res/src/` in order to conform to https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H013-DEFAULT-PACKAGE-LAYOUT .

**Comment by technoyes** [comment]
I'm not quite sure what is up with the CI.  The previous run gave this error on the Mac OS build:

```
-------- Downloading 1 package --------
imgui/1.89.9: Retrieving package bfac49f477c2b8a07274dbc39ebe0ccf5a1f85bb from remote 'conan-center' 
imgui/1.89.9: ERROR: Exception while getting package: bfac49f477c2b8a07274dbc39ebe0ccf5a1f85bb
imgui/1.89.9: ERROR: Exception: <class 'conans.errors.ConanException'> Corrupted imgui/1.89.9:bfac49f477c2b8a07274dbc39ebe0ccf5a1f85bb in 'conan-center' remote: no conaninfo.txt
ERROR: Corrupted imgui/1.89.9:bfac49f477c2b8a07274dbc39ebe0ccf5a1f85bb in 'conan-center' remote: no conaninfo.txt
```

This time the messages are just "This commit cannot be built" and "The build of this commit was aborted".

Any assistance to review this tiny PR and/or gently nudge the CI would be appreciated. @RubenRBS @czoido @Hopobcn

**Comment by technoyes** [comment]
CI ran again and everything looks good except that same corrupted imgui package:
``` 
 Corrupted imgui/1.89.9:bfac49f477c2b8a07274dbc39ebe0ccf5a1f85bb in 'conan-center' remote: no conaninfo.txt
```

Not quite sure what more I can do here.

**Comment by uilianries** [comment]
@technoyes This is an internal error, smell like a corrupted file 😞 . Let's update the branch and re-build it again.

**Comment by technoyes** [comment]
No need to apologize! Thank you for all the hard work you put into this project! I'm just scratching my itch here really.

**Comment by czoido** [comment]
> */*:shared=True

I have launched a job in ci to regenerate the package, let's see if that helps

**Comment by technoyes** [comment]
Whatever you did with the CI seems to have resolved the problem @czoido  \o/ Thank you too @uilianries for helping.

This PR should be ready for review then.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by danimtb — APPROVED** [review]

**Pull request merged**
