### PR TITLE
Added DataFrame 1.14.0

### PR DESCRIPTION
**Pull request by hosseinmoein**
Specify library name and version:  **DataFrame/1.14.0**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by theirix** [comment]
already filled in PR #3422

**Comment by madebr** [comment]
> already filled in PR #3422

But this one's working! 😅

**Review by madebr — APPROVED** [review]

**Comment by Croydon** [comment]
@theirix's PR is explicitly disabling testing for the newer versions so I think it is better :)

**Comment by hosseinmoein** [comment]
> @theirix's PR is explicitly disabling testing for the newer versions so I think it is better :)

Out of curiosity, why are we disabling tests for versions greater than 1.12.0?

**Comment by theirix** [comment]
> > @theirix's PR is explicitly disabling testing for the newer versions so I think it is better :)
> 
> Out of curiosity, why are we disabling tests for versions greater than 1.12.0?

Why we disable tests? Conan recipes usually disable tests because it increases the build time without obvious benefits. Testing of packages is usually done via `test_package` which ensures proper linking and/or basic functionality test.

It is done only for 1.14.0 and later because 1.14.0 introduced a compilation option to do so. Versions <=1.8.0 are patched explicitly. Only version 1.12.0 is left with enabled tests because existing patches do not apply so it was packaged without patches.

**Comment by hosseinmoein** [comment]
So, should I abandon this PR?

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
