### PR TITLE
gdk-pixbuf: bump glib

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@ericLemanissierBot build

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6059087198)

**Comment by ericLemanissier** [comment]
@RubenRBS thanks, but it looks like your change somehow breaks consumption when all libraries are static: https://github.com/ericLemanissier/proof-of-conan/actions/runs/6059087198/job/16441845129#step:8:517

**Review by RubenRBS — DISMISSED** [review]

**Comment by RubenRBS** [comment]
Using this PR to also bump libpng :)

**Review by uilianries — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
