### PR TITLE
nlopt: fix cmake target + delete fPIC if shared + propagate C++ lib if cxx routines

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **nlopt/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018: The "GetOutOfDateItems" task failed unexpectedly. [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018: System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "x64\Release\generate-fortran\generate-fortran.tlog\ParallelCustomBuild.command.1.tlog". Path: x64\Release\generate-fortran\generate-fortran.tlog\ParallelCustomBuild.command.1.tlog exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args) [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018:    at Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(String currentDirectory, String itemSpec, String definingProjectEscaped, String modifier, String& fullPath) [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018:    at Microsoft.Build.Utilities.TaskItem.Microsoft.Build.Framework.ITaskItem2.GetMetadataValueEscaped(String metadataName) [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018:    at Microsoft.Build.Utilities.TaskItem.GetMetadata(String metadataName) [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018:    at Microsoft.Build.CPPTasks.GetOutOfDateItems.Execute() [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(181,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\J\workspace\onan-center-pull-request_PR-2182@2\1\pr_2182_1_0_10\.conan\data\nlopt\2.6.2\_\_\build\fe5b759e1115594409fcd579fe1dbb721e3ee0ce\build_subfolder\source_subfolder\generate-fortran.vcxproj]
```
Again :disappointed_relieved:

**Comment by jgsogo** [comment]
Something related to path length? https://github.com/microsoft/msbuild/issues/4226#issuecomment-561721481

**Comment by SpaceIm** [comment]
Yes but it's not a new recipe. Did changes in CI increase path where recipes builds occur?
Moreover one of my PR have short_paths, and still fail with path length error.
I would like to avoid adding short_paths (tedious to navigate into folders) if it's not necessary.

**Comment by jgsogo** [comment]
> Yes but it's not a new recipe. Did changes in CI increase path length where recipes builds occur?

Yes. All the builds were moved to the _workspace folder_, but at the same time we removed the Windows short-path limitation.... after reading the issue I linked, it looks like MSBuild can have problems with long paths 😞 

> Moreover one of my PR has `short_paths=True`, and still fails with path length error [#1931 (comment)](https://github.com/conan-io/conan-center-index/pull/1931#issuecomment-653678910)
> I would like to avoid adding short_paths (tedious to navigate into folders) if it's not necessary.

In CCI, even those recipes with `short_paths=True` are built inside the _workspace folder_, so, if the problem is with any of the tools (like MSBuild) regardless of the Windows registry key, it looks like this was a bad move and we need to revert it.

**Pull request merged**
