### PR TITLE
Add Gtkmm recipe

### PR DESCRIPTION
**Pull request by planetmarshall**
Specify library name and version:  **gtkmm/4.6.1**

New recipe

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by planetmarshall** [comment]
Marked as draft as requires #11399

**Comment by hesham-essam** [comment]
Note that shared gtkmm 4 will link against gtk 4 which links against shared cairo/pango/glib and it will also link against shared cairomm/pangomm which will link against static cairo/pango/glib.
This will most definitely cause unintended behaviour. A patch similar to this https://github.com/conan-io/conan-center-index/pull/11093 needs to applied for cairomm and pangomm first.

**Comment by hesham-essam** [comment]
Note that shared gtkmm will link against static glib which will cause it to get a different instance of glib from all other dependencies. See https://github.com/conan-io/conan-center-index/issues/11022.
Also a patch similar to https://github.com/conan-io/conan-center-index/pull/11093#event-6794627327 needs to be applied to cairomm and pangomm first.

**Comment by hesham-essam** [comment]
Inner dependency options are not always respected if they're not part of the id of the package.
See https://github.com/conan-io/conan/issues/11396
Since pangomm and cairomm don't use `full_package_mode` with `glib` conan can use a cached version of pangomm/cairomm that use a static glib.

**Pull request closed without merging**
