### PR TITLE
(#4530) Include the mysqld_error.h header in mariadb-connector-c

### PR DESCRIPTION
**Pull request by floriansimon1**
Specify library name and version:  **lib/1.0**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by floriansimon1** [comment]
I had to reupload my commit with my correct email in order to sign the CLA.

**Comment by floriansimon1** [comment]
@SpaceIm I would appreciate it if you could review this, given you originally wrote that recipe 😃

**Comment by prince-chrismc** [comment]
Why do you need this file? Trying to see if it meets #3903

Looking through the code it's completely private and I do not see why it's required.
https://github.com/mariadb-corporation/mariadb-connector-c/search?q=ma_server_error
This is absolutely a discrepancy because of our `cmake_wrapper` I am just curious before I approve 👍 

It was also explicitly excluded https://github.com/mariadb-corporation/mariadb-connector-c/commit/11321f16bfcd92e210d5736af7b7d5073a89c2ef (see commit message) though I am not sure the meaning of "server"

**Comment by floriansimon1** [comment]
Hi,

First of all, thanks for your interest in my pull request! I understand your concerns, and I will try to address them.

So, our source code uses these error codes to interpret what the errors returned by `unsigned int STDCALL mysql_stmt_errno(MYSQL_STMT * stmt);` (`mariadb_stmt.h`) mean. Without that header, it's difficult to understand what the error codes mean. They're basically just random numbers.

I have tried looking for another way to source the definition of these errors, but I haven't managed to find anything saying that you need a second library of headers to get a definition of error codes. I guess that makes sense, since MariaDB is supposed to be a drop-in replacement for MySQL. It wouldn't make sense to mix the two. And they don't really provide a set of headers, as far as I can tell.

If you download their distribution [there](https://downloads.mariadb.org/connector-c/), the file is in there, so I wouldn't say it's private. I think they would have removed it from the release otherwise.

Moreover, the `IS_SUBPROJECT` condition seems to suggest that this project can be integrated in other projects (such as the Maria DB server), in which case this file is undesirable. It's not the case here: we're not a subproject of a bigger whole, we're a standalone library.

I could try setting `IS_SUBPROJECT` to `false`, but from what I gathered it would be kind of pointless. Doing so would mean pulling in some Windows specific code setting variables such as build types, compile flags (can't remember the exact details) which I think would interfere with Conan. My thinking is this would lead to some more patching. I'd rather just pull in the header I need than make the code too complex.

Worst case scenario, if we determine we do in fact need to set `IS_SUBPROJECT` to `false`, we can remove my very simple patch and go for the more complex option. Doing the reverse is a bit more complex, given how unintuitive that would be.

Now, take what I say about `IS_SUBPROJECT` with a grain of salt. I haven't confirmed that with any official source. All I know is that, before our move to Conan, we had that file and we've always included it. When we moved to the Conan recipe forked off something we got from a random GitHub repo, we still had that header. When I tried using the official recipe rather than the hack we had working, it stopped compiling.

Unfortunately, that issue prevents us from moving to the official recipe.

Thanks a lot for your time!

**Comment by floriansimon1** [comment]
PS: I think the Maria DB server is the actual database daemon, as opposed to the client which talks to it or the connector which is meant to be used as a library in external programs.

**Comment by floriansimon1** [comment]
See https://github.com/mariadb-corporation/mariadb-connector-c/commit/d3644be080222abd73d830751d1580b481d3f2eb for a commit message explaining what `ma_server_error` is.

The file itself is [here](https://github.com/mariadb-corporation/mariadb-connector-c/blob/3.1/include/ma_server_error.h).

**Review by SpaceIm — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Seems like it's a common problem... https://github.com/search?q=mysqld_error.h&type=commits
MySQL problems 🤷

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
