### PR TITLE
ctpg: add version 1.3.7

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **ctpg/***

ctpg<=1.3.6 places `ctpg.hpp` in `include`.
ctpg/1.3.7 places `ctpg.hpp` in `include/ctpg`.

To simplify recipe, I divide 2 versions.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
You could use a small conditional to copy according the version, instead of creating a new separated recipe. 

```python
if tools.Version(self.version) >= "1.3.7":
    self.copy(...)
else:
    self.copy(...)
```

**Comment by toge** [comment]
@uilianries 
OK. I will try.

**Comment by toge** [comment]
@uilianries 
Thanks for the advice.
I'll try it this way.

**Comment by toge** [comment]
@uilianries 
Fixed.
Please review again.

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
