### PR TITLE
add lzfse/1.0

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lzfse/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

https://github.com/conan-io/conan-center-index/issues/621

### CODE REVIEW

**Comment by uilianries** [comment]
@SpaceIm please, consider https://github.com/SpaceIm/conan-center-index/pull/5

**Comment by SpaceIm** [comment]
@uilianries 
- If I understand, it is preferred to also build exe if available, so that the package can also be used as a build requirement?
- except for `POSITION_INDEPENDENT_CODE TRUE`, modifications in patch files seems to be useless (LZFSE_BUNDLE_MODE is False). Therefore, is not a better solution to use replace_in_file, since patches can be painful to maintain across versions.

**Comment by uilianries** [comment]
> If I understand, it is preferred to also build exe if available, so that the package can also be used as a build requirement?

Yes. As that package is more about the library and not the executable, it doesn't require an extra package only for the installer.

> except for POSITION_INDEPENDENT_CODE TRUE, modifications in patch file seems to be useless (LZFSE_BUNDLE_MODE is False). Therefore, is not a better solution to use replace_in_file, since patches can be painful to maintain across versions.

No, because it forces BUILD_SHARED_LIBS.

**Comment by SpaceIm** [comment]
When LZFSE_BUNDLE_MODE is False, BUILD_SHARED_LIBS is an option, therefore it's not forced.

**Comment by uilianries** [comment]
Sorry, indeed it's an option. I need to update that patch.

**Comment by uilianries** [comment]
@SpaceIm , done, please take a look again on that PR

**Comment by SpaceIm** [comment]
@uilianries, last part of the patch file is also useless. You can keep the original replace_in_file I think, and remove references to patch file in conandata.yml and conanfile.py.

**Comment by uilianries** [comment]
hmm, that's true too. @SpaceIm please, ignore that patch and call cmake.install() instead.

**Comment by uilianries** [comment]
Thanks @SpaceIm !

**Pull request merged**
