### PR TITLE
(#19767) qt: exclude examples from license pattern

### PR DESCRIPTION
**Pull request by mrjoel**
Don't include license files for examples when the example content is not built.

Specify library name and version:  **qt/5.x.x**, **qt/6.x.x**

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by RubenRBS** [comment]
Thanks a lot for your report and submitting an issue to fix it too! Really appreciated. I'll approve this once the bit gives you access, thanks for your patience! :)

**Review by ericLemanissier — APPROVED** [review]

**Comment by RubenRBS** [comment]
Checking why hafbuz binaries are missing, thanks a lot for your patience

**Review by MartinDelille — APPROVED** [review]

**Comment by RubenRBS** [comment]
They have been available for a bit, did not get the time to circle back to this PR until now, thanks a lot for your patience :)

**Comment by RubenRBS** [comment]
Super sorry about the bot noise, it got stuck on an endless loop, I should have stopped it now

**Review by ericLemanissier — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
