### PR TITLE
thrift: conan v2 support + fix static on non-windows in 0.13.0

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/12535

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
LGTM

**Review by jgsogo — APPROVED** [review]

**Comment by markaren** [comment]
Prior to this change, we could do `find_program(THRIFT_EXECUTABLE NAMES thrift)` in order to locate the thrift compiler. This does not seem to be the case anymore. Any idea how to fix?

**Comment by SpaceIm** [comment]
I don't know, but `thrift` executable is properly packaged in bin folder from what I see in logs of this PR. You can open an issue describing how you require thrift in conan (requires, tool_requires etc), the kind of generators you are using, how you call CMake, and a minimal CMakeLists.

**Comment by uilianries** [comment]
@markaren please, open an issue describing your case with more details. Maybe your Conan client is outdated.

**Comment by markaren** [comment]
We managed to get it working with `find_program(THRIFT_EXECUTABLE NAMES thrift HINTS ${CONAN_THRIFT_ROOT}/bin`. 
If we encounter future issues, I might spend some more debugging hours and make an issue out of it.

**Pull request merged**
