### PR TITLE
openvino: fix yaml

### PR DESCRIPTION
**Pull request by AMDmi3**
### Summary
Changes to recipe:  **openvino**

Remove stray `patch:` line which breaks the schema. 

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by jcar87** [comment]
Thanks @AMDmi3 - apologies for this, this was detected by our CI but not correctly reported before merging - I'll make sure this is addressed.

Remember we can only merge this after the CLA is signed, thanks :)

**Comment by AMDmi3** [comment]
I'm not signing any CLAs, sorry, but if it's not fixed I'll have to remove ConanCenter from Repology.

**Comment by jcar87** [comment]
Given that this is a trivial change we can take care of this, closing in favour of https://github.com/conan-io/conan-center-index/pull/26111.

Please note that unless I'm mistaken, this is not an error: the yaml passes yamllint validation and is correctly processed by Conan - it is equivalent of having `patches: null`, which afaik is valid yaml. I'm unsure of the Repology integration, but it may be worth accounting for things like this.

on the other hand, it does happen that our linter has the ability to pick this up, but it is a warning and not necessarily an error.

**Comment by AMDmi3** [comment]
> Please note that unless I'm mistaken, this is not an error

This is a valid yaml, yes, but at least Repology doesn't expect that what supposed to be a list becomes null suddenly. Is there a schema definition for the format?

**Pull request closed without merging**
