### PR TITLE
mozjpeg: add components + cache cmake + del fPIC if shared + fix build requirements

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **mozjpeg/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/2716/commits/d401bf5233a098dbc147b610b790a0598fb21b63 requires at least conan 1.28.2 due to https://github.com/conan-io/conan/pull/7622

**Comment by uilianries** [comment]
1.28.2 is already available for download, but not yet in CCI. It should be updated in some days.

**Comment by SpaceIm** [comment]
conan was not updated to 1.29.1 in CI?

Still have this error `ERROR: module 'six.moves' has no attribute 'collections_abc'`

**Comment by uilianries** [comment]
@SpaceIm Yes, but only yesterday: https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md

**Comment by SpaceIm** [comment]
@uilianries I saw, thanks. PR can be reviewed now.

**Review by uilianries — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
