### PR TITLE
premake: add 5.0.0-beta2

### PR DESCRIPTION
**Pull request by Croydon**
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
same issue as https://github.com/conan-io/conan-center-index/pull/10241
TLDR : Windows 11 SDK (10.0.22200) is no longer compatible with VS15. we don't know if it's by design and it will be never compatible, or was a bug and will be fixed in newer Windows SDK.
right now, we share the same machine for VS15/16/17, and vcvars tends to pick just latest Windows SDK by default (so VS15 build picks Windows SDK installed by VS17).
technically, import libraries in new SDK contain `XFGHASHMAP` section, which VS15 linker doesn't recognize.

**Comment by Croydon** [comment]
There are more problems here

**Comment by Croydon** [comment]
> C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x64\crypt32.lib : fatal error LNK1127: library is corrupt

**Comment by risuwwv** [comment]
Hello, any update on this ? The version in https://conan.io/center/premake does not support vs2022 so I would like beta2.

**Comment by Croydon** [comment]
> Hello, any update on this ? The version in https://conan.io/center/premake does not support vs2022 so I would like beta2.

No updates from my side, unfortunately. If someone wants to investigate the error message in the builds above this would be great. 

My own motivation for Premake is pretty low and the only project I know that used it now also offers CMake.

**Pull request closed without merging**
