### PR TITLE
Add snitch 1.2.3

### PR DESCRIPTION
**Pull request by cschreib**
Specify library name and version:  **snitch/1.2.3**

Hi there, I am the author of this library and would like to contribute a recipe for it.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by cschreib** [comment]
I will add a patch of o lower the minimum CMake version. That should fix the v1 pipeline. For the V2 pipeline, I don't know yet.

**Comment by cschreib** [comment]
For v1 pipeline: No idea at this stage. I will look at the logs further and see if I can replicate the error on my end. Looks like it involved a generated `conanfile.py`, I guess that comes from your CI infrastructure, in which case it might be a bit difficult to diagnose.

For v2 pipeline: I don't know how this slipped through the cracks, but it seems my CMake scripts actually still require CMake 3.19 features. I will add more thorough tests with CMake 3.14, which is the advertised minimum version.

**Comment by cschreib** [comment]
Note: I have migrated the library from my personal GitHub account to a dedicated organization, to allow for more than one maintainer. Hence all the URLs have been updated.

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
@cschreib Thank you for your first contribution here in ConanCenterIndex! I see your recipe is looking real good. We still need one more positive review to be merged.

More info about our review process: https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
