### PR TITLE
add jasper 2.0.14

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **jasper/2.0.14**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
There seem to be no binary for linux on conan-center index (`conan search -r conan-center jasper/2.0.14@_/_ -q "os=Linux"`). Is it a temporary CCI issue, or a recipe issue ?

**Comment by lasote** [comment]
Checking. By the way, the correct way is using `conan search -r conan-center jasper/2.0.14@ -q "os=Linux"` Use the ref ending with @ to disambiguate a pattern. The "_/_" will stop working at some point.

**Comment by lasote** [comment]
There was an issue with an update. I'll regenerate the packages ASAP.

**Comment by lasote** [comment]
It is done. Thanks for reporting.

**Pull request merged**
