### PR TITLE
libkml: add a patch for C++17 compatibility

### PR DESCRIPTION
**Pull request by valgur**
https://github.com/libkml/libkml/pull/275

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]
Thanks! Feel free to ping me once upstream ahs approved this :)

**Comment by valgur** [comment]
@RubenRBS I'm doubtful the project/fork is actually being maintained. The last release was in 2015.

**Comment by jcar87** [comment]
> @RubenRBS I'm doubtful the project/fork is actually being maintained. The last release was in 2015.

Thanks @valgur  for looking into this.
As per our policy, we do not accept patches to C or C++ where upstream might not. If this is an unmaintained library that does not support C++17, then it should raise an the InvalidConfiguration exception when cppstd=17. We provide libraries built from their sources as-is. By plugging fixes that the upstream maintainers won't, this essentially makes the Conan team responsible for the ongoing maintenance of a library fork.

In general, if the change _truly_ is trivial, please provide more context in the PR description to support this claim. Opening a PR upstream is unfortunately not enough, especially if the authors are known to not respond. We do review upstream PRs/issues and require that the upstream maintainers acknowledge, comment, and confirm whether the proposed solution is what they would include in future versions.

Changing the base class of a C++ class or struct has side effects in the ABI. Conan will not cause a rebuild of consumers_ of `libkml/1.3.0` unless the major or minor components have changed, or other settings have.  So the change proposed in this PR _could_ cause link errors in consumers, provided some conditions were met. I think in this case this would typically be that an public function accepts an object (by value) of the `GetElement` struct. It's unclear to me whether that is the case, but we are not familiar with the codebase to make a call on this.

**Comment by valgur** [comment]
@jcar87 Fair enough.

It would indeed argue that this change is trivial and should not have any effects on the ABI, API or the behavior of the library. The `GetElement` functor is used only locally in an `std::for_each()` and is not declared in any headers, so it won't be linked against even in the same project let alone external libs.

Here's the single usage:
https://github.com/libkml/libkml/blob/916a801ed3143ab82c07ec108bad271aa441da16/src/kml/xsd/xsd_file.cc#L51-L69

**Comment by jcar87** [comment]
On which compiler is this a problem?
The last time this recipe built on CI, it passed with C++17 on both Linux and macOS (with gcc and apple-clang).
https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/20193/1/libkml/1.3.0//summary.json

**Comment by ericLemanissier** [comment]
on msvc : https://github.com/eirikb/proof-of-conan/actions/runs/8830426628/job/24243544036#step:11:521

**Comment by valgur** [comment]
> would have been useful in the description as well

I'll start actually updating descriptions when you fix #18780.

**Comment by jcar87** [comment]
> > would have been useful in the description as well
> 
> I'll start actually updating descriptions when you fix #18780.

Please keep in mind that the team may not review, prioritise and should certainly not merge PRs with incomplete information.  

Even if updating the description results in a new run, the packages are not rebuilt if the commit hasn't changed - it reruns the tests, which should be faster.

**Comment by jcar87** [comment]
> @jcar87 The need for more context info in the description is usually proportional to the size of the PR, which in turn usually depends on the complexity of the recipe and the project.

I would say this PR is a good example of that not being the case. That's why we found it confusing knowing that there _are_ binaries published where C++17 was actually used - we don't know where this fails, why, and if the fixes proposed actually fix what the title is claiming to fix, which turned out not to be the case. Having the information at hand will help the review team get to this quicker.

**Comment by jcar87** [comment]
However this is a distraction. We are asking to provide this information when **opening** the PR.

**Pull request closed without merging**
