### PR TITLE
highway: add version 1.2.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **highway/1.2.0**

https://github.com/google/highway/compare/1.1.0...1.2.0

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
Waiting for https://github.com/google/highway/issues/2225.

**Comment by toge** [comment]
@RubenRBS 
Now ci is passed.
Please review it.

**Review by RubenRBS — APPROVED** [review]
Thanks a lot for the follow-up :)

**Review by uilianries — APPROVED** [review]
LGTM. There is a new support for header-only in the library now, but can be added later as it's experimental: https://github.com/google/highway/compare/1.1.0...1.2.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR83

**Pull request merged**
