### PR TITLE
arrow: add version 16.1.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **arrow/16.1.0**

https://github.com/apache/arrow/compare/apache-arrow-16.0.0...apache-arrow-16.1.0

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
@RubenRBS 
Would you help this PR?
CI failed with folliwing messages:
> Do not raise ConanInvalidConfiguration from build() method. Please, move that same check to validate() method.

But `build()` doesn't call `ConanInvalidConfiguration()` on any conditions.
https://github.com/conan-io/conan-center-index/blob/d634f9c8c076ccef0ace6a934c6f3928523fdf0f/recipes/arrow/all/conanfile.py#L410-L414

Are there any way to workaround this?

**Comment by RubenRBS** [comment]
Curious! Will have a loon asap :)

**Comment by RubenRBS** [comment]
This PR is blocked until we fix an issue in the CI regarding our usage of `conan graph info`, will retrigger once that's ready :)

**Review by RubenRBS — APPROVED** [review]
Thanks a lot for your patience! The issue has now been fixed and the PR correctly compiles now :)

**Pull request merged**
