### PR TITLE
caf: add version 1.0.0

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **caf/1.0.0**

#### Motivation
major version up.

#### Details
https://github.com/actor-framework/actor-framework/compare/0.19.4...1.0.0

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by RubenRBS — COMMENTED** [review]
Maybe it would be a nice idea set `CAF_CXX_VERSION` now that we're at it?

**Review by uilianries — COMMENTED** [review]
The version 1.0.0 adds a new option: https://github.com/actor-framework/actor-framework/compare/0.19.4...1.0.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR78

`set(CAF_CXX_VERSION 17 CACHE STRING "Set the C++ version to use for CAF")`

Need to configure it via generate:

```
def generate(self):
        tc = CMakeToolchain(self)
        if not valid_min_cppstd(self, self._min_cppstd):
            tc.variables["CMAKE_CXX_STANDARD"] = self._min_cppstd
        else:
            tc.variables["CAF_CXX_VERSION"] = str(self.settings.compiler.cppstd).replace("gnu", "")
```

**Comment by toge** [comment]
@AbrilRBS  @uilianries 
Thanks for your review!
Fixed.

**Review by uilianries — APPROVED** [review]
LGTM! Thank you!

**Review by AbrilRBS — APPROVED** [review]
Thanks! :)

**Pull request merged**
