### PR TITLE
libgd: support xpm and webp, add package_type

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **libgd/***

Since all libgd versions of cci support xpm and webp, this PR attempts to add an option to support them.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]
Thanks! Let's see what the CI says

**Review by RubenRBS — CHANGES_REQUESTED** [review]
Woops, seems like I approved a bit too soon, I'm getting compilation errors locally:

```
conan create . --version=2.3.3 -o="&:with_webp=True" -o="&:with_xpm=True" -b=missing

======== Exporting recipe to the cache ========
libgd/2.3.3: Exporting package recipe: /libgd/conanfile.py
libgd/2.3.3: exports: File 'conandata.yml' found. Exporting it...
libgd/2.3.3: Calling export_sources()
libgd/2.3.3: Copied 1 '.yml' file: conandata.yml
libgd/2.3.3: Copied 1 '.py' file: conanfile.py
libgd/2.3.3: Copied 3 '.patch' files: 2.3.3-use-cci.patch, 2.3.3-qualify-nondll.patch, 2.3.x-png-msvc.patch
libgd/2.3.3: Exported to cache folder: /root/.conan2/p/libgd05210c0bfa907/e
libgd/2.3.3: Exported: libgd/2.3.3#48999ad59dd882cd44e8a65bcda7af4a (2024-03-10 00:04:52 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
&:with_webp=True
&:with_xpm=True
[conf]
tools.files.download:verify=False
tools.system.package_manager:mode=install

Profile build:
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[conf]
tools.files.download:verify=False
tools.system.package_manager:mode=install


======== Computing dependency graph ========
Graph root
    cli
Requirements
    libgd/2.3.3#48999ad59dd882cd44e8a65bcda7af4a - Cache
    libwebp/1.3.2#52f69c4a31c5cf033fdd9230d77a8e38 - Cache
    libxpm/3.5.13#7b5b8458b41e7ec9f169289050d94cf3 - Cache
    xorg/system#f626cbdd0ba57d9c53bce2d8b9362fad - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache
Resolved version ranges
    zlib/[>=1.2.11 <2]: zlib/1.3.1

======== Computing necessary packages ========
Requirements
    libgd/2.3.3#48999ad59dd882cd44e8a65bcda7af4a:9487a95ef873d67803c4d6aae54b7296eb8d1b95 - Build
    libwebp/1.3.2#52f69c4a31c5cf033fdd9230d77a8e38:b7ce4e3346ff773fa5350546582465a81de70904#1f195b4eccda0039a3642703042f0df0 - Cache
    libxpm/3.5.13#7b5b8458b41e7ec9f169289050d94cf3:91c7babc09fc498c72179a494ecb00e7ba563ac9#c755fea5061bc7fb29fc8b4dcf404ef0 - Cache
    xorg/system#f626cbdd0ba57d9c53bce2d8b9362fad:da39a3ee5e6b4b0d3255bfef95601890afd80709#0ba8627bd47edc3a501e8f0eb9a79e5e - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:31ae95bed32b612c7c18c2732aec878920f35b7f#142eb5cf2c351c16ca4ff2773567c239 - Cache
xorg/system: System requirements:  already installed
xorg/system: System requirements:  already installed

======== Installing packages ========
libwebp/1.3.2: Already installed! (1 of 5)
xorg/system: Already installed! (2 of 5)
zlib/1.3.1: Already installed! (3 of 5)
libxpm/3.5.13: Already installed! (4 of 5)

-------- Installing package libgd/2.3.3 (5 of 5) --------
libgd/2.3.3: Building from source
libgd/2.3.3: Package libgd/2.3.3:9487a95ef873d67803c4d6aae54b7296eb8d1b95
libgd/2.3.3: Copying sources to build folder
libgd/2.3.3: Building your package in /root/.conan2/p/b/libgd0083c23fc9e8c/b
libgd/2.3.3: Calling generate()
libgd/2.3.3: Generators folder: /root/.conan2/p/b/libgd0083c23fc9e8c/b/build/Release/generators
libgd/2.3.3: CMakeToolchain generated: conan_toolchain.cmake
libgd/2.3.3: CMakeToolchain generated: CMakePresets.json
libgd/2.3.3: CMakeToolchain generated: ../../../src/CMakeUserPresets.json
libgd/2.3.3: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(ZLIB)
    find_package(libxpm)
    find_package(WebP)
    target_link_libraries(... ZLIB::ZLIB libxpm::libxpm libwebp::libwebp)
libgd/2.3.3: Generating aggregated env files
libgd/2.3.3: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
libgd/2.3.3: Calling build()
libgd/2.3.3: Apply patch (portability): use BGD_NONDLL instead NONDLL
libgd/2.3.3: Apply patch (portability): support png on msvc
libgd/2.3.3: Apply patch (conan): use cci's package
libgd/2.3.3: Running CMake.configure()
libgd/2.3.3: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan2/p/b/libgd0083c23fc9e8c/b/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan2/p/b/libgd0083c23fc9e8c/p" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan2/p/b/libgd0083c23fc9e8c/b/src"
-- Using Conan toolchain: /root/.conan2/p/b/libgd0083c23fc9e8c/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- gd version 2.3.3
-- gd shared lib version 3 (3.0.11)
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Conan: Target declared 'ZLIB::ZLIB'
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (ZLIB) does
  not match the name of the calling package (WEBP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /root/.conan2/p/b/libgd0083c23fc9e8c/b/build/Release/generators/FindZLIB.cmake:45 (find_package_handle_standard_args)
  cmake/modules/FindWEBP.cmake:40 (include)
  CMakeLists.txt:137 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: 1.3.1 (found version "1.3.1") 
CMake Error at cmake/modules/FindWEBP.cmake:66 (message):
  Could not find WEBP library
Call Stack (most recent call first):
  CMakeLists.txt:137 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/root/.conan2/p/b/libgd0083c23fc9e8c/b/build/Release/CMakeFiles/CMakeOutput.log".

libgd/2.3.3: ERROR: 
Package '9487a95ef873d67803c4d6aae54b7296eb8d1b95' build failed
libgd/2.3.3: WARN: Build folder /root/.conan2/p/b/libgd0083c23fc9e8c/b/build/Release
ERROR: libgd/2.3.3: Error in build() method, line 118
	cmake.configure()
	ConanException: Error 1 while executing
```

**Comment by toge** [comment]
Sorry.
I will fix it soon.

**Comment by RubenRBS** [comment]
No worries, let me know if you need any help :)

**Comment by toge** [comment]
@RubenRBS 

I update this PR. It seems to work fine.
Please review it again.

<details>
$ conan create . --version=2.3.3 -o="&:with_webp=True" -b=missing

======== Exporting recipe to the cache ========
libgd/2.3.3: Exporting package recipe: /work/conanfile.py
libgd/2.3.3: exports: File 'conandata.yml' found. Exporting it...
libgd/2.3.3: Calling export_sources()
libgd/2.3.3: Copied 1 '.yml' file: conandata.yml
libgd/2.3.3: Copied 1 '.py' file: conanfile.py
libgd/2.3.3: Copied 3 '.patch' files: 2.3.3-qualify-nondll.patch, 2.3.x-png-msvc.patch, 2.3.3-use-cci.patch
libgd/2.3.3: Exported to cache folder: /home/conan/.conan2/p/libgd83e9edf99750a/e
libgd/2.3.3: Exported: libgd/2.3.3#9249ac7ddae30b7d2a419a810c602287 (2024-03-11 08:50:27 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
&:with_webp=True

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    libgd/2.3.3#9249ac7ddae30b7d2a419a810c602287 - Cache
    libwebp/1.3.2#52f69c4a31c5cf033fdd9230d77a8e38 - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache
Resolved version ranges
    zlib/[>=1.2.11 <2]: zlib/1.3.1

======== Computing necessary packages ========
Requirements
    libgd/2.3.3#9249ac7ddae30b7d2a419a810c602287:c3022267fc0d9420614c10fc412d21ce7acba902 - Build
    libwebp/1.3.2#52f69c4a31c5cf033fdd9230d77a8e38:18f01a3f175888d5e3d128efe30c14773afadc83#e55816e5d48a3854454abdc32720bcad - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:b647c43bfefae3f830561ca202b6cfd935b56205#6b307bbcbae23635c4006543ffdbf3ef - Cache

======== Installing packages ========
libwebp/1.3.2: Already installed! (1 of 3)
zlib/1.3.1: Already installed! (2 of 3)
libgd/2.3.3: Calling source() in /home/conan/.conan2/p/libgd83e9edf99750a/s/src

-------- Installing package libgd/2.3.3 (3 of 3) --------
libgd/2.3.3: Building from source
libgd/2.3.3: Package libgd/2.3.3:c3022267fc0d9420614c10fc412d21ce7acba902
libgd/2.3.3: Copying sources to build folder
libgd/2.3.3: Building your package in /home/conan/.conan2/p/b/libgd5eb10e637d9f8/b
libgd/2.3.3: Calling generate()
libgd/2.3.3: Generators folder: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/build/Release/generators
libgd/2.3.3: CMakeToolchain generated: conan_toolchain.cmake
libgd/2.3.3: CMakeToolchain generated: CMakePresets.json
libgd/2.3.3: CMakeToolchain generated: ../../../src/CMakeUserPresets.json
libgd/2.3.3: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(ZLIB)
    find_package(WebP)
    target_link_libraries(... ZLIB::ZLIB libwebp::libwebp)
libgd/2.3.3: Generating aggregated env files
libgd/2.3.3: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
libgd/2.3.3: Calling build()
libgd/2.3.3: Apply patch (portability): use BGD_NONDLL instead NONDLL
libgd/2.3.3: Apply patch (portability): support png on msvc
libgd/2.3.3: Apply patch (conan): use cci's package
libgd/2.3.3: Running CMake.configure()
libgd/2.3.3: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/conan/.conan2/p/b/libgd5eb10e637d9f8/p" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/src"
-- Using Conan toolchain: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Check for working C compiler: /usr/local/bin/cc
-- Check for working C compiler: /usr/local/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- gd version 2.3.3
-- gd shared lib version 3 (3.0.11)
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Conan: Target declared 'ZLIB::ZLIB'
-- Conan: Component target declared 'WebP::webpdecoder'
-- Conan: Component target declared 'WebP::sharpyuv'
-- Conan: Component target declared 'WebP::webp'
-- Conan: Component target declared 'WebP::webpdemux'
-- Conan: Component target declared 'WebP::libwebpmux'
-- Conan: Target declared 'libwebp::libwebp'
Looking for naturaldocs....
-- Found Perl: /usr/bin/perl (found suitable version "5.22.1", minimum required is "5.8") 
-- Could NOT find NaturalDocs (missing: NATURALDOCS_EXECUTABLE) (Required is at least version "1.51")
/usr/bin/perl/home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/src/docs/naturaldocs/nobgd.pl/home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/src/docs/../src/home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/build/Release/docs/tmp
............................................................................................
0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/build/Release

libgd/2.3.3: Running CMake.build()
libgd/2.3.3: RUN: cmake --build "/home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/build/Release" -- -j12
Scanning dependencies of target gd_static
[  1%] Building C object src/CMakeFiles/gd_static.dir/gd.c.o
[  3%] Building C object src/CMakeFiles/gd_static.dir/gd_avif.c.o
[  5%] Building C object src/CMakeFiles/gd_static.dir/gd_bmp.c.o
[  6%] Building C object src/CMakeFiles/gd_static.dir/gd_color.c.o
[  8%] Building C object src/CMakeFiles/gd_static.dir/gd_color_map.c.o
[ 10%] Building C object src/CMakeFiles/gd_static.dir/gd_crop.c.o
[ 11%] Building C object src/CMakeFiles/gd_static.dir/gd_color_match.c.o
[ 13%] Building C object src/CMakeFiles/gd_static.dir/gd_filename.c.o
[ 15%] Building C object src/CMakeFiles/gd_static.dir/gd_filter.c.o
[ 16%] Building C object src/CMakeFiles/gd_static.dir/gd_gd.c.o
[ 18%] Building C object src/CMakeFiles/gd_static.dir/gd_gd2.c.o
[ 20%] Building C object src/CMakeFiles/gd_static.dir/gd_gif_in.c.o
[ 21%] Building C object src/CMakeFiles/gd_static.dir/gd_gif_out.c.o
[ 23%] Building C object src/CMakeFiles/gd_static.dir/gd_heif.c.o
[ 25%] Building C object src/CMakeFiles/gd_static.dir/gd_interpolation.c.o
[ 26%] Building C object src/CMakeFiles/gd_static.dir/gd_io.c.o
[ 28%] Building C object src/CMakeFiles/gd_static.dir/gd_io_dp.c.o
[ 30%] Building C object src/CMakeFiles/gd_static.dir/gd_io_file.c.o
[ 31%] Building C object src/CMakeFiles/gd_static.dir/gd_io_ss.c.o
[ 33%] Building CXX object src/CMakeFiles/gd_static.dir/gd_io_stream.cxx.o
[ 38%] Building C object src/CMakeFiles/gd_static.dir/gd_nnquant.c.o
[ 38%] Building C object src/CMakeFiles/gd_static.dir/gd_matrix.c.o
[ 38%] Building C object src/CMakeFiles/gd_static.dir/gd_jpeg.c.o
[ 40%] Building C object src/CMakeFiles/gd_static.dir/gd_png.c.o
[ 41%] Building C object src/CMakeFiles/gd_static.dir/gd_rotate.c.o
[ 43%] Building C object src/CMakeFiles/gd_static.dir/gd_security.c.o
[ 45%] Building C object src/CMakeFiles/gd_static.dir/gd_ss.c.o
[ 46%] Building C object src/CMakeFiles/gd_static.dir/gd_tga.c.o
[ 48%] Building C object src/CMakeFiles/gd_static.dir/gd_tiff.c.o
[ 50%] Building C object src/CMakeFiles/gd_static.dir/gd_topal.c.o
[ 51%] Building C object src/CMakeFiles/gd_static.dir/gd_transform.c.o
[ 53%] Building C object src/CMakeFiles/gd_static.dir/gd_version.c.o
[ 55%] Building C object src/CMakeFiles/gd_static.dir/gd_wbmp.c.o
[ 56%] Building C object src/CMakeFiles/gd_static.dir/gd_webp.c.o
[ 58%] Building C object src/CMakeFiles/gd_static.dir/gd_xbm.c.o
[ 60%] Building C object src/CMakeFiles/gd_static.dir/gdcache.c.o
[ 61%] Building C object src/CMakeFiles/gd_static.dir/gdfontg.c.o
[ 63%] Building C object src/CMakeFiles/gd_static.dir/gdfontl.c.o
[ 65%] Building C object src/CMakeFiles/gd_static.dir/gdfontmb.c.o
[ 66%] Building C object src/CMakeFiles/gd_static.dir/gdfonts.c.o
[ 70%] Building C object src/CMakeFiles/gd_static.dir/gdfontt.c.o
[ 70%] Building C object src/CMakeFiles/gd_static.dir/gdft.c.o
[ 71%] Building C object src/CMakeFiles/gd_static.dir/gdfx.c.o
[ 73%] Building C object src/CMakeFiles/gd_static.dir/gdhelpers.c.o
[ 75%] Building C object src/CMakeFiles/gd_static.dir/gdkanji.c.o
[ 76%] Building CXX object src/CMakeFiles/gd_static.dir/gdpp.cxx.o
[ 78%] Building C object src/CMakeFiles/gd_static.dir/gdtables.c.o
[ 80%] Building C object src/CMakeFiles/gd_static.dir/gdxpm.c.o
[ 81%] Building C object src/CMakeFiles/gd_static.dir/wbmp.c.o
[ 83%] Linking CXX static library ../Bin/libgd.a
[ 83%] Built target gd_static
Scanning dependencies of target gdcmpgif
Scanning dependencies of target gd2copypal
Scanning dependencies of target gd2togif
Scanning dependencies of target giftogd2
Scanning dependencies of target gif
[ 85%] Building C object src/CMakeFiles/gdcmpgif.dir/gdcmpgif.c.o
[ 86%] Building C object src/CMakeFiles/giftogd2.dir/giftogd2.c.o
[ 88%] Building C object src/CMakeFiles/gd2copypal.dir/gd2copypal.c.o
[ 90%] Building C object examples/CMakeFiles/gif.dir/gif.c.o
[ 91%] Building C object src/CMakeFiles/gd2togif.dir/gd2togif.c.o
[ 93%] Linking CXX executable ../Bin/giftogd2
[ 95%] Linking CXX executable ../Bin/gd2togif
[ 96%] Linking CXX executable ../Bin/gd2copypal
[ 98%] Linking CXX executable ../Bin/gif
[100%] Linking CXX executable ../Bin/gdcmpgif
[100%] Built target gif
[100%] Built target gd2copypal
[100%] Built target giftogd2
[100%] Built target gd2togif
[100%] Built target gdcmpgif

libgd/2.3.3: Package 'c3022267fc0d9420614c10fc412d21ce7acba902' built
libgd/2.3.3: Build folder /home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/build/Release
libgd/2.3.3: Generating the package
libgd/2.3.3: Packaging in folder /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p
libgd/2.3.3: Calling package()
libgd/2.3.3: Running CMake.install()
libgd/2.3.3: RUN: cmake --install "/home/conan/.conan2/p/b/libgd5eb10e637d9f8/b/build/Release" --prefix "/home/conan/.conan2/p/b/libgd5eb10e637d9f8/p"
-- Install configuration: "Release"
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/INSTALL
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/README.JPN
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/README.CMAKE
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/README.TESTING
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/README.TXT
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/arc.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/copyrotated.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/crop.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/flip.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/gif.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/nnquant.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/noIcon.pic
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/noIcon.sgi
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/noIcon.tga
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/noIconAlpha.tga
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/test_crop_threshold.png
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/tgaread.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/tiffread.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/share/doc/gd-2.3/windows.c
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/gdcmpgif
-- Set runtime path of "/home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/gdcmpgif" to ""
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/gd2copypal
-- Set runtime path of "/home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/gd2copypal" to ""
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/gd2togif
-- Set runtime path of "/home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/gd2togif" to ""
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/giftogd2
-- Set runtime path of "/home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/giftogd2" to ""
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/lib/libgd.a
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin/bdftogd
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gd.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gd_color_map.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gd_errors.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gd_io.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gdcache.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gdfontg.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gdfontl.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gdfontmb.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gdfonts.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gdfontt.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gdfx.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/include/gdpp.h
-- Installing: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/lib/pkgconfig/gdlib.pc

libgd/2.3.3: package(): Packaged 6 files
libgd/2.3.3: package(): Packaged 1 '.a' file: libgd.a
libgd/2.3.3: package(): Packaged 12 '.h' files
libgd/2.3.3: Created package revision 4c31be76e4832d4b591c67b585b57f1c
libgd/2.3.3: Package 'c3022267fc0d9420614c10fc412d21ce7acba902' created
libgd/2.3.3: Full package reference: libgd/2.3.3#9249ac7ddae30b7d2a419a810c602287:c3022267fc0d9420614c10fc412d21ce7acba902#4c31be76e4832d4b591c67b585b57f1c
libgd/2.3.3: Package folder /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p
libgd/2.3.3: Appending PATH environment variable: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: libwebp/1.3.2, zlib/1.3.1, libgd/2.3.3
WARN: deprecated:     'env_info' used in: libgd/2.3.3

======== Launching test_package ========

======== Computing dependency graph ========
Graph root
    libgd/2.3.3 (test package): /work/test_package/conanfile.py
Requirements
    libgd/2.3.3#9249ac7ddae30b7d2a419a810c602287 - Cache
    libwebp/1.3.2#52f69c4a31c5cf033fdd9230d77a8e38 - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache

======== Computing necessary packages ========
Requirements
    libgd/2.3.3#9249ac7ddae30b7d2a419a810c602287:c3022267fc0d9420614c10fc412d21ce7acba902#4c31be76e4832d4b591c67b585b57f1c - Cache
    libwebp/1.3.2#52f69c4a31c5cf033fdd9230d77a8e38:18f01a3f175888d5e3d128efe30c14773afadc83#e55816e5d48a3854454abdc32720bcad - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:b647c43bfefae3f830561ca202b6cfd935b56205#6b307bbcbae23635c4006543ffdbf3ef - Cache

======== Installing packages ========
libwebp/1.3.2: Already installed! (1 of 3)
zlib/1.3.1: Already installed! (2 of 3)
libgd/2.3.3: Already installed! (3 of 3)
libgd/2.3.3: Appending PATH environment variable: /home/conan/.conan2/p/b/libgd5eb10e637d9f8/p/bin
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: libwebp/1.3.2, zlib/1.3.1, libgd/2.3.3
WARN: deprecated:     'env_info' used in: libgd/2.3.3

======== Testing the package ========
Removing previously existing 'test_package' build folder: /work/test_package/build/gcc-11-x86_64-gnu17-release
libgd/2.3.3 (test package): Test package build: build/gcc-11-x86_64-gnu17-release
libgd/2.3.3 (test package): Test package build folder: /work/test_package/build/gcc-11-x86_64-gnu17-release
libgd/2.3.3 (test package): Writing generators to /work/test_package/build/gcc-11-x86_64-gnu17-release/generators
libgd/2.3.3 (test package): Generator 'CMakeDeps' calling 'generate()'
libgd/2.3.3 (test package): CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(libgd)
    target_link_libraries(... libgd::libgd)
libgd/2.3.3 (test package): Generator 'CMakeToolchain' calling 'generate()'
libgd/2.3.3 (test package): CMakeToolchain generated: conan_toolchain.cmake
libgd/2.3.3 (test package): CMakeToolchain generated: CMakePresets.json
libgd/2.3.3 (test package): CMakeToolchain generated: ../../../CMakeUserPresets.json
libgd/2.3.3 (test package): Generator 'VirtualRunEnv' calling 'generate()'
libgd/2.3.3 (test package): Generating aggregated env files
libgd/2.3.3 (test package): Generated aggregated env files: ['conanrun.sh', 'conanbuild.sh']

======== Testing the package: Building ========
libgd/2.3.3 (test package): Calling build()
libgd/2.3.3 (test package): Running CMake.configure()
libgd/2.3.3 (test package): RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/work/test_package/build/gcc-11-x86_64-gnu17-release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/work/test_package" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/work/test_package"
-- Using Conan toolchain: /work/test_package/build/gcc-11-x86_64-gnu17-release/generators/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 17 with extensions ON
-- The C compiler identification is GNU 11.1.0
-- Check for working C compiler: /usr/local/bin/cc
-- Check for working C compiler: /usr/local/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: Target declared 'libgd::libgd'
-- Conan: Target declared 'ZLIB::ZLIB'
-- Conan: Component target declared 'WebP::webpdecoder'
-- Conan: Component target declared 'WebP::sharpyuv'
-- Conan: Component target declared 'WebP::webp'
-- Conan: Component target declared 'WebP::webpdemux'
-- Conan: Component target declared 'WebP::libwebpmux'
-- Conan: Target declared 'libwebp::libwebp'
-- Configuring done
-- Generating done
-- Build files have been written to: /work/test_package/build/gcc-11-x86_64-gnu17-release

libgd/2.3.3 (test package): Running CMake.build()
libgd/2.3.3 (test package): RUN: cmake --build "/work/test_package/build/gcc-11-x86_64-gnu17-release" -- -j12
Scanning dependencies of target test_package
[ 50%] Building C object CMakeFiles/test_package.dir/test_package.c.o
[100%] Linking C executable test_package
[100%] Built target test_package


======== Testing the package: Executing test ========
libgd/2.3.3 (test package): Running test()
libgd/2.3.3 (test package): RUN: ./test_package
</details>

**Review by RubenRBS — APPROVED** [review]
Works great now, thanks a lot! :)

**Review by jwillikers — APPROVED** [review]

**Pull request merged**
