### PR TITLE
Add boost 1.69.0

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **boost/1.69.0**

Boost 1.69.0 is a requirement for CPP Rest SDK 2.10.14 (latest)

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@danimtb https://c3i.jfrog.io/c3i/misc/logs/pr/498/1/boost/1.69.0/135d4a21bfa90506eb1aef5fccdc3f6a4a55a620/create_stderr.txt says bzip2/1.0.8 not available under package id 3df6ebb8a308d309e882b21988fd9ea103560e16. However, I can find it easily by running conan search on Conan Center. It seems be an index problem, or connection problem maybe.

**Comment by Minimonium** [comment]
@danimtb @uilianries same in the #499

**Comment by uilianries** [comment]
Again, same error, bzip2/1.0.8 not found :crying_cat_face:

**Comment by uilianries** [comment]
@Minimonium Thanks for pointing!

**Comment by SSE4** [comment]
@uilianries it doesn't build on MSVC (bootstrap fails)
maybe it's better to ask CppRest guys to provide new(er) release with support to modern boost?
1.69 is pretty old, and 1.72 is an actual version, I doubt it makes a lot of sense to add outdated releases (which don't support modern compilers)

**Comment by uilianries** [comment]
@SSE4 I agree, I gonna do it.

**Comment by uilianries** [comment]
Interesting, there are more people complaining about the same thing:

https://github.com/microsoft/cpprestsdk/issues/1302
https://github.com/microsoft/cpprestsdk/issues/1299


They provided a patch, but is available only in develop branch. More info here:
https://github.com/microsoft/cpprestsdk/issues/1302#issuecomment-570943263

We can wait, or use that patch.

**Comment by SSE4** [comment]
@uilianries seems like this old boost version doesn't know about Visual Studio 2019. so, it would be nice to raise an invalid configuration for that case.

**Comment by uilianries** [comment]
I found that patch here: https://github.com/boostorg/build/compare/boost-1.69.0...boost-1.70.0.patch

**Pull request merged**
