### PR TITLE
xkbcommon: put wayland-protocols in build requirements irrespective of one or dual profile + bump dependencies

### PR DESCRIPTION
**Pull request by SpaceIm**
wayland-protocols is a build requirement and it must be removed from requirements if 1 profile. Requirements (not build requirements) must never depend on settings_build.
The workaround is not manually generate pkgconfig file of wayland-protocols if 1 profile.

See also this discussion https://github.com/conan-io/conan-center-index/pull/20545#issuecomment-1793814822

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Version conflict in v2 pipeline, should be solved by https://github.com/conan-io/conan-center-index/pull/21240

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
```
wayland/1.22.0: Retrieving package 043edf4cba7b52083018f38129b2e38fab6d08a8 from remote 'conan-center' 
wayland/1.22.0: Package installed 043edf4cba7b52083018f38129b2e38fab6d08a8
wayland/1.22.0: Downloaded package revision 8c6a5ecc298db48891eb0ca38cf0f373
wayland/1.22.0: Retrieving package 38653ff482676cf8215ed47452383921f0118b56 from remote 'conan-center' 
wayland/1.22.0: ERROR: Exception while getting package: 38653ff482676cf8215ed47452383921f0118b56
wayland/1.22.0: ERROR: Exception: <class 'conans.errors.ConanException'> Corrupted wayland/1.22.0:38653ff482676cf8215ed47452383921f0118b56 in 'conan-center' remote: no conaninfo.txt
ERROR: Corrupted wayland/1.22.0:38653ff482676cf8215ed47452383921f0118b56 in 'conan-center' remote: no conaninfo.txt
```

@RubenRBS @uilianries @danimtb do you know what's wrong here?

**Comment by RubenRBS** [comment]
Good catch, this is a corrupted package coming from transient network errors when doing the final promotion in wayland's last pr - we are actually just now putting checks in place to ensure this does not go unnoticed (we already check for some corruptions but not all of them)

I'll regenerate the bad ones and retrigger the pr once they are available :)

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
Why does it fail in v2 pipeline now? 🤔

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6942907267)

**Comment by SpaceIm** [comment]
```
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb

ERROR: xkbcommon/1.6.0 (test package): Error in test() method, line 27
	self.run(cmd, env="conanrun")
	ConanException: Error 1 while executing
```

@RubenRBS @danimtb @uilianries could you help please with this error in v2 pipeline? It was building fine in https://github.com/conan-io/conan-center-index/pull/21239#issuecomment-1819774153. I didn't change anything and nothing has changed in recipes of dependencies (just made the mistake to merge master, which has triggered a new build).

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Comment by SpaceIm** [comment]
```
xkbcommon/0.10.0: Retrieving package 7f0796d38c082e1820c3885fac4cbad263cd7100 from remote 'c3i_PR-21239' 
xkbcommon/0.10.0: WARN: Package binary is corrupted, removing: 7f0796d38c082e1820c3885fac4cbad263cd7100
ERROR: Binary package not found: 'xkbcommon/0.10.0:7f0796d38c082e1820c3885fac4cbad263cd7100'
```

😢

**Comment by SpaceIm** [comment]
@danimtb @uilianries could you help with this corrupted package please?

**Review by jwillikers — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
