### PR TITLE
glog: fix cmake_find_package{,_multi} names

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **glog/0.4.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/2363#issuecomment-668222965

@madebr Where did you find these names?

In glog master branch:
- config files is `glog-config.cmake`: https://github.com/google/glog/blob/0a2e5931bd5ff22fd3bf8999eb8ce776f159cda6/CMakeLists.txt#L835
- "config" target is `glog::glog`: https://github.com/google/glog/blob/0a2e5931bd5ff22fd3bf8999eb8ce776f159cda6/CMakeLists.txt#L846

I don't see any official module file for `glog`.

**Comment by madebr** [comment]
@SpaceIm 
Indeed, I was wrong.
I just checked google for `cmake find glob` and combinations with `find` and `config`.
Thanks for rectifying.

**Comment by madebr** [comment]
This might mean that some dependency on glog will break.
I don't know remember which one exactly it was..

**Comment by SpaceIm** [comment]
There are only 2 recipes depending on `glog` in CCI: `folly` and `ceres-solver`

**Comment by madebr** [comment]
Thanks, then I'll have to search in projects.

**Comment by SpaceIm** [comment]
folly recipe works fine if lowercase cmake name is restored (this why I came here :p https://github.com/conan-io/conan-center-index/pull/2363#issuecomment-668132666). Didn't check ceres-solver with glog enabled.

**Pull request merged**
