### PR TITLE
BugFix: Update assimp's Draco version from 1.5.5 to 1.5.6 to resolve build error

### PR DESCRIPTION
**Pull request by seppeon**
Specify library name and version:  **lib/1.0**

Before 1.5.6 there was a bug in draco that prevented builds. This was a missing `#include <cstdint>` inside `fileutils.h`. By 1.5.6 this was fixed, this PR bumps in order to get assimp buildable.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by seppeon** [comment]
Fixing: https://github.com/conan-io/conan-center-index/issues/18287

**Review by StellaSmith — APPROVED** [review]

**Review by CJCombrink — APPROVED** [review]

**Comment by seppeon** [comment]
Do I need to do anything to make progress here?

**Review by EstebanDugueperoux2 — APPROVED** [review]

**Comment by StellaSmith** [comment]
> Do I need to do anything to make progress here?

If your request got accepted you can close and reopen the pull request to trigger CI again

**Comment by EstebanDugueperoux2** [comment]
You must also ask write access through https://github.com/conan-io/conan-center-index/issues/4

**Pull request merged**
