### PR TITLE
cairomm v2 toolchain

### PR DESCRIPTION
**Pull request by planetmarshall**
Specify library name and version:  **cairomm**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jcar87** [comment]
I've pushed a fix for the error in the v1 pipeline, as well as some small cleanup to the test_package CMakeLists to align it with the current template.
```
ERROR: cairomm/1.16.1: Error in configure() method, line 56
	self.dependencies["cairo"].options.shared = True
	KeyError: {'ref': cairo/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}
```

Which should also cause the v2 checks to run again. Will keep an eye on this one.

Thanks for your contribution!

**Comment by planetmarshall** [comment]
Getting a test package failure on conan 2.0.10 (succeeds on 1.61) due to the transitive dependency on libsigcpp - something to do with component requires? Can't figure it out.

**Comment by planetmarshall** [comment]
> Getting a test package failure on conan 2.0.10 (succeeds on 1.61) due to the transitive dependency on libsigcpp - something to do with component requires? Can't figure it out.

Ah, it's the new `transitive_headers` thing.

**Comment by valgur** [comment]
cairomm has been migrated to Conan v2: #18884. This PR can probably be closed.

**Comment by jcar87** [comment]
Closing this in favour of https://github.com/conan-io/conan-center-index/pull/18884 - 
@planetmarshall  please let me know if there's anything pending that still needs to be merged, thanks!

**Pull request closed without merging**
