### PR TITLE
zlib: generate relocatable shared lib on macOS + drop 1.2.8 maintenance

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/9052

+ see https://github.com/conan-io/hooks/issues/376

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]
1. I hope no sane person uses zlib 1.2.8 in 2022
2. zlib is kinda foundational and vital (it's a dependency of almost everything) and we know it's sensitive for the name of the library produced (where it could be libz / libzlib / libzlibstatic / libzlibstaticd and o on). I'll try to check some additional configurations beside s that CCI provides (iOS/Android/MSYS/Cygwin/clang-cl etc)

**Review by prince-chrismc — APPROVED** [review]

**Comment by Samulus** [comment]
This just broke ZLIB for me (on CentOS7):
```
[cmake] ERROR: zlib/1.2.11: Error in build() method, line 77
[cmake] 	self._patch_sources()
[cmake] while calling '_patch_sources', line 56
[cmake] 	tools.patch(**patch)
[cmake] 	FileNotFoundError: [Errno 2] No such file or directory: 'patches/0003-cmake-fix-msys2-subsystem.patch'
[cmake] CMake Error at cmake/Conan.cmake:638 (message):
[cmake]   Conan install failed='1'
[cmake] Call Stack (most recent call first):
[cmake]   cmake/AddConanDependencies.cmake:132 (conan_cmake_install)
[cmake]   CMakeLists.txt:20 (include)
```

Regression or PEBKAC?

**Comment by SpaceIm** [comment]
The issue is that your cache is corrupted. Remove zlib from your cache and install again, it should work.

**Comment by Samulus** [comment]
> The issue is that your conan cache is corrupted (it seems that `conandata.yml` in `export` folder of `zlib` recipe in conan cache has not been updated on your machine, either a conan client issue or PEBKAC as you said). Remove zlib from your cache and install again, it should work.

Weird. I tried that multiple times (`rm -rf ~/.conan/data/zlib`) and it didn't work but now it does :shrug: thanks.

**Pull request merged**
