### PR TITLE
add qt5 network module test

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **qt/5.15.2**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
this PR should demonstrate the problem from
https://github.com/conan-io/conan-center-index/issues/6071

**Comment by ericLemanissier** [comment]
This failure is actually different from the one you are trying to demonstrate, but it should be solved with https://github.com/AndreyMlashkin/conan-center-index/pull/3

**Comment by AndreyMlashkin** [comment]
@ericLemanissier, your PR is only for Windows, but the problem is also happening on Mac:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
*:fPIC=True
*:shared=False
[build_requires]
[env]

build log is in attachment
[build_log.txt](https://github.com/conan-io/conan-center-index/files/6725678/build_log.txt)

**Comment by ericLemanissier** [comment]
This error should be solved with https://github.com/AndreyMlashkin/conan-center-index/pull/4/

**Comment by AndreyMlashkin** [comment]
@jgsogo could you please also re-trigger this one?

**Comment by AndreyMlashkin** [comment]
@jgsogo is it a CI failure?

**Comment by AndreyMlashkin** [comment]
Closing a MR does not retrigger the build anymore?

**Comment by jgsogo** [comment]
Looks like it is a side effect of one configuration I've modified on our Jenkins 🤔  

I want to run _branch indexing_ from time to time, so closed/merged PRs are discovered are their branches are removed (otherwise we would run out of space in our agents)... but every time branch-indexing runs it triggers _all_ the PRs again if something has been modified in `master` (we merge PRs everyday, so we they will be triggered always). 

Jenkins has a configuration to not trigger these PRs again, but then it stops listening to other events like the close/open one. TBH, it is an event I really don't like, some people abuse it, but OTH it is very useful for contributors to trigger the pipeline again (we cannot monitor all the jobs all the time).

We could activate it again (and find a workaround for the branch-indexing), or we can find a workaround for this open/close _feature_. Please, @danimtb @SSE4 @uilianries , ideas? arguments? suggestions?

**Comment by AndreyMlashkin** [comment]
Could you re-trigger this job please?

**Comment by AndreyMlashkin** [comment]
Is the CI fix on the way?

**Comment by jgsogo** [comment]
We are recovering... sorry for the delay, but it's been a nightmare, there were too many PRs for Qt, and that library is a beast. It drains all the resources.

**Comment by jgsogo** [comment]
This is a bug on our side. IT should be fixed by https://github.com/conan-io/conan/pull/8532 and https://github.com/conan-io/conan/pull/9022 (Conan v1.37) but we are not using that version yet in the CI.

Meanwhile, it requires some precision surgery in the CI machines. If manage to reduce the load of the CI I will enter the machine and remove the offending file

**Comment by AndreyMlashkin** [comment]
So, restarting the build will not help, right?

**Comment by jgsogo** [comment]
> So, restarting the build will not help, right?

Yes, it does... if it uses a different machine, or if after the next failure it is able to clean the existing workspace and start from scratch. 

Windows machines are really problematic with these filesystem issues... they take so long to remove the workspaces that sometimes the job fails with a timeout. We would love to hear about alternatives:
 * how to make Windows remove files faster
 * we have read about docker containers with Windows, anyone has tried them? any feedback?

**Comment by AndreyMlashkin** [comment]
We are using windows docker containers for our company CI. But we don't use jenkins, but gitlab-ci.
Windows containers are heavy, but it does not matter, if you run it on a local runner and not in a cloud.
The only problem is compatibility: host machine version should match to the base docker image version.

**Comment by jgsogo** [comment]
We definitively need to try them. Start container, 100% sure that everything is clean, run the build, forget about cleaning the workspace... that will prevent some weird errors 😃

**Comment by jgsogo** [comment]
It's been the PREV-null error again 😢 

We did one change to the CI that I'm regretting now: we are running `test_package` for all the packageID, also for those that are already available. The reason is that a PR can modify the tests without modifying the recipe, and we want to know that the package works with the new tests. This is adding extra load to the CI because, even if the package is available, it will trigger the build for the `test_package` (resources, time,... and errors).

Let's see if we can upgrade Conan to 1.37 and https://github.com/conan-io/conan/pull/8532 helps with this (ping @danimtb )

**Comment by ericLemanissier** [comment]
@AndreyMlashkin please consider merging https://github.com/AndreyMlashkin/conan-center-index/pull/5, so that we avoid overloading CCI with another PR on qt

**Comment by ericLemanissier** [comment]
> * how to make Windows remove files faster

@jgsogo A fast way is to do the [two step](https://stackoverflow.com/questions/186737/whats-the-fastest-way-to-delete-a-large-folder-in-windows/6208144#6208144)
```
del /f/s/q foldername > nul
rmdir /s/q foldername
```
Maybe it's faster that what is performed currently in C3I ?

**Comment by AndreyMlashkin** [comment]
Retrigger mb?

**Comment by AndreyMlashkin** [comment]
@jgsogo is there some pattern in the fails?
Does it always happen on different runners?

**Review by ericLemanissier — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
