### PR TITLE
freetype: fix pkg_config file name

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Morwenn** [comment]
The CMake `find_package` name seems to be `Freetype` (with a capital letter), maybe it would be worth adding too.

**Comment by ericLemanissier** [comment]
would that be `self.cpp_info.name`, `cpp_info.names["cmake_find_package"]` or something else?

**Comment by Morwenn** [comment]
I might be wrong but I think that `cpp_info.names["cmake"]` handles all the standard CMake generators. I'm not sure what the policy is wrt to `cpp_info.name` vs. `cpp_info.names` now that we have both. We'll need more information on both points.

**Comment by ericLemanissier** [comment]
As far as I know, `cpp_info.name` is the fallback when no `cpp_info.names[generator]` is defined. So the effect of https://github.com/conan-io/conan-center-index/pull/443/commits/0f050dee342256b2b6ed3a9961114bb69242870a is to use `Freetype` for all generators other than pkg_config, which means cmake_multi, cmake_find_package, cmake_find_package_multi and cmake_paths

**Comment by SSE4** [comment]
studying the code (https://github.com/conan-io/conan/pull/6033/files#diff-90fdfacb06440bf1843cae8764f52de8R51), it's `cpp_info.names["cmake_find_package"]`, and `cmake` affect only the **cmake** generator (not other cmake-based generators).

**Comment by ericLemanissier** [comment]
@danimtb what do you think?

**Pull request merged**
