### PR TITLE
re2: modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by toge — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
CCI died :) all the linux agents are off apparently 🤷

**Comment by prince-chrismc** [comment]
This is not on https://github.com/prince-chrismc/conan-center-index-pending-review/issues/1 either 🤔

**Comment by prince-chrismc** [comment]
it's still working :/ 
image

**Comment by prince-chrismc** [comment]
:( it's looking for build agents

**Pull request merged**
