### PR TITLE
cmake: add version 3.31.0

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **cmake/3.31.0**

#### Motivation
There are lots of new features in 3.31.0.
https://github.com/Kitware/CMake/compare/v3.30.5...v3.31.0

#### Details
https://cmake.org/cmake/help/latest/release/3.31.html

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by jcar87 — CHANGES_REQUESTED** [review]
please retain the 3.x.x folder and do not make any formatting modifications to the recipe (this is in general, for all PRs). In this case doing so would result in unnecessarily generating binaries for all versions, when nothing has affectively changed.

Thank you!

**Comment by toge** [comment]
@jcar87 
Is 3.x.x still using?
I can't find the way to use it.

**Comment by jcar87** [comment]
3.x.x was left for users of Conan Center Index that do not rely on the remote, and would like to manually export the recipe and build binaries from it - perhaps from a local fork, or for a repository they control - so the recipe is still maintained (albeit only on contributors help alone) even if it not checked by CI.

A comment may be handy - but at the same time, and we continue to ask all contributors - please refrain from doing maintenance on top of other changes. If the goal of the PR is to add version 3.31.0 - that's a single, straight forward change in only two files - same goes for removing the test_v1_package, refrain from doing this as well - we will take care of it (perhaps in a single commit down the line). By all means it's not harmful, but the quickest way to get a review from us is by sticking to the goal of the PR.

**Comment by toge** [comment]
@jcar87 
Now I understand.
I will try to revert delete test_v1_package.

One more question.
Should I separate PRs add new version and removing older versions?

**Review by jcar87 — APPROVED** [review]
Verified checksums against: https://github.com/Kitware/CMake/releases/download/v3.31.0/cmake-3.31.0-SHA-256.txt

**Review by uilianries — APPROVED** [review]

**Pull request merged**
