### PR TITLE
icu/73.2 recipe, #20760 dat_package_file option fixed.

### LINKED ISSUE #20760: [package] icu/73.2: Cannot create package with dat_package_file option.
### Description

Cannot create icu/73.2 package with dat_package_file option:
`conan create . icu/73.2@ --profile:host=default --profile:build=default -o icu:shared=True -o icu:with_extras=True -o icu:dat_package_file=c:\TEMP\icudt73l.dat` fails:
ERROR: icu/73.2: Error in validate() method, line 75
        if not os.path.exists(self.options.dat_package_file):
        TypeError: stat: path should be string, bytes, os.PathLike or integer, not PackageOption

It looks like the `str()` function call is missing around the `self.options.dat_package_file`:
`if not os.path.exists(str(self.options.dat_package_file)):`

### Package and Environment Details

* Package Name/Version: **icu/73.2**
* Operating System+version: **Windows 22H2/Gentoo Base System release 2.9**
* Compiler+version: **MSVC 14.16.27023/GCC 11.3.0**
* Conan version: **conan 1.61.0/1.59.0**
* Python version: **Python 3.12.0/3.10.8**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan create . icu/73.2@ --profile:host=default --profile:build=default -o icu:shared=True -o icu:with_extras=True -o icu:dat_package_file=c:\TEMP\icudt73l.dat

### Logs

<details><summary>Click to expand log</summary>

```
Exporting package recipe
icu/73.2 exports: File 'conandata.yml' found. Exporting it...
icu/73.2 exports: Copied 1 '.yml' file: conandata.yml
icu/73.2: Calling export_sources()
icu/73.2: The stored package has not changed
icu/73.2: Using the exported files summary hash as the recipe revision: 0fa00563e51de2fe5c1a9f31df1258ed
icu/73.2: Exported revision: 0fa00563e51de2fe5c1a9f31df1258ed
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
icu:dat_package_file=c:\TEMP\icudt73l.dat
icu:shared=True
icu:with_extras=True
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: icu/73.2: Error in validate() method, line 75
        if not os.path.exists(self.options.dat_package_file):
        TypeError: stat: path should be string, bytes, os.PathLike or integer, not PackageOption
```

</details>

### PR DESCRIPTION
**Pull request by hegyizs**
Fixed conversion from PackageOption to os.path in validate() function.

Specify library name and version:  **icu/73.2**

fixes #20760

### CODE REVIEW

**Comment by SpaceIm** [comment]
Please mention which recipe is fixed in PR title, there are ~1600 recipes in conancenter.

**Comment by hegyizs** [comment]
> Please mention which recipe is fixed in PR title, there are ~1600 recipes in conancenter.

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by hegyizs** [comment]
@jwillikers Could you please approve the "2 workflows awaiting approval", because without approval they don't seem to start.

**Comment by jwillikers** [comment]
> @jwillikers Could you please approve the "2 workflows awaiting approval", because without approval they don't seem to start.

That's not usually the case, though GitHub is having outages right now, so that may be impacting things.

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
> @jwillikers Could you please approve the "2 workflows awaiting approval", because without approval they don't seem to start.

@hegyizs Thank you for your PR! Only administrators can approve that. Sorry about the case, it's a not desired behavior, but is default by Github. Please, ping `@conan-io/barbarians` in case you have similar blocker in the future, only people from that group have permission over Github actions.

**Comment by hegyizs** [comment]
@uilianries Could you help me with how this PR can move forward?

**Comment by uilianries** [comment]
@hegyizs For some reason, the CI refused to run your PR. I started it again, it should be finished in few hours.

**Comment by hegyizs** [comment]
@SpaceIm Could you please approve this PR?

**Comment by SpaceIm** [comment]
There are already 2 approvals, it's sufficient for merge bot, and it will be merged once CI tests completed.

**Comment by hegyizs** [comment]
@SpaceIm The CI tests seems to be completed but I still get: 
```
Review required
At least 2 approving reviews are required by reviewers with write access. 
```
```
Merging is blocked
Merging can be performed automatically with 2 approving reviews.
```

**Pull request merged**
