### PR TITLE
libassert: Add version 2.0.1

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Specify library name and version:  **libassert/2.0.1**

I'm the author. Depends on #23286.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Thanks for merging #23286, I've merged the changes from there into here

**Comment by jeremy-rifkin** [comment]
I'm unfortunately confused why CI says there's a merge conflict. `git merge --no-ff 6ca6e35` says "Already up to date." locally.

**Comment by uilianries** [comment]
@jeremy-rifkin Sorry the internal error. I just re-triggered the CI right now.

**Review by RubenRBS — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Review by ericLemanissier — CHANGES_REQUESTED** [review]
the source of the patch does not match the content.
also, if you're the author of the library, why don't you simply release a fixed version and package the new version in conan ?

**Comment by ericLemanissier** [comment]
@jeremy-rifkin could you please explain why the patch file https://github.com/conan-io/conan-center-index/pull/23351/files#diff-d62d0a8180052ae246d7e69116b8e67f52e66dab371b74c91fe80049ef991fe7 does not have the same content as the source indicated in conandata.yml

**Comment by jeremy-rifkin** [comment]
Hi @ericLemanissier, sorry for the confusion. I should have updated the patch source to read “https://github.com/jeremy-rifkin/libassert/commit/1825976ebc7ccb34687d75aaaaf2a961dafc5450 and https://github.com/jeremy-rifkin/libassert/commit/d3fb654061d1ed01577799aa57a7bb2eb0915bae”

These patches are in the upstream and will be part of the next release, however I’d made the v2.0.1 tag before running into this issue on conan’s CI. I’ve tried to avoid moving tags once creating them.

**Pull request merged**
