### PR TITLE
json_struct receipt

### PR DESCRIPTION
**Pull request by jorgen**
### Summary
Add recipe:  **json_struct/1.0.1**

#### Motivation
Adding the json_struct header only library

#### Details
json_struct is a single header only library that parses JSON to C++ structs/classes and serializing structs/classes to JSON.

---
- [x ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x ] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by AbrilRBS** [comment]
Hi @jorgen thanks a lot for taking the time to add the recipe. There are some easy changes to make it more compliant with CCI policies, could you check the package template in https://github.com/conan-io/conan-center-index/blob/master/docs/package_templates/header_only/all/conanfile.py and follow it? It would help tremendously, thanks! :)

**Comment by jorgen** [comment]
Ok, I have trimmed it down. How does it look?

**Comment by AbrilRBS** [comment]
Hi @jorgen sorry for the delay on getting this reviewed, we were focused on launching the new CI system so some PRs got delayed - hopefuly the new experience is worth it. I've now pushed some last cleanups, and other once it compiles I'll push to get this merged. 

Thanks again for taking the time to add this to CCI, we appreciate it

(For future traceability: 1.0.2 seems to have been tagged but not released, but I'm approving as-is, the diff is only for the cmake min version)

**Review by AbrilRBS — APPROVED** [review]

**Review by perseoGI — APPROVED** [review]
LGTM

**Comment by jorgen** [comment]
@AbrilRBS thank you!

**Pull request merged**
