### PR TITLE
added recipe for openslide 3.4.1 #16340

### PR DESCRIPTION
**Pull request by boussaffawalid**
**openslide/3.4.1**

Added conan recipe for openslide 3.4.1

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by boussaffawalid** [comment]
dependency conflict, gdk-pixbuf from conan center is outdated, will get back to this after https://github.com/conan-io/conan-center-index/pull/19557/files

**Comment by RubenRBS** [comment]
It's been merged now, retriggering :)

**Comment by bgilbert** [comment]
See also https://github.com/conan-io/conan-center-index/pull/21138 by @valgur for OpenSlide 4.0.0.

Note that OpenSlide upstream doesn't support MSVC and we don't have plans to do so.  In 4.0.0 and above, this will be much harder to patch around, since OpenSlide now makes pervasive use of the `cleanup` attribute from GNU C.

**Comment by bgilbert** [comment]
Please use OpenSlide 4.0.0 (#21138) instead of 3.4.1.  OpenSlide 3.4.1 is nine and a half years old and is not maintained.

**Comment by AbrilRBS** [comment]
Closing in favour of https://github.com/conan-io/conan-center-index/pull/21138

**Pull request closed without merging**
