### PR TITLE
mysql-connector-c: Update OpenSSL to latest patch level

### PR DESCRIPTION
**Pull request by Croydon**
- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

_____________________

While still being a useful change, this is mostly a test for more (half-)automation of e.g. OpenSSL updates 😄

### CODE REVIEW

**Comment by madebr** [comment]
Why isn't the openssl version bumped to 1.1.1d?

**Comment by uilianries** [comment]
> Why isn't the openssl version bumped to 1.1.1d?

Does is 1.1.1@ compatible?

**Comment by Croydon** [comment]
> Why isn't the openssl version bumped to 1.1.1d?

If the question is why the bot isn't doing it than the answer is because it would break stuff way too often.

And in this specific case, if I recall correctly mysql-connector-c isn't compatible with OpenSSL 1.1.1. I believe @ericLemanissier did try that in the past

**Comment by ericLemanissier** [comment]
Yes. mysql-connector-c (the upstream project, not the recipe) is not maintained any more. It's recommended to migrate to https://conan.io/center/libmysqlclient/8.0.17

**Pull request merged**
