### PR TITLE
tree-sitter-sql: add version 0.3.7

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **tree-sitter-sql/0.3.7**

#### Motivation
There are several improvements in 0.3.7.

#### Details
https://github.com/DerekStride/tree-sitter-sql/releases/tag/v0.3.7
https://github.com/DerekStride/tree-sitter-sql/compare/v0.3.5...v0.3.7

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by perseoGI — COMMENTED** [review]
Hi @toge, take a look at the new upstream CMakeLists.txt 
https://github.com/DerekStride/tree-sitter-sql/blob/v0.3.7/CMakeLists.txt

Maybe we can consider using upstreams one (with maybe a proper fix) instead of having our own(?)

**Comment by toge** [comment]
@perseoGI 
Oh I missed it.
Let me fix this PR.

**Comment by toge** [comment]
@perseoGI 
CMakeLists.txt was not present in the snapshot corresponding to 0.3.7 of gh-pages.
sources:

As per the official README, the release tarballs don't include the generated codes.
> We don't commit the generated parser files to the main branch. Instead, you can find them on the gh-pages branch.

I will ask about it in upstream, but at this point it looks like we will have to use CMakeLists.txt from CCI.

**Comment by perseoGI** [comment]
@toge thank you very much for reporting upstream, we may wait a little bit to see if they can republish the version!

**Comment by toge** [comment]
@perseoGI 
Now CMakeLists.txt has been added to gh-pages branch.
Please review it again.

**Review by AbrilRBS — APPROVED** [review]
Great to see, thanks!

**Review by perseoGI — APPROVED** [review]
Great! Thank you @toge for taking the time to convince upstream! 🐸

**Pull request merged**
