### PR TITLE
sentry-crashpad: more fixes for v2

### PR DESCRIPTION
**Pull request by prince-chrismc**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by MartinDelille — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/pull/16751 was merged lets kick a new build 🤞

**Comment by paulharris** [comment]
Hey I have a few questions re crashpad (I'm new to it) ...

There is another recipe (called "crashpad"), which seems to package the same library, but from a different source.
This one seems to build the crashpad bundled by sentry, right?
Is the other recipe still valid/required?  Because it needs some v2 love if it is to continue to live.

Second, when deploying your crashpad-enabled program, I believe you are supposed to deploy the built crashpad_handler.exe (or binary) from the package/bin folder.
And, even when not deploying, you are supposed to init the crashpad library by telling it where the crashpad handler program lives.

How is the location of the binary folder (and filename) supposed to be given to the consumers of this library?
How can I find the binary file when it is time to deploy the handler?

At the moment, I have in my consumer cmake file:

```
if (DEFINED sentry-crashpad_PACKAGE_FOLDER_RELEASE)
   set (CRASHPAD_PACKAGE_FOLDER "${sentry-crashpad_PACKAGE_FOLDER_RELEASE}")
elseif (DEFINED sentry-crashpad_PACKAGE_FOLDER_RELWITHDEBINFO)
   set (CRASHPAD_PACKAGE_FOLDER "${sentry-crashpad_PACKAGE_FOLDER_RELWITHDEBINFO}")
elseif (DEFINED sentry-crashpad_PACKAGE_FOLDER_DEBUG)
   set (CRASHPAD_PACKAGE_FOLDER "${sentry-crashpad_PACKAGE_FOLDER_DEBUG}")
else ()
   message (FATAL_ERROR "Could not find ${CRASHPAD_EXE}")
endif()

file (COPY "${CRASHPAD_PACKAGE_FOLDER}/bin/${CRASHPAD_EXE}" DESTINATION "bin/")
install (FILES "${CMAKE_BINARY_DIR}/bin/${CRASHPAD_EXE}" DESTINATION "bin")
```

There didn't seem to be any other way ...

**Comment by MartinDelille** [comment]
Hi @paulharris !

I posted here to know what are the benefit of using crashpad fork from sentry: https://github.com/getsentry/sentry-native/discussions/798

I don't remember what was the motivation to be able to link the original crashpad library.

**Comment by MartinDelille** [comment]
Regarding the missing dependencies, I have the same issue here: https://github.com/conan-io/conan-center-index/pull/17369

How can this be solved ?

**Review by MartinDelille — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]
Is this PR still valuable ?

**Review by SSE4 — APPROVED** [review]

**Pull request closed without merging**
