### PR TITLE
[hotfix] Fix CCI removing CRLF

### PR DESCRIPTION
**Pull request by uilianries**
I just changed from CRLF to LF.

Why? CRLF causes an error on CCI where those files are automatically converted to LF during CI execution, resulting in new PRs errors.

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Review by wolfee001 — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
I shocked this happened...


https://github.com/conan-io/conan-center-index/blob/0234ee178489ae5c1c60ac1a169005e1bd6f5415/.editorconfig#L5

https://github.com/conan-io/conan-center-index/blob/0234ee178489ae5c1c60ac1a169005e1bd6f5415/.gitattributes#L8

**Review by SpaceIm — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Comment by jgsogo** [comment]
As @prince-chrismc is pointing out, this shouldn't have happened...

**Comment by jgsogo** [comment]
...but this is really, really weird. Last three PRs merged have failed because of this (one example):

```
+ git diff --name-only f08a684a8a3231e753bfcea580a33205c1828767 --diff-filter=AMR
warning: CRLF will be replaced by LF in recipes/platform.interfaces/all/conandata.yml.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in recipes/platform.interfaces/all/conanfile.py.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in recipes/platform.interfaces/config.yml.
The file will have its original line endings in your working directory
[Pipeline] echo
Changed files: [recipes/libde265/all/conanfile.py, recipes/platform.interfaces/all/conandata.yml, recipes/platform.interfaces/all/conanfile.py, recipes/platform.interfaces/config.yml]
```

but then, when the bot retries the failure in `master`:

```
+ git diff --name-only f08a684a8a3231e753bfcea580a33205c1828767 --diff-filter=AMR
[Pipeline] echo
Changed files: [recipes/libde265/all/conanfile.py]
```

Same commit in the diff... although there is a slight difference when Jenkins checkouts the sources. In the build that fails, it runs `git rev-list --no-walk f08a684a8a3231e753bfcea580a33205c1828767 # timeout=10`.

---

Good news: at least the system is able to recover automatically and we are not loosing packaging. Bad news, `.gitattributes` not working as expected?

**Comment by madebr** [comment]
Are the rules in `.gitattributes` applied client side?
So a bad behaving client can mess everything up.

Is it possible to create a bad commit with a modified `.gitattributes` file without committing the attributes file?

**Comment by jgsogo** [comment]
This is what I'm thinking. The CI cannot modify the files (locally) because it would create a different recipe-revision from the one pushed to the repository, and we don't want the CI pushing changes to user branches, but the CI should raise an error for files that don't satisfy `.gitattributes`... and prevent the PR from merging.

**Comment by ericLemanissier** [comment]
Maybe a hook could do the job?

**Comment by jgsogo** [comment]
Hook at least: https://github.com/conan-io/hooks/issues/313, but I want this on the CI side as well, it is about the integrity of the repository.

**Comment by alejandro-colomar** [comment]
Related (I think we opened the issue at the same time, because before opening, I couldn't find anything with CRLF):

https://github.com/conan-io/conan-center-index/issues/6057

**Comment by prince-chrismc** [comment]
> but I want this on the CI side as well, it is about the integrity of the repository

Hooks are the easiest way... Required action to prevent merging? Seems uncommon... I only found 1 that exists for this https://github.com/marketplace/actions/check-eol

**Comment by jgsogo** [comment]
Hooks ✅ , but the same way we are checking that several directories are being modified on PRs, we can check if those files satisfy `.gitattributes`. If they don't, the CI can fail and report a _nice_ message to the PR author.

Why not only hooks? Because it is our Jenkins library the one that has problems with this issue. This is not a problem because of a convention (new lines at end of file, not package `.cmake` files, manage `fPIC`,...), this is a problem that breaks the way the library works. The things that hooks are checking don't break the library, they are just _enforced recommendations_ for contributions, we could think about other instance of `conan-center-index` with different conventions but this CRLF thing (validate `.gitattributes`) should be enforced always.

**Pull request merged**
