### PR TITLE
bump dependency of libpq

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **libpq/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
@jgsogo what is going on with the CI? Why so many failed builds?

**Comment by uilianries** [comment]
@AndreyMlashkin please, be patient. We usually restart failed jobs too. It can be many things, out of memory, networking ...

**Comment by AndreyMlashkin** [comment]
> @AndreyMlashkin please, be patient. We usually restart failed jobs too. It can be many things, out of memory, networking ...

three builds later it is still failing

**Comment by jgsogo** [comment]
There are more `Unexpected Errors` that we would like to, and the probability increases with the number of versions. I'm still waiting for an _imgui_ job to finish successfully. We also removed a retry some weeks ago that was running 3 times any failing build (whether it was a legit failure or not), that retry could be alleviating some of these _unexpected failures_.

Now I think it is the time to add the retry again, but only for `Unexpected failures` and in a better place given the current workflows of the CI. Adding that to the backlog, next week I´ll share it with the team and define what exactly can be implemented.

**Review by jgsogo — APPROVED** [review]

**Pull request merged**
