### PR TITLE
[cgal] add cgal/5.6

### PR DESCRIPTION
**Pull request by lrineau**
Specify library name and version:  **cgal/5.6**

Update to latest CGAL upstream release: https://github.com/CGAL/cgal/releases/tag/v5.6

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Regenerating the missing binaries :)

**Comment by lrineau** [comment]
The error is:
```
======== Installing packages ========
ERROR: Missing binary: mpfr/4.1.0:c16aea0f6d35a4856182c8d8c4dedcf2dad52637

mpfr/4.1.0: WARN: Can't find a 'mpfr/4.1.0' package binary 'c16aea0f6d35a4856182c8d8c4dedcf2dad52637' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.version=13
os=Macos
[options]
exact_int=gmp
fPIC=True
shared=False
[requires]
gmp/6.2.Z
```

That is exactly the same error as for cgal/5.5.2 (https://github.com/conan-io/conan-center-index/pull/17858#issuecomment-1584816850). @uilianries, in June you solve that issue by triggering a CI build (https://github.com/conan-io/conan-center-index/pull/17858#issuecomment-1587036461). Strange that the exact same build (with the same profile) no longer exists now. Can you please trigger a rebuild?

**Comment by lrineau** [comment]
Still the same issue:
```
======== Installing packages ========
ERROR: Missing binary: mpfr/4.1.0:c16aea0f6d35a4856182c8d8c4dedcf2dad52637

mpfr/4.1.0: WARN: Can't find a 'mpfr/4.1.0' package binary 'c16aea0f6d35a4856182c8d8c4dedcf2dad52637' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.version=13
os=Macos
[options]
exact_int=gmp
fPIC=True
shared=False
[requires]
gmp/6.2.Z

ERROR: Missing prebuilt package for 'mpfr/4.1.0'
```
Full log: https://c3i.jfrog.io/c3i/misc-v2/logs/pr/19124/3-macos-clang/cgal/5.6//da39a3ee5e6b4b0d3255bfef95601890afd80709-test.txt

**Comment by uilianries** [comment]
Just started a new CI build to generate `mpfr`. The build log should be available at https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/prod-v2/TapaholesRepo/52/summary.json as soon as it finishes.

**Comment by lrineau** [comment]
> Just started a new CI build to generate `mpfr`. The build log should be available at [c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/prod-v2/TapaholesRepo/52/summary.json](https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/prod-v2/TapaholesRepo/52/summary.json) as soon as it finishes.

Unfortunately, that build of `mpfr` failed, for a reason I cannot understand. Should I report an issue on `mpfr`?

**Comment by uilianries** [comment]
> Unfortunately, that build of `mpfr` failed, for a reason I cannot understand. Should I report an issue on `mpfr`?

No. It requires extra investigation why didn't pass. Opening an issue needs more concrete information always. I'll try to take a look on it.

**Comment by uilianries** [comment]
I just add a new PR fixing the situation with mpfr: https://github.com/conan-io/conan-center-index/pull/19150

**Comment by lrineau** [comment]
> I just add a new PR fixing the situation with mpfr: #19150

Thanks. That solved the issue indeed. The last build of cgal/5.6 is fine in the CI now.

**Pull request merged**
