### PR TITLE
Update abseil:20200901

### PR DESCRIPTION
**Pull request by mathbunnyru**
Specify library name and version:  ** abseil:20200901**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
I would be honestly surprised if abseil would not break the universe with every single update. Good luck!

**Comment by uilianries** [comment]
> I would be honestly surprised if abseil would not break the universe with every single update. Good luck!



@mathbunnyru Indeed Abseil is unstable, but because they follow bleeding edge, but they have kind of official releases. The last release was in February: https://github.com/abseil/abseil-cpp/tags

**Comment by SpaceIm** [comment]
I'm working on adding components to abseil. Current recipe for `20200225.2` is broken (2 libs are missing, not even sure that libs order is correct).
abseil has ~120 CMake imported targets, for ~50 static libs.
In each release, some targets are removed, some are added, internal interdependencies change. It requires a specific file in the recipe for each version, tracking all these targets and interdependencies, to feed `cpp_info`.

Not sure that adding a new "cci version" is a good idea (like the first one in CCI: `20200205`), why not waiting an official release?

**Comment by mathbunnyru** [comment]
@SpaceIm I'm gradually start using conan for almost all our external dependencies.
And we can't build our source with the existing abseil version.

I will investigate carefully why.

**Comment by mathbunnyru** [comment]
lts_2020_09_23 was released (https://github.com/abseil/abseil-cpp/branches), closing this PR for now.

**Pull request closed without merging**
