### PR TITLE
libusb: Use systemd/system

### PR DESCRIPTION
**Pull request by Croydon**
Specify library name and version:  **libusb/1.0.23**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.
_____________

- [ ] Depends on #2468
- [ ] Blocks https://github.com/conan-io/hooks/pull/158

### CODE REVIEW

**Comment by madebr** [comment]
@Croydon 
I think this can be closed as we have a libusb/1.0.23 recipe

**Comment by Croydon** [comment]
@madebr This pr is about getting rid of the direct system requirements in the libusb recipe it still has

We need libudev in some Conan system package as it is part of systemd, but we don't have one yet

**Comment by madebr** [comment]
Apologies. My brain shortcut after reading usb.

**Comment by prince-chrismc** [comment]
There appears to be a `libusb` merged #4067

Can this be closed?

**Comment by Croydon** [comment]
No, this is not about adding libusb, this is about changing from a direct system dependencies on a system package, which did not make it yet over the finish line.

**Comment by valgur** [comment]
@RubenRBS @uilianries This one can probably be closed: https://github.com/conan-io/conan-center-index/blob/e57f6851551dc3ab4e076a02225d912d76e91947/recipes/libusb/all/conanfile.py#L67-L70

The PR is also permanently stuck in a "pending" state: https://github.com/conan-io/conan-center-index/pulls?q=is%3Apr+status%3Apending+is%3Aopen+sort%3Aupdated-asc

**Comment by jcar87** [comment]
Closing this as stale - @Croydon  please let us know if this is still needed or if this is blocking anything else, and we can reopen it, thanks!

**Pull request closed without merging**
