### PR TITLE
coz: Causal profiler

### PR DESCRIPTION
**Pull request by klimkin**
**coz/0.2.2** 

Requires **libelfin/0.3** https://github.com/conan-io/conan-center-index/pull/3283

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@klimkin Please, separate libelfin from this PR.

**Comment by klimkin** [comment]
> @klimkin Please, separate libelfin from this PR.

@uilianries Please see https://github.com/conan-io/conan-center-index/pull/3283

**Comment by uilianries** [comment]
@klimkin This PR still contains 2 different packages. CCI does allow it, please, remove one of these packages.

**Comment by klimkin** [comment]
> @klimkin This PR still contains 2 different packages. CCI does allow it, please, remove one of these packages.

@uilianries `coz` requires `libelfin` which is submitted as a separate PR. This PR is rebased on https://github.com/conan-io/conan-center-index/pull/3283. It won't build is `libelfin` is not available.

**Comment by klimkin** [comment]
@emeryberger I noticed coz mentions `coz-profiler` as the package name, but the repo name is `coz`. Which name for the package would you prefer?

**Comment by emeryberger** [comment]
Hi - I'd prefer `coz` if that's possible!

**Comment by klimkin** [comment]
Will resubmit once https://github.com/conan-io/conan-center-index/pull/3283 is merged.

**Comment by emeryberger** [comment]
Noticed that https://github.com/conan-io/conan-center-index/pull/3283 was merged, FWIW.

**Comment by klimkin** [comment]
@emeryberger See re-opened https://github.com/conan-io/conan-center-index/pull/3794. This is now waiting for merging CMake build for coz, since it will simplify the recipe: https://github.com/plasma-umass/coz/pull/178

**Pull request closed without merging**
