### PR TITLE
opencolorio: add version 2.2.1, support conan v2, support C++20 in 2.1.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **opencolorio/***

- add version 2.2.1
- support conan v2
- update dependencies
- fix C++20 compilation errors in 2.1.0
- add version prefix to patch files

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
```
----Running------
> cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/J/w/prod/BuildSingleReference@3/.conan/data/opencolorio/1.1.1/_/_/build/2f46b90c7e26a2b2de42fe1aac9c1a770c9e3286/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/J/w/prod/BuildSingleReference@3/.conan/data/opencolorio/1.1.1/_/_/package/2f46b90c7e26a2b2de42fe1aac9c1a770c9e3286" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\J\w\prod\BuildSingleReference@3\.conan\data\opencolorio\1.1.1\_\_\build\2f46b90c7e26a2b2de42fe1aac9c1a770c9e3286\src"
-----------------
-- Using Conan toolchain: C:/J/w/prod/BuildSingleReference@3/.conan/data/opencolorio/1.1.1/_/_/build/2f46b90c7e26a2b2de42fe1aac9c1a770c9e3286/build/generators/conan_toolchain.cmake
-- Configuring incomplete, errors occurred!
opencolorio/1.1.1: 
CMake Error at C:/J/w/prod/BuildSingleReference@3/.conan/data/opencolorio/1.1.1/_/_/build/2f46b90c7e26a2b2de42fe1aac9c1a770c9e3286/build/generators/conan_toolchain.cmake:29 (message):
  The CMake policy CMP0091 must be NEW, but is ''
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:1 (project)
```

Oh, no.
Why CMP0091 is ``?

**Comment by toge** [comment]
@uilianries 
Could I get one more help?
I am having trouble with CMake's CMP0091 in Visual Studio.
Is there any way to check if this is a problem with my recipe or with the CI environment?

**Comment by prince-chrismc** [comment]
@danimtb @uilianries This Jenkins job is doing the wrong thing 😱 

image

**Comment by prince-chrismc** [comment]
@toge I would suggest making a new PR, the backend really is not doing the right thing anymore

**Comment by toge** [comment]
@prince-chrismc 
Thank you for your help!
I recreate PR.

**Comment by uilianries** [comment]
@prince-chrismc another I needed to remove a folder in artifactory to generate all again, but indeed opening a new PR is much safer.

**Pull request closed without merging**
