### PR TITLE
bshoshany-thread-pool: add version 3.3.0

### PR DESCRIPTION
**Pull request by bshoshany**
Specify library name and version:  **bshoshany-thread-pool/3.3.0**

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by bshoshany** [comment]
Looks like one of the checks fails due to incompatibility with Conan v2. What exactly do I need to change in the `.py` file to make it compatible? Thanks.

**Comment by uilianries** [comment]
@bshoshany on the review page https://github.com/conan-io/conan-center-index/pull/12037/linter, all linter topics are listed, and all them have a link to the documentation explaining your case.

To fix those errors, you just need to update some python imports which will be deprecated on Conan 2.0:

https://github.com/conan-io/conan-center-index/blob/master/docs/v2_linter.md#import-tools-from-conan

**Comment by bshoshany** [comment]
Okay, I tried to follow the instructions [here](https://docs.conan.io/en/latest/conan_v2.html), hopefully this works!

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
