### PR TITLE
exiv2: use official tarballs + modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
```
-------- Computing necessary packages --------
exiv2/0.27.4: Forced build from source
Requirements
    exiv2/0.27.4#a3b0b68d64e63c2d82eb44a9f1f9b89f:c54911fefb64e9505bccd4c3acaeb710a9fd9e4c - Build
    expat/2.5.0#98829cfd97ab55bceed0911eb7825a72:31111f9144d3aa915d4a59ade01b4ecf019616b7#6a39236daba8ff6a874a8986b286577a - Download (conan-center-v2)
    libiconv/1.17#fa54397801cd96911a8294bc5fc76335:d62dff20d86436b9c58ddc0162499d197be9de1e#dd9219669ba15cb67918051e371fe338 - Download (conan-center-v2)
    libpng/1.6.39#deca555b0890e584fc895ba756e83c06:bc81891445daa7010ea20451593c1e0a79a96c94 - Missing
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f:d62dff20d86436b9c58ddc0162499d197be9de1e#6b0dff5c6bb78b52fc856b16c83120b5 - Download (conan-center-v2)

-------- Installing packages --------

-------- Installing (downloading, building) binaries... --------
ERROR: Missing binary: libpng/1.6.39:bc81891445daa7010ea20451593c1e0a79a96c94

libpng/1.6.39: WARN: Can't find a 'libpng/1.6.39' package binary 'bc81891445daa7010ea20451593c1e0a79a96c94' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.version=13
os=Macos
[options]
api_prefix=
fPIC=True
shared=False
sse=True
[requires]
zlib/1.2.Z

ERROR: Missing prebuilt package for 'libpng/1.6.39'
Use 'conan list packages libpng/1.6.39 --format=html -r=remote > table.html' and open the table.html file to see available packages
Or try to build locally from sources with '--build=libpng/1.6.39'
```

@uilianries @danimtb do you know whether libpng binaries are not available in conan v2 remote because recipe is not fully conan v2 compliant or other reason?
Could it be that conan v2 doesn't like https://github.com/conan-io/conan-center-index/blob/93fe1d29af19cb9215ebd7d9796428eef5fd0db6/recipes/libpng/all/conanfile.py#L37?

**Comment by uilianries** [comment]
@SpaceIm probably a missing package, because we fixed libpng days ago. I'm running an internal CI to check it. As soon as I have the result I'll update here.

**Comment by uilianries** [comment]
@SpaceIm Indeed is a missing package, but we have libpng there:

```
"conan-center-v2": {
        "libpng/1.6.39": {
            "revisions": {
                "7927e8ce5b2576a6ea497c6ca70e9751": {
                    "timestamp": 1669038072.976
                },
                "deca555b0890e584fc895ba756e83c06": {
                    "timestamp": 1675158156.573
                }
            }
        }
    }
```

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
