### PR TITLE
fix conandata lint

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
here we go: the linter crashes with [`ModuleNotFoundError: No module named 'strictyaml'`](https://github.com/conan-io/conan-center-index/actions/runs/3534220912/jobs/5930836435#step:8:27)

**Comment by ericLemanissier** [comment]
and with the last commit, the linter error is fixed:
https://github.com/conan-io/conan-center-index/actions/runs/3534251171/jobs/5930899853#step:8:2

**Comment by ericLemanissier** [comment]
friendly ping @danimtb @uilianries @prince-chrismc 
This fixes conandata linter ([without the fix](https://github.com/conan-io/conan-center-index/actions/runs/3534220912/jobs/5930836435#step:8:27) and [with the fix](https://github.com/conan-io/conan-center-index/actions/runs/3534251171/jobs/5930899853#step:8:2))
We did not exercise this linter as part of our tests in https://github.com/conan-io/conan-center-index/pull/13748 because it is called[ after yamllint](https://github.com/conan-io/conan-center-index/blob/master/.github/workflows/linter-yaml.yml#L95). So yamllint always failed and exited early during the tests we performed, short-circuiting the run of config_yaml_linter. We should be good now

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
Lgtm

**Pull request merged**
