### PR TITLE
adding support for intel compiler

### PR DESCRIPTION
**Pull request by jakeheke75**
Specify library name and version:  **ms-gsl/4.0.0**
Hello team, adding support for Intel compiler in the package recipe. Apologize in advance for the newbie mistakes.Thanks.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
It doesn't really add support for intel-icc, because support was already there (this recipe doesn't raise when compiler is unknown).

**Comment by jakeheke75** [comment]
> It doesn't really add support for intel-icc, because support was already there (this recipe doesn't raise when compiler is unknown).

Could you please explain your point of view with a bit more details? Were you able to build successfully a Debug of the recipe with the `icpx` Intel oneAPI compiler? 🤔

**Comment by SpaceIm** [comment]
> > It doesn't really add support for intel-icc, because support was already there (this recipe doesn't raise when compiler is unknown).
> 
> Could you please explain your point of view with a bit more details? Were you able to build successfully a Debug of the recipe with the `icpx` Intel oneAPI compiler? 🤔

I don't understand. I don't have Intel compiler, but I know that if it didn't build before, it won't build after this change anyway.

**Comment by SpaceIm** [comment]
I see what's wrong in this recipe (it doesn't work with conan v2 client and unknown compilers do to usage of a remove function), here is the fix: https://github.com/conan-io/conan-center-index/pull/21264

**Pull request closed without merging**
