### PR TITLE
Update opentdf-client to 0.6.1 with new license info

### PR DESCRIPTION
**Pull request by patmantru**
Specify library name and version:  **opentdf-client/0.6.1**

Update to BSD license
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
https://github.com/opentdf/client-cpp/commit/7ed87bca4bb252f1359c4b59821de3bca060b0e5

**Comment by uilianries** [comment]
@patmantru Is 0.6.1 BSD, but 0.6.0 and older are MIT? If yes, we need to use a condition to change the license attribute, as we have multiple versions available.

**Comment by patmantru** [comment]
Hmm...good question.  I'll have to ask the legal folks here if we can continue to offer the older versions as MIT, or if they all need to be BSD, or what.

**Comment by patmantru** [comment]
I'm told that we're only to publish under BSD now, so...I removed the older versions for now.  I will investigate reinstating the older versions with BSD license text, but that involves updating all the code header comments, release tags, and sha256 values, which is more than I want to do right now.

**Review by sujankota — APPROVED** [review]

**Comment by uilianries** [comment]
@patmantru Thank you for clarifying!

**Comment by SSE4** [comment]
once, we changed license from LGPL2.1 to MPL2 in Haivision SRT repository. it required all the contributors (committers) to agree and approve.
fortunately, there weren't many at that time. but for some large projects with a long history, it might be close to impossible, as some contributor might be no longer active (or even no longer alive).

**Review by SSE4 — APPROVED** [review]

**Comment by patmantru** [comment]
That makes sense!  Thanks for pointing that out, good info to keep in mind.  Nobody outside our company has any commits in here yet, so that isn't a problem in this case.

**Review by intelligide — APPROVED** [review]

**Pull request merged**
