### PR TITLE
zlib: Add MacOS deployment target

### PR DESCRIPTION
**Pull request by talyz**
Specify library name and version:  **zlib/1.2.11**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@talyz Could you please give more details why do you need this change?Is there an error affecting you, if yes, please, provide more details.

**Comment by talyz** [comment]
@uilianries Yes, on macOS you need to specify a target version of the os that you're building for or it will build for the one you're currently building on. We target 10.9, but build on 10.13 (currently). All other libs we build correctly target 10.9, since we set the os.version attribute in the profile to 10.9.

**Comment by SSE4** [comment]
this option is vital in many cases. it's so vital that we maybe should automatically populate it in `AutoToolsBuildEnvironment`?

**Comment by talyz** [comment]
@SSE4 Yeah, that sounds like a good idea - the less corner cases you have to think about / remember when writing recipes, the better :)

**Review by jgsogo — APPROVED** [review]

**Comment by jgsogo** [comment]
> this option is vital in many cases. it's so vital that we maybe should automatically populate it in `AutoToolsBuildEnvironment`?

Please, someone should open the issue in Conan repo.

**Pull request merged**
