### PR TITLE
atk: bump dependencies and use `glib/<host_version>` in build requirements

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Could you please explaining why maintaining this deprecated recipe needed?

**Comment by SpaceIm** [comment]
It's still a dependency of gtk 3.x recipes

**Comment by ericLemanissier** [comment]
Thanks for the details. working on https://github.com/conan-io/conan-center-index/pull/20101 to enable windows build so that atk dependency can be removed from gtk3 recipes

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
I close since it's deprecated and `at-spi2-core` builds for all platforms after https://github.com/conan-io/conan-center-index/pull/20101 thanks to @ericLemanissier

**Pull request closed without merging**
