### PR TITLE
add openblas/0.3.9

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **openblas/0.3.9**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Fix:
- MSVC_STATIC_CRT always False: if True it may lie to consumer because it replaces /MD by /MT in compiler flags (which is controlled by consumer profile and injected by conan).
- ANDROID True if Android also.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@danimtb @uilianries I think this recipe is incomplete, maybe wrong or non reproductible for several platforms. It relies on CMakeLists, but CMake support in OpenBLAS is experimental and far from autoconf files. I'll try to dig into differences between CMakeLists and autoconf files.

**Comment by bmanga** [comment]
Hi @SpaceIm !
Indeed it is incomplete, as it does not expose all the options of the CMakeLists, let alone autoconf.
I implemented not the goal of expressing every possible option but based on my needs, with the idea that people with different requirements can send PRs to enhance it.
I used the cmake version because I am not familiar with autoconf and because in general it seems that cmake has become the de-facto c++ build system. If you need an option that is not covered by the CMakeLists I would suggest sending a PR to the openblas repo and add that option.
But feel free to rewrite the recipe to use autoconf if you think it's a better approach :)

**Comment by SpaceIm** [comment]
I don't understand why it fails to build on Windows, for example it says that `common.h` fails to open `common_param.h` or `common_x86_64.h`, but those file exist in the same directory and actually I don't have any error locally or here: https://ci.appveyor.com/project/SpaceIm/conan-openblas/builds/31563810/job/4mqeitmbwl4e6a7s

**Comment by bmanga** [comment]
@SpaceIm you need to teach me how to suddenly make CI pass 😂

**Comment by SpaceIm** [comment]
:muscle:

Honestly I don't understand. In my testing repo, it doesn't compile on Linux for specific gcc/clang versions: https://github.com/SpaceIm/conan-openblas/actions/runs/58553159

**Pull request merged**
