### PR TITLE
Add patch for protobuf/3.9.1

### PR DESCRIPTION
**Pull request by eirikb**
Patch adds "atomic" to protoc target_link_libraries.
This seems to help mitigate undefined reference to *atomic* when building.

Specify library name and version:  **protobuf/3.9.1**

> This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

Trying to install **protobuf/3.9.1** for armv7, and getting this error:

```
docker run --rm -it conanio/gcc9-armv7 conan install protobuf/3.9.1@

...

[100%] Linking CXX executable ../../bin/protoc
/usr/lib/gcc-cross/arm-linux-gnueabi/9/../../../../arm-linux-gnueabi/bin/ld: ../../lib/libprotobuf.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':
arena.cc:(.text+0x4e4): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [source_subfolder/cmake/CMakeFiles/protoc.dir/build.make:106: bin/protoc-3.9.1.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:201: source_subfolder/cmake/CMakeFiles/protoc.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
protobuf/3.9.1:
protobuf/3.9.1: ERROR: Package 'f08a714d553abc7915a5614d150d1c9340eefc5c' build failed
protobuf/3.9.1: WARN: Build folder /home/conan/.conan/data/protobuf/3.9.1/_/_/build/f08a714d553abc7915a5614d150d1c9340eefc5c
ERROR: protobuf/3.9.1: Error in build() method, line 178
        cmake.build()
        ConanException: Error 2 while executing cmake --build '/home/conan/.conan/data/protobuf/3.9.1/_/_/build/f08a714d553abc7915a5614d150d1c9340eefc5c/build_subfolder' '--' '-j12'
```
Full output can be found here:
https://gist.github.com/eirikb/c923df7ba7b32478360acb3d5efc1c7e

This PR fixes the issue, but: the `test_package` will fail, because it tries to build .proto-file with an ARM-based `protoc` in `x86`-system. Using the pacakge in other packages works fine (no test_package is used).

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing. 
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
You commit authorship is blocking the CLA bot https://github.com/conan-io/conan-center-index/pull/6200#issuecomment-875026995

**Comment by eirikb** [comment]
> You commit authorship is blocking the CLA bot [#6200 (comment)](https://github.com/conan-io/conan-center-index/pull/6200#issuecomment-875026995)

Sorry, how do I go about accepting the CLA? I tried this a couple of days ago as well, and when I open the link now it says
>You have agreed to the CLA for conan-io/conan-center-index

:shrug:

**Comment by prince-chrismc** [comment]
You have to click the badge... it's been awhile... but it won't work because the github account you are logged in does not use the same name and email as the information within commit you pushed

**Comment by eirikb** [comment]
@prince-chrismc I messed up bigtime, both initially and now again.
Maybe I should create a new PR, if you think the PR itself is ok?
Also, is it possible to conditionally apply the patch, e.g., only for armv7 and down?

**Comment by prince-chrismc** [comment]
Let's make a new PR, I did not review it yet

**Pull request closed without merging**
