### PR TITLE
aws-c-cal: modernize more for conan v2 + bump openssl

### PR DESCRIPTION
**Pull request by SpaceIm**
- conan v2:
  - fix windows/shared (protect double deletion of fPIC)
  - fix test package (logic based on self.user_info can't work for conan v2, and it was anyway wrong to define this user_info for the sole purpose of test package)
- bump openssl to 3.x

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
``
`[100%] Linking C executable test_package
/opt/conan/binutils/bin/ld: CMakeFiles/test_package.dir/test_package.c.o: undefined reference to symbol 'aws_logger_init_standard'
/opt/conan/binutils/bin/ld: /home/conan/w/prod-v2/BuildSingleReference/p/aws-ccfae5d5a8245f/p/lib/libaws-c-common.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I explicitly link `AWS::aws-c-common` in test package, how can it happen?

**Comment by SpaceIm** [comment]
v2 pipeline, all shared:

```
[100%] Linking C executable test_package
/opt/conan/binutils/bin/ld: CMakeFiles/test_package.dir/test_package.c.o: undefined reference to symbol 'aws_logger_init_standard'
/opt/conan/binutils/bin/ld: /home/conan/w/prod-v2/BuildSingleReference/p/aws-ccfae5d5a8245f/p/lib/libaws-c-common.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I link `AWS::aws-c-common` in test package, so why does it fail? https://github.com/conan-io/conan/issues/13723?

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
@uilianries @jcar87 @RubenRBS @danimtb Could you review please? This PR is mandatory for other aws recipe PRs opened for more than 1 month, and ultimately for PR providing v2 support to aws-sdk-cpp (and also fix https://github.com/conan-io/conan-center-index/issues/17474).

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
