### PR TITLE
added libgcrypt/1.8.4

### PR DESCRIPTION
**Pull request by dannftk**
Signed-off-by: Denis Pronin <dannftk@yandex.ru>

This PR is a continuation of [PR](https://github.com/conan-io/conan-center-index/pull/6724) as libgpg-error is a dependency of libgcrypt. Once libgpg-error has been merged libgcrypt is possible to be built and merged

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by dannftk** [comment]
The most of code of conanfile.py of libgpg-error and libgcrypt is taken from bincrafters recipes. They have been slightly modified to meet the requirements of CCI

**Comment by Croydon** [comment]
Thanks for providing credits. Would be slightly nicer if it would have been directly in the commits or in the PR description 🙂
____

CCI only allows to add/modify one recipe at a time. You have to split this into two pull requests.

As an early review comment: Please remove the `version` attribute from the `conanfile.py` this conflicts with the `conandata.yml` information once more versions are getting added in the future

**Comment by dannftk** [comment]
@Croydon, I created one more [PR](https://github.com/conan-io/conan-center-index/pull/6724) for libgpg-error as a dependency of libgcrypt that is left here to be merged as a package. Once libgpg-error has been merged we are able to merge this PR that will result in only one package

**Comment by dannftk** [comment]
@Croydon, also I've removed version specification from conanfile.py. Thank you for pointing that out

**Pull request closed without merging**
