### PR TITLE
simple-yaml: new recipe

### PR DESCRIPTION
**Pull request by Zeeno-atl**
Specify library name and version:  **simple-yaml/0.2.0**

Following my first addition, here is the second one. It is a small utility library making reading YAML files simple. I am the author. Please comment also best practices, since I am still not confident enough about creating Conan packages.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Seems like 0 packages are generated in the logs 🤔 that use to fail the build
@jgsogo @danimtb is that no longer a fail?

**Comment by Zeeno-atl** [comment]
In this case, it is correct behavior. The library uses C++20 concepts and constraints and source_location header file and it is fully implemented only in GCC11 and MSC16.11 neither of which is a part of this pipeline. If it helps, I can introduce a compatibility source_location header for clang in order to generate some packages in this pipeline.

**Comment by prince-chrismc** [comment]
Well if no packages are generated CCI can't confirm the package is correct.

It looks good but I just like to know it supposed to pass (it used to be an error) will see what the Conan team says

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
A very nice project!  Thank you for your contribution!

**Review by uilianries — CHANGES_REQUESTED** [review]
Blocking this PR until we have a solution about 0 packages.

**Comment by uilianries** [comment]
GCC 11 is already introduced on Conan Center. Need to check how to proceed with this PR.

**Comment by Zeeno-atl** [comment]
Once a #8932 is out, I can lower the requirements of this library so the pipeline will produce packages.

**Comment by jgsogo** [comment]
* Zero packages generated is no longer an error (~April 2021)
 * GCC 11 will be used when all requirements start to use it as well (epochs: https://github.com/conan-io/conan-center-index/pull/8587)

**Comment by uilianries** [comment]
@jgsogo Are we safe, can we merge it?

**Comment by prince-chrismc** [comment]
> Zero packages generated is no longer an error

🤯

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by jgsogo** [comment]
The zero-packages rule was changed after this PR https://github.com/conan-io/conan-center-index/pull/4658, where due to infrastructure issues it was not going to be possible to build any binaries (it would have required to change underlying servers where docker images are running).

As a side note, it was also useful for us when we introduced the notifications per configuration.

**Pull request merged**
