### PR TITLE
Add libtorrent/1.2.3 recipe

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **libtorrent/1.2.3**

Depends on  #761

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
- The Linux errors are the same as #792
- The Windows errors need #761

**Comment by uilianries** [comment]
@danimtb Can't find 'boost/1.71.0' package for gcc 6

**Comment by danimtb** [comment]
Waiting for #712 to be merge so we don't have to regenerate the packages twice. Sorry for the inconvenience

**Comment by madebr** [comment]
@danimtb I appreciate the update!

**Comment by madebr** [comment]
@danimtb Please unblock and give final review :relaxed:

**Comment by danimtb** [comment]
Relaunching this!

**Comment by danimtb** [comment]
Missing boot packages again. I will take a look

**Comment by madebr** [comment]
@danimtb While looking into this, you can also upgrade the boost version of this recipe to 1.72.0.

**Comment by danimtb** [comment]
boost packages were regenerated for all the versions. Relaunching CI for this PR

**Comment by danimtb** [comment]
There were some errors building the packages. @madebr please take a look at the logs

**Pull request merged**
