### PR TITLE
minizip: standard recipe layout + fix tools if non-Windows + del fPIC if shared + modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — DISMISSED** [review]

**Comment by SpaceIm** [comment]
It's also worth noting that looking at `ZEXPORT` in minizip declarations, it's quite clear that minizip was not designed to be extracted from zlib.
With some replace_in_file, and a patch, we could properly hide all symbols and export public symbols.

**Comment by SSE4** [comment]
diff is hard to check with layout change...

**Comment by SpaceIm** [comment]
Yes, the diff was not lost before the last commit https://github.com/conan-io/conan-center-index/pull/6641/commits/5c1114ae7875bbb84d2905e4f4f7af1d68db57a7

**Comment by SpaceIm** [comment]
It should be easier now.

**Comment by sh0** [comment]
Note that there is another bug with minizip that needs fixing sooner or later. Perhaps you want to add it to this PR. If not I'll try to submit a fix after this PR gets merged.

The issue is that `crypt.h` header should not be installed as it is internal and conflicts with glibc `crypt.h`. Interestingly this bug was already fixed once back when minizip was bundled with zlib recipe. See Conan issue #1525 and corresponding PR #1526. This issue is also discussed in upstream repository https://github.com/madler/zlib/pull/229

**Comment by SpaceIm** [comment]
Yes I can remove it in this PR, actually I was suspecting something wrong with this header.

**Review by SSE4 — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
@sh0 we need to restore crypt.h, it breaks libkml https://github.com/conan-io/conan-center-index/issues/6986

**Comment by sh0** [comment]
@SpaceIm It broke one other package in Conan which incorrectly included minizip `crypt.h` instead of glibc one. I can't remember which one it was, but I'll try to build bunch of packages later to find it.

**Comment by SpaceIm** [comment]
Well, there are 5 recipes with a direct dependency to minizip:

- assimp
- cassandra-cpp-driver
- libkml
- libspatialite
- libxlsxwriter

**Pull request merged**
