### PR TITLE
Package/open62541 v1.3.6

### LINKED ISSUE #16598: [package] open62541/1.3.4: Option single_header yields to CMake errors
### Description

If option `single_header==True` the generated package info contains invalid include paths `include/open62541/plugin` and `include/open62541/win32`.
This leads to CMake errors when adding a dependency to the `open62541::open62541` target generated by `CMakeDeps` generator:

```
[build] CMake Error in CMakeLists.txt:
[build]   Imported target "open62541::open62541" includes non-existent path
[build] 
[build]     "C:/conan/61c4f3/1/include/open62541/plugin"
[build] 
[build]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[build] 
[build]   * The path was deleted, renamed, or moved to another location.
[build] 
[build]   * An install or uninstall procedure did not complete successfully.
[build] 
[build]   * The installation package was faulty and references files it does not
[build]   provide.
```

### Package and Environment Details

* Package Name/Version: **open62541/1.3.4**
* Operating System+version: **Windows 10**
* Compiler+version: **GCC 8**
* Conan version: **conan 1.59.0**
* Python version: **Python 3.10.7**

### Conan profile

[settings]
os=Windows
arch=x86_64
compiler=gcc
compiler.version=8.1
compiler.libcxx=libstdc++11
build_type=Release

### Steps to reproduce

conan install open62541/1.3.4@ -osingle_header=True -g CMakeDeps
cmake -B build -S .
cmake --build build

### Logs

<details><summary>Click to expand log</summary>

```
[build] CMake Error in CMakeLists.txt:
[build]   Imported target "open62541::open62541" includes non-existent path
[build] 
[build]     "C:/conan/61c4f3/1/include/open62541/plugin"
[build] 
[build]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[build] 
[build]   * The path was deleted, renamed, or moved to another location.
[build] 
[build]   * An install or uninstall procedure did not complete successfully.
[build] 
[build]   * The installation package was faulty and references files it does not
[build]   provide.
```

</details>

### LINKED ISSUE #18913: [request] open62541/v1.3.6
### Package Name/Version

open62541/v1.3.6

### Changelog

https://github.com/open62541/open62541/releases/tag/v1.3.6

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

### PR DESCRIPTION
**Pull request by saukijan**
Specify library name and version:  *open62541/1.3.6**

# Changes
- Adds new package version as requested by #18913
- Fixes single header include paths as requested by  #16598
- Fixes `Visual Studio` compiler check in `generate()`
- Simplifies submodule source extraction
- Refactors `self.copy(...)` calls into `copy(self, ...)`
- Fixes `tools_dir` **copy** commands for conan v2
- Refactors `self.deps_user_info["ua-nodeset"].nodeset_dir` into ` self.dependencies["ua-nodeset"].conf_info.get( "user.ua-nodeset:nodeset_dir")` for conan v2 test package

closes  #18913
closes  #16598
---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by saukijan** [comment]
## Tested local packages for:
### Debian Bookworm 

 conan v2.0.9 

`conan create all/conanfile.py --version=1.3.6 --build=missing`

<details><summary>conan profile</summary>

```bash
Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
[options]
shared=True

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
[options]
shared=True

```

</details>

### Debian Bullseye 
conan v1.60.1 with latest [hooks](https://github.com/conan-io/hooks.git)

`conan create all/conanfile.py 1.3.6@ -pr:b=default -pr:h=default`
`conan create all/conanfile.py 1.3.6@ -tf test_v1_package/ -pr:b=default -pr:h=default`

<details><summary>conan profile</summary>

```bash
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

</details>

**Comment by RubenRBS** [comment]
Hi @saukijan thanks a lot for your contribution and patience :)

I've sent https://github.com/Hahn-Schickard/conan-center-index/pull/1 as you have not allowed maintainers to edit the PR, please consider merging :)

**Comment by saukijan** [comment]
@RubenRBS, your requested changes have been merged and verified. Thanks for your input!

**Comment by RubenRBS** [comment]
Thanks! Let's wait for the CI before approving, but this looks great so far :)

**Comment by saukijan** [comment]
> Thanks! Let's wait for the CI before approving, but this looks great so far :)

Oh, I didn't notice that the pipeline was still running. Sorry for the premature message. 

It looks like it's all green now

**Comment by saukijan** [comment]
@RubenRBS CI passed

**Review by RubenRBS — APPROVED** [review]

**Review by czoido — APPROVED** [review]

**Pull request merged**
