### PR TITLE
bump cpython dependencies

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **cpython/all**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
@uilianries @SSE4 , do you know how to resolve this conflict? What's the official way for it
``` - 'libuuid' provided by 'libuuid/1.0.3', 'util-linux-libuuid/2.39'```

**Comment by AndreyMlashkin** [comment]
The recipe itself requires libuuid/1.0.3 and fontconfig requires util-linux-libuuid/2.39

**Review by ericLemanissier — COMMENTED** [review]
You have to do this change to fix the conflict : https://github.com/conan-io/conan-center-index/pull/18550

**Comment by SSE4** [comment]
> @uilianries @SSE4 , do you know how to resolve this conflict? What's the official way for it ` - 'libuuid' provided by 'libuuid/1.0.3', 'util-linux-libuuid/2.39'`

I would like to forward this questions to @samuel-emrys. I know he was messing around different libuuid implementations in the past (see also https://github.com/conan-io/conan-center-index/pull/17427#issuecomment-1545476420). it has to be figured out yet on how to use these 3 implementations together in conan (util-linux, ext2fsprogs and one fork from source-forge).

**Comment by samuel-emrys** [comment]
> > @uilianries @SSE4 , do you know how to resolve this conflict? What's the official way for it ` - 'libuuid' provided by 'libuuid/1.0.3', 'util-linux-libuuid/2.39'`
> 
> I would like to forward this questions to @samuel-emrys. I know he was messing around different libuuid implementations in the past (see also [#17427 (comment)](https://github.com/conan-io/conan-center-index/pull/17427#issuecomment-1545476420)). it has to be figured out yet on how to use these 3 implementations together in conan (util-linux, ext2fsprogs and one fork from source-forge).

@ericLemanissier's response in https://github.com/conan-io/conan-center-index/pull/19552#pullrequestreview-1607953938 was correct:

> libuuid is deprecated because it is incompatible with uuid implementation shipped by most (all?) distros. The solution to your problem is to stop requiring libuuid in cpython and require util-linux-uuid instead.
Cf https://github.com/conan-io/conan-center-index/pull/17664 and https://github.com/conan-io/conan-center-index/pull/18550

FWIW, I had already put up a PR to bump libuuid to util-linux-libuuid in https://github.com/conan-io/conan-center-index/pull/18558, but:
* I don't think the conditions exist to have cpython build in 1.x exist anymore (missing binaries - team support probably required here)
* There are a number of dependencies that are awaiting migration to conan 2 before the cpython conan 2 recipe will build, namely:
    * https://github.com/conan-io/conan-center-index/pull/17806
    * https://github.com/conan-io/conan-center-index/pull/17805
    * https://github.com/conan-io/conan-center-index/pull/17427

**Comment by AndreyMlashkin** [comment]
Why the binaries are missing? Conan v1 is able to consume conan v2 packages, so what's the problem here?

**Comment by samuel-emrys** [comment]
> Why the binaries are missing? Conan v1 is able to consume conan v2 packages, so what's the problem here?

Is that true? If so, it's news to me..

**Review by SSE4 — APPROVED** [review]

**Pull request closed without merging**
