### PR TITLE
openssl 1.x.x: modernize

### PR DESCRIPTION
**Pull request by SpaceIm**
- relocatable shared lib on macOS: https://github.com/conan-io/hooks/issues/376
- CMakeDep support
- rationalize a little bit the recipe (everything is scattered, it's a nightmare to understand the logic of this recipe).
- pure C test package (I've not removed the empty `CONAN_LIBCXX` if Android, very odd stuff).

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
@jgsogo 

```
cmake/3.22.0: Not found in local cache, looking in remotes...
cmake/3.22.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
cmake/3.22.0: Downloaded recipe revision 0f16d40d1712f40dedf01cadc2377b9c
openssl/1.1.1m: Not found in local cache, looking in remotes...
openssl/1.1.1m: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
openssl/1.1.1m: Downloaded recipe revision baa265ba7a1c1bdf33346264aa84fa43
ERROR: openssl/1.1.1m: option 'no_md2' doesn't exist
Possible options are ['no_threads', 'shared', 'fPIC', 'no_asm', 'enable_weak_ssl_ciphers', '386', 'no_stdio', 'no_tests', 'no_sse2', 'no_bf', 'no_cast', 'no_des', 'no_dh', 'no_dsa', 'no_hmac', 'no_md5', 'no_mdc2', 'no_rc2', 'no_rsa', 'no_sha', 'no_async', 'no_dso', 'no_aria', 'no_blake2', 'no_camellia', 'no_chacha', 'no_cms', 'no_comp', 'no_ct', 'no_deprecated', 'no_dgram', 'no_engine', 'no_filenames', 'no_gost', 'no_idea', 'no_md4', 'no_ocsp', 'no_pinshared', 'no_rmd160', 'no_sm2', 'no_sm3', 'no_sm4', 'no_srp', 'no_srtp', 'no_ssl', 'no_ts', 'no_whirlpool', 'no_ec', 'no_ecdh', 'no_ecdsa', 'no_rfc3779', 'no_seed', 'no_sock', 'no_ssl3', 'no_tls1', 'openssldir']
```

cmake is in build requirements of test package, which drags openssl/1.1.1m. Why does it complain about `no_md2` option (this option is deleted if openssl >= 1.1.0) ? It's an option part of the host profile (openssl/1.0.2t), not the build profile.

**Comment by SSE4** [comment]
@SpaceIm I think you may have hit a hidden issue https://github.com/conan-io/conan/pull/9839

**Comment by SpaceIm** [comment]
Ouch, maybe disable test package for macOS M1 for the moment?

**Review by uilianries — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Comment by prince-chrismc** [comment]
@ericLemanissier These linter annotations look incorrect 🤔 

https://github.com/conan-io/conan-center-index/pull/9208/files#diff-d67d36ebb633f3e920a34cd24c6c92ac12ab88b1f1db0a694841133faeb10fe5R676

image

**Review by prince-chrismc — APPROVED** [review]

**Comment by ericLemanissier** [comment]
indeed. and this should have been fixed by https://github.com/PyCQA/pylint/commit/107f59e949f1824251d14717eb57650273c0ffff. I'll do some investigations here.
In the meantime, we could use the usual property https://github.com/conan-io/conan-center-index/blob/1fc6c023eff77f552b69cb52f9e705a75d292213/recipes/swig/all/conanfile.py#L46-L52

**Pull request merged**
