### PR TITLE
catch2: Add cpp_info.system_libs for Android

### PR DESCRIPTION
**Pull request by Linux13524**
Fixes: #4691

Specify library name and version:  **catch2/2.13.4**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SpaceIm — APPROVED** [review]

**Comment by SpaceIm** [comment]
add "closes https://github.com/conan-io/conan-center-index/issues/4691" in PR first message please.

**Comment by Linux13524** [comment]
Is "Fixes: #4691" not the right? At least this is written in the contribution guidelines...

**Comment by SpaceIm** [comment]
Oops, sorry, didn't see that, forget what I said :sleeping:

**Comment by Linux13524** [comment]
I was added to EAP now. How can I trigger the builds?

**Comment by SpaceIm** [comment]
close PR, wait 10-15s and reopen

**Comment by Linux13524** [comment]
> close PR, wait 10-15s and open again

Thanks! That worked :+1:

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
