### PR TITLE
[open62541] update dependencies, remove openssl fix

### PR DESCRIPTION
**Pull request by mathbunnyru**
Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by mathbunnyru** [comment]
I tried first configuration on my local machine and it worked, so I will retrigger CI.

**Comment by prince-chrismc** [comment]
I should not even try to build clang 10

 https://github.com/conan-io/conan-center-index/blob/17884947eaf3926614bb1ed26a58b332ac97358d/recipes/open62541/all/conanfile.py#L138-L139

**Comment by mathbunnyru** [comment]
> It should not even try to build clang 10
> 
> https://github.com/conan-io/conan-center-index/blob/17884947eaf3926614bb1ed26a58b332ac97358d/recipes/open62541/all/conanfile.py#L138-L139

It's under `if tools.Version(self.version) < "1.1.0":`, so the error is not here.

**Comment by prince-chrismc** [comment]
It looks like the newer version do not support newer compilers

image

**Review by prince-chrismc — APPROVED** [review]

**Review by theirix — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
