### PR TITLE
gtest: modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
gtest/1.10.0: [HOOK - hook_conan-center-v2.py] post_package(): ERROR: [MISSING SYSTEM LIBS (KB-H043)] Exception raised from hook: run() got an unexpected keyword argument 'output' (type=TypeError) (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H043)
ERROR: [HOOK - hook_conan-center-v2.py] post_package(): run() got an unexpected keyword argument 'output'
```

@uilianries what is this error? There is no run() with output keyword in gtest recipe. Does it come from https://github.com/conan-io/hooks/pull/469?

**Comment by prince-chrismc** [comment]
Good catch

**Comment by SpaceIm** [comment]
here the fix (hopefully): https://github.com/conan-io/hooks/pull/485

**Comment by SpaceIm** [comment]
that's weird, build has been triggered again 🤔

**Comment by uilianries** [comment]
@SpaceIm I re-triggered it to update Conan v2 result, as that hook is now disabled, so we can really see Conan v2 result .

**Pull request merged**
