### PR TITLE
glaze: add version 3.4.3 and 3.6.1, remove older versions

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **glaze/***

#### Motivation
There are several improvements since 3.4.1.
There are API breaking changes in 3.5.0.

#### Details
https://github.com/stephenberry/glaze/compare/v3.4.1...v3.4.3
https://github.com/stephenberry/glaze/compare/v3.4.3...v3.6.1

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by ErniGH** [comment]
It works for `apple-clang 15` 👍 : 
```
======== Exporting recipe to the cache ========
glaze/3.4.2: Exporting package recipe: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/conanfile.py
glaze/3.4.2: exports: File 'conandata.yml' found. Exporting it...
glaze/3.4.2: Copied 1 '.py' file: conanfile.py
glaze/3.4.2: Copied 1 '.yml' file: conandata.yml
glaze/3.4.2: Exported to cache folder: /Users/ernesto/.conan2/p/glazeb7b66740f87d0/e
glaze/3.4.2: Exported: glaze/3.4.2#40a4f3a5039863f4f6596773aba2d59c (2024-09-24 08:07:10 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu23
compiler.libcxx=libc++
compiler.version=15
os=Macos
[conf]


Profile build:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos
[conf]



======== Computing dependency graph ========
Graph root
    cli
Requirements
    glaze/3.4.2#40a4f3a5039863f4f6596773aba2d59c - Cache

======== Computing necessary packages ========
glaze/3.4.2: Forced build from source
Requirements
    glaze/3.4.2#40a4f3a5039863f4f6596773aba2d59c:da39a3ee5e6b4b0d3255bfef95601890afd80709 - Build

======== Installing packages ========
glaze/3.4.2: Calling source() in /Users/ernesto/.conan2/p/glazeb7b66740f87d0/s/src
glaze/3.4.2: Unzipping v3.4.2.tar.gz to .

-------- Installing package glaze/3.4.2 (1 of 1) --------
glaze/3.4.2: Building from source
glaze/3.4.2: Package glaze/3.4.2:da39a3ee5e6b4b0d3255bfef95601890afd80709
glaze/3.4.2: Building your package in /Users/ernesto/.conan2/p/b/glaze897bba555fa5e/b
glaze/3.4.2: Generating aggregated env files
glaze/3.4.2: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
glaze/3.4.2: Package 'da39a3ee5e6b4b0d3255bfef95601890afd80709' built
glaze/3.4.2: Build folder /Users/ernesto/.conan2/p/b/glaze897bba555fa5e/b/build-release
glaze/3.4.2: Generating the package
glaze/3.4.2: Packaging in folder /Users/ernesto/.conan2/p/b/glaze897bba555fa5e/p
glaze/3.4.2: Calling package()
glaze/3.4.2: package(): Packaged 1 file: LICENSE
glaze/3.4.2: package(): Packaged 124 '.hpp' files
glaze/3.4.2: Created package revision 96a0aa0bc0757cf39041c6c4d18d8e72
glaze/3.4.2: Package 'da39a3ee5e6b4b0d3255bfef95601890afd80709' created
glaze/3.4.2: Full package reference: glaze/3.4.2#40a4f3a5039863f4f6596773aba2d59c:da39a3ee5e6b4b0d3255bfef95601890afd80709#96a0aa0bc0757cf39041c6c4d18d8e72
glaze/3.4.2: Package folder /Users/ernesto/.conan2/p/b/glaze897bba555fa5e/p

======== Launching test_package ========

======== Computing dependency graph ========
Graph root
    glaze/3.4.2 (test package): /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/conanfile.py
Requirements
    glaze/3.4.2#40a4f3a5039863f4f6596773aba2d59c - Cache
Build requirements
    cmake/3.30.1#6d832cf2d46f6ec969ca5ed5b41f91eb - Cache
Resolved version ranges
    cmake/[>=3.20 <4]: cmake/3.30.1

======== Computing necessary packages ========
Requirements
    glaze/3.4.2#40a4f3a5039863f4f6596773aba2d59c:da39a3ee5e6b4b0d3255bfef95601890afd80709#96a0aa0bc0757cf39041c6c4d18d8e72 - Cache
Build requirements
    cmake/3.30.1#6d832cf2d46f6ec969ca5ed5b41f91eb:9e5323c65b94ae38c3c733fe12637776db0119a5#a9d2ec3d84609a8a009de5f1d2b06322 - Cache

======== Installing packages ========
cmake/3.30.1: Already installed! (1 of 2)
cmake/3.30.1: Appending PATH environment variable: /Users/ernesto/.conan2/p/cmake33fe25d241192/p/CMake.app/Contents/bin
glaze/3.4.2: Already installed! (2 of 2)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'env_info' used in: cmake/3.30.1

======== Testing the package ========
Removing previously existing 'test_package' build folder: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-gnu23-release
glaze/3.4.2 (test package): Test package build: build/apple-clang-15-armv8-gnu23-release
glaze/3.4.2 (test package): Test package build folder: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-gnu23-release
glaze/3.4.2 (test package): Writing generators to /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-gnu23-release/generators
glaze/3.4.2 (test package): Generator 'CMakeDeps' calling 'generate()'
glaze/3.4.2 (test package): CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(glaze)
    target_link_libraries(... glaze::glaze)
glaze/3.4.2 (test package): Generator 'CMakeToolchain' calling 'generate()'
glaze/3.4.2 (test package): CMakeToolchain generated: conan_toolchain.cmake
glaze/3.4.2 (test package): CMakeToolchain generated: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-gnu23-release/generators/CMakePresets.json
glaze/3.4.2 (test package): CMakeToolchain generated: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/CMakeUserPresets.json
glaze/3.4.2 (test package): Generator 'VirtualRunEnv' calling 'generate()'
glaze/3.4.2 (test package): Generating aggregated env files
glaze/3.4.2 (test package): Generated aggregated env files: ['conanrun.sh', 'conanbuild.sh']

======== Testing the package: Building ========
glaze/3.4.2 (test package): Calling build()
glaze/3.4.2 (test package): Running CMake.configure()
glaze/3.4.2 (test package): RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package"
-- Using Conan toolchain: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-gnu23-release/generators/conan_toolchain.cmake
-- Conan toolchain: Defining libcxx as C++ flags: -stdlib=libc++
-- Conan toolchain: C++ Standard 23 with extensions ON
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'glaze::glaze'
-- Configuring done (1.8s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-gnu23-release

glaze/3.4.2 (test package): Running CMake.build()
glaze/3.4.2 (test package): RUN: cmake --build "/Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-gnu23-release" -- -j14
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.o
[100%] Linking CXX executable test_package
[100%] Built target test_package


======== Testing the package: Executing test ========
glaze/3.4.2 (test package): Running test()
glaze/3.4.2 (test package): RUN: ./test_package
```

**Review by ErniGH — APPROVED** [review]
LGTM 🚀

**Comment by ErniGH** [comment]
3.6.1 works on for `apple-clang`:
```
======== Exporting recipe to the cache ========
glaze/3.6.1: Exporting package recipe: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/conanfile.py
glaze/3.6.1: exports: File 'conandata.yml' found. Exporting it...
glaze/3.6.1: Copied 1 '.py' file: conanfile.py
glaze/3.6.1: Copied 1 '.yml' file: conandata.yml
glaze/3.6.1: Exported to cache folder: /Users/ernesto/.conan2/p/glaze5847bdc9b1a8c/e
glaze/3.6.1: Exported: glaze/3.6.1#9653430ca52e71c1bc5d066b8dc45de1 (2024-10-01 08:28:00 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=23
compiler.libcxx=libc++
compiler.version=15
os=Macos
[conf]


Profile build:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=23
compiler.libcxx=libc++
compiler.version=15
os=Macos
[conf]



======== Computing dependency graph ========
Graph root
    cli
Requirements
    glaze/3.6.1#9653430ca52e71c1bc5d066b8dc45de1 - Cache

======== Computing necessary packages ========
glaze/3.6.1: Forced build from source
Requirements
    glaze/3.6.1#9653430ca52e71c1bc5d066b8dc45de1:da39a3ee5e6b4b0d3255bfef95601890afd80709 - Build

======== Installing packages ========
glaze/3.6.1: Calling source() in /Users/ernesto/.conan2/p/glaze5847bdc9b1a8c/s/src
glaze/3.6.1: Unzipping v3.6.1.tar.gz to .

-------- Installing package glaze/3.6.1 (1 of 1) --------
glaze/3.6.1: Building from source
glaze/3.6.1: Package glaze/3.6.1:da39a3ee5e6b4b0d3255bfef95601890afd80709
glaze/3.6.1: Building your package in /Users/ernesto/.conan2/p/b/glazefb66f7103df88/b
glaze/3.6.1: Generating aggregated env files
glaze/3.6.1: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
glaze/3.6.1: Package 'da39a3ee5e6b4b0d3255bfef95601890afd80709' built
glaze/3.6.1: Build folder /Users/ernesto/.conan2/p/b/glazefb66f7103df88/b/build-release
glaze/3.6.1: Generating the package
glaze/3.6.1: Packaging in folder /Users/ernesto/.conan2/p/b/glazefb66f7103df88/p
glaze/3.6.1: Calling package()
glaze/3.6.1: package(): Packaged 1 file: LICENSE
glaze/3.6.1: package(): Packaged 125 '.hpp' files
glaze/3.6.1: Created package revision 59738b62cfb2b9773fe8810011c816fa
glaze/3.6.1: Package 'da39a3ee5e6b4b0d3255bfef95601890afd80709' created
glaze/3.6.1: Full package reference: glaze/3.6.1#9653430ca52e71c1bc5d066b8dc45de1:da39a3ee5e6b4b0d3255bfef95601890afd80709#59738b62cfb2b9773fe8810011c816fa
glaze/3.6.1: Package folder /Users/ernesto/.conan2/p/b/glazefb66f7103df88/p

======== Launching test_package ========

======== Computing dependency graph ========
Graph root
    glaze/3.6.1 (test package): /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/conanfile.py
Requirements
    glaze/3.6.1#9653430ca52e71c1bc5d066b8dc45de1 - Cache
Build requirements
    cmake/3.30.1#6d832cf2d46f6ec969ca5ed5b41f91eb - Cache
Resolved version ranges
    cmake/[>=3.20 <4]: cmake/3.30.1

======== Computing necessary packages ========
Requirements
    glaze/3.6.1#9653430ca52e71c1bc5d066b8dc45de1:da39a3ee5e6b4b0d3255bfef95601890afd80709#59738b62cfb2b9773fe8810011c816fa - Cache
Build requirements
    cmake/3.30.1#6d832cf2d46f6ec969ca5ed5b41f91eb:9e5323c65b94ae38c3c733fe12637776db0119a5#a9d2ec3d84609a8a009de5f1d2b06322 - Cache

======== Installing packages ========
cmake/3.30.1: Already installed! (1 of 2)
cmake/3.30.1: Appending PATH environment variable: /Users/ernesto/.conan2/p/cmake33fe25d241192/p/CMake.app/Contents/bin
glaze/3.6.1: Already installed! (2 of 2)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'env_info' used in: cmake/3.30.1

======== Testing the package ========
Removing previously existing 'test_package' build folder: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-23-release
glaze/3.6.1 (test package): Test package build: build/apple-clang-15-armv8-23-release
glaze/3.6.1 (test package): Test package build folder: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-23-release
glaze/3.6.1 (test package): Writing generators to /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-23-release/generators
glaze/3.6.1 (test package): Generator 'CMakeDeps' calling 'generate()'
glaze/3.6.1 (test package): CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(glaze)
    target_link_libraries(... glaze::glaze)
glaze/3.6.1 (test package): Generator 'CMakeToolchain' calling 'generate()'
glaze/3.6.1 (test package): CMakeToolchain generated: conan_toolchain.cmake
glaze/3.6.1 (test package): CMakeToolchain generated: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-23-release/generators/CMakePresets.json
glaze/3.6.1 (test package): CMakeToolchain generated: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/CMakeUserPresets.json
glaze/3.6.1 (test package): Generator 'VirtualRunEnv' calling 'generate()'
glaze/3.6.1 (test package): Generating aggregated env files
glaze/3.6.1 (test package): Generated aggregated env files: ['conanrun.sh', 'conanbuild.sh']

======== Testing the package: Building ========
glaze/3.6.1 (test package): Calling build()
glaze/3.6.1 (test package): Running CMake.configure()
glaze/3.6.1 (test package): RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package"
-- Using Conan toolchain: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-23-release/generators/conan_toolchain.cmake
-- Conan toolchain: Defining libcxx as C++ flags: -stdlib=libc++
-- Conan toolchain: C++ Standard 23 with extensions OFF
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'glaze::glaze'
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-23-release

glaze/3.6.1 (test package): Running CMake.build()
glaze/3.6.1 (test package): RUN: cmake --build "/Users/ernesto/Documents/GitHub/conan-center-index/recipes/glaze/all/test_package/build/apple-clang-15-armv8-23-release" -- -j14
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.o
[100%] Linking CXX executable test_package
[100%] Built target test_package


======== Testing the package: Executing test ========
glaze/3.6.1 (test package): Running test()
glaze/3.6.1 (test package): RUN: ./test_package
```

**Review by AbrilRBS — APPROVED** [review]
Thanks (Sorry for the delay!)

**Pull request merged**
