### PR TITLE
tree-sitter-cql: add recipe

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **tree-sitter-cql/***

#### Motivation
CQL(Cassandra Query Language) parser on tree-sitter.

#### Details
https://github.com/shotover/tree-sitter-cql/tree/main/src

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by perseoGI — APPROVED** [review]
LGTM now! Thank you Toge 🐸

**Comment by toge** [comment]
@perseoGI 
Thank you for your improvements!

**Comment by uilianries** [comment]
I did few changes to this PR:

- The upstream supports both static and shared on Windows, the configuration is over the ifdef TREE_SITTER_HIDE_SYMBOLS: https://github.com/shotover/tree-sitter-cql/blob/v0.2.0/src/parser.c#L22349
- Simplified the test package to consume only CMakeDeps, I see no reason for testing using extra pkgconfig in this case
- Updated the recipe to be 2.x compatible only, using implements


NOTE:

The upstream has a Makefile already, I would be more inclined to use that, but the same is not prepared for Windows and keeping a build for msvc (CMake) and another with Make for Linux and Macos is even worst, so adopting an extra cmakefile is less bad I hope.

This project receives only few updates and last time was 6 months ago, plus, I only found Gentoo packaging it, so there is no much say about adding more complexity when packaging.

**Comment by toge** [comment]
@uilianries 
Thanks a lot for improvements!

**Review by perseoGI — APPROVED** [review]

**Pull request merged**
