### PR TITLE
rocksdb: add version 9.0.0

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **meson/9.0.0**

https://github.com/facebook/rocksdb/compare/v8.8.1...v9.0.0

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by valgur — APPROVED** [review]

**Review by RubenRBS — CHANGES_REQUESTED** [review]
Hi! Thanks a lot for taking the time to add the new version as always :)

Checking the changelog I saw some zstd changes and decided to see if it compiled successfuly, but I got an error:

```
$ conan create . --version=9.0.0 -b=missing -o="&:with_zstd=True"

======== Exporting recipe to the cache ========
rocksdb/9.0.0: Exporting package recipe: /Users/ruben/coding/support/external/toge/recipes/rocksdb/all/conanfile.py
rocksdb/9.0.0: exports: File 'conandata.yml' found. Exporting it...
rocksdb/9.0.0: Calling export_sources()
rocksdb/9.0.0: Copied 1 '.py' file: conanfile.py
rocksdb/9.0.0: Copied 1 '.yml' file: conandata.yml
rocksdb/9.0.0: Exported to cache folder: /Users/ruben/.conan2/p/rocksd8bbd22e6d891/e
rocksdb/9.0.0: Exported: rocksdb/9.0.0#b36efb4bfc57bc41bab00edd34d197af (2024-04-01 08:50:08 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos
[options]
&:with_zstd=True
[platform_tool_requires]
cmake/3.26.4
[conf]


Profile build:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos
[platform_tool_requires]
cmake/3.26.4
[conf]



======== Computing dependency graph ========
Graph root
    cli
Requirements
    rocksdb/9.0.0#b36efb4bfc57bc41bab00edd34d197af - Cache
    zstd/1.5.5#b87dc3b185caa4b122979ac4ae8ef7e8 - Cache

======== Computing necessary packages ========
rocksdb/9.0.0: Checking 5 compatible configurations
rocksdb/9.0.0: Compatible configurations not found in cache, checking servers
rocksdb/9.0.0: '74f556b76d5254aeefefa2442930850dea819848': compiler.cppstd=17
rocksdb/9.0.0: '14a4c68b2b89e029300180d8940579e049bab3c4': compiler.cppstd=20
rocksdb/9.0.0: '6c363c0eb2c980d790db5940b6b090badd2ebbd4': compiler.cppstd=gnu20
rocksdb/9.0.0: 'c164a4f0feb2bfe1547292ca6e3f6504da2dc55e': compiler.cppstd=23
rocksdb/9.0.0: 'b0d20ca6d7b585034377c5ede8b9288772e3b3c5': compiler.cppstd=gnu23
Requirements
    rocksdb/9.0.0#b36efb4bfc57bc41bab00edd34d197af:7c135b2a2959ecd12a78e9765bf7ec192736b526 - Build
    zstd/1.5.5#b87dc3b185caa4b122979ac4ae8ef7e8:76dad4e6c83dde347fd81bafee7e53584d62846e#73df715a085154927c3afaa9c630ab55 - Cache

======== Installing packages ========
zstd/1.5.5: Already installed! (1 of 2)

-------- Installing package rocksdb/9.0.0 (2 of 2) --------
rocksdb/9.0.0: Building from source
rocksdb/9.0.0: Package rocksdb/9.0.0:7c135b2a2959ecd12a78e9765bf7ec192736b526
rocksdb/9.0.0: Copying sources to build folder
rocksdb/9.0.0: Building your package in /Users/ruben/.conan2/p/b/rocks05d6fa0fa9646/b
rocksdb/9.0.0: Calling generate()
rocksdb/9.0.0: Generators folder: /Users/ruben/.conan2/p/b/rocks05d6fa0fa9646/b/build/Release/generators
rocksdb/9.0.0: CMakeToolchain generated: conan_toolchain.cmake
rocksdb/9.0.0: Requested parallel jobs: 12
rocksdb/9.0.0: CMakeToolchain generated: CMakePresets.json
rocksdb/9.0.0: CMakeToolchain generated: ../../../src/CMakeUserPresets.json
rocksdb/9.0.0: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(zstd)
    target_link_libraries(... zstd::libzstd_static)
rocksdb/9.0.0: Generating aggregated env files
rocksdb/9.0.0: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
rocksdb/9.0.0: Calling build()
rocksdb/9.0.0: apply_conandata_patches(): No patches defined in conandata
rocksdb/9.0.0: Running CMake.configure()
rocksdb/9.0.0: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/Users/ruben/.conan2/p/b/rocks05d6fa0fa9646/b/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/ruben/.conan2/p/b/rocks05d6fa0fa9646/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/ruben/.conan2/p/b/rocks05d6fa0fa9646/b/src"
-- Using Conan toolchain: /Users/ruben/.conan2/p/b/rocks05d6fa0fa9646/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: C++ Standard 17 with extensions ON
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: Component target declared 'zstd::libzstd_static'
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER - Success
-- Performing Test HAS_ARMV8_CRC
-- Performing Test HAS_ARMV8_CRC - Success
--  HAS_ARMV8_CRC yes
-- Performing Test BUILTIN_ATOMIC
-- Performing Test BUILTIN_ATOMIC - Success
-- Could NOT find uring (missing: uring_LIBRARIES uring_INCLUDE_DIR) 
-- Disabling RTTI in all builds
-- Performing Test HAVE_FALLOCATE
-- Performing Test HAVE_FALLOCATE - Failed
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE - Failed
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP - Failed
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - not found
-- Looking for sched_getcpu
-- Looking for sched_getcpu - not found
-- Looking for getauxval
-- Looking for getauxval - not found
-- Looking for F_FULLFSYNC
-- Looking for F_FULLFSYNC - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- ROCKSDB_PLUGINS: 
-- ROCKSDB PLUGINS TO BUILD 
-- Found Git: /usr/bin/git (found version "2.39.3 (Apple Git-146)") 
-- JNI library is disabled
-- Configuring done (2.1s)
CMake Error at CMakeLists.txt:1106 (target_link_libraries):
  Target "rocksdb" links to:

    zstd::zstd

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

rocksdb/9.0.0: ERROR: 
Package '7c135b2a2959ecd12a78e9765bf7ec192736b526' build failed
rocksdb/9.0.0: WARN: Build folder /Users/ruben/.conan2/p/b/rocks05d6fa0fa9646/b/build/Release
ERROR: rocksdb/9.0.0: Error in build() method, line 171
	cmake.configure()
	ConanException: Error 1 while executing
```

I haven't checked with old versions which might have the same error still, did you find the same problem?

**Comment by toge** [comment]
@RubenRBS 
Thank you for your review!
I will try to solve this problem.

I believe conan is the best package manager to try the latest version.
I would be honored if I could contribute to that.

**Comment by RubenRBS** [comment]
It'd _my pleasure_ to review it, yes! Thanks a lot for all the contributions, we really really appreciate it :)

**Comment by toge** [comment]
@RubenRBS 
It seems to be solved now.
Please check it again on your environment.

**Review by franramirez688 — APPROVED** [review]
@toge the problem commented by @RubenRBS is gone. Thanks for solving it! 👏

**Review by RubenRBS — APPROVED** [review]
Nice! Thanks a lot :)

**Pull request merged**
