### PR TITLE
aws-c-mqtt: add missing interface definition if shared + modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
see https://github.com/awslabs/aws-c-mqtt/blob/v0.8.10/include/aws/mqtt/exports.h

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
waiting for https://github.com/conan-io/conan-center-index/pull/17100, https://github.com/conan-io/conan-center-index/pull/17104, https://github.com/conan-io/conan-center-index/pull/17105 & https://github.com/conan-io/conan-center-index/pull/17107

**Comment by SpaceIm** [comment]
😫

**Comment by SpaceIm** [comment]
@RubenRBS @uilianries @prince-chrismc could you review please? There are several aws PR to merge (almost 3 months that these PRs have been opened, everything in this ecosystem could have been v2 ready in one day), and they depend on each others. Waiting several weeks each time one is merged (unlocking others) is frustrating, and having to ping is embarrassing.

**Comment by RubenRBS** [comment]
> Waiting several weeks each time one is merged (unlocking others) is frustrating (honestly I don't want to contribute anymore), and having to ping is embarrassing.

Sorry that you feel this way, just wanted to let you know that whatever your decision is, we appreciate your contributions and the time you have invested in CCI.
As for the review times, you might have noticed that in the last few weeks we have picked up the pace of reviewing, as we have internally implemented some processes to help speed things up without compromising PR quality, which we hope contributors like you are able to see and appreciate as we continue to work hard on it :)

**Review by RubenRBS — APPROVED** [review]

**Review by czoido — APPROVED** [review]

**Pull request merged**
