### PR TITLE
libssh2: conan v2 support

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
```
CMake Error at C:/J/w/prod/BuildSingleReference/.conan/data/libssh2/1.8.0/_/_/build/619186d607d148e5b5f1dde5dcc952778786dd88/build/CMakeFiles/CMakeTmp/CMakeLists.txt:19 (add_executable):
  Target "cmTC_3b9ae" links to target
  "CONAN_LIB::openssl_OpenSSL_SSL_libssl_RELEASE" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at C:/J/w/prod/BuildSingleReference/.conan/data/libssh2/1.8.0/_/_/build/619186d607d148e5b5f1dde5dcc952778786dd88/build/CMakeFiles/CMakeTmp/CMakeLists.txt:19 (add_executable):
  Target "cmTC_3b9ae" links to target
  "CONAN_LIB::openssl_OpenSSL_Crypto_libcrypto_RELEASE" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/CheckFunctionExists.cmake:92 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  src/CMakeLists.txt:110 (check_function_exists)
```

Does it come from https://github.com/conan-io/conan-center-index/pull/13228? /cc @ericLemanissier

**Comment by ericLemanissier** [comment]
I don't think it comes from this change, because the cmake variables are not in this log. But maybe there is a common cause

**Comment by SpaceIm** [comment]
Might be similar to https://github.com/conan-io/conan/issues/12180, since it seems to fail during https://github.com/libssh2/libssh2/blob/libssh2-1.8.0/src/CMakeLists.txt#L102-L106

**Comment by SpaceIm** [comment]
don't close please, it's an issue coming from CMakeDeps. Waiting a fix https://github.com/conan-io/conan/pull/12600

**Pull request closed without merging**
