### PR TITLE
aws-c-s3: add missing interface definition if shared + modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
see https://github.com/awslabs/aws-c-s3/blob/v0.2.8/include/aws/s3/exports.h

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
waiting for https://github.com/conan-io/conan-center-index/pull/17104, https://github.com/conan-io/conan-center-index/pull/17105, https://github.com/conan-io/conan-center-index/pull/17107, https://github.com/conan-io/conan-center-index/pull/17108 & https://github.com/conan-io/conan-center-index/pull/17119

**Review by mpimenov — APPROVED** [review]

**Comment by mpimenov** [comment]
@jcar87 Please take a look

**Comment by SpaceIm** [comment]
In aws-c-s3/0.1.29, if apple-clang with conan v2:

```
[100%] Linking C shared library libaws-c-s3.dylib
Undefined symbols for architecture x86_64:
  "_aws_md5_compute", referenced from:
      _aws_s3_message_util_add_content_md5_header in s3_request_messages.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've not tested locally, but shared build of 0.1.49 works fine for me.

**Comment by gjasny** [comment]
The `aws-c-s3` package directly uses functions provided by `aws-c-cal` and therefore should explicitly create a dependency on it. With the following change both: `0.1.29` and `0.1.49` build on macOS with shred library support:

```diff
diff --git a/recipes/aws-c-s3/all/conanfile.py b/recipes/aws-c-s3/all/conanfile.py
index b63b926fa..f63d8e59f 100644
--- a/recipes/aws-c-s3/all/conanfile.py
+++ b/recipes/aws-c-s3/all/conanfile.py
@@ -43,10 +43,12 @@ class AwsCS3(ConanFile):
         self.requires("aws-c-common/0.8.2", transitive_headers=True, transitive_libs=True)
         if Version(self.version) < "0.1.49":
             self.requires("aws-c-auth/0.6.11", transitive_headers=True)
+            self.requires("aws-c-cal/0.5.13")
             self.requires("aws-c-http/0.6.13")
             self.requires("aws-c-io/0.10.20", transitive_headers=True)
         else:
             self.requires("aws-c-auth/0.6.17", transitive_headers=True)
+            self.requires("aws-c-cal/0.5.13")
             self.requires("aws-c-http/0.6.22")
             self.requires("aws-c-io/0.13.4", transitive_headers=True)
         if Version(self.version) >= "0.1.36":
```

**Comment by jcar87** [comment]
Relaunched CI jobs for this PR, will check later to complete the review.

**Review by jcar87 — DISMISSED** [review]

**Comment by SpaceIm** [comment]
There is no dependency to `asw-c-cal` before 0.1.20 (there is still 0.1.19 in conandata)

**Review by jwillikers — APPROVED** [review]

**Review by jcar87 — APPROVED** [review]

**Pull request merged**
