### PR TITLE
xorg: expose system version of each component

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **xorg/system**

With conan 1.29.0 (including https://github.com/conan-io/conan/pull/7524 and https://github.com/conan-io/conan/pull/7534) it is now possible to expose the version of system packages via component.version attribute.
This should fix https://github.com/bincrafters/community/issues/1254

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
mmm, I'm not sure what's happening here. any idea @danimtb @jgsogo ?

**Comment by ericLemanissier** [comment]
At last it passes! You can shoot your reviews.
this PR blocks at least [cairo](https://github.com/conan-io/conan-center-index/pull/2847), [`pulseaudio/13.0@bincrafters/stable`](https://github.com/bincrafters/community/issues/1254), [`ffmpeg/4.2.1@bincrafters/stable`](https://github.com/bincrafters/conan-ffmpeg/pull/15)

**Review by SSE4 — APPROVED** [review]

**Review by Croydon — APPROVED** [review]
`self.cpp_info.components[name].version` seems not to be documented. Am I missing it somewhere or should we open an issue on the docs?

**Review by uilianries — APPROVED** [review]

**Comment by ericLemanissier** [comment]
mmm, it looks like C3I master bot did not process this commit: https://github.com/conan-io/conan-center-index/commit/86049562aa959d0e5774799c3d80f38527ed54c6
Am I just too impatient, or is there something wrong ?

**Comment by danimtb** [comment]
@ericLemanissier you are right, I am checking it

**Comment by ericLemanissier** [comment]
and we're good now, thanks !

**Pull request merged**
