### PR TITLE
Fix eastl configure step

### LINKED ISSUE #552: [package] eastl/3.15.00: A setting is set from inside the recipe
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **eastl/3.15.00**

We consider that setting settings from inside recipes in an anti-pattern.

https://github.com/conan-io/conan-center-index/blob/master/recipes/eastl/all/conanfile.py#L30

### PR DESCRIPTION
**Pull request by Minimonium**
Specify library name and version:  **eastl/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Closes #552 , #553

### CODE REVIEW

**Comment by Minimonium** [comment]
@danimtb What's the magic that needs to be done to stick configuration changes to recipes? I see that you run regeneration builds just recently, but now it seems to try to build for gcc 5 with the default C++ standard version.

**Comment by uilianries** [comment]
@Minimonium seems like eastl requires C++14, but some features are not supported by GCC5. You need to update it to GCC6

**Comment by Minimonium** [comment]
@uilianries that's some weird story with apple-clang. 🙂

**Comment by uilianries** [comment]
That's weird, same error for apple-clang 11.0

**Comment by uilianries** [comment]
Same error for 3.16.01. It seems be known: https://github.com/electronicarts/EASTL/issues/12

**Comment by Minimonium** [comment]
@danimtb How was the apple-clang handled before? Should we raise an error on it now? I don't see a place where the recipe's behaviour would change in a manner to break this behaviour, but we have had regeneration builds on this project's version.

**Comment by danimtb** [comment]
@Minimonium indeed this is something weird as we didn't experience that error before. I will relaunch the CI manually just in case...

**Comment by danimtb** [comment]
I am seeing this error now:

```
Make Error at source_subfolder/CMakeLists.txt:23 (add_library):
  Target "EASTL" links to target "CONAN_PKG::EABase" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

The name for eabase library changed and we are not setting a different name for the cmake generator anymore. please update this patch file as well https://github.com/conan-io/conan-center-index/blob/36b76da19db19070f527f5aa331643f1bf174a29/recipes/eastl/all/patches/0001-cmake-use-conan-add-install.patch#L10 to use `CONAN_PKG::eabase`

**Comment by Minimonium** [comment]
@danimtb We're back to the previous problem. 🙂

**Comment by danimtb** [comment]
I am checking this again and there were packages generated for apple-clang 9.1 before:

```
conan search eastl/3.15.00@ -r conan-center -q "os=Macos and compiler.version=9.1"
Existing packages for recipe eastl/3.15.00:

Existing recipe in remote 'conan-center':

    Package_ID: 0f744c1981808e538bb631fd2ccbe3cf70e9d04d
        [options]
            fPIC: True
            shared: True
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: apple-clang
            compiler.cppstd: 14
            compiler.libcxx: libc++
            compiler.version: 9.1
            os: Macos
        Outdated from recipe: False

    Package_ID: 407a571bae7b1abe7962dea3b7c4c9d3db545000
        [options]
            fPIC: True
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: apple-clang
            compiler.cppstd: 14
            compiler.libcxx: libc++
            compiler.version: 9.1
            os: Macos
        Outdated from recipe: False

    Package_ID: 9bacc47da7b5829d060453011b9fb2e9ab7dee36
        [options]
            fPIC: True
            shared: False
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: apple-clang
            compiler.cppstd: 14
            compiler.libcxx: libc++
            compiler.version: 9.1
            os: Macos
        Outdated from recipe: False

    Package_ID: de52cb92962f18603b20e9dc22faec538ec2bd20
        [options]
            fPIC: True
            shared: True
        [settings]
            arch: x86_64
            build_type: Release
            compiler: apple-clang
            compiler.cppstd: 14
            compiler.libcxx: libc++
            compiler.version: 9.1
            os: Macos
        Outdated from recipe: False
```

I don't know where this is coming from. @SSE4 could you help us with this bug?

**Comment by SSE4** [comment]
@danimtb I am puzzled. the error is within library code:
```
eabase.h:760:21: error: typedef redefinition with different types ('wchar_t' vs 'char32_t')
                        typedef wchar_t  char32_t;
                                         ^
```
e.g. they are trying to re-define built-in type [char32_t](https://en.cppreference.com/w/cpp/keyword/char32_t).
seems like we should just skip unsupported builds (apple-clang) and raise **ConanInvalidConfiguration**

**Comment by danimtb** [comment]
The thing is that I don't know how it worked previously. If you search for those configuration of this package in conan-center, there are packages uploaded!! 😕

**Comment by SSE4** [comment]
@danimtb previously we had issues with Xcode installations (see https://github.com/conan-io/conan-center-index/pull/183).  e.g. it was configured incorrectly and used wrong tools.

**Comment by Minimonium** [comment]
So should we ban the apple-clang as a whole? Or there are supported versions? I'm confused since google says that it's possible to build it on older versions: https://github.com/electronicarts/EASTL/issues/3

Could it be a misconfiguration on their part? Somewhere here: https://github.com/electronicarts/EASTL/blob/master/scripts/CMake/CommonCppFlags.cmake#L9

Btw, is the `compiler.cppstd: 14` configuration value applied implicitly?

**Comment by SSE4** [comment]
@Minimonium let's enable `cmake.verbose=True` and verify if correct flags were applied during the build

**Comment by SSE4** [comment]
@Minimonium flags are:
```  -DEASTL_EXPORTS -DEASTL_OPENSOURCE=1 -D_CHAR16T -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS   -m64 -stdlib=libc++ -g -isysroot /Applications/Xcode-9.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC 
```
is it enough or something else needed?

**Comment by Minimonium** [comment]
I'm a bit confused since the configuration seemingly should add the ` -std=c++17` too:
https://github.com/electronicarts/EASTL/blob/master/scripts/CMake/CommonCppFlags.cmake#L11

(I have checked that the file is the same in the archive we're using)

**Comment by SSE4** [comment]
@Minimonium okay, I am going to debug this on Mac later today, seems like something is going wrong that flag does't apply

**Comment by danimtb** [comment]
@Minimonium I think this can be closed as #1010 got merged

**Comment by Minimonium** [comment]
Good news! 😀

**Pull request closed without merging**
