### PR TITLE
ncurses: modernize

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **ncurses/all**

For https://github.com/conan-io/hooks/pull/320

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by SpaceIm — APPROVED** [review]

**Comment by uilianries** [comment]
Failed with OSX and armv8:

```
ncurses/6.2: 
Configured with: --prefix=/Users/administrator/Downloads/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Users/administrator/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/c++/4.2.1
configure: WARNING: templates do not work
configure: error: Cross-build requires two compilers.
Use --with-build-cc to specify the native compiler.
ncurses/6.2: WARN: Build folder is dirty, removing it: /Users/jenkins/w/BuildSingleReference/.conan/data/ncurses/6.2/_/_/build/77c486d783ac16b5120e565f0fccdd3c7ff8e627
ncurses/6.2: ERROR: Package '77c486d783ac16b5120e565f0fccdd3c7ff8e627' build failed
```

**Comment by madebr** [comment]
@jgsogo 
Is there a way to get access to build environment variables of the build context to set `BUILD_CC`?
e.g. `env_info_build` in analogy to `user_info_build`?
Then I would be able to do:
```python
"--with-build-cc={}".format(self.env_info_build.CC)
```

**Comment by jgsogo** [comment]
> @jgsogo
> Is there a way to get access to build environment variables of the build context to set `BUILD_CC`?
> e.g. `env_info_build` in analogy to `user_info_build`?
> Then I would be able to do:
> 
> ```python
> "--with-build-cc={}".format(self.env_info_build.CC)
> ```

Need to check, but if the environment is already populated when calling the `build()` method, something like the following should work:

```python
"--with-build-cc={}".format(tools.getenv("CC"))
```

**Comment by madebr** [comment]
> > @jgsogo
> > Is there a way to get access to build environment variables of the build context to set `BUILD_CC`?
> > e.g. `env_info_build` in analogy to `user_info_build`?
> > Then I would be able to do:
> > ```python
> > "--with-build-cc={}".format(self.env_info_build.CC)
> > ```
> 
> Need to check, but if the environment is already populated when calling the `build()` method, something like the following should work:
> 
> ```python
> "--with-build-cc={}".format(tools.getenv("CC"))
> ```

I want the compiler that targets the build machine, not the host machine

**Comment by jgsogo** [comment]
I'm not sure I understand what you mean.

If there is a build-requires that provides an environment variable `CC` it will be available in the `build()` method (and override the existing one). Any environment you need in the _host_ context must be provided by build-requires or already available when running Conan.

You might forward variables from the _build_ context to the _host_ one doing something like:

```python
class BuildRequires(ConanFile):
   name = "br"
   version = "test"

   def package_info(self):
      self.env_info.BUILD_CC.append(tools.get_env("CC"))
      
      
class Consumer(ConanFile):
   def build_requirements(self):
       self.build_requires("br/test")

   def build(self):
      self.output.write(tools.get_env("BUILD_CC"))
```

but the value of `BUILD_CC` in the previous example should be the same as `CC`... unless some build-requires is overriding that variable... which is exactly the intention of adding that build-requires.

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
