### PR TITLE
qt6: fix compilation of qtdeclarative with ICU

### PR DESCRIPTION
**Pull request by ericLemanissier**
fixes conan-io/conan-center-index#5290
fixes conan-io/conan-center-index#5841

Specify library name and version:  **qt/6.1.2**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jgsogo — COMMENTED** [review]
Hi! It is amazing how you are taking care of Qt recipe. 🙌 

I see you are waiting for feedback from the two opened issues, so I'll wait until those users report if this new revision works for them.

Thanks!

**Comment by Jihadist** [comment]
It looks strange but I couldnt build qt/6.1.2 
```
  Checking Build System
  Automatic MOC for target test_package
  Automatic RCC for example.qrc
  Building Custom Rule C:/Users/user/source/repos/conan-center-index-qt6/recipes/qt/6.x.x/test_package/CMakeLists.txt
  test_package.cpp
  qrc_example.cpp
  mocs_compilation_Release.cpp
  Generating Code...
  test_package.vcxproj -> C:\Users\user\source\repos\conan-center-index-qt6\recipes\qt\6.x.x\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb\bin\test_package.exe
  Building Custom Rule C:/Users/user/source/repos/conan-center-index-qt6/recipes/qt/6.x.x/test_package/CMakeLists.txt
qt/6.1.2 (test package): Running test()
qt/6.1.2 (test package): Testing CMake_find_package_multi
Resource content: "Hello World From Resource\n"
"Hello World!"
[HOOK - conan-center.py] pre_export(): WARN: [FPIC OPTION (KB-H006)] This recipe does not include an 'fPIC' option. Make sure you are using the right casing
libgettext/0.20.1: WARN: Recipe 'libgettext/0.20.1' is deprecated in favor of 'gettext'. Please, consider changing your requirements.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>' in 'conanbuildinfo.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>' in 'conanbuildinfo.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>' in 'conanbuildinfo.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'conanbuildinfo.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'conanbuildinfo.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindBrotli.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindBrotli.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindBZip2.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindBZip2.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findcmake.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findcmake.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Finddouble-conversion.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Finddouble-conversion.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindFreetype.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindFreetype.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findglib.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findglib.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findharfbuzz.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findharfbuzz.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindIconv.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindIconv.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findlibelf.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findlibelf.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findlibffi.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findlibffi.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findlibgettext.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findlibgettext.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findninja.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findninja.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindOpenSSL.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindOpenSSL.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindPCRE.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindPCRE.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findpcre2.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findpcre2.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findpkgconf.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findpkgconf.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindPNG.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindPNG.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindPostgreSQL.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindPostgreSQL.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindSQLite3.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindSQLite3.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'Findstrawberryperl.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'Findstrawberryperl.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:-Wl,--export-dynamic>' in 'FindZLIB.cmake' file.
WARN: replace_in_file didn't find pattern '$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-Wl,--export-dynamic>' in 'FindZLIB.cmake' file.
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] The *.cmake files have to be placed in a folder declared as `cpp_info.builddirs`. Currently folders declared: ['', '', 'res/archdatadir/bin', 'lib/cmake/Qt6Core', '', '', '', '', '', '', '', 'lib/cmake/Qt6Widgets', '', '', '', '', 'lib/cmake/Qt6DBus', '', '', '', ''] (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H019)
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] Found files: ./bin/ensure_pro_file.cmake; ./lib/cmake/Qt6Gui/conan_qt_qt6_guiprivate.cmake (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H019)
```
My profile:
```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

**Comment by ericLemanissier** [comment]
@Jihadist ok, this is just a hook error. Can you please retry with the updated recipe ?

**Comment by Jihadist** [comment]
@ericLemanissier 
Error with old recipe was:
```
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] The *.cmake files have to be placed in a folder declared as `cpp_info.builddirs`. Currently folders declared: ['', '', 'res/archdatadir/bin', 'lib/cmake/Qt6Core', '', '', '', '', '', '', '', 'lib/cmake/Qt6Widgets', '', '', '', '', 'lib/cmake/Qt6DBus', '', '', '', ''] (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H019)
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] Found files: ./bin/ensure_pro_file.cmake; ./lib/cmake/Qt6Gui/conan_qt_qt6_guiprivate.cmake (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H019)
```
Error with new recipe is:
```
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] The *.cmake files have to be placed in a folder declared as `cpp_info.builddirs`. Currently folders declared: ['', '', 'res/archdatadir/bin', 'lib/cmake/Qt6Core', '', '', '', '', '', '', '', 'lib/cmake/Qt6Widgets', '', '', '', '', 'lib/cmake/Qt6DBus', 'lib/cmake/Qt6Gui', '', '', '', ''] (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H019)
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] Found files: ./bin/ensure_pro_file.cmake (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H019)
```
So the last problem is ./bin/ensure_pro_file.cmake
But i tried to compile QXlsx (I mentioned it here https://github.com/conan-io/conan-center-index/issues/5841#issuecomment-861340619) with qt6.1.2 binaries (with your latest commit) and it works!

**Comment by ericLemanissier** [comment]
ok, you probably want to update your hooks, because this is now a warning, and not an error (https://github.com/conan-io/hooks/commit/d71695f6f1ca1b5d90adb4a48e040c0d0b8a9a8b) This explains why the CI passed !
I removed just pushed a new commit which removes the offending file, because it is useless anyway

**Review by jgsogo — DISMISSED** [review]

**Comment by Jihadist** [comment]
@ericLemanissier everything is ok with updated recipe
```
$ conan install qt/6.1.2@ -g cmake_find_package
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Installing package: qt/6.1.2
Requirements
    brotli/1.0.9 from 'conan-center' - Cache
    bzip2/1.0.8 from 'conan-center' - Cache
    double-conversion/3.1.5 from 'conan-center' - Cache
    freetype/2.10.4 from 'conan-center' - Cache
    glib/2.68.0 from 'conan-center' - Cache
    harfbuzz/2.8.0 from 'conan-center' - Cache
    libelf/0.8.13 from 'conan-center' - Cache
    libffi/3.3 from 'conan-center' - Cache
    libgettext/0.20.1 from 'conan-center' - Cache
    libiconv/1.16 from 'conan-center' - Cache
    libpng/1.6.37 from 'conan-center' - Cache
    libpq/13.2 from 'conan-center' - Cache
    openssl/1.1.1k from 'conan-center' - Cache
    pcre/8.44 from 'conan-center' - Cache
    pcre2/10.36 from 'conan-center' - Cache
    qt/6.1.2 from local cache - Cache
    sqlite3/3.35.5 from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    brotli/1.0.9:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
    double-conversion/3.1.5:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    freetype/2.10.4:27b2733304cef577b19f699fec3a5bdbefb36d16 - Cache
    glib/2.68.0:39022ddb4abc5a55ae186ee8c99842984908fec8 - Cache
    harfbuzz/2.8.0:1f8752c5b0764c0d6010d417fc2e020549726cc2 - Cache
    libelf/0.8.13:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libffi/3.3:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libgettext/0.20.1:b3e4dccd9a7572a5a29c77cc68475a955d494ef7 - Cache
    libiconv/1.16:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libpng/1.6.37:d140711d95cc16a85766a8fc3a551dfafe84cf63 - Cache
    libpq/13.2:d8ac7a0f959aa6a09fd6a37c84b5d5aa5d138d1f - Cache
    openssl/1.1.1k:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    pcre/8.44:3f212c80aa6d2e609fef5fb7cb6dfc086d607220 - Cache
    pcre2/10.36:c3909bc59b2700f5c593b64eb3cdec0e85b05bc5 - Cache
    qt/6.1.2:1c70a6f6d2dff654ef88dfd7665724acbec83e88 - Cache
    sqlite3/3.35.5:050fb3a4d3559ab088bce91739e61889c28839d1 - Cache
    zlib/1.2.11:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

Installing (downloading, building) binaries...
brotli/1.0.9: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: C:\Users\user\.conan\data\bzip2\1.0.8\_\_\package\d16a91eadaaf5829b928b12d2f836ff7680d3df5\bin
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
double-conversion/3.1.5: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libelf/0.8.13: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libffi/3.3: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libiconv/1.16: Already installed!
libiconv/1.16: Appending PATH environment var: C:\Users\user\.conan\data\libiconv\1.16\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\bin
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
openssl/1.1.1k: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
sqlite3/3.35.5: Already installed!
sqlite3/3.35.5: Appending PATH env var with : C:\Users\user\.conan\data\sqlite3\3.35.5\_\_\package\050fb3a4d3559ab088bce91739e61889c28839d1\bin
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
zlib/1.2.11: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libgettext/0.20.1: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libpng/1.6.37: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libpq/13.2: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
pcre/8.44: Already installed!
pcre/8.44: Appending PATH environment variable: C:\Users\user\.conan\data\pcre\8.44\_\_\package\3f212c80aa6d2e609fef5fb7cb6dfc086d607220\bin
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
pcre2/10.36: Already installed!
pcre2/10.36: Appending PATH environment variable: C:\Users\user\.conan\data\pcre2\10.36\_\_\package\c3909bc59b2700f5c593b64eb3cdec0e85b05bc5\bin
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
freetype/2.10.4: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
glib/2.68.0: Already installed!
glib/2.68.0: Appending PATH env var with: C:\.conan\18a64d\1\bin
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
harfbuzz/2.8.0: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
qt/6.1.2: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
Generator cmake_find_package created FindQt6.cmake
Generator cmake_find_package created FindOpenSSL.cmake
Generator cmake_find_package created Findpcre2.cmake
Generator cmake_find_package created Finddouble-conversion.cmake
Generator cmake_find_package created Findharfbuzz.cmake
Generator cmake_find_package created FindSQLite3.cmake
Generator cmake_find_package created FindPostgreSQL.cmake
Generator cmake_find_package created FindFreetype.cmake
Generator cmake_find_package created Findglib.cmake
Generator cmake_find_package created FindPNG.cmake
Generator cmake_find_package created FindBrotli.cmake
Generator cmake_find_package created Findlibffi.cmake
Generator cmake_find_package created FindPCRE.cmake
Generator cmake_find_package created Findlibelf.cmake
Generator cmake_find_package created Findlibgettext.cmake
Generator cmake_find_package created FindZLIB.cmake
Generator cmake_find_package created FindBZip2.cmake
Generator cmake_find_package created FindIconv.cmake
libgettext/0.20.1: WARN: Recipe 'libgettext/0.20.1' is deprecated in favor of 'gettext'. Please, consider changing your requirements.
```

**Review by uilianries — DISMISSED** [review]

**Review by Jihadist — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by Jihadist — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
