### PR TITLE
sdl: add `clang-cl` compatibility, add version 2.28.3

### PR DESCRIPTION
**Pull request by sykhro**
This PR adds support for compiling the sdl recipe with `clang-cl`. I know this is controversial, so I can drop that commit and keep using a forked version of the recipe if this is a change you don't like.
It also adds the latest bugfix release.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by sykhro** [comment]
> ### Conan v1 pipeline ❌
> Changes not allowed in build 1:
> 
> ```
> [sdl, dsp-filters]
> ```
> 
> Only one library can be changed in the same PR.

Err, not sure what's going on here.

**Review by danimtb — APPROVED** [review]

**Comment by sykhro** [comment]
Friendly ping :) rebased

**Review by jwillikers — APPROVED** [review]

**Comment by RubenRBS** [comment]
Retriggered, conflict should now be resolved, thanks a lot for your patience @sykhro :)

**Comment by sykhro** [comment]
> Retriggered, conflict should now be resolved, thanks a lot for your patience @sykhro :)

No worries, I know how it is with these things. I’ll take changes being merged later over having to recompile the same version due to a revision change :p

**Pull request merged**
