### PR TITLE
Update fmt/6.2.0

### PR DESCRIPTION
**Pull request by prince-chrismc**
Specify library name and version:  **fmt/6.2.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
The fix for this issue in in #1290

**Comment by danimtb** [comment]
@prince-chrismc https://github.com/conan-io/conan-center-index/pull/1290 has been merge. Please update this PR with the latest changes in master to solve conflicts. Thanks!

**Comment by danimtb** [comment]
Sorry, clicked the wrong button 😅

**Comment by prince-chrismc** [comment]
When @SpaceIm does amazing work and you have very little to do... Thank you!

**Pull request merged**
