### PR TITLE
leptonica: modernize more for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
v2 pipeline

```
ERROR: Version conflict: libtiff/4.4.0->libwebp/1.2.4, leptonica/1.81.0->libwebp/1.3.0.
```

needs https://github.com/conan-io/conan-center-index/pull/16168

But in the long term, of this v2 stuff will never scale without version range.

**Comment by SpaceIm** [comment]
```
ERROR: Missing binary: giflib/5.2.1:20edc2d7ad41c415355b4fd4a1ea0419c72d7a95

giflib/5.2.1: WARN: Can't find a 'giflib/5.2.1' package binary '20edc2d7ad41c415355b4fd4a1ea0419c72d7a95' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=11
os=Linux
[options]
fPIC=True
shared=False
utils=True

ERROR: Missing prebuilt package for 'giflib/5.2.1'
Check the available packages using 'conan list giflib/5.2.1:* -r=remote'
or try to build locally from sources using the '--build=giflib/5.2.1' argument
```

@danimtb @uilianries missing v2 packages of giflib here

**Comment by SpaceIm** [comment]
draft until https://github.com/conan-io/conan-center-index/pull/16566 is merged

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
The mindset about version ranges is changing so, hopefully we will see something in the near future :)

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
