### PR TITLE
libnpy: add recipe

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **libnpy/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by czoido — APPROVED** [review]

**Comment by RubenRBS** [comment]
Hi @toge, reading upstream's readme, it's not actually clear if the C++14 requirement is for the whole library or only the tests. I've tested locally with C++11 and it seems to work - Maybe we need to ask the author for their intentions and/or to clarify the readme? Thanks!

**Comment by toge** [comment]
@RubenRBS 
Thanks your advice!
I will confirm it.

**Review by samuel-emrys — APPROVED** [review]

**Review by czoido — CHANGES_REQUESTED** [review]
Blocking until this is solved: https://github.com/conan-io/conan-center-index/pull/19952#issuecomment-1725040323

**Comment by RubenRBS** [comment]
Author didn't intentionally make it support C++11, but didn't also use C++14 features, so let's stick it to C++11 and put a comment for future versions to be able to check

**Review by RubenRBS — APPROVED** [review]

**Review by czoido — APPROVED** [review]

**Pull request merged**
