### PR TITLE
doxygen 1.8.19 and 1.8.20 support added

### PR DESCRIPTION
**Pull request by mpusz**
Specify library name and version:  **doxygen/1.8.19** and **doxygen/1.8.20**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
This has hooks failing. So please try it locally 🙏 
Maybe you can look at https://github.com/conan-io/conan-center-index/issues/2537

**Comment by mpusz** [comment]
I tried locally both versions on my WSL2 before submitting them. As you can find out in the comments I am aware of #2537. 1.8.19 and 1.8.20 are created alike to what is already in ConanCenter and did not have any additional issues or requirements.

**Comment by gocarlos** [comment]
related: https://github.com/conan-io/conan-center-index/pull/2912

**Comment by madebr** [comment]
#2912 just got merged, I think this pr can be closed.

**Pull request closed without merging**
