### PR TITLE
Update mold to 1.7.1

### PR DESCRIPTION
**Pull request by ericriff**

### CODE REVIEW

**Comment by ericriff** [comment]
It looks like the hooks are broken. I'm raising from `validate_build` not from `build`

**Comment by ericriff** [comment]
And there is another issue. The `install` stage is silently failing here: https://github.com/rui314/mold/blob/c4850273c79548b6bc46a094b0119c27434dfaa7/CMakeLists.txt#L368-L369

This is because the conan-generated toolchain sets `set(CMAKE_INSTALL_LIBEXECDIR "bin")` instead of `libexec`, which I believe is the default. So Cmake tries to create a folder already exists and fails, so some of the files do not get installed. This fundamentally breaks the usage of this linker for GCC older than 12, since in those cases you need to pass the path to `libexec/mold` using the `-Bpath` thing. See https://github.com/rui314/mold/blob/main/README.md#how-to-use for reference.
What should we do here? 
This is how the conan package looks like
```
tree /home/eriff/.conan/data/mold/1.6.0/eriff/test/package/bfd8a9f3504587959491e9a5d7d3de4654e50db6/
/home/eriff/.conan/data/mold/1.6.0/eriff/test/package/bfd8a9f3504587959491e9a5d7d3de4654e50db6/
├── bin
│   ├── ld64.mold -> mold
│   ├── ld.mold -> mold
│   └── mold
├── conaninfo.txt
├── conanmanifest.txt
├── lib
│   └── mold
│       └── mold-wrapper.so
└── licenses
    └── LICENSE
```
Where as a conan-less build (is that a word?) produces this
```
├── bin
│   ├── ld64.mold -> mold
│   ├── ld.mold -> mold
│   └── mold
├── conaninfo.txt
├── conanmanifest.txt
├── lib
│   └── mold
│       └── mold-wrapper.so
└── libexec
    └── mold
        └── ld -> ../../bin/mold
```
Is it OK if I recreate `libexec/mold/ld` on the package step? Should I patch the CMakelists to avoid creating those folders and store the `ld` symlink in `bin`? I don't think that's the best approach.

**Comment by ericriff** [comment]
@uilianries maybe you have some input?

**Comment by ericriff** [comment]
What about the rest of my questions? Do you have any input?

**Comment by uilianries** [comment]
@ericriff Have you tried forcing CMAKE_INSTALL_LIBEXECDIR to libexec instead? You could use `cmake.cached_variables["CMAKE_INSTALL_LIBEXECDIR"] = "libexec"`

**Comment by ericriff** [comment]
Well, I had to patch the sources to make it install the `ld -> mold` symlink on the `bin` folder instead of `libexec`. I really don't like this since the `libexec` path is explicitly named on the `mold` README as the way con consume the linker. `Conan` complains about the existence of the `libexec` folder and blocks the PR if present.

On the other hand there is something weird with the test package. If, present, the build fails if two profiles (`pr:b/pr:h`) are used. It looks like in this case the `generate()` method is not called. If I remove the test package then it works as expected. Comments?

**Comment by ericriff** [comment]
Well, `generate()` is being called, but the `CMakeDeps` files are not there
```
ls -lah ~/.conan/data/mold/1.7.1/asd/asd/build/cb98efe3cc008371f789eb28289810b8ecd5546a/build/generators
total 36K
drwxrwxr-x 2 eriff eriff 4,0K dic 10 07:05 .
drwxrwxr-x 4 eriff eriff 4,0K dic 10 07:05 ..
-rw-rw-r-- 1 eriff eriff 3,0K dic 10 07:05 cmakedeps_macros.cmake
-rw-rw-r-- 1 eriff eriff  958 dic 10 07:05 CMakePresets.json
-rw-rw-r-- 1 eriff eriff  717 dic 10 07:05 conanbuildenv-release-x86_64.sh
-rw-rw-r-- 1 eriff eriff  142 dic 10 07:05 conanbuild.sh
-rw-rw-r-- 1 eriff eriff 3,8K dic 10 07:05 conan_toolchain.cmake
-rw-rw-r-- 1 eriff eriff   27 dic 10 07:05 deactivate_conanbuildenv-release-x86_64.sh
-rw-rw-r-- 1 eriff eriff  153 dic 10 07:05 deactivate_conanbuild.sh
```

**Comment by prince-chrismc** [comment]
> Well, I had to patch the sources to make CMake install the `ld -> mold` symlink on the `bin` folder instead of `libexec`. I really don't like this since the `libexec` path is explicitly named on the `mold` `README` as the way to consume the linker. `Conan` complains about the existence of the `libexec` folder and blocks the PR if present.

> [HOOK - conan-center.py] post_package(): ERROR: [DEFAULT PACKAGE LAYOUT (KB-H013)] Unknown folder 'libexec' in the package (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H013) 
ERROR: [HOOK - conan-center.py] post_package(): Some checks failed running the hook, check the output

We can add exceptions to the hooks FYI its common on that one https://github.com/conan-io/hooks/blob/d587cfebbf2b31c16e477b79c0c2fd4501f60fc8/hooks/conan-center.py#L1089

**Comment by ericriff** [comment]
> > Well, I had to patch the sources to make CMake install the `ld -> mold` symlink on the `bin` folder instead of `libexec`. I really don't like this since the `libexec` path is explicitly named on the `mold` `README` as the way to consume the linker. `Conan` complains about the existence of the `libexec` folder and blocks the PR if present.
> 
> > [HOOK - conan-center.py] post_package(): ERROR: [DEFAULT PACKAGE LAYOUT (KB-H013)] Unknown folder 'libexec' in the package ([`master`/docs/error_knowledge_base.md#KB-H013](https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md?rgh-link-date=2022-12-13T18%3A05%3A37Z#KB-H013))
> > ERROR: [HOOK - conan-center.py] post_package(): Some checks failed running the hook, check the output
> 
> We can add exceptions to the hooks FYI its common on that one [conan-io/hooks@`d587cfe`/hooks/conan-center.py#L1089](https://github.com/conan-io/hooks/blob/d587cfebbf2b31c16e477b79c0c2fd4501f60fc8/hooks/conan-center.py#L1089)

That would be ideal. I also had to revert the usage of `validate_build` because the hooks think that I'm raising a conan invalid config within `build` :(

**Comment by prince-chrismc** [comment]
> That would be ideal. I also had to revert the usage of `validate_build` because the hooks think that I'm raising a conan invalid config within `build` :(

To my knowledge `validate_build` is not ready for prime time, the migration path is still unclear so I would typicallly advice to avoid it for now 🙊

**Comment by ericriff** [comment]
@prince-chrismc I created a PR for the hooks as you suggested. Thanks!

**Comment by prince-chrismc** [comment]
Hooks are updated

**Review by uilianries — APPROVED** [review]
LGTM

**Review by prince-chrismc — APPROVED** [review]

**Pull request merged**
