### PR TITLE
gegles-spdlog_setup: bump to `spdlog/1.13.0`

### PR DESCRIPTION
**Pull request by gegles**
Specify library name and version:  **gegles-spdlog_setup/1.1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by josefgraus** [comment]
This broke the package as we were using, as now the spdlog version conflicts with another package. There didn't appear to be a version bump of the conan package to avoid backwards-breaking changes?

**Comment by gegles** [comment]
> This broke the package as we were using it, as now the spdlog version conflicts with another package. There didn't appear to be a version bump of the conan package to avoid backwards-breaking changes?

Hello and sorry if this broke your setup. I am still trying to figure out how best to deal with these various version bumps and conflicts... but in general, I think trying to keep everything as up to date as possible is a better way to go.

Are you not able to simply use `override=True` (or explicitly depend on `spdlog/1.12.0` in your package to solve the problem? 
That's what I do in such circumstances..

**Comment by josefgraus** [comment]
Yup, we can fix it on our end. I suppose what's alarming for us is that a fixed version is getting changes. One thing we somewhat depend on is that if we version-lock a requirement, we should be able to rebuild our software without issue in the future. 

I'm not sure what the policy or process is for publishing changes to conan packages. I think I assumed that they would be version bumped if the recipe changed in a way that would break projects that consumed it. Is this something I just made up and hoped was true? haha

**Comment by gegles** [comment]
I hear you, but, I actually think it's better to see the package version change to be more tied to code changes as opposed recipe changes, that can happen independently...
That's why indeed, the package locking mechanism can be key to control that aspect... but I, myself am still figuring how best to use that. If you want more control, you can also just include the revision number in the `self.requires(..)` call... to lock to a specific recipe/package version as well as the normal version...

**Comment by josefgraus** [comment]
I understand, yeah, it's kind of a weird in-between versioning problem. I take it the gegles-spdlog_setup didn't need any changes to compile against the newer version of spdlog? 

Thanks for the tip. We'll go ahead and start adding revisions to our dependencies.

**Pull request merged**
