### PR TITLE
glslang: add 1.3.204.0 + relocatable shared libs on macOS

### PR DESCRIPTION
**Pull request by SpaceIm**
relocatable shared lib: see https://github.com/conan-io/hooks/issues/376

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jgsogo** [comment]
Not yet. I'm monitoring it and we are having today a bottleneck for one of the MacOS configurations. Only one server is currently working and there are many jobs in the queue 😞 . Hopefully, @davidsanfal will have a new server ready soon.

**Comment by SpaceIm** [comment]
I see 1.3.204.0 packages of Spirv-Tools in conan center: https://conan.io/center/spirv-tools?version=1.3.204.0

**Comment by jgsogo** [comment]
True, that version is already there, but others are still in the queue ⏳ 

image

**Review by jgsogo — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Comment by SSE4** [comment]
can you explain the versioning scheme a little bit? e.g. is `1.3.204.0` older than `11.6.0`? if so, why do we need to add an old version now? why are some versions with 3 components and some with 4 components? why only `8.13.3559` ends with non-zero amongst others?

**Comment by SpaceIm** [comment]
> can you explain the versioning scheme a little bit? e.g. is `1.3.204.0` older than `11.6.0`? if so, why do we need to add an old version now? why are some versions with 3 components and some with 4 components? why only `8.13.3559` ends with non-zero amongst others?

For the "why", you should ask to Khronos Group.

glslang `1.3.204.0` refers to the version packaged in Vulkan SDK `1.3.204.0`, it is newer than `11.7.0`.

https://github.com/KhronosGroup/glslang/tags

**Comment by SSE4** [comment]
> https://github.com/KhronosGroup/glslang/tags

and I don't see `8.13.3559` in the tags... it's too puzzling for me

**Comment by SpaceIm** [comment]
https://github.com/KhronosGroup/glslang/releases/tag/8.13.3559

**Pull request merged**
