### PR TITLE
opencv: conan v2 support + bump dependencies

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
WARN: jasper/2.0.33: requirement libjpeg/9d overridden by opencv/2.4.13.7 to libjpeg/9e 
ERROR: Missing binary: jasper/2.0.33:bfdf3fc2246b4ec369e79f4123d8b89d983cc6ef
jasper/2.0.33: WARN: Can't find a 'jasper/2.0.33' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=10, os=Linux
- Options: fPIC=True, shared=False, with_libjpeg=libjpeg, libjpeg:fPIC=True, libjpeg:shared=False
- Dependencies: libjpeg/9e
- Requirements: libjpeg/9e
- Package ID: bfdf3fc2246b4ec369e79f4123d8b89d983cc6ef

ERROR: Missing prebuilt package for 'jasper/2.0.33'
Use 'conan search jasper/2.0.33 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=jasper'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

waiting https://github.com/conan-io/conan-center-index/pull/13285

**Review by jwillikers — DISMISSED** [review]

**Review by uilianries — DISMISSED** [review]

**Review by jwillikers — DISMISSED** [review]

**Review by jwillikers — DISMISSED** [review]

**Review by jwillikers — DISMISSED** [review]

**Comment by SpaceIm** [comment]
Should build hopefully now that includes have been fixed in test package when ffmpeg backend is tested.

**Review by jwillikers — DISMISSED** [review]

**Comment by SpaceIm** [comment]
Just few commits and I'll provide a full conan v2 migration of OpenCV

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
This PR is huge 😱 Maybe split each major in separate PRs so we can review them?

**Comment by prince-chrismc** [comment]
CI is still working 🤞

**Comment by SpaceIm** [comment]
> This PR is huge 😱 Maybe split each major in separate PRs so we can review them?

https://github.com/conan-io/conan-center-index/pull/14947 if you want

**Comment by prince-chrismc** [comment]
Thank you ❤️ I did the 2.x and I will look into the 3.x soon 🤞

**Pull request closed without merging**
