### PR TITLE
add v-hacd/4.1.0

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/3804

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
LGTM

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/14434#issuecomment-1331484500

**Comment by SpaceIm** [comment]
@uilianries what's wrong in CI?

**Comment by uilianries** [comment]
A bottleneck with Linux machines. More builds than usual, but it's working so far, the working queue didn't stop so far

**Comment by SpaceIm** [comment]
All builds of this PR are green, but continuous-integration is pending for almost 1 day, it's odd.

**Pull request merged**
