### PR TITLE
add depot_tools cci.20201009

### PR DESCRIPTION
**Pull request by reneme**
Specify library name and version:  **depot_tools/cci.20201009**

This attempts an update to the `depot_tools` package that was added to CCI in April and wasn't touched since. I'm hoping to use the new version to contribute [the bincrafters recipe for crashpad](https://github.com/bincrafters/conan-crashpad) later on.

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
Do you know if the auto update situation on Windows was fixed?

**Comment by prince-chrismc** [comment]
Looks like something changed :eyes: 

```
ERROR: depot_tools/cci.20201009 (test package): Error in test() method, line 6
	self.run("gclient --version", run_environment=True)
	ConanException: Error 1 while executing gclient --version
```

```
----Running------
> gclient --version
-----------------
The system cannot find the file C:\J\w\cci_PR-3182\s\6dd70c\1\bin\python3_bin_reldir.txt.

[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] original error: file does not exist
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] 
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] goroutine 1:
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #0 go.chromium.org/luci/vpython/python/interpreter.go:120 - python.(*Interpreter).GetVersion()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #1 go.chromium.org/luci/vpython/venv/config.go:286 - venv.(*Config).resolvePythonInterpreter()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241]   reason: failed to determine Python version for: C:\J\w\cci_PR-3182\s\6dd70c\1\bin\\\python3.exe
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] 
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #2 go.chromium.org/luci/vpython/venv/config.go:186 - venv.(*Config).makeEnv()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241]   reason: failed to resolve system Python interpreter
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] 
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #3 go.chromium.org/luci/vpython/venv/venv.go:150 - venv.With()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241]   reason: failed to initialize empty probe environment
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] 
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #4 go.chromium.org/luci/vpython/run.go:62 - vpython.Run()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #5 go.chromium.org/luci/vpython/application/application.go:320 - application.(*application).mainImpl()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #6 go.chromium.org/luci/vpython/application/application.go:408 - application.(*Config).Main.func1()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #7 go.chromium.org/luci/vpython/application/support.go:46 - application.run()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #8 go.chromium.org/luci/vpython/application/application.go:407 - application.(*Config).Main()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #9 vpython/main.go:106 - main.mainImpl()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #10 vpython/main.go:112 - main.main()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #11 runtime/proc.go:204 - runtime.main()
[E2020-10-13T10:59:06.801792Z 16644 0 annotate.go:241] #12 runtime/asm_amd64.s:1374 - runtime.goexit()
```

**Comment by reneme** [comment]
> Do you know if the auto update situation on Windows was fixed?

No, frankly I don't know. I just figured it would be time to try again.

**Comment by reneme** [comment]
Actually: Searching the error message points to this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1077384 Unfortunately, that's describing the exact same problem and refers to [the duplicate ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=1067590) that is discussing the bootstrapping situation on Windows. Unfortunately, it's still open. :-(

**Pull request closed without merging**
