### PR TITLE
ignore .devcontainer

### PR DESCRIPTION
**Pull request by dvirtz**
`.devcontainer` is a folder used by [VSCode](https://code.visualstudio.com/docs/remote/containers) for container development

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by Croydon** [comment]
Is this an extension or some default feature? Makes me wonder why it isn't a subdirectory of `.vscode`

**Comment by dvirtz** [comment]
It's an official extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

**Review by Croydon — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Comment by dvirtz** [comment]
can this be merged?

**Comment by dvirtz** [comment]
@uilianries a kind reminder

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
The CCI team will need to merge this manually, not sure who has permissions

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
@jgsogo @danimtb We need to merge manually here, because is a git file, but as CI failed, the button is disabled. Is there another internal alternative?

**Comment by jgsogo** [comment]
Ok, let's merge it manually 🚀  (it will probably fail in `master`)

**Pull request merged**
