### PR TITLE
fatfs: add conan recipe

### PR DESCRIPTION
**Pull request by b1ackviking**
Specify library name and version:  **fatfs/r0.14b**

[FatFs](http://elm-chan.org/fsw/ff/00index_e.html) is an implementation of a FAT filesystem intended to be used in embedded applications. Although it is widely used, the library sources are not available on GitHub and require modification to use in a project. This recipe makes the library available for consumers and customizable without having to edit the library files and integrate them into the project build system.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@b1ackviking It's not possible to download the source tar file from the server, it returns HTTP 403 (forbidden). Is there an alternative mirror?

**Comment by b1ackviking** [comment]
@uilianries I don't understand why does it fail with 403 on CI. `conan create . fatfs/r0.14b@` succeeds locally. My Conan version is 1.50.0. I am also able to download the source archive using wget and curl. Can the error happen because the website uses HTTP, not HTTPS? 

There are no official mirrors for this project. The most up-to-date [unofficial mirror on GitHub](https://github.com/abbrev/fatfs) also appears abandoned.

**Comment by uilianries** [comment]
@b1ackviking Yes, totally. Do you know if that website provides SSL certificate, or is there a mirror with HTTPS?

**Comment by b1ackviking** [comment]
@uilianries Sorry for the late response.

elm-chan.org does not have an SSL certificate, and I could not find any actively maintained mirrors, except for the specialized forks used in open-source projects like in [Zephyr](https://github.com/zephyrproject-rtos/fatfs) and [ESP-IDF](https://github.com/espressif/esp-idf/tree/master/components/fatfs).

I would like to avoid hosting a mirror myself because it will likely to receive bug reports that I will not able to merge in the upstream.

Are there any other workarounds for HTTP-only downloads?

**Comment by uilianries** [comment]
@b1ackviking Let's keep the download without HTTPS then. It's rare, but we have few cases.

**Comment by uilianries** [comment]
@b1ackviking It didn't work. I'll need to study a bit more this case.

**Comment by uilianries** [comment]
@b1ackviking please, consider https://github.com/b1ackviking/conan-center-index/pull/1

**Comment by b1ackviking** [comment]
@uilianries Merged, thanks!

**Comment by b1ackviking** [comment]
@uilianries I have searched online for the reasons of web server returning 403. Some answers suggest that the web server can filter requests based on the User-Agent header. But I could not reproduce the issue by sending any values, for example:

```
➜  ~ curl -v --user-agent "Conan/1.51.1 (Linux 5.18.16-arch1-1; Python 3.10.5; x86_64)" http://elm-chan.org/fsw/ff/arc/ff14b.zip
*   Trying 211.13.196.134:80...
* Connected to elm-chan.org (211.13.196.134) port 80 (#0)
> GET /fsw/ff/arc/ff14b.zip HTTP/1.1
> Host: elm-chan.org
> User-Agent: Conan/1.51.1 (Linux 5.18.16-arch1-1; Python 3.10.5; x86_64)
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 10 Aug 2022 09:04:51 GMT
< Server: Apache
< Last-Modified: Mon, 01 Nov 2021 12:35:00 GMT
< ETag: "2436c9-5cfb967cad189"
< Accept-Ranges: bytes
< Content-Length: 2373321
< Content-Type: application/zip
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0

➜  ~ curl -v --user-agent "d;salf;lksakj;d" http://elm-chan.org/fsw/ff/arc/ff14b.zip
*   Trying 211.13.196.134:80...
* Connected to elm-chan.org (211.13.196.134) port 80 (#0)
> GET /fsw/ff/arc/ff14b.zip HTTP/1.1
> Host: elm-chan.org
> User-Agent: d;salf;lksakj;d
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 10 Aug 2022 09:05:02 GMT
< Server: Apache
< Last-Modified: Mon, 01 Nov 2021 12:35:00 GMT
< ETag: "2436c9-5cfb967cad189"
< Accept-Ranges: bytes
< Content-Length: 2373321
< Content-Type: application/zip
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0
```

**Comment by uilianries** [comment]
@b1ackviking I can't reproduce it locally, it works for me. I'll open a separated PR and try to enable some debug output. Thanks for sharing it.

**Pull request closed without merging**
