### PR TITLE
Updated vulkan headers to 1.2.182

### PR DESCRIPTION
**Pull request by espositofulvio**
**vulkan-headers/1.2.182**

Update to vulkan-headers to the latest tagged release
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by espositofulvio** [comment]
I'm not sure what this error is about, I didn't change platform.interfaces. Can someone shed some light on this?

**Comment by uilianries** [comment]
Ops! It seems like the PR #5994 caused a little trouble on Conan Center.

**Comment by uilianries** [comment]
Blocked https://github.com/conan-io/conan-center-index/pull/6055

**Comment by espositofulvio** [comment]
hi, @uilianries,
I see you fixed the error in the other recipe, but I'm not sure if I have to do anything, it looks like there's still a build error but I can't see what exactly as the Details link brings me to a 403 page

**Comment by uilianries** [comment]
@espositofulvio you have to click on links provided byt the bot on comments only. That "Details" link on results box will return 403 for sure. The thing is, if you close the PR, wait 10 secs, and re-open again, it should re-trigger the CI build

**Comment by uilianries** [comment]
@espositofulvio Could you please rebase your PR? You can just run `git pull upstream master` and `git push origin`.

**Comment by espositofulvio** [comment]
Done, it's building now I guess

**Comment by espositofulvio** [comment]
Still getting the unexpected error. I'll try with a fresh clone, give me a few minutes

**Pull request closed without merging**
