### PR TITLE
opengl: prefer libopengl-dev on Debian

### PR DESCRIPTION
**Pull request by SpaceIm**
closes https://github.com/conan-io/conan-center-index/issues/17131

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
I'm not sure about this change. libpengl-dev does not seem to be a drop-in replacement of libgl-dev, but more of a complement. 
[libopengl-dev](https://debian.pkgs.org/11/debian-main-amd64/libopengl-dev_1.3.2-1_amd64.deb.html) provides only opengl.pc, without any headers, contrary to [libgl-dev](https://debian.pkgs.org/11/debian-main-amd64/libgl-dev_1.3.2-1_amd64.deb.html) which provides gl.pc (notice the different name) and header files.
I think we need to install both packages and publish them as different components.

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
Indeed headers are missing, I don't know which package to install. But gl.pc refers to the legacy implementation, it's not complementary.

**Comment by ericLemanissier** [comment]
The point is that some package call `pkg-config opengl ...` or link to `-lOpenGL` directly, and other packages call `pkg-config gl ...` or link to `-lGL` directly. There is no way `opengl/system` can decide which of these should be installed. it depends on the consumer

**Comment by SpaceIm** [comment]
So what would you do? package_info() has to be deterministic somehow.

**Comment by ericLemanissier** [comment]
install both, and publish both a different components (the same way xorg publishes several components https://github.com/conan-io/conan-center-index/blob/master/recipes/xorg/all/conanfile.py#L83). We should always publish gl component, but publish opengl component only if it is actually installed (some distros do not provide it yet)

Alternatively, we could just make another recipe for libopengl-dev, but it's unfortunate that the name opengl/system is already taken :/ It would have been clearer to have opengl/system install libopengl-dev and gl/system install libgl-dev

**Comment by SpaceIm** [comment]
When both libopengl-dev & libgl-dev are installed on my distro, find_package(OpenGL) displays a warning that it has found two implementations of OpenGL and it chooses the deprecated one.

**Comment by ericLemanissier** [comment]
that's handled by https://cmake.org/cmake/help/latest/policy/CMP0072.html

**Comment by artem-ogre** [comment]
Will this PR be worked on? Because of this problem qt5 package can't be built with gcc-11.

**Review by valgur — APPROVED** [review]

**Pull request closed without merging**
