### PR TITLE
imgui: add version 1.89.2

### PR DESCRIPTION
**Pull request by toge**
Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot) Find more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)

Specify library name and version:  **imgui/1.89.2**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by MartinDelille — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Auto merge is broken by failed label too 🤔 #15130

**Review by prince-chrismc — APPROVED** [review]

**Comment by sykhro** [comment]
Was there any reason for not adding the 1.89.2 docking branch? docking 1.88 is currently the default on Conan center

**Comment by prince-chrismc** [comment]
What does docking mean? Sorry you question isn't clear if you could be so inclined to explain that be helpful.

**Comment by SpaceIm** [comment]
> Was there any reason for not adding the 1.89.2 docking branch? docking 1.88 is currently the default on Conan center

Because docking branch in imgui recipe is a best effort, feel free to submit a PR.

**Pull request merged**
