### PR TITLE
gfortran: fix hooks

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **gfortran/***

things fixed in this PR:

- download only the binary matching the os
- download linux binary from stable URL

things that still need to be fixed:
- actually test gfortran by compiling and running a program

fixes conan-io/conan-center-index#4696

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
so, the current failure on CCI happens because gfortran is not yet added to the allowlist of KB-H013 conan center hook.
I did some tests and:

- windows [seems to work](https://github.com/eirikb/proof-of-conan/runs/6306233936?check_suite_focus=true#step:8:142)
- macos [seems to work](https://github.com/eirikb/proof-of-conan/runs/6306234033?check_suite_focus=true#step:8:93)
- recent linux distributions [fail because they don't have libisl.so.15](https://github.com/eirikb/proof-of-conan/runs/6306233830?check_suite_focus=true#step:8:111) (this lib is not provided in the archive downloaded by the recipe)
- old linux distributions [fail because they don't have crt1.o and crti.o](https://github.com/eirikb/proof-of-conan/runs/6306234125?check_suite_focus=true#step:9:121)

Do you see a solution for these problems @uilianries @SpaceIm @samuel-emrys ?

**Comment by ericLemanissier** [comment]
if anybody wants to continue working on this,

**Comment by SSE4** [comment]
> if anybody wants to continue working on this,

seems like your comment was truncated...

**Comment by ericLemanissier** [comment]
Oh yes, sorry.
If anybody wants to continue working on gfortan, don't hesitate to base yourself  on this PR

**Pull request closed without merging**
