### PR TITLE
- [libtool] update config.guess/config.sub

### PR DESCRIPTION
**Pull request by SSE4**
libtool doesn't have new releases after 2.4.6
new gnu config provides support for more platforms, e.g. e2k

Specify library name and version:  **libtool/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
I saw this is the other PR as well ... should we be more consistent with the method already in use?
https://github.com/conan-io/conan-center-index/search?q=user_info_build

**Comment by SSE4** [comment]
> I saw this is the other PR as well ... should we be more consistent with the method already in use?
> https://github.com/conan-io/conan-center-index/search?q=user_info_build

to be honest, no idea. these things are still experimental, so we have to live for a while with both approaches.

**Comment by prince-chrismc** [comment]
The second approach has not been merged, but both are correct...

**Review by prince-chrismc — APPROVED** [review]

**Review by madebr — APPROVED** [review]
I didn't know `libtoolize` copied `config.guess` and `config.sub`.

**Review by uilianries — APPROVED** [review]

**Pull request merged**
