### PR TITLE
[googleapis] prepare for google-cloud-cpp-2.10.1

### PR DESCRIPTION
**Pull request by coryan**
Specify library name and version:  **googleapis/cci.20230501**

This is the first in a series of PRs to update `google-cloud-cpp` to v2.10.1.  It updates googleapis to a snapshot circa 2023-05-01 (thus the version).  The SHA matches what `google-cloud-cpp` expects.  Future PRs will update `grpc-protos`, `grpc`, and finally `google-cloud-cpp`.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]
Thanks a lot!

**Review by RubenRBS — APPROVED** [review]

**Comment by coryan** [comment]
Seems like something else failed.  Could you share a link to the logs?

**Review by SSE4 — APPROVED** [review]

**Comment by RubenRBS** [comment]
Seems like the bot posted the results this time :)

**Comment by coryan** [comment]
Yes, my bad.  I forgot how `deactivate_library()` works.  Tested locally on Linux, the offending component is not compiled.

**Review by RubenRBS — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
