### PR TITLE
fontconfig: generate gcc11 binaries

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **fontconfig/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@jgsogo Why did this PR's CI not try to build gcc11 ?
cf

- https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/12379/1-linux-gcc/fontconfig/2.13.91//summary.json
- https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/12379/1-linux-gcc/fontconfig/2.13.92//summary.json
- https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/12379/1-linux-gcc/fontconfig/2.13.92//summary.json

It looks to me that all the (build_)requirements of fontconfig are already on the new epoch.

**Comment by jgsogo** [comment]
From the logs (internal logs) I see:

```
Epoch for 'freetype/2.12.1@#0bbb81805455cee1339cfd08a4682f1b': 0
Epoch for 'libuuid/1.0.3@#42d244923e46f0a22bdafd1978cc4109': 0
```

I'll trigger them behind the scenes and come back to this PR

**Comment by ericLemanissier** [comment]
this is what I don't understand. Both these packages have been updated in the last days, and their PR produced GCC11 binaries:

- https://github.com/conan-io/conan-center-index/commit/52856a3b2200d9ea873322e92800859086a94498 https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/12273/5/libuuid/1.0.3//summary.json
- https://github.com/conan-io/conan-center-index/commit/46297c74812987133dc4ea91fd8ce0d01f9a7065 https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/12272/6/freetype/2.12.1//summary.json

**Comment by jgsogo** [comment]
For some reason, it used an older revision from `libuuid`:

```
Revisions for 'libuuid/1.0.3' at remote 'conancenter':
fbc969de8465e507cbd2742a031ed80d (2022-08-17 14:33:19 UTC)
42d244923e46f0a22bdafd1978cc4109 (2021-07-08 16:29:29 UTC)
25b1b0e082f6bf475cb03d973376f969 (2021-01-04 23:03:20 UTC)
8cb89c32a48c009fdc9d0ba0ebf7f751 (2020-11-19 12:33:43 UTC)
0af468907873ba6cfa5cd2a28966a8af (2020-08-05 08:47:28 UTC)
840ba593f58e204662dc518dc9158ea6 (2019-12-19 08:49:01 UTC)
74d5dc903ef1eb921f5acb0bbd6deec8 (2019-10-13 07:22:48 UTC)
```

Same for `freetype`:

```
Revisions for 'freetype/2.12.1' at remote 'conancenter':
c8c5244e6fa502d35a14ae7b5cb3f751 (2022-08-17 08:11:34 UTC)
0bbb81805455cee1339cfd08a4682f1b (2022-05-27 16:26:34 UTC)
```

I'll check some caches and expiration dates we are using

**Comment by jgsogo** [comment]
Ok. I think I know what's happening here.

When we introduced the concept of epochs, we also added a cache for the packageID computation (iterating all profiles and running `conan info` takes some time). The algorithm to compute the epoch for a PR is easy, but it is iterative: changing from one epoch to another might introduce new configurations and, those configurations might introduce new dependencies/build-requires. Moreover, this package-id computation is performed in the main job and then in some other child jobs that will actually build only the packages that are needed.

To avoid running the same computation several times (epochs algorithm + package-id deduplication) we decided to store the package-id computation in some cache, the key of this cache takes into account several items: reference, recipe-revision, conan version, conan configuration and the content of the configuration file. And it stores all the requirements and build-requirements (with their rrev).

In your case, this cache was populated by https://github.com/conan-io/conan-center-index/pull/12271, that was triggered a couple of days ago and, because this PR is exactly the same rrev for `fontconfig`, everything matches and **it retrieves the cached values... that contained the latest revisions two days ago**.

Hope the explanation is clear enough and, at least, makes sense. We all know that dealing with cached values is always hard (Fowler said), but it is not an excuse. We (@SSE4 ) have already thought about some situations where this cache-invalidation issue might happen and decided that those scenarios were very unlikely (and we were right, most PRs are working fine) and the time that the cache saves was worth the risk.

What to do next?
 * you can introduce some change here, so it computes a new rrev
 * I can invalidate the cache for this PR manually <-- I'll do this now
 * We can think about some extra item to be introduced to cache keys (i.e: date?)

**Comment by ericLemanissier** [comment]
Ok, this is close to what I imagined. I noticed that https://github.com/conan-io/conan-center-index/pull/12271 still did not build gcc11, so I thought about a cache problem, and I closed the PR and opened this one, thinking (wrongly) that there could not be sharing of cache across PRs. If it ever occurs again I'll add a newline to the recipe.

**Comment by jgsogo** [comment]
Now it should build as expected:

```
References in this build:
 - fontconfig/2.13.91@#4857b6bcb212b1c46f66846c2bd43166 (epoch 20220120)
 - fontconfig/2.13.92@#78d0e09f3bb9914b457070f59a4807b8 (epoch 20220120)
 - fontconfig/2.13.93@#6b9893550651d0a186878f545d3ce94d (epoch 20220120)
```

**Review by jgsogo — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
