### PR TITLE
libidn: migrate to Conan v2, add shared MSVC build support

### LINKED ISSUE #16850: [package] libidn/1.36: conan install reports "libidn/1.36 seems broken"
### Description

when I attempt to install libidn/1.36 conan reports 

> Recipe 'libidn/1.36' seems broken.
> It is possible that this recipe is not Conan 2.0 ready
> If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
> If it is your recipe, check if it is updated to 2.0

Hence I am unable to use podofo/0.9.7 for now.

### Package and Environment Details

* Package Name/Version: **libidn/1.36**
* Operating System+version: **Manjaro Linux**
* Compiler+version: **GCC 12.2.1**
* Conan version: **conan 2.0.2**
* Python version: **Python 3.10.9**

### Conan profile

[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

### Steps to reproduce

conan install --requires=libidn/1.36 -of temp

### Logs

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

======== Computing dependency graph ========
Graph root
    cli
*********************************************************
Recipe 'libidn/1.36' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'libidn/1.36' not resolved: libidn/1.36: Cannot load recipe.
Error loading conanfile at '/home/volker/.conan2/p/libidad27bc2fdd138/e/conanfile.py': Unable to load conanfile in /home/volker/.conan2/p/libidad27bc2fdd138/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/volker/.conan2/p/libidad27bc2fdd138/e/conanfile.py", line 1, in <module>
    from conans import AutoToolsBuildEnvironment, ConanFile, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (/home/volker/.local/lib/python3.10/site-packages/conans/__init__.py)

### LINKED ISSUE #20908: [package] libidn/1.36: Not compatible with Conan 2
### Description

This recipe fails to build, as it seems to be importing some old name for an autotools build environment.

### Package and Environment Details

* Package Name/Version: **libidn/1.36**
* Operating System+version: **Windows 11**
* Compiler+version: **MSVC 2022**
* Docker image: N/A
* Conan version: **conan 2.0.13**
* Python version: **Python 3.7.8**

### Conan profile

Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

### Steps to reproduce

With `Conanfile.txt`:
```
[requires]
libidn/1.36

[generators]
PkgConfigDeps
MesonToolchain
```
and running:
```
$ conan install . --output-folder=cbuild --build=missing
```

### Logs

<details><summary>Click to expand log</summary>

```
======== Computing dependency graph ========
libidn/1.36: Not found in local cache, looking in remotes...
libidn/1.36: Checking remote: conancenter
libidn/1.36: Downloaded recipe revision ebf701f91ec5391f2b1973a18cc0d74d
Graph root
    conanfile.txt: ...\conanfile.txt
*********************************************************
Recipe 'libidn/1.36' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'libidn/1.36' not resolved: libidn/1.36: Cannot load recipe.
Error loading conanfile at 'C:\Users\quant\.conan2\p\libid7482640c3fb00\e\conanfile.py': Unable to load conanfile in C:\Users\quant\.conan2\p\libid7482640c3fb00\e\conanfile.py
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\quant\.conan2\p\libid7482640c3fb00\e\conanfile.py", line 5, in <module>
    from conans import AutoToolsBuildEnvironment, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment'
.
```

</details>

### PR DESCRIPTION
**Pull request by valgur**
* Resolves #20908
* Resolves #16850

### CODE REVIEW

**Comment by valgur** [comment]
Closing temporarily to avoid unnecessary load on the CI. Will reopen when I'm actively working on the PR again.

**Comment by toge** [comment]
@valgur 
Could you please run the CI again?
I am very hopeful that your libidn's conan v2 support will work.

**Comment by RubenRBS** [comment]
@valgur in cases like this where the test package requires the library both as a normal and as a tool requires, they first compilation will fail, but every since a few weeks ago, alongside some changes in the CI that ensure we first build (And store!) the static configurations, the second try for the same recipe revision will progress further, as it will be able to find both requested versions

just an FYI, I've also restarted the build so hopefuly now it can pass! Thanks a lot for the changes :)

**Comment by RubenRBS** [comment]
(Also pinging @toge in case they don't know about that either)

**Review by fdgStilla — APPROVED** [review]

**Comment by valgur** [comment]
@RubenRBS maybe check out this one as well. Probably similar to the `libidn2` one.

**Review by toge — APPROVED** [review]

**Pull request merged**
