### PR TITLE
openvino: ported upstream patch for C++23 support

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
Specify library name and version:  **openvino/2023.1.0**

**Changes:** Ported upstream patch for compilation with C++23 for better portability

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Hi @jwillikers @RubenRBS @uilianries 
Please, have a look at current PR. It's a replacement for https://github.com/conan-io/conan-center-index/pull/20782

**Review by jwillikers — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
@RubenRBS 
I've just upstreamed one more patch, please, have a look

**Review by uilianries — APPROVED** [review]
LGTM

**Review by jwillikers — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
can we merge the PR?

**Pull request merged**
