### PR TITLE
libtool: less verbose package_info()

### PR DESCRIPTION
**Pull request by SpaceIm**
same rational than https://github.com/conan-io/conan-center-index/pull/19497#issue-1873328386

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
======== Installing packages ========
ERROR: Missing binary: libtool/2.4.6:b647c43bfefae3f830561ca202b6cfd935b56205

libtool/2.4.6: WARN: Can't find a 'libtool/2.4.6' package binary 'b647c43bfefae3f830561ca202b6cfd935b56205' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=11
os=Linux
[options]
fPIC=True
shared=False

ERROR: Missing prebuilt package for 'libtool/2.4.6'
Check the available packages using 'conan list libtool/2.4.6:* -r=remote'
'conan test' tested packages must exist, and '--build' argument is used only for the 'test_package' dependencies, not for the tested dependencies

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```

? But I'm building libtool in this PR 🤔

**Review by ericLemanissier — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by SpaceIm** [comment]
@RubenRBS @danimtb @uilianries help please. Why v2 pipeline doesn't wait static package? I thought it was implemented in v2 pipeline for several weeks: https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md#06-oct-2023---1015-cest

**Comment by danimtb** [comment]
> @RubenRBS @danimtb @uilianries help please. Why v2 pipeline doesn't wait static package? I thought it was implemented in v2 pipeline for several weeks: https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md#06-oct-2023---1015-cest

yes, that was the fix. We now prioritize the static builds... Let me check what is happening here.

**Comment by danimtb** [comment]
I have done some debugging and it seems that the option was not being picked properly. We'll release a fix in next deployment. Thanks for reaching out!

**Comment by SpaceIm** [comment]
Why does it fail in v1 pipeline now?

**Comment by SpaceIm** [comment]
> I started a CI build to generate the missing libtool/2.4.6

What do you mean? This PR is about libtool and expects its own packages for this RREV. There is a bug in c3i: https://github.com/conan-io/conan-center-index/pull/19501#issuecomment-1792269986

**Review by ericLemanissier — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
