### PR TITLE
openssl: add 3.0.4,3.0.5,1.1.1p,1.1.1q

### LINKED ISSUE #11319: [request] openssl/1.1.1p
### Package Details
  * Package Name/Version: openssl/1.1.1p
  * Changelog: https://www.openssl.org/news/cl111.txt

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

### PR DESCRIPTION
**Pull request by the-nic**
Specify library name and version:  **openssl/3.0.4** **openssl/1.1.1p**

Security fix: https://www.openssl.org/news/secadv/20220621.txt

Fixes #11319

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Comment by Croydon** [comment]
Please put `Fixes #11319` in the description

**Review by toge — DISMISSED** [review]

**Review by tsondergaard — DISMISSED** [review]

**Review by gegles — APPROVED** [review]

**Review by uilianries — DISMISSED** [review]

**Comment by the-nic** [comment]
why isnt the jenkins job finishing?

**Comment by uilianries** [comment]
@the-nic it's more busy than usual building other PRs

**Comment by the-nic** [comment]
@uilianries  for a day?

**Comment by uilianries** [comment]
> @uilianries for a day?

We build more than 100 configurations for each build: https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md#introduction

Now consider some huge packages like Qt, which takes many hours for each build. As result, we will need a couple days. I just canceled the bigger CI build, then others, including this PR will start soon.

**Comment by Croydon** [comment]
Please restart (close PR for 10 seconds, then re-open)

**Comment by the-nic** [comment]
the vs build seems to fail all the time.. Is there a fix required for the runners?

**Comment by ashkulz** [comment]
Is there a way to speed this up, as this is a security sensitive release?

**Comment by ashkulz** [comment]
@the-nic can you close and reopen the PR in the hope this will trigger a rebuild?

**Comment by ashkulz** [comment]
@uilianries is there a way we can take at the log of the failing builds? Right now, clicking on the links where [it had an unexpected error](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/11322/8-configs/windows-visual_studio/openssl/3.0.3//summary.json) doesn't have any information which is actionable from people who don't have access.

**Comment by uilianries** [comment]
@ashkulz Please, read https://github.com/conan-io/conan-center-index/blob/c5358a13384c4f5f763edce5247a4a21be236433/docs/labels.md#unexpected-error

A new CI job has been triggered.

**Comment by the-nic** [comment]
I added 1.1.1q and 3.0.5, too

**Review by Croydon — APPROVED** [review]

**Review by gegles — APPROVED** [review]
Please, merge this asap! Thanks!

**Review by SSE4 — APPROVED** [review]

**Comment by gegles** [comment]
Any progress?

**Comment by ashkulz** [comment]
@uilianries the link you've provided states
> Label [Unexpected Error](https://github.com/conan-io/conan-center-index/pulls?q=is%3Aopen+is%3Apr+label%3A%22Unexpected+Error%22) is assigned by the CI when the process finishes abnormally. It tries to signal all the pull requests that failed, but didn't provide any meaninful message to the user. Usually it is some random internal error and it won't happen next time the CI runs, don't hesitate to trigger a new build in this situation.

but this has been happening again and again, at least in the case of this PR. Rather than waste a lot of resources on re-triggering CI which fail again, would it be possible to merge without having the Jenkins run completed (just the GitHub runs, which seem to work from what I can see)?

**Comment by ashkulz** [comment]
Thanks, happy to see this merged :+1:

**Pull request merged**
