### PR TITLE
docs: remove PEP8 formating request

### PR DESCRIPTION
**Pull request by prince-chrismc**
https://peps.python.org/pep-0008/#maximum-line-length This is the least followed thing in PRs so it seems a bit misleading to ask people to do this extra since it creates a lot of changes.

### CODE REVIEW

**Comment by RubenRBS** [comment]
I agree. One thing we talked about yesterday is that it might make sense to have pre-commit hooks that deal with most of the stylistic choices so whether PEP8 was followed or not does not even need to be asked.

Also, @uilianries said that almost noone runs the hooks at all, so we should also look into ways to make it simpler to have at least some of them on mondatorily

**Review by RubenRBS — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by prince-chrismc** [comment]
I work on my phone and very often make small PRs without being able to test things and usually thats not an issue.

Thats half of the reason I was happy to see the GitHub Actions, so they can run in my fork and I can test them without setting up locally on a PC.

**Comment by RubenRBS** [comment]
Yes, I wouldn't trust a pre-commit to be enforceable (You can always pass `-n` to `git commit` to skip those), so it would be a good thing to have when you _want_ it, but actions should still be ran in most cases as you say, yep

**Comment by prince-chrismc** [comment]
git hooks dont work if you use the web UI or codespaces either :(

**Comment by SSE4** [comment]
@prince-chrismc I worry the message `conan rejects to follow PEP8` might be too sound. but practically speaking, I prefer working PRs. constantly asking contributers to apply minor changes like spaces is kinda super annoying.

**Comment by prince-chrismc** [comment]
Hopefully we are headline worthy and no one writes that.

I did my best to diminish the implication.

We are no longer asking people to apply formatting changes.

**Comment by uilianries** [comment]
We never blocked someone because was not following PEP8, but that checkbox looks like something mandatory for the PR. There was few issues related to PEP8, but more people asking to use or not, exactly because of that checkbox and all code was not formatted according. I would prefer if everyone use PEP8 always, but it is asking too much as Conan is C/C++ tool, and I don't think most of users are Python dev and they are following all good practices.

**Pull request merged**
