### PR TITLE
openssl: add openssl/3.0.2 + openssl/1.1.1n

### LINKED ISSUE #9792: [request] openssl/1.1.1n
### Package Details
  * Package Name/Version: **openssl/1.1.1n**
  * Changelog: **https://www.openssl.org/news/cl111.txt**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

### PR DESCRIPTION
**Pull request by Croydon**
Closes #9792

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Why does CI build other versions?

**Comment by jpilet** [comment]
Thanks @Croydon .
This fixes:
`OpenSSL Security Advisory [15 March 2022] Severity: High`
https://www.openssl.org/news/secadv/20220315.txt

Please review and merge asap.

**Review by SpaceIm — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by Croydon** [comment]
CI has problems // @jgsogo

**Comment by jueschmi** [comment]
any updates on this, I am looking forward to integrate version 1.1.1n  asap due to the latest security finding

**Comment by gegles** [comment]
Please any progress on this? We need to upgrade as well! Thanks!

**Comment by Croydon** [comment]
// @jgsogo @danimtb @SSE4 @uilianries 

CI problems: It builds more versions than it should have and never finishes some builds

**Comment by Croydon** [comment]
Maybe CI has those problems with adding new versions to two different version folders?

I split in into two PRs and the problems do not seem to exist there

-> #9849
->  #9850

Please review there to get it merged ASAP

**Comment by jgsogo** [comment]
Closing it, it's added via https://github.com/conan-io/conan-center-index/pull/9849 and https://github.com/conan-io/conan-center-index/pull/9850

**Comment by Croydon** [comment]
@jgsogo Do you know what happened with CI in this PR? (see comments above)

**Pull request closed without merging**
