### PR TITLE
freetype: drop dead code

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **freetype/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/8783744246/attempts/2)

**Review by RubenRBS — APPROVED** [review]
Thanks!

**Comment by jellespijker** [comment]
@ericLemanissier can you guys double check if the version being passed to `self._make_freetype_config(libtool_version)` should indeed be the libtool_version and not `self.version` ?

This broke our build: https://github.com/Ultimaker/cura-workflows/actions/runs/8798472364/job/24145560363#step:16:27993 
When building fontconfig it searches for freetype2 version 2.13.2 but the generated `freetype2.pc` uses the version extracted from the textfile which is 26.1.20

**Comment by ericLemanissier** [comment]
@jellespijker I guess your question is more related to https://github.com/conan-io/conan-center-index/pull/22974 than to this PR
@jwillikers already has your back: https://github.com/conan-io/conan-center-index/pull/23010

**Comment by jellespijker** [comment]
> @jellespijker I guess your question is more related to #22974 than to this PR

Agreed will ask it there

**Pull request merged**
