### PR TITLE
Patch/expected lite

### PR DESCRIPTION
**Pull request by prince-chrismc**
Specify library name and version:  **expected-lite/0.3.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
If this patch is not appropriate, would it be possible to have some guidance on mixing tagged releases with comming/date versioning of packages?

Ie having version 0.3.0 and 03102019 ? to get the upstream changes

**Comment by uilianries** [comment]
First, where did you find that patch?

Is there any new version to be released soon? If yes, I prefer droping the support and adding the patch for the new version only.

**Comment by prince-chrismc** [comment]
I tagged the commit I cherry picked with my commit

I'll mark this as a draft since there maybe be a new release soon

https://github.com/martinmoene/expected-lite/issues/32#issuecomment-619086509

**Comment by prince-chrismc** [comment]
fixed #1444

**Pull request closed without merging**
