### PR TITLE
Add Taocpp PEGTL 3.2.1

### PR DESCRIPTION
**Pull request by uilianries**
Specify library name and version:  **taocpp-pegtl/3.2.1**

/cc @d-frey

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — CHANGES_REQUESTED** [review]
What is the motivation behind copying these files to a 2.x.x subfolder when there are no changes required?

**Comment by Croydon** [comment]
> 
> 
> _config.yml_ syntax error in build 1:
> 
> ```
> Only one library can be changed in the same PR: [miniaudio/all, taocpp-pegtl/2.x.x, taocpp-pegtl/3.x.x]
> ```

Miniaudio? Go home bot, you are drunk 👀

**Comment by madebr** [comment]
https://github.com/conan-io/conan-center-index/pull/6626 is already adding 3.2.1
I propose to retarget this pr to only rename `all` to `2.x.x`.

**Comment by uilianries** [comment]
> 
> 
> What is the motivation behind copying these files to a 2.x.x subfolder when there are no changes required?

Not copying, renaming the folder. There are 2 folders: all and 3.x.x. The folder "all" contains only 2.x.x, so its name doesn't follow the intention.

**Comment by uilianries** [comment]
> 
> 
> #6626 is already adding 3.2.1
> I propose to retarget this pr to only rename `all` to `2.x.x`.

Thanks, I'll close this one.

**Comment by uilianries** [comment]
> 
> 
> > _config.yml_ syntax error in build 1:
> > ```
> > Only one library can be changed in the same PR: [miniaudio/all, taocpp-pegtl/2.x.x, taocpp-pegtl/3.x.x]
> > ```
> 
> Miniaudio? Go home bot, you are drunk 👀

hmmm, miniaudio has been merged few minutes ago ... I'll check if is not related to CR LF problem again 😭

**Pull request closed without merging**
