### PR TITLE
bump libigl

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **libigl/2.4.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
@jgsogo , RAM overrun?

**Comment by SSE4** [comment]
> @jgsogo , RAM overrun?

very likely. we'll need to check how much RAM does it need, and move it to the proper pod (large or xlarge).

**Comment by uilianries** [comment]
Can we build with only one core to save some RAM? 

https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#constructor

`cmake = CMake(self, parallel=False)`

**Comment by svenpilz** [comment]
I guess we would also need to change to the new _cmake_ options. Some have been renamed. They provide a list in https://github.com/libigl/libigl/blob/v2.4.0/LibiglOptions.cmake.sample.

**Comment by jcar87** [comment]
Closing in favour of https://github.com/conan-io/conan-center-index/pull/18849 - thanks for your contribution!

**Pull request closed without merging**
