### PR TITLE
openssl: ensure install_name_tool works on MacOS #5308

### PR DESCRIPTION
**Pull request by rockdreamer**
Specify library name and version:  **openssl/1.1.1k**

Adds a test to validate that users can effectively run install_name_tool on the generated library when shared=True on MacOS

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Not sure that it's the responsability of conan-center recipe to ckech that.

**Comment by rockdreamer** [comment]
> Not sure that it's the responsability of conan-center recipe to ckech that.

The issue I reported (conan-io#5308) makes the conan-center-index recipe unusable for my workplace.

In [ccdc-opensource/conan-openssl](https://github.com/ccdc-opensource/conan-openssl/blob/db2b88a32dd4b59b6145e59cbed5058675b47432/conanfile.py#L564), you can see the workaround I used:

```
        lflags = env_build.link_flags
        if self.settings.os == "Macos":
            lflags.append("-headerpad_max_install_names")
```
I want to upstream the change but it doesn't make much sense on its own if it can't be tested.

So I've pushed a test first to see if it fails. If it does, I plan on pushing the change above that fixes the test, otherwise I'll keep the workaround recipe in the company org.

We can also have a wider discussion in a separate conan issue: should all dylibs built by conan recipes be checked in the same way? Not being able to change rpaths is a rather limiting defect, it means I can't distribute conan-built libraries that exhibit this behaviour and must rely on DYLD_LIBRARY_PATH. A really bad idea on modern macos systems.

**Comment by SpaceIm** [comment]
> > Not sure that it's the responsability of conan-center recipe to ckech that.
> 
> The issue I reported (#5308) makes the conan-center-index recipe unusable for my workplace.
> 
> In [ccdc-opensource/conan-openssl](https://github.com/ccdc-opensource/conan-openssl/blob/db2b88a32dd4b59b6145e59cbed5058675b47432/conanfile.py#L564), you can see the workaround I used:
> 
> ```
>         lflags = env_build.link_flags
>         if self.settings.os == "Macos":
>             lflags.append("-headerpad_max_install_names")
> ```
> 
> I want to upstream the change but it doesn't make much sense on its own if it can't be tested.
> 
> So I've pushed a test first to see if it fails. If it does, I plan on pushing the change above that fixes the test, otherwise I'll keep the workaround recipe in the company org.
> 
> We can also have a wider discussion in a separate conan issue: should all dylibs built by conan recipes be checked in the same way? Not being able to change rpaths is a rather limiting defect, it means I can't distribute conan-built libraries that exhibit this behaviour and must rely on DYLD_LIBRARY_PATH. A really bad idea on modern macos systems.

What don't you add `-headerpad_max_install_names` to `LDFLAGS` of your profile and build from source. I 'm not sure that's the task of conan-center.

**Comment by rockdreamer** [comment]
> What don't you add `-headerpad_max_install_names` to `LDFLAGS` of your profile and build from source. I 'm not sure that's the task of conan-center.

I hope you'll excuse me for desiring a more authoritative answer than that :)

The way I see this is that I've found a shortcoming with the product of a recipe, provided a test case that is failing and now adding a patch to hopefully fix the problem. Unless a conan developer steps in and declares/documents the products of conan-center-index as not fit for reuse, I don't see why making them usable for what I consider a valid case is 'not the task of conan-center'. By adding the test before the fix, I'm trying to make sure the issue exists in the recipe and not in my infrastructure/builds and reduce the administrative burden for the conan team and volunteers as much as possible.

If there's an alternate take on what conan and conan-center is, I'd like to know about it because I've invested a lot of time in and with it already!

**Comment by SpaceIm** [comment]
For sure, this flag is important to be able to set custom RPATH afterwards if you want to relocate shared libs outside of conan tree. But if this flag is added to openssl recipe, it should be added to all recipes, so it would place a huge burden on conan-center.

**Comment by rockdreamer** [comment]
> For sure, this flag is important to be able to set custom RPATH afterwards if you want to relocate shared libs outside of conan tree. But if this flag is added to openssl recipe, it should be added to all recipes, so it would place a huge burden on conan-center.

I totally understand the will to have consistency and the dread at the thought of checking all packages in conan-center index! 🤯 

However, openssl is the only inconsistent one for me! It is the only recipe where setting a custom rpath afterwards fails for me out of about [70-ish](https://github.com/ccdc-opensource?q=conan-&type=all&language=&sort=) packages we use. I think this is caused by some little difference in the openssl build system.

Hence why I'm purposefully proposing a recipe change and not a generic solution. Sometimes a local change can help create consistency!
If this change helps surface the need for rpath-alterable recipes, all the better! That can then be addressed separately, prioritised, candidate solutions for solving this generically proposed.

**Comment by rockdreamer** [comment]
A look at the logs shows that this breaks cross-compilation. The build is trying to create test executables in x86_64 mode

**Comment by SpaceIm** [comment]
It seems that boost also suffer of this issue: https://github.com/conan-io/conan-center-index/pull/13892

**Pull request closed without merging**
