### PR TITLE
gstreamer: bump dependencies + few build machine logic in build requirements + relocatable shared libs on macOS

### PR DESCRIPTION
**Pull request by SpaceIm**
- bump dependencies and use `<host_version>` for glib in build requirements
- test build machine instead of host machine for win/flex logic in build requirements
- relocatable shared libs on macOS

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by franramirez688 — DISMISSED** [review]

**Review by valgur — APPROVED** [review]

**Comment by RubenRBS** [comment]
retriggering v2, the logs are unclear as to what went wrong

**Comment by SpaceIm** [comment]
> retriggering v2, the logs are unclear as to what went wrong

@RubenRBS @danimtb Do you know what's wrong? There is no v2 log.

**Comment by danimtb** [comment]
> > retriggering v2, the logs are unclear as to what went wrong
> 
> @RubenRBS @danimtb Do you know what's wrong? There is no v2 log displayed by bot, but I can see v2 logs in https://c3i.jfrog.io/artifactory/misc-v2/logs/pr/20071/ (and it seems to build fine).

Indeed, I can see some timeouts there. Let me check it further. Thanks for the ping!

**Comment by SpaceIm** [comment]
@danimtb https://github.com/conan-io/conan-center-index/pull/20994 doesn't seem to help

**Review by jwillikers — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Review by franramirez688 — APPROVED** [review]

**Pull request merged**
