### PR TITLE
vdpau: add package_type

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jwillikers — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Comment by SpaceIm** [comment]
@danimtb @RubenRBS @uilianries @prince-chrismc what's wrong here? I had this message twice already, and afterwards `continuous-integration/jenkins/pr-merge ` turns to red silently while it was green and PR should have been merged.

**Comment by uilianries** [comment]
@SpaceIm Jenkins triggers again when executing the automatic merge and finding that this PR parent commit is different from the master commit, like, some new commit has been merged to master, in middle of your PR and is affecting your PR too. Indeed, now always it's correct, and it should be improved, there is an internal issue noticing it and we tracked some more information related to other cases. The thing is, fixing it, actually would need to re-implement the way use execute out git diff, and it requires caution as we could break CCI badly. Anyway, it's a bad known case, but not abandoned. I just retriggered your PR now, thanks for pinging!

**Review by uilianries — APPROVED** [review]

**Comment by SpaceIm** [comment]
Still the same issue :s

**Review by danimtb — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by SpaceIm** [comment]
Would it be possible to merge this one manually please?

**Comment by SpaceIm** [comment]
If you don't want that this PR runs forever in c3i, I think it's a good idea to manually merge this one.

**Comment by SpaceIm** [comment]
So you don't want to manually merge?

**Pull request merged**
