### PR TITLE
paho-mqtt-cpp: Add support for version 1.3.2

### PR DESCRIPTION
**Pull request by camm73**
Specify library name and version:  **paho-mqtt-cpp/1.3.2**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
Hello @camm73 ! Thank you for your suggestion. Could you please elaborate if you really need all these three versions? We usually only add the latest version available.

**Comment by camm73** [comment]
Hey @uilianries. I only need 1.3.2. Just figured I'd add the others since they were missing, but I can remove 1.3.0 and 1.3.1 if that is preferred

**Comment by uilianries** [comment]
> Hey @uilianries. I only need 1.3.2. Just figured I'd add the others since they were missing, but I can remove 1.3.0 and 1.3.1 if that is preferred

Yes please, let's add only 1.3.2 for now. In case anyone needs another version, we can add in the future.

**Comment by camm73** [comment]
Sounds good. PR was updated yesterday to only include v1.3.2

**Comment by camm73** [comment]
Looks like the Conan V2 builds are broken for a different version than the one I'm modifying here. Should that be opened as a separate issue?

**Comment by uilianries** [comment]
@camm73 I just rebased your PR right now. We merged the PR #21360 with some important changes that should fix your current error. The CI is running right now, so no action needed from your side 😸

**Review by uilianries — APPROVED** [review]
LGTM

**Review by toge — APPROVED** [review]

**Pull request merged**
