### PR TITLE
Allow to set ENABLE_HARU and WT_RASTERIMAGE_IMPLEMENTATION

### PR DESCRIPTION
**Pull request by ViktarHasiul231862**
Right now original Wt recipe doesn't allow to set two CMake flags, that I need to set in order to properly build Wt for my project.
WT_RASTERIMAGE_IMPLEMENTATION can not be set at all and ENABLE_HARU is always false: 
tc.variables["ENABLE_HARU"] = False

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi @ViktarHasiul231862 thanks a lot for your contribution. In order for the PR to be mergeable, please remember to write in the [access request issue](https://github.com/conan-io/conan-center-index/issues/4) :)

**Comment by Nekto89** [comment]
you'll also need to add libharu to requirements

**Comment by ViktarHasiul231862** [comment]
> you'll also need to add libharu to requirements

**Comment by ViktarHasiul231862** [comment]
Yes, good point, thank you. Libharu was added to requirements.

**Review by danimtb — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Pull request merged**
