### PR TITLE
stb: add new version cci.20240531, remove old versions

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **stb/cci.20240531**

#### Motivation
cci.20240531 has stb image resize 2.0.7.

#### Details
https://github.com/nothings/stb/blob/master/stb_image_resize2.h#L331-L334

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by AbrilRBS — COMMENTED** [review]
I think we can remove pre-2021 (Or 2022?) versions fine here, and clean up some of the recipe :)

**Comment by AbrilRBS** [comment]
We're having some issues in our CI - Jenkins seems to not be behaving itself. I've restarted the build but it might fail again until we have a chance to fix the infra issues tomorrow :)

**Review by perseoGI — APPROVED** [review]
Thanks for the cleanup!

**Review by AbrilRBS — APPROVED** [review]
Thanks!

**Pull request merged**
