### PR TITLE
Bump simfil to 0.2.1

### PR DESCRIPTION
**Pull request by josephbirkner**
### Summary
Changes to recipe:  **simfil/0.2.1**

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Review by RubenRBS — COMMENTED** [review]
Hi @josephbirkner thanks a lot for taking the time to keep the library up-to-date in CCI, we appreciate it :)

Seeing [the diff](https://github.com/Klebert-Engineering/simfil/compare/v0.1.3...v0.2.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR40), Conan likes to handle `CMAKE_POSITION_INDEPENDENT_CODE` by itself. Could we patch that line out so Conan has prioprity over its value? Thanks!

**Comment by josephbirkner** [comment]
> Hi @josephbirkner thanks a lot for taking the time to keep the library up-to-date in CCI, we appreciate it :)
> 
> Seeing [the diff](https://github.com/Klebert-Engineering/simfil/compare/v0.1.3...v0.2.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR40), Conan likes to handle `CMAKE_POSITION_INDEPENDENT_CODE` by itself. Could we patch that line out so Conan has prioprity over its value? Thanks!

Done, thanks for taking a look!

**Comment by josephbirkner** [comment]
Closed in favor of https://github.com/conan-io/conan-center-index/pull/24393 by @johannes-wolf since he has approved access.

**Comment by jcar87** [comment]
> Closed in favor of #24393 by @johannes-wolf since he has approved access.

thanks @josephbirkner  - have launched the job for that one, since it's otherwise under maintenance.
just today we are granting ourselves the ability to manually approve runs for PRs from "unauthorised" users, once we verify the changelog, so hopefully this will be less burdensome for all in the future. thanks!

**Pull request closed without merging**
