### PR TITLE
boost: use clang-win toolset when compiler=Visual Studio and compiler.toolset=ClangCL

### LINKED ISSUE #4727: [package] boost/1.75.0: Builds under the "msvc" toolset instead of "clang-win" when "ClangCL" toolset is specified with Visual Studio
### Package and Environment Details
  * Package Name/Version: **boost/1.75.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2019 v16.8.6/Clang v11.0.1**
  * Conan version: **Conan version 1.33.1**
  * Python version: **Python 3.9.2**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.toolset=ClangCL
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
I've found that using clang directly as a compiler on windows is very hit and miss with regard to what packages will actually build successfully, and I've had much more success using Visual Studio with the toolset set to ClangCL as seen in the above profile. However when building boost with this profile, the recipe selects "msvc" as the toolset to use for building which results in ``cl.exe`` being invoked instead of ``clang-cl.exe``.

``conan install boost/1.75.0@ -r conan-center -pr vs-clang`` can be used with a common conan installation to reproduce the behavior, where profile ``vs-clang`` equals the aforementioned profile.

It's unlikely that building under the "msvc" toolset will ever be the intent of a user using the above profile and so I'd suggest the behavior be changed to select the "win-clang" toolset when conan specifies the compiler toolset as ClangCL in conjunction with the Visual Studio compiler.

The current behavior is caused by the branch on line 1054 of conanfile.py (seen below) being eagerly taken when Visual Studio is the compiler specified by conan.
```python
        if self._is_msvc: # <-- branch always followed when compiler given by conan is "Visual Studio"
            return "msvc"
        elif self.settings.os == "Windows" and self.settings.compiler == "clang": # <-- ideally this branch should be followed when compiler.toolset is "ClangCL"
            return "clang-win"
```
I've had success with building using the "clang-win" toolset on the above profile by changing the first branch to read the following, but it feels like a very dirty solution considering that the next branch still exists and serves a similar purpose.
```python
        if self._is_msvc:
            return "clang-win" if self.settings.compiler.toolset == "ClangCL" else "msvc"
```

</details>

### PR DESCRIPTION
**Pull request by IanE9**
Specify library name and version:  **boost/1.75.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

fixes #4727

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]
https://github.com/conan-io/docs/pull/1784/files#diff-a315defbfc1c66ead66d806583c37c07352168535ac8bda4ab94d80cb0b38f64R46

https://github.com/conan-io/conan/pull/5705

https://github.com/conan-io/conan/issues/1839

**Comment by IanE9** [comment]
I'm unsure why the bot build under version 1.73.0 failed. The logs available to me are not enlightening either. I'd appreciate it if someone would take a look at this.

**Comment by prince-chrismc** [comment]
projects like boost take a lot of resource to build... which means sometimes things break

You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁

**Comment by prince-chrismc** [comment]
Let's call the infra team.... @danimtb @jgsogo this PR seems to be failing unexpectedly, if you have a chance please take a peak

**Comment by jgsogo** [comment]
Oooops! This is indeed an unfortunate consequence of the _"zero packages"_ situation. All packages were already generated in previous builds (same commit, several builds) and we are not building them again (in the table they appear as `UPSTREAM`):

https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/4749/8/boost/1.71.0//summary.json

The check (right now) is counting the number of packages it **will** generate and fail if there aren't any... we need to take into account these packages we are not going to generate because they were already generated 😓 😓 😓

**Comment by prince-chrismc** [comment]
🤯 

Thanks for the explanation, it will help identify the problem in other PRs

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]

**Pull request merged**
