### PR TITLE
brunsli: allow shared brotli dependency

### PR DESCRIPTION
**Pull request by valgur**

### CODE REVIEW

**Comment by valgur** [comment]
The project itself hard-codes the builds to be static, but I patched around that in the original PR and forgot to re-enable it in the recipe.

**Review by jwillikers — APPROVED** [review]

**Comment by valgur** [comment]
@RubenRBS Ping.

**Review by ericLemanissier — APPROVED** [review]

**Review by AbrilRBS — APPROVED** [review]

**Comment by AbrilRBS** [comment]
My main fear with this is that we could become maintainers of "using shared brotli" if upstream does not really wants to support that - I'm initially in favour, but let me quickly double check with the team, sorry for the delay!

**Comment by jcar87** [comment]
Seems like the upstream project allows shared since version 1.1.0: https://github.com/google/brotli/commit/641bec0e30bea648b3da1cd90fc6b44deb429f71 
(unsure how that correlates with the conan center index).

in general please add context to the PR description when removing these checks - they are (usually) there for a very valid reason, and without additional context we don't have information to determine whether we risk bringing back old problems or not.

**Pull request merged**
