### PR TITLE
Add assimp 5.4.3

### PR DESCRIPTION
**Pull request by EstebanDugueperoux2**
### Summary
Changes to recipe:  **assimp/5.4.3**

#### Motivation
Add the latest release

### CODE REVIEW

**Review by AbrilRBS — COMMENTED** [review]
We'll want to disable `ASSIMP_BUILD_USE_CCACHE` as it's ON by default, thanks!

**Comment by EstebanDugueperoux2** [comment]
Hi @AbrilRBS ok I have pushed another commit to disable ccache and enable short_paths.

**Review by AbrilRBS — APPROVED** [review]

**Review by ErniGH — APPROVED** [review]
LGTM

**Comment by EstebanDugueperoux2** [comment]
Thanks @AbrilRBS  and @ErniGH, also need to review on https://github.com/conan-io/conan-center-index/pull/25437

**Pull request merged**
