### PR TITLE
ffmpeg: Add av1 library support

### PR DESCRIPTION
**Pull request by sjlamerton**
Specify library name and version:  **ffmpeg/***

This picks up the work started by @sorny92 in https://github.com/conan-io/conan-center-index/pull/17094 to add support for the various av1 encoding and decoding libraries to ffmpeg. 

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by sorny92** [comment]
@sjlamerton Force-push is frown upon in this repo when the PR is set as ready to review. Better to put it on draft as it otherwise triggers some internal blah blah that I don't remember which annoys the maintainers 😄

**Comment by sorny92** [comment]
OH yes, pulseaudio. There's also an open PR that updates it as that error appeared:
https://github.com/conan-io/conan-center-index/pull/17219

**Review by MartinDelille — APPROVED** [review]

**Comment by sjlamerton** [comment]
@franramirez688 Anything I can do to help unblock this PR?

**Comment by franramirez688** [comment]
> @franramirez688 Anything I can do to help unblock this PR?

Hi @sjlamerton,

So sorry for replying too late. Let me update the branch to check if it's still failing with the same errors just in case.
Let's move this forward 💪

**Review by franramirez688 — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Pull request merged**
