### PR TITLE
add flac/1.3.3

### PR DESCRIPTION
**Pull request by intelligide**
Specify library name and version:  **flac/1.3.3**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Would this error be caused by library link order ? Can it be solved by specifying `self.cpp_info.libs = ['flac++', 'flac']` ?

**Comment by danimtb** [comment]
@intelligide where does the CMakeLists.txt come from? Why is it needed instead of using the original one or the original build method?

**Comment by uilianries** [comment]
@danimtb It's pretty similar from https://github.com/microsoft/vcpkg/blob/master/ports/libflac/CMakeLists.txt

**Comment by danimtb** [comment]
If that is the case, please include a header inside the CMakeLists.txt with something similar to this https://github.com/conan-io/conan-center-index/blob/master/recipes/mpfr/all/CMakeLists.txt#L1L25

**Comment by Croydon** [comment]
We don't need a custom CMakeLists.txt anymore.

1.3.3 has added CMake support

**Comment by danimtb** [comment]
@intelligide this PR has been open for a while, please address the points commented above or it will be closed in the following weeks. Thank you

**Comment by intelligide** [comment]
See #577

**Pull request closed without merging**
