### PR TITLE
simde: supports all platforms

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **simde/0.7.6**

Simde supports all platforms.
https://github.com/conan-io/conan-center-index/pull/18087#pullrequestreview-1501929198
I removed `validate()` method.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
@mr-c
I create another PR to improve simde recipe.

> Will the full test suite be run in CI?
You asked this question in a previous PR, could you tell us why?

In my opinion, the test suite for quality checks should be run in the official (upstream) repository, and CI for conan-cent-index should be run to check the recipe deployed correctly.

**Review by RubenRBS — APPROVED** [review]
Yaaay!

**Comment by RubenRBS** [comment]
I'm checking one infa thing with this PR, re-launching the build :)

**Review by czoido — APPROVED** [review]

**Comment by mr-c** [comment]
Thank you very much @toge  (and hello from Shodoshima Island, Kagawa where I'm at the [Japan BioHackathon 2023](https://2023.biohackathon.org/)!)

**Comment by mr-c** [comment]
> @mr-c I create another PR to improve simde recipe.
> 
> > Will the full test suite be run in CI?
> > You asked this question in a previous PR, could you tell us why?
> 
> In my opinion, the test suite for quality checks should be run in the official (upstream) repository, and CI for conan-cent-index should be run to check the recipe deployed correctly.

Yes, we run many many tests there. In other packaging systems (Debian, Conda, etc.. ) we still run the tests as they might adopt a newer compiler or patch their compiler in way that affects SIMDe. The extra testing helps quickly identify issues before they affect users.

It would be a bonus to do also test SIMDe in Conan as well, but it is not required.

Again, thank you!

**Pull request merged**
