### PR TITLE
package the zug libarary

### PR DESCRIPTION
**Pull request by BlueSolei**
Library:  **zug/0.0.1**

This library implements a fundamental concept from the Functional Programming paradigm.
FP is getting a lot of traction these days and is implemented across languages.
This library gives the C++ developer tools like Python's standard [itertools](https://docs.python.org/3/library/itertools.html) library, in a very performant impl.

The library author didn't set a version yet, so I put version 0.0.1 for now (discussed [here](https://github.com/arximboldi/zug/issues/12))

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
I've never ever heard about that `__declspec(selectany)` 🤔

**Comment by BlueSolei** [comment]
@SSE4 
Q: how do I version a package which its library doesn't have a version?
For now, I just put 0.0.1 :-|

**Comment by uilianries** [comment]
@BlueSolei Please, read https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases

**Comment by uilianries** [comment]
@BlueSolei Please, consider https://github.com/BlueSolei/conan-center-index/pull/2

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
