### PR TITLE
Add mold 2.0.0

### PR DESCRIPTION
**Pull request by fschoenm**
Specify library name and version:  **mold/2.0.0**

Essentially a version bump. mold 2.0.0 has been relicensed from AGPL to MIT (see [Release Notes for mold 2.0.0](https://github.com/rui314/mold/releases/tag/v2.0.0)), which is why I moved the old _all_ folder to _1.x.x_ and created a new _all_ folder that essentially only changed the `license` attribute. I hope that's the correct approach.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by fschoenm** [comment]
Can anybody advise how to solve the CI issue? Seems like some package is missing. In the #conan Slack channel I was told that somebody from the team has to run a build for missing packages?

**Comment by fschoenm** [comment]
@mgehre-amd IMO I didn't change anything there. On the slack channel somebody told me I have to wait for the team to help with that but I don't know what to do with this issue.

**Comment by valgur** [comment]
The `onetbb` issue is a recurrent one (https://github.com/conan-io/conan-center-index/pull/19229#issuecomment-1700522804) and @uilianries is looking into it, it seems.

The #18848 PR should help with any Conan v1 issues in the mold v1 recipe, once it gets merged.

**Review by uilianries — CHANGES_REQUESTED** [review]
@fschoenm Thank you for your contribution, good catch with the license change! Please, let's keep it simpler:

- Keep everything in the same recipe, there is no big change that justify such duplication.
- You can change the license according the version, it's something already used in CCI: https://github.com/conan-io/conan-center-index/blob/master/recipes/jfalcou-eve/all/conanfile.py#L41

**Comment by fschoenm** [comment]
@uilianries Thanks for the pointer, I didn't know that is possible. Maybe could be added to the contribution documentation (or maybe I just didn't see it) :)

**Comment by uilianries** [comment]
@fschoenm changing a recipe is something rare, but indeed it deserves be documented. I'll open a PR soon.

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — DISMISSED** [review]
NICE!

**Comment by fschoenm** [comment]
Is there a problem with the CI system? It says something about an unexpected error.

**Comment by uilianries** [comment]
@fschoenm not exactly, but right the build with Conan 1.x is still running, see the yellow circle in the status. The Conan 2.x build failed due a missing dependency:

>    ERROR: Missing binary: onetbb/2021.3.0:d7a9f73b4f7a501a35ebea3234d4801bf5740350

I started an internal CI build job to generate that missing package. Sorry about this.

The full result should be available as soon Conan 1.x finishes its job, so the CI bot will post the result.

**Review by jwillikers — APPROVED** [review]

**Comment by fschoenm** [comment]
> > ERROR: Missing binary: onetbb/2021.3.0:d7a9f73b4f7a501a35ebea3234d4801bf5740350

@uilianries 
It's the same problem for weeks now. Do you think you can help me fix it? I don't know what I'd have to do :(

**Comment by uilianries** [comment]
@fschoenm I just checked OneTBB recipe and there is a bug in terms of its implementation. I opened the PR https://github.com/conan-io/conan-center-index/pull/20786 fixing it. After merging that PR, yours will be working. Sorry for the delay.

**Comment by fschoenm** [comment]
@uilianries Do I need to trigger a rebuild or is there some way you can start it manually?

**Comment by jwillikers** [comment]
@fschoenm Updating your branch from master should trigger a new build.

**Comment by jwillikers** [comment]
@uilianries Might have to manually build the required variation of the `onetbb` package. He'll probably manually retrigger the CI for you when that's done.

**Review by jwillikers — APPROVED** [review]

**Comment by fschoenm** [comment]
@uilianries Unfortunately, it still didn't work.

I saw that there's a _onetbb_ package depending on _hwloc/2.9.Z_ on conancenter:
```
fbd41063c30b49345892a94c8747c6efed28b489
  info
    settings
      arch: x86_64
      build_type: Release
      compiler: gcc
      compiler.cppstd: 17
      compiler.libcxx: libstdc++11
      compiler.version: 11
      os: Linux
    options
      shared: True
      tbbbind: True
      tbbmalloc: True
      tbbproxy: True
    requires
      hwloc/2.9.Z
```

But the build requires _onetbb_ depending on _hwloc/2.9.3_:
```
onetbb/2021.3.0: WARN: Can't find a 'onetbb/2021.3.0' package binary 'd7a9f73b4f7a501a35ebea3234d4801bf5740350' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
shared=True
tbbbind=True
tbbmalloc=True
tbbproxy=True
[requires]
hwloc/2.9.3#30511a65bbe6044dab2139ab73cbbe2c:f651771e3392d8c689d4fdd4b39be363dfe184d3
```

I'm not really sure what it means. I think it has something to do with `full_mode` vs `minor_mode` but I'm unclear how these are determined.

**Comment by uilianries** [comment]
There was problem related to the OneTBB and its supported package IDs, but I created a PR fixing it: https://github.com/conan-io/conan-center-index/pull/20786

I just started the PR again. Let's if it works now.

**Review by jwillikers — APPROVED** [review]

**Comment by fschoenm** [comment]
@uilianries Sorry but that's no fix at all. It doesn't change the fact, that the _onetbb_ package required for _mold_ needs hwloc/2.9.3 instead of hwloc/2.9.Z.

> There was problem related to the OneTBB and its supported package IDs, but I created a PR fixing it: #20786
> 
> I just started the PR again. Let's if it works now.

**Comment by SpaceIm** [comment]
Here is a possible explanation: https://github.com/conan-io/conan/issues/15040#issuecomment-1790753531

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/20897 should avoid missing package id for this case. It may lead to other issues related to missing packages in downstream recipes.

**Comment by SpaceIm** [comment]
You have to wait a little bit after merge of a PR (not just 3 min), before new packages can be available.

**Review by uilianries — COMMENTED** [review]
Looking good, asking @franramirez688 for an extra review.

**Review by franramirez688 — APPROVED** [review]

**Review by jwillikers — APPROVED** [review]

**Comment by fschoenm** [comment]
@uilianries Anything missing here?

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
