### PR TITLE
Flann/support embedded lz4

### LINKED ISSUE #4969: [package] flann/1.9.1: Add option to not remove embedded lz4
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **flann/1.9.1**

This is more a feature request but wasn't sure the best place to put it. 

The existing flann/1.9.1 recipe strips out the embedded lz4 code and adds it as an external dependency. When building pcl 1.9.1 with the provided cmake files this leads to a linking error since it can't find lz4/doesn't link against the external lz4. I'd like to add an option to have the consumer choose if the flann recipe should remove the embedded lz4 code or not, which will make it easier for us to build pcl 1.9.1, with minimal changes to the pcl 1.9.1 provided CMakeLists.txt.

I already have some proposed changes and will create a PR.

### PR DESCRIPTION
**Pull request by nichmj01**
Specify library name and version:  **flann/1.9.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Fixes #4969

### CODE REVIEW

**Comment by SpaceIm** [comment]
If the issue in PCL build comes from a lack of robustness of its build system files, those files should be fixed instead of introducing vendoring in flann recipe.

**Comment by SSE4** [comment]
@SpaceIm I don't get it, IMO it should be able to link with lz4, no matter where is it coming from (sub-directory, conan or system library). as long as lz4 provides all the API functions needed, it shouldn't be a concern.
the only way it fail if embedded lz4 contains some modifications (e.g. new API functions or changed signatures), then it's another story.

**Comment by SpaceIm** [comment]
I didn't dig into PCL build files, but I guess it uses the bad old way to link with dependencies lib files directly instead of using an abstraction like flann CMake imported target or pkgconfig, asssuming that flann can't have dependencies itself.

**Comment by nichmj01** [comment]
I'm not sure this is vendoring (which I'm interpreting to mean adding changes/options to support a subset of downstream consumers). The issue appeared because I was trying to compile PCL but ultimately the issue, imo, is that this recipe changes the default behavior of the code as released. flann v1.9.1 by default embeds a version of lz4 so if I download the archive this recipe points to and and build it manually I'll get lz4 embedded. It seems odd to have the conan recipe produce something different than what the original sources produce?

To be fair, the current master branch of flann has removed the embedded lz4 and now points to an external lz4 but that isn't the version this recipe points to. There also hasn't been an official release since 2016 despite there being multiple commits to master.

**Comment by SSE4** [comment]
my personal opinion libraries using embedded sources are offering disservice. that might look neat at first glance, however, they are troubling:
- easy to violate ODR if two or more libraries provide the copies of LZ4 (potentially different)
- harder to switch version of LZ4
- need to understand were LZ4 sources modified somehow, or not

debian also suggests the same policy: https://wiki.debian.org/EmbeddedCopies

**Comment by nichmj01** [comment]
I think that's a fair and valid critique and don't disagree with it on it's face. The question to me is: should the recipe modify the way in which the source as released behaves? 

To be clear, I have no allegiances either way. I'm just a consumer of flann, PCL, and conan. If the decision is that the recipe as currently written is the preferred/recommended method and a consumer needs to handle lz4 not being embedded when using this recipe, then I can live with it. I've already cloned the recipe to produce what I needed and using the original recipe with the modifications to PCL necessary or using my custom recipe is fine with me. My goal was to see if adding an option to get the original behavior would be useful.

I will say that as a relative conan newbie, getting this recipe to work out of the box was more difficult that I would expect/hope and required either a deeper understanding of conan to create a custom recipe or digging into the PCL build files more than I would like (there's a lot of cmake understanding that needs to exist to look at the PCL build). I suspect that if any of my junior engineers, who have less conan and cmake experience than I do, had been trying to get this to work we would have settled for building flann from source locally and stopped our attempts to use conan at this time.

**Review by Arya128-ux — APPROVED** [review]

**Review by Arya128-ux — APPROVED** [review]

**Pull request closed without merging**
