### PR TITLE
libnghttp2: add version 1.55.0, update dependencies, remove older versions

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **libnghttp2/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]
Love this, thanks a lot! :)

**Comment by RubenRBS** [comment]
Opps, quick question. Did you make sure that none of the removed versions is currently a requirement on any of the CCI recipes? They wouldn't stop working, as the binaries themselves will still be there, but it would be nice to know

**Comment by toge** [comment]
@RubenRBS 
Yes, I checked those.
I think only libcurl requires libnghttp2, and libcurl is kept to update latest libnghttp2.

**Comment by RubenRBS** [comment]
Thanks 🫶

**Review by czoido — APPROVED** [review]

**Pull request merged**
