### PR TITLE
lunasvg: add version 2.4.1

### PR DESCRIPTION
**Pull request by toge**
### Summary
Changes to recipe:  **lunasvg/2.4.1**

#### Motivation
There is a new feature in 2.4.1.

#### Details
https://github.com/sammycage/lunasvg/compare/v2.4.0...v2.4.1

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

### CODE REVIEW

**Comment by toge** [comment]
@ErniGH 
Only pr-merge tasks are failed.
Could you check these tasks?

**Comment by ErniGH** [comment]
@toge It seemed like a small error in the ci. I have already relaunched it 🚀

**Comment by toge** [comment]
@ErniGH 
Thanks!

**Review by ErniGH — APPROVED** [review]
Thanks for your effort!

**Review by valgur — APPROVED** [review]

**Pull request merged**
