### PR TITLE
fontconfig: remove symlinks

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **fontconfig/2.13.91**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Just to be clear, without this change Conan Center Index fails to upload the package to the repo, as explained https://github.com/conan-io/conan-center-index/pull/1762#issuecomment-638014760 by @jgsogo, so the situation is currently that we have fontconfig in conan-center-index github, but not on conan-center remote.

**Comment by jgsogo** [comment]
It has already fixed in the main job, `fontconfig` is in Conan Center (https://conan.io/center/fontconfig/2.13.91/).

I totally believe that we shouldn't package symlinks that point outside the package (https://github.com/conan-io/hooks/issues/202), I don't know if more complex recipes like `msys2` or some other tools rely on files in the Windows system or something like that... I hope not 😄 

So, are all this symlinks pointing outside `fontconfig` package? Why is `fontconfig` adding all of them by default? Are these symlinks to files found in the system while building?  Are we missing features because these files are no longer in the package?

**Comment by ericLemanissier** [comment]
they are pointing inside the package folder. They have absolute path though:
```
/home/eric/.conan/data/fontconfig/2.13.91/_/_/package/4fb4ea7ea368e5d0c3aab0da2460e23f629d5393/
├── bin
│   ├── etc
│   │   └── fonts
│   │       ├── conf.d
│   │       │   ├── 10-hinting-slight.conf -> /home/eric/.conan/data/fontconfig/2.13.91/_/_/package/4fb4ea7ea368e5d0c3aab0da2460e23f629d5393/bin/share/fontconfig/conf.avail/10-hinting-slight.conf
```

**Comment by jgsogo** [comment]
I'll have a look to Conan sources, I would expect it to make this symlinks relative to the package folder (before adding them to tarfile)

**Pull request merged**
