### PR TITLE
Add cfitsio/3.480

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **cfitsio/3.480**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@SpaceIm why the 3.470 and 3.480 version numbers, when upstream project names them 3.47 and 3.48 ?
cf https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt

**Comment by SSE4** [comment]
> @SpaceIm why the 3.470 and 3.480 version numbers, when upstream project names them 3.47 and 3.48 ? cf https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt

it was merged more than 3 years ago, are you sure you're commenting to the right PR?

**Comment by ericLemanissier** [comment]
yes

**Comment by SpaceIm** [comment]
In 3.x series, there were 3 digits for minor version, despite what you can see in changelog (cfitsio was also quite inconsistent while mentionning these versions). All other packages managers have followed this version scheme for cfitsio.

**Pull request merged**
