### PR TITLE
bump libxml2 dependencies

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **libxml2/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
Version bump didn't require a review before, when did it changed?...

**Comment by AndreyMlashkin** [comment]
Please approve
@madebr
@SpaceIm
@ericLemanissier
@prince-chrismc
@Croydon
@intelligide
@theirix
@gocarlos
@mathbunnyru
@ericriff
@toge
@MartinDelille
@dmn-star

**Review by mathbunnyru — APPROVED** [review]

**Comment by AndreyMlashkin** [comment]
@jgsogo @prince-chrismc, why conan-bot didn't maked this PR with "Bump dependencies" label?

**Comment by YevhenServetnykSD** [comment]
Will you plan to bump version of `libiconv` in boost?

**Comment by AndreyMlashkin** [comment]
No, but you can create a PR ;)

**Comment by prince-chrismc** [comment]
Please be gentle with tagging everyone 😉 The build service got stuck and when it was opened backup everything got rolling so just be patient.

We have been consistently getting 150+ PRs a week averaging 6 builds so the load is getting higher and the edges are starting to show 🙈

**Pull request merged**
