### PR TITLE
mingw: split windows and linux recipes

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **mingw-w64/***

there is no change at all in the recipe, just a separation of the 2 paths (linux and windows), which are 99% of the time different.

related to #8306

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by toge — APPROVED** [review]

**Review by AndreyMlashkin — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Comment by ericLemanissier** [comment]
Context: this recipe is more or less "dead" because there is no plan to put newer version on http://sourceforge.net/projects/mingw-w64/. I will make a new windows recipe based on https://github.com/niXman/mingw-builds when a new tag will be made (https://github.com/niXman/mingw-builds/issues/575)

**Comment by SSE4** [comment]
> Context: this recipe is more or less "dead" because there is no plan to put newer version on http://sourceforge.net/projects/mingw-w64/. I will make a new windows recipe based on https://github.com/niXman/mingw-builds when a new tag will be made ([niXman/mingw-builds#575](https://github.com/niXman/mingw-builds/issues/575))

this is kinda unfortunate. are these `niXman` binaries considered official? are they drop-in replacements for mingw-w64?

**Comment by ericLemanissier** [comment]
AFAIK, there are no "official" migw-w64 binaries.  But NiXman was already one of the contributors behind the `mingw-builds` binaries this recipe downloads from sourceforge

**Comment by SSE4** [comment]
> AFAIK, there are no "official" migw-w64 binaries. But NiXman was already one of the contributors behind the `mingw-builds` binaries this recipe downloads from sourceforge

at this point, I am not completely sure if it should be just `mingw` or `nixman-mingw` to distinguish distribution.
if it's the main source of truth, it's okay to name it just `mingw` to avoid unnecessary confusion for consumers.
but there are other distributions, like https://nuwen.net/mingw.html or one provided with MSYS. are they considered equal?

**Comment by ericLemanissier** [comment]
Just to confirm what I said above, there is a file named `build-info.txt` in existing `mingw-w64\8.1\_\_\package\***` and the file says `user    : nixman`.
You are right that the situation needs to be improved regarding the multiple versions of mingw. I don't know if one is better than the other, but there are (at least) all the following:

- all the ones on https://www.mingw-w64.org/downloads/ (including mingw-builds)
- https://nuwen.net/mingw.html 
- https://winlibs.com/
- https://osdn.net/projects/mingw/ which is rising from the ashes of https://mingw.osdn.io/ (mingw.org, which is now down)

I'll definitely submit the new recipe packaging https://github.com/niXman/mingw-builds as a new package (I prefer the project name `mingw-builds` instead of the name of the maintainer).
Regarding the existing `mingw-w64/8.1` windows version. Do you think it's worth moving it to a new package name ? I think we should deprecate it as soon as the mingw-builds recipe is up.

**Review by prince-chrismc — APPROVED** [review]

**Comment by ericLemanissier** [comment]
closing this one in favor of #8349

**Pull request closed without merging**
