### PR TITLE
Qt6: fix qt multimedia on linux

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **qt/6.***

Fix egl target name, and don't override gstreamer cmake module
Also, make egl and gstreamer requirements explicit

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Without this, qtmultimedia fails with
```
CMake Error at qtbase/cmake/QtTargetHelpers.cmake:168 (target_link_libraries):
  Target "Gui" links to:

    EGL::EGL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  qtbase/src/gui/CMakeLists.txt:436 (qt_internal_extend_target)


CMake Error at qtbase/cmake/QtTargetHelpers.cmake:168 (target_link_libraries):
  Target "QXcbEglIntegrationPlugin" links to:

    EGL::EGL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  qtbase/cmake/QtPluginHelpers.cmake:336 (qt_internal_extend_target)
  qtbase/src/plugins/platforms/xcb/gl_integrations/xcb_egl/CMakeLists.txt:10 (qt_internal_add_plugin)


CMake Error at qtbase/cmake/QtTargetHelpers.cmake:168 (target_link_libraries):
  Target "EglFSDeviceIntegrationPrivate" links to:

    EGL::EGL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  qtbase/cmake/QtModuleHelpers.cmake:599 (qt_internal_extend_target)
  qtbase/src/plugins/platforms/eglfs/CMakeLists.txt:24 (qt_internal_add_module)


CMake Error at qtbase/cmake/QtTargetHelpers.cmake:168 (target_link_libraries):
  Target "QEglFSIntegrationPlugin" links to:

    EGL::EGL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  qtbase/cmake/QtPluginHelpers.cmake:336 (qt_internal_extend_target)
  qtbase/src/plugins/platforms/eglfs/CMakeLists.txt:91 (qt_internal_add_plugin)


CMake Error at qtbase/cmake/QtTargetHelpers.cmake:168 (target_link_libraries):
  Target "QMinimalEglIntegrationPlugin" links to:

    EGL::EGL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  qtbase/cmake/QtPluginHelpers.cmake:336 (qt_internal_extend_target)
  qtbase/src/plugins/platforms/minimalegl/CMakeLists.txt:10 (qt_internal_add_plugin)


CMake Error at qtbase/cmake/QtTargetHelpers.cmake:168 (target_link_libraries):
  Target "QGstreamerMediaPlugin" links to:

    GStreamer::GStreamer

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  qtbase/cmake/QtPluginHelpers.cmake:336 (qt_internal_extend_target)
  qtmultimedia/src/plugins/multimedia/gstreamer/CMakeLists.txt:6 (qt_internal_add_plugin)

```

**Comment by ericLemanissier** [comment]
tested by @paulharris , the build passed

**Review by jwillikers — APPROVED** [review]

**Review by MartinDelille — APPROVED** [review]

**Comment by paulharris** [comment]
Note, there might be a problem with this recipe when some of the options are enabled.
Critically, qt:shared=True may not work with multimedia+gstreamer.

**Review by jwillikers — APPROVED** [review]

**Comment by paulharris** [comment]
For what its worth, I'd be happy to see this merged so we can move onto the next problem/PR.

**Review by paulharris — APPROVED** [review]

**Review by franramirez688 — APPROVED** [review]

**Pull request merged**
