### PR TITLE
glib: bump libiconv

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **glib/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jgsogo — DISMISSED** [review]

**Review by jgsogo — DISMISSED** [review]
Thanks for taking care of the linter errors! 🙌

**Comment by jgsogo** [comment]
Closing and open, might the CLA be with us (and also, trigger again CI, which has failed without message)

**Comment by ericLemanissier** [comment]
I tried to go to https://cla-assistant.io/conan-io/conan-center-index?pullRequest=11854 but it does not seem to refresh the status :/

**Comment by uilianries** [comment]
I believe is time to think about moving CLA assistant to a github action ...

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Review by toge — APPROVED** [review]

**Pull request merged**
