### PR TITLE
quill: QUILL_X86ARCH should be optional

### PR DESCRIPTION
**Pull request by odygrd**
`QUILL_X86ARCH` uses some specific instructions for cache line optimisations (prefetch, clflushop) that are not available in each architecture. It also requires the user to compile their executable by passing specific flags (march). This option won't be needed by the majority of the users. It also should be possible to disable it. The default should be `False` and we should let the user explicitly enable it.

Specify library name and version:  **quill/2.7.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by toge** [comment]
@odygrd 
Thank you for your PR.
CI seems to be stalled.
Please close PR, wait 10 sec and reopen PR.
CI will run again.

**Comment by toge** [comment]
@odygrd 
Sorry, CI seems to be stopped. We have to wait.

**Comment by odygrd** [comment]
how long is the maintenance expected to last ? :)

**Review by jwillikers — APPROVED** [review]

**Comment by odygrd** [comment]
@toge any update please when this can be merged? It is currently blocking some users from being able to compile

**Comment by jwillikers** [comment]
> @toge any update please when this can be merged? It is currently blocking some users from being able to compile

@odygrd Hopefully soon, the Conan 2.0.0 release has inundated the backlog of reviews as CI was stalled for some time. Now that this build is passing, it just needs one review from a Conan team member.

@prince-chrismc or @uilianries, could we get a quick review here for this small change? Thanks!

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
There were lots of surprises during the upgrade and then we rushed and needed to fix a few things... things are finally rolling should be back to normal for PRs (about 5-7 days)

This 3 weeks gap will destroy my graphs 😭

**Pull request merged**
