### PR TITLE
cpp-httplib: add 0.10.1 + modernize + drop maintenance of several versions

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Review by ericLemanissier — DISMISSED** [review]

**Comment by SpaceIm** [comment]
let's try https://github.com/yhirose/cpp-httplib/pull/689 in 0.7.7

**Comment by ericLemanissier** [comment]
We can probably keep only the last patch version of each minor version. v0.7.18 does not have this bug

**Comment by ericLemanissier** [comment]
Please consider removing all the non-last patch version of each minor version. These patches are not needed

**Comment by SpaceIm** [comment]
Yep, let's do that

**Review by ericLemanissier — DISMISSED** [review]
Much lighter to review, thanks!

**Review by madebr — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
