### PR TITLE
gtest: cleanup recipe to match upstream 1.12

### PR DESCRIPTION
**Pull request by prince-chrismc**
There were a bunch of weird stuff that's no longer support in recent version.

Some removed options were still being support oddly enough.

All the old versions were updated to 2.0 so dropping them here should not cause any problems.

```
 conan create all 1.12.1@ -o gtest:build_gmock=False
conan create all 1.12.1@ -o gtest:build_gmock=False -o gtest:no_main=True
conan create all 1.12.1@ -o gtest:shared=True
 ```

Specify library name and version:  **gtest/1.12**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by jgsogo — DISMISSED** [review]
I see `1.12` simplifies the recipe a little bit, nevertheless, maybe removing all the previous versions is a bit too much... but if noone complains I'm fine with it (and we can recover and build again older versions if needed).

**Comment by prince-chrismc** [comment]
At first I did not want to remove them but with the last PR all of the version will be 2.0 compatible.

Recipe is less clean than I hoped in the the diff, but overall 
image
i think it will be easier to maintain. From https://github.com/google/googletest/releases/tag/release-1.12.1

> This will be the last release to support C++11. Future releases will require at least C++14.

Adding back 1.11 is easy its just putting back the debug suffix in the libs. 1.10 is a lot of patches add C++98 and some settings. If they have not updated gtest in 3+ years than I bet they are not expecting updates here 🤞 support 4 different compiler sets would be complicated!

If you need an older version please @prince-chrismc 😄 I am sorry and will add back the version you need.

However, from their own words ... https://github.com/google/googletest/releases/tag/release-1.11.0

> We recommend building GoogleTest from the latest commit instead.

**Review by jgsogo — APPROVED** [review]
LGTM (See previous comment)

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
