### PR TITLE
openal: add version 1.21.0

### PR DESCRIPTION
**Pull request by madebr**
Generated and committed by [conan-center-bot](https://github.com/qchateau/conan-center-bot)

Specify library name and version:  **openal/1.21.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by madebr** [comment]
@qchateau 
The build fails on MSVC.
Is there a way I can push fixes?
I guess I'll have to bump openal in my own conan-center-index fork?

**Comment by intelligide** [comment]
OpenAL > 1.21 requires C++14. (https://github.com/kcat/openal-soft/blob/c0cbe602ce66481a822ba16856052a47154f5cc5/ChangeLog#L3)

**Comment by qchateau** [comment]
> @qchateau
> The build fails on MSVC.
> Is there a way I can push fixes?
> I guess I'll have to bump openal in my own conan-center-index fork?

That's the idea. Then either recreate the PR (or edit to change the source repo if you can ?) or create a PR in my fork targeting the source branch of this PR

**Comment by madebr** [comment]
I can only change the target branch, not the source branch.
I'm going to redo this pr from my fork to have a faster turn around.

**Review by ericLemanissier — APPROVED** [review]

**Pull request closed without merging**
