### PR TITLE
boost-1.78 fix cmake auto configuration for windows

### PR DESCRIPTION
**Pull request by pgeler**
closes: #8550 
Specify library name and version:  boost-1.78

cmake auto configuration failing with boost-1.78:
```
1> [CMake] 	"toolset": "-{}".format(self._toolset_tag),
1> [CMake] while calling '_toolset_tag', line 1294
1> [CMake] 	if self.settings.compiler in ("msvc", "Visual Studio"):
1> [CMake] 	ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value.
1> [CMake] Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc']
```

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
> Specify library name and version: boost-1.78
> 
> cmake auto configuration failing with boost-1.78:
> 
> ```
> 1> [CMake] 	"toolset": "-{}".format(self._toolset_tag),
> 1> [CMake] while calling '_toolset_tag', line 1294
> 1> [CMake] 	if self.settings.compiler in ("msvc", "Visual Studio"):
> 1> [CMake] 	ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value.
> 1> [CMake] Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc']
> ```
> 
>     * [ ]  I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
> 
>     * [ ]  I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
> 
>     * [ ]  I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
> 
>     * [ ]  I've tried at least one configuration locally with the
>       [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Your `settings.yml` is outdated.

**Comment by DDoSolitary** [comment]
I encountered the same problem, but I think swapping the strings isn't a real fix. It only works if your compiler is `Visual Studio`.

> Your settings.yml is outdated.

@SpaceIm I don't think it's a good idea to require an up-to-date settings.yml file. The recipe is breaking existing projects running on a somewhat old version of Conan. Such breaking change without any warning is really annoying.

I would suggest using a similar approach as conan-io/conan#9954, i.e. reading the compiler value with `self.settings.get_safe('compiler')` before comparision.

**Comment by ericLemanissier** [comment]
It's not going to happen, cf https://github.com/conan-io/conan-center-index/blob/master/docs/consuming_recipes.md

**Comment by SpaceIm** [comment]
The last revision of boost recipe already requires conan 1.33.0, and `msvc` has been added to `settings.yml` in conan 1.33.0 https://github.com/conan-io/conan/releases/tag/1.33.0

**Comment by pgeler** [comment]
> The last revision of boost recipe already requires conan 1.33.0:
> 
> https://github.com/conan-io/conan-center-index/blob/19dc4ac03bceb2dbad3aec0668e6a6d46c56560f/recipes/boost/all/conanfile.py#L19
> 
> 
> And `msvc` has been added to `settings.yml` in conan 1.33.0 https://github.com/conan-io/conan/releases/tag/1.33.0

the problem in the way conan upgrade the configurations, changes in seettings.yml especially when it was all the way "default" is a painful to push through entire organization especially when people using it time to time...

**Comment by SpaceIm** [comment]
`if self.settings.compiler in ("msvc", "Visual Studio")` raises `ConanException` when msvc is not in settings, it's a conan client issue I believe.

**Comment by pgeler** [comment]
> `self.settings.compiler in ("msvc", "Visual Studio")` raises `ConanException` when msvc is not in `settings.yml`, it's a conan client issue I believe, not a recipe issue. We should be able to compare `self.settings.compiler` with any string, it should never raise (return False instead). Indeed, recipes have no control on consumers `settings.yml`.
> 
> Does it work with `str(self.settings.compiler) in ("msvc", "Visual Studio")`?
> 
> (also related to #6155)

yes, it does work, in fact that was original solution. but then found this ("order") hack in other receipts

**Comment by pgeler** [comment]
I think it will be more straight forward to change to condition to self.settings.get_safe("compiler"): @SpaceIm, @SSE4 thoughts?

**Comment by ericLemanissier** [comment]
get_safe does not help here. Compiler always exists

**Comment by pgeler** [comment]
> self.settings.get_safe("compiler")

it does help

well, another way I may think of is to use local variable in condition compiler == 'vc'

**Comment by SpaceIm** [comment]
`str(self.settings.compiler)` seems to be the most robust approach.

**Comment by pgeler** [comment]
> `str(self.settings.compiler)` seems to be the most robust approach.

✔️  sold

**Review by ericLemanissier — COMMENTED** [review]
I don't like this change because it introduces a weakness to typos. It's necessary to update settings.yml for other reasons anyway. If user really want to use an outdated settings.yml, they can use older revisions of recipes.

**Comment by pgeler** [comment]
> I don't like this change because it introduces a weakness to typos. It's necessary to update settings.yml for other reasons anyway. If user really want to use an outdated settings.yml, they can use older revisions of recipes.

outdated settings.yml was not intentional, the very first time I actually noticed it even exists was @SpaceIm comment above. The main problem I view is in strategy conan uses for upgrading it. But I'm confident that the strategy was thoughtful and don't want to dealt with changing it... I'm just trying to simplify upgrade for my organization and other people who is not to investigate each issue with every update. Otherwise the package manager does not remove, but add complexity to their day by day work...

**Review by SpaceIm — APPROVED** [review]

**Comment by prince-chrismc** [comment]
> simplify upgrade for my organization and other people who is not to investigate each issue with every update.

Former Conan enterprise user, what worked best for us was using the https://docs.conan.io/en/latest/reference/commands/consumer/config.html install option with a repo with our settings (but we needed custom settings and had to semi-automatic upgrade)

There's a super awesome feature

> The `conan config install` can be periodically executed, before any command, when `config_install_interval` is configured in `conan.conf`. Conan runs it based on `config_install.json`, including the timestamp of the last change.

Hopefully this helps

**Review by SSE4 — APPROVED** [review]

**Comment by prince-chrismc** [comment]
You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁

**Review by uilianries — APPROVED** [review]

**Pull request merged**
