### PR TITLE
harfbuzz: bump dependencies

### PR DESCRIPTION
**Pull request by db4**
**harfbuzz/6.0.0**

### CODE REVIEW

**Comment by SpaceIm** [comment]
```
======== Installing packages ========
ERROR: Missing binary: glib/2.76.1:2a450722d3413cb2b1ccb88e085925540376fae3

glib/2.76.1: WARN: Can't find a 'glib/2.76.1' package binary '2a450722d3413cb2b1ccb88e085925540376fae3' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.version=13
os=Macos
[options]
shared=True
with_elf=True
[requires]
bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d:12b38c622ab94fbabd118653840a0f5f7c93b72d
libelf/0.8.13#2a27c51d562810af629795ac4aa85666:d62dff20d86436b9c58ddc0162499d197be9de1e
libffi/3.4.3#ab23056d668dc13482a811f215f7be3e:d62dff20d86436b9c58ddc0162499d197be9de1e
libgettext/0.21#f4b0a8d73ecaa9f481fe4688b79fb04c:4fdcdcec781b3aa9d725a1acafacc666a2729855
libiconv/1.17#fa54397801cd96911a8294bc5fc76335:d62dff20d86436b9c58ddc0162499d197be9de1e
pcre2/10.42#2079a0447f9652dffcbbf1eb73ae2d4e:8d0721e12496b6316bae8bfbb2be21c784190a36
zlib/1.2.13#13c96f538b52e1600c40b88994de240f:d62dff20d86436b9c58ddc0162499d197be9de1e

ERROR: Missing prebuilt package for 'glib/2.76.1'
Check the available packages using 'conan list glib/2.76.1:* -r=remote'
or try to build locally from sources using the '--build=glib/2.76.1' argument
```

@danimtb @uilianries @RubenRBS @jcar87 I think it's the same issue already pointed out in https://github.com/conan-io/conan-center-index/pull/16339#issuecomment-1500905491

**Comment by jcar87** [comment]
> ```
> ======== Installing packages ========
> ERROR: Missing binary: glib/2.76.1:2a450722d3413cb2b1ccb88e085925540376fae3
> 
> glib/2.76.1: WARN: Can't find a 'glib/2.76.1' package binary '2a450722d3413cb2b1ccb88e085925540376fae3' for the configuration:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=apple-clang
> compiler.version=13
> os=Macos
> [options]
> shared=True
> with_elf=True
> [requires]
> bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d:12b38c622ab94fbabd118653840a0f5f7c93b72d
> libelf/0.8.13#2a27c51d562810af629795ac4aa85666:d62dff20d86436b9c58ddc0162499d197be9de1e
> libffi/3.4.3#ab23056d668dc13482a811f215f7be3e:d62dff20d86436b9c58ddc0162499d197be9de1e
> libgettext/0.21#f4b0a8d73ecaa9f481fe4688b79fb04c:4fdcdcec781b3aa9d725a1acafacc666a2729855
> libiconv/1.17#fa54397801cd96911a8294bc5fc76335:d62dff20d86436b9c58ddc0162499d197be9de1e
> pcre2/10.42#2079a0447f9652dffcbbf1eb73ae2d4e:8d0721e12496b6316bae8bfbb2be21c784190a36
> zlib/1.2.13#13c96f538b52e1600c40b88994de240f:d62dff20d86436b9c58ddc0162499d197be9de1e
> 
> ERROR: Missing prebuilt package for 'glib/2.76.1'
> Check the available packages using 'conan list glib/2.76.1:* -r=remote'
> or try to build locally from sources using the '--build=glib/2.76.1' argument
> ```
> 
> @danimtb @uilianries @RubenRBS @jcar87 I think it's the same issue already pointed out in [#16339 (comment)](https://github.com/conan-io/conan-center-index/pull/16339#issuecomment-1500905491)

Currently being generated!

**Comment by db4** [comment]
@jcar87: still missing dependencies (`Can't find a 'glib/2.76.1' package binary`), now in both Conan v1 and v2 pipelines.

**Review by ericLemanissier — DISMISSED** [review]

**Review by prince-chrismc — DISMISSED** [review]

**Comment by SpaceIm** [comment]
I think there is a misunderstanding here about the reason of this missing glib package. The fix is not to re-generate binaries, they are already there. The fix is to enforce "all static" in build profile.

**Review by prince-chrismc — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by jcar87** [comment]
Placeholder comment

**Comment by jcar87** [comment]
For the last build of the v1 pipeline, this error:
```
ERROR: Missing binary: glib/2.76.2:35a2987206414fc1968e948dd2b71196d6dcb604
glib/2.76.2: WARN: Can't find a 'glib/2.76.2' package for the specified settings, options and dependencies:
```

I can see that binary with that package_id exists just fine - chances are I triggered the PR too quickly before the packages were promoted after the glib merge.

**Review by ericLemanissier — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Review by jcar87 — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@db4 would you be ok to sign the new CLA at https://github.com/conan-io/conan-center-index/pull/17046#issuecomment-1553073785 so that this PR can be merged ? thanks !

**Comment by db4** [comment]
> @db4 would you be ok to sign the new CLA at [#17046 (comment)](https://github.com/conan-io/conan-center-index/pull/17046#issuecomment-1553073785) so that this PR can be merged ? thanks !

Done

**Pull request merged**
