### PR TITLE
cocoyaxi: conan v2 support & update tarball url

### PR DESCRIPTION
**Pull request by SpaceIm**
project has been renamed, it's coost now: https://github.com/idealvin/coost

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Should we not deprecate the old one and publish under the new name?

**Review by jgsogo — APPROVED** [review]

**Review by jgsogo — CHANGES_REQUESTED** [review]
Read last comment, waiting for final word about renaming

**Comment by prince-chrismc** [comment]
https://github.com/idealvin/coost/issues/247#issuecomment-1228659870 🤞

**Comment by idealvin** [comment]
> /cc @idealvin

@SpaceIm  Thanks. The new version is not released yet. We'll release coost v3.0.0 in the following days.

**Comment by SpaceIm** [comment]
@idealvin Actually it was a question about project name. Should cocoyaxi be deprecated in favor of a new recipe called coost?

**Comment by prince-chrismc** [comment]
Yes! https://github.com/idealvin/coost/issues/247#issuecomment-1232863979

**Comment by idealvin** [comment]
A new version v3.0.0 was released [here](https://github.com/idealvin/coost/releases/tag/v3.0.0).

**Review by danimtb — APPROVED** [review]

**Review by jgsogo — APPROVED** [review]
After adding `coost`, we should mark this recipe as deprecated, right?

**Comment by SpaceIm** [comment]
> After adding `coost`, we should mark this recipe as deprecated, right?

correct

**Pull request merged**
