### PR TITLE
Follow-ups from #6462: minor refactors in nlohmann_json

### PR DESCRIPTION
**Pull request by cbachhuber**
Specify library name and version:  **nlohmann_json/all**

In #6462, we discussed a couple of minor issues with nlohmann_json. This is the corresponding follow-up.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Ok for the modernization, but I don't understand what are the minor issues fixed here.

**Review by SSE4 — APPROVED** [review]

**Comment by madebr** [comment]
> > In #6462, we discussed a couple of minor issues with nlohmann_json. This is the corresponding follow-up.
> 
> Ok for the modernization (you can also replace `tools.cross_building(self.settings)` by `tools.cross_building(self)` in test package), but I don't understand what are the minor issues fixed here.

I suppose he hinted at [this discussion](https://github.com/conan-io/conan-center-index/pull/6462#discussion_r675529006)

**Comment by SpaceIm** [comment]
Ok, not a fix, it works whatever the order. Let's say it's a modernization & convention PR 😛

**Comment by cbachhuber** [comment]
Agreed, this is only convention and modernization. Sorry for misleading you with too strong wording!

**Review by SpaceIm — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Pull request merged**
