### PR TITLE
gflags: use system_libs

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **gflags/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Comment by Croydon** [comment]
Bots to the rescue!

**Review by SSE4 — APPROVED** [review]

**Comment by prince-chrismc** [comment]
> Bots to the rescue!

Can someone make me a bot too please?

I'd love a cyborg to do my dishes 👀 "Hey [google/alexa], do my dishes!"

**Review by prince-chrismc — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
> I'd love a cyborg to do my dishes eyes "Hey [google/alexa], do my dishes!"

Nowadays you can easily integrate a voice service with a coffeemaker at least

**Comment by prince-chrismc** [comment]
> Nowadays you can easily integrate a voice service with a coffeemaker at least

I actually do have one 🤣

**Comment by Croydon** [comment]
I have now a smart LED, I could use it as a warning signal if CI fails 💡 🤔

**Comment by ericLemanissier** [comment]
you'd better have it light up when CI passes, that would save a lot of energy !

**Comment by prince-chrismc** [comment]
You guys are an absolute delight to collaborate with! Thank you for a good laugh

**Pull request merged**
