### PR TITLE
qt6: fix resources object files location

### PR DESCRIPTION
**Pull request by ericLemanissier**
Specify library name and version:  **qt/6.7.1**

fixes https://github.com/conan-io/conan-center-index/issues/24131

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9282882504/attempts/1)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9282882504/attempts/2)

**Comment by ericLemanissier** [comment]
The error can be seen in:
- https://c3i.jfrog.io/c3i/misc/logs/pr/24150/1-linux-gcc-legacy/qt/6.7.1/c6f9811941e2715cb33edb4bc2b1e217a1780d85-test.txt
- https://github.com/ericLemanissier/proof-of-conan/actions/runs/9282882504/job/25546810097#step:8:11269
- https://github.com/ericLemanissier/proof-of-conan/actions/runs/9282882504/job/25546816038#step:8:10499

It happens when linking to qtWidgets or qtGui:
```
/usr/bin/ld: cannot find /home/conan/workspace/prod-v1/bsr/50590/eacde/.conan/data/qt/6.7.1/_/_/package/c6f9811941e2715cb33edb4bc2b1e217a1780d85/lib/objects-Release/Widgets_resources_2/.qt/rcc: file format not recognized
/usr/bin/ld: cannot find /home/conan/workspace/prod-v1/bsr/50590/eacde/.conan/data/qt/6.7.1/_/_/package/c6f9811941e2715cb33edb4bc2b1e217a1780d85/lib/objects-Release/Widgets_resources_4/.qt/rcc: file format not recognized
/usr/bin/ld: cannot find /home/conan/workspace/prod-v1/bsr/50590/eacde/.conan/data/qt/6.7.1/_/_/package/c6f9811941e2715cb33edb4bc2b1e217a1780d85/lib/objects-Release/Widgets_resources_1/.qt/rcc: file format not recognized
/usr/bin/ld: cannot find /home/conan/workspace/prod-v1/bsr/50590/eacde/.conan/data/qt/6.7.1/_/_/package/c6f9811941e2715cb33edb4bc2b1e217a1780d85/lib/objects-Release/Widgets_resources_3/.qt/rcc: file format not recognized
/usr/bin/ld: cannot find /home/conan/workspace/prod-v1/bsr/50590/eacde/.conan/data/qt/6.7.1/_/_/package/c6f9811941e2715cb33edb4bc2b1e217a1780d85/lib/objects-Release/Gui_resources_2/.qt/rcc: file format not recognized
/usr/bin/ld: cannot find /home/conan/workspace/prod-v1/bsr/50590/eacde/.conan/data/qt/6.7.1/_/_/package/c6f9811941e2715cb33edb4bc2b1e217a1780d85/lib/objects-Release/Gui_resources_1/.qt/rcc: file format not recognized
```
In qt < 6.7.0 these resources were in `lib/objects-Release/Gui_resources_1/.rcc` but with 6.7.1 they are in `lib/objects-Release/Gui_resources_1/.qt/rcc`. Notice the added folder level. This PR transitions to using `os.walk` in order to get all files recursively instead of statically fixing the nesting level by calling `os.listdir`

**Review by RubenRBS — COMMENTED** [review]
Thanks a lot! Minor question before approving to udnerstand a bit more why we didn't catch this earlier :)

**Comment by ericLemanissier** [comment]
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/9285685416/attempts/1)

**Review by RubenRBS — APPROVED** [review]

**Review by toge — APPROVED** [review]

**Pull request merged**
