### PR TITLE
benchmark: fix `_cmake_new_enough()` for conan v2

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by dpronin** [comment]
I'm beginning to migrate from conan-1.59 to conan-2.0 and have had generator like 'cmake_find_package' that has worked properly. Now this package with conan-2.0 does not work with new generators like "CMakeToolchain", "CMakeDeps" because when I run `conan install` it does not generate any Findbenchmark.cmake file like it used to. Who is able to give an answer why the migration is so painful in terms of working with find_package not having been migrated properly for this package? Thank you

**Comment by jcar87** [comment]
> I'm beginning to migrate from conan-1.59 to conan-2.0 and have had the generator 'cmake_find_package' that has worked properly. Now this package with conan-2.0 does not work with new generators like "CMakeToolchain", "CMakeDeps" because when I run `conan install` it does not generate any Findbenchmark.cmake file, but it used to. Who is able to give an answer why the migration is so painful in terms of working with find_package not having been migrated properly for this package? Thank you

Hi @dpronin  - the `CMakeDeps` generator will generate `benchmark-config.cmake`, which should satisfy a `find_package(benchmark)` inside a CMake script. This works in tandem with the `CMakeToolchain` generator, which creates a file `conan_toolchain.cmake` that you need to pass to Cmake when first configuring the build.

You can read more about this workflow:
* https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html

**Comment by dpronin** [comment]
Hi @jcar87 . If you look at zlib recipe and benchmark recipe you will find them different. I suspect that method **package_info** lacks some definitions and content to provide a correct information to generate **find_package**-related files, doesn't it?

**Comment by SpaceIm** [comment]
CMakeDeps doesn't generate `Findbenchmark.cmake` file for `benchmark` recipe because it doesn't make sense since there is no such file upstream.
By default `CMakeDeps` generates config files only.
Recipes packaging libraries listed in https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html#find-modules are exception and we indeed force `CMakeDeps` to also generate a Find module files for these ones, that's all.

**Comment by dpronin** [comment]
@SpaceIm look, it used to work with cmake_find_package generator. Now I do not have a clue how to get it to work back. Could you please provide an example how I am supposed to use conan-v2.0 with current version of recipe to make it work without having to rewrite my 'CMakeLists.txt' where 'find_package(benchmark REQUIRED)' is called?
Thank you

**Comment by dpronin** [comment]
@SpaceIm ok, I have finally sorted it out and got to work generation of benchmark-config.cmake. But, to make my project link against `libbenchmark.a` library I have had to switch from `def build_requirements(self)` to `def requirements(self)`, [see](https://github.com/dpronin/memcpy/commit/504679ef0dee5e01d32a781d3535e366e0112401)

So, initially I made code like:

```
    ...

    def build_requirements(self):
        self.tool_requires("benchmark/[~1.7]")

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
        deps = CMakeDeps(self)
        deps.build_context_activated = ["benchmark"]
        deps.generate()

    ...
```

And when I am linking the binary the compiler cannot see any real libraries like `libbenchmark.a` and fails to link due to many benchmark's symbols being undefined

**Review by jcar87 — APPROVED** [review]

**Pull request merged**
