### PR TITLE
add include paths to lzo/2.10

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **lzo/2.10**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
This is needed to avoid patching libvncserver sources

**Comment by AndreyMlashkin** [comment]
@SSE4 @uilianries @ericLemanissier @feragon

**Review by ericLemanissier — CHANGES_REQUESTED** [review]
`include` is already in the default includedirs

**Comment by AndreyMlashkin** [comment]
Hmmm, you're right.

**Pull request closed without merging**
