### PR TITLE
ffmpeg: PKG_CONFIG_PATH not set in case of build with msvc

### PR DESCRIPTION
**Pull request by elvisdukaj**
Specify library name and version:  **ffmpeg**

This PR tries to solve the issue(s) in:

- https://github.com/conan-io/conan-center-index/issues/23309
- https://github.com/conan-io/conan-center-index/issues/21694

In particular when build with `msvc` the ffmpeg recipe has a branch on using `AutotoolsDeps` as they actually are broken when the compiler is `msvc`. A better solution would probably be fix the conan `AutotoolsDeps` to better support `msvc` instead of the many workarounds we have. Indeed other packages would benefit from this (`coin-utils`, `ffmpeg`, `gf-complete`,  `libgettext`, `ncurses`, `xapian-core`).

Please note that simply `prepend_path` doesn't work if the `PKG_CONFIG_PATH` was empty before, see [issue 21694](https://github.com/conan-io/conan-center-index/issues/21694) for the detailed reason

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by elvisdukaj** [comment]
If https://github.com/conan-io/conan/pull/16016 is approved this PR is not needed.

**Comment by elvisdukaj** [comment]
After deeper investigation the issue wasn't in https://github.com/conan-io/conan/pull/16016 but is in `pkgconfig` that is unable to split the environment variable correctly on msys2. As a patch we can override the PKG_CONFIG_PATH environment variable to don't contain multiple paths.

**Comment by elvisdukaj** [comment]
Building ffmpeg with the `pkgconf` package coming from `msys2` works out of the box. I modified `msys2` to don't remove `pkgcong` and removed the `build_requirment` from msys2.

The problem is with `pkgconf` on Windows and how paths are handled.

I think having `pkgconf` built on Windows with Visual C++ (no msys2) and used from `msys2` environment cannot work.

**Comment by paulharris** [comment]
Any progress on this?   I'm still using eric's original patched version of this...

**Comment by elvisdukaj** [comment]
I made a lot of trouble shooting with this https://github.com/conan-io/conan/pull/1601. I had the feeling that the `PKG_CONFIG_PATH` was not properly set. Indeed, trying to print the environment variable from the conanfile, this was empty. But I failed to reproduce this situation with a test.
I stopped there, but I think it's worth continuing investigating.

**Comment by jcar87** [comment]
We're unable to reproduce this issue, more details here: https://github.com/conan-io/conan-center-index/issues/23309#issuecomment-2213803996

We're trying to understand what is failing where, but so far can't get the configure step to fail on windows with msvc.

**Comment by elvisdukaj** [comment]
@jcar87 I added all my observation here: https://github.com/conan-io/conan-center-index/issues/23309

**Pull request closed without merging**
