### PR TITLE
spirv-headers: add new versions, remove old ones

### PR DESCRIPTION
**Pull request by valgur**
Kept only versions from the past year.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Thanks! did you check if any of the removed ones is in use by any other recipe in CCI?

**Comment by valgur** [comment]
> Thanks! did you check if any of the removed ones is in use by any other recipe in CCI?

Yes. It's only used transitively via `spirv-tools` in `diligent-core` and `shaderc`. `spirv-tools` uses 1.3.224.0, which can be safely bumped to 1.3.224.1. And as for `shaderc`, the motivation for it was to bump its dependencies in the first place for https://github.com/conan-io/conan-center-index/pull/18807/files#diff-8081cb7851a6cf6ba55b29260e409058efb299d48cc9b8c21d0fd5e46480f805R46-R58

**Review by jwillikers — APPROVED** [review]

**Comment by valgur** [comment]
Closing in favor of #20838.

**Comment by SpaceIm** [comment]
Sorry, didn't see there was an old PR already.

**Pull request closed without merging**
