### PR TITLE
boost: no quotes around compiler (os.environ["CXX"])

### LINKED ISSUE #2996: [package] boost/1.73.0: boost can not be crosscompiled when CXX contains sysroot
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.73.0**
  * Operating System+version: **Ubuntu 19.10**
  * Compiler+version: **GCC 9**
  * Docker image: **conanio/gcc9-armv7hf**
  * Conan version: **Conan version 1.28.1**
  * Python version: **Python 3.7.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=armv7hf
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]

[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
notice: found boost-build.jam at /home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/boost-build.jam
notice: loading B2 from /home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src
notice: Searching '/etc' '/home/conan' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src' '/home/conan/.conan/data/b2/4.2.0/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/b2_src/src/kernel' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/kernel' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/util' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/build' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/tools' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/contrib' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/.' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in '/etc' '/home/conan' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src' '/home/conan/.conan/data/b2/4.2.0/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/b2_src/src/kernel' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/kernel' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/util' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/build' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/tools' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/contrib' '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/.'.
notice: Loading explicitly specified user configuration file:
    /home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/user-config.jam
notice: Searching '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from '/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build'.
notice: [zlib] Using pre-installed library
notice: [zlib] Condition
notice: [bzip2] Using pre-installed library
notice: [bzip2] Condition
warning: toolset gcc initialization:
warning: can not find user-provided command 'arm-linux-gnueabihf-g++-9  --sysroot=/whatever'
warning: initialized from /home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/user-config.jam:5
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/tools/gcc.jam:164: in gcc.init from module gcc
error: toolset gcc initialization:
error: provided command 'arm-linux-gnueabihf-g++-9  --sysroot=<sysroot>' not found
error: initialized from /home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/user-config.jam:5
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/build/toolset.jam:44: in toolset.using from module toolset
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/build/project.jam:1104: in using from module project-rules
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/user-config.jam:5: in modules.load from module user-config
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/build-system.jam:255: in load-config from module build-system
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/build-system.jam:449: in load-configuration-files from module build-system
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/build-system.jam:607: in load from module build-system
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/kernel/modules.jam:295: in import from module modules
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/home/conan/.conan/data/boost/1.73.0/_/_/source/source_subfolder/boost-build.jam:17: in module scope from module

```
</details>

NOTE: this did work with boost 1.72.0

### PR DESCRIPTION
**Pull request by madebr**
Specify library name and version:  **boost/all**

Fixes #2996

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SSE4** [comment]
does it work with compiler wrappers (e.g. ccache, distcc)?

**Comment by madebr** [comment]
> does it work with compiler wrappers (e.g. ccache, distcc)?

No, it didn't.
removing the quotes obviates the need for `shlex.split`.

**Comment by SSE4** [comment]
okay, this might be tricky to get it working for all cases. I remember, for windows, quotes were needed, e.g. if CC points to the path with spaces, like `C:\Program Files\LLVM\bin\clang-cl.exe`.
that might be a situation fixing one thing, but breaking another, so please check it carefully.

**Comment by jgsogo** [comment]
I see one potential problem: what if the path to CXX contains blanks?

**Comment by madebr** [comment]
> okay, this might be tricky to get it working for all cases. I remember, for windows, quotes were needed, e.g. if CC points to the path with spaces, like `C:\Program Files\LLVM\bin\clang-cl.exe`.
> that might be a situation fixing one thing, but breaking another, so please check it carefully.

There is no way to distinguish between a space in a path and spaces for arguments.
When there is a space in the compiler path, should the `CXX` environment variable contain double quotes?
Or is #2996 invalid and should `CXX` not contain any arguments and should they be put in `CXXFLAGS`/`CPPFLAGS`?

I've tested with the following (on Linux):
```
mkdir -p "/tmp/best compiler ever/compiler"
ln -s /usr/bin/g++ "/tmp/best compiler ever/compiler"
```
and putting `CXX=ccache "/tmp/best compiler ever/compiler" -fchar8_t -fpermissive` in my profile.

Building boost succeeds, but boost's test_package fails because cmake fails to recognize the compiler.

**Comment by SSE4** [comment]
`CXX` usually works for multiple arguments, e.g. things like `CXX=ccache g++` and `CXX=g++ -m32` work out of the box, and it's pretty common use-case.
for instance, on Mac, you always can escape spaces with slashes and don't use quotes: `CXX=/Library/Application\ Support/Android/ndk/bin/clang++` will work.
on other hand, on Windows, it's tricky, because there are different things involved:
1. command line passed to the shell (cmd.exe/bash) or function like `ShellExecute`. in that case shell-specific things like quotes work.
2. command line directly passed to the `CreateProcess`/`exec` function. this cannot handle shell-specific things, e.g. quotes, output redirection syntax, background syntax. probably, cmake works this way and doesn't like quotes in command line.
from the conan point of view, we don't know what's going to be done with `CXX` in the particular build system. puzzling...

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by intelligide — APPROVED** [review]

**Pull request merged**
