### PR TITLE
cmake: add version 3.22.3

### PR DESCRIPTION
**Pull request by ericLemanissier**
Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot)
Find more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)

Specify library name and version:  **cmake/3.22.3**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Comment by ericLemanissier** [comment]
this should have been tagged as a bump by the bot

**Comment by SSE4** [comment]
URL patter might be two different from the previous one? @uilianries 
```
    url: https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0.tar.gz
    url: "https://github.com/Kitware/CMake/archive/v3.22.3.tar.gz"
```

**Review by SSE4 — APPROVED** [review]

**Review by AndreyMlashkin — APPROVED** [review]

**Comment by uilianries** [comment]
> URL pattern might be two different from the previous one? @uilianries
> 
> ```
>     url: https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0.tar.gz
>     url: "https://github.com/Kitware/CMake/archive/v3.22.3.tar.gz"
> ```

Good catch! 

I checked both https://github.com/Kitware/CMake/releases/download/v3.22.3/cmake-3.22.3.tar.gz and https://github.com/Kitware/CMake/archive/v3.22.3.tar.gz. They have different checksum ...

Doing a deeper investigation, validating all files checksum, only one file is different:

```
diff CMake-v3.22.3/Source/CMakeVersion.cmake cmake-3.22.3/Source/CMakeVersion.cmake 
24c24
<   set(git_info [==[6e9eaf209da CMake 3.22.3]==])
---
>   set(git_info [==[6e9eaf209d CMake 3.22.3]==])
```

Basically, same thing both tar files.

**Review by Croydon — APPROVED** [review]
CMake is the one case, where I would like to have all versions, but lets merge this one first

**Review by Croydon — CHANGES_REQUESTED** [review]
This uses the automatically generated source archives from GitHub, not the official release downloads of the source code which we should use

It also uses an old URL pattern for that

https://github.com/Kitware/CMake/archive/v3.22.3.tar.gz

became 

https://github.com/Kitware/CMake/archive/refs/tags/v3.22.3.tar.gz

a while ago

**Review by prince-chrismc — APPROVED** [review]

**Comment by Croydon** [comment]
@prince-chrismc Please undo your approval if you are fast enough. We shouldn't use auto-generate archives of source code if there are official ones

**Review by prince-chrismc — CHANGES_REQUESTED** [review]
Block!

**Pull request closed without merging**
