### PR TITLE
lz4: use external xxhash

### PR DESCRIPTION
**Pull request by SpaceIm**
- lz4 is compiled with bundled xxhash source file. This PR removes xxhash files from lz4 source and injects external xxash.
- cache CMake configuration with functools.lru_cache
- modernize test package

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
It's a proposal, but I don't know if it's a good idea. If we go in this direction, zstd recipe should also use external xxhash.

**Comment by SSE4** [comment]
> It's a proposal, but I don't know if it's a good idea. If we go in this direction, zstd recipe should also use external xxhash.

it's always good idea, otherwise it's subject to ODR violation and all the consequences (e.g. crashes hard to debug)

**Comment by SpaceIm** [comment]
There might be side effects since it introduces a new dependency and therefore would change package id of lz4 and zstd, with consequences in recipes depending on lz4 & zstd. I think also that symbols of the bundled version are properly renamed/hidden. I've checked other package managers, and they keep bundled xxhash version if lz4 & zstd.

**Comment by SSE4** [comment]
> There might be side effects since it introduces a new dependency and therefore would change package id of lz4 and zstd, with consequences in recipes depending on lz4 & zstd. I think also that symbols of the bundled version are properly renamed/hidden. I've checked other package managers, and they keep bundled xxhash version in lz4 & zstd. xxhash, lz4 & zstd are developed by the same folks.

if they do special effort to rename symbols, it's fine

**Pull request closed without merging**
