### PR TITLE
bump ffmpeg dependencies

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **ffmpeg/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
@jgsogo @prince-chrismc 
is it an infrastructural problem?

**Comment by SSE4** [comment]
> @jgsogo @prince-chrismc is it an infrastructural problem?

I don't think so - the output is truncated (full at https://c3i.jfrog.io/c3i/misc/logs/pr/11824/1-linux-gcc/ffmpeg/4.4//7149c02942aed8b56c011116b58ddf0c9a84b5ba-build.txt), basically the error is:
```
ERROR: libpulse not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```
we need to capture `ffbuild/config.log` to see an actual error

**Comment by SSE4** [comment]
might be related to #11847

**Comment by AndreyMlashkin** [comment]
@jgsogo could you please retrigger this one?

**Comment by uilianries** [comment]
@AndreyMlashkin done, it has been re-triggered.

**Pull request merged**
