### PR TITLE
freetype: provide official CMake variables (uppercase) in cmake_find_package

### PR DESCRIPTION
**Pull request by SpaceIm**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by SpaceIm** [comment]
Freetype is interesting, because imported target in FindFreetype is different than the one in config file. I'm wondering how CMakeDeps will handle this case.

**Review by madebr — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by SpaceIm** [comment]
@uilianries @jgsogo What's wrong here? Always the same cryptic error:

```
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\conans\client\command.py", line 2164, in run
    method(args[0][1:])
  File "c:\python36\lib\site-packages\conans\client\command.py", line 307, in test
    lockfile=args.lockfile, profile_build=profile_build)
  File "c:\python36\lib\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "c:\python36\lib\site-packages\conans\client\conan_api.py", line 332, in test
    test_build_folder=test_build_folder, recorder=recorder)
  File "c:\python36\lib\site-packages\conans\client\cmd\test.py", line 38, in install_build_and_test
    recorder=recorder)
  File "c:\python36\lib\site-packages\conans\client\manager.py", line 59, in deps_install
    lockfile_node_id=lockfile_node_id)
  File "c:\python36\lib\site-packages\conans\client\graph\graph_manager.py", line 120, in load_graph
    apply_build_requires=apply_build_requires)
  File "c:\python36\lib\site-packages\conans\client\graph\graph_manager.py", line 255, in _resolve_graph
    graph_lock=graph_lock)
  File "c:\python36\lib\site-packages\conans\client\graph\graph_manager.py", line 365, in _load_graph
    apply_build_requires=apply_build_requires)
  File "c:\python36\lib\site-packages\conans\client\graph\graph_manager.py", line 286, in _recurse_build_requires
    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
  File "c:\python36\lib\site-packages\conans\client\graph\graph_binaries.py", line 389, in evaluate_graph
    self._evaluate_node(node, build_mode, update, remotes)
  File "c:\python36\lib\site-packages\conans\client\graph\graph_binaries.py", line 176, in _evaluate_node
    self._process_node(node, pref, build_mode, update, remotes)
  File "c:\python36\lib\site-packages\conans\client\graph\graph_binaries.py", line 242, in _process_node
    self._evaluate_cache_pkg(node, package_layout, pref, metadata, remote, remotes, update)
  File "c:\python36\lib\site-packages\conans\client\graph\graph_binaries.py", line 95, in _evaluate_cache_pkg
    assert node.prev, "PREV for %s is None: %s" % (str(pref), metadata.dumps())
AssertionError: PREV for brotli/1.0.9:a79a557254fabcb77849dd623fed97c9c5ab7651 is None: {"recipe": {"revision": "802b2457f7a7a509ed80e7e45adf960e", "remote": "conan-center", "properties": {}, "checksums": {"conan_export.tgz": {"md5": "79960f320ee43a2d3c147fbb29bac38a", "sha1": "136cb6fd2703572891d37c6e8dfc238a5e2c070b"}, "conanmanifest.txt": {"md5": "435b2c972b28d8dda25a06c081604061", "sha1": "e2318b845365c854bfb89a5866ffc51fc0cd357c"}, "conanfile.py": {"md5": "2e0ab9294327821a66c72a3050bd4af3", "sha1": "cc9dd63b1437ed11f6ebb833519637130065e717"}}}, "packages": {"a79a557254fabcb77849dd623fed97c9c5ab7651": {"revision": null, "recipe_revision": null, "remote": null, "properties": {}, "checksums": {}}}}

ERROR: PREV for brotli/1.0.9:a79a557254fabcb77849dd623fed97c9c5ab7651 is None: {"recipe": {"revision": "802b2457f7a7a509ed80e7e45adf960e", "remote": "conan-center", "properties": {}, "checksums": {"conan_export.tgz": {"md5": "79960f320ee43a2d3c147fbb29bac38a", "sha1": "136cb6fd2703572891d37c6e8dfc238a5e2c070b"}, "conanmanifest.txt": {"md5": "435b2c972b28d8dda25a06c081604061", "sha1": "e2318b845365c854bfb89a5866ffc51fc0cd357c"}, "conanfile.py": {"md5": "2e0ab9294327821a66c72a3050bd4af3", "sha1": "cc9dd63b1437ed11f6ebb833519637130065e717"}}}, "packages": {"a79a557254fabcb77849dd623fed97c9c5ab7651": {"revision": null, "recipe_revision": null, "remote": null, "properties": {}, "checksums": {}}}}
```

**Comment by jgsogo** [comment]
Not sure if you are opening/closing and you are bitten by this same thing: https://github.com/conan-io/conan-center-index/pull/6072#issuecomment-870607996

> Looks like it is a side effect of one configuration I've modified on our Jenkins 🤔  
>
> I want to run _branch indexing_ from time to time, so closed/merged PRs are discovered are their branches are removed (otherwise we would run out of space in our agents)... but every time branch-indexing runs it triggers _all_ the PRs again if something has been modified in `master` (we merge PRs everyday, so we they will be triggered always). 
>
> Jenkins has a configuration to not trigger these PRs again, but then it stops listening to other events like the close/open one. TBH, it is an event I really don't like, some people abuse it, but OTH it is very useful for contributors to trigger the pipeline again (we cannot monitor all the jobs all the time).
> 
> We could activate it again (and find a workaround for the branch-indexing), or we can find a workaround for this open/close _feature_. Please, @danimtb @SSE4 @uilianries , ideas? arguments? suggestions?

**Comment by SpaceIm** [comment]
@jgsogo, this PR suffered of several issues:

- odd errors about PREV of brotli
- lot of configurations were built correctly, and when I closed/opened, those same configurations failed with this PREV issue (I thought that CI was able to not build again successful configurations if there was not change).
- and at then end yes maybe the error you are talking about

**Comment by prince-chrismc** [comment]
Could community reviewers trigger CI? 😉

**Comment by SpaceIm** [comment]
waiting improvement in https://github.com/conan-io/hooks/pull/314

**Comment by jgsogo** [comment]
Hi! We added this hook here (https://github.com/conan-io/hooks/pull/314), and I was feeling like it was too strict. Probably it should take into account only the files listed in the `.gitattributes` which, in turn, means that we should hardcode the extensions of the files we are going to check.

cc/ @uilianries

**Comment by uilianries** [comment]
Hotfix on PR https://github.com/conan-io/hooks/pull/317

**Review by jgsogo — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Pull request merged**
