### PR TITLE
fix freetype cmake flags for dependencies

### PR DESCRIPTION
**Pull request by maddanio**
Specify library name and version:  freetype/all

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

this fixes cmake flags in the freetype recipe to enable/disable dependencies. also it forbids finding packages via pkgconfig if the dependency was not enabled

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @maddanio ! What's the exactly error that you are having without this change? Could you please post a log?

**Comment by maddanio** [comment]
see this section from the CMakeList.txt of freetype
```
# . Set the `FT_WITH_ZLIB', `FT_WITH_BZIP2', `FT_WITH_PNG', and
#   `FT_WITH_HARFBUZZ' CMake variables to `ON' to force using a dependency.
#   Leave a variable undefined (which is the default) to use the dependency
#   only if it is available.  Set `CMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=TRUE' to
#   disable a dependency completely (CMake package name, so `BZip2' instead of
#   `BZIP2'). Example:
#
#     cmake -DFT_WITH_ZLIB=ON -DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=TRUE [...]
```
so obviously the conanfile.py was missing the FT_ prefixes. also, and I noticed that as I was building for ios and disaling libpng (which does not build for my target, and I dont need it so I cant be bothered to fix that), it will run pkgconfig for libpng (as documented) and pick up a system one, which is obviously wrong and also not what was configured. so the right way is as the file already does for HarfBuzz.

**Comment by maddanio** [comment]
actually the deiff could me made slightly shorter by leaving out FT_...=FALSE, since its reduntant as per comment.

**Comment by maddanio** [comment]
so how does this get merged now?

**Comment by uilianries** [comment]
Just need to wait, someone with admin power will merge it.

**Pull request merged**
