### PR TITLE
test qt components

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Specify library name and version:  **qt/5.15.2**

I think, I am not an only one who would like to have a working example, demonstrating how to include different Qt modules in CMakeLists or *.pro file. test_package/ is a perfect place for it.

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
The test does not work for me:

[100%] Built target test_package
qt/5.15.2 (test package): Running test()
qt/5.15.2 (test package): Testing qmake
Resource content: "Hello World From Resource\n"
"Hello World!"
qt/5.15.2 (test package): Testing CMake_find_package_multi
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
ERROR: qt/5.15.2 (test package): Error in test() method, line 115
	self._test_with_cmake_find_package_multi()
while calling '_test_with_cmake_find_package_multi', line 109
	self.run(os.path.join("bin", "test_package"), run_environment=True)
	ConanException: Error 134 while executing bin/test_package


Does anyone have the same problem?

**Comment by AndreyMlashkin** [comment]
There is exactly the same problem in CI as I have locally

**Comment by ruilvo** [comment]
That probably means lack of deployment. Does this build Qt as a shared library? You can't use a Qt application before running [win/linux/mac]deployqt on it (that basically copies dlls over and creates files). It works magically on Qt Creator because it adds the Qt libs to path when you click the play button. 

Now with the PR of proper Qt5 components, if you want to know how to use it, you can read the official documentation...

**Comment by ericLemanissier** [comment]
Do you have the problem only when using qt as a static library (which is the default)? Can you please try to use [Q_IMPORT_PLUGIN](https://doc.qt.io/qt-5/qtplugin.html#Q_IMPORT_PLUGIN) ?

**Comment by ruilvo** [comment]
Yeah, as @ericLemanissier  said, this seems to be an issue with headless environments, and definitely lack of "deployment". Qt Applications aren't trivial to run.

**Comment by AndreyMlashkin** [comment]
I have removed a gui part, so an example should be able to run on a headless system.

**Comment by ruilvo** [comment]
We'll find out in a couple hours after this really have library rebuilds in the CI :)

**Comment by AndreyMlashkin** [comment]
I have tried to run macdeployqt with the old bincrafters recipe out of conanfile, but it didn't work on some reason for me.
If you have a working example of using it with conan installation, please share it.
Almost every user of this recipe will need it I think.

**Comment by ruilvo** [comment]
If you read the commit log, there was a patch explicitly for macdeploy Qt. I don't have a mac, sorry, so I can't give input.

**Comment by AndreyMlashkin** [comment]
For all interested, this code allows to create a runnable qt executable with all plugins for gui.
The only problem is that it fails on Linux because of symlinks, but still imports all needed files.

    def imports(self):
       self.copy("*.dll",           dst="bin", src="bin"    , keep_path=True)
       self.copy("*.dll",           dst="bin", src="plugins", keep_path=True)
       
       self.copy("*.dylib",         dst="bin", src="lib"    , keep_path=True)
       self.copy("*.dylib",         dst="bin", src="plugins", keep_path=True)
       
       self.copy("*.so",            dst="bin", src="lib"    , keep_path=True)
       self.copy("*.so",            dst="bin", src="plugins", keep_path=True)

I have reported this issue a while ago
https://github.com/conan-io/conan/issues/9084

**Comment by ruilvo** [comment]
Wouldn't run [win|mac|linux]deployqt be must better in this scenario?
This is an example of the code I've used before in Windows + CMake:
```cmake
  # On Windows, run windeployqt after building
  if(WIN32)
    # Run winddeployqt if it can be found
    find_program(
      WINDEPLOYQT_EXECUTABLE
      NAMES windeployqt
      HINTS ${QTDIR} ENV QTDIR
      PATH_SUFFIXES bin)
    add_custom_command(
      TARGET qt5_example
      POST_BUILD
      COMMAND ${WINDEPLOYQT_EXECUTABLE} $<TARGET_FILE:qt5_example>)
  endif()
```

**Comment by Renari** [comment]
> For all interested, this code allows to create a runnable qt executable with all plugins for gui.
> The only problem is that it fails on Linux because of symlinks, but still imports all needed files.
> 
> ```
> def imports(self):
>    self.copy("*.dll",           dst="bin", src="bin"    , keep_path=True)
>    self.copy("*.dll",           dst="bin", src="plugins", keep_path=True)
>    
>    self.copy("*.dylib",         dst="bin", src="lib"    , keep_path=True)
>    self.copy("*.dylib",         dst="bin", src="plugins", keep_path=True)
>    
>    self.copy("*.so",            dst="bin", src="lib"    , keep_path=True)
>    self.copy("*.so",            dst="bin", src="plugins", keep_path=True)
> ```
> 
> I have reported this issue a while ago
> [conan-io/conan#9084](https://github.com/conan-io/conan/issues/9084)

It fails because you copy the symlinks e.g. `mylibrary.so` but `mylibrary.so` is a symlink to `mylibrary.so.5.15.2` which does not get copied by the above commands, thus you end up with a broken symlink.

**Comment by AndreyMlashkin** [comment]
This code worked with bincrafters recipe:


       self.copy("*.so.*.*.*", dst="bin", src="lib", keep_path=True)
       self.copy("*.so", dst="bin", src="plugins", keep_path=True)

**Pull request closed without merging**
