### PR TITLE
Add libde265/1.0.9 recipe

### PR DESCRIPTION
**Pull request by theirix**
Specify library name and version:  **libde265/1.0.9**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by theirix** [comment]
Waiting for Conan 1.55.0 which should introduce `conan.tools.build.stdcpp_library`

**Comment by uilianries** [comment]
@theirix I marked as blocked to avoid new CI executions until we have 1.55

**Comment by theirix** [comment]
> @theirix I marked as blocked to avoid new CI executions until we have 1.55

Sorry, I was not clear. I meant it *could* benefit from 1.55 by removing the [deprecated line](https://github.com/theirix/conan-center-index/blob/libde265-1.0.9/recipes/libde265/all/conanfile.py#L5). Currently it will pass CI because it requires only 1.50.0.

I can refactor this and other recipes later, when 1.55 will land on the CI.

**Comment by theirix** [comment]
I meant 1.54.0, misread the git log.

**Review by jwillikers — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
can we not let this merge in and then circle back with a new PR?

**Pull request merged**
