### PR TITLE
openvino: set c++11 standard cmake feature

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
Specify library name and version:  **openvino/2023.1.0**

WA for this issue https://github.com/conan-io/conan/issues/10281

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Hi @jwillikers @SpaceIm @RubenRBS 
Please, have a look

**Review by jwillikers — APPROVED** [review]

**Review by uilianries — CHANGES_REQUESTED** [review]
Please, do not propagate the C++ standard down the graph.

The correct approach is using `compiler.cppstd` from your profile. And, in case not compatible, you still can use `check_min_cppstd` and `check_max_cppstd` to manage the package compatibility.

**Comment by ilya-lavrenov** [comment]
> Please, do not propagate the C++ standard down the graph.
> 
> The correct approach is using `compiler.cppstd` from your profile. And, in case not compatible, you still can use `check_min_cppstd` and `check_max_cppstd` to manage the package compatibility.

It does not work for Conan 1.x
Please, read discussion here https://github.com/conan-io/conan-center-index/pull/20774#discussion_r1373869641

**Comment by ilya-lavrenov** [comment]
Better to merge this PR https://github.com/conan-io/conan-center-index/pull/20782, which additionally removes explicit C++ standard in `test_package`

**Pull request closed without merging**
