### PR TITLE
Boost: pass Apple deployment target flag to linker as well + v2 linter changes

### LINKED ISSUE #12328: [package] boost/1.79.0: custom macOS deployment target is not applied
### Package and Environment Details

* Package Name/Version: **boost/1.79.0**
* Operating System+version: **macOS 12.5**
* Compiler+version: **Apple clang 13**
* Conan version: **conan 1.51.3**
* Python version: **Python 3.9.13**

### Conan profile

[settings]
os=Macos
os_build=Macos
os.version=10.13
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

use the following `conanfile.txt`:

```
[requires]
boost/1.79.0

[generators]
CMakeDeps
CMakeToolchain

[options]
boost:shared=True
```

and run `conan install --build=missing`

### Logs

Posting only the relevant bit:
<details><summary>Click to expand log</summary>

```
boost/1.79.0: WARN: b2 -q target-os=darwin architecture=x86 address-model=64 binary-format=mach-o abi=sysv --layout=system --user-config=/Users/kambala/.conan/data/boost/1.79.0/_/_/source/source_subfolder/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=on boost.locale.iconv.lib=libiconv threading=multi visibility=hidden link=shared variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-filesystem --with-iostreams --with-locale --with-log --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure toolset=clang-darwin pch=on -sICONV_PATH=/Users/kambala/.conan/data/libiconv/1.17/_/_/package/695abc271c487ea9fb8409de6f2960c1c0be9cdd linkflags="-stdlib=libc++" cxxflags="-fPIC -stdlib=libc++ -mmacosx-version-min=10.13 -DBOOST_STACKTRACE_ADDR2LINE_LOCATION=/usr/bin/addr2line" install --prefix=/Users/kambala/.conan/data/boost/1.79.0/_/_/package/4ce36ef959ecd1c98e211c772ca31b2a9c9c2e61 -j6 --abbreviate-paths -d0 --debug-configuration --build-dir="/Users/kambala/.conan/data/boost/1.79.0/_/_/build/4ce36ef959ecd1c98e211c772ca31b2a9c9c2e61"
```

</details>

But then I see that 10.13 deployment target wasn't applied (the same for all built Boost libs):

```
> vtool -show-build /Users/kambala/.conan/data/boost/1.79.0/_/_/package/4ce36ef959ecd1c98e211c772ca31b2a9c9c2e61/lib/libboost_locale.dylib
/Users/kambala/.conan/data/boost/1.79.0/_/_/package/4ce36ef959ecd1c98e211c772ca31b2a9c9c2e61/lib/libboost_locale.dylib:
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACOS
    minos 12.0
      sdk 12.3
   ntools 1
     tool LD
  version 764.0
```

Other built libs don't have such issue, for example:

```
> vtool -show-build /Users/kambala/.conan/data/ffmpeg/4.4/_/_/package/ef8e71b8a0af027ee62fc961c8282392ede5f251/lib/libavcodec.58.134.100.dylib
/Users/kambala/.conan/data/ffmpeg/4.4/_/_/package/ef8e71b8a0af027ee62fc961c8282392ede5f251/lib/libavcodec.58.134.100.dylib:
Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 12.3
```

### PR DESCRIPTION
**Pull request by kambala-decapitator**
Otherwise LC_VERSION_MIN_MACOSX / LC_BUILD_VERSION isn't added to dylib. Also slight refactoring: extracted a couple of variables.

Specify library name and version:  **boost/1.79.0**

Fixes #12328

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]

**Comment by SiarheiFedartsou** [comment]
It seems it broke Windows builds 

```
Error loading conanfile at 'C:\Users\runneradmin\.conan\data\boost\1.79.0\_\_\export\conanfile.py': Unable to load conanfile in C:\Users\runneradmin\.conan\data\boost\1.79.0\_\_\export\conanfile.py
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\runneradmin\.conan\data\boost\1.79.0\_\_\export\conanfile.py", line 1, in <module>
    from conan.tools.apple import is_apple_os
ImportError: cannot import name 'is_apple_os' from 'conan.tools.apple' (C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\tools\apple\__init__.py)

Downloading conanfile.py
Downloading conan_export.tgz
boost/1.79.0: Downloaded recipe revision 0
CMake Error at cmake/conan.cmake:540 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:882 (old_conan_cmake_install)
  CMakeLists.txt:498 (conan_cmake_run)
```

**Comment by SiarheiFedartsou** [comment]
There is even note about that by bot:
Screenshot 2022-08-30 at 13 04 44

**Comment by uilianries** [comment]
@SiarheiFedartsou You need to run conan 1.51.3

About the Conan v2 error: It's not ported to Conan beta 2, it will be available on the next beta version

**Comment by bryanjhunt** [comment]
> @SiarheiFedartsou I agree that breaking people is not a good idea, and forced upgrade is bad for many companies. For those cases, Conan Center Index recommends people to use [Lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles/introduction.html) which is a dependencies freeze files, including package revision, so you can be protect by any upstream change.
> 
> Please, read the FAQs which documented your case too: https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#how-to-protect-my-project-from-breaking-changes-in-recipes

We are seeing Windows and Linux builds broken this morning with Conan 1.51.2. 

We are using this older package/revision, as Boost recommends as an option in the FAQ link that you sent out:
boost/1.71.0#60ae8694b11b93d4aced3243705e87b5

image


Why does an older package and revision get updated overnight and break peoples compilations? Im confused how this works...

**Comment by bryanjhunt** [comment]
Wait, just stumbled across this. https://docs.conan.io/en/latest/versioning/revisions.html#how-to-activate-the-revisions Revisions isn't enabled by default, even if you ask for one?

**Comment by prince-chrismc** [comment]
No unfortunately, recipe revisions where an addition during the 1.x development and it would have utterly broken every existing package to set it on by default (since old ones did not have one calculated).

The only saving grace it's going to be enabled for Conan 2.0 but for now you need to make sure it's send in your conf

**Pull request merged**
