### PR TITLE
antlr4-cppruntime: Upgrade to 4.12.0

### PR DESCRIPTION
**Pull request by 0xFireWolf**
Specify library name and version:  **antlr4-cppruntime/4.12.0**

This PR contains the following changes:
- Upgrade the runtime library to 4.12.0.
- Upgrade the receipt to build the shared/static library only instead of both of them as of 4.12.0.
    - Related Issue: https://github.com/antlr/antlr4/issues/3993
    - Related PR: https://github.com/antlr/antlr4/pull/3996
    - Related CMake Options: `ANTLR_BUILD_SHARED` and `ANTLR_BUILD_STATIC`
- Drop the dependency `utfcpp` as of 4.10.0.
    - Related PR: https://github.com/antlr/antlr4/pull/3398
- Bump the dependency `utfcpp` to 3.2.3. 

Thank you.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by michalwidera** [comment]
Hi Eric, I'm gratefull that you take action here and bump 4.12.0 - But Antlr4 has one ugly methodology in their project development - they publish 1.x.0 version then in a few week later - 1.x.1 with bug fixes that is quite stable for some time. I'm Just checking https://github.com/antlr/antlr4/issues - I'm ok with bumping to 1.12.0 but this should be in the back of our heads. I've always wait for 1.x.1 stable version in mine project.

**Review by michalwidera — APPROVED** [review]
LGTM.

**Review by ericLemanissier — APPROVED** [review]

**Comment by michalwidera** [comment]
Look's like https://github.com/conan-io/conan-center-index/pull/16159 have solved conan-v2 issue.
Can we close this dup?

**Review by michalwidera — CHANGES_REQUESTED** [review]
Please sync with https://github.com/conan-io/conan-center-index/pull/16159 and solve V2 build issue or close as DUP

**Comment by 0xFireWolf** [comment]
> Look's like #16159 have solved conan-v2 issue. Can we close this dup?

The V2 pipeline failed because prebuilt package for `utfcpp` is missing, so I don't think it has anything to do with my changes to the recipe. Besides, https://github.com/conan-io/conan-center-index/pull/16159 does not use the new CMake options `ANTLR_BUILD_SHARED` and `ANTLR_BUILD_STATIC` that can reduce the compile time by 50%.

```
======== Installing packages ========
ERROR: Missing binary: utfcpp/3.2.1:da39a3ee5e6b4b0d3255bfef95601890afd80709

utfcpp/3.2.1: WARN: Can't find a 'utfcpp/3.2.1' package binary 'da39a3ee5e6b4b0d3255bfef95601890afd80709' for the configuration:

ERROR: Missing prebuilt package for 'utfcpp/3.2.1'
Check the available packages using 'conan list utfcpp/3.2.1:* -r=remote'
or try to build locally from sources using the '--build=utfcpp/3.2.1' argument
```

**Comment by 0xFireWolf** [comment]
Let me bump the dependency to `utfcpp/3.2.3` to if things still work.

**Comment by 0xFireWolf** [comment]
@SpaceIm Could you please generate the package `utfcpp/3.2.3` which is required by `antlr4-cppruntime/4.9.3`. The V2 pipeline failed because it cannot find prebuilt package on the server. I encountered the same error when I tested the recipe locally without passing the argument `--build missing` to Conan 2.0.2. Thank you in advance.

**Comment by SpaceIm** [comment]
I'm not a team member but a contributor like you, therefore I can't generate these binaries on-demand. You may want to ping @danimtb or @uilianries instead.

**Comment by michalwidera** [comment]
I've ping @uilianries - cause I do not understand why #16159 is passing successfully on V2 pipeline.

**Review by michalwidera — DISMISSED** [review]

**Comment by michalwidera** [comment]
@0xFireWolf - your argument about 50% looks valid for me.
Can you merge your change  ANTLR_BUILD_SHARED and ANTLR_BUILD_STATIC with with @toge PR ?

**Comment by 0xFireWolf** [comment]
> @0xFireWolf - your argument about 50% looks valid for me. Can you merge your change ANTLR_BUILD_SHARED and ANTLR_BUILD_STATIC with with @toge PR ?

I carefully examined @toge's PR, and I believe that his changes to the recipe is a strict subset of mine. In fact, I tried his recipe locally without passing the argument `--build missing` and encountered the same error `ERROR: Missing prebuilt package for 'utfcpp/3.2.1'`. As such, instead of duplicating the effort, I think it's better to wait for the Conan Team to generate the missing package and then merge this PR. I certainly hope that they can do so as soon as possible, because it has been a month since antlr 4.12.0 was released.

**Review by prince-chrismc — DISMISSED** [review]

**Comment by prince-chrismc** [comment]
@jcar87 @uilianries can you please check if those binaries are expected to be missing 🙏

**Comment by 0xFireWolf** [comment]
Any updates from the Conan team? The other PR #16159 was merged a few days ago without passing the V2 pipeline.

**Comment by prince-chrismc** [comment]
There are merge conflicts

**Comment by prince-chrismc** [comment]
Binaries failed to get promoted  https://github.com/conan-io/conan-center-index/pull/15016#issuecomment-1367978126 🤔

**Comment by prince-chrismc** [comment]
> Binaries failed to get promoted [#15016 (comment)](https://github.com/conan-io/conan-center-index/pull/15016#issuecomment-1367978126) 🤔

@jcar87 @uilianries @danimtb can you please take a peak ❤️

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
New version should not need new binaries for 🤞

**Review by SSE4 — APPROVED** [review]

**Comment by prince-chrismc** [comment]
😖 How can binaries exist if the dependency is missing

https://github.com/conan-io/conan-center-index/blob/5660ac5cb35ea05ad69593e9a00078cbdc4aa3c8/.c3i/conan_v2_ready_references.yml#L11

**Comment by 0xFireWolf** [comment]
> 😖 How can binaries exist if the dependency is missing
> 
> https://github.com/conan-io/conan-center-index/blob/5660ac5cb35ea05ad69593e9a00078cbdc4aa3c8/.c3i/conan_v2_ready_references.yml#L11

Probably because the other PR https://github.com/conan-io/conan-center-index/pull/16159 got merged and the one who can update the Ready List decided to add `antlr` to the list. However, `antlr`'s recipe does work with Conan 2.x, because I can build v4.9.3 with the argument `--build missing`. By the way, will the package for `utfcpp` be generated after your PR gets merged or just passes the V2 CI?

**Comment by prince-chrismc** [comment]
Yes! they should abe available now that it's merged so 🤞 everything goes through

**Comment by prince-chrismc** [comment]
V2 passed 🚀

**Comment by prince-chrismc** [comment]
Finally!!!!

**Pull request merged**
