### PR TITLE
Bump eigen in opencv

### PR DESCRIPTION
**Pull request by czoido**
Bump eigen to 3.4.0 to avoid doing overrides

### CODE REVIEW

**Comment by czoido** [comment]
> AFAIK, OpenCV 3.x & 4.x fail to compile against eigen 3.4.0 with several Visual Studio versions. I've already tried last year. See #8868.

Thanks for the reference, let's see what's the build result and if any 4.x version is affected

**Comment by SpaceIm** [comment]
Unexpected error in v2 pipeline. It has been merged before c3i had the time to add opencv to v2 ready references after https://github.com/conan-io/conan-center-index/pull/16678.

**Comment by czoido** [comment]
> Unexpected error in v2 pipeline. It has been merged before c3i had the time to add opencv to v2 ready references after #16678.

Yes, we noticed, thanks for reporting. We have been regenerating packages for OpenCV and should be available soon.

**Comment by db4** [comment]
Hi @czoido,
In the light of https://github.com/conan-io/conan-center-index/issues/18077 don't you think that this PR should be reverted?

**Pull request merged**
