### PR TITLE
ffmpeg: add new version 7.0.1

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **ffmpeg/7.0.1**

https://github.com/FFmpeg/FFmpeg/compare/n6.1...n7.0.1

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
@toge Thank you for updating FFmpeg! I checked the current failure locally I thought it was a bug in ffmpeg, because vvc_mc is indeed a new feature introduced in 7.0. I almost sent a bug report to the project, but when I tried to build directly in my Linux machine (no Docker container), it worked. 

The `yasm` package that we use is 10+ years old and the upstream does not have any update. When building with nasm is working, so I changed the recipe to nasm instead, but only for ffmpeg +7.0.

**Comment by uilianries** [comment]
I'll take a look as it failed only for Conan 1.x. Probably because is building in Debug, the CI only builds in Release for Conan 2.x

**Comment by uilianries** [comment]
The Conan 2.x build log is missing from the comment, but can be found here: 

https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/24249/5/ffmpeg/7.0.1//summary.json

**Review by uilianries — APPROVED** [review]
The version 7.x of ffmpeg looks good at this point. The new module avcodec-vvc is failing to build in debug mode and when using yasm. 

Checking both trac.ffmpeg.org the issue page in Github, I found 3 more reported bugs related this module, so is something that should be improved in the future. 

Release diff: https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/af25a4bfd2503caf3ee485b27b99b620302f5718?hp=e38092ef9395d7049f871ef4d5411eb410e283e0;ds=sidebyside

**Review by AbrilRBS — APPROVED** [review]
Thanks!

**Pull request merged**
