### PR TITLE
Adding protobuf/3.5.1

### PR DESCRIPTION
**Pull request by luizfeldmann**
Specify library name and version:  **protobuf/3.5.1**

This is an older version of the library but it's important to have it here because it's the last one to support C++98.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by lucaskdc** [comment]
Regarding the macOS build failure. It happens because there is not patch to the GID fields in the test_package. Other versions of protobuf received those patches (see [](https://github.com/conan-io/conan-center-index/pull/16453/))

https://github.com/conan-io/conan-center-index/pull/16453/

**Comment by lucaskdc** [comment]
Regarding the macOS build failure. It happens because there is no patch to the GID fields for 3.5.1 in the test_package for this version. Other versions of protobuf received those patches (see the PR https://github.com/conan-io/conan-center-index/pull/16453). That bug is officially fixed since 3.22.0, and probably can be easily be backported to 3.7.1 (using the port_def.inc and port_undef.inc mechanism). 

The reason the mentioned PR give to backport this bugfix to 3.21.12 is to allow the googleapis to use it. See [googleapis conanfile](https://github.com/conan-io/conan-center-index/blob/master/recipes/googleapis/all/conanfile.py).

I suggest to change the test_package to let this bug pass in 3.5.1.

**Comment by uilianries** [comment]
Saudações @luizfeldmann and @lucaskdc I don't recommend skipping the test package, it's important to keep reproducibility and validate the generated package. Instead, I would ask to backport patch if possible. You see, without the test package we can't confirm if that package is really working when distributed.

**Comment by luizfeldmann** [comment]
Running the command `conan create -s build_type=Debug -o protobuf:shared=True -tf test_v1_package . protobuf/3.5.1@ --build=missing` I was able to reproduce the error:

```
dyld[13117]: Library not loaded: 'libprotocd.dylib'
  Referenced from: '/Users/jenkins/w/prod-v1/bsr@3/36213/dccff/.conan/data/protobuf/3.5.1/_/_/package/6ba6920b22b03a7cda05599853afac26e7fdfce2/bin/protoc'
  Reason: tried: 'libprotocd.dylib' (no such file), '/usr/local/lib/libprotocd.dylib' (no such file), '/usr/lib/libprotocd.dylib' (no such file), '/Users/jenkins/w/prod-v1/bsr@3/cci-a6bfc911/recipes/protobuf/all/test_v1_package/build/9be9c4d74b252db4497c80d51dbbc27e25fa4789/test_package/libprotocd.dylib'
```

As I'm not familiar with macOS, I'm assuming it's related to `@rpath` warning produced by the [hook](https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H077).

@uilianries Do you maybe have any comments ?

**Comment by luizfeldmann** [comment]
This [PR](https://github.com/protocolbuffers/protobuf/pull/4620) seems to address this issue.

**Comment by luizfeldmann** [comment]
New issue related to source file generated at build-time, see:
https://github.com/protocolbuffers/protobuf/pull/4694
https://github.com/protocolbuffers/protobuf/issues/4704

The build process generates a custom executable `js_embed` which in turn generates the file `src/google/protobuf/compiler/js/well_known_types_embed.cc` before the build can continue.

This method seems to break cross-compilations and because the host cannot run this executable (which is built for the cross compilation target and not for the host architecture).

This [PR](https://github.com/protocolbuffers/protobuf/pull/4709) later resolved the issues by completely removing this step and instead having this file being part of the source instead of auto-generated.

**Comment by luizfeldmann** [comment]
Let's try to backport these patches into the upstream:
https://github.com/protocolbuffers/protobuf/pull/14644
https://github.com/protocolbuffers/protobuf/pull/14641

**Comment by jcar87** [comment]
Hi @luizfeldmann - thank you for your contribution.

unforunately as you have seen - this is too old a version (2017) and keeping it working for newer systems and compilers is too much effort - this wouldn't be `3.5.1`, this would be 3.5.1 with a series of backports. It's also telling that protobuf themselves have not paid https://github.com/protocolbuffers/protobuf/pull/14644 or https://github.com/protocolbuffers/protobuf/pull/14641 much attention.

Accepting this would impose too high a maintenance burden for us. 

I appreciate this is a common use case that in certain users need to stay on too-old versions of certification purposes - that is why we have a variety of strategies for users to maintain their own versions of recipes:
* https://docs.conan.io/2/devops/using_conancenter.html#control-and-customization
* https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires
* https://docs.conan.io/2/tutorial/conan_repositories/setup_local_recipes_index.html

**Pull request closed without merging**
