### PR TITLE
[qt6] sort build_modules

### PR DESCRIPTION
**Pull request by fdgStilla**
Fix https://github.com/conan-io/conan-center-index/issues/13760

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by fdgStilla** [comment]
> Thanks for the contribution. the fact that alphabetical order "happens to work" is just out of luck right ? It may break other modules (for examples qt3d, qt5compat and qtactiveqt are placed alphabetically before qtbase, but they do require qtbase) The true solution would be to order them according to the dependency chain between components, but I'm not sure how to do this properly.

I agree with you but I do not know how to do this properly either

**Comment by ericLemanissier** [comment]
Ok, so I'm trying to do it correctly in https://github.com/conan-io/conan-center-index/pull/12906/commits/62bebd617adade6c99957323efac82892695ed85

**Comment by ericLemanissier** [comment]
@fdgStilla can you try with https://github.com/conan-io/conan-center-index/pull/12906 ? If it works for you, then you can close this PR

**Comment by prince-chrismc** [comment]
Bump :)

**Pull request closed without merging**
